### ISSUE TITLE
Windows Defender flags ZoeyBoy file as Trojan

### ISSUE THREAD

**Issue by granblue5eva** [Masuzu/ZooeyBot#10]
Following item was flagged by Windows Defender as a Trojan virus:

containerfile:E:\zooey-bot-v1.0.0.zip
file:E:\zooey-bot-v1.0.0.zip->zooey-bot-v1.0.0/zooey-bot-extension/background.js
webfile:E:\zooey-bot-v1.0.0.zip|https://dl.dropboxusercontent.com/content_link/F13KRt9kh900J3QE91KArCEdfMNMkbusCDaLTcyd4xB2jGqqXPJOxBIhWsuwsyml/file?dl=1|chrome.exe

Entry on Windows Malware Encyclopedia:

https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aJS%2fJorv.A!cl&threatid=2147717644&enterprise=0

**Comment by Masuzu** [comment]
False positive and similar to https://github.com/Masuzu/GBFPokerBot/issues/79
