### ISSUE TITLE
Cinderella Quest Faming.

### ISSUE THREAD

**Issue by arthurneo** [Masuzu/ZooeyBot#100]
Hi Just a quick question.

I'm trying zooey bot for the first time. 
I managed to get it to select the extreme battle  and it does the whole Battle 1.
When the battle ends, it tries to go to a result page, where sometimes it tries to reload the select summon, or it just freezes 

![zooey](https://user-images.githubusercontent.com/29359181/27014268-1460c06e-4ebb-11e7-9e5d-96b77e3fe1eb.JPG)

 I have activated event mode, or am I supposed not to activate it for cinderella?

Any help would be greatly appreciated.

**Comment by Masuzu** [comment]
Hi,
It looks like you have a pretty bad ping since you should not see the "no response after pressing... " after using attacks and without using any skills between. With a stable 200 ms ping I never encounter this issue. Having a stable ping is a requirement.
