### ISSUE TITLE
Treasure mode on Second Avent  summon select stuck

### ISSUE THREAD

**Issue by yuzurihaz** [Masuzu/ZooeyBot#1000]
i try to farm Ex mode that require  3 moon files(items) it nevigate me to summon select but it dont select any summon. this is my treasure event mode script in Zoeybot.ini

[TreasureEventMode]
Enabled=true
TreasureEventUrl=http://game.granbluefantasy.jp/#quest/supporter/737001/1/0/10302
Difficulty=ex
ActionPointCost=30
TreasureEventModeScript=event.lua

**Comment by gaojianj96** [comment]
TreasureEventUrl=TreasureEventUrl=http://game.granbluefantasy.jp/#event/treasureraid076

**Comment by gaojianj96** [comment]
My treasure mode also stuck but it is after summon select. It would stuck after Combat mode active no matter which mode it is (ex/impossible). I am sure my script location and syntax is correct. EventMode one is working when enabled.


```
[EventMode]
Enabled=false
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/736991/1
EventRaidScript=Scripts/event201901EX.lua
NightmareModeUrl=http://game.granbluefantasy.jp/#quest/supporter/737021/3
EventPageUrl=
NightmareModePreferredSummons=Bahamut_2,Celeste Omega_2,Bahamut_1,Celeste Omega_1,Bahamut,Celeste Omega

[TreasureEventMode]
Enabled=true
TreasureEventUrl=http://game.granbluefantasy.jp/#event/treasureraid076
Difficulty=ex
ActionPointCost=30
TreasureEventModeScript=Scripts/event201901EX.lua

```

![l_7d9zo g1ucxswvmc zu7](https://user-images.githubusercontent.com/25236171/50618105-bbde6480-0ebe-11e9-88f3-00edad89a4d9.png)

**Comment by pakulu** [comment]
I've had the same issue before and found a "way" to work around it.
If you create a custom schedule for that raid, the bot will execute it without any problems.
I do not know how to add NM procs to the custom schedules tho, so it becomes a bit innefficient at times if you really care about the amount of pots you use.
![image](https://user-images.githubusercontent.com/44754208/50731115-2ca2ac80-115d-11e9-9c9a-1760d2fc6c72.png)
It's extremely rudimentary from last event but it helped me get some boxes done while i was busy.
I do wish we had some input in this issue, or at least how to add nightmare to the schedule :^)

**Comment by DarkHorse1121** [comment]
@Masuzu 

I usualy concern that it is better to improve treasure event mode like as followings.
- Add event url and script parameter in order to collect meats.
  (Add meats counts parameter.)
- If fill meats counts, do treasure event url quest.
  (Already exsits, select ex+, hell, hell90, hell95, hell100)

This improvement also be useful for guild war.
I hope you to concern as enhancement issue.

Thanks,

**Comment by Ohwhat00** [comment]
> I've had the same issue before and found a "way" to work around it.
> If you create a custom schedule for that raid, the bot will execute it without any problems.
> I do not know how to add NM procs to the custom schedules tho, so it becomes a bit innefficient at times if you really care about the amount of pots you use.
> ![image](https://user-images.githubusercontent.com/44754208/50731115-2ca2ac80-115d-11e9-9c9a-1760d2fc6c72.png)
> It's extremely rudimentary from last event but it helped me get some boxes done while i was busy.
> I do wish we had some input in this issue, or at least how to add nightmare to the schedule :^)

Thanks for this temporary workaround!
