### ISSUE TITLE
I/O in lua scripts

### ISSUE THREAD

**Issue by Antialiased** [Masuzu/ZooeyBot#1001]
It would be very useful to be able to printf / fread / fwrite from scripts, for instance to debug complex logic or to maintain a record of which steps in a schedule have been completed so that the schedule can be resumed if zooey crashes. At the moment using print statements prints garbage and crashes the bot.

**Comment by Masuzu** [comment]
The function print was now fixed in Lua scripts. I assume that anyone who would need that kind of feature can run the script from a powershell CLI, which makes redirecting the output of the console to a file possible that way.

**Comment by Antialiased** [comment]
yeah that's fine, I can work around not being able to read files
