### ISSUE TITLE
Is there a way to use Eustace (Dark) 1st skill with the bot?

### ISSUE THREAD

**Issue by omieqqe** [Masuzu/ZooeyBot#1002]
Hello sir,

I got a little problem with my script for using Eustace Splinter cell skill. The thing is he need to be 3 stacks so i can OTK the GW meat mob.

I tried to reference by the example in the LUA SCRIPT wiki (Hound dog swap) but it's only for use swap with MC and Diantha (1st position and 1 position).

I'm abit out of the way now since i'm not a pro writer script. If anyone can share the way to make the bot click Splinter cell and Click on the character (Whoever). I'm very thank you so much.

Have a nice day. 
Thank you.

**Comment by zappky** [comment]
You are on the right track, it is the same as NH swap code.

**Comment by omieqqe** [comment]
> You are on the right track, it is the same as NH swap code.
> 
> I did this
> characters["Eustace"]:OnPartyMember(1):UseSkill(1)

Oh. That's why!
Thank you so much >_<
