### ISSUE TITLE
Payment processing for 3 days

### ISSUE THREAD

**Issue by aquatakashi** [Masuzu/ZooeyBot#1003]
Hello - I paid for a month of your service a few days ago and it says the payment is still processing, but the money has come out of my account instantly. Is there anything I can do?

**Comment by Masuzu** [comment]
Updates were released to recover lost transactions in the future and should be effective right now in your particular case. Please follow up in a private mail to support@azuriteworlds.com if you would like me make amendments for your case, from refunds to licence extensions. Thank you again!
