### ISSUE TITLE
can not connect to the manager counter page

### ISSUE THREAD

**Issue by autogfwar** [Masuzu/ZooeyBot#1007]
It looks like the same event
Cant boot zooey bot and access Manage account page. #1005

I already purchased licence (Auto Upgrade with paypal)
but can't access my account page.

please help.

**Comment by autogfwar** [comment]
In this state zooeybot will not work, please help me

**Comment by autogfwar** [comment]
When you create a new account you will see the manage account page.
It seems to be caused by the license AutoUpdate.
Switching account does not display manage account page.
Please help me as soon as possible.

**Comment by Masuzu** [comment]
Hello,
I am looking into it at the moment, it seems like a critical issue.

**Comment by Masuzu** [comment]
This is now resolved.
