### ISSUE TITLE
Is it me or the bot can automatically fill the captcha?

### ISSUE THREAD

**Issue by omieqqe** [Masuzu/ZooeyBot#1009]
Hi there it's GW times, also Bot hunting time.

I heared the sound warning for captcha then i press F1 to stop bot immediately and fill the captcha. But none of captcha has been see in the screen.

I though the bot just went crazy when my company computer is going too slow.

I go back to home menu and check inside the crate for some Gold moons and surprise! There is some rupies they gave you when you complete the captcha.

Any though?

Thank you and have a nice Guild war <3 

![image](https://user-images.githubusercontent.com/45419353/51374907-ad21bf80-1b04-11e9-9668-da8ecb241faa.png)

**Comment by Hexadecimalism** [comment]
That's for providing support to other players, aka people borrowing your summons. Captcha completion is only ever 100 rupies.
