### ISSUE TITLE
slave mode "Next" Button

### ISSUE THREAD

**Issue by Dreamfinal** [Masuzu/ZooeyBot#101]
Hi guys!
Recently I spot an issue in the bot program. I would like to share this matter with you.
When I played 2 accounts in the co-op Mode, the program didn't continue to loop the cycle. I've tried many ways to figure the source of problem until I found out that it is the detection process of the main account. 

Here is the situation: the slave account delivers last movement and kills the monster. The 'next' buttons appear on both screens. When it's the main's turn, the monster has already died and the script signifies that it is waiting for the attack button which is now gone. Thus, the bot cannot complete its process and the game becomes dormant.

There is no such problem if the main account do the last damage or be the last to kill the monster. It's working really fine unless the slave eliminates the target. I've been observing and testing until I am certain of this conclusion.

Could you please help me with this issue? I look foward to the better solution. Thanks for your time and support.

P.S. I am currently using ver 1.9.7

**Comment by Masuzu** [comment]
Hi @Dreamfinal ,

I acknowledged the request but I have no guarantee to provide a fix by the end of the month.

**Comment by Masuzu** [comment]
Fixed in version 1.9.8
