### ISSUE TITLE
Use skills according to support summon

### ISSUE THREAD

**Issue by AtGod1711** [Masuzu/ZooeyBot#1012]
So I use the classic kengo bonito to OTK EX+.  I need 3 buttons if I can get a FLB Levi, but 4 buttons if i only get a MLB Levi. Is it possible to write a conditional command that determine whether the supp summon is FLB or not, then decide whether or not to use the extra button. What I want is something like this:

If Summon(6) == MLB Leviathan:
use extra nuke
Else:
do nothing

What would be the correct script syntax?

Alternatively, I can reroll until FLB Levi but it would be terribly inefficient in terms of time. I can also set the script to do 4 buttons regardless of MLB or FLB, but it would also not be optimal. So I just wonder whether i can do something like mentioned above.

**Comment by Masuzu** [comment]
A new variable was added in v3.5.0 for this purpose: `friend_summon_evolution`.
