### ISSUE TITLE
Is there anyway to refresh page after the GW95 Boss is dead?

### ISSUE THREAD

**Issue by GBFUSER1993** [Masuzu/ZooeyBot#1013]
As mentioned above, I can't solo GW95 boss, so I need to use the backup request. However, I will attack the boss until my whole team fall. And the boss will most likely be killed by my crew members after my whole team fall, which makes the bot stuck. So I was thinking is there anyway I can refresh the page after my whole team fell, so I can automatically start the next raid?

**Comment by gold-nugget** [comment]
if you have an idea at how fast they can burn it
Wait(XXX)
Refresh ()

can't really say if it works or not, so let us know

**Comment by Masuzu** [comment]
That is close to paranoia, I would not worry that much about this. You can use `60*math.random()` in your script to generate a random number between 0 and 59 for instance.
