### ISSUE TITLE
Serial Number Problem

### ISSUE THREAD

**Issue by Sumonner** [Masuzu/ZooeyBot#1015]
I created my first account to use the bot, but it didn't got any email message, so I created another one... so it looks like I can't use the same serial code for both, and it is making me not be able to use the bot... how can I solve this?

**Comment by Masuzu** [comment]
Hello,
Did you check the spam folder?
Otherwise, if the provided email was not correct in the first place, please could you provide that first email so I can delete the associated account?

**Comment by Sumonner** [comment]
Already checked the spam and the trash can, nothing

**Comment by Sumonner** [comment]
I can't confirm or change the password of the first account... so yeah, I can't use the bots because of it too

**Comment by Masuzu** [comment]
Then please provide the mail of that account so that the corresponding account can be deleted.

**Comment by Sumonner** [comment]
lucasestudigio@gmail.com

**Comment by Masuzu** [comment]
Ah, that solves the issue then! There are no users with that email currently registered.

**Comment by Sumonner** [comment]
So why it says my serial number is already in use?

"Name 2ad94a598fa9621fce64de9c7e52e5a1f1b9d9b618ccf78eeaebb62357c9804452c3bb9773419e50d995d98f338af0099745ede78a384e6469b87dfcca123c57 is already taken."

I mean, the zooey bot is locked in this serial code, and I can't use this code because it says is already in use.

**Comment by Sumonner** [comment]
Oh... I see now, the email is wrong, it is lucasetudigio@gmail.com .... type error, can you delete this one? I saw my email recover just now
