### ISSUE TITLE
Can't start bot 

### ISSUE THREAD

**Issue by nut11443366** [Masuzu/ZooeyBot#1017]
I was trying to start zooeybot, displayed as popup "Unregisterd user "
I can used until I updated my graphic card software (I don't think this is a cause)

ps. I did checked my serial number already it still be the old one that I always used it 

this is my pic and the error code https://imgur.com/a/MmnuXpy

**Comment by Masuzu** [comment]
Hello,
This is invariably due to a change in serial number. Chech the contents of the serial_number.txt file, as described is in https://github.com/Masuzu/ZooeyBot/wiki/FAQ
