### ISSUE TITLE
Script being ignored and zooey wont even attack?

### ISSUE THREAD

**Issue by PrinzVelvet** [Masuzu/ZooeyBot#1021]
I am using a very simple code for ROTB but everytime I open zooey it selects my summon and then just does nothing else. Zooey's cmd has no errors or anything it just refuses to do anything

`if turn == 1 then

character_2:UseSkill(3) 
character_2:UseSkill(2) 
character_2:UseSkill(1) 
character_1:UseSkill(1) 
character_1:UseSkill(2) 
character_1:UseSkill(3) 
Summon(1) 
end`

`[EventMode]
Enabled=true
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/711191/1
EventRaidScript=Scripts/zhuque.lua
NightmareModeUrl=
NightmareModeScript=
EventPageUrl=http://game.granbluefantasy.jp/#event/advent
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode is set to true.
NightmareModePreferredSummons=leviathan omega
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=false
WaitTimeInMsAfterEventPageIsLoaded=1000`

**Comment by Masuzu** [comment]
Hello,
At each turn there is a message saying the path of the script which tries to be loaded, so you will know immediately if one is loaded or not.

**Comment by PrinzVelvet** [comment]
I am not getting that message it tells me about the party selection lua but then it never loads a script despite the path being correct and name of the script is correct

**Comment by xerance** [comment]
I have the same issue vs lumi

**Comment by Kokkujin** [comment]
I am having the same exact issue, it says combat mode activated then a while the page is loading up it just doesnt move
