### ISSUE TITLE
Zooey Crashing on Windows Server 2016

### ISSUE THREAD

**Issue by kiaben** [Masuzu/ZooeyBot#1023]
Hi,

for various reasons I am trying to run Zooey on Windows Server 2016. I can start it and after installing Visual C++ Redistributable for Visual Studio 2015 it doesn't display missing DLL errors anymore.

However after clicking the licence window I it immediately crashes. If I look in the event viewer I can see it that an access violation with Exception code: 0xc0000005 happens.

Any ideas what I the cause of the issue is?

Thank You

**Comment by Masuzu** [comment]
Hello,
I will try and reproduce the issue on a Google cloud VM later on.

**Comment by kiaben** [comment]
> 
> 
> Hello,
> I will try and reproduce the issue on a Google cloud VM later on.

Hey, any news?

Thank You

**Comment by kiaben** [comment]
> 
> 
> Hello,
> I will try and reproduce the issue on a Google cloud VM later on.

Still trying to make it work on my end, did you have time to look into it?

**Comment by kiaben** [comment]
Still waiting on this, would be nice if you could take a look.
