### ISSUE TITLE
New update broke Zooey Bot

### ISSUE THREAD

**Issue by FatherOJ** [Masuzu/ZooeyBot#1024]
Seems like the new update broke Zooey Bot. Does not work in both regular and event mode. Everything seems normal  until I press the quest button, then it says "successfully hooked to the home button" and "zooey bot initialized." then nothing can be done from here on.

**Comment by Alaric323** [comment]
Ditto, stalling at Zooeybot Initialized, stays at quest screen.

**Comment by Alaric323** [comment]
Indeed, this issue is fixed with 3.6

**Comment by Masuzu** [comment]
An updated version was released. Let me know in another issue thread if you find out other bugs. Thank you. So far quest costs are not retrieved in certain cases.
