### ISSUE TITLE
Seems like I can no longer refill ap/ep with zoibot after update

### ISSUE THREAD

**Issue by xerance** [Masuzu/ZooeyBot#1025]
title, also noticing it being broken with viramate

**Comment by ErogeSeiyuu** [comment]
zoibot can't refill but viramate still can tho

**Comment by rockysilver** [comment]
Same problem here, still work on viramate tho.

**Comment by Alaric323** [comment]
Update 3.6.0 did NOT fix the refilling bug.

**Comment by Masuzu** [comment]
Thank you for reporting the issue with quest costs not being retrieved.

**Comment by giauten** [comment]
this issue also occurs in version 3.5.1

**Comment by Jinko78** [comment]
If you set up a scheduled event like megablues suggests aboved you can circumvent this issue, at least until it's fixed.

**Comment by Masuzu** [comment]
The question action point cost always being 0 is now fixed in v3.6.1!
