### ISSUE TITLE
Co-op Problem? "Failed to detect the Twitter side menu" and Ap problem

### ISSUE THREAD

**Issue by Chololoco13** [Masuzu/ZooeyBot#1026]
I'm trying to play in slavemode.
the bot says the following problem. The problem starts after pressing the Enter key to start bot
I am using the version 3.6.0, this problem had not happened to me with the previous versions.
Will it be a problem for the last update of the game?
Anyone else with that problem?
![zooeybot_e6c1xttake](https://user-images.githubusercontent.com/25869534/51956984-663e9e80-240f-11e9-8a6b-f385484a623a.png)

**Comment by gold-nugget** [comment]
Try opening the app on home page. 
And/or refreshing network side menu

**Comment by Chololoco13** [comment]
Problem solved.
I had to restart my computer and it worked again.
Now I have another problem, the bot recharges ap in both accounts. Main and slave accounts
![chrome_3wisqvofes](https://user-images.githubusercontent.com/25869534/51994259-07604000-2476-11e9-9afa-db27e2c8e12c.png)
![chrome_jo1lny2xqi](https://user-images.githubusercontent.com/25869534/51994301-13e49880-2476-11e9-974b-852e24f3ec24.png)

**Comment by Chololoco13** [comment]
Zooey bot 3.6.1 version.
the problem continues, bot recharges ap in both accounts. 
![chrome_cc354t7tfv](https://user-images.githubusercontent.com/25869534/52017984-95581d00-24ae-11e9-956c-c6134efd0bae.png)
![chrome_irnhuakf2n](https://user-images.githubusercontent.com/25869534/52017991-99843a80-24ae-11e9-9157-41812459acd1.png)

**Comment by Masuzu** [comment]
Hello,
This is discussed here https://github.com/Masuzu/ZooeyBot/wiki/FAQ#failed-to-detect-the-twitter-side-menu
