### ISSUE TITLE
Slave mode not starting

### ISSUE THREAD

**Issue by vash9177** [Masuzu/ZooeyBot#1028]
I've run the steps for slave slime blasting and i get to the point where it connects to the home button and then says calibrating but then the bot just sits there.

Current version of Zooey 3.6.1 and chrome  Version 72.0.3626.81(64 bit).
I've tried starting the slave first and then the main account and vice-versa and have tried restarting zooey with the devtools closed and then opening them just before activation beatrix and zooey

**Comment by Masuzu** [comment]
Hello,
I have updated the FAQ section: https://github.com/Masuzu/ZooeyBot/wiki/FAQ#zooey-is-stuck-during-the-calibration-phase
but will give it a try. Nothing changed as far as I remember.

**Comment by vash9177** [comment]
That was it didnt realize incognito was in lite settings, thanks

**Comment by RaiModels** [comment]
Hello I am having the same issue even though my incognito mode account also has standard graphics. Am on Chromium Version 72.0.3626.81 (Official Build) (64-bit)
