### ISSUE TITLE
Bug that causes co-op bot to stop with "Something went terribly wrong while trying to set the quest" notification

### ISSUE THREAD

**Issue by kommtodd** [Masuzu/ZooeyBot#103]
![screenshot_28](https://user-images.githubusercontent.com/29377321/27037874-e2bfc0d0-4fbb-11e7-92a0-076ed5d14b95.jpg)

appears to be a problem with the slave account starting the quest after a few rounds. the longest i've been able to run the bot was around 10 minutes before encountering this problem.

looks like the slave account trying to set the quest when the quest has already been set?

**Comment by Masuzu** [comment]
Acknowledged as bug.

**Comment by Masuzu** [comment]
Fixed in version 1.9.8
