### ISSUE TITLE
Bot stops after using one skill

### ISSUE THREAD

**Issue by Santheron** [Masuzu/ZooeyBot#1035]
![image](https://user-images.githubusercontent.com/40581698/52160789-9a68c800-2678-11e9-86bf-056d0049ce72.png)

After one skill the bot just freezes at this point, I have tried increasing MinWaitTime values, but still does not work. This is my current LUA code.

![image](https://user-images.githubusercontent.com/40581698/52160815-2844b300-2679-11e9-8496-e59259e4ad42.png)

**Comment by ngocin** [comment]
Do you use viramate ? if yes, untick the last option here
![image](https://user-images.githubusercontent.com/30687323/52164070-208b1a00-271e-11e9-93cb-542d52616174.png)
