### ISSUE TITLE
Bot using pots on main account whilest in slave mode

### ISSUE THREAD

**Issue by SunStrider8420** [Masuzu/ZooeyBot#1037]
Hi, I noticed that it was spending pots on my main account even though it was running in slave mode sliming.
Is this a bug, or is there something I need to turn off?

**Comment by Chololoco13** [comment]
same problem

**Comment by moonlee7777** [comment]
Same problem here.

**Comment by Einhalkzt** [comment]
my problem is that the slave cant even refill it's ap, stuck on "use pot window" that pops when ap ran out, have to manually click how many pot to use for it to continue

**Comment by Rkdheishins** [comment]
yea im updated to 3.6.2 and im still having this problem, I made sure to remove and reenable both extensions to make sure im doing it right and its still using pots on my main account :(

**Comment by SunStrider8420** [comment]
Creator has been releasing bug fixes for other issues, but he hasn't even replied to this to confirm he's looking into it.

**Comment by SunStrider8420** [comment]
It's been 2 months since this was raised, and another separate thread has been made.
@Masuzu can you at least acknowledge this is a bug, or give us a sign you're looking into this?
