### ISSUE TITLE
Skill 1 Failure

### ISSUE THREAD

**Issue by MegaBlues** [Masuzu/ZooeyBot#1039]
Sometimes, when using Skill 1, the bot will not use it and cause Zooeybot to hang. Other times, the bot will use it, but it won't be recognized. The bot will then attempt to use the skill again while it is on cooldown, and will hang. Also, to preempt, 

I suspect there's some flaw with how the Viramate workaround for Skill 1 interacts with MaxNumActionRetries, but that's just a guess. Highlighting quick panels is disabled.

**Comment by Masuzu** [comment]
Hello,
You may need to set EnableEarlyTurnStartWithViramate to false to prevent using skills too early.

**Comment by MegaBlues** [comment]
It was disabled when I had the issue, but I'll take a screenshot of the cmd window logs if I run into the issue again.
