### ISSUE TITLE
Zooey bot initialization error

### ISSUE THREAD

**Issue by Garnetus** [Masuzu/ZooeyBot#104]
It says slave mode expects 2 granblue fantasy active windows to be found, yet I have two windows open and it worked before...
I have no idea what's the cause, I did try redownload program/reboot system but the issue remains.

PS: Just a follow up, now it says no active window with granblue fantasy was found

**Comment by Masuzu** [comment]
Please. Check the language settings and that no other windows beginning with Granblue Fantasy is active.
I can guarantee that there is absolutely no issue with this part of Zooey Bot.
