### ISSUE TITLE
Zooey bot stuck at initialized

### ISSUE THREAD

**Issue by zimzok** [Masuzu/ZooeyBot#1040]
Bot shows:
Calibrating
Successfully hooked to the Home Page
Zooey bot initialized. 
![capture](https://user-images.githubusercontent.com/47345248/52256031-b35acd00-2947-11e9-9994-919840ce15cd.PNG)
I reinstalled chrome and opened only game tab but it couldnt solve

**Comment by iSDestiny** [comment]
I'm having the same problem

**Comment by Masuzu** [comment]
Hello,
I regret but to tell you that both of those exceptions are unrelated whatsoever to ZooeyBot if you use the latest version (make sure you use the latest extension).
