### ISSUE TITLE
proving grounds can't refile AP

### ISSUE THREAD

**Issue by matp07289** [Masuzu/ZooeyBot#1043]
stop proving grounds menu

**Comment by DarkHorse1121** [comment]
I am also faced same problem.

**Comment by Jinko78** [comment]
Have you changed the amount of AP under TreasurEventMode ? in the ini

I'm not getting any issue with AP refill but the bot does crash after the first fight and tries to select the second team.

**Comment by DarkHorse1121** [comment]
@Jinko78 
Sorry, my mistaking the report.
I also face like your problem.
Suddenly stop and couldn't start second battle.
Zooeybot was crashed.

**Comment by GranblueOjisan** [comment]
yes its known issue, we have to wait for fix
https://github.com/Masuzu/ZooeyBot/issues/967

**Comment by Masuzu** [comment]
Hello all,
You will find here guidelines to automate the current Proving Grounds event: https://github.com/Masuzu/ZooeyBot/issues/1044
Happy farming!
