### ISSUE TITLE
Zooey not autopiloting

### ISSUE THREAD

**Issue by kirie7** [Masuzu/ZooeyBot#1046]
After i picked my favorite quest, zooey did not go to autopilot mode in the select summon screen. I waited for a while, nothing happened as well.

**Comment by zappky** [comment]
Does restarting the bot helps??

Otherwise, just use eventmode or custom schedule.

**Comment by Masuzu** [comment]
Hello,
Fully supported favorite quests include story and free quests. Raids and event quests should use the event more
