### ISSUE TITLE
Summon reroll bug

### ISSUE THREAD

**Issue by ErogeSeiyuu** [Masuzu/ZooeyBot#1047]
Got the same issue as previously closed bug report:

https://github.com/Masuzu/ZooeyBot/issues/607

https://github.com/Masuzu/ZooeyBot/issues/422

Zoibot would go to trial battle, click on a random fire support summon. Instead of clicking the Go button afterwards, it refresh loops for about 5 times and then play captcha sound before crashing.

**Comment by Masuzu** [comment]
Hello, is this really the case, which mode are you using?
All the time, after selecting a random summon and starting the trial battle, Zooey navigates to the quest page then proceeds to retreat from the trial battle. If after entering the trial battle mode you do not manage to navigate to the quest menu that is worrying.

**Comment by appleloli** [comment]
Can confirm this happening

![image](https://user-images.githubusercontent.com/35543465/52682206-c2b6c780-2f92-11e9-9c38-3641195bec64.png)

**Comment by ErogeSeiyuu** [comment]
It was Treasured Event + Proving Ground mode. Rolling back to previous version makes Zoibot crash when doing Proving Grounds Ex+ since my backline are light metera and alex. 

Zoi bot would:

1. Load proving ground quest
2. Can't find Shiva
3. Go to trial battle summon select page
4. Click on a random fire summon
5. Hover mouse over the OK button
6. Get stuck there for around 5 seconds before refresh loops as seen in appleloli's comment above. i.e. a mix of #607 and #422
