### ISSUE TITLE
Probable problem with ZooeyBot/SarasaBot authentication server

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/ZooeyBot#1049]
Hi, since yesterday I have hard time launching the ZooeyBot/SarasaBot. Sometimes the version checker doesn't popped up, then the bot crashes. Other times it stuck before the 'time remaining pop up'. Then even after those two, the bot often crashes before showing up "Please go to quest".
At first I thought it was my connection problem, but I can play gbf fine or just use the internet in general without problem. Just the bots.

**Comment by zappky** [comment]
As for the first part,where the version checker and License Info doesnt pop up and got stuck. These sometimes do occurs,but it is seldom. It is there for a long time already.
I usually just restarts the bot and it starts up fine.

I didnt encounter the others tho.

**Comment by Masuzu** [comment]
Such errors are rare indeed.
