### ISSUE TITLE
stuck on using skill while silenced

### ISSUE THREAD

**Issue by Einhalkzt** [Masuzu/ZooeyBot#105]
it the boss cast silence/stone, the bot will still keep on trying to use skill, causing it to stuck
or is there any method i can used to avoid this in the script?

**Comment by Masuzu** [comment]
I took note of this.
If I remember correctly, the bot will try to reuse the same skill up to MaxNumActionRetries.
Not the optimal case, but this could be solved by taking into account current character debuffs.
To fix/improve later.
