### ISSUE TITLE
Always turn 1

### ISSUE THREAD

**Issue by Koraxor** [Masuzu/ZooeyBot#1054]
I noticed none of my turn == worked, and I noticed the console always says Battle 1 Turn 1 (haven't done any multi battles since so can't confirm if battles isn't working either). Not sure if this is on my end or not.

**Comment by SchismEternel** [comment]
Same problem. As a result any instructions supposed to apply after turn 1 are no longer taken into consideration.

**Comment by granblue5eva** [comment]
Surprised not more people mentioning this during GW, just ran into the issue as I was previously only farming meat.

**Comment by Masuzu** [comment]
I guess that is when the page is not refreshed each turn? I will test in trial battles.

**Comment by Koraxor** [comment]
I actually tried with it refreshing each turn and it still stayed as turn 1, but I do normally play with no refresh.

**Comment by sam-f-owens** [comment]
Hey guys, I've been working with this for a while. Here's a dumb but working fix until it gets actually fixed. 

In your turn 1 if block use this
`if turn == 1 and numbers["turn_fix"] == nil then
  numbers["turn_fix"] = 1
  --whatever you do
end`

Then for every subsequent turn you do stuff on, head the if block with 
  `if turn == 2 or numbers["turn_fix"] == 2 then`
where 2 is whatever turn it actually is and then at the end of your .lua put the line
  `numbers["turn_fix"] = numbers["turn_fix"]+1`

It should only initialize to 1 on the first actual turn, then run through checking everything against turn_fix , then increment at the end. 

I guess you could replace the if turn == whatever part entirely, but I like to leave that in so I can delete the fix stuff later when it gets fixed.

**Comment by Masuzu** [comment]
Still wracking my brain surgery on this one. When my game reloads after each turn I always get the turn incremented correctly (also the turn is incremented properly in raids such as Akasha).
