### ISSUE TITLE
Any support for Google VM?

### ISSUE THREAD

**Issue by csyeul** [Masuzu/ZooeyBot#1055]
https://github.com/Masuzu/ZooeyBot/issues/1023

I see it has been mentioned in this thread. 
I also use this too because it allows you to have JP ping anywhere you are. 
@Masuzu If you're having trouble setting it up, the link is this https://www.reddit.com/r/Granblue_en/comments/8j1uhp/visual_guide_to_lowlag_granblue_using_windows/

it gives an in-depth and easy guide on setting it up.

I'd really like this compatibility to happen because I can just slot in my bot in here and do something else on my pc. It's worth mentioning that your Serial Generator doesn't work in Windows server 2016 either. Not sure why though.

I know not a lot of your bot user's population use this but few of us that do would really appreciate it. Please make this happen.

**Comment by edgyboi** [comment]
I have the same issue as well, cannot get the serial number when using google VM

**Comment by kiaben** [comment]
So I am not the only one, this would really be great since some people are stuck with terrible pings on their normal connection.

**Comment by Masuzu** [comment]
Hello,
Short answer, it does not work for now for Google VMs but I am really short on time lately. I would like to do something about it as for competitive players the benefits of playing with near instant reloads are huge.

**Comment by Masuzu** [comment]
Quick update: you should be able to run Zooey Bot, Sarasa Bot, the Poker Bot and the GBF Combat Sniffer on a Google Cloud machine without any GPU (a Windows Server 2016 image with a desktop GUI was used). A GPU is not required at all when using a single window and won't be detrimental whatsoever regarding the experience - FPS will still be choppy but it is not what matters in this case.
![image](https://user-images.githubusercontent.com/5464705/54157890-2cff4280-4441-11e9-93ad-1cc9badc6475.png)

**Comment by kiaben** [comment]
I could not run the .exe on my windows server 2016 image with the same settings as you had. Also someone else reported that he/she could not run the serial key generator on the server.

Have you tested that? With the 2 day lookout trying it out yourself is kind of a terrible since you might lock yourself out of your bot.

**Comment by csyeul** [comment]
> I could not run the .exe on my windows server 2016 image with the same settings as you had. Also someone else reported that he/she could not run the serial key generator on the server.
> 
> Have you tested that? With the 2 day lookout trying it out yourself is kind of a terrible since you might lock yourself out of your bot.



> Quick update: you should be able to run Zooey Bot, Sarasa Bot, the Poker Bot and the GBF Combat Sniffer on a Google Cloud machine without any GPU (a Windows Server 2016 image with a desktop GUI was used). A GPU is not required at all when using a single window and won't be detrimental whatsoever regarding the experience - FPS will still be choppy but it is not what matters in this case. I used this for tests:
> ![image](https://user-images.githubusercontent.com/5464705/54157890-2cff4280-4441-11e9-93ad-1cc9badc6475.png)



Also going to wait until further confirmation from Masuzu in case the bot doesn't work.

**Comment by kiaben** [comment]
> 
> 
> #1023
> 
> I see it has been mentioned in this thread.
> I also use this too because it allows you to have JP ping anywhere you are.
> @Masuzu If you're having trouble setting it up, the link is this https://www.reddit.com/r/Granblue_en/comments/8j1uhp/visual_guide_to_lowlag_granblue_using_windows/
> 
> it gives an in-depth and easy guide on setting it up.
> 
> I'd really like this compatibility to happen because I can just slot in my bot in here and do something else on my pc. It's worth mentioning that your Serial Generator doesn't work in Windows server 2016 either. Not sure why though.
> 
> I know not a lot of your bot user's population use this but few of us that do would really appreciate it. Please make this happen.

I tried the new 3.6.7 version and its working now on google VPS.
