### ISSUE TITLE
Network Error Detection

### ISSUE THREAD

**Issue by csyeul** [Masuzu/ZooeyBot#1056]
I don't fucking understand why this isn't a feature already.

I just leave my bot around and do something else in the room, if there's a captcha I can hear the sound and enter it but if there's a network error, bot just gets stuck and doesn't even play a sound. 

Because of this I don't even know the bot got stuck within first few minutes   and come back few hours later to a stuck bot and a network error. This gets me so fuckign pissed this has been happening this entire gw and I have to  look at this god damn bot whenever I am running it lie what the hell's the point of having this fucking bot if I have to stare at it every second??

Like PLEASE implement a way to detect that the fucking game have network error because cygames server during GW is absolute fucking garbage 
https://imgur.com/a/krZBk5t

**Comment by Masuzu** [comment]
Hello,
I hardly got any network errors in general, if any during this GW. Rare events are not something I intend to spend time on, and are resolved on their own by Cygames. It can happen when there is too much server load or game bugs, like that black home page a few days ago. Seeing them pop and refreshing the page won't make things any better until Cygames fixes the issue, unfortunately.
