### ISSUE TITLE
Can't use summon in raid

### ISSUE THREAD

**Issue by GivemeDokkan** [Masuzu/ZooeyBot#1059]
Hi,
Could you please check this out, the bot keep crashing when try to use summon in battle.

I'm a totally newbie to this programming stuffs, so maybe I did something wrong. 

![2capture](https://user-images.githubusercontent.com/47890542/53243163-99f0a980-36d9-11e9-9193-48386c2dc6e8.JPG)
![capture](https://user-images.githubusercontent.com/47890542/53243164-9a894000-36d9-11e9-8144-b725e498e4dc.JPG)

**Comment by Alaric323** [comment]
Case sensitivity...
