### ISSUE TITLE
Treasure Event Mode doesnt work with new event format (WMTSB 3)

### ISSUE THREAD

**Issue by AtGod1711** [Masuzu/ZooeyBot#1062]
Developer probably already notices, but the arrangement of raid battle during this event is slightly different from usual, which likely confuses Zooeybot when it tries to find extreme/impossible raid. 

Would be great if this is addressed soon!

**Comment by Masuzu** [comment]
Hello!
Sure thing, I will look into it today.

**Comment by Masuzu** [comment]
This is now addressed with v3.6.5. Happy farming!
