### ISSUE TITLE
no preferred summon found (tiamat)

### ISSUE THREAD

**Issue by Rkdheishins** [Masuzu/ZooeyBot#1064]
PreferredSummons=Tiamat_2
PreferredSummons=Tiamat
PreferredSummons=Tiamat__omega
PreferredSummons=Tiamat_omega_2

none of these work, im unsure as to why its not being able to find this summon when there's multiple to select from, any idea why?

**Comment by MegaBlues** [comment]
The proper way to write the name would be "Tiamat Omega", or "Tiamat Omega_2", I believe. You only use an underscore to denote the level of uncap.
