### ISSUE TITLE
Bot recharge AP in both main account and slave account

### ISSUE THREAD

**Issue by wuwe1** [Masuzu/ZooeyBot#1067]
My problem is same as the [#1026](https://github.com/Masuzu/ZooeyBot/issues/1026). How can I stop  main account to use half elixir?

**Comment by Sundaerae** [comment]
any update on this? because it still happens (and eventually will crash zooeybot because it can't refill)

**Comment by falassiry** [comment]
Yes this issue is really affecting ability to use zooeybot for sliming (doesn't gain any half elixirs from sliming at all, instead spends them)

**Comment by Masuzu** [comment]
Closing since AP refilling as revamped for the slave mode as well.
