### ISSUE TITLE
i need variable

### ISSUE THREAD

**Issue by Dreamfinal** [Masuzu/ZooeyBot#107]
Hello, I want to program Can set the variable itself.

a sample
I use Lucifer Ougi.
Lucifer has Buff Skill 2 Double Shoot
I substitute Variable 

`x = 1.`

Turn later

```
If x == 1 then
 character_4:UseSkill(2)
 x = 0
end
```

Or

```
for Character_4.buff_Debuff_List() do
   if Character_4.buff_Debuff_List(i).nameBuff == 'Out of the Ashes' then
      Character_4:UseSkill(2);
   end
end
```

Or

Enemies use Skill charming.
DisableChargeAttack.

```
for Character_4.buff_Debuff_List() do
   if Character_4.buff_Debuff_List(i).nameBuff == 'Charming' then
      DisableChargeAttack()
   end
end

```
I'm not sure about the lua syntax.
The syntax may be incorrect, sorry.
I used to write but Java, JavaScript
But I will communicate about it. Think you understand

I have not hastened to do this now, I just introduced it. You will follow or not follow but you,
I think my idea May be useful

Thanks for giving me more time to sleep.

**Comment by Masuzu** [comment]
Hi,

This feature would be great to be able to define user variable resetted at the beginning of each new raid, and to access debuffs.
There are debuffs which last for a certain number of turns, easier to manage, and some others which lasts for a given amount of time, which will require a different syntax.
I will see what I can do about it but not right now.
