### ISSUE TITLE
New update makes bot ignores to read turns

### ISSUE THREAD

**Issue by YumeHaru** [Masuzu/ZooeyBot#1070]
Hi,

The bot works fine but it ignores the "turn" code in my script.
https://i.imgur.com/QQzybCQ.png

If think it's because even if I am at turn 3 of the battle, it still thinks it's at turn 1.
![bug](https://user-images.githubusercontent.com/37016519/54087424-0b279200-4353-11e9-9301-7b123e2c7834.png)

Edit: this happens only while using the Treasure mode in the event Why the sky is blue 3 in "ex".
I also tested it under Chrome and Chromium

**Comment by Masuzu** [comment]
Hello,
I acknowledged the bug and will work on a fix.

**Comment by Masuzu** [comment]
I apologize for the delay. The version [3.6.6](https://github.com/Masuzu/ZooeyBot/releases/tag/3.6.6) should address this issue.
If the problem still persists, could you please set the configuration parameter `DebugLuaScriptLoading` under the `Debug` section of the `ZooeyBot.ini` file to `true` and provide a screenshot of the console messages when this happens? Thank you.

**Comment by YumeHaru** [comment]
Sorry for the late reply, I couldn't come online for a while.
Thanks for fixing the issue.
