### ISSUE TITLE
Bot stuck in refresh loop while doing coop slime

### ISSUE THREAD

**Issue by AtGod1711** [Masuzu/ZooeyBot#1071]
I was doing standard coop slime with slave acc and noticed that after a short while (3-5 minutes), the acc would get stuck at the result screen, and zooeybot, without knowing that the round was already over, keep refreshing over and over again. Only the main acc 's tab get refreshed continuously.
I wonder if this has anything to do with the recent update. I have never encountered this issue before, using the exact same configuration. This issue also does not show up in solo slime. 
I would appreciate a quick fix.

Thanks.

**Comment by Masuzu** [comment]
Hello,
Could you please upload a screenshot of the console messages when it gets stuck? Thank you.

**Comment by AtGod1711** [comment]
Certainly, here it is. 
![image](https://user-images.githubusercontent.com/46847982/54168996-6dfa5580-4447-11e9-8aa1-f3afb23536f0.png)

The lua code for main acc is use clarisse skill 2, skip attack
the lua code for slave acc is use sword master skill 1

**Comment by AtGod1711** [comment]
Hello again,

I think the problem was on my end, and it was due to ping. I noticed Zooeybot tried to perform actions before the page was fully loaded so I increased the ping/delay tolerance parameter, and it seems to work fine currently.

Apologies for taking up your time.

**Comment by executedlol** [comment]
How did you fix this? I've tried messing with every parameter but I didn't manage to make it work, what did you change?

**Comment by AtGod1711** [comment]
In the ZooeyBot.ini file, at the top, I increased the values of the following parameters:
- MaxPageLoadDelayInMsBeforeRetry
- MaxTriggerDelayInMsBeforeFallback
- MaxResponseDelayInMs
- MinWaitTimeInMsAfterRefresh
to about 5000-7500 ms. This probably depends on where you live, but I am in NA so my ping isnt particularly great. High values might make Zooeybot respond a bit slow, but I am fine as long as it works.

**Comment by executedlol** [comment]
Thanks for the help but I managed to fix it, there seems to be a problem with using the slave on incognito, using another profile on chrome works fine.
