### ISSUE TITLE
bot won't start due to web socket error

### ISSUE THREAD

**Issue by Blackpandar** [Masuzu/ZooeyBot#1075]
I try to follow the guide to install zooey bot, but when I finished install it, it won't start.
The extension is available and have "Zooey bot, your friendly co-op companion, is waiting for orders", but when I clicked on start button, nothing happened.
When I checked at extension, there are two errors about websocket.
![image](https://user-images.githubusercontent.com/48514252/54271646-85a31c80-45b4-11e9-9cf1-9a0127e87f29.png)
I don't know what causes this problem since I have little knowledge about coding, so please inform me if you know how to fix it.
Thanks in advance.

**Comment by twelve1997** [comment]
same error, pls help

**Comment by Masuzu** [comment]
When the program is started for the first time it requests to be allowed through the firewall which may otherwise block some connections. It needs to be allowed through the firewall.

**Comment by cownono** [comment]
WebSocket is already in CLOSING or CLOSED state.
Same error. allowed through the firewall. how can i figure it out

**Comment by vipirius** [comment]
Hi, I am getting the same issue. App is added to firewall whitelist but is still not working.. Can you please help I paid 10 euros and couldnt even use the app once.
