### ISSUE TITLE
Multiple Slime botting issue with different setup

### ISSUE THREAD

**Issue by Gutenhl** [Masuzu/ZooeyBot#1077]
If i turn on slave go first, it'll stuck on refill AP ui when slave ap is no longer sufficient.
If main go first, it'll refill both slave and main ap.
solo slime works perfectly fine no issue whatsoever.

**Comment by zappky** [comment]
This problem has been reported a lot of times now already.
Personally, i used to encounter it too. 

After updating to latest version, i am met with a stranger problem of main acc skill click for mc  will fly the mouse pointer in a weird Arc into the chrome dev area,and then the bot proceed to process slave turn and kills the slime. Slave mode to me is totally unusable
