### ISSUE TITLE
New Event : combat mode active bot my bot dont work

### ISSUE THREAD

**Issue by waiperwing75** [Masuzu/ZooeyBot#1078]
<img src="https://www.img.in.th/images/5b42a4a69936fdacb3b5f81741f37198.png" alt="5b42a4a69936fdacb3b5f81741f37198.png" border="0" />

then choose summon. and combat mode active. my bot doesnt attack.
please help me

thank you

**Comment by zappky** [comment]
You mean after the raid starts, the bot just stood there do nothing or what?

From the bot output, it doesnt seems like anything is wrong.

**Comment by waiperwing75** [comment]
Now I can do thank you
