### ISSUE TITLE
Need help scripting for Alchemist Astray

### ISSUE THREAD

**Issue by justjulz29** [Masuzu/ZooeyBot#1079]
Hey there, new to ZooeyBot.

I followed your scripting guide but I have two problems; the first is that it won't select my party after it selects the summon (the partyselectlua script is empty and despite what it says about auto selecting your party, it doesn't do it); and the second is that I run into this syntax error when the combat begins; 

![bandicam 2019-03-18 13-05-35-675](https://user-images.githubusercontent.com/48667055/54508010-1136f780-497f-11e9-9782-d5e1b36a9117.jpg)

I've written my code like this (as a lua script) and I don't know what the error is; 

DisableChargeAttack()
if character_1.charge_guage >= 100 then
    EnableChargeAttack()
end

if battle == 1 and turn == 1 then
    character_1:UseSkill(4)
	character_1:UseSkill(1)
end

if battle == 2 and turn == 1 then
   character_2:UseSkill(1)
   character_2:UseSkill(3)
   
if battle == 3 and turn == 1 then
    character_1:UseSkill(2)
    character_1:UseSkill(3)
	character_3:UseSkill(3)
	character_4:UseSkill(2)
	character_4:UseSkill(1)
end

I'm using Chromium 75.0.3733.0

**Comment by zappky** [comment]
This is just basic scripting syntax error.
you forgot to put "end"

if battle == 2 and turn == 1 then
character_2:UseSkill(1)
character_2:UseSkill(3)
(put end here)

**Comment by justjulz29** [comment]
Oh DERP. Lol no wonder it didn't work before; now the script is working properly, thank you! But may I ask; is there any way to have ZooeyBot hit the 'back' button after using a skill to kill the enemy (or after I attack it) to skip the enemy death animation at all in Battles 1 and 2? Or is there no way?

**Comment by zappky** [comment]
i dont think there is a way to do that, but you can call a refresh with Refresh()
