### ISSUE TITLE
enemy_1.overdrive_state // can not be used.

### ISSUE THREAD

**Issue by Dreamfinal** [Masuzu/ZooeyBot#108]
I believe that enemy_1.overdrive_state
can not be used eventhough
I set ReloadPageOnLastBattle as true.

I'm quite sure because Enemy_1.charge_diamonds // enemy_1.max_hp // enemy_1.hp
works normally

sample

```
if (enemy_1.hp / enemy_1.max_hp) < 0.75 then
	character_1:UseSkill(4)
end
```
work

```
if enemy_1.charge_diamonds > 0 then
	character_1:UseSkill(1)
end
```
work 

```
if enemy_1.overdrive_state == true then
	character_3:UseSkill(2)
	character_3:UseSkill(3)
end
```
not work

**Comment by Masuzu** [comment]
If you happen to use a skill which makes the enemy go into overdrive mode, enemy_1.overdrive_state will be false, unless you use the command `Refresh` after using the skill. That's a bit annoying indeed, until a better solution is found.
