### ISSUE TITLE
2 Slime bugs(refresh results and refresh on room screen)

### ISSUE THREAD

**Issue by DarkenShade** [Masuzu/ZooeyBot#1081]
When i have the main kill without the slave attacking, the bot will spam refresh in the lobby room until i stop it.
When i have the slave hit first and then the main kills it, the bot will spam refresh the results screen.

**Comment by zappky** [comment]
The refresh spasms have been reported before.  

My guess is that internally, in zooeybot, the gamestate is not in sync with the actual gamestate of the game, so the bot is refreshing and trying to get the game into a recognizable battle state,but the game is actually in coop state.  Hence the spasm.

Anyway, there is a refresh trap,but i dunno if you are in actual fact encountered this. 
Just try this. Make slave host the quest, and make it kill it. Main will go straight to the no loot page, now try refreshing. it would be stuck there.  This should may explains your problem.  Btw this is how the game handles for the non host, no action , player. The only way out is to press the Room button.
