### ISSUE TITLE
Can't start Campaign-Exclusive Quest.

### ISSUE THREAD

**Issue by Hildibrand** [Masuzu/ZooeyBot#1083]
New to program, started fiddling with it and it can farm the Cargo quest without problems, but when I go to Quest->Special->Campaign-Exclusive Quest, ZooeyBot doesn't seem to respond. I realized that, however, the number at the side of the "X" in the Chrome dev tool starts rising, and the problems showing at the bottom mention something about Internal Server Error.
![image](https://user-images.githubusercontent.com/48763502/54771094-dfcf5d80-4c04-11e9-8a1a-7ebc5c668b41.png)

**Comment by ChellyBeam** [comment]
use a CustomizedScheduling

**Comment by Hildibrand** [comment]
Worked, thanks.
