### ISSUE TITLE
How can I start Xeno Sagitarius

### ISSUE THREAD

**Issue by DarkHorse1121** [Masuzu/ZooeyBot#1086]
How can I start Xeno Sagitarius raid?

TreasureEventUrl=http://game.granbluefantasy.jp/#quest/extra/event/2022
Difficulty=xeno-raid

Then started Xeno Ifrit raid.

**Comment by Masuzu** [comment]
Hello,
Should the event mode fail to pick the correct quest cost for the raid, using the [raid scheduling mode](https://github.com/Masuzu/ZooeyBot/wiki/Customized-raid-scheduling) and using the raid URL directly http://game.granbluefantasy.jp/#quest/supporter/501191/1/0/20641 should be fine.

**Comment by DarkHorse1121** [comment]
Got it.
Thanks.
