### ISSUE TITLE
Unregistered user

### ISSUE THREAD

**Issue by twelve1997** [Masuzu/ZooeyBot#1087]
Last week the bot was working well, I have not touched practically this week until today and I realized that I have the following error:
![image 4](https://user-images.githubusercontent.com/48158499/54870503-5a1eef80-4d75-11e9-8676-3e000d041497.JPG)

I have the license a day

**Comment by twelve1997** [comment]
None of the 3 options that appear there I work to fix that error.

**Comment by JillVernus** [comment]
check whether your serial number is same as the one on the web portal.
update serial number if not

**Comment by twelve1997** [comment]
![sillproblem](https://user-images.githubusercontent.com/48158499/54994633-b7dc5300-4f92-11e9-988f-db96d710eda9.JPG)
![Captura](https://user-images.githubusercontent.com/48158499/54994645-bad74380-4f92-11e9-8374-7eec403cabfd.JPG)
I tried that, it does not work, even tried the bot from another computer, changing the serial number and still not working

**Comment by Masuzu** [comment]
Please use the serial number in the serial_number.txt file created whenever you start Zooey Bot. In some cases which I won't investigate, it is different than the one from the serial number generator.

**Comment by twelve1997** [comment]
![image](https://user-images.githubusercontent.com/48158499/55675876-2f618a80-588f-11e9-8c5a-8e20a0dbb9dd.png)
 Thanks for trying to help, I guess it doesn't matter the truth anymore. Thanks for trying to help, I guess it doesn't matter the truth anymore.
