### ISSUE TITLE
Failed to select the summon.

### ISSUE THREAD

**Issue by omieqqe** [Masuzu/ZooeyBot#1089]
Hi there,

Since the lasted patch, Zooey just kept saying failed to select the summon. 
I tried to look around if any of my .ini line gone wrong but there is nothing is wrong.

Thank you and have a nice day.

**Comment by august2231** [comment]
Same problem here. It clicks on the summon and then the cursor stops moving. then it refreshes and the same bug happens again.

**Comment by august2231** [comment]
@Masuzu @omieqqe  
I think i solved the problem. I tweaked the ini file a bit and it started working. Here is what i changed:

General
MaxNumActionRetries=3
MinWaitTimeInMsAfterRefresh=5000

**Comment by Ryuug** [comment]
> @Masuzu @omieqqe
> I think i solved the problem. I tweaked the ini file a bit and it started working. Here is what i changed:
> 
> General
> MaxNumActionRetries=3
> MinWaitTimeInMsAfterRefresh=5000

Hey man, can you send me your entire .ini file? I’m having the same problem but i can’t fix it

**Comment by august2231** [comment]
> Hey man, can you send me your entire .ini file? I’m having the same problem but i can’t fix it

sure 
[ZooeyBot.zip](https://github.com/Masuzu/ZooeyBot/files/3000283/ZooeyBot.zip)

**Comment by Ryuug** [comment]
You’re a god-send!

**Comment by omieqqe** [comment]
This is gold.
