### ISSUE TITLE
cant work on razer blade stealth

### ISSUE THREAD

**Issue by ChoAbbg** [Masuzu/ZooeyBot#1091]
i have been using zooeybot for 5months on my pc
for some reason it cant run on my laptop(razer blade stealth 13inch)
i did match all the setting which it required (https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation)
and when ever i start and click the quest button
it stuck at the "calibrating"

**Comment by Ryuug** [comment]
It’s an issue with the size, you have to set the window size to “medium”, auto sizing to off, chrome’s zoom to 100% and windows zoom to 100% too, i had this same problem before and it was because my granblue was set to small and had the auto resizing on
