### ISSUE TITLE
Zooey randomly clicks auto-select changing the party completely

### ISSUE THREAD

**Issue by Zbterr** [Masuzu/ZooeyBot#1092]
It starts fine, plays the quest for a few times but then randomly when starting again it clicks “auto-select” changing the entire party, weapons and summon to dark, what may be causing this?

**Comment by Alissa1122** [comment]
Same problem here using 3.6.7 which did not happen at 3.6.6.

Also 3.6.7 will accidently change your party selection after running several raids.

**Comment by MegaBlues** [comment]
As a stop-gap, I recommend using AdBlock to remove the auto-form button from the summon confirmation menu.

**Comment by Zbterr** [comment]
> As a stop-gap, I recommend using AdBlock to remove the auto-form button from the summon confirmation menu.

Can you explain how? I have adblock but the thing still appears, it seems that the problem occurs when you try to fight a stage using an off-element team, the auto select pop-up appears and zooey just clicks “ok” and moves on with the new team created

**Comment by MegaBlues** [comment]
Right-click the button, select 'block this ad,' then set the filter strength until it displays

`game.granbluefantasy.jp##DIV[class="prt-recommend-button"]`

Then the button will no longer appear, so it can't accidentally be clicked.

**Comment by Zbterr** [comment]
That worked, thanks!

**Comment by Alissa1122** [comment]
I think we better let this issue stay opened until Masuzu has time to look into the mis-click problem, using adblock is just a workaround
