### ISSUE TITLE
New update keeps having "failed to select summon"

### ISSUE THREAD

**Issue by hamdolf** [Masuzu/ZooeyBot#1093]
And keeps refreshing. Bot worked fine on 3.6.6, but now on 3.6.7 I need to keep going inbound manually before it continques. Now it just does nothing except refresh the page over and over selecting the summon I have set up in my script.

**Comment by Ryuug** [comment]
https://github.com/Masuzu/ZooeyBot/issues/1089 check this thread it has the solution

**Comment by ErogeSeiyuu** [comment]
I tried that but it's still not working.

**Comment by rudnyk** [comment]
Same problem for me, I get "failed to select the summon message" right after the bot clicks on a summon(sometimes confirm select window appears and sometimes it even doesn't) and without any obvious errors or problems page goes into reload. Sometimes it's works on second try after reload, but it's quite rare occasion.

Tweaking various delay values didn't help at all. Version 3.6.6 works just fine.

**Comment by xerance** [comment]
bump, this needs fixing

**Comment by Masuzu** [comment]
Hello all,
This should have been addressed with the last version: delays were increased between each click on the summon to select as in the earlier versions.
