### ISSUE TITLE
Xeno Ifrit Raid stuck on Summon Select

### ISSUE THREAD

**Issue by Miyoumu** [Masuzu/ZooeyBot#1094]
Hello, 

I'm trying to configure Zooeybot to start the Xeno Ifrit Raid (lv 100, 40 ap) through the use of TreasureEventMode. However once it navigates to summon selection it does not do anything and gets stuck.

It does not repeatedly refresh or move the mouse or click anything. 

![image](https://user-images.githubusercontent.com/28634170/54888397-2f1ac580-4e73-11e9-9271-f21e16990039.png)

![image](https://user-images.githubusercontent.com/28634170/54888410-49ed3a00-4e73-11e9-97a6-ff2d224c7448.png)

![image](https://user-images.githubusercontent.com/28634170/54888415-4fe31b00-4e73-11e9-8a55-3f70d883c755.png)

Please help. 

As a note: Event mode for solo xeno ifrit has been working fine. I've only been having commencing the raid.

**Comment by Miyoumu** [comment]
As a note: Event mode for solo xeno ifrit has been working fine. I've only been having commencing the raid.

**Comment by MegaBlues** [comment]
You'll need to use a schedule now. Here's the layout for my own.

SetEventPageUrl("http://game.granbluefantasy.jp/#quest/extra/event/2022")
SetLuaScript("Scripts/XenoIfritHost.lua")
SetPreferredSummons("Europa; Poseidon, the Tide Father; Gabriel")
RerollSummonWhenNoPreferredSummonWasFound=true
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/500861/1/0/20611", 40, 30)

**Comment by Miyoumu** [comment]
I figured it out. I was using the summon select link instead of the event page url. My mistake.

That also works however for anyone running into other issues.
