### ISSUE TITLE
How to select Xeno Sagittarius raid in TreasureEvent mode ?

### ISSUE THREAD

**Issue by Message0202** [Masuzu/ZooeyBot#1095]
I set up Zooeybot as https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode instructed, but always end up starting the Xeno Ifrit one.

**Comment by Ryuug** [comment]
You put the wrong url on the .ini file

**Comment by lamewood** [comment]
i just use the event mode, not the treasure mode. works the same

**Comment by Sundaerae** [comment]
how do you set it up for the raid?
It doesn't work on mine. I've also tried to use EventPageURL but still doesn't work.
If I check the network, it will give me error pages.

**Comment by lamewood** [comment]
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/500811/5
NightmareModeUrl=http://game.granbluefantasy.jp/#quest/supporter/500831/5
EventPageUrl=http://game.granbluefantasy.jp/#quest/extra/event/2022

the rest is just the script location or summon itself
![image](https://user-images.githubusercontent.com/37760162/54943496-b29aec00-4f31-11e9-9388-8cb95b7c0d2f.png)

**Comment by Sundaerae** [comment]
Sorry to say, that's for the solo clash. I also have no problem with the solo clash. It's the raid I have problem with..
It won't work for the raids because it needs mats to host, and some other tidbit.

**Comment by lamewood** [comment]
Ah, I've missread that. I just use custom schedule
you just need enough host mats and it should be fine

**Comment by Sundaerae** [comment]
I tried using the custom schedule, it gives me error right after selecting summon, then refresh the page, rinse repeat

> SetEventPageUrl("http://game.granbluefantasy.jp/#quest/extra/event/2022")
SetLuaScript("Scripts/fire-apsalas-nm.lua")
SetPreferredSummons("Shiva")
SetPreferredPartyGroup(5)
SetPreferredPartyDeck(3)
 RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/501191/1/0/20641", 40, 10)

**Comment by lamewood** [comment]
_SetLuaScript("Scripts/xeno_ifrit_raid.lua")
SetPreferredSummons("europa, macula marius, varuna")
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/500861/1/0/20611", 40, 30)_
these are the only lines i added and it's currently running just fine

_SetEventPageUrl
SetPreferredPartyDeck(3)
SetPreferredPartyGroup(5)_
i didnt add these since gbf remembers what team you've used last and the event page isnt required here

i'd suggest you to host the raid with the team you've set up and try it with Zooey with less line like mine

**Comment by Cyuss321** [comment]
Sometimes nightmare pops up after doing raids, is there any script to add to custom scheduler for that? Seems like custom scheduler is the only way I can do event raids and being able to do nightmare would be nice, just have no idea what to add.
