### ISSUE TITLE
ZooeyBot holding down keys in exe window?

### ISSUE THREAD

**Issue by sparkster48** [Masuzu/ZooeyBot#1098]
This is super weird and I have not seen anything on here so I figured I would make it known--this does not hinder attacks or summoning its just a minor issue since the new release.
Zooey will constantly spam 4 after the attack command and wont stop until told to do the next task (for me zooey will just keep autoing) 
![Screenshot_2](https://user-images.githubusercontent.com/47395433/55006830-c3407600-4fb4-11e9-9274-646320c28262.png)

**Comment by Jinko78** [comment]
Yea am getting this also since last update.

**Comment by AtGod1711** [comment]
same for me, i think it is because there is no lua.script (which we dont need because we just auto attack)

perhaps do a test with a lua script maybe?

**Comment by Masuzu** [comment]
Hello,
I took note of this

**Comment by Masuzu** [comment]
Fixed
