### ISSUE TITLE
Zooey not selecting Europa or Godsworn Alexiel

### ISSUE THREAD

**Issue by Jinko78** [Masuzu/ZooeyBot#1099]
Curious if someone can spot a mistake I'm making because I can't seem to see it.
Current code I'm using is
`SetPreferredSummons("Europa_2,Europa,Leviathan Omega_2,Gabriel,Leviathan Omega")`
and
`SetPreferredSummons("Yggdrasil Omega_2, Godsworn Alexiel_2, Godsworn Alexiel, Uriel")`

It's selecting the summons as it should besides Godsworn Alexiel and Europa.

Any ideas ?

**Comment by Koraxor** [comment]
There is no _2 for Alexiel or Europa, just _1. Though generally I'd say just put "Europa" and "Godsworn Alexiel" without _1, the damage difference isn't too huge a deal and it'll always pick a MLB one over a non MLB one if there's the choice of both, but if there's no MLB it'll take the non MLB one, which will keep you from having to reset summons more often.

**Comment by Jinko78** [comment]
Ok that's good to know there is no _2 version of these summons, but it still won't select "Europa" or "Godsworn Alexiel" with or without the MLB suffix.

**Comment by Koraxor** [comment]
SetPreferredSummons("Europa, Leviathan Omega_2, Gabriel, Leviathan Omega")
SetPreferredSummons("Yggdrasil Omega_2, Godsworn Alexiel, Uriel")

These are the strings you should be using. This is for a schedule though right and not a regular .ini?

**Comment by Jinko78** [comment]
That is what I have and yea it's scheduled, but doesn't matter if you put it in the ini either.
It still doesn't recognise these summons.
