### ISSUE TITLE
News: Viramate has been shutdown by cygames request

### ISSUE THREAD

**Issue by Alissa1122** [Masuzu/ZooeyBot#1102]
Looks like cygames is now very serious about plug-in/extension/bots, better lay low for a bit now I guess

Discussion thread here
https://www.reddit.com/r/Granblue_en/comments/b6xx25/viramate_is_gone_from_the_chrome_store_and_the/

**Comment by Gutenhl** [comment]
i hope that masuzu can add an option to recharge pot normally, since that's the only thing that doens't look human in zooeybot atm

**Comment by Jinko78** [comment]
Wow they trying to kill their game :S

**Comment by Masuzu** [comment]
Hello all,
The AP/BP refill going through the support item page is on high priority and will be released by the end of the week.
Definitely a letdown indeed, the Lite mode suppression announcement topping out everything.
It may be the good time for a reboot I guess, with different in-game models, and getting contents creator involved. https://www.youtube.com/watch?v=A_M41dMdJaU

**Comment by zooeyjapan** [comment]
That's some nice videos there, based on that a quesiton seeing the information thread is closed.

The GCP instances which you show in the video for zooey & combat sniffer, do they use the Nvidia setups ( Tesla t4 or  the t4 virtual workstation) or are these examples done on instances without any additional video resources?

**Comment by Masuzu** [comment]
The racing videos all use a machine with a Tesla T4 GPU for the smoothest experience possible, the difference is quite noticeable from personal experience without.
RP grinding is done on a machine without any GPU.

The GPU machine used was as follows:
![image](https://user-images.githubusercontent.com/5464705/55443423-9c80d180-55aa-11e9-89bf-0755842576ed.png)

**Comment by YumeHaru** [comment]
I have a suggestion: you could make your own Viramte so people relucent to bot would pay you at least for a goo Viramte clone.

**Comment by Masuzu** [comment]
The most useful features like ability/attack/summon shortcuts and raid joining will be ported to [GBF Combat Sniffer](https://gbtools.azurewebsites.net/CombatSniffer/en/Home)

**Comment by Masuzu** [comment]
Instant raid joining is now live
https://www.youtube.com/watch?v=d8kHpGFHVT8

**Comment by zooeyfan** [comment]
> Hello all,
> The AP/BP refill going through the support item page is on high priority and will be released by the end of the week.
> Definitely a letdown indeed, the Lite mode suppression announcement topping out everything.
> It may be the good time for a reboot I guess, with different in-game models, and getting contents creator involved. https://www.youtube.com/watch?v=A_M41dMdJaU
> Stay tuned!

Is the first mentioned feature implemented? I'm using 3.6.6 but I don't see the pots change in patch notes. Very interested in that feature especially now that Cygames is improving their anticheat.
