### ISSUE TITLE
3.6.11 Co-op Slave mode Ap Problem?

### ISSUE THREAD

**Issue by Chololoco13** [Masuzu/ZooeyBot#1106]
Could someone answer me if they already solved the problem?
I mean that the bot recharged in both accounts (slave and main account)
I was checking the patch notes but nothing comes of it.
I do not have an active license at this time and I just want to use the bot to get potions. I do not want to waste my money and the problem is not solved.
Thank you very much and sorry for the inconvenience. google translate

**Comment by Rkdheishins** [comment]
would appreciate if this would get fixed too but in the meantime its an ok problem to deal with, considering you net ap after 2 hours of doing coop's just make sure u can do several at a time to net pot wise, as of right now its seems to not be fixed yet "could just be me" but its still worth buying again, its a small price to pay for a huge convenience, im sure in time he'll get around to fixing this

**Comment by omieqqe** [comment]
![Capture d'écran 2019-04-07 00 14 16](https://user-images.githubusercontent.com/45419353/55675891-1e823a80-58ca-11e9-849f-4331f1426f55.png)

Yep. I can confirm that the Bot refil both account. Today is my first day trying the Slave mode and got a big surprise XDDDD.
