### ISSUE TITLE
Calibrating

### ISSUE THREAD

**Issue by Sliime** [Masuzu/ZooeyBot#1107]
my application does not exit "calibration" even though I press enter, am I doing something wrong?
![ewe](https://user-images.githubusercontent.com/44802328/55523226-859bb700-565e-11e9-9a48-28f36d8eaa29.png)

I've already zoomed in 100% and my settings are in standart.

**Comment by Rkdheishins** [comment]
if this is your first time setting up zooey, id religiously follow step by step the instruction in getting it set up, even the smallest detail will keep it from working, had the same problem when I first bought it. 

definitely go over the instructions to make sure every detail is reflecting correctly

**Comment by Sliime** [comment]
I already fixed it, in my case the tutorial "I have scaling issues! (Again?!)" helped me.
