### ISSUE TITLE
ZOOEY STUCK

### ISSUE THREAD

**Issue by Rarow** [Masuzu/ZooeyBot#1108]
I dont know what is happening, but after sometime the cursor will move too high (i think it move to the chrome address bar) and will get stuck because it cant select anything. zooey didnt refresh too, it just get stuck. I have to move the cursor lower again then zooey will continue. This thing randomly happening and not showing anything in console. Do i have wrong setting? or is it a bug?

It always happening after running for a few minutes. And it happens when trying to select summon selection. It showed this too https://ibb.co/Zx75r63

**Comment by Masuzu** [comment]
This looks like a user window layout issue and won't be addressed. By default the NM mode popup will always be located in the top left corner. I always have my GBF window not located in the top left corner to avoid overlaps (in any case, the GBF window should have the focus set on it after the NM window pop ups)
