### ISSUE TITLE
ZooeyBot clicks on "cancel" instead of "OK" for skills.

### ISSUE THREAD

**Issue by tretray** [Masuzu/ZooeyBot#1115]
I tried the solution from #672, but did not fix the issue. Help would be greatly appreciated. 

Current script:

character_1:UseSkill(2)
character_1:UseSkill(4)
character_3:OnPartyMember(2):UseSkill(1)
character_3:UseSkill(2)
Summon(1)
Refresh()
character_2:UseSkill(3)
character_2:UseSkill(2)

![Error](https://user-images.githubusercontent.com/42560652/56086839-d1dfb780-5e13-11e9-966e-52bb34819f82.png)

**Comment by ssskch** [comment]
are you sure you tried the solution?... 

Check the box that says skill check under a characters portrait in a battle, this will stop that box from popping up in the first place

**Comment by tretray** [comment]
I thought the solution was about the "skill effect dialog," but thanks for clarifying. It works now.
