### ISSUE TITLE
Updating bot versions - serial conflict

### ISSUE THREAD

**Issue by IZEROII** [Masuzu/ZooeyBot#112]
I apologize but I am having a major hang up.  I updated to latest version (1.9.10) and I keep getting "unregistered user" prompt on start up.  I changed my serial yesterday so can't do that for another 3 days.  It appears that the new version is paired with it's own serial and there is a discrepancy between what the folder's serial number is and that in account manager.

I tried to just replace the serial within the software folder with that in account manager.  It appears to save however, it simply reverts to the newly generated serial that is paired with the new version.  

I am blocked from updating serial codes in account manager because I recently did it.  I'm effectively blocked from using my license because each new version appears to come with it's own serial code which you have to manually update in your account manager.  What exactly am I suppose to do here?

Edit:
I have sent you an email Masuzu after seeing several closed threads regarding this same issue and needing direct intervention by you to resolve.

**Comment by IZEROII** [comment]
I'm not noting that although I replaced the serial number to what shows on the account manager and saving the txt file, upon closing and reopening the serial number is reverting to a different one every time despite the previous intervention.  As noted previously, I can't update the serial number in account management because it was just recently updated.

**Comment by Masuzu** [comment]
I am really sorry for the very late reply.
Unless you change your computer, there is no need to update your serial number with each new version.
