### ISSUE TITLE
Can't use more than 1 potion at a time during refills

### ISSUE THREAD

**Issue by kusyarudaora123** [Masuzu/ZooeyBot#1122]
Even if you have two or more half AP potions, when you select the number of items it is the number, but it was actually only one was recovering.

Please confirm.
Thank you.

**Comment by Chololoco13** [comment]
I have the same problem

**Comment by Chololoco13** [comment]
The problem continues even in the new version 3.7.1.
Someone else?

**Comment by krypticsalt** [comment]
Mine gets stuck at the pot refill screen. It goes into supplies and to the pots it selects the correct amount of pots but then gets stuck.

**Comment by zappky** [comment]
Same issue, the number just goes blank and only 1 pot is used. In addition, sometimes the bot click on Zephy Feather instead.

**Comment by SunStrider8420** [comment]
Im using the new version(3.7.1) but i don't see it manually refilling pots, all i see is the log saying pot refilled. Is your Zooeybot actually going to the supplies screen where you can see it?

**Comment by zappky** [comment]
> 
> 
> Im using the new version(3.7.1) but i don't see it manually refilling pots, all i see is the log saying pot refilled. Is your Zooeybot actually going to the supplies screen where you can see it?

Yes,you should see the bot goes into the supply screen, click pot, numbers change into the desired amount and press OK. 

But for now, even if the numbers changed and clicked, it actually still only uses 1 pot.

**Comment by SunStrider8420** [comment]
> > Im using the new version(3.7.1) but i don't see it manually refilling pots, all i see is the log saying pot refilled. Is your Zooeybot actually going to the supplies screen where you can see it?
> 
> Yes,you should see the bot goes into the supply screen, click pot, numbers change into the desired amount and press OK.
> 
> But for now, even if the numbers changed and clicked, it actually still only uses 1 pot.

Huh. I was using the new version for treasure event mode and it still uses the old method of AP refill.
I had (incorrectly) assuming it was already using the new method and there was no visual changes.

**Comment by Masuzu** [comment]
I took note of the issue.

**Comment by Masuzu** [comment]
This is now fixed in v3.7.2
