### ISSUE TITLE
Treasure Event Mode still uses old method of AP refilling

### ISSUE THREAD

**Issue by SunStrider8420** [Masuzu/ZooeyBot#1123]
Hi, I saw the patchnotes so I figured the pot refill was implemented.
However, I only ran this in Treasure Event Mode, and it still used the old method.
Only realized this when I tried it in normal Event Mode and it actually went to the supplies page to refill potions.

Anyone else having this issue?
V3.7.1

**Comment by twgok123** [comment]
Yes i also have this problem. Pls fix this.

**Comment by Masuzu** [comment]
Hello,

Thank you for reporting this. This has now been addressed in v3.7.3
