### ISSUE TITLE
[Request] Event-Exclusive Quest ZooeyBot.ini file/settings

### ISSUE THREAD

**Issue by lz83** [Masuzu/ZooeyBot#1125]
Hi @Masuzu 

Would you be able to share the ZooeyBot.ini file/settings you used for the event exclusive quest guide video #1085? I am using the same GCP setup from your other video but ZooeyBot takes a lot longer before pressing any buttons. I'd like to use the same wait before/etc time settings as in the video. 

My script is just simply Seofon skill 2 and skipattack.

Thanks!

**Comment by Masuzu** [comment]
Hello,
Sure, there it is
https://github.com/Masuzu/ZooeyBot/blob/master/ZooeyBotExclusiveEventQuestBoosting.ini
