### ISSUE TITLE
Nothing Happens

### ISSUE THREAD

**Issue by ItsKatsura** [Masuzu/ZooeyBot#1126]
I'm pretty new to these bots so not sure if I;m just dumb, but after I opened the bot, this is the only thing that shows. It doesn't tell me to start the extension or anything like usual. How do I fix this
![Capture](https://user-images.githubusercontent.com/49734901/56423661-30c18880-627b-11e9-9bae-3e7a6659d614.PNG)
?

**Comment by BB951** [comment]
Same here, it was working fine with 3.7.1, but updating seems to have broken it.

**Comment by GranblueOjisan** [comment]
same here

**Comment by twgok123** [comment]
It seem the last bug fix broke the bot.

**Comment by Poko302** [comment]
Happenned to me also in 3.7.3

**Comment by 10shii** [comment]
Hello! am also new and i'm stuck in the same situation, like when i click on the start button of Zooey bot extension nothing happens :(

**Comment by RaiModels** [comment]
Can confirm nothing happens

**Comment by katsuraki** [comment]
me too normally when new version my windows will ask to add program into whitelist of firewall but this one not happen i try to close firewall / add program manual but not work

**Comment by alongsea2** [comment]
when to fix,I want to use it for box

**Comment by gold-nugget** [comment]
It's it safe to use previous version?

**Comment by lamewood** [comment]
it is up to you to use but you will need to add the AP yourself since the 3.7.3 change is the refill of your AP (safer way)

**Comment by rockysilver** [comment]
Same here, nothing happen :(

**Comment by katsuraki** [comment]
i want to use 3.7.3 but it stuck like the picture that ItsKatsura post 
so i guess i have no choice

**Comment by azeroex33** [comment]
where can i get 3.7.1 ,Same here,

**Comment by lz83** [comment]
Also having the same issue with 3.7.3. I am using 3.7.1 without any issues.

**Comment by Etherlon2** [comment]
same here,anyone have a fix? Or where do I download 3.7.1?

**Comment by alongsea2** [comment]
> same here,anyone have a fix? Or where do I download 3.7.1?

in release

**Comment by Etherlon2** [comment]
> > same here,anyone have a fix? Or where do I download 3.7.1?
> 
> in release

I downloaded 3.7.1 in release but I don't see zooeybot inside the zip

**Comment by alongsea2** [comment]
I have it local ,but I can't upload it.

**Comment by Etherlon2** [comment]
> I have it local ,but I can't upload it.

Rip

**Comment by SunStrider8420** [comment]
doesnt work for me either.

**Comment by GranblueOjisan** [comment]
Masuzu please
GW is a living hell for me ... without zooeybot

**Comment by lamewood** [comment]
Can't you guys stop spaming here? This won't get you anywhere.
Try to research for yourself more, all Masuzu added for 3.7.3 is a changed and safer way of refilling. All that means for you is, that you can use 3.7.1/3.7.2, refill beforehand, like 999 ap and let the bot run.
You have to keep watch on the bot anyway since it's mandatory for reasons

**Comment by 10shii** [comment]
I just downloaded the 3.7.1 and 3.7.2 but i don't really see how do i start up, i dont see any exe

**Comment by 10shii** [comment]
Still the same here trying since yesterday to find out the issue :(

**Comment by shimi1** [comment]
why you guys can use a downgrade version of zooeybot? I always pop up the version info to stop me from using it, no choice for using newest version.

**Comment by katsuraki** [comment]
@shimi1  when you open the previous version it will say  new version available...... just close that little window

**Comment by shimi1** [comment]
@katsuraki then it appeared: failed to initialize COM library .Error code 0x80010106. It seems that only happened on me, try to figure it out. Thank you.

**Comment by kusyarudaora123** [comment]
Please use 3.7.1 if you like.

https://github.com/Masuzu/ZooeyBot/files/3091944/zooey-bot-v3.7.1.zip

**Comment by alongsea2** [comment]
Is some one can use 3.7.3 here? Tell us how to zoom the windows to make the bot load while 3.7.1 is no problem.

**Comment by Etherlon2** [comment]
> Please use 3.7.1 if you like.
> 
> https://github.com/Masuzu/ZooeyBot/files/3091944/zooey-bot-v3.7.1.zip

Thank you so much

**Comment by ErogeSeiyuu** [comment]
still happening on 3.7.3. Reverting it back to 3.7.1 works as usual.

**Comment by devvah** [comment]
I can't get solo coop in 3.7.1 to work unfortunately, double sucks situation.

**Comment by Sundaerae** [comment]
@Masuzu you there?

**Comment by SunStrider8420** [comment]
I like how its been 10 days and the creator hasn't even replied to acknowledge this.

**Comment by ErogeSeiyuu** [comment]
he replied plenty of times on other threads too.

**Comment by devvah** [comment]
/slap @Masuzu 

Silence on critical bug is no good. ><
At least tell us if you're working on some update.

**Comment by Sundaerae** [comment]
Are you serious, @Masuzu ?
I don't know about this 'new project' you've been working on, but fixing things should be your priority, no?
not to mention I often timed out when the bit tried to connect to your server (using 1.7.1), not to mention I can't even connect to your azurewebsites.net. That leads to bot closed in the start of raid or can't even be started because the bot can't check whether I'm subscribed or not.

Pretty sure this will take you less time than whatever that 'private server' or 'simulation' do.

**Comment by katsuraki** [comment]
while we waiting for masuzu for fix 
let's share how we dealing for now
I use 3.7.1 temporally For the last guild war it's not quite big lost if see bot need to go to "Consumer" Page to use Poiton.
But in this event i use "Treasure Mode" and realize bot is auto fill the Ap potion without go to "Consumer" page  (i think this quite risk to get ban) anybody has better way to share?

**Comment by ErogeSeiyuu** [comment]
@katsuraki use a timer and manual fill every 20~30 minutes.

**Comment by katsuraki** [comment]
> @katsuraki use a timer and manual fill every 20~30 minutes.

U mean like fill ap to 999 then when it almost out turn off bot and fill it again ?

**Comment by ErogeSeiyuu** [comment]
I refill it on my phone while bot is still running so if it's "detected", it's just "oh I played on PC but it's annoying to stop midway so I refill it while I'm fighting.

Considering I was not banned during second ban wave, it's safe.

But if you're paranoid just stop bot then refill.

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ZooeyBot?src=hash&amp;ref_src=twsrc%5Etfw">#ZooeyBot</a> An issue preventing the use of the version 3.7.3 has been rolled out. You do not have to do anything. I apologize for the inconvenience.</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/1126210025851170826?ref_src=twsrc%5Etfw">May 8, 2019</a></blockquote>
