### ISSUE TITLE
Script issue

### ISSUE THREAD

**Issue by Cyuss321** [Masuzu/ZooeyBot#1133]
I have a script that activates charge attack, it does everything right aside from summoning. I get no syntax errors or anything running it, but it never wants to summon after clicking the charge attack button. It just goes back to attacking and following the rest of the script. Here's the script for reference:
if character_1.charge_gauge == 100 and
     character_2.charge_gauge >= 90 and
	 character_3.charge_gauge >= 80 and
	 character_4.charge_gauge >= 70 and
	 EnableChargeAttack() then
	 Summon(6)
end

**Comment by SunStrider8420** [comment]
Try 
EnableChargeAttack() 
Summon(6)
End

I've never used a "then" after enabling charge attack before and it works just fine for me.

**Comment by Cyuss321** [comment]
Thanks, I'll give it a shot. Not sure why I included then, I must have gotten tired of syntax errors and wanted to be sure the script wouldn't break anymore.
