### ISSUE TITLE
Nothing happens when I click start on the extension

### ISSUE THREAD

**Issue by Longcatto** [Masuzu/ZooeyBot#1136]
zooey bot work fine for me but after i update version and renew my account 
i setup and start zooey normaly but after click start on extension noting happend
what can i do?
![Untitled-1](https://user-images.githubusercontent.com/50016045/56801013-a2cf3a00-6846-11e9-9695-f7293f91964e.jpg)

**Comment by ErogeSeiyuu** [comment]
#1126

It's been like that since 3.7.3 released

**Comment by Longcatto** [comment]
now im back to use 3.6.6 its perfectly fine

**Comment by ErogeSeiyuu** [comment]
do NOT use 3.6.x unless you want to get banned. 
pre 3.7.x auto refill and doesn't "manually" refill, meaning you're prone to get banned due to auto-detection.

Use 3.7.1

**Comment by Longcatto** [comment]
could you send 3.7.1 exe for me? i dont backup that version

**Comment by ErogeSeiyuu** [comment]
https://github.com/Masuzu/ZooeyBot/issues/1126#issuecomment-485219483

**Comment by Longcatto** [comment]
thanks :)

**Comment by ErogeSeiyuu** [comment]
Just a reminder that there's a bug in 3.7.1 (that's supposed to be fixed in 3.7.3 but it's obviously not functioning right now) where zoibot fails to select AP for refill then stops working. Which is why you'll have to manually refill them whenever the bot stops working.
