### ISSUE TITLE
ROTB raid scheduling

### ISSUE THREAD

**Issue by soufflenote** [Masuzu/ZooeyBot#1137]
Hey, does anyone have a sample raid scheduling script they'd be willing to share for rotb, or at least the URL's of the nightmares (Agni, Titan, etc.) if not? Would really appreciate the help, thanks!

**Comment by devvah** [comment]
Wiki has small section with examples https://github.com/Masuzu/ZooeyBot/wiki/Customized-raid-scheduling#hosting-event-quests

**Comment by soufflenote** [comment]
Thank you! Any chance for the Agni and Zephyrus URL's, though, if it's not too much trouble?

**Comment by Rkdheishins** [comment]
Agni
http://game.granbluefantasy.jp/#quest/supporter/711201/1/0/5020

Zep
http://game.granbluefantasy.jp/#quest/supporter/501351/5

**Comment by soufflenote** [comment]
Thank you!
