### ISSUE TITLE
Issue with Scheduling mode - does not repeat properly

### ISSUE THREAD

**Issue by lz83** [Masuzu/ZooeyBot#1138]
I am trying to schedule ZooeyBot to farm the campaign quest as in #1085, but it does not repeat. It will complete the quest once or twice without any issues but it does not repeat properly. 

[CustomizedScheduling]
Enabled=true
SchedulingLuaScript=scheduling.lua
PlaySoundNotificationAfterScheduling=false

SetPreferredPartyGroup(7)
SetPreferredPartyDeck(2)
SetLuaScript("Script/campaignhalo.lua")
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/800021/22", 15, 270)

characters["Seofon"]:UseSkill(2)
Refresh()

--------------------

Select character at position 2 (Seofon)
Use skill at position 2
Refresh
New page loaded: http://game.granbluefantasy.jp/#raid/######### (numbers hidden)
New page loaded: http://game.granbluefantasy.jp/#quest
New page loaded: http://game.granbluefantasy.jp/#quest
New page loaded: http://game.granbluefantasy.jp/#result/######### (numbers hidden)

**Comment by lz83** [comment]
It keeps taking me to the main home page instead of loading up the actual quest URL. 

New page loaded: http://game.granbluefantasy.jp/#quest/supporter/800021/22
Listing available summons
New page loaded: http://game.granbluefantasy.jp/#mypage
Reloading the summon selection page
New page loaded: http://game.granbluefantasy.jp/#quest/supporter/800021/22
New page loaded: http://game.granbluefantasy.jp/#mypage
Reloading the summon selection page
New page loaded: http://game.granbluefantasy.jp/#quest/supporter/800021/22
New page loaded: http://game.granbluefantasy.jp/#mypage
Reloading the summon selection page
New page loaded: http://game.granbluefantasy.jp/#quest/supporter/800021/22
New page loaded: http://game.granbluefantasy.jp/#mypage

**Comment by lz83** [comment]
Issue seems to be similar to #478 and #991
I wonder if they changed the campaign exclusive battle URL to act like an event mode so we need to get a URL for the "event"?

**Comment by choginga** [comment]
I am having a similar issue, the quest does not load at all, regardless of scheduling mode or default mode.

**Comment by Masuzu** [comment]
The raid URL of the campaign quest changed. Depending on your total number of runs if may change as well. Please check it on your side first. When the cost costs 0 AP the URL is
http://game.granbluefantasy.jp/#quest/supporter/800011/22 for instance.

**Comment by choginga** [comment]
The URL is still the same, game.granbluefantasy.jp/#quest/supporter/800011/22
