### ISSUE TITLE
How do i use my lua scripts?

### ISSUE THREAD

**Issue by 10shii** [Masuzu/ZooeyBot#1139]
Hello am kinda newbie with all of this and even tho i got how to create .lua i don't really get how do i activate it, like i made one in order to farm Shiny Slime Search! in very hard mode but now i'd like to know how do i use it.

**Comment by zappky** [comment]
Write your script(code), in txt file, save it as ,or change its extension to .lua.
For example, toolazytoreadup.lua

At zooeybot config file(ZooeyBot.ini), reference the script
For example, if it is in eventmode(your regular botting mode), 
set the mode to active , Enabled=true
Reference the quest url  , EventRaidUrl=https://github.com/Masuzu/ZooeyBot/wiki/Event-mode
Reference the script, EventRaidScript=Scripts/toolazytoreadup.lua . 
Note the Scripts/  is to mean, the scripts are put inside the folder called Scripts. 
Reference the event url, EventPageUrl=https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts

**Comment by Masuzu** [comment]
Thanks as always @zappky
