### ISSUE TITLE
slavemode refreshing

### ISSUE THREAD

**Issue by reinharto** [Masuzu/ZooeyBot#114]
Been following the guide in the FAQ. Main account just get stuck and constantly refresh the page.
Here the steps that I followed:
2 windows with both acc logged in, party and summons selected (does it matter if one is regular chrome vs 2 incognito?)
open dev windows on both
start bot.exe
follow the onscreen prompt
enable main bot extension
enable slave bot extension
refresh bot window
press enter

**Comment by arthurneo** [comment]
You need to have the mission  open and with the ready flashing on the main account  
(I had the same problem as you and I was missing that step)  
You need to have it like this before refreshing the bot, preferably before starting the bots
![image](https://user-images.githubusercontent.com/29359181/27257785-830e1a96-53a9-11e7-9323-c7f4d12d25c8.png)
