### ISSUE TITLE
Campaign Quest issues. 

### ISSUE THREAD

**Issue by choginga** [Masuzu/ZooeyBot#1140]
Is anyone else having trouble loading the campaign quest? 

When the URL http://game.granbluefantasy.jp/#quest/supporter/800011/22 is being loaded the game boots you right back to the home page. 

I've tried everything I can think of, no luck. 

The weird thing is. If i manually load the URL before opening zooey bot it'll load, but once zooey bot is active it boots you right back to the home page. Any ideas?

**Comment by ErogeSeiyuu** [comment]
#1085

**Comment by ErogeSeiyuu** [comment]
I haven't got to do campaign quests again this magfest so idk if there's anything changed tho.

**Comment by lz83** [comment]
I had the same issues in #1138 but it was closed out...

**Comment by Masuzu** [comment]
Hello,
If you can't navigate from http://game.granbluefantasy.jp/#quest to http://game.granbluefantasy.jp/#quest/supporter/800011/22 I am afraid I do not know...

**Comment by ErogeSeiyuu** [comment]
I just did the same thing I'd done last magfest but replaced scheduled url to http://game.granbluefantasy.jp/#quest/supporter/800011/22 and everything worked just fine.

**Comment by skadoo** [comment]
anyone know why it wouldn't refill my AP for 3.7.0 or 3.7.1? i might be missing or forgetting something here since it wouldn't refill my AP for new campaign quest. unless it's not meant to be and i'm just not aware of it lol everything works just fine. just the new campaign AP refilling

**Comment by ErogeSeiyuu** [comment]
3.7.0 and 3.7.1 can't refill AP because it's bugged. You'll have to manually refill. 

It's supposed to be fixed in 3.7.3 but too bad 3.7.3 is completely broken.

**Comment by skadoo** [comment]
ah gotcha. yeah just wasnt sure about it and needed to make sure i wasn't forgetting but all good. not a problem. yeah, unfortunately :/ I'm sure he's working on it. he just seem very busy with new project his working on.

**Comment by choginga** [comment]
@erogeseiyu do you mind giving me a copy of your setup? I really don't know what to do here.

**Comment by ErogeSeiyuu** [comment]
Custom Scheduling lua and scripts are both called free.lua

Zoibot/free.lua:
```
SetLuaScript("Scripts/free.lua")
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/800011/22", 20, 10000)
```
Scripts/free.lua
`character_2:WithWaitTime(300):UseSkill(3)`

Zoibot.ini
```
[General]
Language=en
ChromeDevToolsWindowDockedOnTheRight=true
MaxPageLoadDelayInMsBeforeRetry=3000
MaxTriggerDelayInMsBeforeFallback=5000
MaxResponseDelayInMs=2500
MaxNumActionRetries=1
MinWaitTimeInMsAfterRefresh=5000
TimeLimitInSeconds=9000
UseViramate=false
MaxNumPotionsToUse=999
NumPotionsToUsePerRefill=15
UseFullElixirsWhenNoRemainingHalfAPPotions=true
UseFullElixirsFirst=false
CountdownTimerHorizontalPosition=0
CountdownTimerVerticalPosition=0

[Inputs]
DelayInMsBetweenMouseDownAndUp=40
RandomDelayInMsBetweenMouseDownAndUp=20
MouseSpeed=777
MouseScrollSpeed=250
ExitKeyCode=112
WaitTimeInMsBeforeClickInput=80

[Summons]
# Kaguya,White Rabbit,Bahamut_2,Hades_1,Bahamut_1,
PreferredSummons=White Rabbit_1,Black Rabbit_1,Nobiyo_1,Kaguya,
DefaultSummonAttributeTab=misc
RerollSummonWhenNoPreferredSummonWasFound=true

[Combat]
MinWaitTimeInMsAfterAttack=500
MinWaitTimeInMsAfterSummon=1500
MinWaitTimeInMsAfterAbility=850
LuaScript=Scripts/free.lua
ReloadPageOnLastBattle=true
MaxWaitTimeToLoadCharacterSelectionMenuInMs=1100
EnableEarlyTurnStartWithViramate=false
MinWaitTimeBeforeActionAfterEarlyTurnStartInMs=1500
AdditionalDelayInMsAfter2ChainBurst=3000
AdditionalDelayInMsAfter3ChainBurst=7000
AdditionalDelayInMsAfter4ChainBurst=8500
AdditionalDelayInMsAfterOverchainBurst=10500

[CustomizedScheduling]
Enabled=true
SchedulingLuaScript=free.lua
```

**Comment by ErogeSeiyuu** [comment]
It's like, the basic of the basic, nothing special at all.

**Comment by xerance** [comment]
3.7.1 refills ap for me, although it refills only 1 potion regardless if i put 1 or 64545345 in settings

**Comment by ErogeSeiyuu** [comment]
it sometimes refills, sometimes just refill loop and never refills. 

Hence it's bugged and it's better be manually refilled. Not to mention with how fast you can clear AH/CQ it's way too slow to let zoibot manually refill 1 pot at a time.

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ZooeyBot?src=hash&amp;ref_src=twsrc%5Etfw">#ZooeyBot</a> An issue preventing the use of the version 3.7.3 has been rolled out. You do not have to do anything. I apologize for the inconvenience.</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/1126210025851170826?ref_src=twsrc%5Etfw">May 8, 2019</a></blockquote>
