### ISSUE TITLE
program shuts down after entering quest

### ISSUE THREAD

**Issue by MetaKomgui** [Masuzu/ZooeyBot#1141]
I just started using zooeybot, but the program closes itself right after it automatically chooses summon and enters the battle screen.

I was trying to test it out on angel halo, so there's no script set for it, so I believe it should attack on every turn, but it just shuts itself down.

is this a problem with 3.7.1? because i first tried the latest version, but that one seems to be just broken, not working at all

![qwe](https://user-images.githubusercontent.com/44829099/56898071-1f724a80-6acb-11e9-926c-2fff48d0670a.png)

**Comment by devvah** [comment]
You want to edit that screen and remove numbers after /raid/ ASAP!

**Comment by MetaKomgui** [comment]
> You want to edit that screen and remove numbers after /#raid/ ASAP!

oops forgot about that thx for the mention

**Comment by Sundaerae** [comment]
it is the same problem as the others
#1126

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ZooeyBot?src=hash&amp;ref_src=twsrc%5Etfw">#ZooeyBot</a> An issue preventing the use of the version 3.7.3 has been rolled out. You do not have to do anything. I apologize for the inconvenience.</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/1126210025851170826?ref_src=twsrc%5Etfw">May 8, 2019</a></blockquote>
