### ISSUE TITLE
Coding Turn Conditions 

### ISSUE THREAD

**Issue by SoyBois** [Masuzu/ZooeyBot#1142]
I read issue #1054 and implemented the fix but seem to still just Auto attacks and doesn't actually do the commands. 

I have literally zero coding experience and just following the tags, so I do apologise if I get confused on what your guys are talking about.
![code](https://user-images.githubusercontent.com/50140164/56959670-8ce8ae80-6b91-11e9-8f87-538a64362ab0.PNG)

**Comment by devvah** [comment]
Turns aren't bugged in 7.1 so you just need

> 
> if turn == 1 then
>  code
>  end
>if turn == 2 then
> code
> end

**Comment by talran** [comment]
You can also specify a range for turns or use LE/GT operators. A good catchall would be a turn 1 set and then a 'turn >= 2' which will take care of reusing skills when they meet the conditions. assuming you don't need to watch triggers otherwise

**Comment by SoyBois** [comment]
Okay that's fixed the Turn conditions, what about Stage Conditions?

Mainly want to use it for Slime Blasting or Angel Halo.
![sadfg1](https://user-images.githubusercontent.com/50140164/57033156-82144380-6c8f-11e9-9223-7da921a7fc60.PNG)

**Comment by MegaBlues** [comment]
You would use something like `if battle == 2 then`, as 'battle' denotes the turn.

I would recommend looking at the lua script writing notes.

https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ZooeyBot?src=hash&amp;ref_src=twsrc%5Etfw">#ZooeyBot</a> An issue preventing the use of the version 3.7.3 has been rolled out. You do not have to do anything. I apologize for the inconvenience.</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/1126210025851170826?ref_src=twsrc%5Etfw">May 8, 2019</a></blockquote>
