### ISSUE TITLE
Zooeybot not recognizing GBF Window

### ISSUE THREAD

**Issue by kiaben** [Masuzu/ZooeyBot#1143]
Tried with 3.7.1 and 3.7.3, the exe won't even recognize the GBF window now that light mode is gone.

Did the required resolution settings change?

**Comment by devvah** [comment]
I'm always using high res at medium browser setting, 100% zoom in browser.

**Comment by kiaben** [comment]
If I use my old zooeybot.ini from the 3.6.7 it works but the ini from 3.7.1 and 3.7.3 won't load the window.

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ZooeyBot?src=hash&amp;ref_src=twsrc%5Etfw">#ZooeyBot</a> An issue preventing the use of the version 3.7.3 has been rolled out. You do not have to do anything. I apologize for the inconvenience.</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/1126210025851170826?ref_src=twsrc%5Etfw">May 8, 2019</a></blockquote>
