### ISSUE TITLE
Did Zooey bot 3.7.1 stopped working as well?

### ISSUE THREAD

**Issue by Momo119** [Masuzu/ZooeyBot#1145]
It just doesn't start anymore and it was working well yesterday.

**Comment by Rkdheishins** [comment]
yea, for some reason, the websites down, zooey's down as well as sarasa, unsure myself whats going on

**Comment by Sundaerae** [comment]
the website:
![error aspx](https://user-images.githubusercontent.com/31296536/57105819-04ffd180-6d56-11e9-8bbe-c2f733d19a09.png)

**Comment by rockysilver** [comment]
May be he is updating the server or something, Masuzu is just one person after all.

**Comment by Sundaerae** [comment]
it just an authentication server, you need to update nothing.

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ZooeyBot?src=hash&amp;ref_src=twsrc%5Etfw">#ZooeyBot</a> An issue preventing the use of the version 3.7.3 has been rolled out. You do not have to do anything. I apologize for the inconvenience.</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/1126210025851170826?ref_src=twsrc%5Etfw">May 8, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
