### ISSUE TITLE
GBFPokerBotSerialNumberGenerator.exe wont launch

### ISSUE THREAD

**Issue by Foos420** [Masuzu/ZooeyBot#1146]
Kinda new to this thing so i apologize if its an easy issue to fix.
Followed the steps provided but every time i try to open the exe file nothing happens.
I've tried running as administrator, reinstalling VCredist 2015 (x86), restarting my pc and it still doesn't launch. I've read another issue here with a different OS but I was expecting it should be working fine for Windows 10
OS: Windows 10 pro

**Comment by Masuzu** [comment]
Hello,
Depending on the version you are using, it may be a very old version and VCRedist 2013 x86 may have to be installed.
Depending on the missing DLL error message you may want to refer to https://help.ea.com/en-gb/help/origin/origin/your-vc-runtime-package-has-not-installed-correctly-error-troubleshooting/
