### ISSUE TITLE
Failed to initialize combat mode

### ISSUE THREAD

**Issue by lz83** [Masuzu/ZooeyBot#1147]
I get an error saying "Failed to initialize combat mode" in about 50-60% of my runs 
ZooeyBot just refreshes itself when this occurs but it significantly delays the run since it takes a couple seconds before it refreshes 

I am not using any script. I just have it attack when it starts the campaign quest. 
Currently using 3.7.1

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ZooeyBot?src=hash&amp;ref_src=twsrc%5Etfw">#ZooeyBot</a> An issue preventing the use of the version 3.7.3 has been rolled out. You do not have to do anything. I apologize for the inconvenience.</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/1126210025851170826?ref_src=twsrc%5Etfw">May 8, 2019</a></blockquote>
