### ISSUE TITLE
multibattle -waiting for first battle animation to finish before next stage

### ISSUE THREAD

**Issue by Demonbream** [Masuzu/ZooeyBot#1148]
I don't recall if it's always been this way, but zooey is waiting for the kill animation to finish on stage 1(slime) before advancing to next stage. When I play this manually, I always just hit back in browser or game button as soon as my mc starts to respond to my action(swordmaster disparia). Anyone know how to replicate this?

**Comment by BB951** [comment]
IIRC in multi-stage battle, if you refresh before the last stage, you will end up back at the Quest page, where you need to click "Resume" again to load back into the next stage. That's why Zooey only refresh on kill for the last stage.

**Comment by Demonbream** [comment]
That's correct. There's the other option of just hitting the back button on your browser or the in game back button to advance it forward. It works much better. Actually, I even use it in raid battles. For some reason, it's faster than refresh in raids and in multibattles doesn't kick you to quest page.
