### ISSUE TITLE
Extension is giving this error

### ISSUE THREAD

**Issue by iSDestiny** [Masuzu/ZooeyBot#1150]
![image](https://user-images.githubusercontent.com/32033119/57208000-07e10900-6f86-11e9-9c5c-9288d229d401.png)

Any idea why?

**Comment by iSDestiny** [comment]
It is also giving me network errors. 
![image](https://user-images.githubusercontent.com/32033119/57208494-f77e5d80-6f88-11e9-8228-5d07a6c63ba0.png)

**Comment by Masuzu** [comment]
This is an error which can be treated as a warning message and can be safely ignored.
Do not use any other mode other than the Treasure Event mode for the event special quest
https://github.com/Masuzu/ZooeyBot/issues/1085
