### ISSUE TITLE
Not refilling AP in Slave mode

### ISSUE THREAD

**Issue by water000qazzaqzxccxz** [Masuzu/ZooeyBot#1151]
Sorry for my bad English.
It seems that zooey will be stuck when the slave account refills its AP.
The slave will go to the items and click the 1/2 AP potion icon and then it just stops.

**Comment by meteoshower** [comment]
i can confirm this issue 
zooey loop to click drop down list of number to refill potion again and again .

**Comment by Zuser120000000** [comment]
Is this problem already solved?
troubled with the same problem.

**Comment by Masuzu** [comment]
Changes related to this issue were introduced in v3.9.0.
If the issue still exist then the quick AP refill will be reintroduced as well.

Follow up will be made in #1185
