### ISSUE TITLE
multibattle -waiting for first battle animation to finish before next stage  Shiny Slime Search

### ISSUE THREAD

**Issue by Demonbream** [Masuzu/ZooeyBot#1152]
zooey is waiting for the kill animation to finish on stage 1(slime) before advancing to next stage. When I play this manually(no bot), I always just hit back in browser or game's back button as soon as my mc animation begins(swordmaster disparia). Anyone know how to script the "back" button click to happen 1 second after clicking glory arts instead of the bot just waiting for the "attack" button to switch to "next" button and clicking that?

**Comment by zappky** [comment]
I dont think there is any.
The only one i know is Refresh() which isnt the same as clicking back.
