### ISSUE TITLE
unable to refill ap

### ISSUE THREAD

**Issue by Demonbream** [Masuzu/ZooeyBot#1153]
Trying to slime for more than 15 minutes at a time(campaign quest) before having to manually refill ap but zooey keeps failing to refill ap.  
I notice that command prompt keeps inaccurately reporting cost as 0 AP. I don't see where to edit this in the ini. Not sure if it has anything to do with failure to refill...

using 3.7.3 on chromium  71.0.3547.0

**Comment by Demonbream** [comment]
It works fine on shiny slime search. It is also accurately reporting ap cost. I guess campaign quest changing ap cost is a problem for zooey?

**Comment by iSDestiny** [comment]
Use customized scheduling. #1085
