### ISSUE TITLE
Choose between Xeno Cocy or Xeno Vohu raids

### ISSUE THREAD

**Issue by Zbterr** [Masuzu/ZooeyBot#1158]
Basically, when setting it to auto the Xeno Raids, it will choose the first one listed, which is Cocytus, so you cant choose Vohu, i think this stems from the time the feature was created; because we didnt have double xenos back then, any solution to this or how to choose Vohu instead of Cocytus?

**Comment by talran** [comment]
Create a schedule to access the raid as such:

```
SetLuaScript("../scripts/wind_xeno_raid.lua")
SetPreferredSummons("Tiamat Omega_2,Grimnir_1,Hamsa")
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/501081/1/0/20631", 40, 20)--xeno raid 800ap

```

**Comment by Zbterr** [comment]
Thanks! Btw, what does the 40,20 mean?

**Comment by talran** [comment]
40 is 40ap, 20 is repeat 20 times. This way you only have to use enough pots to hit 800ap if you manually ap pot

**Comment by zappky** [comment]
I bot the event as per usual using Eventmode,nothing went wrong.
I bot blue cock monster and brown librarian as per i like.

Maybe you are justing missing something? 
You could also do as per talran suggest, custom schedule to do them one after another,but you will be missing out on nightmare spawns,which are important.

**Comment by Zbterr** [comment]
You can’t auto the vohu raid because it chooses cocytus, you can however auto the extreme ones
