### ISSUE TITLE
Friend Support Summon Update

### ISSUE THREAD

**Issue by MegaBlues** [Masuzu/ZooeyBot#1161]
Recently, friend support summons were changed so that they can be reused up to 20 times in a row, and they appear at the top of your list after each battle.

Can Zooeybot and Sarasabot be changed to select the second summon in the list when rerolling summons to get around that?

**Comment by Masuzu** [comment]
Hello,
I took note of this request and will take care of it this week-end.

**Comment by Masuzu** [comment]
This is now addressed in v3.7.4!

**Comment by MegaBlues** [comment]
Thank you for the quick update!
