### ISSUE TITLE
Zooeybot not recognizing GBF Window in Versions past 3.7.1

### ISSUE THREAD

**Issue by kiaben** [Masuzu/ZooeyBot#1164]
Hello,

I have an issue with any version after 3.7.1, the bot won't recognize the GBF window.

Already tried light, normal and full animation settings but it always displays the same message. Tried reloading the extension and every version after 3.7.1 including 3.7.4.

Here is a screenshot, I am playing on GCP:

https://i.imgur.com/hHWXpnX.png

**Comment by slashkoopa** [comment]
I am having the same issue

**Comment by samuelljacksonn** [comment]
Looks like it has something to do with Zooeybot.ini.
This workaround worked for me:
I copied zooeybot.ini from an older version (3.6.5 for me) into the new version folder.

**Comment by Masuzu** [comment]
Hello,
Make sure to check the encoding of your ini file
![image](https://user-images.githubusercontent.com/5464705/57985547-54861300-7a61-11e9-9eea-2b9c5ebf063a.png)
