### ISSUE TITLE
3.8.0 half pot refill issues with frame acceleration on

### ISSUE THREAD

**Issue by samuelljacksonn** [Masuzu/ZooeyBot#1166]
Same settings between 3.7.4 and 3.8.0, except 3.8.0 has frame acceleration on. It seems like with frame acceleration on, Zooeybot is not waiting for the page to load before clicking through. I've experienced 2 outcomes:
1. Does not wait for page to load after clicking "consumables" tab, clicks on feather in the first tab instead. In 3.7.4 it waits until the page loads the consumables tab completely
2. Loads the consumables tab but clicks on the soul balms instead

**Comment by Masuzu** [comment]
Thanks for reporting this, I will release a patch for this later today.

**Comment by Masuzu** [comment]
This should be addressed in v3.8.1
