### ISSUE TITLE
3.8.0 skill usage with frame acceleration on

### ISSUE THREAD

**Issue by skadoo** [Masuzu/ZooeyBot#1167]
I tried adjusting the minimum wait time for each individual but it seems that no matter how much i adjust it, i still can't stop the "processing" wait time because the skills are being cast too quick/fast with frame acceleration on.

**Comment by skadoo** [comment]
Actually, could just be the game getting updated today and responding very slow. Will update again later to test around and see if it works just fine.

**Comment by Masuzu** [comment]
Hi,
Keep in mind that even if the animations play faster, the lockout remains the same (it is on the server side and not controllable on the client side).

**Comment by skadoo** [comment]
Hey, thanks for fast reply! Yep, i was aware of that. I think it is possible i was just having hiccups earlier when i was playing at home after the server updated. But thanks for clarification!
