### ISSUE TITLE
Crash at nm95 50% HP

### ISSUE THREAD

**Issue by ErogeSeiyuu** [Masuzu/ZooeyBot#1169]
```
if turn == 1 then
	EnableChargeAttack()
	character_4:UseSkill(3)
	character_3:UseSkill(1)
	character_3:UseSkill(2)
	character_2:UseSkill(3)
	character_2:UseSkill(1)
 if character_1.charge_gauge < 100 then
	character_2:UseSkill(2)
 end
	Summon(3)
	character_1:UseSkill(1)
	character_1:UseSkill(3)
	character_1:UseSkill(4)
end
if turn == 2 then
	character_3:UseSkill(3)
end
if turn == 3 then
	character_4:UseSkill(1)
end
if enemy_1.hp_percentage < 55 and enemy_1.hp_percentage > 50 then
	character_4:UseSkill(2)
end
if enemy_1.hp_percentage < 31 and enemy_1.hp_percentage > 25 and character_4.skill_4_available == true then
	character_4:UseSkill(1)
end
if enemy_1.hp_percentage < 25 and enemy_1.hp_percentage > 15 then
	Summon(2)
end
if character_1.skill_3_available == true and character_1.charge_gauge > 40 then
	character_1:UseSkill(1)
	character_1:UseSkill(3)
	character_1:UseSkill(4)
end
-- healing
if character_1.hp_percentage <= 70 then
	UseSupportPotion()
end
if character_2.hp_percentage <= 65 then
	UseSupportPotion()
end
if character_3.hp_percentage <= 65 then
	UseSupportPotion()
end
if character_4.hp_percentage <= 65 then
	UseSupportPotion()
end
if turn > 3 then
 if character_3.charge_gauge < 60 and character_3.skill_3_available == true then
	character_3.UseSkill(3)
 end
 if enemy_1.break_state == false and character_2.skill_3_available == true then
	character_2:UseSkill(3)
 end
	character_2:UseSkill(1)
	character_4:UseSkill(3)
 if character_4.skill_4_available == true and enemy_1.hp_percentage > 4 then
	character_4:UseSkill(4)
 end
end
```
Zoi keeps crashing at around 45~55% hp in NM95, is there something wrong with the code I wrote?
It keeps crashing with no error message.

**Comment by Masuzu** [comment]
I think it is boss-specific, so I will have to check later.

**Comment by xerance** [comment]
second this

**Comment by lamewood** [comment]
yesterday i could run the bot solonm95 over 10h straight without any issues, but today it crashed randomly after 1-3 raids each time without me changing anything on the working script

**Comment by MegaBlues** [comment]
You should set custom booleans/numbers to use Support Potions so that the bot won't attempt to use them when you run out. You should also set a wait time before and after using them so that the screen has a chance to fall into a neutral position beforehand, avoiding crashes.

**Comment by MegaBlues** [comment]
Here are some examples of potion-use scripts I use. They're not perfect, but they'd make a good springboard for you to write your own trigger-based scripts.

```
if turn == 1 then
	booleans["GottenBackup"] = false
	numbers["GreenPot"] = 2
	numbers["BluePot"] = 1
end

if enemy_1.hp_percentage <= 75 and booleans["GottenBackup"] == false then
	Wait(5000)
	RequestBackup()
	Wait(5000)
	booleans["GottenBackup"] = true
	numbers["BluePot"] = numbers["BluePot"] + 1
end

if enemy_1.hp_percentage <= 50 and numbers["BluePot"] > 0 then
	Wait(2000)
	UseBluePotion()
	numbers["BluePot"] = numbers["BluePot"] - 1
	Wait(2000)
end

if numbers["GreenPot"] > 0 then
	if characters["De La Fille"] == nil or characters["De La Fille"].skill_2_available == false then
		if character_1 ~= nil and character_1.hp_percentage < 30 then
		UseGreenPotionOnPartyMember(1)
		numbers["GreenPot"] = numbers["GreenPot"] - 1
		end
		if character_2 ~= nil and character_2.hp_percentage < 30 then
		UseGreenPotionOnPartyMember(2)
		numbers["GreenPot"] = numbers["GreenPot"] - 1
		end
		if character_3 ~= nil and character_3.hp_percentage < 30 then
		UseGreenPotionOnPartyMember(3)
		numbers["GreenPot"] = numbers["GreenPot"] - 1
		end
		if character_4 ~= nil and character_4.hp_percentage < 30 then
		UseGreenPotionOnPartyMember(4)
		numbers["GreenPot"] = numbers["GreenPot"] - 1
		end
	end
end
```

**Comment by samuelljacksonn** [comment]
This seems to be happening to me as well, and I'm not using any potions. Yesterday same script was working fine. Zooeybot just closes

**Comment by xerance** [comment]
If it helps, every crash is after a summon is used for me.

**Comment by ErogeSeiyuu** [comment]
it's after Alex using her 2 for me.

**Comment by Masuzu** [comment]
A change was added yesterday to swallow possible errors.

https://github.com/Masuzu/ZooeyBot/issues/1169#issuecomment-495574261 that will be helpful, thanks.

**Comment by Demonbream** [comment]
was the change added in 3.8.2 because Its still crashing for me. I'll verify the exact moment when day 4 opens.

**Comment by lamewood** [comment]
I've had crash issues too. Most of them were resolved when I added "Wait(500)" here and there, but my nm95/nm100 just won't work if I have 
if enemy_1:HasStatusEffect("1931_14") then
character_1:UseSkill(3)
end
in it. after using all queued skills in turn 1, the bot checks the status effect and crashes
it worked at some point for 10 hours in nm95, but later it crashed.

**Comment by ErogeSeiyuu** [comment]
no matter how much I change my code

> Remove status clear
> remove boss HP check
> remove characters self check (status check, charge bar check) etc. 
> make it as simple and as straight forward as possible (turn 1 do this, turn 2 do this, turn 3 do this, end, nothing else)

the bot always stop on turn 3 regardless if I have skill queued for turn 3 or even if there's no skills queued for turn 3 at all.

**Comment by Masuzu** [comment]
It might have to do with some new weird status they added for this boss.
If you set the parameter `kDebugLuaScriptLoading` to true, a list of letters should be displayed and the last ones displayed will help identifying the issue.

**Comment by ErogeSeiyuu** [comment]
It goes from:
Before turn 1:
> ABCDCDCDCDCDCDEFFFGHI loading lua script
During and After turn 1, 2, 3  etc.
> BCCCCCCDDDDEE (select skills, select character etc.)
 Turn 3 crash:
```
Battle 1 turn 3
Attack
BCCCCCCDDDDEE Enemy at position 1 is in overdrive state
Chain burst with 3 characters.
Refresh
New page loaded: <...>
ABCDCDCDCDCDCDEFFFFGHILoading Lua script: <...>
```

**Comment by ErogeSeiyuu** [comment]
.lua used:
```
if turn == 1 then
	booleans["GottenBackup"] = false
end
if turn == 1 and booleans["GottenBackup"] == false then
	RequestBackup()
	Wait(2000)
	booleans["GottenBackup"] = true
	EnableChargeAttack()
	character_4:UseSkill(3)
	character_4:UseSkill(2)
	character_3:UseSkill(1)
	character_3:UseSkill(2)
	character_2:UseSkill(3)
	character_2:UseSkill(1)
	Summon(3)
	character_1:UseSkill(1)
	character_1:UseSkill(3)
	character_1:UseSkill(4)
end
if turn == 2 then
	character_3:UseSkill(3)
end
if turn == 3 then
	character_4:UseSkill(1)
end
if turn == 6 then
	UseSupportPotion()
end
if turn == 8 then
	UseSupportPotion()
end
if turn == 10 then
	UseSupportPotion()
end
if turn >= 8 then
	character_4:UseSkill(1)
	Summon(4)
end
if character_1.skill_3_available == true and character_1.charge_gauge >= 40 then
	character_1:UseSkill(1)
	character_1:UseSkill(3)
	character_1:UseSkill(4)
end
if turn >= 4 then
	character_3.UseSkill(3)
	character_4:UseSkill(1)
	character_3.UseSkill(1)
	character_2:UseSkill(3)
	character_2:UseSkill(1)
	character_2:UseSkill(4)
end
```

**Comment by ErogeSeiyuu** [comment]
Updated to 3.8.3 it's still crashing.

**Comment by gold-nugget** [comment]
mine keeps disappearing randomly when GW was running.
but, it's guaranteed to break on scheduled.lua

**Comment by Masuzu** [comment]
@ErogeSeiyuu you had a syntax error in the if turn == 4 block: it should be a `:` instead of a |.`
