### ISSUE TITLE
Bot is stuck at clicking Support Summons at 1366 x 768 resolution

### ISSUE THREAD

**Issue by kururugikai** [Masuzu/ZooeyBot#117]
Perhaps due to bad scaling or anythings, my Bot keep falling at picking support summon .
the games automatically make the support summon notification a little bit higher, just like in the picture i attach

![screenhunter_03 jun 18 09 56](https://user-images.githubusercontent.com/29514091/27257746-7f2183b0-540c-11e7-829e-698fdf3531e6.gif)

Do you have a way to solve this problem

btw,
i am using your poker bot but so far there is no problem, and its great! thank you!

**Comment by ariaanaa** [comment]
change your screen rotation to portrait (ctrl+alt+arrow left key), i have use this method for my laptop and its work
