### ISSUE TITLE
refill AP didn't work well

### ISSUE THREAD

**Issue by Necoboro** [Masuzu/ZooeyBot#1170]
I use Event Mode for several days.Every time when AP isn't enough,Zooey Bot just went into Item Page and stop work.
Should I change the Zooey‘s config or browser's config so that AP could be refilled?
Thanks.

**Comment by Masuzu** [comment]
Hi,
Unfortunately, without more details I won't be able to help, since I can't reproduce the issue.

**Comment by Necoboro** [comment]
![image](https://user-images.githubusercontent.com/25545825/58225458-b641c800-7d54-11e9-9866-16ec4e535576.png)
Zooey didn't show anything so I couldn't tell any details about the issue.What can I do to solve the issue?just like checking the log?

**Comment by Masuzu** [comment]
Ah it looks like you are using an extension, therefore this time around there is no bug on Zooey Bot side :)
On a vanilla version of the game you should have 3 widgets under Items:
Treasures, Consumables, Tickets
