### ISSUE TITLE
Use [EnableFpsAcceleration] without automation

### ISSUE THREAD

**Issue by hazamukara** [Masuzu/ZooeyBot#1171]
Hello,

Is it possible to use [EnableFpsAcceleration] without using Event or Treasure Mode? I wanted to play manual but with [EnableFpsAcceleration].

I tried enabling [ListenerMode] to try but it's stuck on Initiation 3/3

**Comment by Masuzu** [comment]
Hello,
There is no plan for this, but https://gbtools.azurewebsites.net/CombatSniffer/en/Home does exactly this.
