### ISSUE TITLE
BOT stuck when the enemy is defeated by others

### ISSUE THREAD

**Issue by GBFUSER1993** [Masuzu/ZooeyBot#1173]
Just like The title states
This GW, I am using the request backup feature to gain honors with guild member's help in hell 100

However, when the enemy was defeated by other people, which the game screen showed on "the battle was ended", zooey bot won't process further.

I Guess zooey bot can't detect the end of the battle by others help. Is there anyway to let the bot detect correctly and do further raids?

BTW, the bot won't detect the end of battle if my team was all knock out. Anyway to fix this too?

**Comment by hazamukara** [comment]
You could try this one, not sure if it works. Technically should work.
```
if enemy_1.hp_percentage < 1then
    TerminateBattle()
end
```

**Comment by Masuzu** [comment]
Hi,
Zooey was never designed from the start to support this feature.
If you still want to use it though, the best thing is to enable Viramate shortcuts and to use Viramate with only the combat shortcuts enabled.
