### ISSUE TITLE
TrialBattleMode goes to item page

### ISSUE THREAD

**Issue by JillVernus** [Masuzu/ZooeyBot#1174]
Trying to debug my lua script by using TrialBattleMode . 

I have set TrialBattleMode = true , lua file path to combat section.

turn on ZooeyBot, press Enter , 
calibration OK,
Get into the TrialBattle stage, press Enter to allow ZooeyBot take over. 
then ZooeyBot nevigate to item page and use 20 soul berries

![20190524](https://user-images.githubusercontent.com/28760023/58302970-5dd7fc80-7e20-11e9-9f74-8d8b53ce3ffe.jpg)

**Comment by UminekoScarlet** [comment]
Same for me. No matter what I do, it always goes to the item page and uses soul berries.

**Comment by Masuzu** [comment]
Oh, thank you for reporting this and apologies for the inconvenience.
It is a bug indeed.
