### ISSUE TITLE
Has the button certification changed a bit?

### ISSUE THREAD

**Issue by himappe** [Masuzu/ZooeyBot#1176]
Has the button certification changed a bit? Are you compatible?
![CC8E12DD-8EF3-49F6-B98C-E020DA06A5C8](https://user-images.githubusercontent.com/29257104/58311476-0a77a580-7e44-11e9-8a22-1371d4add9d6.png)
![A0327A92-C3C5-4D19-8079-D5AB9C251EC8](https://user-images.githubusercontent.com/29257104/58311477-0b103c00-7e44-11e9-9cf6-c14a12b31b81.png)

**Comment by hazamukara** [comment]
It's always been there, plus yeah it's compatible.

**Comment by Masuzu** [comment]
As answered by @hazamukara
