### ISSUE TITLE
Slavemode  main account not attacking Zooey 1.9.10

### ISSUE THREAD

**Issue by arthurneo** [Masuzu/ZooeyBot#118]
Had the same issue in 1.9.8

Main account doesn't attack either becuase it doesnt find the attack, or because after the slave turns it says the battle ended. (attaching console pic)

(No viramate) 
Things I have tried.
1. Restarting chrome - didn't work.
2. redownloading zooey . no change.
3. change the slave and the main account -  no effect.
4. acctivating Process MainAccountTurnFirst (it got stuck on an endless refreshing loop because it didn't found the attack button).
5. Using scripts for main account . No change.
6. Deactivating scripts for both. No change.
7. RelodpageonLastbattle Is set to false.
8. do not wait for server response is set to fale (otherwise summons failed and zooey crashed)
![slaveboterror](https://user-images.githubusercontent.com/29359181/27258043-9d256370-53b4-11e7-9fc8-0cf7b3ad3bb7.JPG)

also after refreshing the man account sometimes slave bot desynchronizes and doesnt hook to the attack button on the slave account.  haven't found an exact when, but it seems common and random, been attempting to change the distance between windoes and using the ones in the faq as a guide but no avail

**Comment by reinharto** [comment]
I got it to work if I put the main account in incognito window and slave in regular chrome window if you want to try that.

**Comment by arthurneo** [comment]
gonna give it a try. thanks reinharto

**Comment by arthurneo** [comment]
didn't work, updated to zooey 1.9.11 no change :(

**Comment by reinharto** [comment]
Turn out the older version work much better for me. I just use the 1.0.0 version on a separate folder to slime now.

**Comment by arthurneo** [comment]
Mazuzu no suggestions or troubleshoot?
