### ISSUE TITLE
Does GBFCombatSniffer integrate with Zooeybot?

### ISSUE THREAD

**Issue by ramblinguy** [Masuzu/ZooeyBot#1180]
I'm wondering if it's possible for Zooeybot to use keyboard shortcuts (or if it's still safe to do so after the recent bans). I don't want to use Viramate, and it sounds like GBF Combat Sniffer has gotten most of what I would want anyways. Question is, can Zooeybot/Sarasabot use keyboard shortcuts from GBFCombatSniffer and is it safe to do so?

**Comment by ramblinguy** [comment]
Sorry if this isn't the right place to ask, I tried searching the past issues but couldn't find anything related to this.

**Comment by Masuzu** [comment]
Hello,
Not for now but I plan to have combat shortcuts available in Zooey Bot, the same way as with Sarasa Bot in one of the last releases.

**Comment by ramblinguy** [comment]
Ah ok, that's good to know. Thanks!
