### ISSUE TITLE
I got banned.

### ISSUE THREAD

**Issue by DarkHorse1121** [Masuzu/ZooeyBot#1183]
I got banned with Zooeybot for 1 month.

**Comment by soomore** [comment]
Did you use acceleration or viramate?

**Comment by DarkHorse1121** [comment]
Yes, I used acceleration.
We have to be attention.

**Comment by takashiiiiii** [comment]
I used acceleration of a zooey bot.
This is dangerous.
https://i.imgur.com/eRRzdmg.jpg
                                                                     by takashi

**Comment by takashiiiiii** [comment]
I was banned.
I used acceleration of a zooey bot.
It is a dangerous.
https://i.imgur.com/eRRzdmg.jpg                         by takashi

**Comment by kusyarudaora123** [comment]
It was not BAN without using acceleration.
I think it's still safe if you don't use acceleration

**Comment by takashiiiiii** [comment]
I think so.
Please, delete acceleration.

**Comment by Sasamitatami** [comment]
Yeah same here, got ban when using the acceleration
http://imgur.com/gallery/FMzTtRM

**Comment by takashiiiiii** [comment]
Chinese acceleration, not BAN.
Why is it?

**Comment by 1uminated** [comment]
BTW just as a warning, if you are caught tooling during GW from here on, you account will be flagged from (1) gaining honor during GW, (2) joining raid with ID and (3) banned from coop. Bot has been "safe" but I'm not taking the risk with stakes like these.

https://twitter.com/granbluefantasy/status/1132996195268251653

**Comment by NzString** [comment]
I checked for anti-cheat bypass on the Chinese tool.
Chinese tool anti-cheat bypass works before my personal anti-cheat bypass.

But When I used zooey accelerator, My personal anti-cheat bypass work first.
@Masuzu Does zooey accelerator has anti-cheat bypass?

And I got banned my alt account using Chinese tool.
[https://imgur.com/u3CunyB](url)
There're some problem with bot or accel.

**Comment by ghosimage1** [comment]
How do I check if my acceleration is turn on or off?

**Comment by takashiiiiii** [comment]
> How do I check if my acceleration is turn on or off?
[Combat]
# If set to true, increase the in-game frame rate. The feature is disabled by default.
EnableFpsAcceleration=false

EnableFpsAcceleration=true -> ON
EnableFpsAcceleration=false -> OFF

**Comment by takashiiiiii** [comment]
> How do I check if my acceleration is turn on or off?
[Combat]
If set to true, increase the in-game frame rate. The feature is disabled by default.
EnableFpsAcceleration=false

EnableFpsAcceleration=true -> ON
EnableFpsAcceleration=false -> OFF

**Comment by ghosimage1** [comment]
@takashi Thanks for the reply.
As long as it is off, it will be much safer to bot ya?

**Comment by takashiiiiii** [comment]
> @takashi Thanks for the reply.
> As long as it is off, it will be much safer to bot ya?

Yes. 
Only acceleration is dangerous.
I used acceleration in a war for 68 hours.

**Comment by Sasamitatami** [comment]
> Yes.
Only acceleration is dangerous.
I used acceleration in a war for 68 hours

I only use for 2hr still banned

**Comment by Chololoco13** [comment]
I was testing the Chinese bot with the acceleration for two days and I was not banned but I read from people who have been banned.
Maybe the problem in both tools is that option

**Comment by cobeng13** [comment]
What Chinese Bot are you talking about?

**Comment by UthurPen** [comment]
Might be the one that someone took a picture of

**Comment by UthurPen** [comment]
Still no matter what bot it is might be better turn off any speed or acceleration hack for now

**Comment by takashiiiiii** [comment]
> What Chinese Bot are you talking about?

I know this Chinese bot.
But when I told, MASUZU gets angry.
It'll be business interference.

**Comment by takashiiiiii** [comment]
A Chinese bot is being also accelerated now.
Chinese are also killing Ultimate Bahamut at high speed now.
This is a problem between the Japanese famous player.
Masuzu also accelerates added one because of this.

**Comment by takashiiiiii** [comment]
https://twitter.com/sakuya1617/status/1129328154948976640

Please see this.
I know.
Chinese skip the first animation. And it's fast.
Chinese would destroy a game eventually.

**Comment by takashiiiiii** [comment]
Why isn't Masuzu announced?
This is a serious defect.
If there are no announcements, I put the name of Chinese bot.

**Comment by Sundaerae** [comment]
tbh, I think @Masuzu stop caring about the bots from a while ago. We only see him once every 3 weeks/ 1 month now.

So even if you put the name out, he'd only realize it 2 weeks later.

**Comment by takashiiiiii** [comment]
I see, I exhibit the name of the Chinese tool.
This name is "罐子屋".
https://world.taobao.com/item/564271055165.htm

Chinese BOT is more excellent than ZooeyBot.
This has not been even prohibited by acceleration.
I replace it with this.
Good-bye

**Comment by NzString** [comment]
@takashiiiiii Did you use chinese auto bot?

**Comment by takashiiiiii** [comment]
Chinese's friend told that to me.
Chinese people use this.

**Comment by takashiiiiii** [comment]
Chinese tool test movie
https://www.nicovideo.jp/watch/sm35195430

**Comment by Mrbanana123** [comment]
@takashiiiiii Do you have any idea how to use character skills?
and how does the co-op with multiple accounts work?

**Comment by takashiiiiii** [comment]
Chinese bot can use a skill automatically. 
But I don't know whether that can do Slime blast.

**Comment by Mrbanana123** [comment]
i see.
It's a bit difficult to understand how it works, for short fights it's quite simple but I do not understand how it would be in long fights.
https://puu.sh/DznIM/7fb8f65156.png

**Comment by takashiiiiii** [comment]
Sorry.
My account is banned, so I can't use Chinese Bot yet.
I used acceleration of a zooey bot.
So I can't explain.

**Comment by devvah** [comment]
Everyone would use Chinese bot.... if they knew chinese.

To make it even worse dude posted all about bot in images so we can't even use translator for this.

So until someone kind makes full guide for that bot we're stuck there.

Hopefully Masuzu will wake up from his own gbf server fever that I'm not sure who would want to play and gets back to improving bots.

There's still no upgrade bot 5 years into game despite it being one of worst chores and more and more bahamut skill lvling weapons are released.

**Comment by Sundaerae** [comment]
Well, I don't need any more feature other than fixing/stabilizing zooey/sarasa bot. But we can't even have that. 

Why we can't have that? because here we are 4 days talking about chinese bot and masuzu didn't even realize. I'll comment here again after a week and see how far we can go ;)

**Comment by UthurPen** [comment]
Well since takashi basically advertised the bot here are its features
Speeshack,Auto-farming(nm included),auto co-op,auto-join pubbed raids
Setting up the skills are a bit confusing but once you get used to its easy to do

**Comment by Masuzu** [comment]
The TLDR summary of this is that FPS acceleration should be turned off if you would like to be on the safe side:
```
EnableFpsAcceleration=false
```
(or not having this parameter defined either in the ZooeyBot.ini settings boils down to having acceleration disabled as well).

Please do deep in mind that detecting client side FPS changes is easy on their side: for instance it would simply require moving the detection code elsewhere or obfuscating it to have it bypass anti-anticheat bypassers.
