### ISSUE TITLE
Nightmare mode ignored.

### ISSUE THREAD

**Issue by Hildibrand** [Masuzu/ZooeyBot#1187]
Hella, using TreasureEvent mode and when Nightmare pops up, it tends to be ignored, spamming Extreme raid endlessly. It tends to happen randomly, because I've been using it for a few days on this event and I've seen ZooeyBot running NM correctly. It just starts ignoring them at (seemingly) random.

Currently using this config and always starting without NM active:

> NightmareModeUrl=http://game.granbluefantasy.jp/#quest/supporter/741121/3
> NightmareModeScript=Scripts/rainbowNM.lua
> NightmareModePreferredSummons=Grimnir, Raphael
> RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
> NightmareModeAvailableAtStart=false 

Also, sometimes an incorrect summon is selected. I've catched the program picking Tiamat and still telling in the command window that it was Grimnir.
What is causing these issues?

**Comment by Masuzu** [comment]
Hello,
Picking incorrect summons used to happen with summon reordering with Viramate for instance. I could see this happening as well if, after trying to pick the summon, the page is reloaded, resulting in a new ordering of summon.

Regarding the Nightmare mode, I am not sure if recent in-game changes could have caused as I've seen none, but will go for another round this weekend.

**Comment by Masuzu** [comment]
Unfortunately, doubled checked and won't fix unless some actual recorded footage is provided as evidence. I will upload mine later in the week-end. It could be due to a delay loading the summons (on that side several checks are already in place) or scrolling speed

Chasing that +0.X% is not the best optimisation possible.

**Comment by Hildibrand** [comment]
Alright, I'll try to record it because as far as I remember it's something that it has been happening for a good while (2-3 months maybe): when I stop the bot, I check the event page and Nightmare is up and 40-20 minutes are left for it, so the bot has just been spamming extreme.
Do I close the issue and open another one when I have proof, or just leave this one opened??

**Comment by Masuzu** [comment]
Thank you, let's just leave this one open then.
It is only 1h20 but I completed the event now with nothing suspicious to report.
https://www.youtube.com/watch?v=yEgiTGDcSp0
