### ISSUE TITLE
i have no idea how to startthis

### ISSUE THREAD

**Issue by randylaw321** [Masuzu/ZooeyBot#1188]
I cant start the bot it keeps saying "Zooey bot, your friendly co-op companion, is waiting for orders" then when I start up the zooey file it says no granblue is found wtf am i doing wrong please help

**Comment by Necoboro** [comment]
maybe your languege config is wrong.

**Comment by randylaw321** [comment]
> Maybe your languege config is wrong.You should read the FAQ so that you can solve it by yourself

i read the faq i still have no idea how to use it to farm anything makes no sense at all maybe u can help me??

**Comment by takashiiiiii** [comment]
If that can be started, setting of ini is probably strange.

[General]
Possible values: jp, en. Default to en when the string is malformed. Please make sure that your configuration file is encoded using UTF8 if you use non Unicode characters.
Language=en ←OK？not jp

[Summons]
Comma-delimited list of summons which will be selected in priority if they are available
PreferredSummons=Kaguya,White Rabbit　←PreggerredSummon OK?
In case none of the preferred summons was found, select a random summon in the given summon attribute tab, unless the parameter RerollSummonWhenNoPreferredSummonWasFound is set to true.
Possible values are 'misc' (Kaguya, White Rabbit fall into this category), 'fire', 'water', 'earth', 'wind', 'light' or 'dark'.
 Not case-sensitive.
DefaultSummonAttributeTab=misc　←PreggerredTab OK?
Zooey will reroll summons until one of the preferred summons is available, using trial battles to refresh the summon list. This does not apply to the summon selection for the nightmare stage (see the EventMode section).
RerollSummonWhenNoPreferredSummonWasFound=false

[EventMode]
 Set this parameter to true to use the event mode. Zooey will enter autopilot mode when you navigate to the quest menu.
Enabled=true　←true = Event mode ON OK?
 Url of the summon selection page for Angel Halo (Extreme)
EventRaidUrl= ←event page URL please (Select Summon page URL)
EventRaidScript= ←(ex.Scripts/xxxxxx.lua) if u can make lua program
 Url of the summon selection page for Dimensional Halo
NightmareModeUrl=
NightmareModeScript=
 Some events such as Rise of the Beasts require to navigate to the home page of the event before navigating to the event raid url defined above. If EventPageUrl is provided, Zooey will first navigate to this url before hosting the raid. Leave EventPageUrl blank for events which do not require you to do so.
EventPageUrl=

**Comment by cahya0307** [comment]
Please make tutorial video for that


I don't understand either :'(

**Comment by takashiiiiii** [comment]
Zooey bot is difficult.
Knowledge of setting is needed.
And they're unkind.

I'm Japanese, so I can't explain in English well.
The legal measure is also fearful.

If it doesn't move no matter what, it should be replaced.
This is Chinese tool. Knowledge isn't necessary.
Most setting can be done only by on-off of a button.
https://world.taobao.com/item/564271055165.htm

**Comment by takashiiiiii** [comment]
The knowledge of lua is also necessary and troublesome.
That's out-of-date already. And safety was also lost.
Masuzu failed in acceleration.

**Comment by cahya0307** [comment]
I see so i think its useless for me xD

Already try to learn lua but still doesnt undestand xD

**Comment by takashiiiiii** [comment]
If you need, ini file which is already set can be offered.
But it won't be a fundamental solution.
Please tell me where to stop.

**Comment by takashiiiiii** [comment]
When you can set ini, lua should consult here.
https://github.com/Masuzu/ZooeyBot/tree/master/Scripts

Everything is on the meaning of the script here.
https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts

Recommended lua software.
Notepad++
https://notepad-plus-plus.org/

**Comment by Masuzu** [comment]
Thanks to the people who helped.
