### ISSUE TITLE
Can't launch slave mode during Initializaiton 6/6

### ISSUE THREAD

**Issue by rnelty** [Masuzu/ZooeyBot#119]
Initialization 6/6 after press the enter, Zooey(1.9.7~1.9.12) didn't work out.
![2017-06-20_18-20-51](https://user-images.githubusercontent.com/15686949/27326212-d7f57fc0-55e5-11e7-96cf-79d17c938021.png)

cursor going to move chrome devtools window,it doesn't move from there.
No message after calibrating
![2017-06-20_18-26-01](https://user-images.githubusercontent.com/15686949/27326498-8eb68d58-55e6-11e7-9845-d50c97382335.png)

i got stuckkked

**Comment by Masuzu** [comment]
Did you make sure to have the Chrome DevTools windows docked to each window?
Otherwise, I ran sometimes into this issue when I was trying to start a new slime blasting session.
I just had to close and reopen both Chrome browser windows to get past the calibration phase.
