### ISSUE TITLE
[Treasure Mode] 3.9.0 Bot doesn't stop after reaching set amount of potions.

### ISSUE THREAD

**Issue by devvah** [Masuzu/ZooeyBot#1191]
After bot uses AP from last round of refills it will continue to try to fight boss which ends with pots pop up displayed and got infinitely clicking on it, in my case I choose VH raid which ended with bot somehow picking 10 full pots to refill and clicking few times confirm button but fortunately game doesn't allow for more than 999 AP.

Edit: Seems like it happens at random when reaching 0 AP.

Also when for some reason game takes longer to answer bot starts refreshing until it somehow ends at "http://game.granbluefantasy.jp/" not sure what caused this.

**Comment by Masuzu** [comment]
Hello,
This issue (not taking into account the max number of potions to use) was addressed in v3.9.1
