### ISSUE TITLE
How to set different script for different party for Proving Ground??

### ISSUE THREAD

**Issue by RedMagus** [Masuzu/ZooeyBot#1193]
Since each of my party for every round of Proving Grounds is so different from each other, they can't share the same script because it will mess up my fight composition and things can easily go wrong from there. I don't see the parameters that tell which party to use a certain script. Is it because the bot never designed this way or I'm missing something here?

**Comment by Masuzu** [comment]
Hello,
Each battle being different, you can simply use the battle count:
```
if battle == 1 then
  // Do things with your first party
elseif battle == 2 then
  ...
elseif battle == 3 then
end
```
