### ISSUE TITLE
Can't change serial number.

### ISSUE THREAD

**Issue by kiaben** [Masuzu/ZooeyBot#1194]
Hello,

I am trying to change my serial number but I just get this error:

https://i.imgur.com/mVnzo3H.png

**Comment by kiaben** [comment]
After going through the existing issues it might be windows updates. I am using GCP and my trial ran out so I am switching to a new account. 

But I am unable to switch my serial, still have 20 days on my current licence so I really don't want to buy another one just because of it.

**Comment by Masuzu** [comment]
Hello,
I think you must be trying to change your serial number to another serial number already in use by another user. https://gbtools.azurewebsites.net/en/Account/ForgotEmail and inputting the serial number you are trying to set will tell you if it is already in use by someone else.
