### ISSUE TITLE
Stop when nightmare mode pops up.

### ISSUE THREAD

**Issue by Hildibrand** [Masuzu/ZooeyBot#1195]
Hella, I know there's an option to display a notification when nightmare mode pops up; however, it doesn't work in Event mode for farming RotB. Point is, since a backup option hasn't been implemented and I can't solo the nightmare mode on my own: is there a way to command ZooeyBot to do 8 raids and stop?
Scheduling doesn't work for RotB.

**Comment by ladysour** [comment]
What do you mean by scheduling doesn'y work? You can find my rotb block from scheduling.lua below, it's a bit lame but does get the job done(I tried after seeing this post). I was thinking of implementing the nightmare modes after the 8 raids complete but it's too much effort to check which one will be in rotation(with my skills at least). 

Here you go:

`-- --RotB
SetEventPageUrl("http://game.granbluefantasy.jp/#event/advent")
SetLuaScript("Scripts/rotbdark.lua")
SetPreferredSummons("Bahamut, Kaguya, Hades, Celeste")
RerollSummonWhenNoPreferredSummonWasFound=true
SetPreferredPartyGroup("2")
SetPreferredPartyDeck("2")
Assert4SymbolsPendantsBelow(100000)
-- --Water
-- --RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/711041/1", 20, 8)
-- --Earth
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/711141/1", 20, 8)
-- --Wind
-- --RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/711091/1", 20, 8)
-- --Fire
-- --RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/711191/1", 20, 8)`

**Comment by ladysour** [comment]
You are most likely missing the 

SetEventPageUrl("http://game.granbluefantasy.jp/#event/advent")

string
