### ISSUE TITLE
Scheduling not working for RotB.

### ISSUE THREAD

**Issue by Hildibrand** [Masuzu/ZooeyBot#1196]
Excuse me for creating two threads, but the last one was locked before I could reply.
I tried using scheduling for RotB using @ladysour's scheduling block, as shown:

> --RotB--
> 
> SetEventPageUrl("http://game.granbluefantasy.jp/#event/advent")
> SetLuaScript("Scripts/rotbdark.lua")
> SetPreferredSummons("Bahamut, Kaguya, Hades, Celeste")
> RerollSummonWhenNoPreferredSummonWasFound=true
> SetPreferredPartyGroup("2")
> SetPreferredPartyDeck("2")
> Assert4SymbolsPendantsBelow(100000)
> 
> --Water--
> --RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/711041/1", 20, 8)
> 
> --Earth--
> RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/711141/1", 20, 8)
> 
> --Wind--
> --RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/711091/1", 20, 8)
> 
> --Fire--
> --RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/711191/1", 20, 8)

But whenever I try to activate ZooeyBot after entering the Quest page, the "Done scheduling all of your raids" message pops up before doing anything else. Both the event page URL and the quest URL are valid, and the Wiki doesn't seem to mention anything else. What's wrong?

**Comment by ladysour** [comment]
Are you using notepad or notepad++ for this? Cause in my block I made everything into a comment except Baihu. My initial theory would be that the lines are misaligned and the bot interprets everything as a comment - which you would see in green colour on notepad++. Other than that I don't know really:? It works for me :/

**Comment by Hildibrand** [comment]
I have to note, I changed the selected party group but it was a valid line nonetheless. And yes, I do indeed use Notepad++ so it's displayed correctly. Quite a clever use of comments to avoid creating adittional files or editing a lot of lines.

**Comment by Masuzu** [comment]
Hi,
Did you try to change the encoding of your file to UTF8 or UTF8-BOM instead of the default? I used to run into similar issues depending on the computer language settings.

**Comment by Hildibrand** [comment]
I was using UTF8-BOM since I read about it in the Wiki somewhere. Changing the sheduling .lua file to UTF did the trick. Thanks a lot.
