### ISSUE TITLE
Enemy Selection Bug

### ISSUE THREAD

**Issue by ProjectOJ** [Masuzu/ZooeyBot#1197]
Trying to automate Xuanwu, I have my battle script set to SelectTarget(3). While this works, it opens up a new page everytime it gets to this command.

**Comment by Masuzu** [comment]
Hi,
I am afraid I do not see this happening, unless you misclick somewhere else?

**Comment by devvah** [comment]
I went through 200 badges on 3.9.8 and didn't have problem with picking middle enemy and no strange things happened.
