### ISSUE TITLE
Slave mode refill ap on main account

### ISSUE THREAD

**Issue by Birizuhh** [Masuzu/ZooeyBot#1198]
I think slave mode sometimes refill AP on my main account. I'm sure it's not because of wrong setting between slave and main. 

I can noticed this because sudden my main AP 999. Please check on this case. I used fast refill when slave too

**Comment by Masuzu** [comment]
Hi,
Please check the new setup instructions on https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)
You should not use the incognito node anymore.
