### ISSUE TITLE
Constant refreshing on CAPTCHA

### ISSUE THREAD

**Issue by almartn123** [Masuzu/ZooeyBot#12]
Playing GBF too long prompts a CAPTCHA.
ZooeyBot doesnt stop at the CAPTCHA when playing (botting) too long.
Left it at an hour expecting for it to not pop up; however it did and constantly refreshed as it couldn't continue on past it as the pop out kept happening.
Had to manually stop it and put in the code.
Please add a way to stop ZooeyBot if the CAPTCHA pops up.
-don't have screenshot due to thinking I was safe

**Comment by Masuzu** [comment]
This is something I will fix as soon as possible. I would just need 2 pieces of information please:
- On which page did you get the captcha pop up (summon selection, other page?)
- Did a message window from Zooey saying that "Captcha" appeared?
If so there is a trivial fix and I will do it as soon as possible.

**Comment by po456asd** [comment]
normally captcha can appear on all page except stage page isn't it? 
never heard about that before

**Comment by Masuzu** [comment]
It can only appear during the summon selection page or when you press ready/start in the coop room.
