### ISSUE TITLE
Zooey bot keeps refreshing quest and doesnt startn (slime mode)

### ISSUE THREAD

**Issue by Zoichan** [Masuzu/ZooeyBot#120]
https://gyazo.com/0fa7da117968b5274a04089b997173d4
Here is my issue. After calibrating and F5 to refresh the Slave window, with both account ready with the quest, I pressed Enter. But Zooey doesnt start the quest. It keeps refreshing the address of the coop room in the main account windows. I dont know what to do. 
Please help.

**Comment by Masuzu** [comment]
Hi,
I ran into the exact same issue during a solo slime session and fixed this in the version 1.9.12:
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes
