### ISSUE TITLE
serial number issue

### ISSUE THREAD

**Issue by mmisosoup** [Masuzu/ZooeyBot#1201]
I made a typo in my email while I was registering for an account, so the verification email was sent to an email that doesn't exist. Is there a way to get a new serial number for my laptop or to start the registration process over again?

**Comment by Masuzu** [comment]
Hello,
I will purge non confirmed accounts later today and let you know once it is done.

**Comment by Masuzu** [comment]
The cleanup is now done. You should be able to reuse the same serial number.
