### ISSUE TITLE
Zooey Bot V1.9.12 Slime Mode

### ISSUE THREAD

**Issue by ChocolateBall** [Masuzu/ZooeyBot#121]
I keep having an issue with getting the slave mode to run; no mateer how I start up the bot, I frequently keep having both the Slave ID and my Main ID be the same account.
![error](https://user-images.githubusercontent.com/29619188/27416449-30b755f6-5740-11e7-9e54-d533c1d111f0.PNG)

**Comment by Dreamfinal** [comment]
me too

**Comment by Masuzu** [comment]
Before restarting the bot, make sure to close all the devtools window, refresh the tabs or reopen the Chrome browser.
After starting the bot, open the DevTools window on the Chrome Window with the slave account and press the start button of the Zooey slave extension, then wait for the slave player ID to be displayed in the console.
Then, open the DevTools window on the Chrome Window with the main account and press the start button the Zooey extension. The player ID of your main account should then appear.

**Comment by ChocolateBall** [comment]
Took me a while to get to trying again because of GW, but I am still getting this error. Does the slave acc have to be on the incognito window or something?
