### ISSUE TITLE
Time to pull out FPSAcceleration given the recent ban wave?

### ISSUE THREAD

**Issue by Vatar** [Masuzu/ZooeyBot#1210]
Hello,

According to the latest ban wave tweets, specifically [this one](https://twitter.com/granbluefantasy/status/1141258521003978753), they banned people for using speed-up and rendering hacks, which while the recent chinese hacks, claimed to have been undetectable, is the first culprit to mind, wouldn't it affect FPS Acceleration as well? 

I haven't used it but rather for the option to be for adventurous users, it seems to be easily bannable now.

**Comment by Alissa1122** [comment]
heard this time CY is targeting the chinese bots/tools, they get the tools and try to study it’s flow (maybe disassembled the tools), so they can detect it precisely

I think they may also get Zooey too, hope they won’t get any useful information for detecting Zooey in the future

**Comment by Sasamitatami** [comment]
@Masuzu with this recent wave does zooey still safe? Not talking about the fps acceleration. I mean the general use of zooey for farming

**Comment by Masuzu** [comment]
Nothing changed indeed. Just do not use FPS acceleration.
