### ISSUE TITLE
As a result of BAN at May 27th.

### ISSUE THREAD

**Issue by DarkHorse1121** [Masuzu/ZooeyBot#1212]
![image](https://user-images.githubusercontent.com/31133619/60217944-e414b200-98a8-11e9-99b5-f8bb1588fbeb.png)

I got banned at May 27th with zooey FPS acceleration.
As a result, corp raid disabled.
I trusted Zooeybot, but I am frustrated with this result....

**Comment by Miyoumu** [comment]
When you cheat you assume the responsibility and possibility of consequences. Its your fault and only yours.

**Comment by Masuzu** [comment]
The responsibility is fully assumed by the user, as always.
