### ISSUE TITLE
Unable to change serial code

### ISSUE THREAD

**Issue by YukiNoUsagi** [Masuzu/ZooeyBot#1213]
I switch the Zooey Bot account around my laptop and desktop quite frequently and I would like to change my serial code through the management page, but it keeps giving me the error that says "An error occurred while processing your request." 

Could you please change my serial number for the account 'granbluetran@gmail.com' to be a6605707a6cdc936f3a1786165fe81a4a4148770a7fe0455a0ad20e36c9a3247a6738cecde2695ab82696dd6176cea539ea527a3c83d15892dde93e65bd8c93d ?

Thank you

**Comment by Masuzu** [comment]
Hi,
This serial number is already bound to the address granbluetran1220@gmail.com, which is also yours I suppose?

**Comment by YukiNoUsagi** [comment]
Oh yes, it is. I forgot my password on the 1220 email so I started using Zooey on the email in my post

**Comment by YukiNoUsagi** [comment]
Oh thanks for that. Resolved!
