### ISSUE TITLE
I can't login and can't recovery my email

### ISSUE THREAD

**Issue by rukadabra** [Masuzu/ZooeyBot#1214]
i have a problem when i want to login and i'm totally forgot my password and e-mail password and my e-mail totally locked and i can't recovery my email. 

Could you please delete the account with email ddtrung2212@gmail.com? 
i want to make a new account with my new email

my serial number : 
924e9f783708043413c8b8ede58fefdb052f0036140597dd3d74e1dcf21ee07b2218e664d71d4d3335bc37b7d421db8cd20be9cce0c3beff799bdf06e65400ab

![image](https://user-images.githubusercontent.com/41042562/60384744-b011da80-9abc-11e9-8f6a-31aabb36837f.png)

**Comment by Masuzu** [comment]
Hello,
It is done now.
