### ISSUE TITLE
"Back" button refresh

### ISSUE THREAD

**Issue by giauten** [Masuzu/ZooeyBot#1217]
It can be noticed that with battles have many stages, zooey cannot refresh
If I put Refresh() in the script, zooey will go to Main quest screen and staying there
But there is a way to Refresh and stay in the battle by using "Back" button
So can you add function to use Back key to refresh besides of current Refesh()?

**Comment by Masuzu** [comment]
Got it. Sure thing.

**Comment by Masuzu** [comment]
This is now patched in v3.10.1
