### ISSUE TITLE
Cannot use 1st summon when EnableShortcutKeys = true

### ISSUE THREAD

**Issue by giauten** [Masuzu/ZooeyBot#1218]
Hi, when I `EnableShortcutKeys = true` and put
```
CastAbility1ShortcutKeyCode=81
CastAbility2ShortcutKeyCode=87
```
Zooey cannot use 1st summon, it seems like: Open summon menu > press Space bar, then stuck there

**Comment by Masuzu** [comment]
Hi,
Here is an update on the matter: https://github.com/Masuzu/ZooeyBot/issues/1204!
