### ISSUE TITLE
Use skills which need to select character

### ISSUE THREAD

**Issue by rabbit02178** [Masuzu/ZooeyBot#122]
Is there any lua variable for skills which need to select character, e.g. Juliet skill 2

**Comment by HiddenIce** [comment]
If Juliet is in position 2 for example -
character_2:UseSkill(2)

However if Juliet is in your frontline and you want to check for the variable to be true -
if character_2.name == "Juliet"
then character_2:UseSkill(2)

**Comment by sellsell** [comment]
I'm in the same boat, I don't know how to handle skills that target other characters like buffs or heals. Say I want my Petra to use her skill 1 on my Seofon/Siete, how would I go about it?

**Comment by Masuzu** [comment]
Hi,

I took note of the enhancement request.

**Comment by Masuzu** [comment]
Partial support in the v1.13.0 was added.
Support for skills requiring several targets to be added later on as it is a pretty rare occurrence.
