### ISSUE TITLE
Would it be possible notify to other apps when captcha appear?

### ISSUE THREAD

**Issue by skkks** [Masuzu/ZooeyBot#1220]
Hello, is there any way to setting notify others apps when captcha appear? 
Because I can not keep connecting to the PC running the zooey-bot during commuting.
For example, Slack's web hook URL would be nice!

```
[Alerting]
# Command to execute when the captcha window appears
CaptchaNotification=curl -XPOST -d "token=<TOKEN>" -d "channel=#general" -d "text=Hello @rubytomato" -d "username=rubybot" "https://slack.com/api/chat.postMessage"
```

**Comment by Masuzu** [comment]
Hello,
Sure that'll be useful to many and made available soon, before the 2nd GW round.

**Comment by Masuzu** [comment]
Added in the newly released versions.
