### ISSUE TITLE
Feature Request - Safe Mode / Battle Mode

### ISSUE THREAD

**Issue by HeavenScent736** [Masuzu/ZooeyBot#1222]
Would it be possible to enable some type of Safe Mode for those of us who are paranoid of a sudden change in automation countermeasures / Battle Mode for those of us who are doing trains and want to reduce repetitive motion strain?

I propose that a mode that requires the user to do all of the menu navigation, then once a battle has started, use some type of in battle button (Menu or Home, for example) or keyboard hotkey to start the lua battle script. Then go dormant when a battle is finished until the action is done again in battle.

**Comment by Masuzu** [comment]
I am sorry but this won't bring much value.
However, a raid train mode may be available in the future.
