### ISSUE TITLE
Farming NM90 in later days of GW.

### ISSUE THREAD

**Issue by Hildibrand** [Masuzu/ZooeyBot#1223]
Hella, is there a way to farm NM90 from the second day of GW onwards? Treasure Event doesn't work with "gw", and the other codes farm NM95. Event mode doesn't work either.

**Comment by UminekoScarlet** [comment]
Not sure if I understood it correctly, but:
When just NM90 and NM95 are available, use "gw-day-2-nm-90".
When all 3 are available, use "gw-day-4-nm-90".

**Comment by Hildibrand** [comment]
You were right. For some reason I just saw the "gw-day-2-nm-95" code on the instructions and didn't realize I could just adjust the number. Thanks a lot!
