### ISSUE TITLE
Crash log?

### ISSUE THREAD

**Issue by 0gawdn0** [Masuzu/ZooeyBot#1227]
Is there a crash log available, or can there be one created please? I feel like this would be great use.

Sometimes I would come back to my computer and see the Zooeybot gone, and my characters are still in battle. For me to figure out what I'm doing wrong with maybe my lua scripts or something that occurs, to minimise the problem happening again I feel like a log will be very useful.

Just food for thought. :)

**Comment by Mewnya** [comment]
Hello,
Actually, you can already keep those logs by launching `ZooeyBot.exe` from a command line.
