### ISSUE TITLE
Summon / Skill press not registering sometimes

### ISSUE THREAD

**Issue by 0gawdn0** [Masuzu/ZooeyBot#1228]
Sometimes when a skill is pressed and there is a minor delay (network lag or fps), Zooeybot will attempt to try and click the skill 2-3 more times. Which is okay, but it happens in about 1500 ms each press, which im pretty sure if our accounts are audited it may be a little suspicious.

in my Lua scripts, I even have 'if character_1.skill_1_available then' but that doesn't help. It still attempts to press the skill even though it has already been initiated.

This happens with the summons as well, sometimes Zooeybot will press the summon, and then it says ' failed to summon.' and then completely crash.

Anyone know if this is something that I can fix on my end?

**Comment by Masuzu** [comment]
Hi,
You most likely have values for MinDelayAfterXXX (under the Combat section of the `ZooeyBot.ini` file) too small. I would suggest increasing them to give Zooey more time and avoid those random delays (I do get them too sometimes!)
