### ISSUE TITLE
How do I structure Seox's skill 3 to cast when he doesn't have the unchallenged buff?

### ISSUE THREAD

**Issue by tryninja** [Masuzu/ZooeyBot#1230]
For example something like:

if characters["Seox"]:HasActiveEffect("1028") <is not available> then
	characters["Seox"]:UseSkill(3)
end

**Comment by Masuzu** [comment]
Hello,
You are on the right track indeed. I will check the buff ID and follow up.

**Comment by Masuzu** [comment]
The status ID for the unchallenged effect is "1028" as you wrote earlier indeed. You will be fine!
