### ISSUE TITLE
Raid with other players involved 

### ISSUE THREAD

**Issue by Rkdheishins** [Masuzu/ZooeyBot#1231]
![Capture](https://user-images.githubusercontent.com/28521755/62259598-bc42cd80-b3c3-11e9-89d8-c4955ecaa6ff.PNG)

im doing event raid "Kappa summer" but any raid will do the same thing, when ever it involves other players in the raid finishing the raid as in they get the last hit not me, my screen fails to go to results menu and play the raid again, i have to keep stopping it and starting it again

any idea on how to fix this from happening?

**Comment by Masuzu** [comment]
I took note of the issue, thank you for bringing this up.

**Comment by Hildibrand** [comment]
Excuse me, how do you manage to put the bot to work with raids with people? I thought there wasn't a "Call for backup" option yet, and as far as I know the raid bot is Sarasa.

**Comment by Rkdheishins** [comment]
in lua scrips put
RequestBackup()
zooey bot and Sarasa bot will both do the same thing in lua scrips
tho the issue in in zooey bot

**Comment by Masuzu** [comment]
This is now addressed in v2.12.1
