### ISSUE TITLE
Bot crashes when summoning.

### ISSUE THREAD

**Issue by Hildibrand** [Masuzu/ZooeyBot#1232]
Hella. This always have been a bug from time to time, but lately while farming the summer events Zooey has been crashing more frequently when summoning. In fact, starting to crash several times in a row. I added a "wait" command in case it was a overstacking of clicks but didn't work.

Basically ZooeyBot casts a summon at the start of the turn, sucessfully does so, then crashes. When I finish the battle manually, the error count of the Chrome tab starts rising constantly until I refresh the page. The error states "Uncaught TypeError: Cannot read property 'style' of undefined (X) at <anonymous>:Y:ZZ".

For me, the bot has always eventually crashed when farming and using summons, but lately it has been crashing a lot so I'm kinda looking for a solution.

![028 2](https://user-images.githubusercontent.com/48763502/62283913-e0012480-b452-11e9-86e5-d47addaf9fb8.jpg)
![028 1](https://user-images.githubusercontent.com/48763502/62283914-e0012480-b452-11e9-8153-c9af8f940b69.jpg)

Any ideas?

**Comment by Masuzu** [comment]
I took note of the issue, thank you for bringing this up.

**Comment by Masuzu** [comment]
An issue which could lead to such a situation was identified and patched in v2.12.1
