### ISSUE TITLE
Serial Number Taken

### ISSUE THREAD

**Issue by Raskert** [Masuzu/ZooeyBot#1233]
Hello
I was trying to register today but it says my Serial Number is already taken.
When I check in forgot email it is linked to yonathan prawiro.com, which i dont't know who it is.
![gbf_error](https://user-images.githubusercontent.com/53579968/62319954-49bc1580-b4c9-11e9-9a2d-17f453a723ff.png)

can you help me to issue new serial number or is there any way to register?

**Comment by Masuzu** [comment]
The mentioned account has been deleted due to inactivity.
