### ISSUE TITLE
Raid stopping point

### ISSUE THREAD

**Issue by Rkdheishins** [Masuzu/ZooeyBot#1234]
So now with new update its no longer refreshes on results screen but itll be stuck on event page now, takes like 20 or so minutes but itll happen
i've notice it specifically does this when enabling 
ReloadPageOnLastBattle=true
which saves a significant amount of time refreshing after each attack
id hate to have a work around by disabling it

![2nd stoping point](https://user-images.githubusercontent.com/28521755/62436042-368c8e00-b6f3-11e9-80b7-2eb90546ba0c.PNG)
![Frozen](https://user-images.githubusercontent.com/28521755/62436043-368c8e00-b6f3-11e9-8a35-e6f6333e819c.PNG)

**Comment by Rkdheishins** [comment]
![often](https://user-images.githubusercontent.com/28521755/62330931-177dca00-b46f-11e9-8e5a-868f1c665f3a.PNG)

happening more often

**Comment by edgyboi** [comment]
Yes
this also happen to me
It stucked at result screen

**Comment by 0gawdn0** [comment]
@Rkdheishins  Mate i would recommend you at least blur out your full name when sending these pics, unless you don't care if ppl know who you are

**Comment by Masuzu** [comment]
Acknowledged
https://discordapp.com/invite/JaNR87n
