### ISSUE TITLE
Zooeybot won't click on target properly

### ISSUE THREAD

**Issue by justjulz29** [Masuzu/ZooeyBot#1236]
Heya,

Having a problem in Nightmare mode in Bzzt: Amped Up, Zooeybot won't properly click on the mafia boss target, as a result I end up charge attacking the ruffian instead. I'm not sure how to fix it otherwise; my mouse click speed is 50, scroll speed 500. Window size is 100% medium size as recommended. My script is also correct.

Any idea how I can fix this?

**Comment by Mirr0r22** [comment]
Instead of writing this line once in your script 
SelectTarget(2)
Write like this
if turn == 1 then
SelectTarget(2)
SelectTarget(2)

**Comment by xerance** [comment]
same here, SelectTarget(2) doesn't work

**Comment by Masuzu** [comment]
Hi,
You need to wait for the current action animation to end, adding delays as needed with the Wait command for instance.
https://discordapp.com/invite/JaNR87n
