### ISSUE TITLE
3.12.2 turn error

### ISSUE THREAD

**Issue by Akifuma** [Masuzu/ZooeyBot#1240]
![2019-08-12_182021](https://user-images.githubusercontent.com/31799116/62861735-93f59000-bd2e-11e9-87f3-ef9ae70585e7.jpg)

**Comment by Masuzu** [comment]
Was there a change according to which the very first "turn" when you start a raid is actually labeled as "0"?

**Comment by Masuzu** [comment]
Reproduced and fixed v3.12.3
