### ISSUE TITLE
Can’t be used

### ISSUE THREAD

**Issue by happydanial** [Masuzu/ZooeyBot#1241]
I just bought ZooeyBot today and it just can’t be used. I checked and followed the guide and did everything however it’s either that it couldn’t run while getting stucked. Or even if it run it just doesn’t run properly. I checked out all the ways and just the same issue over and over again. So can I get a refund of it?

**Comment by Masuzu** [comment]
Hello,
Sure, absolutely. Please request a refund through Paypal and I will process it as soon as possible.
