### ISSUE TITLE
Script for Dark Jeanne d'Arc to survive after 5 turns of skill 3

### ISSUE THREAD

**Issue by tryninja** [Masuzu/ZooeyBot#1242]
Does anyone know the script to have Jeanne d'Arc survive after 4 turns of using her skill 3? I want the script to use 2 green potions on her 4 turns after she casts skill 3 but I'm not familiar with how to do it.

**Comment by Masuzu** [comment]
Hello,

For this kind of questions, just ask it directly on https://discordapp.com/invite/JaNR87n!
