### ISSUE TITLE
Treasure Event Mode

### ISSUE THREAD

**Issue by tidusZX** [Masuzu/ZooeyBot#1243]
**Describe the bug**
My bot works for everything else except treasure event mode. After it selects the quest, it just stops. Hasnt been working for me for the past few updates but everything else works fine!
![1](https://user-images.githubusercontent.com/33868380/63857299-02e11300-c9d6-11e9-8f3f-7a1ce8bcadac.png)
![2](https://user-images.githubusercontent.com/33868380/63857300-02e11300-c9d6-11e9-8272-8786abc2f0e2.png)

**Screenshots**

**Chat directly with us**
https://discordapp.com/invite/JaNR87n

**Comment by Masuzu** [comment]
Oh, you used the wrong url. It should be the event page URL itself, so http://game.granbluefantasy.jp/#event/treasureraid085 in your case I surmise.
