### ISSUE TITLE
Zooey bot cannot refill ap now?

### ISSUE THREAD

**Issue by hello545** [Masuzu/ZooeyBot#1247]
Zooey or sarasa bot isn't able to refill its ap/bp automatically now. 
I think its because the interface has changed. 
Is there any plans for update on the bot?

**Comment by Masuzu** [comment]
Hello,
Checking

**Comment by Masuzu** [comment]
I am not saying that it is not a legitimate issue, but it can't be reproduced at all with the current build. It could have been a transient issue. Therefore we will not follow up on this matter for now.
