### ISSUE TITLE
Zooey Bot won't update serial number

### ISSUE THREAD

**Issue by justjulz29** [Masuzu/ZooeyBot#1254]
Heya, 

Got an unfortunate problem of Zooey Bot not updating my serial number to be the same as on my account, stopping me from using it. I've re-downloaded it fresh and new only to find the same serial number; and even after I've copy pasted and saved the new one, it simply overwrites it when I start Zooey Bot again. I don't know what more I can do; and it's especially frustrating for this to happen during GW. Could I have some help please?

**Comment by Masuzu** [comment]
Hi,
The serial number you should use is the one written in the serial_number.txt file updated each time your start Zooey.
