### ISSUE TITLE
Combat Script Errors 

### ISSUE THREAD

**Issue by betacucksoyboy** [Masuzu/ZooeyBot#1255]
I've attempted multiple versions of these commands I'm so confused what I'm doing wrong. I've removed spaces, I've added spaces, I've copy and pasted identical commands from other users and still getting the same error message. 

I've added and taken spaces away from these commands; 
UseSkill (x) / UseSkill(x)
Summon (x) / Summon(x)
DisableChargeAttack() / DisableChargeAttack ()
EnableChargeAttack() / EnableChargeAttack ()

I doubt it's the charge attacks cause I just copied and pasted the commands from the FAQ, so I'm honestly confused if it's the characters or the if commands I inputed are incorrect or uncompatible;
if **X** **Y** == then 

My script command for the ZooeyBot.ini
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/748061/1
EventRaidScript=Scripts/gw_ex+.lua

Here's a screenshot of the commands I'm using the error message I'm recieving;
![GW EX+](https://user-images.githubusercontent.com/57923609/69102345-394e9b80-0ab6-11ea-92b7-860fada5f9f7.JPG)

I would greatly appreciate some help and I'm completely new to all this type of commands I used to just put all the commands in one **_.lua_** file and just go from there. So I'm completely lost at this type of segmented coding

**Comment by justjulz29** [comment]
You turns are actually supposed to be written as "if turn == 1 then" instead of the way they are. That's why it's not working. Also, there should be no space between any of the numbers or brackets in your script. Aka, it should be "UseSkill(1)" "Summon(6)" "DisableChargeAttack()".

**Comment by justjulz29** [comment]
In other words, it should look like this; 

DisableChargeAttack()
if turn == 1 then 
character_1:UseSkill(1)
character_2:UseSkill(2) etc. 
EnableChargeAttack()
end 

If you click on ZooeyBot on this page, then go to Scripts, you can see example scripts to see what you really should be writing :)

**Comment by betacucksoyboy** [comment]
You're a genius! Thank you so much for teaching a noob like me.
