### ISSUE TITLE
Debug lua script with Trial battle

### ISSUE THREAD

**Issue by zappky** [Masuzu/ZooeyBot#1256]
i want to debug my script using
TrialBattleMode=true
but the program complains about not able to find the script.

so where do i specific the name of the script i want to test?
or what is the name predefined in the program already?

i am sorry but i cannot seems to find any documentation related to this

**Comment by Masuzu** [comment]
The script which will be loaded in the TrialBattleMode is the one under the `Combat` section of the configuration file.
