### ISSUE TITLE
Calibrating ERROR

### ISSUE THREAD

**Issue by zero2despair** [Masuzu/ZooeyBot#1263]
Hello, I am very troubled now.
When I tried to play this event regularly, I couldn't start with an error with calibrating.
I have used it for about a year, but this is my first time. Help me.
Scaling is 100%.
Is there anything to check other than scaling?

When DebugCalibration was set to true, 0.738031 was output.

I also helped with "There is a scaling problem! (Again ?!)" but the result was 305.

![87fb70cd212b8b5d16c58313ab826033-png](https://user-images.githubusercontent.com/35548186/70957621-0b12aa80-20ba-11ea-9748-b910cd3f35d3.jpg)

**Comment by Masuzu** [comment]
Try with a standard resolution instead of the lite settings, it can help in those cases.
