### ISSUE TITLE
Zooey bot licence don't renew

### ISSUE THREAD

**Issue by twgok123** [Masuzu/ZooeyBot#1267]
I have auto renew on and i notice that my paypal got charge but the licence don't renew for me

**Comment by Masuzu** [comment]
Hello,
There might be an initial delay. Otherwise, which is the email or serial number you are using? (You can provide only the first few characters)

**Comment by twgok123** [comment]
My email is Kuuhakukei@gmail.com and serial number is aa7c93755....  I don't think it delay because it been over a week (it charged me on 14 of Dec)

**Comment by twgok123** [comment]
The zooey bot auto renew just charge me again while the licence still active and not extended the time. @Masuzu

**Comment by Masuzu** [comment]
Closing as non-issue after investigation and refund was/will be issued
