### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by lek2080** [Masuzu/ZooeyBot#1271]
Do not speak English well.
So I use a translator.
I bought it and it worked.
Hunt repeatedly only Angel Halo.
I want to campaign, and I want to hunt slime.
I want to be guild war and I want to do zeno.

But i don't know the script.
I don't know how to use it.
The explanation on the home page doesn't make any sense.
I need help

**Comment by lek2080** [comment]
run zooey bot-> run zooey bot chrome-> click the quest button and it will automatically go to the angel halo and repeat.

**Comment by Masuzu** [comment]
Please refer to
https://github.com/Masuzu/ZooeyBot/wiki/Event-mode for regular event quests and GW EX+ modes
https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode-(Guild-Wars-and-others) for quests requiring materials to host.
There are also other comprehensive guides on https://github.com/Masuzu/ZooeyBot/wiki
