### ISSUE TITLE
Zooey bot can't farm Lower Xeno raid in Duo Xeno Clash

### ISSUE THREAD

**Issue by ggtest12** [Masuzu/ZooeyBot#1273]
**Describe the bug**
In Treasure Raid Event mode
Zooey bot always chose upper xeno(fire) from event page 
(http://game.granbluefantasy.jp/#quest/extra/event/2022)

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/59574185/71834002-be325a80-30e0-11ea-9658-959aa2506520.png)

**Comment by Proxymanity** [comment]
It would seem this has been asked before in https://github.com/Masuzu/ZooeyBot/issues/1158.
We have to use customized scheduling rather than Treasure Event Mode

**Comment by ggtest12** [comment]
Thanks!
