### ISSUE TITLE
I want to use the characters automatically when the skills are available.

### ISSUE THREAD

**Issue by lek2080** [Masuzu/ZooeyBot#1275]
I wrote like below but it doesn't work.
Please tell me how.
I want to use it automatically whenever a skill or summon is available. I'm not sure if I browse the homepage. Give me an example or show me how,
=======================================

character_1.skill_2_available
character_1.skill_3_available
character_1.skill_4_available
character_1.skill_1_available
character_2.skill_3_available
character_2.skill_1_available
character_2.skill_2_available
character_3.skill_1_available
character_3.skill_2_available
character_3.skill_3_available
character_4.skill_2_available
character_4.skill_3_available
character_4.skill_1_available
Summon(6)

**Comment by zappky** [comment]
Pls refer to this:
https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts

characters["Whatever char name here "]:UseSkill(the skill position here, 1 being leftmost)
That line will automatically use the skill whenever it is available.
Similarly, Summon(6) will automatically use summon on slot 6, aka your friend summon.

character_1.skill_3_available is like just checking if character in slot 1, has skill 3 available to be use, which returns you a true or false value. You are not actually activating the skill. You are just checking.
There are use cases of such check,but honestly for now, you dont need to.

**Comment by Masuzu** [comment]
Thanks Zappy.
