### ISSUE TITLE
automate GW NM 90+ farming problem

### ISSUE THREAD

**Issue by japanesezooey** [Masuzu/ZooeyBot#128]
Only once does not go well. Second time out error.
this is settings and error message.
https://gyazo.com/b75080453e8b8c256c3b2926c599f7d5

**Comment by Ziragat** [comment]
Im getting the same error, I had extra AP in case that was the issue but it still fails when trying to host the second one

**Comment by meteoshower** [comment]
yes i get problem too.

**Comment by Masuzu** [comment]
Got it, will fix it asap.

**Comment by Masuzu** [comment]
This is fixed in version 1.10.1.
![](https://gbf.wiki/images/0/0f/Stamp17.png)
Some adjustements will be made to support the NM 95 mode too at the start of today's round.
