### ISSUE TITLE
Got permanent banned.

### ISSUE THREAD

**Issue by i-Grey** [Masuzu/ZooeyBot#1280]
My ID got banned in today's ban wave.
I'm using the latest version of ZooeyBot and I was monitoring while grinding though.

There was one CAPTCHA appear last night which I intermediately enter that one right away in 5sec.
I don't know why myself got banned anyway. I was using only ZooeyBot without using Viramate for 2 years.

Edit: as same as Groudypi.
That browser has no extension except ZooeyBot and ZarazaBot.
I use my laptop to running only bot and GBF too.

**Comment by Groudypi** [comment]
I got suddenly banned mid-way during gw Ex raid.
The browser has no extension,except zooey bot one.
The computer was not running anything else too.

i highly believe zooeybot is no longer safe.

Better lay low and just grind manually bois

**Comment by DarkHorse1121** [comment]
How long time did you run?

**Comment by Groudypi** [comment]
Just a mere hour. Moreover, i was watching it bot and suddenly went to the ban screen. The ban is one month even tho the account wasnt banned before.

**Comment by Chololoco13** [comment]
Could you share your Zooetbot.ini file?

**Comment by Groudypi** [comment]
if you are wondering if i was using any of the experimenting features,like fps, i wasnt. Just your usual config for Ex grind

**Comment by zero2despair** [comment]
hello.
Have you ever used sarasa bot ?
