### ISSUE TITLE
AP recovery does not work well

### ISSUE THREAD

**Issue by kusyarudaora123** [Masuzu/ZooeyBot#1290]
I started Zooey bot after adding the "rise of the beasts" event, but no matter how much AP I had, the operation to recover to MAX occurred forever and it stopped working.

Please take action as the order of internal data may have been changed.

If you set the quest consumption AP to 0 in "scheduling" mode, it will work for the time being, so please try this setting until everyone improves.

**Comment by Qewar** [comment]
You expect @Masuzu to actually do something? He's been afk for 3 months and doesn't seem to be working on the bot anymore, meanwhile still charging overpriced subscriptions for outdated and buggy software.

**Comment by Proxymanity** [comment]
I was having this bug too and updating Zooeybot fixed it for me. Have you tried updating to the newest version of zooeybot? 
The 3.15.2 patch notes states: "Fixed an issue which caused Zooey to refill action points even when action points were sufficient."
