### ISSUE TITLE
Zooeybot Keep Refilling AP for Rise of The Beast Event

### ISSUE THREAD

**Issue by Rarow** [Masuzu/ZooeyBot#1291]
I am using the scheduling script which masuzu shared for Rise of The Beast event. But it just keep trying to refill the AP even though the AP is sufficient. Please help @Masuzu . Thank you

**Comment by Proxymanity** [comment]
I was having this bug too and updating Zooeybot fixed it for me. Have you tried updating to the newest version of zooeybot? 
The 3.15.2 patch notes states: "Fixed an issue which caused Zooey to refill action points even when action points were sufficient."
