### ISSUE TITLE
ZooeyBot Can't detect Chrome

### ISSUE THREAD

**Issue by GudakoFujimaruu** [Masuzu/ZooeyBot#1294]
Hello,

Having some issues with Version 3.15.2. It is unable to detect Granblue but it shows chrome with granblue open on the app. Any way to adjust the config settings to allow for detection? I tried opening and closing out Zooey but no luck there.

**Comment by Proxymanity** [comment]
What version of chrome are you using? And could you post a screenshot of the error/what is happening?
I am able to use Zooeybot just fine in the latest version.

**Comment by Mewnya** [comment]
Make sure to set the language parameter accordingly (by default it is set to 'jp')
