### ISSUE TITLE
No response received / abnormally long wait time

### ISSUE THREAD

**Issue by ClubShrimp91** [Masuzu/ZooeyBot#1295]
My lua script isn't executing properly. Zooeybot picks a character, then the skill, but doesn't click OK to actually use the skill. The cursor just stops, and then the error message above appears in the command window. Any ideas what's causing this? I can't find anything that helps in the ini.

**Comment by Mewnya** [comment]
Please do _not_ use the in game option which displays skill details when they are selected.
