### ISSUE TITLE
Keep getting scaling error

### ISSUE THREAD

**Issue by firdaus-gfb** [Masuzu/ZooeyBot#1297]
**Describe the bug**
I have tried following the guides that are available and also went through a few previous scaling issues but I couldn't get it to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/62802383/77825759-51d55f00-7103-11ea-8746-67ba4ab5c6d4.png)

**Comment by Mewnya** [comment]
I am still surprised at how many people use non standard DPI settings!
This could help:
https://www.tenforums.com/tutorials/5990-change-dpi-scaling-level-displays-windows-10-a.html

**Comment by firdaus-gfb** [comment]
Thanks for the link but I have gone through all those settings and all are set to what it should be but still not working.
