### ISSUE TITLE
Cant get lua script running

### ISSUE THREAD

**Issue by Runan92** [Masuzu/ZooeyBot#130]
Hi, I purchased and started using zooey today.
Everything is fine but somehow I cant get the lua script running.
I tried some way like turning off Viramate, or copy exactly the example configuration that Masuzu provided in issue #123. However, zooey still auto attack in the end.
Do you have any idea what I did wrong and how can I fix this problem?

**Comment by Ziragat** [comment]
did you choose the lua in the ini? show me your ini i may be able to help

**Comment by Runan92** [comment]
This is the ini and lua script I'm using.
[ZooeyBot.txt](https://github.com/Masuzu/ZooeyBot/files/1100174/ZooeyBot.txt)
[dark_gw_ex.txt](https://github.com/Masuzu/ZooeyBot/files/1100175/dark_gw_ex.txt)

**Comment by Ziragat** [comment]
Try using the lua like this:

if turn == 1 then
  character_1:UseSkill(4)
  character_1:UseSkill(1):WithWaitTime(3600)
  character_1:UseSkill(3):WithWaitTime(1300)
  characters["Zooey"]:UseSkill(2):WithWaitTime(4100)
  characters["Zooey"]:UseSkill(1)
  characters["Jeanne d'Arc"]:UseSkill(1):WithWaitTime(1600)
  characters["Jeanne d'Arc"]:UseSkill(2):WithWaitTime(1600)
  characters["Jeanne d'Arc"]:UseSkill(3):WithWaitTime(1200)
  characters["Narmaya"]:UseSkill(2)
  characters["Narmaya"]:UseSkill(1):WithWaitTime(3000)
end

if turn == 2 then
  characters["Zooey"]:UseSkill(3):WithWaitTime(1600)
  characters["Narmaya"]:UseSkill(3):WithWaitTime(1500)
  character_1:UseSkill(2)
end

**Comment by Runan92** [comment]
I just keep encountering this WebSocket Exception and the lua script wont be loaded :(

![screenshot 2017-06-25 17 32 39](https://user-images.githubusercontent.com/15991716/27515402-62fb1ba4-59cc-11e7-9157-9bfe72b0afab.png)

**Comment by Masuzu** [comment]
Hello,
Would you happen to play while having the twitter feed window open on the left side?
There is a known issue which happen in this case.
This will be fixed later as it is minor.
You can either close the twitter news tab or use adblocker on the page and block platform.twitter.com in the meantime.

**Comment by Runan92** [comment]
It works like a charm now after I closed the twitter side bar, thank you very much.
