### ISSUE TITLE
Zooey bot not starting

### ISSUE THREAD

**Issue by IanKoss** [Masuzu/ZooeyBot#1302]
**Describe the bug**
Hello, when I try to use the zooeybot, I try starting it through the developer icon but nothing happens, i tried various methods but it just will not start, please help!

**Screenshots**

![Capture](https://user-images.githubusercontent.com/25437967/79701842-4ee70d80-826e-11ea-8c8c-745e404182e1.PNG)

**Chat directly with us**
https://discordapp.com/invite/JaNR87n

**Comment by IanKoss** [comment]
It gets stuck on that icon and pressing start does nothing

**Comment by Mewnya** [comment]
Hi there,
Please read the manual _fully_:
https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation
