### ISSUE TITLE
Problems with Key File not matching serial number

### ISSUE THREAD

**Issue by babyragedota** [Masuzu/ZooeyBot#132]
The serial number in the Zooey bot folder, on the generator, as well as the one listed on my manage account screen does not match the key file download. Should I change my serial number to the one listed in the key file? 

Thanks for any help

**Comment by Masuzu** [comment]
Hi,

The serial number is completely different from your key file contents.
You should never have to modify the contents of the key file, simply download this key file from the management page.

**Comment by babyragedota** [comment]
Hi, 
I'm sorry if I am just being dumb here but I copied the downloaded key file directly into the folder with zooeybot in it but it still doesn't register

Can you offer any insight on why this might be happening? 

(https://user-images.githubusercontent.com/29693408/27520486-abd67c20-59da-11e7-9701-9f35a5e8f104.png)
(https://user-images.githubusercontent.com/29693408/27520487-ad9d8b34-59da-11e7-9643-bd14f5b732e4.png)
Thanks
