### ISSUE TITLE
Key file 

### ISSUE THREAD

**Issue by babyragedota** [Masuzu/ZooeyBot#133]
Hi,
I'm sorry if I am just being dumb here but I copied the downloaded key file directly into the folder with zooeybot in it but it still doesn't register..

I just downloaded it off the site and copied it into the folder. 

Can you offer any insight on why this might be happening?

(https://user-images.githubusercontent.com/29693408/27520486-abd67c20-59da-11e7-9701-9f35a5e8f104.png)
(https://user-images.githubusercontent.com/29693408/27520487-ad9d8b34-59da-11e7-9643-bd14f5b732e4.png)
Thanks

**Comment by Masuzu** [comment]
The key file must be named `key.txt`
Yours is named `key (44).txt`
