### ISSUE TITLE
Stuck at the first result page for the automated Light GW EX+

### ISSUE THREAD

**Issue by Reh87** [Masuzu/ZooeyBot#136]
Hello,

Itried to automated Light GW EX+ farm with this https://github.com/Masuzu/ZooeyBot/issues/123
But i'm stuck after the first result page
![image](https://user-images.githubusercontent.com/29696509/27521342-01afe186-5a1c-11e7-9bf1-217a3392109c.png)
I copied the eventmode part from your post and only modified the summon and script part.
I don't know what's the issue here, can you help me ?

**Comment by Masuzu** [comment]
Please use the option `ReloadPageOnLastBattle=true` for now, thank you.

**Comment by Masuzu** [comment]
Fixed in v1.11.1
