### ISSUE TITLE
lua script error code help

### ISSUE THREAD

**Issue by IZEROII** [Masuzu/ZooeyBot#137]
![screenshot 33 _li](https://user-images.githubusercontent.com/24773141/27568467-06418228-5ac0-11e7-9afa-3d98c5fbd1f0.jpg)

I am getting this error as identified in the screenshot and I am at a loss as to why.  It is occurring during turn 6 repeatedly and I can't make clear what it is trying to tell me.  character_1 is a valid variable, skills 2 and 3 are available (even if they were on cool down it should skip), and I haven't inputted any new code that hasn't been used in the previous lines/turns. 

Any help would be appreciated.

**Comment by Dreamfinal** [comment]
Line 36  index null

Please use Edit++ for easier reading.

**Comment by Dreamfinal** [comment]
Did you the this

```
character[“Zooey”].is_alive == true then
	character[“Zooey”]:UseSkill(1);
	character[“Zooey”]:UseSkill(2);
	character[“Zooey”]:UseSkill(3);
end

character[“Seox”].is_alive == true then
	character[“Seox”]:UseSkill(1);
	character[“Seox”]:UseSkill(2);
	character[“Seox”]:UseSkill(3);
end
```


or

```
if character_3.name == “Zooey” then
	xxxxx
end
if character_3.name == “Seox” then
	xxxxx
end

```

or

```
if character_3.name == “Zooey” then
	xxxxx
else if character_3.name == “Seox” then
	xxxxx
end
```

**Comment by Dreamfinal** [comment]
character_3 <<<<< no s
characters[“Seox”] <<<<< add S

character
characters <<

**Comment by IZEROII** [comment]
Thank you.  I will implement this change when I get home from work and will report back.

**Comment by IZEROII** [comment]
Ya the problem persists it is at line 36 and detailing character_1.  Even when I remove character_1 actions from turn 6 it still gives the same error.  I am at a loss

**Comment by IZEROII** [comment]
if turn < 4 then
  DisableChargeAttack()
else
  EnableChargeAttack()
end

if turn == 1 then
  character_1:UseSkill(2)
  character_1:UseSkill(3)
  characters["Seox"]:UseSkill(1)
  characters["Seox"]:UseSkill(2)
  characters["Seox"]:UseSkill(3)
  characters["Zooey"]:UseSkill(3)
  characters["Vira"]:UseSkill(1)
  characters["Vira"]:UseSkill(2)
end

if turn == 2 then
  characters["Vira"]:UseSkill(3)
  characters["Vira"]:UseSkill(4)
end

if turn == 3 then
  characters["Seox"]:UseSkill(1)
end

if turn == 4 then
  Summon(6)
  characters["Seox"].is_alive:UseSkill(3)
  characters["Zooey"].is_alive:UseSkill(2)
  characters["Zooey"].is_alive:UseSkill(1)
end

if turn == 5 then
  character_1:UseSkill(1)
  characters["Seox"].is_alive:UseSkill(1)
end

if turn == 6 then 
  character_1:UseSkill(2)
  character_1:UseSkill(3)
  characters["Seox"]:UseSkill(2)
  Summon(2)
end

if turn == 7 then

  characters["Dark Jeanne d'Arc"].is_alive:UseSkill(2)
  characters["Narmaya"].is_alive:UseSkill(2)
  characters["Zooey"].is_alive:UseSkill(3)  
  characters["Seox"].is_alive:UseSkill(1)
  characters["Seox"].is_alive:UseSkill(3)
end

if turn == 8 then
  characters["Vira"].is_alive:UseSkill(1)
  characters["Dark Jeanne d'Arc"].is_alive:UseSkill(3)
  Summon(3)
end

if turn == 9 then
  characters["Vira"].is_alive:UseSkill(2)
  characters["Seox"].is_alive:UseSkill(1)
  Summon(4)
end

if turn == 10 then
  character_1:UseSkill(1)
  characters["Seox"].is_alive:UseSkill(3)
  characters["Narmaya"].is_alive:UseSkill(2)
end

**Comment by Dreamfinal** [comment]
characters["Seox"]:UseSkill(2) <<<< seox die = error

You have to do this.

```
if turn == 6 then
character_1:UseSkill(2)
character_1:UseSkill(3)
characters["Seox"]:UseSkill(2)
Summon(2)
end
```


change to


```
if turn == 6 then
character_1:UseSkill(2)
character_1:UseSkill(3)

      if character_2.name == “Seox” then
          characters["Seox"]:UseSkill(2)
      end

Summon(2)
end
```

You have to check it every time. If you use the character name.

**Comment by IZEROII** [comment]
I will test this suggestion when GW comes out of intermission
