### ISSUE TITLE
Can't load the unpacked extension

### ISSUE THREAD

**Issue by akira9311** [Masuzu/ZooeyBot#138]
Hello there,

I can load the zooey_bot from 1.5.1 to my chrome.
But I cannot do the same thing for the version 1.11.0
Please help me, thanks.

**Comment by akira9311** [comment]
Can't start the bot even I use the version 1.5.1, which I used before. PS. It is the same surface pro4

**Comment by akira9311** [comment]
The error message is 
Failed to load extension from: ~\Desktop\zooey-bot-v1.11.0\zooey-bot-extension
Could not load background script 'js/zooey-util.js'.

THanks

**Comment by Dreamfinal** [comment]
This must be used version 1.10.0 extension == work

1.11.0 extension == error

(English I'm not good sorry)

**Comment by Masuzu** [comment]
I updated the download link on dropbox. It is fixed now.
Windows Defender is giving me a headache.
Apologies for the inconvenience.
