### ISSUE TITLE
Combat to HellMode in TreasureEventMode?

### ISSUE THREAD

**Issue by himappe** [Masuzu/ZooeyBot#141]
Event of PlayRanger Sign is Active now.
in Event mode, cant play vh and Ex of TreasureEvent (like this event).
Bur in TreasureEventMode cant play Hell in this Event.
How to do to botting this event's HellMode

**Comment by Masuzu** [comment]
Hello there,

There is not yet support for this. I will see what I can do about it.

**Comment by greatmany** [comment]
bot does not seem to go to nightmare mode yet with the new version, was there a mistake in the ini provided?
NightmareModeUrl is the same as variable as the one used for event mode

**Comment by Masuzu** [comment]
There is a `NightmareModeUrl ` parameter for the EventMode and a second parameter named identically for the `TreasureEventRaid` section.
Did you update the one in the TreasureEventRaid section?
After the bot displays in the console `Nightmare mode appeared`, it should proceed to the Nightmare mode.
I will double check it a bit later.

**Comment by greatmany** [comment]
Sorry I reconfigured the ini from scratch again and it works now, I might have copied the ini updates wrongly previously

**Comment by Masuzu** [comment]
Good to know, all good then!
