### ISSUE TITLE
Suggestions: script sharing repository + treasure event mode fallback when no materials are available

### ISSUE THREAD

**Issue by ErogeSeiyuu** [Masuzu/ZooeyBot#142]
1. Have a directory for people to share/comment their zooeybot.ini config and scripts for references. Took me quite a while to figure out a good script for my comp. A private subreddit would also work.
2. (QoL) Add in the option for TreasureEventMode to include a section for auto-farm for required items. So people can select, for example, VH mode + VH mode script, and a farm mode and farm script all in one .ini. If VH mode runs out of treasure, bots will go to farm mode to farm. Just like how we reroll for summons with trial.

That's about it. Second idea is mostly for QoL and isn't that necessary, but would be great if it can be implemented. I do highly suggesting considering the first one though.

**Comment by Masuzu** [comment]
Currently, I do not have the permission to create subreddits.
Should you want to do it to have subreddits similar to this: http://zooeybot.freeforums.org/, feel free to.
