### ISSUE TITLE
there's bug in coop mode

### ISSUE THREAD

**Issue by Dreamfinal** [Masuzu/ZooeyBot#143]
the bot select target id in a wrong way

i record a sample, pls see this vdo

sample1
https://youtu.be/WEeKHEsNI2s

sample2
https://youtu.be/RnopPlcs7PM

**Comment by ChocolateBall** [comment]
I opened an issue regarding case 2 a few days ago, as per the suggestion, I refresh and did everything according to instructions. Doesn't work. Or rather very occasionally.

**Comment by Masuzu** [comment]
I will look into it.

**Comment by Masuzu** [comment]
@Dreamfinal The links are dead so I can't see it anymore. You can share it with me in private via Google drive if you want.

**Comment by Dreamfinal** [comment]
@Masuzu ok i fix it

**Comment by Masuzu** [comment]
Thank you for fixing the links :)
About this incorrect player ID, you have to have only one Chrome DevTools window open when you start the bot. It is a current limitation of the Chrome DevTools feature when you have multiple of them open on several different Chrome windows, and for now that is the best workaround which I found for it. "Best" as "consistent" workaround which never runs into this wrong player ID detection on my side.

Following-up with the refresh issues in https://github.com/Masuzu/ZooeyBot/issues/147
