### ISSUE TITLE
Suggestion: More accounts on Coop

### ISSUE THREAD

**Issue by Zir1984** [Masuzu/ZooeyBot#144]
Would it be possible to set more than 2 accounts for coop?
I mean the main and slave that are working as of now, and 2 more " sub mains".
It would be useful for farming pots on slimes, dunno if it can be implemented tho

**Comment by Masuzu** [comment]
Hello,

Sure thing It would be possible to do so but I think very few people would use this feature. Hence not on the priority list for now.

**Comment by KoryuIlyen** [comment]
Yeah, this would be wonderfully awesome, would love to see it implemented!

**Comment by Tyrrandae** [comment]
Indeed, this would make farming on my 4 accounts much easier and faster. Definately would love to see it implemented. Keep up the great work!

**Comment by Dreamfinal** [comment]
In my opinion, 3 accounts are enough. The half red potion is infinite and can be looped with 3 accounts (2 cannot work on this). I'm just fine with 3 or 4 accounts . By the way, my intention is to farm the potion, that's it.

**Comment by Masuzu** [comment]
Small update but unfortunately, I won't do it due to current limitations with the Chrome browser.
