### ISSUE TITLE
I cannot for the life of me figure out what relative path means for lua script

### ISSUE THREAD

**Issue by SunshineJones** [Masuzu/ZooeyBot#145]
I'm usually pretty good with computers and picking things up quickly but i cannot for the life of me figure out what relative path to zooey.exe means for the lua scripts :/ Any help will be greatly appreciated and im sorry for my stupidity :D

https://gyazo.com/90bbcf657da8892750572a0f42c41d1d

https://gyazo.com/b34e6c10eae2b3b89166fa6f39809992

**Comment by Masuzu** [comment]
It means to use the "knight" script, you have to set the `LuaScript` parameter to `Scripts/knight` in the ZooeyBot.ini file.
It looks like that you are hiding files extension too. So take this into account too.
