### ISSUE TITLE
Don't work EventMode.

### ISSUE THREAD

**Issue by NzString** [Masuzu/ZooeyBot#146]
![no3](https://user-images.githubusercontent.com/26919276/27769403-804a791a-5f63-11e7-9301-297f162702f1.png)

Stop working after that message.

![no4](https://user-images.githubusercontent.com/26919276/27769426-db4d7b96-5f63-11e7-8104-3debdf82b65a.png)

And I checked 500(Internal Server Error).

help me.

**Comment by Masuzu** [comment]
Could you please post here the content of the ZooeyBot.ini file that you are using so I can try and reproduce the issue?

**Comment by NzString** [comment]
[mac.zip](https://github.com/Masuzu/ZooeyBot/files/1119326/mac.zip)
here!
Still not work.
![no2](https://user-images.githubusercontent.com/26919276/27791123-82ccd14e-602e-11e7-8aa0-7d5e9f982431.png)
![no](https://user-images.githubusercontent.com/26919276/27791134-914f9152-602e-11e7-8d61-d75ac4fe96ce.png)

**Comment by Masuzu** [comment]
First thing:
You can't use your (second try) script to farm Fenrir as this raid requires items to host it.
Please use the TreasureRaidEvent mode for this: https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode

**Comment by Masuzu** [comment]
Same thing with your (first try) ZooeyBot.ini
Please use the TreasureRaidEvent mode for this: https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode for this use case.
Therefore, closing this ticket as invalid.
