### ISSUE TITLE
Bug: in TreasureEventMode bot does not do nightmare if farming VH difficulty

### ISSUE THREAD

**Issue by greatmany** [Masuzu/ZooeyBot#148]
When nightmare mode spawns while farming very hard difficulty the bot will continue to farm very hard instead of going to nightmare mode as it should

If farming extreme difficulty everything works fine, except that a new nightmare timer is started every time nightmare mode spawns, so there will be 10+ windows to close after a session is done

**Comment by Masuzu** [comment]
Got it about the timer windows.
Could you please also post your ZooeyBot.ini file too? I would like to check something.

**Comment by greatmany** [comment]
[ZooeyBot.txt](https://github.com/Masuzu/ZooeyBot/files/1123268/ZooeyBot.txt)

**Comment by greatmany** [comment]
Okay, using the ini i posted, i switched to ex and once again it was not going into nightmare. 

i extracted a fresh ini again and changed only the variables for language, viramate and treasureevent and nightmare farming works normal again.
