### ISSUE TITLE
Checking "auto" for Angel Halo

### ISSUE THREAD

**Issue by bostong3** [Masuzu/ZooeyBot#149]
Is there an option to click "Auto" for Angel Halo as opposed to "Attack" on every stage? It would save a lot of time this way. Thanks!

**Comment by Dreamfinal** [comment]
Do not put anything in Script

``

``

**Comment by bostong3** [comment]
Isn't that the default option? In which case Zooey attacks every turn.

**Comment by Masuzu** [comment]
That's the same thing as auto basically.
