### ISSUE TITLE
Lua  code problem

### ISSUE THREAD

**Issue by Yalzy** [Masuzu/ZooeyBot#15]
i need my DF use stall on turn 2 and continue use if it available

if turn >= 2 then
  character_1:UseSkill(1)

end

still not use

**Comment by Masuzu** [comment]
Does it says it is trying to use a skill in the console window?

**Comment by Yalzy** [comment]
EnableChargeAttack()
Summon(6)


if character_1.name == "ยาว" then

  character_1:UseSkill(2)
  character_1:UseSkill(3)
  
end

if characters["Amira"] ~= nil then
  characters["Amira"]:UseSkill(1)
end

if character_2.name == "Jeanne d'Arc" then
  character_2:UseSkill(1)
  character_2:UseSkill(2)
  character_2:UseSkill(3)

end

if character_4.name == "Juliet" then
  character_4:UseSkill(1)
  character_1:UseSkill(4)
  character_1:UseSkill(1)
end


other part is work fine but  code on MY topic not work he use at turn 2 and never use it agian

**Comment by po456asd** [comment]
@Yalzy ไปลองเปลี่ยนชื่อจาก ยาว เป็นอย่างอื่น น่าจะมีปัญหาที่โค้ดตรงที่มันอ่านค่าภาษาไทยไม่ได้นี่แหละ

**Comment by Yalzy** [comment]
ไม่เกี่ยวภาษาไทยครับ ผมลองเขียนสคริป ตรงอื่นใช้ได้หมด

ผมแค่อยากให้มันใช้ Stall ตอนเทิร์น2 แล้วก็เทิร์นถัดไปที่มันใช้ได้เฉยๆ ไม่อยากให้มันใช้เทิร์นแรก (ตอนนี้ใช้แบบให้มันเริ่มต้นเทิร์นแรก พอมันคูลดาวเสร็จก็ใช้ใหม่เอง)

**Comment by po456asd** [comment]
คือลองใช้

if turn => 2 then
  character_1:UseSkill(1)
end

ก็ไม่ได้ใช่ไหม

ตอนถึงเทิร์น ตัวคอนโซลได้บอกไหมว่ากำลังจะใช้สกิล

**Comment by Yalzy** [comment]
ถึงเทิร์นมันจะกดสกิลครับ แต่พอ สกิลสามารถใช้ได้อีก มันก็จะไม่กดใช้ให้

**Comment by po456asd** [comment]
ลองเขียนสคริปเป็นแบบ

if turn == * then

ไปเรื่อยๆแบบวางแผนเองเลยเทิร์นไหนใช้สกิลไหน ไม่แน่ตัวโซอี้เองอาจจะยังไม่มีระบบตรวจสอบสกิลที่ใช้ได้นะ

**Comment by Yalzy** [comment]
มีครับ สคริปข้างบนพอ เวลาผ่านไปมันจะใช้ให้เอง  ทุกครั้งที่ cooldown เสร็จ

**Comment by Masuzu** [comment]
If you want to use a skill whenever it is off cooldown at the second turn and whenever it becomes available again the future, just do:
```
if turn >= 2 then
  character_1:UseSkill(1)
end
```
At turn 3, 4 and so on, if the skill 1 of the first character is not available, then it will be skipped.
As soon as the skill 1 is available again, it will be used.

I will consider adding some other features such as accessing the number of diamonds of enemies to make it easier to use some skills such as Phalax or Stall.

**Comment by Masuzu** [comment]
There is no support yet for skills which may reset your cooldowns though (Quatre for instance).
