### ISSUE TITLE
can fix download site?

### ISSUE THREAD

**Issue by kalarotia** [Masuzu/ZooeyBot#152]
"download  Zooey Bot "
Error (429)
This link is temporarily disabled. The person who shared it hit their daily limit of traffic or downloads.

plz fix it

**Comment by Masuzu** [comment]
Hi,
Do you live in China?
China blocked dropbox

**Comment by Masuzu** [comment]
Alternative download link was provided:
https://github.com/Masuzu/ZooeyBot/releases/tag/1.12.0
