### ISSUE TITLE
Suggestion: "Auto" as a selectable option

### ISSUE THREAD

**Issue by ReinaryuIlyen** [Masuzu/ZooeyBot#153]
Was curious if it's possible that a toggle-able option could be added to just have Zoi hit attack, followed by auto, and wait for the battle end to then repeat? 

While this isn't a speed concern, it doesn't seem very "human-like" to always hit attack if you don't use skills for super easy quests, as most humans would just hit auto.

Thanks!

**Comment by Masuzu** [comment]
Hello there,

People just pressed continuously the attack button before the auto feature was implemented and still do.
Therefore this is very low on priority, might not be implemented.
