### ISSUE TITLE
How to play Daily Special Quest?  stucking in event mode & default mode by "required AP has changed".

### ISSUE THREAD

**Issue by himappe** [Masuzu/ZooeyBot#154]
stucking in Diaboros EX.
first time is ok but second time  and after are stucking.
How to botting?

quest Id is

http://game.granbluefantasy.jp/#quest/supporter/500521/5

![stuck](https://user-images.githubusercontent.com/29257104/27991114-96dcec00-64a7-11e7-8377-1fab350cd3ee.jpg)

**Comment by Masuzu** [comment]
Do not use the event mode for daily quests. Use the default mode.
https://github.com/Masuzu/ZooeyBot/wiki/Basic-mode---story-quests,-free-quests-and-special-quests-automated-farming#

After navigating to the quest menu, the console will tell you to navigate to either the special or favourite quest menu.
Simply follow the instructions from this point and select Diablo EX
