### ISSUE TITLE
Can't renew license.

### ISSUE THREAD

**Issue by meteoshower** [Masuzu/ZooeyBot#155]
I just try to buy license 1 month (with Stripe) i think it successes because green check mark appear. so after that
 https://poker-bot.azurewebsites.net/ZooeyBot/en/Manage
 reload 1 time but nothing happen and my license status still expired after that I try twice time to pay with Stripe and  still nothing happen.  Money has not yet been paid but I'm concerned about the order have stuck.

**Comment by Masuzu** [comment]
No charges are induced in case the renewal failed.
You can either use Paypal or Stripe.
