### ISSUE TITLE
ignores nm's

### ISSUE THREAD

**Issue by wilsteir** [Masuzu/ZooeyBot#159]
Heyo, so as the title says, it works fine but flat-out ignores any nms that pops up during events, links are probably set correctly, because when I put "NightmareModeAvailableAtStart" into "true" it goes there. Once. then continues to ignore them. here's my code: http://imgur.com/a/8jTPA

**Comment by Masuzu** [comment]
I confirm that the feature works as intended as I have been farming Fenrir since the event started.
`NightmareModeAvailableAtStart` should be set to true only if the nightmare mode is available when you start the bot, and set to false otherwise.

**Comment by wilsteir** [comment]
yeah, my friend using it and it works just fine for him, yet it nevertheless doesnt work for me. Also Im setting that to true only when nm is up, yeah, that'd be pretty lame if it was that. Should I give you the whole code so you may check out?

**Comment by wilsteir** [comment]
there are two cases for me:
first is when I don't have any nms up and just set  "NightmareModeAvailableAtStart" to false. Here it just runs ex's and completely ignores any nms that pops up.
second is when I have nm up (usually after I check if the bot runned these said nms or not), I set  "NightmareModeAvailableAtStart" to true and it runs that nm as intended, but any further are ignored like the first case.
