### ISSUE TITLE
Slave Mode Problem

### ISSUE THREAD

**Issue by mynameisjovi** [Masuzu/ZooeyBot#16]
Hello
There is a problem of salves mode.
It will stuck on "the processing turn 1 of main account"
No matter i use lua script or empty it (do not use lua script) of the main account.
It will still stuck on this place.
Thank you.

![1](https://cloud.githubusercontent.com/assets/27763675/25790439/1a69a95c-33eb-11e7-8187-c7a0326b6aea.png)
![2](https://cloud.githubusercontent.com/assets/27763675/25790440/1a6d480a-33eb-11e7-9605-8a380da16d63.png)
![3](https://cloud.githubusercontent.com/assets/27763675/25790441/1a6fb432-33eb-11e7-9bdc-878db17fcb54.png)

**Comment by po456asd** [comment]
in this case try to completely close chrome and try again
if not
try to swap slave and main account window position

**Comment by Masuzu** [comment]
Hello,
There seems to be some weird interaction (a bug on Google's side) when several DevTools window are open such as in slave mode but it is not happening all the time.
When it says "Processing turn 1 of Main account", at least it should make the main account window active and set on the front.
I will release a new version with slightly more info today.

**Comment by Masuzu** [comment]
@po456asd @mynameisjovi Some updates to make it easier to use the slave mode which will make it easier to see if there is an issue before starting the stage.
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes

**Comment by mynameisjovi** [comment]
@Masuzu I got the message of "New slave network request received". However, it will still stuck on the main account attack. (Waiting for attack button to be active)
![4](https://cloud.githubusercontent.com/assets/27763675/25801006/4efda9c4-341e-11e7-9a5a-63dd8058b4a0.png)

**Comment by BakaPhoenix** [comment]
I have the same problem, stuck at using char 1 skill

**Comment by BakaPhoenix** [comment]
I fixed it by enabling viramate keyboard shortcut

**Comment by mynameisjovi** [comment]
@BakaPhoenix Even I remove viramate still stuck at the same place :\

**Comment by BakaPhoenix** [comment]
If you removed viramate make sure you put false on viramate config setting

**Comment by mynameisjovi** [comment]
@BakaPhoenix Yes, I put false on setting but still stuck on "Waiting for Attack button to be active"

**Comment by mynameisjovi** [comment]
After I try to use my main account to be Slaves, and the salves account to be Main (incognito window) , it finally not stuck on the first round attack but it keep refreshing the main account window and never stop refreshing.

![5](https://cloud.githubusercontent.com/assets/27763675/25820503/04e91df0-3464-11e7-9077-260fd1de47df.png)

**Comment by po456asd** [comment]
maybe zooey (main extension) doesn't like you
![image](https://cloud.githubusercontent.com/assets/13596788/25820735/85088960-345c-11e7-88c7-7b0d66dc5c18.png)
try buy her some skin.

**Comment by po456asd** [comment]
btw what your screen size?
have you try on completely clean chrome? (no extension except zooey and zeta)

**Comment by mynameisjovi** [comment]
lol already bought her skin
my game setting screen size is medium
i tried to completely clean chrome but still keep refreshing the window
![6](https://cloud.githubusercontent.com/assets/27763675/25821345/5314ffdc-3467-11e7-9a4f-fb99141fe1e6.png)

**Comment by po456asd** [comment]
i mean your desktop screen size (like 1280*720 1600*900 1920*1080)

**Comment by mynameisjovi** [comment]
my desktop screen size is 1920*1080

**Comment by po456asd** [comment]
oh and beware about room id, raid id, or everything that look like a random number id. they can check that.
like who in this room id or something.
![image](https://cloud.githubusercontent.com/assets/13596788/25821503/8b66f460-345f-11e7-840f-7ecd8bbc6fff.png)

**Comment by scortie** [comment]
![report](https://cloud.githubusercontent.com/assets/28549219/25830016/d5c9feea-340e-11e7-87f0-c41df141e813.png)
I'm having a similar issue, except it never even proceeds to the quest screen. I hit enter on the slave main screen check, then it opens coop lobby on slave and refreshes main window constantly and nothing else happens.

**Comment by Masuzu** [comment]
Sorry for the late reply, I have been busy.
```
After I try to use my main account to be Slaves, and the salves account to be Main (incognito window) , it finally not stuck on the first round attack but it keep refreshing the main account window and never stop refreshing.
```
That is the normal behaviour by default after each turn: after pressing on the attack button and if the parameter `ReloadPageOnLastBattle` is set to true, the page will be refreshed, until the quest is cleared.
That holds true if you use a different script than https://github.com/Masuzu/ZooeyBot/blob/master/Scripts/slime_blasting_sword_master.lua for one of the two accounts.

**Comment by Masuzu** [comment]
@scortie Regarding your latest screenshot, Zooey will wait for the "Ready" button to be visible **and** _not selected_. Otherwise, it will refresh the main account page over and over. Make sure that at the start, you did not select the "Ready" button.

**Comment by Masuzu** [comment]
@mynameisjovi Could you please share the Lua scripts you use and the co-op quest you are trying to clear? It looks like you are not using any Lua script so both accounts will try to attack to death the enemy. This may be a bug and I will test it later.

**Comment by Masuzu** [comment]
@BakaPhoenix About Viramate and skill usage, very good point indeed. I will update the FAQ section later on.

**Comment by Masuzu** [comment]
It looks like there is an issue when the Slave window is wrongly identified at the start (that is to say when you have to press "DELETE" during the calibration phase). Otherwise things run smoothly.

**Comment by mynameisjovi** [comment]
@Masuzu here is a video of stuck at "Waiting for attack button to be active"
[https://youtu.be/ZIV4SNd5M_8](url)

**Comment by BakaPhoenix** [comment]
did you set that script in the slave mode `MainAccountLuaScript=` ?

**Comment by mynameisjovi** [comment]
Yes, i have set a script for mainaccount

**Comment by Masuzu** [comment]
I am afraid that the bot is blocked at the moment when it tries to detect the Attack button, but this should not happen if you managed to proceed to the co-op stage.
I will try to see if I can reproduce the issue. If not I'll link a custom binary with more message.

**Comment by Masuzu** [comment]
@po456asd As you mentioned this point in particular, I have good news for you: https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes
You won't need anymore to restart the bot if the slave window is incorrectly identified: https://github.com/Masuzu/ZooeyBot/issues/25
