### ISSUE TITLE
Can't continue Fennir hell

### ISSUE THREAD

**Issue by NzString** [Masuzu/ZooeyBot#162]
When entering hell, sometimes popup appears.
and zooeybot stops.

<img width="349" alt="2017-07-13 1 39 32" src="https://user-images.githubusercontent.com/26919276/28150727-3d82c51c-67d1-11e7-9f46-96ad19e7bd6e.png">

**Comment by Masuzu** [comment]
The version 1.13.2 is supposed to fix this issue by refreshing the page after a certain amount of time.
If not, could you please describe exactly on which page it appear (URL/screenshot of the whole screen)?
Thank you.

**Comment by NzString** [comment]
I didn't update. Thank you for answer.
