### ISSUE TITLE
GBF url warning

### ISSUE THREAD

**Issue by gbf27** [Masuzu/ZooeyBot#164]
【グランブルーファンタジー】7/13(木) 20:45に実施したアップデートにて、難易度HELLのクエストにおいて、ドロップを確認してからURLを改竄することで、不正に再挑戦できる不具合を修正しました。詳細はゲーム内のお知らせをご確認ください。 #グラブル

can I ask if this puts the bot at risk? I heard it is something about bans via URLs etc

**Comment by Dreamfinal** [comment]
Could it run sound alert notification instead of exiting program?

in long term we will change process form using url to image processing
so bot will click on the real image

**Comment by Dreamfinal** [comment]
http://i3.photobucket.com/albums/y86/dreamfinal/321_zpsryypmsvg.png

**Comment by Dreamfinal** [comment]
Or try to solve this problem in this way.

step 1.http://game.granbluefantasy.jp/#quest
step 2.http://game.granbluefantasy.jp/#quest/extra
step 3.http://game.granbluefantasy.jp/#quest/supporter/500411/5

Instead of
http://game.granbluefantasy.jp/#quest/supporter/500411/5

**Comment by GBFThrowaway** [comment]
I'd be careful for now. This is the second time I've been suspended this event.

http://i.imgur.com/9dWtyHS.png

**Comment by Masuzu** [comment]
Hello everyone,

This issue is completely unrelated: 
There was a bug which allowed hosting Nightmare modes repeatedly, which is a bannable offense.
More details in https://www.reddit.com/r/Granblue_en/comments/6n87l0/violation_of_rules_by_manipulation_of_url/
