### ISSUE TITLE
Bot stuck at result page

### ISSUE THREAD

**Issue by maguno** [Masuzu/ZooeyBot#166]
Before in the Fenrir event it was working normaly and it was also working well after it and then turning off event mode (tried deluge trial for one day and it worked fine), but now at any quest it is stuck in the result page, nothing was changed, also tried to recalibrate but it continues trying to reach the adress bar and then does nothing in the result page

**Comment by Masuzu** [comment]
Please post a screenshot of the console messages when it gets stuck.
