### ISSUE TITLE
Target selection

### ISSUE THREAD

**Issue by pcfemail** [Masuzu/ZooeyBot#167]
I have looked for the way to select specific enemy in Lua scripts sections and I could not find a way to select.

Is there any way to script in order to select enemy to attack?

As you know... Xeno Vohu has many special behavior

**Comment by Dreamfinal** [comment]
I agree with you.

**Comment by Masuzu** [comment]
Target selection is now live with version 1.14.0
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#1-14-0
