### ISSUE TITLE
Can you make Zooey count Korwa's Fil?

### ISSUE THREAD

**Issue by cobeng13** [Masuzu/ZooeyBot#170]
(enhancement)
Would it be possible to add this feature to count Korwa's Fil as a variable.
Currently I am using "if turn == x", however due to the randomness of Korwa being hit, this method is unreliable unless I know there is an incoming AoE attack to anticipate. Thanks in advance!

**Comment by Masuzu** [comment]
Hi there,
Sure thing, I had this in mind too and will do something about it later on.

**Comment by Meiun** [comment]
being able to keep track of stacks will also help with metera and sutera.

**Comment by Djeeta-kun** [comment]
Please help how to use lua script?

**Comment by Djeeta-kun** [comment]
will there be a script available for GW meat farming?
