### ISSUE TITLE
 It has a little bug (Select Target)

### ISSUE THREAD

**Issue by Dreamfinal** [Masuzu/ZooeyBot#171]
```
DisableChargeAttack
if turn == 1 then
     SelectTarget(3)
end

if characters["abcdefg"].charge_gauge == 100 and  etc and etc2  and etc3 then
     EnableChargeAttack
end
```
SelectTarget - First
EnableChargeAttack - Second
Bot status = Normal 

```
DisableChargeAttack
if characters["abcdefg"].charge_gauge == 100 and  etc and etc2  and etc3 then
     EnableChargeAttack
end

if turn == 1 then
     SelectTarget(3)
end
```
EnableChargeAttack - First
SelectTarget - Second

Bot status = Click stopped  

----------------------

Not a major bug.
You have free time to edit.

**Comment by Masuzu** [comment]
Hi,
Target positions should be in the same order as the enemy HP gauges at the top of the raid battle window.
Therefore, the enemy in the middle does not necessarily corresponds to the enemy #2.
You could test it in the trial battle for instance using the [TrialBattleMode] (set the corresponding parameter in the [Debug] section to true) to make sure that you select the correct enemy beforehand.
