### ISSUE TITLE
Help with ini config for the poacher event

### ISSUE THREAD

**Issue by maguno** [Masuzu/ZooeyBot#173]
[EventMode]
 Set this parameter to true to use the event mode. Zooey will enter autopilot mode when you navigate to the quest menu.
Enabled=true
  Url of the summon selection page for Poacher
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/719981/3
EventRaidScript=Scripts/elemental_water_summer.lua
 Url of the summon selection page for Dimensional Halo
NightmareModeUrl=
NightmareModeScript=
Some events such as Rise of the Beasts require to navigate to the home page of the event before navigating to the event raid url defined above. If EventPageUrl is provided, Zooey will first navigate to this url before hosting the raid. Leave EventPageUrl blank for events which do not require you to do so.
EventPageUrl=

When I try to start it always go back to home screen
![console](https://user-images.githubusercontent.com/17077212/28809750-a9e11afe-765b-11e7-92af-c4919a83d222.png)

**Comment by MagCat** [comment]
I need some help on this too. Bot just freezes with event mode set to true. If I use TreasureEventMode it can't go straight to the link battle without going through the main event page.

**Comment by Masuzu** [comment]
Hi,
You can't use the Event mode for the poacher event since to host the quests, you need items.
The treasure event mode is there for this.
