### ISSUE TITLE
slow slime bot

### ISSUE THREAD

**Issue by spongebear** [Masuzu/ZooeyBot#174]
Not sure what happened, before this the bot will ocassionally refresh the main account thrice. but right now it refreshes after every single slime.. anyone facing this issue as well?

**Comment by Gaburu** [comment]
Console always said "Something went wrong while trying to set the quest, checking what might be wrong.

**Comment by spongebear** [comment]
yea. it's happening after every round.

**Comment by greatmany** [comment]
I have the same problem as well, the quest is already set but the bot says something went wrong while trying to set the quest.

**Comment by dippaa** [comment]
having the same issue

**Comment by sellsell** [comment]
Same issue here, both the slave and main account will refresh at least once before pressing Ready and continuing the loop, accompanied by the ""Something went wrong while trying to set the quest, checking what might be wrong." message.
This doesn't just happen occasionally either, it does this after every single round without fail which significantly slows down the entire process.
Playing around with the MinWaitTimeInMsAfterRefresh setting doesn't do anything.

**Comment by spongebear** [comment]
yup, need to wait for masuzu to solve it

**Comment by Masuzu** [comment]
Hi, I noticed it too and apologize for the issue.
The version 1.14.1 to be released within 1 hour will fix this.

**Comment by spongebear** [comment]
thanks for the quick update!
