### ISSUE TITLE
Bot starts clicking bookmarkbar after finishing quest once.

### ISSUE THREAD

**Issue by devvah** [Masuzu/ZooeyBot#175]
Bot works perfectly well until it gets to results page, then instead of continuing it just starts to spam clicking bookmark bar below url (hiding bar doesn't change anything) forever until I close it with F1.

I'm using standard mode to farm extreme elemental trials.

**Comment by Zoiya** [comment]
same here. 
1920x1600 1600x900  
![zooey1](https://user-images.githubusercontent.com/30725529/28969719-f800b84c-794f-11e7-9db5-cc1e91d86a7e.png)
![zooey2](https://user-images.githubusercontent.com/30725529/28969718-f8000aa0-794f-11e7-9719-a15531492c19.png)

**Comment by Masuzu** [comment]
Hi there,
I am not sure I can reproduce the error. It is the first time I see this.
This is what my browser window looks like with a 1:1 scaling:
![](https://i.imgur.com/oqdKfKc.png)

**Comment by devvah** [comment]
I've got my solution after hours of tinkering, basically the problem was using chrome in maximized mode, once I switched to windowed bot stopped having problems and started farming no problem, I guess it would be good to put that into tutorial?
