### ISSUE TITLE
Zooey Bot calibrate- Vertical offset 104

### ISSUE THREAD

**Issue by Ramkm77** [Masuzu/ZooeyBot#176]
The bot was working perfect before . Now trying to start do slime but always gives me calibrating issue saying Vertical offset 104 . Tried a lot to try many resolution but still same

**Comment by Masuzu** [comment]
Make sure that the Home button is fully visible in the top left corner.
If it is the case already, then your scaling settings must be wrong:
https://github.com/Masuzu/ZooeyBot/wiki/FAQ#i-have-scaling-issues-again
The message saying "vertical offset" is just informative.

Even if it is not your case in this issue, for issues where nothing is happening after starting the extension, someone had a similar issue: https://github.com/Masuzu/ZooeyBot/issues/177

**Comment by Ramkm77** [comment]
Thx masuzu for the answer . It's solved by changing both accounts to standard animation and standard resolutions.
