### ISSUE TITLE
Nothing happens when I click start on the extension 

### ISSUE THREAD

**Issue by iDorkyKenny** [Masuzu/ZooeyBot#177]
"Please check the configuration parameter ChromeDevToolsWindowDockedOnTheRight depending on which side your Chrome DevTools window is docked. The former has to be docked either on the right or at the bottom. Thank you.Please start the Zooey bot Chrome extension to get started"
![image](https://user-images.githubusercontent.com/17240142/28924298-1b6610ec-7816-11e7-8432-e74ba2369f4d.png)

![image](https://user-images.githubusercontent.com/17240142/28924381-69cab0da-7816-11e7-8972-3d9f3fb20a6d.png)
the f12 console menu is on the right side of my browser 

![image](https://user-images.githubusercontent.com/17240142/28923786-0b443cf4-7814-11e7-99b2-a6a7224ce70c.png)
![image](https://user-images.githubusercontent.com/17240142/28923818-3499c3b2-7814-11e7-87b5-90aba9f71770.png)
![image](https://user-images.githubusercontent.com/17240142/28924196-ba45d7de-7815-11e7-845c-18662d15bd1b.png)

I've tried restarting my browser and computer multiple times, made sure I already installed all the prerequisites and reinstalling zooey bot. None seem to help.

**Comment by Masuzu** [comment]
Some firewalls may block some of the features. Otherwise, closing the executable file then reopening the Chrome browser after some time and proceeding as usual will do the trick.
