### ISSUE TITLE
Coop Slave/Master issue.

### ISSUE THREAD

**Issue by angstbian** [Masuzu/ZooeyBot#178]
I've been trying to use the slime-blasting feature, but after I set up the slave and master for the blasting, Zooey tries to host on the master account, which causes her to be very confuses about where the ready button is, and she then just refreshes over and over again.

**Comment by Masuzu** [comment]
Make sure to press correctly ENTER or DELETE depending on which window corresponds to the account which will host the co-op quest.
Also make sure _not_ to press the ready button.

**Comment by angstbian** [comment]
I did do this, but regardless of whichever one is the slave, it tries to host on the one that isn't hosting?
