### ISSUE TITLE
Zooey stop at calibrating line

### ISSUE THREAD

**Issue by Kluiman** [Masuzu/ZooeyBot#18]
![image](https://cloud.githubusercontent.com/assets/28539574/25814007/f987a2d8-3445-11e7-9be2-4e01854b1ec2.png)

**Comment by Kluiman** [comment]
and it stuck there

**Comment by Masuzu** [comment]
1. Please make sure that you have the "Home" button visible in the top left hand corner of the game.
2. If you do please make sure that you set the language setting properly
3. If you still have the same issue then it's 100% a scaling issue again: https://github.com/Masuzu/ZooeyBot/wiki/FAQ#i-have-scaling-issues-again

**Comment by Kluiman** [comment]
Pokerbot works fine so far. And, yes my screen is at 100% following the FAQ.

**Comment by Kluiman** [comment]
![image](https://cloud.githubusercontent.com/assets/28539574/25855876/8f154d24-34fe-11e7-8ab9-a96b5986b9e7.png)
my current quest menu
