### ISSUE TITLE
i accidently change serial number.

### ISSUE THREAD

**Issue by kensu46** [Masuzu/ZooeyBot#181]
can u change reset my serial number, i accidently change my serial number without much though
bcos i need to wait for 4 days, i just buy zooey bot today for slime blast
my id email is: daniel143500@gmail.com
![kjh](https://user-images.githubusercontent.com/29462956/29013919-5fd8aaca-7b70-11e7-894e-9e65663388e5.png)

**Comment by kensu46** [comment]
![fdsfdsfds](https://user-images.githubusercontent.com/29462956/29013673-bcc038ea-7b6e-11e7-921f-3f5179fe0ed9.png)
can u reset my serial number bcos i need to wait for 4 days, i just buy zooey bot today for slime blast
my id email is: daniel143500@gmail.com

**Comment by kensu46** [comment]
and btw, i buy zooey bot and poker bot, but the expiration date is the same?? and same serial number? hmm

**Comment by kensu46** [comment]
![kjhiuyiuy](https://user-images.githubusercontent.com/29462956/29014020-06e156e6-7b71-11e7-8a55-4af562f50c39.png)
please help me

**Comment by mawile0816** [comment]
I have same problem... Could you help me?
My email: asakaze0816@gmail.com

**Comment by Masuzu** [comment]
Hi,
I may remove temporarily the 4-day limitation but this is exceptional.

**Comment by Masuzu** [comment]
The 4-day limitation was temporarily removed.
