### ISSUE TITLE
Enabling ViraMate in battle

### ISSUE THREAD

**Issue by Dest1nationX** [Masuzu/ZooeyBot#182]
I've been trying to use viramate, but it didn't work. I already set UseViramate parameter to true, and enabled the hotkeys option for viramate, but the bot is still using character panels and manually use skills from there. Anything did i miss to set up the viramate? Thanks

**Comment by Masuzu** [comment]
You must have forgotten to save the ini file after making the modification.
I am positive there is absolutely no issue on this side since me and many other users also set `UseViramate=true` with the latest version.
