### ISSUE TITLE
licence suddenly expired?

### ISSUE THREAD

**Issue by pcfemail** [Masuzu/ZooeyBot#185]
I was using zooey bot and my licence suddenly expired.
The expiration date has become 5/25/2009 which made no sense.
Any help?

**Comment by Dreamfinal** [comment]
same

**Comment by BakaPhoenix** [comment]
the whole site is down, probably server went rip and cannot check license expiration date

**Comment by MagCat** [comment]
Hopefully this isn't the end of our botting days...

**Comment by Masuzu** [comment]
Hello,

I apologize for the inconvenience. Do not fret, it should be back to normal within the next hours:
https://twitter.com/GBFPokerBot/status/895350987858354176

**Comment by Masuzu** [comment]
The website is now back, happy sliming or farming!
