### ISSUE TITLE
My account's Expiration date changed 2009/5/25

### ISSUE THREAD

**Issue by mawile0816** [Masuzu/ZooeyBot#186]
@Masuzu 
Hello.
My account's Expiration date changed to 2009/5/25

Yesterday, I requested that remove temporarily the 4-day limitation.
But I can not change serial number even this time.
I think, there was some trouble in removing the 4-day limitation temporarily.

My Account is this : asakaze0816@gmail.com

I apologize for the inconvenience this has caused you.

**Comment by Masuzu** [comment]
Hello,

I apologize for the inconvenience. Do not fret, it should be back to normal within the next hours:
https://twitter.com/GBFPokerBot/status/895350987858354176

**Comment by Masuzu** [comment]
The website is now back, happy sliming or farming!
