### ISSUE TITLE
Invalid login attempt

### ISSUE THREAD

**Issue by WeylandYuuyani** [Masuzu/ZooeyBot#187]
@Masuzu Hi, ever since your server maintenance I haven't been able to get in my account to get my license. The email is WeylandYuuyani@gmail.com.

**Comment by WeylandYuuyani** [comment]
Please help me with this! I can't change the S/N nor get the license at this rate!

**Comment by WeylandYuuyani** [comment]
@Masuzu okay, I recreated the account with another random serial number with the same address, got the same email address but now I can't change it back to my PC's S/N anymore (since it kept saying my PC/s S/N being used) so I can use the bot. The server outage really damaged my account information here.

**Comment by Masuzu** [comment]
Hello, do you mean you did not manage to login?
You can reset your password here: https://poker-bot.azurewebsites.net/en/Account/ForgotPassword

**Comment by WeylandYuuyani** [comment]
@Masuzu That's the problem. Something wrong with the server outage yesterday that did not recognized my account registration but kept the S/N instead. I tried to use the ForgotPassword and it didn't work since the email basically didn't exist. I only realized that because I made a new one with the same exact email. with random SN, which means that now my account is stuck with a random SN and not the one I use for my PC. Should I write the S/N below or write you an email so you can look at the database?

**Comment by Masuzu** [comment]
Either is fine.
If the other user who has the same S/N has no active licence I will delete his account so you can use again that S/N.

**Comment by WeylandYuuyani** [comment]
@Masuzu:  Sorry for late reply I haven't been able to play the game much these 2 days. This is the S/N I am using to register, which was stuck in the account that was lost to the server outage.
`b8bb56a96c61c4c49406f6d35e122aa8f9b5679014c4d86e13c13e87c4c89ef41785c1ed2636fb92783a60ac4c5b5577825f1bd58d3f7cd8b502e2ad57edebae`

**Comment by Masuzu** [comment]
The user who was using this serial number was deleted as he had no active licence. You should now be able to reuse this S/N.
