### ISSUE TITLE
Potion use + Character active effects

### ISSUE THREAD

**Issue by Dreamfinal** [Masuzu/ZooeyBot#189]
After update 1.14.2, the mode coop works perfectly.

Previous bugs and issues are gone and never shows up again.
https://github.com/Masuzu/ZooeyBot/issues/147
https://github.com/Masuzu/ZooeyBot/issues/143

What I'm waiting right now are

1. Coop with 3 monitors for the better effectiveness in farming red potion. It can loop infinite because the third account often drops red potion.

2. Able to use green and blue potion.

3. Characters'buff can be countable i.e. Korwa buff

If these requests are granted, the bot will get even closer to the absolute perfection.

**Comment by Masuzu** [comment]
Hello,
I am glad to hear this.
I won't implement the point 1 due to inherent limitations with the Chrome browser.
I will take a look into 2 and 3 after the end of the summer campaign.

**Comment by Masuzu** [comment]
Closing at it is a duplicate ticket
