### ISSUE TITLE
"OK" button is hidden behind bottom menu, so Zooey cant click on it

### ISSUE THREAD

**Issue by prokopets** [Masuzu/ZooeyBot#19]
Hello, Masuzu. Really like your grind bot, but unfortunetly i am stuck with this problem...

So, i have done all settings correctly. Zooey bot selects summon, and after that this happens...it gets stuck on clicking OK button, as it is hidden behind bottome menu. 
![sc1](https://cloud.githubusercontent.com/assets/22854160/25816234/1c017326-342c-11e7-9072-676e6504b00d.png)

Everything is working fine in fullscreen mode, but, as there is no address bar, zooey can't refresh quest. Tried moving my bottom menu to the right and this is maximum i could get. 
![sc3](https://cloud.githubusercontent.com/assets/22854160/25816269/36edfe48-342c-11e7-8e4f-835aed4fc06a.png)

Measures for co-op quest is close to yours
![sc4](https://cloud.githubusercontent.com/assets/22854160/25816341/7cbc47fe-342c-11e7-83bf-f93cc74fa150.png)

My setup is laptop with 1368 x 768 resolution.

Settings:
![set1](https://cloud.githubusercontent.com/assets/22854160/25816223/10a3ac2e-342c-11e7-8cc1-14bc7bc57aff.png)

And btw, on yours setup guide it shown in bottom menu option - off/on, while for me it's - off/large. I wonder why is this way. 
Can you please suggest me smth? Would really appreciate it! Thank you in advance!Will answer all questions if needed. 
UPDATE: works good on 1920 x 1080 res(

**Comment by Masuzu** [comment]
Hello,

Thank you for reporting this, I will update the guidelines later on.
Please make sure to never have the 'OK' button on the summon selection page overlaid by any other button. You should just increase the height of your Chrome Window.
I have a screen resolution of 1920 x 1080 too so there should be no reason for it not to work on your side!

**Comment by prokopets** [comment]
The problem is that i cannot make button not being overlaid by anything else, because resoluiton seems to low. 1366 x 768 is max resolution for my laptop i can get. And Chrome window in no way can be incresed in height. Yeah, i have another pc with 1920 x 1080 resolution and there bot works great. But unfortunetly i dont have access to it the whole time, so it there solution to low res monitors?( If only bot automatically scrolled down a little when summon was selected...

**Comment by osidavi** [comment]
@prokopets your problem and mine is similar, my monitor's max resolution is 1366 x 768, so there i no hope for us right now then
