### ISSUE TITLE
Zooey bot failed to parse script

### ISSUE THREAD

**Issue by nyaonyao56** [Masuzu/ZooeyBot#191]
I made a script to use skill in notepad++ encoded it as utf-8 saved it into the Scripts folder and set my EventRaidScript = Scripts/placeholder_name.lua

Everything is fine until my scripts turn 3 battle when I try to make my summer zooey use her skills and it would give a zooey bot lua script error: Failed to parse lua script D:\zooey-bot-v1.14.3\Scripts\placeholder_name.lua:1:. Here's my script

if battle == 3 and character_1.charge_guage >= 100 then
	EnableChargeAttack()
else
	DisableChargeAttack()
end
if battle == 1 and turn == 1 then
	Summon(6)
end
if battle == 3 and turn == 1 then
	characters["Zooey"]:UseSkill(2)
	characters["Zooey"]:UseSkill(3)
end

**Comment by Dreamfinal** [comment]
```

DisableChargeAttack()

if character_1.charge_guage >= 100 then
    EnableChargeAttack()
end

if battle == 1 then
    Summon(6)
end

if battle == 3 then
    characters["Zooey"]:UseSkill(2)
    characters["Zooey"]:UseSkill(3)
end
```

**Comment by nyaonyao56** [comment]
Does using and turn == *some integer value* not work anymore?

**Comment by Masuzu** [comment]
You can safely ignore the message "no response for an abnormally long time".
