### ISSUE TITLE
bot cant skill

### ISSUE THREAD

**Issue by kensu46** [Masuzu/ZooeyBot#194]
![kjhkjh](https://user-images.githubusercontent.com/29462956/29238498-0247b0aa-7f61-11e7-81d4-672923025e93.png)

**Comment by Masuzu** [comment]
Hello,

Maybe this applies in your case:
https://github.com/Masuzu/ZooeyBot/wiki/FAQ#zooey-is-not-using-skills-or-summons-but-my-lua-scripts-are-valid-viramate-user
?
