### ISSUE TITLE
Delighted but I have a few questions! 

### ISSUE THREAD

**Issue by Copiousity** [Masuzu/ZooeyBot#195]
I am very delighted with the bot. The bot has been useful for me for the past few days!
Except I have a few problems with it. The bot farmed Angel Halo and Six-Dragon just fine while I was away.
But I can't get it to do my Story Quests. 

Also is it possible to configure the bot to auto raid for the current event raid "Five Flowers of Fate"?
Can I get some help with the .ini for that?

Thank you so much

**Comment by Masuzu** [comment]
Hello,

You need to add the story quest(s) you want to automate to your list of favourite quests beforeand then use the default mode (https://github.com/Masuzu/ZooeyBot/wiki/Basic-mode---story-quests,-free-quests-and-special-quests-automated-farming).
After the calibration phase, simply click on the favourite quest button and follow the instructions which are displayed in the console.

To automate farming the current event, you want to use the EventMode (https://github.com/Masuzu/ZooeyBot/wiki/Event-mode)

In the EventMode section, set:
`Enabled` to true
`EventRaidUrl` to the URL of the stage/raid you want to farm.
`EventPageUrl` to http://game.granbluefantasy.jp/#quest/extra/event/11009
Leave blank `NightmareModeUrl` to ignore the nightmare modes.
Also, make sure to write and set the script you would like to use or else only auto attacks will be performed.

You can also force Zooey to refresh the summon list when some of them are not available, more information about this feature can be found here:
https://github.com/Masuzu/ZooeyBot/wiki/Summon-selection

**Comment by Copiousity** [comment]
Thank you so much!
