### ISSUE TITLE
Suggestions : raid scheduling + NM mode issue with the default mode

### ISSUE THREAD

**Issue by LordShade** [Masuzu/ZooeyBot#197]
Hi, just a few suggestions but I do not know how hard they are to implement if they can be at all.

Firstly, is "TimeLimitInSeconds" the amount of time you want Zoey to play? if it isn't, then the first suggestion can be useful, if it is - well, I haven't seen Zoey pay attention to this config option at all. But you can ignore my first suggestion if its working as intended.

1. The Ability to be able to set a length of time you want zoeybot to play, something like a config variable TimeToPlay and this can be set in milliseconds/seconds afterwards,  So if you want Zoey bot to only play for 2hrs and then to hard stop and exit, it can also display a message such as "Zoey Bot has reached time limit, stopping!" Which leads onto...
2. The ability to set rest breaks for Zoey every hr, while most likely complex to get working properly, the ability to set this is a great way to avoid captcha. As you can set Zoey to take a break every hr or so for 15minutes. The sentence "Zoey is tired, taking a rest now for XX minutes" can be displayed on the console to indicate when a rest break has started.

And thirdly

3. Variables that Zoey will recognize to do the VH and N primals in Lua scripts. While these primals are essentially raids, they are very easily solo-able with anybody who has a decent to mid-tier weapon pool, the problem is they're a lot of them, and completing them all is a very tedious objective. But this is absolutely essential for valor farming so you can trade it in for weapons you can't get to drop. If this is already possible in the current build, I wouldn't mind an example Lua config/script on how it can be done! Including variables that can be set to do the primals only 3 times each! Because they are limited to 3 and rarely 5 on some occasions. She will also need to know how to stop after reaching Celeste VH completion 3/3.

4. A simple variable in the config that allows zoey to ignore dimension halo spawns. While grinding for a 5star GW is nice, it is simply out of reach for me at this moment and is something I do not want to do because of lack of gold bars to do it, so a simple config option can be setup so we have the choice to drown in angel fodders, something like "DrownInAngelFodder" True/False

Thanks!

**Comment by Masuzu** [comment]
Hello,

Indeed, the variable `TimeLimitInSeconds` already does what you mentioned in the first point.
As for second point, catpchas are not an issue at all. I have been sliming for several hours per day this magna fest with 2 captcha per day at least. You just need to make sure to complete them as soon as they appear, hence the sound notification which will loop until you stop Zooey manually by pressing F1.

I do not have yet support for custom raid "scheduling", like do Raid A 3 times, then Raid B twice, then Raid C 3 times, then stop. It would be only limited to Magna fest mostly so I did not really spend time implementing this feature. Why not having such a thing in the future indeed.

The 4th point is already supported. Simply leave the URL of the nightmare mode blank and it will skip the nightmare mode. You can also use the default mode (story/special quest/free quest farming) and Zooey will skip all the nightmare modes.

**Comment by LordShade** [comment]
thanks for the response and clarifying a few variables. I'll mess with TimeLimitInSeconds for setting timelimits that I want zoey to be active.

I would guess for raid scheduling it would be something like 
If bossbattle == 3 do (link to support summons page for tia hm/n here)
-followed by-
if bossbattle == 0 do (link to support summons page for colo hm/n here) and etc

while it sounds simple, I'm not sure if Lua is capable to hold a link in its code effectively. 

as for number 4, I checked zoeyconfig.ini and made sure all nightmare mode links were blank, I was under the assumption that with event mode disabled, zoey would ignore all links in the event mode area. However, even in default mode, she was stopping when nightmare mode popped and got stuck until I closed the timer. I will try this again with the link in event mode nightmare set blank however and see what happens.

**Comment by Dreamfinal** [comment]
your set NightmareModeUrl to null

example
```
[EventMode]
Enabled=true
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/510031/5
EventRaidScript=Scripts/event.lua
NightmareModeUrl=
NightmareModeScript=
```
and set
NightmareModeAvailableAtStart=false

**Comment by Masuzu** [comment]
About the raid scheduling, you can do such a thing with Lua scripts, it is not an issue at all.
The priority after the magna fest and before the start of the GW, if I can, will be to add the ability to use potions in raid battles (green and blue ones, as well as GW items, a bit later during this GW).

Thank you for reporting the issue about the default mode.
It looks like something was broken with one of the changes.

**Comment by Masuzu** [comment]
About that nightmare mode issue with the default mode, I can't reproduce the issue on my side 🤔 
After a Nightmare mode appears, a message appears in the console telling so and the timer window also pop ups.
Then the bot goes on and set immediately after the URL of the quest to repeat it.

**Comment by LordShade** [comment]
it appears whatever you did, this was fixed in the latest update.  The bug tag can be removed I would guess and the enhancement tag left for raid scheduling.
