### ISSUE TITLE
Need help identifying coop quest ID

### ISSUE THREAD

**Issue by spongebear** [Masuzu/ZooeyBot#198]
I couldn't find the coop quest ID that was shown in the picture masazu showed.

https://imgur.com/a/q7xSf

anyone know whats the ID for this?

**Comment by kensu46** [comment]
same here, idk how to see the code i click F12 but cant find the id quest

**Comment by Masuzu** [comment]
Hi,

Simply do as in the picture shown here. You have a search feature in the DevTools window to search for tags in the HTML page. Simply look for `data-quest-id`.
