### ISSUE TITLE
RetreatWhenNoDimensonalHaloTransform=true, but no retreat?

### ISSUE THREAD

**Issue by sonderbyyonder** [Masuzu/ZooeyBot#199]
As described in the title. Is there anything I'm doing wrong?

**Comment by Masuzu** [comment]
I tested it with the version 1.14.1 and it still applies to the more recent versions without any fail on my side.

**Comment by sonderbyyonder** [comment]
Thanks I'll try again and get back to you. I should be on the 'console' tab of F12?

**Comment by Masuzu** [comment]
No, you should be on the Network tab of the Chrome Devtools, as Zooey regularly clears the Network request history.
Otherwise, after 30 minutes or more, you will start experiencing issues.
