### ISSUE TITLE
Calibrating issue

### ISSUE THREAD

**Issue by Karbie** [Masuzu/ZooeyBot#2]
Hi, i tried using Zooey bot but the program would not get pass Calibrating. I followed the instructions from the website. Can it be because i am using multiple display?
<img width="724" alt="capture" src="https://cloud.githubusercontent.com/assets/25868014/25778362/3cbcde10-332e-11e7-9edd-d1eccf1b7e19.PNG">

**Comment by Masuzu** [comment]
Hello,

It's the notorious scaling issue again:
https://github.com/Masuzu/ZooeyBot/wiki/FAQ#i-have-scaling-issues-again
Someone had the exact same problem as you and got it fixed by using proper scaling settings.
