### ISSUE TITLE
Could you make detailed syntax's errors?

### ISSUE THREAD

**Issue by devvah** [Masuzu/ZooeyBot#202]
So I wanted to setup farm for remaining of this event but I can't, lua screams error even though I copied lines from already working scripts, I don't know what's wrong and error isn't helping me either since it only states that error is near character_1 in 3rd line, for my eyes it looks fine.

Here's script in question

```
if turn == 1 then
  DisableChargeAttack
  character_1:UseSkill(4)
  character_1:UseSkill(2)
  character_2:UseSkill(3)
  end
if turn == 2 then
  character_2:UseSkill(2)
  character_1:UseSkill(3)
  end
if turn == 4 then
  EnableChargeAttack
  character_1:UseSkill(1)
  character_4:UseSkill(3)
  Summon(6)
  character_3:UseSkill(2)
  character_3:UseSkill(3)
  character_3:UseSkill(1)
  character_4:UseSkill(2)
  character_4:UseSkill(1)
  character_2:UseSkill(1)
 end
```
What could be wrong here?

**Comment by devvah** [comment]
2 bonus issues! How lucky I'm today. :)

[image](http://i.imgur.com/km9veLW.png) 
As you can see above Zoi is just waiting for me to dismiss popup after auto-skipped sidescrolling scenes in Scattered Cargo.

2nd issue araised in 3rd fight in that quest when ReloadPageOnLastBattle was true as seen above in log, bot started refreshing page every attack, excepting it showed vyrn animation of reaching 3rd fight every time causing battle to take way longer than if bot wasn't refreshing page.

**Comment by Masuzu** [comment]
Hi,

It looks like your clicks are not registered. You can set the parameter `Clicks` to true to check when a click is performed.
2 possibilities:
- Antivirus blocking clicks
- Low computer specs
In both cases, I can't do anything on my end.
The basic assumption of the bot is that each time it performs a "click" then the click goes through.
Otherwise I am afraid you won't be able to use it properly

**Comment by Masuzu** [comment]
About your script posted above, you forgot parenthesis ;)
DisableChargeAttack()
EnableChargeAttack()

**Comment by devvah** [comment]
So clicks=true fixed sidescrolling issues.

Script was also fixed, thanks. :)

But that enforces my point about detailed error, I would never guess that 3: syntax error near 'character_1' means lack of parentheses in charges since that's different line and different command.
