### ISSUE TITLE
Invalid combat state retrieval with ProcessMainAccountTurnFirst=false [To investigate]

### ISSUE THREAD

**Issue by jsun1234** [Masuzu/ZooeyBot#203]
Hi Masuzu,
Here's the code I'm using to farm alluvium from coop:character_4:UseSkill(3)
character_4:UseSkill(1)
I have my main account set as slave since dummy account isn't advance through coop stages enough. What happens is that, it will skip skill 3 and go straight to skill 1. This order makes sarasa skill 1 do very little damage.

![coopfail]

I've tried increasing to as high as MinWaitTimeInMsAfterAbility=20 seconds. it still skips straight to skill 1.

Copy of my ini
[ZooeyBot.txt](https://github.com/Masuzu/ZooeyBot/files/1223665/ZooeyBot.txt)

**Comment by jsun1234** [comment]
I've also tried to rewrite as:
if turn == 1 then
character_4:UseSkill(3)
character_4:UseSkill(1)
end
 with the same results

**Comment by Dreamfinal** [comment]
You can also customize the waiting time after using an ability with the following syntax: characters_4:UseSkill(1):WithWaitTime(3500)

**Comment by Masuzu** [comment]
Hmm it looks like it could be an issue with the particular character Sarasa,
The only way for this to happen would be that her 3rd skill is on cooldown but that's not possible on the first turn. Weird indeed, I'll probably provide you with a custom version with more debug info.

**Comment by Masuzu** [comment]
However, I think the issue is not a bug but failure to set up properly the bot, for the following reason:
You have a message "No response received after using the ability" even though you set `MinWaitTimeInMsAfterAbility` to 20 seconds and `DoNotWaitForServerResponse` to false, meaning that the bot will wait 20 seconds after using the skill to get an acknoledgement that the skill was used.

I suspect that on your main account, the character at position 4 has no 3rd skill and that Zooey tried to determine the skill availability wrongly, using the party you had on your main account.

**Comment by jsun1234** [comment]
It should be using the skill 3 of my slave account. The main is just there to tag along for legal coop, but you're correct, the main chara 4 doesn't have a skill 3. I have the script set to ProcessMainAccountTurnFirst=false for this reason. Slave is supposed to kill it first but the mouse doesn't look like it's even trying to touch turn 3.

I've been using this great tool for slimeblasting and events and such for the last week and a half and rechecked the order multiple times. So far its only been a problem when I use my true main as a slave with my mule account as main in incognito window. Strange thing is I've used this set up to farm this non-slimeblast stage in coop before with a lot of fiddling. Just super flakey this way, but using it the original way with my true main as main and dummy as slave in incognito--never a problem.

I'll fuss around with it some more after gw. thanks

**Comment by Masuzu** [comment]
Thank you for reporting back about that matter!
This may be a bug as few users use the option `ProcessMainAccountTurnFirst=false` as you do.
I will check it after the guild wars too.
