### ISSUE TITLE
version 1.14.6 copy/paste quest URL bug

### ISSUE THREAD

**Issue by LordShade** [Masuzu/ZooeyBot#204]
Has issues trying to copy paste the raid ID into the URL window to start the quest again.

Version 1.14.5 works fine so I have downgraded to that

What seems to happen is zoey will right click the url and then stop entirely, if I manually move the mouse to "paste and go" zoey will pick up immediately, but get stuck again after the battle is done. Not sure if this is scaling issue but the mouse cursor upon watching it feels a bit off.  Then again, if it was a scaling issue, downgrading to a previous version wouldn't of fixed it.

**Comment by Masuzu** [comment]
Hi,
There was absolutely no change regarding this part. I am not sure why it happens 🤔 
There should be no issue as long as you do not have a maximized Chrome browser window.
