### ISSUE TITLE
Bot stopping at the GW main page

### ISSUE THREAD

**Issue by Jagger0083** [Masuzu/ZooeyBot#205]
As the title says. Not 100% if my settings are right if anyone can double check it.

[TreasureEventMode]
Enabled=True
TreasureEventUrl=http://game.granbluefantasy.jp/#event/teamraid032
Difficulty=vh
ActionPointCost=30
TreasureEventModeScript=Scripts/GW.lua

**Comment by Masuzu** [comment]
Hi,
Please do not use the trasure event mode for the GW VH mode, but the event mode instead:
https://github.com/Masuzu/ZooeyBot/issues/123 provides guideline to farm the EX+ mode. Just replace the EX+ URL with the VH raid URL and you'll be fine :+1:
