### ISSUE TITLE
Proposal to changes to the mode selection

### ISSUE THREAD

**Issue by thenastyworm** [Masuzu/ZooeyBot#208]
Hi,

I just realized that whenever I want to change the mode on Zooey, it takes quite some scrolling and editing with our ever growing ini files and multiple supported modes. 

I would therefore like to propose to change the ini to have one global setting at the start for example:

#valid values are "Slave", "Treasure", "Event" 
Mode=Treasure

This would save us from having to scroll and edit the values from true/false in each section when we want to change the mode. I think as the game (and probably the bot) continues to grow we will get more modes and it would be beneficial then too.

Another cool option would be to have the ability to override ini values with command line parameters, or have the ability to specify an external ini file as a parameter in the command line. This way users could create multiple ini files for different modes and launch them from bat files or similar for quick switching.

Example:

ZooeyBot.exe --ini=slime.ini
ZooeyBot.exe --mode=Treasure

**Comment by Masuzu** [comment]
Hi,

Indeed that would be nice.
For now I suggest you keep separate copies of the ini file and just rename them depending on which one you need.
