### ISSUE TITLE
Bot stuck at backup request screen

### ISSUE THREAD

**Issue by Otohimesahara** [Masuzu/ZooeyBot#209]
I copied a few scripts and put them together into one script to make them easier and they work fine but when I try to farm the Evil Eye for the Guild War Zooey Bot doesn't click out of backup requests? 

http://i.imgur.com/Udx6tld.png

I have tried checking the FAQ and even looking through the issues and haven't seen anyone run into this problem. Do I need to add a line of code into the script to make Zooey Bot click cancel on the backup requests?

**Comment by Jagger0083** [comment]
As stated in #42 and #66, it is assumed that you can finish the quest without backup.

**Comment by Otohimesahara** [comment]
My team is able to clear it it's just that when I enter the battle the request backup screen appears,and by the time it appears Zooey Bot is trying to click on my characters to use skills,but it is blocked by the request back up screen. So I was wondering if there was a way I could make a .lua script that makes Zooey Bot click cancel and then use character skills

**Comment by Masuzu** [comment]
Oh that!
Please go to http://game.granbluefantasy.jp/#setting and disable the automatic backup request at the start of the battle and you will be good to go :)
