### ISSUE TITLE
calibration issue

### ISSUE THREAD

**Issue by myfateisnow** [Masuzu/ZooeyBot#21]
doesn't work for scarlet trial; anyone reason why?

**Comment by Zoichan** [comment]
Same. couldnt auto Scarlet Trial. Still be able to auto Angel Halo.

**Comment by Masuzu** [comment]
Could you please be more specific? What do you mean by calibration?
Does it get stuck in the "calibration" phase?
I will check it later.

**Comment by Masuzu** [comment]
Can't reproduce on my side. The bot is working fine for the scarlet trial as well.

**Comment by myfateisnow** [comment]
![image](https://cloud.githubusercontent.com/assets/28507114/25875330/e1e114da-34e4-11e7-9872-240e190de6f7.png)
