### ISSUE TITLE
Lua scripting revive potions?

### ISSUE THREAD

**Issue by angstbian** [Masuzu/ZooeyBot#218]
I'm unsure if this is implemented, but is it possible to script a way to use revive potions/elixirs?

**Comment by Masuzu** [comment]
Hi,

It is not but the basic assumption is that your party is strong enough to solo the raid >_<

**Comment by angstbian** [comment]
I was hoping to add such a thing to my scripts as more of a fail-safe: sometimes random chance messes a party up or the boss gets really lucky with the hits and wipes the party at 5% health left. It'd be useful to have revive potions to smooth it over and not have to manually re-activate

**Comment by Masuzu** [comment]
I do not know which boss you are facing, but you could use blue potions pre-emptively using a conditions to check the remaining HP of your party members.
If it is the nightmare 90 mode of the current guild war, usually you just need to guard against the triggers and you can auto attack the boss to death the rest of the time. This is what I use to clear it consistently in 7-8 turns maximum.
