### ISSUE TITLE
Zooeybot Extension keeps Removing itself from chrome when closing chrome.

### ISSUE THREAD

**Issue by Phucie** [Masuzu/ZooeyBot#219]
Ever since yesterday I have been having issues with 'calibrating' my game with the bot. I did not change any settings though to my game or the bot for it to behave in such a way. And now my zooey bot extension in chrome keeps removing itself. So neither the calibrating work nor the extension stays and I feel it's related probably but don't know for sure.

An error in the console states" mobage-jssdk-client.3.7.7.min.js:5 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://connect.mobage.jp') does not match the recipient window's origin ('http://game.granbluefantasy.jp')."

**Comment by Masuzu** [comment]
Hi,

This error message is unrelated to the extension removing itself from the browser.
I have this too on my side >_< and it is most likely due to some Windows security settings. I just reload the extension each time, no biggie thanksfully.

**Comment by Hexadecimalism** [comment]
I also have this issue, temporary workaround, create a new chrome shortcut and rename it to whatever you like. "Zooey Chrome" works. Edit the properties of the shortcut and add this to the target

> --load-extension="C:\[your zooey-bot installation location\zooey-bot-extension"
So it looks like this

>"C:\[your chrome installation location]\chrome.exe" --load-extension="C:\[your zooey-bot installation location]\zooey-bot-extension"

This forces chrome to install/load it every time you launch with that specific shortcut. Should be a valid workaround for a while.

**Comment by Phucie** [comment]
Yeah I just reload the extension, I'll try that work around you have for that issue. In the meantime I still do not know why my calibration is not working properly since I did not change any settings for it to have gone out of order when it was working fine prior.

**Comment by Hexadecimalism** [comment]
Consider this post on calibration.

https://github.com/Masuzu/ZooeyBot/issues/217#issuecomment-323709167

**Comment by Phucie** [comment]
I seem to have been able to resolve the issue, for some reason I am forced to run both chrome and the bot as administrator in order to get it to take over my mouse....strange because I never had to do that prior, glad I only wasted 5 days of not being able to use this.

**Comment by Masuzu** [comment]
@Hexadecimalism Very creative workaround, I love it.
