### ISSUE TITLE
Unregistered user

### ISSUE THREAD

**Issue by BakaPhoenix** [Masuzu/ZooeyBot#22]
I get this error while I try to run the bot.
When i update the code to it say i already changed it in the latest 4 days.
I did a huge mess at first to make it run so i don't remember what i did that time but i already did that procedure once, but i think i triggered the pc id change is was when i wanted to find if there was a settings to reduce the main acc return to lobby timing so i downloaded the bot again on my main pc (using a mac) while the bot was running on my pc.
So now i can't use the bot for 4 days? D:
I just buffed the room and can't use the bot and magnafest ends in 5 days /o\

**Comment by Masuzu** [comment]
Hello,
Please send me a mail at gbfpokerbot@gmail.com with the serial number you would like to set and the serial number that you are currently using.
I will make the change within 10 hours.
Please note for future reference though that there is a cooldown of 4 days for each serial number update!

**Comment by BakaPhoenix** [comment]
Mail sent.
Please ignore the other mail i sent was before i got reply here.
Thanks

**Comment by BakaPhoenix** [comment]
Well i have no idea on what is happening but my uuid went back to the original one, then now that you changed my id is not working anymore...
From what i'm reading is impossible to change a machine uuid so i really have no idea of what is happening '-'

**Comment by BakaPhoenix** [comment]
I know but when i started this topic it changed to another one, now is back to the old one so i can't use bot anymore since you updated it.
Is so confusing i have no idea why it changed in the first place...
