### ISSUE TITLE
Bot autocloses

### ISSUE THREAD

**Issue by jn1127** [Masuzu/ZooeyBot#221]
After the recent ZooeyBot update, the bot consistently crashes after starting up the Extreme+ for the current GW. I've tried basic/quest mode and that seems to be fine, but the event mode for me seems broken.

Edit: Also changed scripts and used Extreme to test and still crashing.

**Comment by SchismEternel** [comment]
Same problem. As soon as the bot starts the gw raid battle, zooey will crash if I enable any script while in event mode

**Comment by crazeefella** [comment]
Same here. I have been having crashes when it tries to load the lua scripts for GW. If I remove the lua scripts from being loaded it works fine and can auto attack. But load a lua file and it dies even if the lua file only has EnableChargeAttack() in it.

**Comment by Masuzu** [comment]
Hello,

I am really sorry, there was an issue introduced with the version 1.18.0.
Please use the stable version 1.17.0 instead in the meantime, thank you.
