### ISSUE TITLE
Serial number is already taken

### ISSUE THREAD

**Issue by Jormungands** [Masuzu/ZooeyBot#222]
Hello :)
Due to the serial number being used, it can not be used despite extending the deadline by one month.
The contents of serial_number.txt are the same as SerialNumberGenerator, so there is no difference.
Is it impossible to make the serial number available again?
It's my own bad but I purchased a month's worth, so it's a waste if I can not use it.
Could you please fix it?

Thank you.

![ws000001](https://user-images.githubusercontent.com/31189131/29506393-58c5abea-8686-11e7-8e78-1be46749a6eb.JPG)
![ws000000](https://user-images.githubusercontent.com/31189131/29506400-5c05f1de-8686-11e7-9dec-726ab6958a5c.JPG)
![ws000002](https://user-images.githubusercontent.com/31189131/29506403-5e3d709e-8686-11e7-9e73-ec5f36f9b5a2.JPG)

**Comment by Masuzu** [comment]
Hi,

I can't fix it if another user who subscribed already use this serial number but this should only happen in very rare cases such as when you use the same university network/lease computers.
However, if the other user who uses the same serial number has you has no active licence, I can remove his account to make this S/N available again.

Could you please post here the email you used to register your licence so I can investigate the case?

I will make the change within 15 hours or so.

Also, there is an issue with the latest release from yesterday, I apologize for the inconvenience: https://github.com/Masuzu/ZooeyBot/issues/223

**Comment by Jormungands** [comment]
Thank you for your answer.

If another user pays for the license, is it impossible to delete the account?
Conversely, if you do not pay for the license, is it possible to delete the account?
Please refer to the following for my own e-mail.
bazaraga@yahoo.co.jp

Please.

**Comment by Masuzu** [comment]
Good news, this serial number is now available again for use.
If another user uses the same licence, which is very unlikely unless you share the same computer (university computer for instance) and still has an active subscription, I won't delete the account unless the licence is expired.
There is no option to delete an account with no active licence, unless X amount of time (not disclosed) passes before the licence expires.
