### ISSUE TITLE
Zooey bot initialization error

### ISSUE THREAD

**Issue by japanesezooey** [Masuzu/ZooeyBot#224]
I have a single window open. However, the message "Multiple Grandblue Fantasy active windows were found. Please close all of them but the one with poker table." is displayed.
I confirmed this with ver1.17.0 and ver1.15.0.
Is it only for me?

**Comment by Masuzu** [comment]
Hi,
This is not possible, unless you have other windows whose title contains Grandblue Fantasy in their name, such as the GBF wiki for instance.
