### ISSUE TITLE
Bot crashing again version 1.17.0

### ISSUE THREAD

**Issue by jn1127** [Masuzu/ZooeyBot#225]
Worked for about an hour and now it's also starting to crash. Script runs for a turn or two and then will start to crash.

**Comment by SchismEternel** [comment]
I've been using it for 2h straight and it's working just fine for me with the 1.17.0 version

**Comment by Masuzu** [comment]
I have no issue with the version 1.17.0 after letting it runs for 2-3 hours in a row several times per day. Please send a screenshot of the last messages in the console and the game window when the crash happened if you run into this issue again. Thank you in advance.

**Comment by jn1127** [comment]
I was able to get it working with a clean install. Just deleted my current version and all the changes and used the basic Zooey.ini file from the previous version.
