### ISSUE TITLE
Allow Daily Hard/Omega Magnas Farm

### ISSUE THREAD

**Issue by Bakamoto** [Masuzu/ZooeyBot#227]
Everything works amazing, from GW farming to angel farming, with no issues with Lua scripts. Thank you. But will there be support for daily magnas in the future?

**Comment by Masuzu** [comment]
Thank you for the feedback.
Maybe, but it is not a priority for now.

**Comment by Sundaerae** [comment]
no public raid is no problem :)
What I hope is doing a favorite quest #1 3 times, then #2 3 times, #3 3 times, and so on till I do all the magna, especially on magnafest

**Comment by Masuzu** [comment]
Got it! No plan for now as other features regarding debuff and buff retrieval have the priority before the next GW. But hopefully "custom farming planning" feature will be available before the next half AP event.

**Comment by Masuzu** [comment]
Now live with version 1.19.0
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#1-19-0
