### ISSUE TITLE
Crash on Xeno Sagitarius Extreme

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/ZooeyBot#228]
Zooey 1.17 always crash on 2nd turn of Xeno Sagitarius Extreme, but didn't happen on NM.
I don't use Viramate, and the reloading page on last battle is on.
EDIT: I tried turning off the reloading page. It managed to go to turn 3, then crash.
Not to mention, somehow the game become laggy if I use zooey on ex sagi (not just the xeno sagi, but even the first 2 battles)

![crash](https://user-images.githubusercontent.com/31296536/29682573-b32c7224-8935-11e7-88f0-d408800cf354.png)

**Comment by Masuzu** [comment]
I am not sure which version 1.17 you are using, but one is not stable and includes some of the crash issues from the version 1.18.0.
I will remove it and replace it with an updated version 1.18.1.

**Comment by Sundaerae** [comment]
downloaded 1.18.1 from the github (because the dropbox is exceeding limit).
still crashed
![still broken](https://user-images.githubusercontent.com/31296536/29684539-8cd316b2-893c-11e7-88ae-f5d785a46227.png)
