### ISSUE TITLE
Is it possible to add "reroll summon option" not only for nightmare mode quests?

### ISSUE THREAD

**Issue by prokopets** [Masuzu/ZooeyBot#23]
Hello!

I wonder if you can add refreshing summons thing not only for nightmare quests. or mby there is a possibility to do so already, and i am just being dumb x) 
Tried this:
1. Enable event mode
2. Set diablo extreme url as nightmare quest
3. Enabled refresh option
4. Set summon for nightmare as Lucifer
5. Enabled Trial battle mode
No use x) Bot still selects first summon in light tab if no Lucifer to be found.

**Comment by Masuzu** [comment]
Hello,

There is no summon rerolling for "not nightmare" stages, for now.

**Comment by prokopets** [comment]
would really like to see this feature later) Thank you! And regarding low res monitors(my issue about OK button being covered by bottom menu) can you suggest doing something? Mby it will be possible to add little scrolling on that menu, so zooey wont get stuck there

**Comment by Masuzu** [comment]
Yes, sure thing, I can add some scrolling. Towards the end of the week probably.

**Comment by Masuzu** [comment]
This should be done in version 1.4.1 which has just been released:
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes
