### ISSUE TITLE
enemy break status

### ISSUE THREAD

**Issue by reinharto** [Masuzu/ZooeyBot#231]
Can't seem to ever get salted wound going at the beginning of the turn even when it is already in break. Here my setup for xeno sagi nm.
if enemy_1.break_state == true then
  character_2:UseSkill(2)
end

Even when I put refresh() it still doesn't detect it. Anyone having this issue?

**Comment by Shamool** [comment]
Maybe it's my own incompetence with scripts as well, but I don't seem to be able to do either break or overdrive even when I put Refresh().

I tried this recently in Xeno Sagi NM, but it doesn't trigger. I also tried it with reload on last battle as well. Would appreciate it much if someone point out either what I'm doing wrong or if there is a bug.

if turn>4 and enemy_1.break_state==false and enemy_1.overdrive_state==false and enemy_1.charge_diamonds==3 then
 character_4:UseSkill(1)
 end

**Comment by rockysilver** [comment]
I have the same problem with overdrive state, zooey just won't recognize overdrive state no matter what I tried. 

I tried enemy_1.overdrive_state==true and enemy_1.overdrive_state==1, neither works for me.

**Comment by Masuzu** [comment]
Hi, I will look into it

**Comment by Masuzu** [comment]
https://github.com/Masuzu/ZooeyBot/issues/324
