### ISSUE TITLE
option for zoey to ignore summon selection in "misc" category

### ISSUE THREAD

**Issue by LordShade** [Masuzu/ZooeyBot#233]
I am getting a consistent bug that seems to only happen during summon selection in the misc category, specifically because zoey scrolls too far down and misses the selection she was going to pick and bugs out

She ends up endlessly refreshing and does not change her mind (even with multiple preferred summons put down)

https://puu.sh/xjRR1/92ecf4a094.png

it is a quick and dirty fix, but it'll fix this bug I seem to encounter very often.

**Comment by Masuzu** [comment]
Hi, reducing the scrolling speed parameter should be enough to fix this issue.
