### ISSUE TITLE
Bot does not stop automatically and attempts to refresh past captcha

### ISSUE THREAD

**Issue by zcdragon** [Masuzu/ZooeyBot#238]
I was using the bot version 1.18.3 under Event mode to farm the Side Story missions. 

I specified the TimeLimitInSeconds=7200 but came back after 3 hours to see the bot stuck at the summon select page, trying to refresh past the captcha. No alarms and no signs of captcha detected in the console. (Was able to fill it in manually but I have no idea how long the bot was stuck at the captcha screen as I got hit by a suspension either way.)

Unsure if this is specific to the Side Story missions but seems to be something worth looking into.

**Comment by Masuzu** [comment]
Got it, I will look into this matter with the utmost attention and provide a quick fix.

**Comment by Masuzu** [comment]
Addressed with version 1.8.5
