### ISSUE TITLE
Using ZooeyBot with Korwa's buffs

### ISSUE THREAD

**Issue by SchismEternel** [Masuzu/ZooeyBot#240]
Hi ! Thanks again for the hard work. Everything is in the title: I am a complete beginner with lua scripts and even after reading the guide's section about active effects, I just can't figure out how to write a functionning script for this character. Basically I would like to always disable charge attacks until Korwa reaches 7 or more Fils then enable them  again for her ougi.

Also, how could I configure Zooey so that it auto casts Korwas first skill after her second skill whenever the buffs are about to end ?

If anyone else has managed to write a working script with Korwa, I'd be very interested to see an example.

**Comment by Masuzu** [comment]
Hi,

This is in the pipeline. Maybe by the end of the week you should be able to do so much more easily than it is now (to do so you would have to have a loop over Korwa's buffs and check whether the IDs of these buffs match the in-game IDs for the buff effects "Fil 7", "Fil 8", "Fil 9" or "Fil 10". Not very practical indeed!)

https://twitter.com/GBFPokerBot/status/902218984799559680

**Comment by SchismEternel** [comment]
Wait and see then^^ looking forward to it !

**Comment by Masuzu** [comment]
Now live with version 1.19.0.
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#1-19-0
