### ISSUE TITLE
Event doesn't run

### ISSUE THREAD

**Issue by jn1127** [Masuzu/ZooeyBot#242]
Event mode not running properly for ZooeyBot. Using http://game.granbluefantasy.jp/#event/treasureraid059 for event page, and http://game.granbluefantasy.jp/#quest/supporter/721091/1/0/10233 for the event raid but nothing happens. Zooey just gets stuck at Initializing.

Must be noted that it works for hard version of the raid at http://game.granbluefantasy.jp/#quest/supporter/721081/3.

**Comment by Masuzu** [comment]
Hello, you can't use the EventMode for events requiring you to have materials to host it.
Please use the treasure event mode to do so:
https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode

I will upload a working ZooeyBot.ini file a bit later in case you would still have issues with it.

**Comment by Masuzu** [comment]
As an example configuraiton, here you go:
https://github.com/Masuzu/ZooeyBot/issues/247
