### ISSUE TITLE
Creating coop rooms?

### ISSUE THREAD

**Issue by NotInjured** [Masuzu/ZooeyBot#243]
Would it be possible to have the bot create coop rooms after the sliming session is done?

**Comment by Masuzu** [comment]
Hi,

Maybe, but I won't work on this feature for now unless another half AP event is scheduled.

**Comment by nami1235** [comment]
1addition about coop rooms.
Can i host coop play (etc slime) for my friends?
i cant understand how it works. should i choose  TreasureEventMode?

**Comment by crsparky** [comment]
They've just announced the 17 million players celebration which includes 1/2 AP and bonus RP/EP. Any chance of adding an auto room creation (as well as applying room buffs) feature? :)

**Comment by Masuzu** [comment]
Hi,

I am afraid I won't do it, not for now at least, I do not see much gain from it actually.
Usually you just set up your room, leave Zooey running for one hour then rinse and repeat.

**Comment by Masuzu** [comment]
@nami1235 You can't do this.
The slime blasting mode is designed to be used with an alt account:
Please refer to https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting) for more details and should you use this mode, make sure to follow exactly in the same order the steps described in this page.

https://www.youtube.com/watch?v=PNAfeDmIEkI

**Comment by NotInjured** [comment]
No worries. I only suggested it cuz sometimes I run the coop bot for sliming when i'm away for a few hours or overnight
