### ISSUE TITLE
Does not NightmareMode in the TreasureEventmode section work?

### ISSUE THREAD

**Issue by mawile0816** [Masuzu/ZooeyBot#246]
In my case the NightmareMode doesnt work in this Scenario Event...

I can see the text "Nightmare mode appeared" in the Zooey.

Zooey doesnt start Nightmare quest and Continue Ex.

This is my ini file.
[ZooeyBotini.zip](https://github.com/Masuzu/ZooeyBot/files/1268973/ZooeyBotini.zip)

**Comment by Masuzu** [comment]
Hi,

It works fine for me and without any issue with the exact same configuration that you provided (I just changed the scripts).
Could it be a case where Zooey tried to reroll your summons because no preferred summon was found?

**Comment by worthworth** [comment]
so issue here.

TreasureEventMode setting is
[[TreasureEventMode].txt](https://github.com/Masuzu/ZooeyBot/files/1271628/TreasureEventMode.txt)

**Comment by worthworth** [comment]
add NightmareURL, NightmareScript, EventURL to [EventMode]
I dont know why but it works well.
[Event-TreasureEventMode.txt](https://github.com/Masuzu/ZooeyBot/files/1271997/Event-TreasureEventMode.txt)

**Comment by worthworth** [comment]
add NightmareURL, NightmareScript, EventURL to [EventMode]
I dont know why but it works well.
[Event-TreasureEventMode.txt](https://github.com/Masuzu/ZooeyBot/files/1271999/Event-TreasureEventMode.txt)

**Comment by Masuzu** [comment]
Do not set `NightmareModeAvailableAtStart` to true if the hell mode has not yet spawned when you start Zooey. It won't work obviously, as expected.
