### ISSUE TITLE
Is it possible for bot to play story mode?

### ISSUE THREAD

**Issue by devvah** [Masuzu/ZooeyBot#249]
So I've got new acc and I'd like to have unlocked all major bosses but skipfest tiredom is real, is it possible for bot to finish it? Because beside repating single story episode I didn't found such option.

**Comment by Masuzu** [comment]
Hi,
You need to add the story quest to automate to your favorite quests.
Please refer to https://github.com/Masuzu/ZooeyBot/wiki/Basic-mode---story-quests,-free-quests-and-special-quests-automated-farming

**Comment by devvah** [comment]
But you can't add story quests to favorites before you clear then and this page doesn't contain anything about previously uncleared story quests, on top of that Story quests and Angel Halo movie is private and no one can watch it.
