### ISSUE TITLE
Coop mode issue with refreshing taking too long

### ISSUE THREAD

**Issue by nobody0014** [Masuzu/ZooeyBot#250]
So what happen is that my Zooey bot will finish the slime and refresh the page, but sometimes the internet is bad and so the bot has to refresh again. When this refresh occurs, the bot program automatically shut down. (This is because it was expecting the co op room to appear instead of the raid result after the second refresh.) 
I'm currently running on 1.14.3 so this issue might have been solved in 1.18 but i could not find the issue reported yet nor could i find the mention of this in the patch note. If you have solved it please tell me.

**Comment by Masuzu** [comment]
Hi, please refer to https://github.com/Masuzu/ZooeyBot/issues/236
