### ISSUE TITLE
Unable to use Event mode to farm NM

### ISSUE THREAD

**Issue by ErogeSeiyuu** [Masuzu/ZooeyBot#253]
I tried using EventMode=true to farm both VH difficulty and NM procs, but Zooeybot is stuck at "Vertical offset=108... Zooeybot Initialized" and didn't proceed further.
It didn't load with or without EventPageUrl, with or without NightmareModeAvailableAtStart.

It works fine right away when I switch back to TreasureEventMode=true.

**Comment by Masuzu** [comment]
Hi,
You can't use the Event Mode to farm the VH as it requires materials to host it.
That's why you _have to use_ the TreasureEventMode.
https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode
