### ISSUE TITLE
LuaScript

### ISSUE THREAD

**Issue by Djeeta-kun** [Masuzu/ZooeyBot#255]
how do I add script? On the Zooeybot config setting itself?

**Comment by Masuzu** [comment]
Hi

You create a separate script named as you wish and edit the ini file setting the relative path to this script.
For instance if you create a script named "test.lua" in the folder Scripts, to use it you will set `LuaScript=Scripts/test.lua`

Please note that depending on the mode you use, there is a separate parameter `LuaScript` scoped for each of them.
