### ISSUE TITLE
Issue with scheduling script

### ISSUE THREAD

**Issue by ryokage** [Masuzu/ZooeyBot#256]
Hi I tried to use the new scheduling part of zooey bot and running into some problems. The selection of the hard/norm mags are correct and activates but it doesn't activate my combat script. I even checked the commands in zooeybot when it starts attacking. the combat script i've been using is fine since I'm using the same one for coop so i think its a bug or something im missing. Please help thanks!

[Combat]
# Zooey-bot will wait at least the given number of milliseconds after pressing the attack button
MinWaitTimeInMsAfterAttack=500
# Zooey-bot will wait at least the given number of milliseconds after using a summon
MinWaitTimeInMsAfterSummon=3000
# Zooey-bot will wait at least the given number of milliseconds after using a skill
MinWaitTimeInMsAfterAbility=2200
# Relative path to the script to use to customize the pace of combats. Embrace a world of infinite possibilities!
# Leave this parameter blank if you do not want to use any script. In this case Zooey will just attack at each turn. You can test your scripts using the TrialBattleMode (see the Debug section).
# Please refer to https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts for a comprehensive overview of the scripting features.
LuaScript=Scripts/yoda.lua
# If set to true, Zooey will refresh the page after each attack on the last stage of a quest.
# This saves up some precious seconds and that is what every MVP racer does.
ReloadPageOnLastBattle=true
# If set to true, Zooey won't wait for a response from GBF servers after using a skill or summon or after attacking. Use this parameter if you know what you are doing, or else this may result in Zooey going out of control in case you use several skills each turn. The main use of this parameter is to make skill usage slightly more responsive during slime blasting.
DoNotWaitForServerResponse=false
# Maximum wait time in milliseconds to load the character selection menu when an ability targetting a party member is used.
MaxWaitTimeToLoadCharacterSelectionMenuInMs=1100
# Retrieving party members status effects at each turn may degrade the performance depending on your ping.
RetrieveStatusEffects=false

[CustomizedScheduling]
Enabled=true
SchedulingLuaScript=scheduling.lua

--------------------------
my yoda script
if turn == 3 then
  character_2:UseSkill(1)
  character_2:UseSkill(3)
end
------
scheduling for magfest
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300091/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300041/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300151/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300191/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300251/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300211/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300181/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300141/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300081/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300221/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300031/1", 0, 3)

**Comment by ryokage** [comment]
just wondering why it doesn't load the combat part when it starts the script even though i have it on and it works for other things just not when scheduling is on

**Comment by mdanishu** [comment]
I'm having the exact same issue.

**Comment by benz07942** [comment]
same here

**Comment by fumika779** [comment]
same issue

it doesn't load lua script

**Comment by ryokage** [comment]
^ what do you mean

**Comment by MonaSaySleep** [comment]
same issue, combat lua doesn't load when scheduling is on

**Comment by Masuzu** [comment]
Hi,

This is a bug indeed: scripts are ignored with the customized raid scheduling mode. I will fix it within 24 hours.
Sorry for the inconvenience.
