### ISSUE TITLE
Please show Lua scripts Korwa buff combo 

### ISSUE THREAD

**Issue by anubiscross** [Masuzu/ZooeyBot#258]
I try korwa buff combo but it not work 
Maybe I will miss something

It does not check buff.id and skip line

buff combo korwa Fill 10 > skill 2 > Fill 10 > skill 1 > Fill 8 > Ougi

**Comment by Masuzu** [comment]
Hi,

Please refer to https://github.com/Masuzu/ZooeyBot/wiki/Lua-Scripts-(character-specific)

You can now just do for instance:
```
DisableChargeAttack()
if num_kowa_fils >= 9 then
  if characters["Korwa"].skill_1_available then
    characters["Korwa"]:UseSkill(1)
  else --[[ The skill was cast the previous turn, Ougi to enhance the buff effect ]]
    EnableChargeAttack()
  end
end
```

**Comment by cobeng13** [comment]
I'm pretty stumped too on how to use this function
I made it:

if buff.id == 153310 then
character_2:UseSkill(2)
end

if buff.id ==153310 and 1534 then
character_2:UseSkill(1)
end

if buff.id = 153310 and 1534 and 1535 then
EnableChargeAttack()
else
DisableChargeAttack()
end

what I wanted it to do was to wait for 10 fils, cast the red skill, wait for 10 fills, cast the white skill,  wait for 10 skills with both buffs active then enable charge attack

I think I just haven't got a hang of how to script this one.

**Comment by Masuzu** [comment]
Hi,
This script won't work. buff is not a script-global variable but buffs are bound to characters. I plan to add some helpers to make it easier to check whether a buff/debuff is active or not for a given character.
If you want to check the number of Fils, please use `num_korwa_fils` as shown in the example above.

I will provide some examples when the GW is closing.

**Comment by Masuzu** [comment]
If you still need to iterate over the buffs of character_2 for instance, then you can do something like this, for now:
```
--[[Helper method]]
function Iterator(t)
local i = 0
local n = table.getn(t)
return function ()
    i = i + 1
    if i <= n then return t[i] end
  end
end

buff_XXX_is_active = false
for buff in Iterator(character_2.buffs)
  if buff.id == XXX then
    buff_XXX_is_active= true
  fi
end

if buff_XXX_is_active then
  EnableChargeAttack()
end
```
