### ISSUE TITLE
Mouse always try to click bottom left corner

### ISSUE THREAD

**Issue by aysien** [Masuzu/ZooeyBot#259]
When I click quest after activate the bot, its always running to bottom left corner and clicking widget and ended up opening new tab to widget website of cygames. Its make the bot stop or not run properly. 

Well sometimes i hikd the most so it wont run to bottom left corner and after that the boy works fine. But sometimes it run to bottom left corner again randomly. Do tou know how to fix this?

**Comment by Masuzu** [comment]
Hi,

It is not a bug, it is required or else the game will be very slow after some time.
Make sure to have your DevTools window look like this:
![](https://i.imgur.com/7SlacPp.png)
and above all, please update the parameter _ChromeDevToolsWindowDockedOnTheRight_ accordingly in the ZooeyBot.ini file.
