### ISSUE TITLE
trials not working

### ISSUE THREAD

**Issue by myfateisnow** [Masuzu/ZooeyBot#26]
Trials just don't work; now i'm trying the cerulean trial and i can't do anything; this is with the bot in basic mode.
![trials](https://cloud.githubusercontent.com/assets/28507114/25875443/74d546d0-34e5-11e7-8cea-1e16fd8b5c02.png)

I've seen from another reply that trials worked fine for you; what could I be doing wrong?

**Comment by Masuzu** [comment]
Hello,

I can confirm that it's a bug. On it.

**Comment by Masuzu** [comment]
Tested and fixed in version 1.2.0: https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes
Sorry for the inconvenience.
