### ISSUE TITLE
Issue with scheduling script ver 1.19.2

### ISSUE THREAD

**Issue by fumika779** [Masuzu/ZooeyBot#260]
![2017-09-10_112109](https://user-images.githubusercontent.com/31799116/30246096-323de610-961a-11e7-8d26-6fa030e01581.jpg)

custom lua scripts in scheduling is not working.
bot is stuck.

**Comment by zcdragon** [comment]
I am encountering the same issue with the bot stuck at the same line.

I am using a script for automating magna raids, as seen here: 
```SetLuaScript("Scripts/magna_auto.lua")
--[[ autoattack script for tiamat, colo, and levi ]]
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300051/1/0/18", 15, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300101/1/0/19", 15, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300161/1/0/20", 15, 3)

--[[ autoattack script for yggdrasil ]]
SetLuaScript("Scripts/magna_ygg.lua")
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300261/1/0/21", 15, 3)```

**Comment by Sundaerae** [comment]
Had the same problem as fumika
And also, if magnafest, should we use 0 as parameter or 10/15?

**Comment by fumika779** [comment]
@Sundaerae Use 0 (if you mean norm/hard Omega)

**Comment by ryokage** [comment]
yup still there

**Comment by Masuzu** [comment]
Moving to https://github.com/Masuzu/ZooeyBot/issues/265
