### ISSUE TITLE
Bot keeps clicking area between bookmarks bar and URL bar.

### ISSUE THREAD

**Issue by sinanjugbf** [Masuzu/ZooeyBot#262]
When I start the bot, it'll click either my GBF bookmark or the space between the bookmarks bar and URL bar. How do I get it to stop doing this? I'm using 2560x1440 resolution with the window size guidelines if that helps.

**Comment by Hexadecimalism** [comment]
Try manually resizing your window so the top is just a little bit smaller than the resolution height of your screen.

**Comment by sinanjugbf** [comment]
So I need to make chrome windowed instead of maximized?

**Comment by Hexadecimalism** [comment]
You shouldn't have to, but if you're having problems, give it a shot. It worked on my laptop for some time that way before I started running into calibration issues. Be sure to reply here if it works.

**Comment by sinanjugbf** [comment]
Yeah it works this way. I guess it's because it was calibrated this way when I was sliming?

**Comment by Hexadecimalism** [comment]
Glad to hear it works. Pretty sure it re-calibrates at every launch, though I could be wrong.

**Comment by Masuzu** [comment]
Please never use a maximized window. Thank ou @Hexadecimalism
