### ISSUE TITLE
Calibration issues redux.

### ISSUE THREAD

**Issue by Hexadecimalism** [Masuzu/ZooeyBot#263]
The calibration issues are back and I've been trying to troubleshoot it for the last two weeks to no avail. I've tried my older settings, and I've tried the ones listed in the guide and I'm still running into the issue.
I've tried running it on my desktop at 1920x1080p and my laptop at 1366x768 and the results are the same.

As an aside, can moving your licences across machines be made easier? Having to wait a few days before I can switch my serial number from PC to Laptop and back again to troubleshoot really slows things down.

**Comment by Masuzu** [comment]
Hi,

Could it be an issue related to https://github.com/Masuzu/ZooeyBot/wiki/FAQ#i-have-scaling-issues-again

I will do something about last point too later in the day, for the duration of the magna fest at least.

**Comment by Hexadecimalism** [comment]
I've tried at various screen resolutions and chrome window sizes to no avail. I'll get back to troubleshooting in about 2 hours or so. If I cannot get it to work still can I ask that my machine transfer be reset so I can go back to troubleshooting on the desktop.

**Comment by Hexadecimalism** [comment]
Windows scaling is at 100% and browser zoom  is at 100%

Window size Medium (2 diamonds). Automatic resizing off. Bottom menu on.

![image](https://user-images.githubusercontent.com/14233254/30269936-ae68c016-96e2-11e7-9ac5-81dfddac2a4f.png)
My quest banner hits about 452 but you can measure it yourself as I've included it below (hopefully github does not resize).

![image](https://user-images.githubusercontent.com/14233254/30270013-f4bc096a-96e2-11e7-84bc-2baaf7137812.png)

Attempting to get the width of the quest banner gives me this error.

![image](https://user-images.githubusercontent.com/14233254/30269796-1e03c0ac-96e2-11e7-9c5d-d816b2a3c068.png)

I've exhausted all options on my laptop. Still odd that it would suddenly stop working when it was working before. Same with the desktop, but I'll run my tests again the second I can transfer.

**Comment by Masuzu** [comment]
Thank you for the feedback.
About the JS command to input, it should be $(".prt-quest-banner.difficulty-2")[0].clientWidth
and it should return a value close to 305.

With a banner size in pixels of 457 on my side (which is pretty much the same setup as yours), it is working fine on my side.

If you still run into the same issue, I will provide a custom version with more information within 12 hours.

**Comment by Hexadecimalism** [comment]
> $(".prt-quest-banner.difficulty-2")[0].clientWidth

Thanks a lot, just tried that and it did return 305. If we manage to get it working properly over the next 4 days and 9 hours (that's all the time I have left), I'll definitely be picking it up for at least another month.

**Comment by Masuzu** [comment]
Would you at least happen to have an image named `CalibrationDebugImage.png` in the same folder as the executable file?
If you do, then it means that at least the calibration could find the "Home" button.

**Comment by Hexadecimalism** [comment]
I definitely have it. It's an 11kb png file.

**Comment by Masuzu** [comment]
Oh alright, I will provide you with a custom binary with more debug info and options to disable parts of the calibration process in a few hours.

**Comment by Hexadecimalism** [comment]
Thanks a lot.

**Comment by Masuzu** [comment]
The new version 1.19.3 adds some debugging messages during the calibration phase.
Unfortunately I could not see anything which could go wrong (I was mainly worried about the failure to hook to the "Home" button but it does not seem to be the case) so I would suspect that it is the Antivirus blocking some features.

I think I got the same issue once in the past and all I did was closing Chrome and restarting it.

**Comment by Hexadecimalism** [comment]
Good to hear, I'll test it out on the laptop right now. I'll also give a a go on the desktop in about 3-4 hours when I get home.

**Comment by Hexadecimalism** [comment]
No change. I'll report back on desktop in a few hours.

**Comment by Hexadecimalism** [comment]
I can verify that it works on my desktop again right out of the box. I have no idea why it suddenly stopped and continues to fail on the laptop. After Magnafest and the next GW, I'll go back to troubleshooting it. If you want to mark this as solved do so. If you do not, I'll continue to post in next month when I go back to troubleshooting on the laptop.

**Comment by Masuzu** [comment]
Thank you for the feedback, would you happen to have error messages looping in the console on the laptop if you remember?
It should display something along the lines of:
Successfully hooked to the Home button
Then a bunch of error messages

**Comment by Hexadecimalism** [comment]
On the laptop, it didn't even get to the point of hooking the home button. It just stayed at calibrating.

**Comment by Masuzu** [comment]
Oh I see. Either it's a scaling issue or image retrieval issue.
I will report back later but I am glad that you managed to get it working.

**Comment by Gferudo** [comment]
I got the same issue as Hexadecimalism and tried to scale it to no avail,I saw sometimes that my zooeybot hooked to home button but it just starts to click on a specific place of my screen until I close the bot
![image](https://user-images.githubusercontent.com/32129014/30696203-252d310a-9edb-11e7-9748-383115295539.png)

**Comment by Hexadecimalism** [comment]
@Gferudo You're running it in chrome mobile mode. You should be running it in the regular browser.

**Comment by Gferudo** [comment]
God,I feel so stupid now... Thanks for telling me,it works wonders now

**Comment by Masuzu** [comment]
Oh, nicely spotted, thank you for the input @Hexadecimalism

**Comment by Hexadecimalism** [comment]
@Masuzu Not a problem. Might I suggest setting up a (free) discord server, so people can get help from other users on issues that are not bug related? That would probably slow down the amount of non-issues (not bugs) people post.

**Comment by Masuzu** [comment]
Thank you for the suggestion. That would be helpful indeed but some people may be worried about revealing their discord name unless they create a "discardable" account.
