### ISSUE TITLE
whats the code for flb summons?

### ISSUE THREAD

**Issue by ryokage** [Masuzu/ZooeyBot#264]
I know the code for mlb is _1 but whats the code for flb summons like baha flb or luci flb? thanks!

**Comment by Hexadecimalism** [comment]
Details here.
https://github.com/Masuzu/ZooeyBot/wiki/Summon-selection

`Bahamut`
Picks any Bahamut
`Bahamut_0`
Picks any Bahamut
`Bahamut_1`
Picks mlb Bahamut
`Bahamut_2`
Picks flb Bahamut

**Comment by Masuzu** [comment]
Thank you @Hexadecimalism !
