### ISSUE TITLE
Scheduling combat bug still there

### ISSUE THREAD

**Issue by ryokage** [Masuzu/ZooeyBot#265]
The combat scheduling bug is still there. It wont read my combat script :[

**Comment by ryokage** [comment]
i even tried the new thing
SetLuaScript("Scripts/yoda.lua")
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300091/1", 0, 2)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300041/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300151/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300191/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300251/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300211/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300181/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300141/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300081/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300221/1", 0, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300031/1", 0, 3)

**Comment by ryokage** [comment]
It'll say loading summons but nothing happens

**Comment by Masuzu** [comment]
Could you please provide a screenshot of where it gets stuck?

**Comment by fumika779** [comment]
i think He stuck at the same line as me

**Comment by ryokage** [comment]
https://imgur.com/a/X6Cfs this part @Masuzu . I think everyone is stuck here based on the other thread

**Comment by ryokage** [comment]
after the quest part usually itll take over but if you try to add the script line as said in the new lua scripting combat syntax it stops and wont load the script anymore. I even tried not putting anything else aside from the base scheduling and in the combat section of the zooeybot.ini and wont load the script.

**Comment by ryokage** [comment]
Is there also a way to set specific summons to look for loading each script?

**Comment by sellsell** [comment]
just chiming in to say that i'm experiencing the same issue

**Comment by Masuzu** [comment]
Got it, thank you for reporting this bug. I did not expect this mode to be this popular.
I found the issue and hopefully it should be fixed with the newly released version 1.19.3.

@ryokage Not yet, a bit later during the Magna fest probably.

**Comment by ryokage** [comment]
@Masuzu awesome. you're doing a great job and yeah this feature would really help alot with time!

**Comment by ryokage** [comment]
the script is working now thanks @Masuzu but is there a way to set preferences for summons for each script?
