### ISSUE TITLE
Resolution problems

### ISSUE THREAD

**Issue by 13olt3** [Masuzu/ZooeyBot#267]
![screenshot_1](https://user-images.githubusercontent.com/31859433/30285600-f5e78592-9761-11e7-88bc-12119f7ffe0a.jpg)
What resolution do I have to set my game to to get the command to work?
I'm pretty sure I have the game settings correct, but whenever I change to console mode, the game resizes.

**Comment by Masuzu** [comment]
Hi,

You are using the Mobile phone Chrome emulator ;) Please don't.
![](https://i.imgur.com/sMiT9rH.png)
