### ISSUE TITLE
Slave mode scaling issues (resolution?)

### ISSUE THREAD

**Issue by SchismEternel** [Masuzu/ZooeyBot#268]
Hi there. Well, my problem this time is that I think that my gbf windows are too big for my screen. In your video demonstration of the slave mode, we can easily see your whole screen and your dev tool as well in both game windows. While I have no calibrating problem when I just use Zooey to farm one quest or event, once I try using slave mode, I don't have enough space on my computer screen  (max resolution is 1366 * 768) and as a result my slave account keeps refreshing at the beginning of the battle. If I try reducing the size of one or both gbf windows, zooey won't be able to calibrate. What can I do ? I'd REALLY like to take advantage of the 1.5 XP to lvl up those pesky lvl 90 characters !

**Comment by Masuzu** [comment]
Hi,

You should already be able to have overlapping Chrome windows for the Slave/Main account out of the box and Zooey will automatically set the proper window on the foreground when it is needed.

**Comment by SchismEternel** [comment]
So i've made a bit of progress since last time. Now Zooey consistently completes the first fight. After that however, both gbf windows get stuck to coop lobby for a while and zooey seems to be confused about what to do. Then it will go to the main account window (and not the slave one) and keep on refreshing. Any idea why ?

**Comment by Masuzu** [comment]
After returning to the co-op lobby, which window is on top (active/has the focus) when you were stuck?
Was the quest set properly? If it is, then the main account window should have the quest set at least.
Probably it is an issue with the expected window not having the focus.
Would you still have a screenshot with the situation with the last messages in the console window please?

The least I can say for now is that this console error message is unrelated.
