### ISSUE TITLE
Is there a way to select summons for specific scripts?

### ISSUE THREAD

**Issue by ryokage** [Masuzu/ZooeyBot#269]
Is there a way to select summons for specific scripts or is it set to only one which is specified in the combat line? Like if I wanted to use scheduling script to run ancient cloth with wind team with antat then celeste quest with kaguya

**Comment by Masuzu** [comment]
No, no yet.

**Comment by ryokage** [comment]
thanks

**Comment by Masuzu** [comment]
Feature added in v1.20.0
