### ISSUE TITLE
Repeating press reload after select a summon

### ISSUE THREAD

**Issue by osidavi** [Masuzu/ZooeyBot#27]
Zoeey keep pressing reload after select a summon in angel hallo, she can not scroll down to select OK button after select a sumon support in sumon list tab.

**Comment by Masuzu** [comment]
Hello,

There is no scrolling down on the party selection page. Thanksfully it is very easy to fix. You should make sure that your game window is high enough to look like this:
![](https://i.imgur.com/lYGOiLi.png)
That is a good point indeed and I will add it to the guidelines later on to avoid such issues in the future.

**Comment by osidavi** [comment]
the problem is, my max monitor's resolution is 1366 x 768

**Comment by osidavi** [comment]
FIX: change my monitor to 1280x960 and work

**Comment by prokopets** [comment]
how did you set your screen res to 1280x960? Or did you just changed monitor?

**Comment by osidavi** [comment]
My monitor support that resolution. Just try change your wide resolution more than 768.
