### ISSUE TITLE
UseSkill(x):OnPartyMember(x) can't be used on backline characters.

### ISSUE THREAD

**Issue by devvah** [Masuzu/ZooeyBot#270]
I was testing my event NM script but I've misjudged Phalanx requirement by one turn and Amatsumaula killed one of my frontline characters bringing up 1st backup character which later got down to red hp, since my script consist of DLF using her 2nd skill to heal characters_1-4 when below 30% hp script triggered, but when bot was picking character to click on from popup error came that action can't be completed, script then closed healing popup and carried out next action leaving skill unused. 

Script had no problem healing frontline characters.

**Comment by Hexadecimalism** [comment]
Yeah if you tell the script to use the skill of a character that is no longer available, the process ends. I recommend following the guidelines I laid out here. 

https://github.com/Masuzu/ZooeyBot/issues/261#issuecomment-328359894

**Comment by Masuzu** [comment]
If you reference your characters by name (for instance `characters["Korwa"]`), please make sure to check whether the party member is on the front line beforehand or else the script will raise an exception.
For instance, to check whether `Korwa` is still on the front line:
```
if  characters["Korwa"] ~= nil then
  --[[OK]]
  characters["Korwa"]:UseSkill...
end
```
