### ISSUE TITLE
question

### ISSUE THREAD

**Issue by okamijackie** [Masuzu/ZooeyBot#271]
when you write up a script how do you connect each line together?

**Comment by Hexadecimalism** [comment]
You're going to have to be specific, I'm not sure anyone understands what you need. Beginner scripting help (unless you're running into bugs) doesn't really classify as a "relevant" issue. I recommend taking a look at script examples that have been posted and modifying them to suit your needs.

**Comment by Masuzu** [comment]
I'm afraid I will close this as it seems it won't lead to anywhere.
