### ISSUE TITLE
ZooeyBot repeating quest before Result Screen is loaded

### ISSUE THREAD

**Issue by sellsell** [Masuzu/ZooeyBot#272]
I assume this issue only affects people like me who are nowhere near the GBF servers physically (EU in my case).
Basically ZooeyBot will occasionally just repeat the quest or move onto the next one before the result screen has finished loading, causing the bot to get stuck. This is what the bot log looks like when it happens:
![log](https://user-images.githubusercontent.com/29638866/30439580-79dda5d4-9974-11e7-87ab-6b4d7e364272.jpg)

From this point the only way to get the bot to continue is to manually backspace or input the summon selection link again.

Edit: The bot will also sometimes not dismiss the quest stage popup at the start, presumably because it takes too long to appear if the loading times happen to be bad.

**Comment by Masuzu** [comment]
Hi,

Ah I see. It is related to lag indeed. From Europe it works fine usually, unless some accidental lag spikes.
I will do something about it to solve this issue, such as reloading the summon page.

**Comment by Masuzu** [comment]
Mitigation provided in v1.20.0
