### ISSUE TITLE
R-only Free Quest 

### ISSUE THREAD

**Issue by sinanjugbf** [Masuzu/ZooeyBot#273]
So Zooeybot seems to stop working whenever I do Scattered Cargo and Whiff of Danger. Is this a bug or do I have to do something specific? I already have it choosing my R party.

**Comment by Masuzu** [comment]
I run it fine on my side after setting the proper party and adding the quest to the favorite quests.
Would you have a more specific error message before the crash/screenshot of the last messages in the console when the crash happens?

**Comment by sinanjugbf** [comment]
I actually figured out why. It's because of Viramate's experimental feature of auto-hiding pop-ups. It dismisses the quest pop-up before zooey bot can.

**Comment by Masuzu** [comment]
Oh I see. I am glad that you found it on your own!
