### ISSUE TITLE
how to fold in a lua script 

### ISSUE THREAD

**Issue by okamijackie** [Masuzu/ZooeyBot#274]
how do i add the symbol that will let me fold or collapse a line of code

**Comment by Hexadecimalism** [comment]
This seems directly related to the question you asked here. 

https://github.com/Masuzu/ZooeyBot/issues/271

If that is the case refrain from making multiple threads on the same subject.
I could be wrong, but I suspect what you're asking is editor based. I suggest you download something like notepad++ and switch the language to lua.
