### ISSUE TITLE
Bot crashing on script execution

### ISSUE THREAD

**Issue by silverraine** [Masuzu/ZooeyBot#275]
I've been using two scripts for the current event, for EX and NM60. I don't have any problems with running my script on EX using a much simpler script but for the NM60 one after running just the first turn the bot hangs for a few seconds then just crashes. Been looking for any indication / log file also to indicate where I made a mistake on my script but to no avail. Any chance you can advise on this? I'm attaching the two scripts I'm using here if it'll help.

EX script
```
--[Disable charge attacks on battle before boss]
DisableChargeAttack()
--[Use Razia's Substitute to ensure Halle builds up stacks]
if battle == 1 and turn == 1 then
	characters["Razia"]:UseSkill(1)
end
if battle == 3 then
	--[MC use Miserable Mist, TH3]
	
		character_1:UseSkill(2)
		character_1:UseSkill(4):WithWaitTime(3000)
	
	--[Sieg use buff, Uwe]
	if character_2.name == "Siegfried" then
		character_2:UseSkill(2)
		character_2:UseSkill(1):WithWaitTime(3000)
	end
	--[Halle buff, MC reapply TH3 and Stall to force OD, full ougi]
	if turn == 3 then
		EnableChargeAttack()
		character_3:UseSkill(2)
		character_3:UseSkill(3)
		character_1:UseSkill(1)
	end
end
```

NM60 script
```
if turn == 1 then
  DisableChargeAttack()
  character_1:UseSkill(2)
  character_1:UseSkill(4)
  --[[Razia's defense buff--]]
  character_4:UseSkill(1)
end

--[[Use TH on cooldown]]
character_1:UseSkill(4)

if enemy_1.charge_diamonds > 1 then
	--[[MC use stall to delay and force OD]]
	character_1.UseSkill(1)
	character_2.UseSkill(2)
	character_2.UseSkill(1)
end

--[[Halle dodge AOE skill]]
if enemy_1.charge_diamonds == 3 then
	--[[Halle use dodge]]
	character_3.UseSkill(1)
end

--[[Gravity and Stall during boss OD]]
if enemy_1.overdrive_state == true then
	character_1.UseSkill(3)
	character_1.UseSkill(1)
end

if enemy_1.hp_percentage <= 65 then
	EnableChargeAttack()
	Summon(1)
end

if enemy_1.hp_percentage < 50 then
	Wait(5000)
	if character_1.hp_percentage < 23 then
	  UseGreenPotionOnPartyMember(1)
	end
	if character_2.hp_percentage < 23 then
	  UseGreenPotionOnPartyMember(2)
	end
	if character_3.hp_percentage < 23 then
	  UseGreenPotionOnPartyMember(3)
	end
	if character_4.hp_percentage < 23 then
	  UseGreenPotionOnPartyMember(4)
	end
end

if enemy_1.hp_percentage < 25 then
	--[[Summon Godsworn Alexiel]]
	Summon(6)
	if characters["Hallessena"] ~= nil then
		characters["Hallessena"]:UseSkill(1)
	end
end

--[[In case backline characters enter into the fray--]]
if characters["De La Fille"] ~= nil then
  characters["De La Fille"]:UseSkill(1)
  characters["De La Fille"]:UseSkill(3)
  if characters["Hallessena"].is_alive == true then
	characters["De La Fille"]:UseSkill(2):OnPartyMember(3)
  end
  if characters["Siegfried"].is_alive == true then
	characters["De La Fille"]:UseSkill(2):OnPartyMember(2)
  end
end
```

**Comment by Masuzu** [comment]
Hi,

The script looks fine.

If I am not mistaken, when you start the NM 60 mode, you will perform those 4 actions:
DisableChargeAttack()
character_1:UseSkill(2)
character_1:UseSkill(4)
--[[Razia's defense buff--]]
character_4:UseSkill(1)

Where exactly does it crash? Would you still have the last messages displayed in your console please before it happened?

**Comment by silverraine** [comment]
After running the first run, it's refreshes the page as per default configuration to skip the animation. I didn't remove it as it's needed to capture enemy status too right? Then it proceeds to turn 2, loads the script again, hangs for a few seconds, then crashes. I've included the screenshot below.
![issue1](https://user-images.githubusercontent.com/12539116/30483877-1f7b2e44-9a5b-11e7-836b-b3c4b724eacd.png)

**Comment by Masuzu** [comment]
Oh wait, never mind, my bad.
Your Script syntax in incorrect:
It is `character_1:UseSkill(1)` instead of `character_1.UseSkill(1)`
