### ISSUE TITLE
is characters["...."].is_alive not functioning as intended?

### ISSUE THREAD

**Issue by zodiark2078** [Masuzu/ZooeyBot#283]
So i have come across the condition where 1 of my character die and "Zooey bot" still attempt to execute the skill code, although i have set it checked whether the character is still alive or not. Can you please check where have my code gone wrong? Thanks in advance. Your Zooey bot has made my life becoming easier.

Sorry i'm still a newbie in these coding scirpts.

In this case, Character Darkness is death:
https://imgur.com/WzMVMvV

My code:

if enemy_1.is_alive == true then
	DisableChargeAttack()
	
	if characters["Vira"].is_alive == true then 
	characters["Vira"]:UseSkill(2)
	characters["Vira"]:UseSkill(1)
	end
	
	if characters["Jeanne d'Arc"].is_alive == true then
	   characters["Jeanne d'Arc"]:UseSkill(2)
	   characters["Jeanne d'Arc"]:UseSkill(1)
	end

	if characters["Darkness"].is_alive == true then
	characters["Darkness"]:UseSkill(2)
	characters["Darkness"]:UseSkill(3)
	characters["Darkness"]:UseSkill(4)
	end

	if enemy_1.charge_diamonds > 0 then
		if character_1.is_alive == true then
		   character_1:UseSkill(1)
		end
	end

    if characters["Darkness"].is_alive == false or characters["Vira"].is_alive == false or characters["Jeanne d'Arc"].is_alive == false or characters["Zooey"].is_alive == false then
    	if characters["Seox"].is_alive == true then
    	characters["Seox"].UseSkill(1)
    	characters["Seox"].UseSkill(3)
    	end
    end

    if characters["Darkness"].is_alive == false and characters["Zooey"].is_alive == false or characters["Darkness"].is_alive == false and characters["Vira"].is_alive == false or characters["Darkness"].is_alive == false and characters["Jeanne d'Arc"].is_alive == false or characters["Zooey"].is_alive == false and characters["Vira"].is_alive == false or characters["Zooey"].is_alive == false and characters["Jeanne d'Arc"].is_alive == false or characters["Vira"].is_alive == false and characters["Jeanne d'Arc"].is_alive == false or characters["Zooey"].is_alive == false then
    	if characters["Vaseraga"].is_alive == true then
    	characters["Vaseraga"].UseSkill(3)
    	characters["Vaseraga"].UseSkill(1)
    	characters["Vaseraga"].UseSkill(2)
    	end
    end

	if characters["Vira"].is_alive == true and characters["Vira"].charge_gauge >= 50 and characters["Vira"].skill_4_available == true then
		characters["Vira"]:UseSkill(4):WithWaitTime(2000)
	end

	if characters["Jeanne d'Arc"].is_alive == true and characters["Jeanne d'Arc"].hp <= 1100 then
		booleans["Unchanllenged"] = true
	end

	if character_1.charge_gauge == 100 and character_2.charge_gauge >= 90 and character_3.charge_gauge >= 80 and character_4.charge_gauge >= 70 then
	Summon(6)
	characters["Zooey"]:UseSkill(2)
	characters["Zooey"]:UseSkill(1)
	characters["Zooey"]:UseSkill(3)	
		EnableChargeAttack()
	booleans["Unchanllenged"] = false
	end
    
    if booleans["Unchanllenged"] == true then
       characters["Jeanne d'Arc"]:UseSkill(3)
    end
end

**Comment by Masuzu** [comment]
Hi,

The `is_alive` field is only intended to be used with the variables `character_1`, `character_2` and so on.
If you want to check by name whether `CharacterName` is alive, you have to do it as follows:
```
if characters["CharacterName"] ~= nil then
   --[[Do something]]
end
```
Please note that the character names are case sensitive.
