### ISSUE TITLE
Raid Scheduling Issue

### ISSUE THREAD

**Issue by iSDestiny** [Masuzu/ZooeyBot#284]
So I noticed that if you reroll when your preferred summon isn't found, this is counted as one of the attempts for that raid. I'm not sure if this was intended or not but I just wanted to point it out since it was bothering me that some of my hard raids weren't completed due to this.

**Comment by Masuzu** [comment]
Hi,

Yes it is the expected behaviour. You might want to use the parameter `RerollSummonWhenNoPreferredSummonWasFound`
https://github.com/Masuzu/ZooeyBot/wiki/Summon-selection

Doesn't everyone use a sword master with DJeanne sword and the first skill to deal over 1.2M white damage nowadays ;)
