### ISSUE TITLE
Update Idea "Enemy Debuff and buff check".

### ISSUE THREAD

**Issue by clowniiizzz** [Masuzu/ZooeyBot#286]
i think checking for enemy buff and debuff effect usefull for some case. ex: reflact so if avaible we can use "Dispel" or When "Paralyze" active we can command bot to attack without using skill. Thank You.

**Comment by Masuzu** [comment]
Hi,

This feature is less trivial to add than it seems as those status effects are time based and not turn based most of the time. I had it in mind and will consider doing something about it later.
The main objection I have to do it is that the only way to retrieve a character or enemy status and the duration of their remaining active effects, a long query has to me made. This could induce some noticeable delay each turn as seen with the `RetrieveActiveStatus` parameter, and some people compained about those.
