### ISSUE TITLE
Still the bug related to replaced characters

### ISSUE THREAD

**Issue by zodiark2078** [Masuzu/ZooeyBot#289]
So i have changed all the code as you instructed, and i came across the situation, when the characters in front row is replaced by characters in back row, Zooey bot crash. Can you check it for me? Thanks for solving my problems.

In this case, Characters Vira is death:
https://imgur.com/a/dFgDU

My code
```
if enemy_1.is_alive == true then
  DisableChargeAttack()

  if characters["Vira"] ~= nil then
    characters["Vira"]:UseSkill(2)
    characters["Vira"]:UseSkill(1)
  end

  if characters["Jeanne d'Arc"] ~= nil then
    characters["Jeanne d'Arc"]:UseSkill(2)
    characters["Jeanne d'Arc"]:UseSkill(1)
  end

  if characters["Darkness"] ~= nil then
    characters["Darkness"]:UseSkill(2)
    characters["Darkness"]:UseSkill(3)
    characters["Darkness"]:UseSkill(4)
  end

  if enemy_1.charge_diamonds > 0 then
    if characters["Darkness"] ~= nil then
      characters["Darkness"]:UseSkill(1)
    end
  end

  if characters["Seox"] ~= nil then
    characters["Seox"].UseSkill(1)
    characters["Seox"].UseSkill(3)
  end

  if characters["Vaseraga"] ~= nil then
    characters["Vaseraga"].UseSkill(3)
    characters["Vaseraga"].UseSkill(1)
    characters["Vaseraga"].UseSkill(2)
  end

  if characters["Vira"] ~= nil and characters["Vira"].charge_gauge >= 50 and characters["Vira"].skill_4_available == true then
    characters["Vira"]:UseSkill(4):WithWaitTime(2000)
  end

  if characters["Jeanne d'Arc"] ~= nil and characters["Jeanne d'Arc"].hp <= 1100 then
    booleans["Unchanllenged"] = true
  end

  if character_1.charge_gauge == 100 and character_2.charge_gauge >= 90 and character_3.charge_gauge >= 80 and character_4.charge_gauge >= 70 then
    Summon(6)
    characters["Zooey"]:UseSkill(2)
    characters["Zooey"]:UseSkill(1)
    characters["Zooey"]:UseSkill(3)
    EnableChargeAttack()
    booleans["Unchanllenged"] = false
  end

  if booleans["Unchanllenged"] == true then
    characters["Jeanne d'Arc"]:UseSkill(3)
  end
end
```

**Comment by Imakuki** [comment]
You are trying to check Vira's charge gauge right here which might be leading to a crash in the case where Vira is dead. 
```
if characters["Vira"] ~= nil and characters["Vira"].charge_gauge >= 50 and characters["Vira"].skill_4_available == true then
	characters["Vira"]:UseSkill(4):WithWaitTime(2000)
end
```
Try a different approach like this (for any characters) :
```
if characters["Vira"] ~= nil then 
  if characters["Vira"].charge_gauge >= 50 and characters["Vira"].skill_4_available == true then
	characters["Vira"]:UseSkill(4):WithWaitTime(2000)
  end
end
```
Hope this helps.

**Comment by Masuzu** [comment]
Hi,

I'm afraid it is a script syntax error:
`characters["Seox"].UseSkill(1)` sould be `characters["Seox"]:UseSkill(1)` and likewise for similar occurrences.
However, thank you for reporting this. Zooey is supposed to return an error message instead of crashing when this happens.

**Comment by zodiark2078** [comment]
Thanks for pointing out my errors. Everything works fine for now. Also, can you fix the error of using green potion? For example, when the characters use skill and still on characters skill tab, and right after that zooey bot execute the function usegreenpotion, it will get stuck because zooey bot can't find the targeted characters. I have to refresh the page which is really inconvenient and time-wasted.

**Comment by Masuzu** [comment]
You're welcome, I am glad to hear this!
Using a green potion followed by a skill works fine on my side. It may not on your side depending on "how much time" it takes to receive the server response after using your potion and the animation playing time.
To mitigate this issue, please add a Wait(XXX) after using the potion (https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts#force-zooey-to-wait-before-performing-the-next-action)
