### ISSUE TITLE
Problem with payment with paypal

### ISSUE THREAD

**Issue by ryokage** [Masuzu/ZooeyBot#290]
I had a great first month and wanted to extend another month but just letting you know your paypal payment method isn't working atm. Please fix it so I can keep using this great program. It says payment is not available from this merchant atm.

**Comment by Masuzu** [comment]
Hi,
I can confirm that Paypal transactions are working.
Maybe it was a transient issue.

**Comment by ryokage** [comment]
Still same problem https://imgur.com/a/aDFp5

**Comment by ryokage** [comment]
Still getting the same problem https://imgur.com/a/aDFp5 even when in incog mode
