### ISSUE TITLE
Paypal still not working

### ISSUE THREAD

**Issue by ryokage** [Masuzu/ZooeyBot#292]
Hi I posted a topic about this a day or ago or so and still running into the payment error. I definitely need this for guild war. thanks! I'm from the US if that makes a difference. Ive tried it multiple times throughout today and last nite but still run into same problem even in incognito
https://imgur.com/a/RGO6p

**Comment by Masuzu** [comment]
Hi,
I can confirm that Paypal payments work. It is probably an issue with your Paypal account (so this time, the issue is not something I can work on). There is Stripe which is also provided as an alternative payment processor.
