### ISSUE TITLE
bot doesn't use combat scripts during scheduling mode

### ISSUE THREAD

**Issue by merkavahaha** [Masuzu/ZooeyBot#295]
hi,

I set up a script to go through the daily 10/15 AP raids with scheduling mode. However, my teams aren't strong enough to kill all the bosses just by autoattacking, so I wrote a simple lua script that uses my teams buffs, skills etc.  Unfortunately, the script doesnt activate when I start a battle so they just start autoattacking as usual.

It's not a problem with my combat script itself since it works when farming favourite or special quests in default mode.

If anyone can help it would be appreciated, thank you

**Comment by Masuzu** [comment]
Hi,

From the info you provided I guess that misconfigured the path to your scripts:
https://github.com/Masuzu/ZooeyBot/wiki/Customized-raid-scheduling
Paths are relative to the location of `ZooeyBot.exe`.
