### ISSUE TITLE
Sometimes Zooey clicks profile instead of summons

### ISSUE THREAD

**Issue by JermaineCole** [Masuzu/ZooeyBot#297]
Hi,
Sometimes Zooey clicks on a profile name instead of the support summon. I have to manually press previous page on Chrome to fix this. Is there a way to automaticly bypass this? 

Thanks in advance

**Comment by Masuzu** [comment]
Hi,
It looks similar to the issue reported in https://github.com/Masuzu/ZooeyBot/issues/293

**Comment by JermaineCole** [comment]
I've read the issue and tried to change the  max response time to a higher value, yet the issue still reoccurs. 
I use Viramate and have it show Kaguya/WhiteRabbit at the top so Zooey doesn't have to scroll down to pick one so I don't think it's a scrolling issue in my case. I'll try to record / replicate the bug and post it here.

**Comment by Masuzu** [comment]
Ok, thank you!

**Comment by JermaineCole** [comment]
Here's the recorded issue
It happens around 8:55
https://www.youtube.com/watch?v=WmoC2yxBszo

**Comment by Masuzu** [comment]
Thank you very much.
Ah I realize why it happens: you probably have an option in Viramate which disables displaying the effect of the summons in the summon selection screen.
I did not think that some people would use it.
I will take it into account in the future patch.

**Comment by JermaineCole** [comment]
I disabled that option in Viramate and the bug isn't happening anymore!

Thank you for creating this awesome bot and actively helping with issues!

**Comment by Masuzu** [comment]
Thank you for the feedback.
This is the summon settings I use for Viramate:
![](https://i.imgur.com/zZyiQFH.png)
