### ISSUE TITLE
Program sets Player and Slave ID as the same number

### ISSUE THREAD

**Issue by Dewten** [Masuzu/ZooeyBot#299]
Before slimeblasting, opening up devtools in the slave window and starting beatrix, then opening up devtools in the main window and starting zooey sets both IDs to my slave account ID. Doing the opposite sets both IDs to my main account ID, causing the program not to work correctly. Is this behavior chrome's fault and if that's the case how do I go about it?
![example](https://user-images.githubusercontent.com/12978332/30696327-8fd3701e-9edb-11e7-9682-d53182c8faa3.jpg)

**Comment by Dewten** [comment]
Update: It sometimes works if I open the devtool windows beforehand, but then it gets stuck on "something went wrong while trying to set the quest" and the program keeps refreshing the main account. I was never able to send the bot to a fight.

**Comment by Masuzu** [comment]
Hi,
This is a typical issue which happens if you do not follow **exactly** the instructions listed on https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting).
