### ISSUE TITLE
slime master no longer returning to lobby.

### ISSUE THREAD

**Issue by jsun1234** [Masuzu/ZooeyBot#301]
I can get it to run normally until it gets to loot page, then slave returns to lobby as usual, but master doesn't. Any chance this can be resolved before gw starts?

**Comment by Masuzu** [comment]
Hi,
Thank you for reporting this issue this quickly!
I found the problem and will release a fix withing the next hour, with the new solo co-op mode as well.
https://github.com/Masuzu/ZooeyBot/wiki/Solo-co-op-mode

**Comment by Masuzu** [comment]
This is now fixed with the release of the version 1.22.0, which also introduces the new solo co-op mode:
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#1-22-0
