### ISSUE TITLE
I know korwa has a fil counter is there something for Siete?

### ISSUE THREAD

**Issue by ryokage** [Masuzu/ZooeyBot#302]
I know korwa has a fil counter is there something for Siete for his stacks? Something to dectect if he has 3 stacks and uses it for team ougi?

**Comment by Masuzu** [comment]
Not for now, unless you can provide me with the buff ID for each number of stack, as done in https://github.com/Masuzu/ZooeyBot/wiki/Lua-Scripts-(character-specific)
https://github.com/Masuzu/ZooeyBot/wiki/Lua-Scripts-(playing-with-status-effects)
Please check the last section mentioning the file "status_effects.txt".
You will need however to have the parameter RetrieveStatusEffects set to true which might slow down Zooey's actions.

**Comment by Hexadecimalism** [comment]
Mildly unrelated, but here are the ones for Rosetta's stacks.

14601 Rose Barrier [turn]
14602 Rose Barrier [turn]
14603 Rose Barrier [turn]
14604 Rose Barrier [turn]

**Comment by ryokage** [comment]
^ so would that code indicate just the status of her barrier or when to use it. can you give me an example of her using her skills at 5 stacks to get the bonus?

**Comment by Masuzu** [comment]
Thank you @Hexadecimalism 
I will update the list later.

**Comment by Masuzu** [comment]
@ryokage Please refer to https://github.com/Masuzu/ZooeyBot/issues/320
It is more of a "do it yourself" thingie.
