### ISSUE TITLE
Guild war farming

### ISSUE THREAD

**Issue by Garnetus** [Masuzu/ZooeyBot#303]
Hello.
So I set the EventRaidUrl to "http://game.granbluefantasy.jp/#event/teamraid033/supporter/722151/1" which is the EX+ summon page for this GW.
Somehow  zooey always get me back to the main page after the"quest menu" and stopped working....I have no idea if its my PC or its the bot.

Tried download the bot again with fresh setting, same thing. The alt account with fresh chrome, same thing. 
PS: It worked just fine last guild war.

**Comment by devvah** [comment]
Same problem, tried to setup bot but seems like switching urls too fast results in getting thrown back to main page.

**Comment by Garnetus** [comment]
Pretty sure other events/missions works, just tried halo, perfectly fine. Just the guild war farm won't work.

**Comment by sharrkan** [comment]
I have the same issue with the bot going to main page and skipping over the quest

**Comment by Masuzu** [comment]
Hi, it works perfectly fine if you follow the instructions on https://github.com/Masuzu/ZooeyBot/issues/300

I guess you are missing `EventPageUrl=http://game.granbluefantasy.jp/#event/teamraid033`

**Comment by Garnetus** [comment]
It worked! Did not add this line last time and worked just fine so I did not read your guide carefully.

Thanks for the reply
