### ISSUE TITLE
Party member target skill problem

### ISSUE THREAD

**Issue by sinanjugbf** [Masuzu/ZooeyBot#305]
I'm getting the error "attempt to call a nil value (method 'OnPartyMember') when I use Scathacha's shield. The codes I'm trying to use are 
characters["Scathacha"]:UseSkill(3):OnPartyMember(1)
character_3:UseSkill(3):OnPartyMember(1)

Neither one work.

**Comment by Masuzu** [comment]
Hi,
It looks like a bug.
I will investigate it.

**Comment by Masuzu** [comment]
It works as intended? Not sure what went wrong.
Tested with Scathacha is the 3rd position with both:
`character_3:UseSkill(3):OnPartyMember(1)`
and `characters["Scathacha"]:UseSkill(3):OnPartyMember(1)`
