### ISSUE TITLE
After error message bot skip the skill

### ISSUE THREAD

**Issue by ariaanaa** [Masuzu/ZooeyBot#306]
Hi!
it is because of lag or what some time the game give me error message in the middle of using character skill, then the bot reload it self and skip the remaining skill and just click the attack button. i hope you have solution for this also i use this script [https://github.com/Masuzu/ZooeyBot/issues/300](url) for farm EX+

thank you,

**Comment by Masuzu** [comment]
Hi!

This is due on the speed at which your animation plays/whether you have other active raids at the time (using skills too fast in 2 different raids on in the same raid will reset in a popup error message)

You may want to tweak the parameters:
```
[Combat]
# Zooey-bot will wait at least the given number of milliseconds after pressing the attack button
MinWaitTimeInMsAfterAttack=500
# Zooey-bot will wait at least the given number of milliseconds after using a summon
MinWaitTimeInMsAfterSummon=3000
# Zooey-bot will wait at least the given number of milliseconds after using a skill
MinWaitTimeInMsAfterAbility=2100
```
and/or use `WithWaitTime` in your scripts (https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts#using-skills)
