### ISSUE TITLE
Is there an example script for krowa for 90 nm gw?

### ISSUE THREAD

**Issue by ryokage** [Masuzu/ZooeyBot#308]
Is there an example script for krowa for 90 nm gw? how to use ougi at 8-10 fill and only use ta/attack buffer at certain times to make sure its at 10 fil? thanks! I saw a post earlier about how you were going to post a lua example but haven't seen it yet

**Comment by Masuzu** [comment]
People do not use Korwa to clear the NM 90 mode as she is really slow. I do not either so I won't be posting any example script using Korwa for the NM 90 mode but maybe others will.

**Comment by ryokage** [comment]
Got it. Whom would you use for nm90 and script wise?

**Comment by Masuzu** [comment]
I do not think it would be applicable to a lot of other players.
Not having any wind GW character:
Chaos Ruler, Lecia, Melissabelle, Swimsuit Siegfried (Gawain and Esser in the back)
That's with a complete Maga grid (+99 included) and a FLB Morrigna to deal with the triggers.
But you should rather see what works best for your grid and team/check youtube probably to see examples.
