### ISSUE TITLE
Can a lua file cause Zoey to crash?

### ISSUE THREAD

**Issue by granblue5eva** [Masuzu/ZooeyBot#309]
Has happened 5 times now, where Zoey gets stuck on the "loading lua script" step when trying to farm GW and then I get a Windows pop-up indicating the program has stopped working. Is there some sort of limitation on length / complexity of lua file that could cause Zoey to crash?

**Comment by Masuzu** [comment]
Yes it can and was reported in a previous ticket, even though it should not. It's usually due to a syntax error. The length of the file is not an issue.
Can you please post the script you're trying to use?

**Comment by granblue5eva** [comment]
Here is the lua file I was using - I don't think it was due to a syntax error though, as the bot was catching those and giving me an explicit error message when there were syntax errors in the script (sidenote, some sort of compiler program for debugging lua scripts would be nice to have).

--[[Green Potion heal first priority--]]
if character_1.hp_percentage < 30 then
   UseGreenPotionOnPartyMember(1)
end
if character_2.hp_percentage < 30 then
   UseGreenPotionOnPartyMember(2)
end
if character_3.hp_percentage < 30 then
   UseGreenPotionOnPartyMember(3)
end
if character_4.hp_percentage < 30 then
   UseGreenPotionOnPartyMember(4)
end

--[[Anchira emergency heal if any party member under 20% HP--]]
if character_3.name == "Andira" then
   if character_1.hp_percentage < 20 then
       character_3.UseSkill (2)
   end
   if character_2.hp_percentage < 20 then
       character_3.UseSkill (2)
   end
   if character_3.hp_percentage < 20 then
       character_3.UseSkill (2)
   end
   if character_4.hp_percentage < 20 then
       character_3.UseSkill (2)
   end
end

--[[Use summons off CD--]]
Summon (6)
Summon (1)
Summon (2)
Summon (4)
Summon (5)
Summon (3)

--[[Turn 1 and charge attack management--]]
if turn == 1 then
   DisableChargeAttack()
   character_1:UseSkill(4)
   character_2:UseSkill(1)
   character_2:UseSkill(3)
   character_3:UseSkill(1)
   character_4:UseSkill(3)
   character_4:UseSkill(2)
   character_1:UseSkill(2)
   character_1:UseSkill(3)
   character_1:UseSkill(1)
   character_4:UseSkill(1)
end

if turn == 4 then
   EnableChargeAttack()
end

--[[Use skills off CD for frontline--]]
if character_1.name == "Name" then
   character_1.UseSkill(2)
   character_1.UseSkill(4)
   character_1.UseSkill(3)
   character_1.UseSkill(1)
end

if character_2.name == "Nezahualpilli" then
   character_2.UseSkill(1)
   character_2.UseSkill(2)
   character_2.UseSkill(3)
end

if character_3.name == "Andira" then
   character_3.UseSkill(3)
end

if character_4.name == "Carmelina" then
   character_4.UseSkill (3)
   character_4.UseSkill (2)
   character_4.UseSkill (1)
end

--[[Backrow character emergence--]]
if characters["Scathacha"] ~= nil then
   characters["Scathacha"].UseSkill(1)
   characters["Scathacha"].UseSkill(2)
end

if characters["Siegfried"] ~= nil then
   characters["Siegfried"].UseSkill (1)
   characters["Siegfried"].UseSkill (2)
end
