### ISSUE TITLE
Hard raids not working

### ISSUE THREAD

**Issue by XenoeJin** [Masuzu/ZooeyBot#31]
![image](https://cloud.githubusercontent.com/assets/23413591/25935951/14c9463c-3658-11e7-8da1-dcc7f8df3499.png)

Hard raids not working, the bot just does nothing after selecting the hard raid.

**Comment by prokopets** [comment]
if i am not mistaken, hard raids are not supported

**Comment by Masuzu** [comment]
Hi, it is not supported and won't be.
