### ISSUE TITLE
[Question] About ChromeDevToolsWindowDockedOnTheRight

### ISSUE THREAD

**Issue by musashi111** [Masuzu/ZooeyBot#310]
![1](https://user-images.githubusercontent.com/32217526/30771787-e5794780-a081-11e7-91b6-4910fdffccc0.png)
hello, I try to start ZooeyBot today but it seems that ZooeyBot can't make sure where my chrome devtools is docked. I tried to reinstall it but it didn't work at all.
 How came it to be so and how to fix it? Thank you very much.

**Comment by Masuzu** [comment]
Hi,

Please use this ![](https://i.imgur.com/qtCb9yb.png) to choose the docking location.
Zooey Bot only supports docking the DevTool window either to the right or at the bottom.

**Comment by musashi111** [comment]
both two plans
1.use dock to bottom with"ChromeDevToolsWindowDockedOnTheRight=false"
2.use dock to right with"ChromeDevToolsWindowDockedOnTheRight=true"
have been tried before I post the first issue, but without success;
Maybe my chrome has some problems with the setting but I can't find out.
Thank you anyway!

**Comment by Masuzu** [comment]
Make sure to have the Network tab open in the DevTool window, like this:
![](https://i.imgur.com/nEvBwch.png)

**Comment by musashi111** [comment]
![1](https://user-images.githubusercontent.com/32217526/30782461-49269f38-a165-11e7-8854-7654cc50d6e6.png)
![2](https://user-images.githubusercontent.com/32217526/30782462-4c4408f4-a165-11e7-9137-690caa6d22b0.png)
There are the two patterns. Anything is wrong in the two picture?
Sorry about it but please tell me anything can I try to do, thank you.

**Comment by Masuzu** [comment]
Those are both fine.
If you still have issues with the initialization phase it is very likely related to scaling issues (not ingame scaling but also windows DPI scaling (https://github.com/Masuzu/ZooeyBot/wiki/FAQ#i-have-scaling-issues-again)
