### ISSUE TITLE
GW 90 bug

### ISSUE THREAD

**Issue by jpgodkit** [Masuzu/ZooeyBot#311]
I can run EX+ but I can't run 90hell

[EventMode]
# Set this parameter to true to use the event mode. Zooey will enter autopilot mode when you navigate to the quest menu.
Enabled=true
# Url of the summon selection page for the Xeno Sagittarius Extreme mode.
EventRaidUrl=http://game.granbluefantasy.jp/#event/teamraid033/supporter/722171/1
EventRaidScript=Scripts/battlehell.lua
# Url of the summon selection page for the Xeno Sagittarius Nightmare level 100 mode.
NightmareModeUrl=
NightmareModeScript=
# Some events such as Rise of the Beasts require to navigate to the home page of the event before navigating to the event raid url defined above. If EventPageUrl is provided, Zooey will first navigate to this url before hosting the raid. Leave EventPageUrl blank for events which do not require you to do so.
EventPageUrl=http://game.granbluefantasy.jp/#event/teamraid033
# Comma-delimited list of summons which will be selected in priority if they are available for the nightmare mode.
# In case none of the preferred summons was found, select a random summon in the summon attribute tab defined by the parameter DefaultSummonAttributeTab, unless the parameter RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode is set to true.
NightmareModePreferredSummons=Bahamut
# Zooey will reroll summons until one of the preferred summons for the nightmare mode is available, using trial battles to refresh the summon list.
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
# Set this parameter to true if the nightmare mode is available when you start Zooey so she can proceed to the nightmare stage right ahead.
NightmareModeAvailableAtStart=false
# Wait time in milliseconds after Zooey finishes loading the EventPageUrl
WaitTimeInMsAfterEventPageIsLoaded=1000

**Comment by rabbidluigi** [comment]
You can't use event mode for GW NM - you need to use treasure event mode as described here https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode

**Comment by Masuzu** [comment]
Thanks, please do that indeed.
It is on the front page too by the way...
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home
