### ISSUE TITLE
Capture mode for status effects.

### ISSUE THREAD

**Issue by Hexadecimalism** [Masuzu/ZooeyBot#313]
I suggest "RetrieveStatusEffects=" be it's own mode [RetrieveStatusEffects] like [EventMode] and [TreasureEventMode]. A capture mode that runs no scripts while the player plays to capture status effects. This will allow you to switch parties, characters, quests etc while the bot does nothing but capture status effects. The current method of doing it requires stopping the bot, switching characters and sometimes the quest in the .ini script for new characters.

**Comment by Masuzu** [comment]
That would be great indeed.
Probably after the guild war though.

**Comment by Masuzu** [comment]
Implemented in v2.6
