### ISSUE TITLE
hang after gw screen w/ treasure event mode

### ISSUE THREAD

**Issue by zyphil** [Masuzu/ZooeyBot#314]
I'm trying to use the treasure event mode to farm ex+.

I set the difficulty parameter to ex, and the action points to 40. I start up the bot, and it brings me to the UnF screen http://game.granbluefantasy.jp/#event/teamraid033.
Then it does nothing. It just sits there, not even choosing a raid. I don't need it to farm NM's or VH. Just EX+. 

Also, there are two extremes. EX and EX+. Can I get some clarification on what to use for EX+ in regards to difficulty parameters? Is it just ex with AP 40? Or is it like ex-2/ex-+(I've tried)/ex-1, etc?

**Comment by zyphil** [comment]
Disregard, I'm just gonna use the event mode again.

**Comment by Masuzu** [comment]
Hi,
You have to use the EventMode for the GW events EX+ mode specifically.
https://github.com/Masuzu/ZooeyBot/issues/300
