### ISSUE TITLE
Debugging print outs?

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#317]
Any chance we could get print() to work to print things to console for help debugging scripts?

**Comment by Masuzu** [comment]
Hi,
I will consider adding this feature, after the GW though.

**Comment by Masuzu** [comment]
Actually, you should already be able to do so:
`print(<something>)`

**Comment by thebp2** [comment]
I just tried this with 2.6.0 and zooeybot crashed.
