### ISSUE TITLE
.is_alive not working

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/ZooeyBot#318]
In code below, the lua parsing returns an error because Korwa is dead. characters["Korwa"] return a nil.
The wiki needs to be adjusted.
if characters["Korwa"].is_alive then
	if characters["Korwa"]:HasStatusEffect("1534") and (not characters["Korwa"]:HasStatusEffect("1535")) then
	  characters["Korwa"]:UseSkill(1)
	end
	if (not characters["Korwa"]:HasStatusEffect("1534")) and num_korwa_fils == 10 then
		characters["Korwa"]:UseSkill(2)
	end
end

**Comment by Masuzu** [comment]
Please use `if characters["Korwa"] ~= nil` in the meantime.
