### ISSUE TITLE
Question - Is it possible to refresh on specific turns?

### ISSUE THREAD

**Issue by nezabird** [Masuzu/ZooeyBot#319]
ReloadPageOnLastBattle=true refreshes after every attack, but I only want Zooeybot to refresh after the EX+ 50% trigger since the boss animation takes too long. Is it possible to use something like "if turn = x, reload after pressing the attack button"?

**Comment by Masuzu** [comment]
Hi,
Yes you can: https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts#force-page-refresh

**Comment by nezabird** [comment]
I tried this but Zooey ended up refreshing before attacking on turn x. What do I have to do to make the refresh happen after pressing attack?

**Comment by Masuzu** [comment]
You can't. It's not supposed to be used that way.
I am not sure why people do not want to refresh after each turn.
That's the way you have to play if you want to race and optimize your clear time.
