### ISSUE TITLE
Using the status effect list to find out buffs and status effect IDs

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/ZooeyBot#320]
1. The wiki mentioned status_effect.txt but I can't find it on my zooeybot package.
2. With 1.22.2, do I still have to RetrieveStatusEffect for ailment that is not in Lua-Scripts-(character-specific) page ? Since that function is taking a long time to do.
3.  I would be thankful if anyone can tell me Scarred debuff ID from NM bird. :)

**Comment by 13olt3** [comment]
Yeah that would be useful, is there a way to detect a debuff and then use skill on character with that debuff, my example would be Scarred + Lecia cure.

**Comment by Masuzu** [comment]
Hi,

You need to set RetrieveStatusEffect to true to have that status_effects.txt file created and updated each time your characters are affected by a new buff/debuff. This will indeed increase noticeably the processing time for each turn (less visible with a good ping) but will help you find the ID of the status effects which interest you.
