### ISSUE TITLE
Can't detect break_state and overdrive_state.

### ISSUE THREAD

**Issue by Nassy1121** [Masuzu/ZooeyBot#324]
I use 1.22.2 but still can't detect break_state and overdrive_state of enemy.

eg.)
  if enemy_1.break_state == true then
    characters["xxxx"]:UseSkill(2)
  end

I know it's known issue but would you have plan to fix it?

**Comment by Masuzu** [comment]
Hi,

I am aware of this issue indeed.
I do have plans to fix it, as to when I do not know, but comparatively to the other enhancement and bug requests this will have the priority.

**Comment by Masuzu** [comment]
This will be solved incidentally with https://github.com/Masuzu/ZooeyBot/issues/328
