### ISSUE TITLE
Cursor stuck issue

### ISSUE THREAD

**Issue by Ramkm77** [Masuzu/ZooeyBot#325]
Sometimes while choosing the summon . And scroll down up while looking  but when it's go up to choose the summon it's stuck under the url bar and gives captcha sound.

It's happen from time to time and should reset the bot and start again. 

Anyone got idea how to solve it.

Thx

**Comment by Masuzu** [comment]
If Zooey scrolls down too far down the summon list, you may want to reduce the scrolling speed parameter.

**Comment by Ramkm77** [comment]
Thx a lot . Went very smooth after decreasing the scrolling speed
