### ISSUE TITLE
Blue potion issue

### ISSUE THREAD

**Issue by Ramkm77** [Masuzu/ZooeyBot#326]
When the bot try using blue potion . And no potion there it's go for sticker then go heal use blue potion . While using the sticker and one of the chars skills page up. So there no heal button . So bot stuck here.

Anyway if there is a way to use sticker from the start so u can avoid this bug.

**Comment by Masuzu** [comment]
Oh, thanks for reporting this.
If you want to use a blue potion, please do it before using any other skills for now, *unless* you use Viramate, in which case you won't run into this issue.
