### ISSUE TITLE
Support for lite animation settings

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#327]
I've been using Zooey on the lite animation setting to make it go faster, but just today (because of the game update), it gets stuck on calibrating when on lite. Switching back to standard makes calibration instantly work so I'm pretty sure that setting is the issue.

**Comment by Masuzu** [comment]
Don't, it 's not supported for now and have no plan to support it for now, not until the end of the GW at least.

**Comment by Masuzu** [comment]
Hi,
I can confirm that you can use Lite settings from the get go so it should work already.
