### ISSUE TITLE
Bot stopping when farming GW EX.

### ISSUE THREAD

**Issue by ExtantLily** [Masuzu/ZooeyBot#329]
The bot stops working after about 15 minutes or so of continuously farming GW EX. Capture Snapshots is off.

**Comment by Masuzu** [comment]
Hi,

I am sorry but given the lack information given, the issue is too isolated and can't be reproduced, and hence will be closed. Simple matter of etiquette.
I have been running ZooeyBot for sessions of 2-3 hours in a row to farm the EX+ mode.
