### ISSUE TITLE
Can't farm event raid bosses

### ISSUE THREAD

**Issue by Antialiased** [Masuzu/ZooeyBot#33]
For some reason when I give Zooey the url for an event raid boss (say, Quinglong Nightmare), and it pastes it into the address bar, I am redirected back to the front page unless I go through the event page dialog where I select a celestial. This was also a problem with farming the raid bosses in the previous event.

Going through the event page first will make the link work, but only for a few minutes so the bot can't farm unsupervised.

Repro:
- Paste http://game.granbluefantasy.jp/#quest/supporter/711091/1 in to the address bar
- Observe you are redirected to http://game.granbluefantasy.jp/#mypage

Obviously this is not a problem with Zooey but it prevents me farming these bosses which is unfortunate.

**Comment by mdanishu** [comment]
Same problem for me

**Comment by XenoeJin** [comment]
Me too, same issue, I find that the game will send you to the home screen when you select quest, but if you go to the rise of the beast page, pasting the link works.

**Comment by Masuzu** [comment]
Ok got it, you need to be on the page http://game.granbluefantasy.jp/#event/advent015 to be able to move to the selection page.
Week-end and coming in a few hours, as well as the fix for this.

**Comment by Masuzu** [comment]
This should have been fixed with the version 1.3.0 which adds a new configuration parameter `EventPageUrl`.
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes
