### ISSUE TITLE
Lua Scripting - Setting Combat to Autobattle

### ISSUE THREAD

**Issue by AutoRobotnik** [Masuzu/ZooeyBot#330]
Is it possible to add a lua script parameter that will allow us to set combat to Auto? This is not a priority, as the bot functions just fine without it, but it seems it could save some time. 

Bit of backstory: I'm strong enough to defeat a boss by debuffing, then setting battle to Auto, but if I try something similar with Zooey, she takes too long and the debuffs end up falling off, which causes the run to fail. I realize I am able to reapply the debuffs after a certain number of turns have elapsed, but this just increases the run time by roughly 1 minute, which in bot terms, means a lot less runs completed.

**Comment by Masuzu** [comment]
Hi,
I am not sure which part takes too long? Could you please elaborate?
