### ISSUE TITLE
lua script sample for hard raids

### ISSUE THREAD

**Issue by readmynameplease** [Masuzu/ZooeyBot#332]
Hi! I just wanted to know if someone can share a script they made for auto completing the hard raids this will be a big help for me as I have zero idea on how to start a script

**Comment by Masuzu** [comment]
Hi,
You already have a ton of examples and exhaustive documentation [here](https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts) and [here](https://github.com/Masuzu/ZooeyBot/wiki/Customized-raid-scheduling).

**Comment by LordShade** [comment]
SetLuaScript("Scripts/Magna.lua")
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300041/1", 15, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300091/1", 15, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300151/1", 15, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300191/1", 15, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300221/1", 15, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300251/1", 15, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300031/1", 10, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300081/1", 10, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300141/1", 10, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300181/1", 10, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300211/1", 10, 3)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300241/1", 10, 3)

basic as hell but it does the job

remove the first line if you don't use a lua script for picking skills.

**Comment by readmynameplease** [comment]
thanks a lot man!

**Comment by Masuzu** [comment]
Awesome, thanks
