### ISSUE TITLE
Setting up a PreferedPartyGroup/Deck on schedule mode.

### ISSUE THREAD

**Issue by GumiFlatline** [Masuzu/ZooeyBot#334]
Like the title says, it's possible to set up different party group/deck in a scheduling script? Like, let's say I want the first raid in my schedule list to use the 1st party on 1st party group, but I want to use the 2nd party on 1st party group in the next scheduled raid. 

Thanks in advance.

**Comment by Masuzu** [comment]
Hi,
I took note of the request.
