### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by cakei** [Masuzu/ZooeyBot#336]
Zooey worked fine, used her 10 pots and stopped. Then when I tried to reopen her, she stopped and gave me these errors. I cleared the cache but it didn't work. Not sure if its on my side to fix it but it looks like # is missing just before the quest 
instead of /#quest/ its /quest 

https://puu.sh/xMCkk/6848119672.png
https://puu.sh/xMCjG/8aaf322da0.png
var xmlhttp=new XMLHttpRequest;xmlhttp.open('GET','http://game.granbluefantasy.jp/quest/quest_data/0/6',!0),xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState===XMLHttpRequest.DONE){var apCost=JSON.parse(xmlhttp.responseText).action_point;chrome.runtime.sendMessage({data:btoa(apCost)})}},xmlhttp.send();

**Comment by Masuzu** [comment]
Hi,
The quest ID selected is not correct. (6 in your case), hence the error.
