### ISSUE TITLE
Discord Server and Beatrix first skill question

### ISSUE THREAD

**Issue by readmynameplease** [Masuzu/ZooeyBot#337]
is it possible to have a discord server as we can help out each other there in more convenient way?
and about Beatrix how can I set Beatrix 1st skill for her to use it only twice  in the lua script for optimal buff?
I already took a look at the status effect and it seems her buff is not in there

**Comment by Masuzu** [comment]
Hi,

As for the discord server I am not so sure as a lot of people would like to keep their identity hidden.
To retrieve the ID of status effects, actually it is more of a "do-it-yourself" thingie, and the procedure to do so is described in the 3rd post of this issue: https://github.com/Masuzu/ZooeyBot/issues/320, which in turn will point you to this documentation page: https://github.com/Masuzu/ZooeyBot/wiki/Lua-Scripts-(playing-with-status-effects)

**Comment by readmynameplease** [comment]
i did try the retrieve status effect but the buff it gets from beatrix is not showing up

**Comment by Masuzu** [comment]
Do you mean that your status_effects.txt file is empty or that it does not show up inside the effects listed?
To have it showed up you will need to take a second turn with the buff effect _still active_ and setting `ReloadPageOnLastBattle` to true. You can easily do this using the TrialBattleMode (parameter under the Debug section) and a trial battle.
Granted though, it is not very convenient for now.

**Comment by Masuzu** [comment]
https://github.com/Masuzu/ZooeyBot/issues/342

**Comment by readmynameplease** [comment]
then they should make a fake discord account? so we can all communicate together. 

and got 1 more question how do I set up zooey to reload when the lage is stuck at now loading?

**Comment by Masuzu** [comment]
This case is not handled very well and indicates a bad internet connection usually.

**Comment by readmynameplease** [comment]
so there is no work around for this?

**Comment by Masuzu** [comment]
It is not supposed to happen in the first place.
However, if you can tell me at which point exactly it happens (after selecting party. going to the result page, something else) I can provide some mitigations in later releases.

**Comment by readmynameplease** [comment]
Nvm I found a way to make it work just set the delay higher, and another question is it possible to use summon each time when they cooldown is gone?

**Comment by readmynameplease** [comment]
there seems to be problem still everytime I use the scheduling it doesn't follow the scheduled raids but everytime it tried to reset the summon to get the one that I want, It will count as a 1 run from the set RUNS you want tthe bot to run. like for example if you set 3 and it havent found the summon you want it will reset it then you will only have 2 runs left. does it make sense?

**Comment by readmynameplease** [comment]
and my another issue is this one after resetting to get the summon i want stuck into this 
![screenshot_4](https://user-images.githubusercontent.com/32391012/31166786-a5d95b98-a93b-11e7-94d7-106f005f98f6.jpg)

**Comment by Masuzu** [comment]
Please create another ticket as it is completely unrelated to the initial topic.
`Summon(X)` does that by default
It looks like your PC takes a lot of time to load the summon page.
Refreshing the summon page for summon selection won't work with the events requiring to navigate to the event page in the first place.
https://github.com/Masuzu/ZooeyBot/issues/347
