### ISSUE TITLE
Treasure Event mode ignoring the nightmare

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/ZooeyBot#338]
Somehow the Zooeybot keep doing the Extreme and ignoring the Nightmare. Even if I set 'NightmareAvailableAt Start' to true then start the bot, the bot doing Extreme instead of Nightmare.
Did I do something wrong?

**Comment by mdanishu** [comment]
I have the same issue

**Comment by readmynameplease** [comment]
just a question how do you guys to run the queens armor at this event? because i set the summon url on the bot but it doesnt work

**Comment by Sundaerae** [comment]
I'm not on my computer so I can't copy paste it.

Set it to treasure event mode. Set the url to the event page, difficulty to vh, ap to 20. The summon will use the summon setting on Combat segment. Hope this helps.

**Comment by readmynameplease** [comment]
that works thanks a lot man!

**Comment by readmynameplease** [comment]
@Sundaerae just another question how you do the 15 ap in treasure event mode? it seems I cant farm it

**Comment by Sundaerae** [comment]
Use the event mode for it, not treasure event.

**Comment by readmynameplease** [comment]
you reply so fast have you got any issues when using the overdrive.state command? I'm using this script everything is fine but when Beatrix uses 2nd skill for overdrive enemies, Zooey just crash 

if character_1.charge_gauge >= 100 then
  EnableChargeAttack()
else
  DisableChargeAttack()
end
if character_1.hp_percentage <=20 then
UseGreenPotionOnPartyMember(1)
end
if character_2.hp_percentage <=20 then
UseGreenPotionOnPartyMember(2)
end
if character_3.hp_percentage <=20 then
UseGreenPotionOnPartyMember(3)
end
if character_4.hp_percentage <=20 then
UseGreenPotionOnPartyMember(4)
end

-- # main character
character_1:UseSkill(2)
character_1:UseSkill(3)
character_1:UseSkill(4)

-- # Beatrix
if turn == 1 then
character_2:UseSkill(1)
character_2:UseSkill(1)
character_2:UseSkill(3)
end 

if enemy_1.overdrive_state then
  character_2:UseSkill(2)
  end

-- # Clarisse
character_4:UseSkill(1)
character_4:UseSkill(3)
-- # Grea
character_3:UseSkill(1)
if turn == 1 then
Summon (6)
end

**Comment by Sundaerae** [comment]
I don't use that function, please make a new issue about it.

**Comment by Masuzu** [comment]
@readmynameplease Stop polluting threads please.

**Comment by Masuzu** [comment]
Hi,
You need to use the Treasure Event mode to do so:
https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode
The same applies for any events which require you to have materials to host the raids.
