### ISSUE TITLE
Treasure Event mode ignoring the nightmare

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/ZooeyBot#341]
And why do you close my issue!? @Masuzu 
Just from the title you'd see that I DID use the treasure event mode AND the nightmare IN Treasure Event mode don't work.
It doesn't matter if I fill the nightmare url, it doesn't matter if I set the nightmare available at start to true (when I manually spawn that nm), the bot just skip like there is no nightmare.
THAT is my issue.
![nm](https://user-images.githubusercontent.com/31296536/31077438-b52403ee-a7a8-11e7-9b69-5ebb558f1155.png)

**Comment by himappe** [comment]
Fill in Event mode section.  
Nightmare mode URL
 And
Nightmare mode scripts

Same parameter

**Comment by Sundaerae** [comment]
So basically the bot read the nm parameter from the event mode instead of the treasure event?
Thanks! will try it later.

**Comment by Masuzu** [comment]
Sorry about that.
Actually, there is a bug which made it so that if you have the parameter NightmareMode blank (under the `EventMode` section), then TreasureEventNightmareModeUrl would be completely ignored.

**Comment by Masuzu** [comment]
Fixed in v2.0.1
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-0-1
