### ISSUE TITLE
Error on using user defined variables

### ISSUE THREAD

**Issue by Dest1nationX** [Masuzu/ZooeyBot#343]
Hi, i tried to use user defined variables for same script to make me easier manage the script for scheduling dailies. However, the bot returned error after successfully using MC's first skill. Here's the link of my script and error: https://imgur.com/a/1MBB2 Thank you!

`
if turn == 1 and character_1.charge_gauge == 100 then
  booleans["assault_time"] = true
end
if booleans["assault_time"] == nil then
  character_1:UseSkill(1):WithWaitTime(3600)
  character_1:UseSkill(2)
  character_1:UseSkill(3)
  character_1:UseSkill(4)
  characters["Jamil"]:UseSkill(1)
  characters["Jamil"]:UseSkill(2)
else
  EnableChargeAttack()
end
`

**Comment by Masuzu** [comment]
Hi,
The old syntax is deprecated.
It's `character_X:WithWaitTime(YYY):UseSkill(Z)` from now on.
