### ISSUE TITLE
Slime Coop crashes (patch 2.0.1)

### ISSUE THREAD

**Issue by fumika779** [Masuzu/ZooeyBot#344]
after complete ready screen. Bot crashes. it don't use any ability (and stuck)

1. ID Main press Ready
2. ID Secondary press start (secondary ID is Host Creep room) 
3. ID Secondary Loading 
4. ID Main Loading 
5. Secondary load is completed. 
6. Main load is completed.
7. bot crashes

![2017-10-03_090754](https://user-images.githubusercontent.com/31799116/31108170-c33063d2-a821-11e7-99f7-835ba96ce015.jpg)
![2017-10-03_091140](https://user-images.githubusercontent.com/31799116/31108171-c3362326-a821-11e7-97b8-b08a64e33045.jpg)

**Comment by Masuzu** [comment]
Hi,
Regardless of the crash which might be related to https://github.com/Masuzu/ZooeyBot/issues/345, you should **never, ever, ever** run into "Abnormal wait time" messages if you follow exactly https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)#getting-down-to-business , setting DoNotWaitForServerResponse to false as it is your case.
Bug aforementioned aside, it seems I can't stress enough the gimicky initialization **required** for the Slime blasting mode: your Summon command being ignored while it should not is the proof.

**Comment by fumika779** [comment]
@Masuzu thank for advice  
I will check that.

however My initial time is as same as I use before (1.12-1.22) 
I will check it again as soon as possible

**Comment by Masuzu** [comment]
The version 2.0.1 is bugged in any case :(
You should not use it until I fix it (later today/tomorrow). I will take the change to check again the slave mode.

**Comment by Masuzu** [comment]
Fixed in v2.0.2 https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-0-2
Please note that if you use the v2.0.0 you will run into some of the issues which would cause crashes after using some abilities. v2.0.2 includes a fix for these issues as well as this ticket.

**Comment by fumika779** [comment]
it's fixed in 2.0.2

Thank For hardwork

**Comment by Masuzu** [comment]
Nice :)
