### ISSUE TITLE
Crash after 1st attack

### ISSUE THREAD

**Issue by WildKaiser** [Masuzu/ZooeyBot#345]
![screenshot 2017-10-03 14 55 28](https://user-images.githubusercontent.com/22787581/31113287-1dc5ceda-a84b-11e7-951b-524d1e921507.png)

As seen above, after the first attack, the bot crashes. I just updated to the latest 2.0.1 too. The following is what I used to farm the items for the event. 

> [EventMode]
> Set this parameter to true to use the event mode. Zooey will enter autopilot mode when you navigate to the quest menu.
> Enabled=true
> Url of the summon selection page.
> EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/722981/3
> EventRaidScript=
> Url of the summon selection page for Nightmare level 100 mode.
> NightmareModeUrl=
> NightmareModeScript=
> Some events such as Rise of the Beasts require to navigate to the home page of the event before navigating to the event raid url defined above. If EventPageUrl is provided, Zooey will first navigate to this url before hosting the raid. Leave EventPageUrl blank for events which do not require you to do so.
> EventPageUrl=http://game.granbluefantasy.jp/#event/treasureraid060

Any help will be appreciated

**Comment by Arohe** [comment]
I have also been having this problem when trying to do any quest. Is it a problem with the update? This is my first time using the software.
![pic 2](https://user-images.githubusercontent.com/32477518/31113611-19f8164a-a7e8-11e7-842a-32ebe92e1a3e.png)

**Comment by Masuzu** [comment]
Hi, do you still have the same issue with v2.0.0 (https://github.com/Masuzu/ZooeyBot/releases/tag/2.0.0)?
I will fix this within 24 hours.

**Comment by Masuzu** [comment]
Never mind, you do not need to test, I identified the issue which resulted in this crash :|
I will provide a patch for this specific issue in 12 hours or so from now.
I apologize for the inconvenience.
![](https://gbf.wiki/images/0/0f/Stamp17.png)

**Comment by WildKaiser** [comment]
Thank you for the quick response. Yes 2.0.0 works fine so there's no inconvenience. Thanks again

**Comment by Masuzu** [comment]
Fixed in v2.0.2 https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-0-2
Please note that if you use the v2.0.0 you will run into some of the issues which would cause crashes after using some abilities. v2.0.2 includes a fix for these issues as well as this ticket.
