### ISSUE TITLE
Stuck at this page after resetting summon

### ISSUE THREAD

**Issue by readmynameplease** [Masuzu/ZooeyBot#348]
http://prntscr.com/gt4i8x

**Comment by Masuzu** [comment]
Oh, the issue is different than what I initially thought. https://github.com/Masuzu/ZooeyBot/issues/347
You lag like hell, that is the only reason why it could happen.
I will take note of this rare issue though for the future releases.

**Comment by readmynameplease** [comment]
it seems like its able to put the link but did not able to press enter to get into link

**Comment by Masuzu** [comment]
The problem is that Zooey failed to retreat from the trial battle.

**Comment by readmynameplease** [comment]
yeah. btw thanks for being so active and keeps updating the bot it's a big help

**Comment by readmynameplease** [comment]
@Masuzu  stuck at this page its not clicking retreat anymore after the update
![stuck](https://user-images.githubusercontent.com/32391012/31364356-ea0ed0ea-adaf-11e7-9bff-94d400a4444d.jpg)

**Comment by Masuzu** [comment]
Oh ok, I will look into it later today. It is a bug it seems.

**Comment by readmynameplease** [comment]
yeah it's a big bug preventing the bot to keep running

**Comment by Masuzu** [comment]
You can still use v2.0.2 in the meantime

**Comment by readmynameplease** [comment]
just a suggestion when rerolling for summon instead of putting a link to retreat how bout just click menu then just click retreat I think that will be a lot easier and will be fail proof @Masuzu

**Comment by Masuzu** [comment]
Tomorrow or a bit later this week, I will just release a bugfix for the reported issue for now.
