### ISSUE TITLE
Bot says I am an unlicensed user

### ISSUE THREAD

**Issue by Arohe** [Masuzu/ZooeyBot#349]
When I try to start the bot it will tell me I am unregistered despite my license not ending until November. My key file is the same as my serial number. I can PM you my serial number if you'd like. 
![image](https://user-images.githubusercontent.com/32477518/31181504-85066d62-a8ef-11e7-8d66-2df2adce9ff9.png)

**Comment by Masuzu** [comment]
Hi,

How many times do I have to say that PEOPLE SHOULD NEVER MODIFY THEIR KEY FILE but should just download it.
The contents of the serial number.txt file created at start up has to match the one on the management page. If not copy and paste the contents of that file in the management page.

**Comment by Arohe** [comment]
Hi! Sorry for the post, I ended up finding out what was wrong, since I realized I never edited the key file. I switched computers and as such my serial numbers weren't matching. I have to wait a few days to change it but afterwards it should be fine. ^^" I apologize.
