### ISSUE TITLE
Lua script commands attempted but fail

### ISSUE THREAD

**Issue by AshkanZirakzadeh** [Masuzu/ZooeyBot#35]
My ZooeyBot attempts to run the commands as per my Lua script, but the mouse cursor just moves a few pixels and then does nothing.

I am using Viramate and have set UseViramate=true.

**Comment by Kentiah** [comment]
If you want to use viramate, I think you need to enable hotkeys under viramate. However, you can also try with viramate disabled.

**Comment by AshkanZirakzadeh** [comment]
Yep I just figured this out while I was playing around with setting

It would be nice to add a note that the bot attempts to use the hotkeys by default if viramate is ON.
