### ISSUE TITLE
Custom scaling 

### ISSUE THREAD

**Issue by Bakamoto** [Masuzu/ZooeyBot#352]
Is there a way to set custom scaling instead of having it set to 100% like in previous versions? Sometimes the mouse misses the html bar at the top by a millimeter and my web browser icons are super small haha

**Comment by Masuzu** [comment]
Hi,
I have no plan to support such feature.
That's a first. Could you please send a screenshot of your Chrome window with the navigation bar visible?
Here is what mine looks like ![](https://i.imgur.com/7e41EeV.png)
By the way, never use full screen.
