### ISSUE TITLE
Bot sometimes missess Start button in Co-op missions on 1366 x 768 screen resolution

### ISSUE THREAD

**Issue by prokopets** [Masuzu/ZooeyBot#353]
Hi!
I am playing on my laptop and max resolution for me is 1366 x 768. When bot takes control of mouse in coop quest, he sometimes press my page instead of Start button.
So this is how my screen looks, a dont really know how bot missess this click...
![eo-km4y2lf8](https://user-images.githubusercontent.com/22854160/31311197-da7159ca-abaf-11e7-99b5-f074d9397fce.jpg)
Bottom line with Start button is already moved to the right

**POSSIBLE SOLUTION.** 
As far as i remember, you added a little scrolling on page when Start button is needed to be clicked for regular quests, maybe you can add something like this here. Thanks in advance!

**Comment by Masuzu** [comment]
Hi,

768 is pretty small as for the height and most laptop offer a 1920x1080 resolution nowdays.
I take this point into account though to "try and avoid" clicking on the My page button.

**Comment by Masuzu** [comment]
Mitigation added in v2.0.3
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-0-3
