### ISSUE TITLE
The bot sometimes clicking the bottom left corner?

### ISSUE THREAD

**Issue by salvanost** [Masuzu/ZooeyBot#356]
Why the bot sometimes to go to bottom left corner?
Looks like it to "clear netwirk request"?

The bot go to left bottom then Click once before back to the browser and continue with the farm

It clicking the windows icon and making the sidebar appear and hindrance the browser (want to click chara no 1 and no 2 position but cannot because the side bar)

Out topic:
Using 2gb RAM notebook
The bot frequently error and stop working suddenly, anither issue when the RAM reach 93% the harddisk suddenly go to 100% make the browser lag so much

Upgrade to 4GB RAM without above issue

**Comment by salvanost** [comment]
Update:
The bot still stop working after upgrade to 4 gb
Stop at the

Battle 1 turn 1
Cheking wheter the battle already ended

**Comment by arthurneo** [comment]
that happened to me because of scaling issues.
apparently my browser setting was large and had auto resizing on which caused the same problem.

**Comment by salvanost** [comment]
https://github.com/Masuzu/ZooeyBot/issues/234
maybe the ping / connection not good

i will change my connection

**Comment by salvanost** [comment]
> that happened to me because of scaling issues.
> apparently my browser setting was large and had auto resizing on which caused the same problem.

-------------------------
my zooey bot stop at random duration from 5 minutes the shortest to around 1 hour

**Comment by salvanost** [comment]
nope, still error
https://s1.postimg.org/65u89hqebj/error.jpg

**Comment by salvanost** [comment]
New problem
The bot closed after finish the dimensional nightmare

**Comment by Masuzu** [comment]
Hi,

If it stops randomly it may be due to poor connection due to some mechanism implemented, I had it a while due to DNS issues. I doubt it is due to a bug as none of them were reported lately.
If you have a flaky Internet connection then I am afraid you will constantly run into this kind of errors resulting in a crash.

**Comment by Masuzu** [comment]
As for the click on the left corner that's right. Make sure to set `ChromeDevToolsWindowDockedOnTheRight` properly as indicated in the first messages in the console window, and to have the Network tab active in your DevTools console as mentioned in the getting started guide.

**Comment by salvanost** [comment]
Weird
No error when farming sakura event...

I will update again later...
