### ISSUE TITLE
script for dimension halo

### ISSUE THREAD

**Issue by ummokay** [Masuzu/ZooeyBot#357]
Complete scrub here, charas used are CR, djeanne, BK, and Zoi. Not sure how to do this, script isn't working. Also how can i make it so zoi(character 4) uses her skills at enemy 50% hp?

>   Summon(6)
>   character_2:UseSkill(2)
>   character_1:UseSkill(2)
>   character_1:UseSkill(3)
>   character_2:UseSkill(1)
>   character_1:UseSkill(4)
>   character_3:UseSkill(3)
>   character_2:UseSkill(1)
>   character_4:UseSkill(2)
>   character_4:UseSkill(1)
>   character_4:UseSkill(3)
>   character_2:UseSkill(3)
> end

**Comment by salvanost** [comment]
use this as reference
my dimensional lua,
team of sage, dark jeanne, vira, zoi, katalina

if turn == 1 then
  DisableChargeAttack()
  character_1:UseSkill(2)
  character_1:UseSkill(3)
  character_1:UseSkill(4)
  character_2:UseSkill(2)
  Summon(1)
end

if turn == 2 then
  character_2:UseSkill(4)
end

if turn == 3 then
  character_1:UseSkill(3)
end

if turn == 4 then
  Summon(6)
  EnableChargeAttack()
  character_2:UseSkill(1)
  character_4:UseSkill(2)
  character_4:UseSkill(1)
  character_4:UseSkill(3)
  character_1:UseSkill(2)
end

if turn == 5 then
  Summon(2)
  character_2:UseSkill(2)
  character_2:UseSkill(1)
  character_2:UseSkill(3)
  character_2:UseSkill(3)
  character_1:UseSkill(2)
end

if turn == 6 then
  character_1:UseSkill(3)
  character_1:UseSkill(1)
end

if turn == 7 then
  character_2:UseSkill(2)
  end

if turn == 8 then
  character_1:UseSkill(4)
end

if turn == 9 then
  character_1:UseSkill(3)
end

if turn == 10 then
  Summon(5)
  character_2:UseSkill(1)
  character_4:UseSkill(3)
  --[[jeanne mati ganti katalina]]--
  characters["Katalina"]:UseSkill(1)
  characters["Katalina"]:UseSkill(2)
  character_1:UseSkill(2)
end

if turn ==11 then
  Summon(4)
  character_1:UseSkill(1)
  characters["Katalina"]:UseSkill(3)
end

if turn ==12 then
  Summon(3)
  character_1:UseSkill(3)
  character_4:UseSkill(1)
end

if turn ==13 then
  Summon(6)
  character_3:UseSkill(3)
end

if turn ==14 then
  Summon(1)
  characters["Katalina"]:UseSkill(3)
  character_3:UseSkill(2)
  character_1:UseSkill(2)
  character_1:UseSkill(3)
  character_1:UseSkill(4)
end

if enemy_1.hp_percentage < 50 then
  if character_1.hp_percentage < 30 then
    UseGreenPotionOnPartyMember(1)
  end
  if character_3.hp_percentage < 30 then
    UseGreenPotionOnPartyMember(3)
  end
  if character_4.hp_percentage < 30 then
    UseGreenPotionOnPartyMember(4)
  end
end

**Comment by salvanost** [comment]
U need to speculate to the longest turn available
My previous lua script end after 13 turn and the bot error at turn 14...

**Comment by ummokay** [comment]
making a template with that worked, thanks!
