### ISSUE TITLE
Scheduled Raid attempt count incorrect

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/ZooeyBot#358]
So I have this script that runs tiamat and leviathan 3 times
Leviathan - 3 runs
Tiamat - 3 runs

For some reason it runs like this
Leviathan - 2 runs
Tiamat - 4 runs 

and thus throwing error cause it exceeds the limit. This could be related to the issue where it was treating trial mode as 1 run?

**Comment by Masuzu** [comment]
Hi,
This is a known bug.

**Comment by breinjhel** [comment]
Thanks sir

**Comment by Masuzu** [comment]
https://github.com/Masuzu/ZooeyBot/issues/362
The fix will be delayed, sorry about this.

**Comment by breinjhel** [comment]
Hi can we atleast get a fix for this. Its really frustrating always restarting and updating schedule.lua everytime an error occurs

**Comment by Masuzu** [comment]
Hi,

It should be addressed in v2.1.0 https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes

**Comment by breinjhel** [comment]
Nice Thanks!
