### ISSUE TITLE
Suggestion: Auto Join raids

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/ZooeyBot#359]
It would be great addition to have a feature that automatically joins raids and just looks for it in via twitter api. Would pay more for that

**Comment by salvanost** [comment]
chance banned for 3 hour for leeching too much raid
cmiiw

**Comment by readmynameplease** [comment]
this will be so awesome. during the magnafest everything will be a breeze

**Comment by LordShade** [comment]
I am pretty sure Masuzu said such a feature would not come to the bot ever. Reasons I do not know why.

**Comment by Masuzu** [comment]
Hi,
If I release such a feature it will be a under a different licence.

**Comment by readmynameplease** [comment]
that will be fine by me as long as we have Auto raid to help ease the farming raids for weapons then im all in @Masuzu

**Comment by Masuzu** [comment]
サラーサボット is on the way~

**Comment by breinjhel** [comment]
Nice!!!!
