### ISSUE TITLE
privacy

### ISSUE THREAD

**Issue by 1uminated** [Masuzu/ZooeyBot#36]
could you add a bit of privacy for ur website so ur website isnt a simple google search and click to access? i run my own "coop botting program" but always kept it to a close circle because giving the public access just leads the devs to take more serious notice of botting issues. ie if they cant fix it outright they might remove ap/ep drops. just saying

**Comment by Kentiah** [comment]
Sounds good for a user, but not great for someone trying to make money off of it. Hopefully the monthly "buy in" will be enough to keep the masses from making it an issue, which I guess is also not great for business, but yeah, as users we definitely want that sweet spot of getting to use the bot without the company thinking we're an issue.
