### ISSUE TITLE
Attempt to call a nil value

### ISSUE THREAD

**Issue by GBFThrowaway** [Masuzu/ZooeyBot#360]
In scheduling my raids I'm trying to make it so that Luna uses Soul Conversion on position one but I keep getting the same error.

```
if turn == 1 then
	characters["Luna"]:UseSkill(1):OnPartyMember(1)
	character_4:UseSkill(2)
	character_4:UseSkill(3)
	character_4:UseSkill(1)
end
```

I also tried`
character_3:UseSkill(1):OnPartyMember(1)`
but I get the same result. It seems to be the same issue as #305 .

**Comment by Masuzu** [comment]
Hi,
You're using the old syntax.
Everything changed since the release of v2.0 and the wiki was updated accordingly:
character_3:OnPartyMember(1):UseSkill(1)
