### ISSUE TITLE
Crash on start battle screen

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#365]
Using 2.0.4.

Let me know if there's any more information I can provide

![windows10_16_10_2017_01_12_48](https://user-images.githubusercontent.com/32204823/31596275-63471842-b20f-11e7-9d02-ef4f0ea6b3e2.png)

**Comment by thebp2** [comment]
I reverted back to 1.22.2 and it's working fine for now.

**Comment by Masuzu** [comment]
Too isolated to reproduce. Never had this one before. I will take note of it though.

**Comment by thebp2** [comment]
Is there a way to get a stack trace with better information for you? It's crashing there very reliably for me.

**Comment by readmynameplease** [comment]
yeah this is getting bit frustrating as yo cant bot for more than 1 hour

**Comment by thebp2** [comment]
Crash Report from windows Event Log:
Faulting application name: ZooeyBot.exe, version: 0.0.0.0, time stamp: 0x59dd10c8
Faulting module name: ZooeyBot.exe, version: 0.0.0.0, time stamp: 0x59dd10c8
Exception code: 0xc0000094
Fault offset: 0x00077dc5
Faulting process id: 0x10cc
Faulting application start time: 0x01d34af52d5a4657
Faulting application path: R:\ZooeyBot.exe
Faulting module path: R:\ZooeyBot.exe
Report Id: 3c90a44c-d95b-43f2-a6f7-80f9011a8b90
Faulting package full name: 
Faulting package-relative application ID:
