### ISSUE TITLE
Struck with a temp-hour ban after grinding the Cardcaptor event for a bit

### ISSUE THREAD

**Issue by Anontastic** [Masuzu/ZooeyBot#368]
I just updated to 2.04 after holding onto an older version for a while, and for the first time since I started using Zooey in July, I got hit with a temporary 3-hour ban after using Zooey to grind materials from the current story event.

I recognize that this may be well within the realm of expectation, and I just coincidentally got unlucky after updating, but I just want to make sure no one else is experiencing similar issues before I touch the bot again. For the time being, I'm going to roll back my version of the bot to the one I had before.

**Comment by breinjhel** [comment]
Did you miss a captcha?

**Comment by Masuzu** [comment]
^
