### ISSUE TITLE
Bookmarkbar

### ISSUE THREAD

**Issue by Cortez555** [Masuzu/ZooeyBot#370]
I wanted to try your Zooeybot out on some Angel Halo. At first I was kinda confused why the bot keeps pressing other tabs for no reason. After a bit I closed my bookmarkpage and retried it. It worked fine so I guess the bar is not supported. Which is not really an Issue, but it would be a nice hint on the FAQ Page or the Getting started Page.

Thanks for your hard work.

**Comment by HariboApfel** [comment]
i am not having this issue with google chrome, which browser are u using?

**Comment by Masuzu** [comment]
Hi,
It works fine on my side with or without the bookmark bar.
