### ISSUE TITLE
rise of the beasts

### ISSUE THREAD

**Issue by worthworth** [Masuzu/ZooeyBot#372]
Can I farming EX+ on Rise of the beasts?
my zooey farming Ex only...
```
# Set this parameter to true to use the event mode. Zooey will enter autopilot mode when you navigate to the quest menu.
Enabled=true
# Url of the summon selection page for the Angel Halo
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/711141/1
EventRaidScript=Scripts/EX.lua
# Url of the summon selection page for the Dimension Halo
NightmareModeUrl=http://game.granbluefantasy.jp/#quest/supporter/711151/1/0/5017
NightmareModeScript=Scripts/titan.lua
# Some events such as Rise of the Beasts require to navigate to the home page of the event before navigating to the event raid url defined above. If EventPageUrl is provided, Zooey will first navigate to this url before hosting the raid. Leave EventPageUrl blank for events which do not require you to do so.
EventPageUrl=http://game.granbluefantasy.jp/#event/advent017
# Comma-delimited list of summons which will be selected in priority if they are available for the nightmare mode.
# In case none of the preferred summons was found, select a random summon in the summon attribute tab defined by the parameter DefaultSummonAttributeTab, unless the parameter RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode is set to true.
NightmareModePreferredSummons=Tiamat Omega_1
# Zooey will reroll summons until one of the preferred summons for the nightmare mode is available, using trial battles to refresh the summon list.
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
# Set this parameter to true if the nightmare mode is available when you start Zooey so she can proceed to the nightmare stage right ahead.
NightmareModeAvailableAtStart=false
# Wait time in milliseconds after Zooey finishes loading the EventPageUrl
WaitTimeInMsAfterEventPageIsLoaded=1500
```

**Comment by HariboApfel** [comment]
`you` can only run the NM that is currently in the ROB rotation.

for the wind rotation i use these settings and they work.

<code>[EventMode]
# Set this parameter to true to use the event mode. Zooey will enter autopilot mode when you navigate to the quest menu.
Enabled=true
# Url of the summon selection page for the Xeno Sagittarius Extreme mode.
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/711091/1
EventRaidScript=Scripts/robgeneral.lua
# Url of the summon selection page for the Xeno Sagittarius Nightmare level 100 mode.
NightmareModeUrl=http://game.granbluefantasy.jp/#quest/supporter/711101/1/0/5017
NightmareModeScript=Scripts/robgeneral.lua
# Some events such as Rise of the Beasts require to navigate to the home page of the event before navigating to the event raid url defined above. If EventPageUrl is provided, Zooey will first navigate to this url before hosting the raid. Leave EventPageUrl blank for events which do not require you to do so.
EventPageUrl=http://game.granbluefantasy.jp/#event/advent017
# Comma-delimited list of summons which will be selected in priority if they are available for the nightmare mode.
# In case none of the preferred summons was found, select a random summon in the summon attribute tab defined by the parameter DefaultSummonAttributeTab, unless the parameter RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode is set to true.
NightmareModePreferredSummons=Bahamut
# Zooey will reroll summons until one of the preferred summons for the nightmare mode is available, using trial battles to refresh the summon list.
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
# Set this parameter to true if the nightmare mode is available when you start Zooey so she can proceed to the nightmare stage right ahead.
NightmareModeAvailableAtStart=true
# Wait time in milliseconds after Zooey finishes loading the EventPageUrl
WaitTimeInMsAfterEventPageIsLoaded=1000
</code>

**Comment by sellsell** [comment]
For me Zooeybot only runs the NM stage if I set the "NightmareModeAvailableAtStart" parameter to true and even then the bot will only clear the NM once and then continue to farm Extreme forever. If "NightmareModeAvailableAtStart" is set to false then Zooey will just farm Extremes forever and ignore the NM stage completely.

**Comment by YobiMyszkowski** [comment]
same as @sellsell cant make zooi to start nm :(
