### ISSUE TITLE
Summons spelling

### ISSUE THREAD

**Issue by Ramkm77** [Masuzu/ZooeyBot#373]
Hi , usually do bahamut and hades . But Celeste never work . Can u gives the right spelling for Celeste summon . I do Celeste or Celeste_1

Thx

**Comment by HariboApfel** [comment]
Celeste Omega

**Comment by Ramkm77** [comment]
I did 
Bahamut, Celeste Omega

Still do only baha and never choose Celeste if no baha

**Comment by Masuzu** [comment]
Hi,
Remove the space after the comma ','
