### ISSUE TITLE
2.1.0 the first scheduling has 1 extra count

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/ZooeyBot#375]
When I use this line on scheduling: (adversa hard)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300221/1", 15, 3)
Zooeybot will try to enter the quest for the 4th time, whereas I only ask for 3 times, resulting in error

When I use these lines: (celeste hard to tiamat hard)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300251/1", 15, 2)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300191/1", 15, 2)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300151/1", 15, 2)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300091/1", 15, 2)
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/300041/1", 15, 2)
Zooeybot will do Celeste 3 times, and the rest 2 times

**Comment by breinjhel** [comment]
Yes I can reproduce this too. And also this issue
https://github.com/Masuzu/ZooeyBot/issues/358

**Comment by Masuzu** [comment]
Hello,
Thanks for reporting this

**Comment by Masuzu** [comment]
This should be fixed in v2.1.2

**Comment by breinjhel** [comment]
Is this really fixed? I just updated and issue still there
