### ISSUE TITLE
vh for Forgiveness and Gratitude won't select a summon.

### ISSUE THREAD

**Issue by ericli51** [Masuzu/ZooeyBot#378]
Hello, I'm trying to use the treasure event mode for the current Yuel/Sochie event, but it seems like they changed the requirements for the Very Hard raid to no longer require mats like previous end-of-the-month events (so there's no longer any pop-up prompt to confirm using the VH mats).

Would this be causing a bug with zooeybot's TreasureEventMode? I'm trying to automate VH but it keeps freezing at the summon select page (navigates to the page and event just fine though)

Edit: the Extreme raid works like a charm.

**Comment by Masuzu** [comment]
Please refer to https://github.com/Masuzu/ZooeyBot/issues/379 but I am sure you have figured it out already :)
