### ISSUE TITLE
"error loading extension"

### ISSUE THREAD

**Issue by gakurans** [Masuzu/ZooeyBot#38]
casinobot is fine but when i try to use zooey this happens?
![untitled](https://cloud.githubusercontent.com/assets/28652765/26000806/54ff2622-36f8-11e7-9b6f-76c30c7ffe94.png)

**Comment by Masuzu** [comment]
Tested with the latest Chrome ![](https://i.imgur.com/f5YTF3C.png) and could not reproduce the issue.
Could you please post here the whole contents of your manifest.json file?

**Comment by gakurans** [comment]
{
  "name": "GBF Poker Advisor",
  "version": "1.0.0",
  "manifest_version": 2,
  "devtools_page": "devtools/devtools.html",
  "browser_action": {
    "default_icon": "icon.png",
    "default_popup": "popup.html"
  },
  "background": {
    "scripts": [
      "js/zooey-util.js",
      "js/zooey-websocket-request.js",
      "background.js"
    ]
  },
  "permissions": [
    "activeTab",
    "http://game.granbluefantasy.jp/*"
  ],
  "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"
}

**Comment by Masuzu** [comment]
This is the manifest.json file of the GBFPoker bot advisor.
In any case, I can't reproduce the issue and you seem to be the only one in this case 🤔

**Comment by gakurans** [comment]
my apologies



{
  "name":"Zooey Bot",
  "version":"1.0.0",
  "manifest_version":2,
  "devtools_page":"devtools/devtools.html",
  "browser_action":{
    "default_icon":"icon.png",
    "default_popup":"popup.html"
  },
  "background":{
    "scripts":[
      "third_party/jquery-3.1.1.min.js",
      "js/zooey-util.js",
      "js/zooey-websocket-request.js",
      "background.js"
    ]
  },
  "permissions":[
    "activeTab",
    "http://game.granbluefantasy.jp/*"
  ],
  "content_security_policy":"script-src 'self' 'unsafe-eval'; object-src 'self'"
}

**Comment by gakurans** [comment]
note: the slave extension loads up fine, just not the main zooey bot

**Comment by gakurans** [comment]
you have to pay separately for zooey and the poker simulator? i never got to use my trial for zooey

**Comment by gakurans** [comment]
the new version of zooeybot works without problem
i don't know what the problem was
since i downloaded it for the very first time just this morning from the link on the website...

thank you for your time
