### ISSUE TITLE
Tries to set #coopraid in main window during slave sliming

### ISSUE THREAD

**Issue by Broppler** [Masuzu/ZooeyBot#381]
I believe I have followed the guide to the letter and it works fine all the way through calibrating both windows but after I press enter to start auto-piloting the first thing it does is hover up to the adress bar of the main window and try to set it to "http://game.granbluefantasy.jp/#coopraid", the game quickly corrects this into "http://game.granbluefantasy.jp/#coopraid/room/(room ID)" and as soon as the game adds the Room ID Zooey accepts the challenge and tries to change it back to just "http://game.granbluefantasy.jp/#coopraid"

I assumed there was something in the .ini but I can't seem to find anything. After that I noticed that I had Viramate going on my main account only and thought that the fact that viramate displays the menu differently made Zoeey think that I wasn't in the coop-lobby. I disabled viramate but the problem remains.

**Comment by Masuzu** [comment]
Hi,
After pressing ENTER with the slime mode, the first things Zooey will try to do is to try and press the Ready button on the slave account. If you already pressed it before, then Zooey will keep refreshing the slave window page ad vitam æternam, as seems to be described.

**Comment by Broppler** [comment]
Yeah that was it. Oh man. Embarrassing. Thank you for your time.
