### ISSUE TITLE
[TLDR: misconfigured ZooeyBot.ini] Issue when using custom script for GW

### ISSUE THREAD

**Issue by Dekiimasen** [Masuzu/ZooeyBot#383]
![image](https://user-images.githubusercontent.com/33460937/32604556-002fdbc6-c589-11e7-8120-26f5b295b69e.png)
Using this team, i always get a issue where the skills don't get used and instead gives me a issue about parse ability. Code below

character_1:UseSkill(1)
character_1:UseSkill(2)
character_1:UseSkill(4)
character_2:UseSkill(1)
character_2:UseSkill(3)
character_2:UseSkill(2)
character_1:UseSkill(3)
character_3:UseSkill(1)
character_3:UseSkill(3)
character_3:UseSkill(2)
character_3:UseSkill(1)
character_4:UseSkill(1)
character_4:UseSkill(2)
Refresh()

**Comment by Dekiimasen** [comment]
EnableChargeAttack()
character_1:UseSkill(1)
character_1:UseSkill(2)
character_1:UseSkill(4)
characters["Altair"]:UseSkill(1)
characters["Altair"]:UseSkill(3)
characters["Altair"]:UseSkill(2)
character_1:UseSkill(3)
characters["Owen"]:UseSkill(1)
characters["Owen"]:UseSkill(3)
characters["Owen"]:UseSkill(2)
characters["Lily"]:UseSkill(1)
characters["Lily"]:UseSkill(2)
Refresh()
changing it to something like this also dosen't work, am i doing something wrong here or?

**Comment by Masuzu** [comment]
Hi,

Everything seems fine for me.
Did you make sure to encode your file as UTF8 ?
![](https://i.imgur.com/qasr2Zd.png)

**Comment by Dekiimasen** [comment]
OH YOU NEEDED TO DO THAT? HAHAHA sorry my bad, i'm still new to this uwu

**Comment by Dekiimasen** [comment]
I'll give it a try again and keep you updated o/

**Comment by Dekiimasen** [comment]
![2017-11-10_02-44-24](https://user-images.githubusercontent.com/33460937/32623566-95a1e5d6-c5c1-11e7-8700-d19316ecce3b.png)
Still dosent work

**Comment by Dekiimasen** [comment]
![image](https://user-images.githubusercontent.com/33460937/32623677-e8bd62ea-c5c1-11e7-8e08-7cc3eafd549e.png)

**Comment by salvanost** [comment]
If the lua script works on turn 1

Maybe your problem come from the refresh / reload
Slow connection maybe

Look at zooey bot setup
# This saves up some precious seconds and that is what every MVP racer does.
ReloadPageOnLastBattle=true
Change the true to false

**Comment by Masuzu** [comment]
Oh it's simply that you misconfigured you ZooeyBot.ini file.
The script is not even loaded as shown in the console.
Could you post your ZooeyBot.ini contents?

You need to update the Combat section LuaScript parameter.

**Comment by Dekiimasen** [comment]
I'm not at home currently but I've listed the script as WaterGW.lua in the events section

**Comment by Dekiimasen** [comment]
https://pastebin.com/Ndx2j8Uc
sent my zooeybot ini file here

**Comment by Dekiimasen** [comment]
![2017-11-10_22-15-39](https://user-images.githubusercontent.com/33460937/32662345-29e5bb02-c665-11e7-8b76-e9f36681a491.png)

**Comment by Dekiimasen** [comment]
Nevermind, solved it! Sorry for the trouble, i’m still new to this 😂

**Comment by Masuzu** [comment]
Good to hear!
