### ISSUE TITLE
Unable to start ZooeyBot

### ISSUE THREAD

**Issue by YeezysOwo** [Masuzu/ZooeyBot#385]
Renewed licence for this month but as I try to run it, it says it's unregistered user - even though I keep copying/pasting the serial ID I see on my "manage accounts" window, it keeps resetting to a different one that I can't change to as the token is taken - it keeps resetting.

![image](https://user-images.githubusercontent.com/33522475/32614300-a1b43e88-c575-11e7-8315-acc77bc0ffc5.png)

**Comment by Masuzu** [comment]
Hi,

I am afraid and I can't do anything if you shared your serial number with someone else in the past.
There is also this option to retrieve the email associated with a serial number too:
https://poker-bot.azurewebsites.net/en/Account/ForgotEmail

**Comment by YeezysOwo** [comment]
Didn't share it with anyone else. It's using serial number of a different account that has the license inactive, but I renewed license on another one, though not letting me changing it in any way.

**Comment by Masuzu** [comment]
There is no licence transfer feature for now.
An option would be to change the serial number on the inactive account to some gibberish serial number to make it available again for the account where your licence is active.

**Comment by YeezysOwo** [comment]
I see, looks like solution. Just need to wait 4 days now then, I suppose.

**Comment by Masuzu** [comment]
I'll lift the limitation for the GW.
