### ISSUE TITLE
Zoey bot keeps clicking on the very edge of the address bar....

### ISSUE THREAD

**Issue by whyiseveryusernamealreadytaken** [Masuzu/ZooeyBot#386]
![image](https://user-images.githubusercontent.com/29005374/32616819-9a50d7c0-c573-11e7-90ae-4eb63ae712a5.png)
Keeps clicking inside the red box, thus not being able to paste the link for the event raid it's supposed to farm...

![image](https://user-images.githubusercontent.com/29005374/32616927-e790e5f2-c573-11e7-9845-8118ede3c128.png)
Size of the "screen"

**Comment by Dest1nationX** [comment]
Try using Chrome without fullscreen, so the address bar position got a bit lower

**Comment by MasuzuN** [comment]
Hi, 
Please never use a full screen window. It should be stated in the getting started guide.
