### ISSUE TITLE
Share your experience with captcha

### ISSUE THREAD

**Issue by salvanost** [Masuzu/ZooeyBot#387]
Well this week i got 2 captcha
1 after playing poker for 4 hours 
1 after farming meat at UnF for 3,5 hours

Anyone got the captcha popups after playing for more than 3 hours?

**Comment by Masuzu** [comment]
From personal experience and several hours in a row per day of automating my raids over several months:
As for raids, it depends on how many raids you hosted in the given time span.
Hosting 50 raids in the span of 3 hours is not the same as hosting 50 raids in the span of 30 minutes for instance.

**Comment by whyiseveryusernamealreadytaken** [comment]
Personally, when I used zoey bot to farm meat last GW (60s per ex+) I got captcha every 2 hours. Pretty annoying when i left the bot on at night, got woken up every 2 hours :D
