### ISSUE TITLE
Stuck at "waiting for last turn to be processed" when using items after C.A

### ISSUE THREAD

**Issue by lyhonlam** [Masuzu/ZooeyBot#388]
My zooey often get stuck when it try to use items after C.A. I changed delay after chainburst to very high but its still happen.
AdditionalDelayInMsAfter2ChainBurst=6000
AdditionalDelayInMsAfter3ChainBurst=14000
AdditionalDelayInMsAfter4ChainBurst=25000
AdditionalDelayInMsAfterOverchainBurst=25000

**Comment by Masuzu** [comment]
Hi,
That is really weird indeed. Instead of using items, does it get stuck too when you try to use a skill?
I could not reproduce the issue so far.

**Comment by lyhonlam** [comment]
There's no problem with using skills, it just click ok and continue working. But in case of using items, the mouse move to heal button first then then "waiting for last turn to be processed" box pop on and it just stuck there.

**Comment by Masuzu** [comment]
https://github.com/Masuzu/ZooeyBot/issues/392

**Comment by Masuzu** [comment]
Fixed in v2.1.1
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-1-1
