### ISSUE TITLE
Hangs on calibrating step

### ISSUE THREAD

**Issue by mustangfan76** [Masuzu/ZooeyBot#39]
Ever since upgrading to 1.3.1 the bot gets stuck on the calibrating phase after hitting enter once the master and slave accounts have been activated. I've tried refreshing the page or manually starting the quest and the bot never attempts to start.

Thanks.

**Comment by Masuzu** [comment]
Assuming that your scaling settings are correct, if you do not pass the 6/6 initialization phase then the calibration will never complete.
It looks similar to https://github.com/Masuzu/ZooeyBot/issues/37
