### ISSUE TITLE
About the skill delay time of slave mode

### ISSUE THREAD

**Issue by Inroi** [Masuzu/ZooeyBot#390]
Hi Masuzu.

I'm right using the slave mode, but I found my skill casting speed is slower than your demo.

I've set MinWaitTimeInMsAfterAbility as 10 but it still get like 1 second delay after the slaver cast the skill then my main account would cast.

I'm using viramate BTW.

Thanks for reply :)

**Comment by Inroi** [comment]
I've solved the issue.

**Comment by Masuzu** [comment]
Good to hear then!
Values are in milliseconds.
