### ISSUE TITLE
Revival potion during GW

### ISSUE THREAD

**Issue by Garnetus** [Masuzu/ZooeyBot#391]
Hi.
Just a quick question...trying to use revival potion with "userevivalpotion", but the bot can't recongnize it. Am I doing something wrong or the bot just can't use revival potion atm?

**Comment by Masuzu** [comment]
Hi,
No it is not supported yet. I assume that your party has to be strong enough to clear the raid already.

**Comment by Garnetus** [comment]
Ok, thanks, just want make sure :)
