### ISSUE TITLE
F.O buffs NOT working when zoey bot starts a battle.

### ISSUE THREAD

**Issue by whyiseveryusernamealreadytaken** [Masuzu/ZooeyBot#393]
Saw another post that was dismissed as invalid but it's not. Manually hosting an EX+ while F.O buff is active gives me 65% charge bar at the start of the battle (Charlotta backline for +5%) while I only start with 35% when zoey bot hosts an EX+.
![image](https://user-images.githubusercontent.com/29005374/32690345-90179bf8-c6f5-11e7-8812-d6c9ce79addc.png)

MANUAL host:
![image](https://user-images.githubusercontent.com/29005374/32690348-a7c25d10-c6f5-11e7-8eff-efeefc39dd73.png)

ZOEY host:
![image](https://user-images.githubusercontent.com/29005374/32690367-f41e0f24-c6f5-11e7-8440-e9dd7af23f2b.png)

As you can see, no crew buffs are available at the very start. Once zoey bot uses an ability however:
![image](https://user-images.githubusercontent.com/29005374/32690375-0b3013c4-c6f6-11e7-873f-aea7263bbb8d.png)

The buffs appear but you don't get the +30% charge bar boost. It is definitely something on the side of Zoey bot, and not unrelated. Event raid URL are both the same for manual host during active crew buffs and inactive.

**Comment by Masuzu** [comment]
I've been farming with crew buffs active with Zooey Bot without any issue. You should not trust the visual displays on the client side which may not sometimes reflect the actual state on the server side (GBF servers).
I am sorry but this is pure nonsense and unrelated to what Zooey Bot does.
