### ISSUE TITLE
Keep reloading on same page

### ISSUE THREAD

**Issue by Lucas2009** [Masuzu/ZooeyBot#394]
Hi Masuzu,

Just start using this tools today, trying to farm GW nightmare mode 90, and I found sometimes
when finishing the quest and go to result page, Zooeybot will keep reload this result page for maybe
3~20 times before going to the GW event page again, is this an intended behavior?

http://game.granbluefantasy.jp/#result_multi/empty/3815xxxxxx

Similar problem happens if I turn on the RerollSummonWhenNoPreferredSummonWasFound option,
when no preferred summons available, Zooeybot will go for trial mode and retreat immediately, but it will keep reloading the trial mode battle page or the quest page for many times before it can really retreat from trial mode, is it normal?

Anything I can do to improve this reload problem?

Thanks.

**Comment by Masuzu** [comment]
Hi,
As for the repeated reload on the result page this is usually due to lag and faced this issue too rarely to notice it.
As for the retreat, same thing. With v2.1.1, as far as I know there was an issue which caused the retreat button to be pressed repeatedly with no response whatsoever. With v2.1.2, when this happen, the quest page will be refreshed instead to try again and press the "retreat" button.

**Comment by Masuzu** [comment]
Please send a screenshot of the console message if that happens again.

**Comment by Lucas2009** [comment]
Hi Masuzu,

Please check this link for screenshot
http://pan.baidu.com/s/1bp0dHr5

Sometimes it just keep reloading and never go into battle again, I’ve seen it reload at result page or at teamraid034 page

Thanks for your supporting

**Comment by Masuzu** [comment]
Hi,

Thank you for the update. Depending on your ping, the entered URL might be replaced by the one of the result page (if the result page takes longer to load than expected).
Basically it is a lag issue.
I will keep it in the backlog.

**Comment by Lucas2009** [comment]
Hi Masuzu,

Unfortunately the problem happens again on my 2nd PC, the reproduce step on my PC is like this
1. open chrome and go to http://game.granbluefantasy.jp/#mypage
2. press F12 to open dev console and switch to network page
3. open zooeybot, click the extension start button, finish calibration and click quest button to start the bot,
current page address is http://game.granbluefantasy.jp/#quest/index
4. bot move cursor to chrome address bar, paste http://game.granbluefantasy.jp/#event/teamraid034,
but suddenly the address jump back to http://game.granbluefantasy.jp/#quest/index
5. bot move cursor to address bar again, try to paste the teamraid034 page address, still reload as http://game.granbluefantasy.jp/#quest/index
6. looping step 5, never go to battle, from the bot console, no error message, just keep showing new page loaded: http://game.granbluefantasy.jp/#quest/index

the bot does work perfectly for one day on my 2nd PC, but today when I boot up my PC again and try to run bot again, the same problem happens on my 1st PC happens again on my 2nd PC now.

 It’s really frustrating , I didn’t change any settings, just shutdown my PC last night and boot up today, nothing changed, regarding to network condition, I live in Asia and close to Japan, so I don’t feel any lag during my gameplay actually, so I don’t think it is a network lag issue, btw both my PC are running windows 10 with i7 processor, please raise the priority on this issue, since It’s basically unusable on all my PCs now

Thanks.

**Comment by Garnetus** [comment]
Yeah I had the same problem during past 2/3 days, and I think it was getting worse, before it happened when you exit the re-roll, now, even you just started the bot and clicked quest button, it begins refreshing the quest page for 20 times before moving on, and if you need re-roll, well good luck, another 40 times.

**Comment by Masuzu** [comment]
Oh, that, did you just try to increase WaitTimeInMsAfterEventPageIsLoaded ? To like 1000 (1 second).

**Comment by Masuzu** [comment]
If manually, by navigating to `http://game.granbluefantasy.jp/#event/teamraid034` from `http://game.granbluefantasy.jp/#mypage`, you go back to `http://game.granbluefantasy.jp/#quest/index`, it might be that there are some other pending battles ongoing which finished. Happened me a few times while playing manually during Unite and Fight.

**Comment by Lucas2009** [comment]
1. Even set WaitTimeInMsAfterEventPageIsLoaded to 5000ms, this problem still happens.
2. Not navigating from mypage, after calibration, bot start from quest index page, and it try to go to teamraid034 page, but stuck at quest index page.

Thanks

**Comment by Garnetus** [comment]
Yeah, my situation is the same as Lucas2009, I already set all the wait timer to 50000+, same thing, it seems like the paste is complete, but instead of clicking the browser choose to refresh so it keep stucking in quest page and doing the paste-refresh over and over

**Comment by Masuzu** [comment]
I am sorry but I don't see how on earth it can happen.
Can you reproduce manually the situation by navigating to http://game.granbluefantasy.jp/#event/teamraid034 from http://game.granbluefantasy.jp/#mypage?

**Comment by Lucas2009** [comment]
Manually navigate to http://game.granbluefantasy.jp/#event/teamraid034 from http://game.granbluefantasy.jp/#mypage has no problem.

Also manually navigate to http://game.granbluefantasy.jp/#event/teamraid034 from http://game.granbluefantasy.jp/#quest/index has no problem either.

**Comment by Garnetus** [comment]
So I have been testing and find out if you disable adblock on the game website/page, everything seems working well so far, very smooth for an hour now, you may want try it out.

**Comment by Lucas2009** [comment]
Seems not work for me, http://game.granbluefantasy.jp is already in my adblock whitelist long time ago.

**Comment by Lucas2009** [comment]
Found a temporarily solution, google use chrome canary, tested a few hours, it seems has no problem so far.

Current chrome I use is version 62.0.3202.94 (64-bit), and chrome canary is version 64.0.3269.0 (64-bit).

**Comment by Masuzu** [comment]
Thanks for the feedback. It seems related to other parameters I have no control over then.
