### ISSUE TITLE
About use the blue potion

### ISSUE THREAD

**Issue by Inroi** [Masuzu/ZooeyBot#396]
Hi, Mazuru.

Thanks for your help, I'm working really well on Guild War.

I'm trying to reduce the coding lines of my scripts and meet a trouble.

I want to set if all the characters' hp are lower than 60% and one of the character's hp is lower than 40%, then I will use the bluepotion. (I'm right using the turn as the trigger)

so what I should do to link those triggers?

thanks for your reply :)

**Comment by Masuzu** [comment]
Hi,

You can refer to this example script https://github.com/Masuzu/ZooeyBot/blob/master/Scripts/water_gw_august_2017_nm_90.lua replacing the green potion uses with blue potion uses.
Please note that GW blue potions are not yet supported, for now.
https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts#potions-use
