### ISSUE TITLE
Lyria, Summon(x) command in script twice

### ISSUE THREAD

**Issue by sonderbyyonder** [Masuzu/ZooeyBot#398]
Hi, is it possible to use two summons in the first turn? When i input Summon (1) and Summon (6) only summon (1) gets used in the Lua script.

Do advise.

**Comment by Masuzu** [comment]
Hi,

This is a special case with Lyria which is not well supported yet.
Thank you for pointing this out.

**Comment by Masuzu** [comment]
This is now implemented in v2.12.8
