### ISSUE TITLE
GW Ext+ raids sometimes goes to pending raids page

### ISSUE THREAD

**Issue by salvanost** [Masuzu/ZooeyBot#399]
Hello
Looks like my internet not quick enought to follow the bot action
After the battle finished, the bot click next then change the url to event home page url

But the click from next to event home url sometimes too fast (due to my slow connection)
So the bot stuck, never find summon selection because the bot need to proceed with last page raids result first,

Any command to make slower response for bot before switching between url?
Thank you

**Comment by ZippyDragon** [comment]
Edit WaitTimeInMsAfterEventPageIsLoaded in the [EventMode] section of the .ini
