### ISSUE TITLE
Salves Mode Problem

### ISSUE THREAD

**Issue by mynameisjovi** [Masuzu/ZooeyBot#4]
Hello
I want to use salves mode.
However, the bot keep refreshing my chrome window.
And the Co-op quest never start but only refreshing.
Thank you
![keep refreshing](https://cloud.githubusercontent.com/assets/27763675/25779203/59e57da0-3345-11e7-87a0-17f58ed51236.png)

**Comment by Masuzu** [comment]
This will happen if you have a very slow internet connection: Zooey waits for the "Ready" (must not be pressed for the first run) and "Start" button to be visible.
