### ISSUE TITLE
Reload Preffered Summon not work

### ISSUE THREAD

**Issue by ariaanaa** [Masuzu/ZooeyBot#40]
Hi! So recently I test event mode to do dimensional halo and use shiva for preferred, when there is no shiva in the list support summon then the bot will auto reload with trial battle but for the second reload instead of trial battle the bot always open the dimensional halo for reload summon. can you help me to fix this? thanks!

**Comment by Masuzu** [comment]
Hi!
I identified the issue. I will provide a fix for this in version 1.4.1

**Comment by Masuzu** [comment]
Version 1.4.1 is now live:
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes

**Comment by ariaanaa** [comment]
Really appreciated, thank you!
