### ISSUE TITLE
Customized raid scheduling

### ISSUE THREAD

**Issue by ypk1246** [Masuzu/ZooeyBot#401]
My BOT ignores the number of times written in scheduling.lua.

RepeatQuest ("http://game.granbluefantasy.jp/#quest/supporter/300041/1", 15, 1)
RepeatQuest ("http://game.granbluefantasy.jp/#quest/supporter/300091/1", 15, 3)

Even if you write to scheduling.lua like this, I will challenge "http://game.granbluefantasy.jp/#quest/supporter/300041/1" four times and stop with an error.
How do I write properly?

**Comment by rednax27** [comment]
same, regardless of how many times you state it will run (e.g: 1,2,3), it will still do the raid for more than 3 times.

I honestly thought this issue had been addressed, guess not.

**Comment by Masuzu** [comment]
Hi,

Definitely annoying. Time to look into it again...
Thank you for reporting the issue.

**Comment by Masuzu** [comment]
This time that should be fine with v2.2.1. I tested that it worked fine with the following example:
```
RepeatQuest ("http://game.granbluefantasy.jp/#quest/supporter/300041/1", 15, 1)
RepeatQuest ("http://game.granbluefantasy.jp/#quest/supporter/300091/1", 15, 3)
```

I apologize for the inconvenience.
