### ISSUE TITLE
stuck at mypage after trial battle reroll in eventmode

### ISSUE THREAD

**Issue by ErogeSeiyuu** [Masuzu/ZooeyBot#402]
Is it possible to add in a debug option to zoibot so that whenever it **reroll summon and retreat from trial battle**, it will **refresh** after pasting #event/teamraid034 **before** pasting the EventRaidURL?

This issue persisted since August but I was too lazy to type it here. Zoibot will act like this on my computer whenever it rerolls summon:

1. Zoibot go to trial battle, go to granbluefantasy.jp/#quest to retreat.
2. It successfully retreated, but it gets stuck at granbluefantasy.jp/#quest screen while pasting EventPageURL (which is currently teamraid034)
3. Zoibot paste EventRaidURL and still get stuck at granbluefantasy.jp/#quest screen.
4. Zoibot detects the error and re-paste EventRaidURL, which redirects the game to granbluefantasy.jp/mypage and gets stuck there indefinitely unless I manually click the Event Page on mypage to redirects it back.

This issue can easily be fixed manually (like what I've done in the past 3 months) by refreshing after zoibot paste EventPageURL before it paste EventRaidURL. 

I hope a QoL update would happens when zoibot detects the mypage loop and it then **automatically** go to EventPageURL before pasting EventRaidURL. 

**But before that happens, I only need a small debug feature where zoi simply **always refresh after pasting EventPageURL** _after retreating from trial battle summon reroll_**

**Comment by ErogeSeiyuu** [comment]
This only happens when the event requires returning to EventPageURL

**Comment by Masuzu** [comment]
Hi,
I did not know this could happen.
Thanks for reporting this.
