### ISSUE TITLE
how to use defaultmode to fight?

### ISSUE THREAD

**Issue by jpgodkit** [Masuzu/ZooeyBot#403]
hello , how to use default mode to auto fight when I use my hand choice a raids?
I hope to join the other people raids but I hope to use my zooey script. thank you!

**Comment by MasuzuN** [comment]
Hi,
You may want to look at the `TrialBattle` mode under the Debug section of the ZooeyBot.ini file.

**Comment by jpgodkit** [comment]
but it's just work once time , how to continue at next battle?

**Comment by Masuzu** [comment]
You can't. It is not made for this use.
