### ISSUE TITLE
error message during slave mode

### ISSUE THREAD

**Issue by onionknight107** [Masuzu/ZooeyBot#404]
Hi. I constantly get this message about every ten minute when I use the slave mode. Could you provide some solution to it? Is there anything wrong in my setting? The lua script I am using is just the default one so I don't think there is anything wrong with that.
![qq 20171117220501](https://user-images.githubusercontent.com/32561965/32976575-78c753de-cbe7-11e7-9386-2834482bfa99.png)

**Comment by Masuzu** [comment]
Hi,

I am afraid I can't help without the last corresponding messages in the console.
