### ISSUE TITLE
Bot suddenly tells me i'm unregistered.

### ISSUE THREAD

**Issue by violafayde** [Masuzu/ZooeyBot#405]
I was running the bot as per usual, when suddenly the bot force closed.
Upon reopening the bot, it told me that I was an unregistered user.
My subscription is still active and i still have around 11 days to go. Is this a server issue?

**Comment by ypk1246** [comment]
me too...

**Comment by i-Grey** [comment]
Same things happen with me too.

**Comment by komagi** [comment]
ahh me too

**Comment by RhoninSeiei** [comment]
me too....

**Comment by Masuzu** [comment]
Hi,
I am sorry for the late notice.
https://github.com/Masuzu/ZooeyBot/issues/408
