### ISSUE TITLE
Licence issues 

### ISSUE THREAD

**Issue by komagi** [Masuzu/ZooeyBot#406]
![2017-11-19 16_44_28-c__users_komagi-pc mk3_desktop_zooey-bot-v2 2 1_zooeybot exe](https://user-images.githubusercontent.com/33801708/32989472-574508b0-cd49-11e7-973b-ab267e8f71bf.png)

I already Active my Licence , Key , series  but it said im unregistered user  

thank you

**Comment by Masuzu** [comment]
Hi,
I am sorry for the late notice.
https://github.com/Masuzu/ZooeyBot/issues/408
