### ISSUE TITLE
Licence Issue

### ISSUE THREAD

**Issue by RhoninSeiei** [Masuzu/ZooeyBot#407]
![default](https://user-images.githubusercontent.com/33801807/32989529-2176531e-cce6-11e7-8223-67da6e7a5067.png)
The program shows me like this. I have just used it 1 hours ago, but it shows me now. I noticed that the serial number which is the text file was changed, which is different from the website one now. However, I cannot change the website one because it shows me I only can change it after four days. I don't know why the serial number changed, I'm just used the same laptop.
I faced this problem during my using on Zooeybot. Once it crashed today, it showed me like this. Before this happened, I can use the problem. Please help me.

**Comment by Masuzu** [comment]
Hi,
I am sorry for the late notice.
https://github.com/Masuzu/ZooeyBot/issues/408
