### ISSUE TITLE
Slave mode stuck on refresh

### ISSUE THREAD

**Issue by BakaPhoenix** [Masuzu/ZooeyBot#41]
Sometime the slave get stuck on refresh loop instead loading a new quest.
It happens sometimes not always and sorry i can't figure out what triggers it and give a way to reproduce the error.
Can run fine for 30min or only after 3 run and then get into loop.

Using the 1.3.2

**Comment by Masuzu** [comment]
Is it with the slave mode or the regular mode?
Is it at the result page or summon selection page?
There is still the parameter `ReloadPageOnLastBattle` otherwise.

**Comment by BakaPhoenix** [comment]
No is slave that go in refresh loop while trying to set the next quest
