### ISSUE TITLE
error serial number

### ISSUE THREAD

**Issue by Reh87** [Masuzu/ZooeyBot#411]
Hello,
i just took a licence for 1 month for zooey boot but there is a probleme with my serial number, i can't change it because it's already taken, can you help me ?
here my login: rehodi.oy@gmail.com

**Comment by Reh87** [comment]
and here the S/N 6fc9e1c38b674d6f24e813f15c989c22dde9c34bbaf1ff4d68930aac67ff18bf8876b088f824f30ce585fb8c07230f1c058a166ff9f6648fc20b54600e28bffe

**Comment by salvanost** [comment]
Correct me if i’m wrong
Looks like u using 2 account for 1 pc

I’m using 2account too
But the serial number cannot used for 2 account
So 1 pc serial number only works for 1 account

If u already using 1 account for those pc
The 2nd account would pop up message the serial jumber already taken (for 1st account)

**Comment by Reh87** [comment]
So how can i fix the problem ?

**Comment by Masuzu** [comment]
@Reh87 Do you have more than 1 account registered?

**Comment by Masuzu** [comment]
There is a password recovery feature if you try to login

**Comment by Reh87** [comment]
i just tried the link you send but le serial number is affected to isugia30@gmail.com and this is not me :(

**Comment by Masuzu** [comment]
I am sorry but I can't do anything. That email has active licence at the moment.

**Comment by Reh87** [comment]
so i pay for an licence but can't use it ?
i want a refund

**Comment by Masuzu** [comment]
I'll grant it.

**Comment by Reh87** [comment]
is there a way to change the serial number of my pc ?
or i can't use any of your bot anymore ?
