### ISSUE TITLE
I cant get past this page

### ISSUE THREAD

**Issue by tidusZX** [Masuzu/ZooeyBot#412]
The bot doesnt work when i navigate to quests and once it starts calibrating nothing else happens. I dont know what else to do.
![unnamed](https://user-images.githubusercontent.com/33868380/33074783-5b0025f6-cf02-11e7-9fa6-1b83d9051a19.jpg)

**Comment by Masuzu** [comment]
Hi,
You got stuck in the calibration phase.
Please check again your in game settings.
This is what is should look like:
![](https://i.imgur.com/rTEbku7.png)
