### ISSUE TITLE
Payment error

### ISSUE THREAD

**Issue by patrapornlee** [Masuzu/ZooeyBot#415]
Hi.

Yesterday I purchased the 1 month subscription for zooey bot. But it appears as 6 hours in the account.
Today I tried again. But still the same problem.
Could you please help me fix this problem?

Thx

**Comment by Masuzu** [comment]
Hello,
There was an issue with Stripe which has just been fixed.
The charges induced correspond to the 6h licence and this can be checked in your bank statement.
I apologize for the inconvenience.
