### ISSUE TITLE
failed to parse lua script

### ISSUE THREAD

**Issue by salvanost** [Masuzu/ZooeyBot#416]
why randomly the bot sometimes stop with error failed to parse lua script?
![untitled](https://user-images.githubusercontent.com/32562379/33138603-7b878bf8-cfdd-11e7-9f75-396b70cedd5e.jpg)

**Comment by salvanost** [comment]
> if battle == 1 and turn == 1 then
  character_3:UseSkill(1)
end

if battle == 1 and turn == 3 then
  character_2:UseSkill(3)
end

if battle == 2 and turn == 1 then
  character_1:UseSkill(2)
end

if battle == 3 and turn == 1 then
  EnableChargeAttack()
  character_1:UseSkill(1)
  character_1:UseSkill(3)
  character_1:UseSkill(4)
  character_4:UseSkill(3)
  character_2:WithWaitTime(2700):UseSkill(3)
  character_2:UseSkill(2)
  character_2:UseSkill(1)
end

if battle == 3 and turn == 2 then
  Summon(6)
  character_3:UseSkill(2)
end

if battle == 3 and turn == 3 then
  Summon(1)
end

if character_1.hp_percentage < 40 then
  UseGreenPotionOnPartyMember(1)
end
if character_3.hp_percentage < 40 then
  UseGreenPotionOnPartyMember(3)
end
if character_4.hp_percentage < 40 then
  UseGreenPotionOnPartyMember(4)
end

**Comment by salvanost** [comment]
randomly error, now happen at battle stage 2

![untitled](https://user-images.githubusercontent.com/32562379/33140259-09f39e00-cfe2-11e7-846f-93833c452434.jpg)

**Comment by Masuzu** [comment]
Hi,
This is an especially nasty error and should not happen normally (I still have to face it...). From the provided screenshots it seems to appear right after a new raid stage is loaded. I'll see what I can do about it in the next version.

**Comment by Masuzu** [comment]
Mitigation added in v2.3.0
Nonetheless, this is not supposed to happen with a decent internet connection and computer.
