### ISSUE TITLE
New version has no executable

### ISSUE THREAD

**Issue by soufflenote** [Masuzu/ZooeyBot#417]
Just downloaded the 2.2.2 version since I saw the notice that previous versions were being discontinued; however, there's nothing but ini files for old versions and lua scripts inside the zip folder. How do we run the new version?

![image](https://user-images.githubusercontent.com/32054761/33147786-1ebfcdd6-cf97-11e7-9f07-6effd0489cd0.png)

**Comment by Masuzu** [comment]
This is not the correct download link. Please double check again

**Comment by soufflenote** [comment]
Absolutely understandable, but I got to this download from the bot and front pages, not github, on the alternative download link since the original link wasn't working. Would you be able to provide another link in the meantime for downloading, as Dropbox seems to have an error about too much traffic?

**Comment by soufflenote** [comment]
Found it, I'm so sorry for my mistake, I can't believe I didn't try the link above earlier >.<

**Comment by Masuzu** [comment]
![](https://i.imgur.com/86j0ylG.png)

**Comment by Masuzu** [comment]
All good then :)
