### ISSUE TITLE
Support for Xeno raid solo

### ISSUE THREAD

**Issue by Djeetamate** [Masuzu/ZooeyBot#418]
I've tried using the event mode and default mode to load the xeno cocytus raid, but it doesn't seem to catch. Event mode just gets stuck at the quest screen. It won't even go to the event page from there if I specify it. I'm guessing this just isn't supported right now?

Also while I'm at it, the option to have the bot load raids (and open for pubs to kill) in between xeno ex runs and check if the raids have been completed afterwards would be nice. Currently we have to do that manually as the bot is doing ex and hope we don't trigger the rewards screen at a bad time. This would be the most efficient way to get animas while farming mats to host the raids.

At least being able to load the raid for solos would be nice. This one happens to be easy enough to manage.

**Comment by Masuzu** [comment]
Hi,

> Also while I'm at it, the option to have the bot load raids (and open for pubs to kill) in between xeno ex runs and check if the raids have been completed afterwards would be nice. Currently we have to do that manually as the bot is doing ex and hope we don't trigger the rewards screen at a bad time. This would be the most efficient way to get animas while farming mats to host the raids.

I have no intention to add such feature but: https://github.com/Masuzu/ZooeyBot/issues/359

> At least being able to load the raid for solos would be nice. This one happens to be easy enough to manage.

The event mode won't work for this, since the raid require materials to host. This would require an update of the TreasureEventMode to support . I will see if I can make the change by the end of the event.

**Comment by Masuzu** [comment]
Feature added in v2.3.0
