### ISSUE TITLE
How to do

### ISSUE THREAD

**Issue by GGfans** [Masuzu/ZooeyBot#419]
I want to use the Slave mode, but will not automatically start after calibration is done. Where did I go wrong? Solo co op mode also can not automatically start

English is not good, using Google Translate. Sorry

**Comment by Masuzu** [comment]
Hi,

Please refer to the documentation https://github.com/Masuzu/ZooeyBot/wiki/Solo-co-op-mode and https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting) and try to run google translate on those pages.
