### ISSUE TITLE
Is it possible to add "Request backup" or ability use potion?

### ISSUE THREAD

**Issue by rockysilver** [Masuzu/ZooeyBot#42]
My character is just barely strong enough to finish some event, a few time the party got wiped, is it possible  to request backup or use blue potion at low health?

**Comment by Masuzu** [comment]
Not yet for now. The basic assumption is that you can clear the quest by yourself.

**Comment by cobeng13** [comment]
Is this feasible in the near future?

**Comment by MagCat** [comment]
@Masuzu the ability to use potion or revive potion decrease the huge chance of bot getting crashed because RNG screws over and kill entire party. Please consider this greatly because it's extremely annoying in some events like Vohu, a HP potion can make a huge difference between life and death.
