### ISSUE TITLE
New popup keeps appearing while sliming.

### ISSUE THREAD

**Issue by violafayde** [Masuzu/ZooeyBot#420]
has anyone seen the message 'processing previous quest, you will be able to select a quest shortly' or some sort of dialog box when sliming? the bot is unable to get rid of the dialog box and gets stuck.
this happened when i was using slime mode with two accounts.

**Comment by cfilorvyls** [comment]
Same issue happened to me. The 'Processing previous quest.." box only pop up on the slave account.

**Comment by onionknight107** [comment]
Same issue here

**Comment by sujiC** [comment]
Having the same issue here

**Comment by sujiC** [comment]
@Masuzu

**Comment by Masuzu** [comment]
![](https://gbf.wiki/images/f/f1/Stamp117.png)

Thank you for reporting this. I will look into it during the upcoming week.
Thanksfully there is no ongoing half AP event.

**Comment by Masuzu** [comment]
Actually it's a very minor bug. From tests the popup may appear only the first time after setting a quest or changing a quest. Just clear it manually once and you should be good to go.

**Comment by Maestro93** [comment]
@Masuzu Even if you clear it once, it reappears again after you've killed a few more.

**Comment by cfilorvyls** [comment]
The popup appears very frequently for me actually.
It appears even every quest sometimes, but usually it will appears every 6 or so quests.

I'm using vpn btw, if that matters at all.
Using browsec chrome extension premium, from indonesia and using singapore vpn

**Comment by ReinaryuIlyen** [comment]
Same issue happening here, the pop-up appears pretty frequently but intermittently. Clearing once does not get rid of it.

**Comment by agesa** [comment]
I have gotten it multiple times in a row a couple of times.  Could it be related to clicking the ready button multiple times as it's trying to host?

Has anyone encountered this while sliming manually and is able to reproduce it?

**Comment by ReinaryuIlyen** [comment]
Viramate autohide popup on the slave account is working as a temporary work-around, as a heads up

**Comment by violafayde** [comment]
@ReinaryuIlyen how do you enable that?

**Comment by Masuzu** [comment]
@ReinaryuIlyen Oh, good to know, thank you.
I will provide a fix for the issue this week. Maybe today or tomorrow.

**Comment by cfilorvyls** [comment]
Btw, i tried doing some coops without the bot, and the popup still appears when i host

**Comment by Masuzu** [comment]
That was expected.

**Comment by Masuzu** [comment]
Addressed in v2.3.2
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-3-2
