### ISSUE TITLE
License error happens on Ver2.3.1

### ISSUE THREAD

**Issue by Nassy1121** [Masuzu/ZooeyBot#424]
I really confused that license expired error happens on 2.3.1.
![license_error_231](https://user-images.githubusercontent.com/31133619/33240280-223fbc92-d2f7-11e7-87d0-9a946eab6ad1.png)
When I used ver2.2.2, also see license expired error.
![license_error_222](https://user-images.githubusercontent.com/31133619/33240287-37a7cbce-d2f7-11e7-8efd-19de7cfb4da3.png)

But as per my account page, license is still activated.
![mylicense](https://user-images.githubusercontent.com/31133619/33240309-798a5002-d2f7-11e7-8899-e2eaf5e8d28f.png)

I have ever seen such a license error from around Ver2.1.x.

What shall I do something?

**Comment by Masuzu** [comment]
Hi,
Apart from the broken message displayed, you key file is probably invalid now. Please redownload a new key file and replace the existing one, using the Management page (in Other settings -> Download key file).
