### ISSUE TITLE
Network loss behaviour

### ISSUE THREAD

**Issue by patrapornlee** [Masuzu/ZooeyBot#425]
Right now the Zooey will stop after experience network loss in chrome (the dinosaur page). I am thinking of setting the auto refresh inside chrome://flags to refresh the page after the browser is offline and goes online later. Will the zooey continue the flow after the page is refreshed?

**Comment by Masuzu** [comment]
Hi,
Well you are not supposed to experience a network loss in the first place. I won't add any workaround in the foreseeable as it is very far from normal use conditions.
