### ISSUE TITLE
Unregistered User

### ISSUE THREAD

**Issue by Jagger0083** [Masuzu/ZooeyBot#429]
As title says. I'm getting an error when started Zooeybot
![user](https://user-images.githubusercontent.com/30936638/33365989-d6509cc6-d49e-11e7-9ffd-52f26a4ead76.png)

**Comment by Masuzu** [comment]
Hello,
Please redownload your key.txt file (Other settings on the management menu => key file)

**Comment by Jagger0083** [comment]
The same issue is happening even after downloading the new key file

**Comment by Masuzu** [comment]
Then probably the contents of your serial_number.txt file created when you start Zooey Bot does not match the one on https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber

**Comment by Jagger0083** [comment]
Ah, yes. I upgraded windows recently and apparently that caused this whole thing with the key file. All fixed, thank you

**Comment by Masuzu** [comment]
![](https://gbf.wiki/images/2/2f/Stamp3jp.png)
