### ISSUE TITLE
Target certain enemy as long as it is alive?

### ISSUE THREAD

**Issue by thenastyworm** [Masuzu/ZooeyBot#43]
Wondering if this is already supported in the Lua scripting. Could not find any example of this in the documentation or examples.

Multi enemy battles such as Xuanwu slow down Zooey a lot right now due to her focusing on the wrong enemies first.

**Comment by Masuzu** [comment]
Not yet but this could be considered in the future, since it is not the most common scenario to have multiple enemies on the same stage.

**Comment by cobeng13** [comment]
In Xeno Vohnu, the book is the second target and it's better to take it down first when doing solo runs, this would be really helpful

**Comment by Masuzu** [comment]
Target selection support added since v1.14.0
