### ISSUE TITLE
Coop Sliming with main and slave

### ISSUE THREAD

**Issue by UthurPen** [Masuzu/ZooeyBot#431]
I recently tried doing the coop sliming but when i get to linking my 2nd acc it just gets stuck in 3/6 initialized
Please help

**Comment by Masuzu** [comment]
Please reread the **full** setup carefully.
There are 2 different extensions. Both are needed for the slave mode to work.
https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation#installing-the-zooey-bot-chrome-extension
