### ISSUE TITLE
The program automatically edits my serial number file when I run it.

### ISSUE THREAD

**Issue by Anontastic** [Masuzu/ZooeyBot#433]
Both this program and the poker bot automatically edit my serial number file to something different when I run it, and give me a message saying I'm not registered. I currently can't use either bot. Deleting and re-downloading everything didn't help. Why is this happening?

**Comment by Masuzu** [comment]
The first time you run it your `serial_number.txt` file may change indeed. The following runs the serial number will stay the same.

**Comment by Anontastic** [comment]
I've been using the bot for a while, and this "unlicensed user" thing started happening randomly. I tried to rectify it by changing my serial number to what I found in the new text file, and re-downloading the whole program + key file, and I'm still having no luck.

**Comment by Masuzu** [comment]
I am not sure what the issue is but it is not supposed to happen.
Make sure both those files are encoded in UTF8.
Can you mail me your serial number and key file at gbfpokerbot@gmail.com with 'Anontastic' in the subject please?

**Comment by Anontastic** [comment]
I changed my Serial Number again, now that the 4-day time cooldown on that is up, and there seems to be no problem now. I'll try to keep it that way ;=_=

**Comment by Anontastic** [comment]
I changed my Serial Number again, now that the 4-day time cooldown on that is up, and there seems to be no problem now. I'll try to keep it that way ;=_=
