### ISSUE TITLE
When on favorite tab and I pick a certain quest it keeps reloading on first battle

### ISSUE THREAD

**Issue by UthurPen** [Masuzu/ZooeyBot#434]

**Comment by Masuzu** [comment]
Hi,

This is the exact same problem described here: https://github.com/Masuzu/ZooeyBot/issues/421
Basically it's an issue with the Chrome browser, but thankfully the solution described in this ticket works well in practice :)

There is FAQ too: https://github.com/Masuzu/ZooeyBot/wiki/FAQ#zooey-keeps-reloading-the-same-page-over-and-over
