### ISSUE TITLE
Keeps looping summons to main page when initializing

### ISSUE THREAD

**Issue by pockydesuwa** [Masuzu/ZooeyBot#435]
Read through the questions regarding infinite loops for chrome,
turned off address bar auto complete as well
I believe my screen scaling is correct since i dont have issues with the calibration, 
But the bot keeps getting stuck on the loading of the summons page 

It tries to 'List available Summons'
then sends it back to 'mypage'
then tries to get to the /friendsummonpage/ then kicks me back to my page
![error](https://user-images.githubusercontent.com/34168411/33495622-2c907ca8-d695-11e7-9d64-f39a3b781664.PNG)

Potential errors: Viramate's auto favourite summons?

Only on a 6 hour trial but thanks if you can help fast!

**Comment by Garnetus** [comment]
this happens with normal chrome, you should try chrome canary, apparently it only happens to certain amount of people and can't be easily solved.

**Comment by Masuzu** [comment]
Hi,

This is the exact same problem described here: https://github.com/Masuzu/ZooeyBot/issues/421
Basically it's an issue with the Chrome browser, but thankfully the solution described in this ticket works well in practice :)
