### ISSUE TITLE
Same issue as before when dping favorite quest tab

### ISSUE THREAD

**Issue by UthurPen** [Masuzu/ZooeyBot#436]
Ive already tried disabling auto complete and cleared my history but it didnt solve it

**Comment by Masuzu** [comment]
Hi,
I am not sure I understand what the issue is then, unless you can upload a recording of what happens.
I have had no other reports of users running into this kind of issue.

**Comment by agesa** [comment]
I suddenly started getting this issue too as of this latest patch when I wasn't getting it before.  Happens probably a third of the time and sometimes resolves itself after a while but not always.  Running I Challenge You, it will sometimes attempt to refresh the empty results screen over and over.

**Comment by Masuzu** [comment]
Oh, nice finding. I discharge my responsibility from any possible incompability issues with other extensions.
