### ISSUE TITLE
docking problem

### ISSUE THREAD

**Issue by Helbaren** [Masuzu/ZooeyBot#437]
![2017-12-06_01-10-23](https://user-images.githubusercontent.com/13334142/33620253-529fe5a6-da22-11e7-8acf-7de8b458e993.png)
it works fine first time I tried but after that I always get the same error.
I already set the 
> ChromeDevToolsWindowDockedOnTheRight
to true and tried to change it to bottom  but it's still the same,

**Comment by Masuzu** [comment]
Hi,
This is not an error. You should have your devtools window look like this:
![](https://i.imgur.com/B68TA8G.png)
Then start the Zooey Bot extension. There are step by step instructions in the Wiki.

**Comment by Helbaren** [comment]
![image](https://user-images.githubusercontent.com/13334142/33722350-aad20514-dba4-11e7-9d43-e3377dd0caad.png)
Now the program just blank and quit right after this, clicking on chrome extension doesn't do anything as well.
