### ISSUE TITLE
Anyone have a looping problem?

### ISSUE THREAD

**Issue by ryokage** [Masuzu/ZooeyBot#438]
Anyone have a looping problem? I used to use zooey bot all the time but just started to use it again since the new updates. I tried to even copy past the event but everytime it loops to the home page instead of doing hard farming mat quest. Anyone else having this problem?

**Comment by ryokage** [comment]
It goes back to http://game.granbluefantasy.jp/#mypage when it tries to load this quest 
http://game.granbluefantasy.jp/#quest/supporter/723981/3

**Comment by ryokage** [comment]
I've also tried it with http://game.granbluefantasy.jp/#quest/supporter/723971/3 but it keepsd bringing me back to mypage and wont load the event pages

**Comment by ryokage** [comment]
[EventMode]
# Set this parameter to true to use the event mode. Zooey will enter autopilot mode when you navigate to the quest menu.
Enabled=true
# Url of the summon selection page for Angel Halo (Extreme)
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/723971/3
EventRaidScript=
# Url of the summon selection page for Dimensional Halo
NightmareModeUrl=http://game.granbluefantasy.jp/#quest/supporter/723971/3
NightmareModeScript=
# Some events such as Rise of the Beasts require to navigate to the home page of the event before navigating to the event raid url defined above. If EventPageUrl is provided, Zooey will first navigate to this url before hosting the raid. Leave EventPageUrl blank for events which do not require you to do so.
EventPageUrl=
# Comma-delimited list of summons which will be selected in priority if they are available for the nightmare mode.
# In case none of the preferred summons was found, select a random summon in the summon attribute tab defined by the parameter DefaultSummonAttributeTab, unless the parameter RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode is set to true.
NightmareModePreferredSummons=Bahamut
# Zooey will reroll summons until one of the preferred summons for the nightmare mode is available, using trial battles to refresh the summon list.
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=false
# Set this parameter to true if the nightmare mode is available when you start Zooey so she can proceed to the nightmare stage right ahead.
NightmareModeAvailableAtStart=false
# Wait time in milliseconds after Zooey finishes loading the EventPageUrl
WaitTimeInMsAfterEventPageIsLoaded=2000

**Comment by ryokage** [comment]
I've tried to even put the event page prior too http://game.granbluefantasy.jp/#event/treasureraid062

**Comment by Masuzu** [comment]
Hi, please refer to this ticket: https://github.com/Masuzu/ZooeyBot/issues/421
