### ISSUE TITLE
Would it be possible to add sound alert when captcha appear? 

### ISSUE THREAD

**Issue by meteoshower** [Masuzu/ZooeyBot#44]
Greeting, is there any way to setting sound alert when captcha appear? since i got ban for 2 times now using Zooey while im doing works.
it's not your fault but is that possible to get  a sound alert when captcha appear? Thanks! Masuzu huurayy!

**Comment by Masuzu** [comment]
Hello @meteoshower ,

Sure thing I will do this as soon as possible and before the start of the guild war.
```
Even if Zooey closes immediately when a captcha screen appears, please avoid to fall asleep when a captcha pop-ups and make sure to clear it as soon as possible. Even legit players can be caught if they do not complete the captcha in a certain timeframe.
```

**Comment by meteoshower** [comment]
Thanks. Can't wait for up date. 🍡

**Comment by meteoshower** [comment]
Wow i see that update look nice. I have some question. Can i replace mp.3 file with other sound right? and rename to captcha_notification.

**Comment by Masuzu** [comment]
Done in v1.5.1
