### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by RedMagus** [Masuzu/ZooeyBot#440]
@Masuzu Hi, I recently started resubscribing again with ZooeyBot but I'm encountering critical issues right now. The bot keeps crashing without giving any error so I hope you can look into the issue why this is happening, I updated the account with new SN which is: `0a8b5b49c58f71b38dc2546d3b98c04e0c46acbf9c21cf070d4cbc8473002aa015ba6b6e2b741164568b15feece80e18fc21eb400ca06b7d4643362a995c22da`
account email is theredmagusx@gmail.com

**Comment by RedMagus** [comment]
@Masuzu Hi can you fix it? I already spent money on this...

**Comment by RedMagus** [comment]
@Masuzu hello? :(

**Comment by RedMagus** [comment]
@Masuzu Now I really regret I resub to the bots since there is no response from you at all, and the event is ending...

**Comment by Masuzu** [comment]
Hi,
What do you mean by a crash?
Did you make sure to redownload a key.txt file too? Some past versions provided an invalid key.txt file - which should not have happened - which caused some issues.
I am not reponsible in any case for firewall/antivirus issue which may cause this problem.

**Comment by RedMagus** [comment]
@Masuzu Thank you for response this time. I downloaded the new version and it works fine this time around. I don't have any firewall activated or any antivirus on my new windows version so they can't be at fault.

**Comment by Masuzu** [comment]
All good then.
