### ISSUE TITLE
The application was unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by BrokenWing67** [Masuzu/ZooeyBot#441]
Hi
As stated on the title, the error pops up whenever i tried to start the apps. I tried Poker, zooey and Sarasa and all have the same error. I tried run as administrator and compatibility but it still doesn't work. The bot was working a few days ago and suddenly it stopped working.
Please help

**Comment by Masuzu** [comment]
Hi,

I am afraid it looks like it's like you missed some of the prerequisites: https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation
Or are missing windows updates.

The issue is too localized for there to be a fix since it's working for everyone else.
