### ISSUE TITLE
Cannot run Zooey bot 2.7.0 version.

### ISSUE THREAD

**Issue by Omegawp** [Masuzu/ZooeyBot#442]
I use to run 2.7.0 version because my computer cannot run newer version than this. (It keep saying missing api-ms-win in picture) My 2.7.0 version used to run very well but this time after subscribe again, It keep close itself.

What should I do? Can I keep using 2.7.0 version or I need to fix this api issue?
![error](https://user-images.githubusercontent.com/26983989/34129897-77652c1a-e478-11e7-90e8-63a2580bbe47.JPG)

**Comment by Shamool** [comment]
Err, correct me if I'm wrong, but doesn't that mean you are missing a C runtime?

**Comment by Omegawp** [comment]
I know. But my old computer and win7 cannot setup C runtime so I have to stay on 2.7.0 version.
![error1](https://user-images.githubusercontent.com/26983989/34144538-8815cad2-e4c4-11e7-9b21-3a3d4bce7c23.JPG)

**Comment by Masuzu** [comment]
Hi,
It won't run as long as you do manage to install VC++ 2015 redist packages (32 bit for Zooey Bot by the way, not the x64 version). You should Google the error message as it looks like it is a common error.
