### ISSUE TITLE
ZooeyBot crash whenever a character is dead.

### ISSUE THREAD

**Issue by rockysilver** [Masuzu/ZooeyBot#443]
I been having this problem that zooeybot will crash whenever a character died. For example, if I put the script:

```
if characters["Lecia"]:HasStatusEffect("133201") then
    character_4:UseSkill(1)
end

```
The script run fine, but if Lecia got kill, an error will pop up and zooeybot will crash. Same thing if I used the if characters["CharacterName"] ~= nil command. Is there any way to get prevent or get around this?

**Comment by Shamool** [comment]
I usually use booleans to get around this or I don't specify the characters at all. I just make it evaluate if the character at that position is alive and condition my raids following that.

**Comment by Masuzu** [comment]
Hi,
What Shamool said. It is not a bug but an error in your script. You should check whether your character is still alive first:
`if characters["Lecia"] ~= nil then ....`
