### ISSUE TITLE
ZooeyBot stuck and crash after result page in slime blasting mode

### ISSUE THREAD

**Issue by Saftz** [Masuzu/ZooeyBot#444]
I have an issue when using the slave mode. When the main account proceeds after the result page, 
ZooeyBot will stuck on a page saying that there isn't any loot you can collect and then crashes after refreshing for a few times. The slave account works fine though. Any way getting pass this?

![2017-12-19_175924](https://user-images.githubusercontent.com/34677844/34152069-44a2e928-e4e8-11e7-8b8c-1e2a595e10f1.jpg)

**Comment by agesa** [comment]
Do you have search autocomplete on?

https://github.com/Masuzu/ZooeyBot/issues/421

**Comment by Masuzu** [comment]
Hi,
It could be that. I haven't looked into it since the change in the page navigation.

**Comment by Masuzu** [comment]
I will look into it quickly before leaving and see if it is an issue indeed or rather caused by user misconfiguration.
