### ISSUE TITLE
[TODO] Dismiss info popup related to elemental resistance at party selection

### ISSUE THREAD

**Issue by Masuzu** [Masuzu/ZooeyBot#447]
As said in the title. In the meantime you can use Viramate auto popup dismissal to work around this issue.

**Comment by KuroShiro39** [comment]
Hi admin.
Is this what you are referring too?
![vira1](https://user-images.githubusercontent.com/34737156/34249970-721f35ca-e676-11e7-98e9-5135b5b9561f.jpg)

**Comment by Masuzu** [comment]
Yes that would be it.

**Comment by fumika779** [comment]
no it didn't work
![2017-12-22_021536](https://user-images.githubusercontent.com/31799116/34271296-458566ea-e6be-11e7-9ea2-e23fd6cc306d.jpg)
![2017-12-22_021712](https://user-images.githubusercontent.com/31799116/34271297-45bdf32a-e6be-11e7-989b-7463881c0ee3.jpg)

**Comment by Masuzu** [comment]
Got it.
Fix under test. Release ETA: 1- 2 hours from now.

**Comment by Masuzu** [comment]
Fixed in v2.4.3
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-4-3
