### ISSUE TITLE
Trial Licence Expired Immediately

### ISSUE THREAD

**Issue by LawrenceLE** [Masuzu/ZooeyBot#448]
Hi, I wanted to try out zooey bot before buying.
How do I start a trial version? How long is the trial?
My licence status shows Expired on the pokerbot manage account page.
And for the zooeybot manage account page, my licence status shows Expired after I select "Get licence" button.
Downloaded pokerbot and zooeybot, Licence info shows expired too.

Email: Lawrence_L_Esparza@protonmail.com

![capture](https://user-images.githubusercontent.com/34745647/34261629-b6c285d2-e6a4-11e7-8d70-0b73e2d317f5.PNG)
Btw its Granblue, not Grandblue 😆

**Comment by Masuzu** [comment]
Hi,

Unfortunately, the trial mode had to be removed and I have no plan to go back on this decision.
