### ISSUE TITLE
Lua Error in Json::Value::find in Xeno Diablo NM

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#450]
Getting this error:
![image](https://user-images.githubusercontent.com/32204823/34299871-5979b1f8-e6f3-11e7-8b69-1f72ff501f22.png)

Anyone else seeing it?

Script:
  Summon(5)
  Summon(2)
  Summon(6)
  characters["thebp"]:UseSkill(2)
  characters["thebp"]:UseSkill(1)
  characters["thebp"]:UseSkill(3)
  characters["thebp"]:UseSkill(4)
if characters["Jeanne d'Arc"] ~= nil then
  characters["Jeanne d'Arc"]:UseSkill(1)
  characters["Jeanne d'Arc"]:UseSkill(3)
  if turn > 3 then
    characters["Jeanne d'Arc"]:UseSkill(2)
  end
end
if characters["Lucio"] ~= nil then
  characters["Lucio"]:UseSkill(1)
  characters["Lucio"]:UseSkill(3)
  characters["Lucio"]:UseSkill(2)
end
if characters["Seruel"] ~= nil then
  characters["Seruel"]:UseSkill(1)
  characters["Seruel"]:UseSkill(2)
  if turn > 1 then
    characters["Seruel"]:UseSkill(3)
  end
end

**Comment by thebp2** [comment]
I turned off refreshing the page and haven't seen the error again yet.

**Comment by thebp2** [comment]
I'm now seeing this happen when doing coop on the first page load. Seems like it has to do with executing the script too fast after page load?

**Comment by thebp2** [comment]
Still seeing this error in 2.4.4 for what it's worth.

**Comment by thebp2** [comment]
*bump* I hope this is on the list to get addressed before GW. Please let me know if you need any additional information.

**Comment by Masuzu** [comment]
Hi,
It looks like you were one of the unlucky sole or few person who ran into this issue.
It would seem to appear only on certain types of raids.

**Comment by thebp2** [comment]
I ran into at least once per hour while doing coop as well.

**Comment by Masuzu** [comment]
This particular issue is especially hard to debug for now. I will keep it in mind and try and add more information in the future releases.

**Comment by Masuzu** [comment]
Similar to https://github.com/Masuzu/SarasaBot/issues/35

**Comment by thebp2** [comment]
Let me know what I can do to help debug. I can run a debug build and report too if that helps.

**Comment by Masuzu** [comment]
I did not forget about this issue. Some improvements were added in the latest version: https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-5-2

**Comment by thebp2** [comment]
Thanks for the support. I haven't seen this issue so far while using 2.6.0.

**Comment by thebp2** [comment]
I spoke too soon, it happened again.

On nightmare 95. Here's the end of the log if it helps:

Loading Lua script Y:\\fire-NM95.lua
Checking whether the battle already ended
Number of remaining clarity herbs: 4
Trying to use a clarity herb on the party member at position 2
List of active buffs
1019 DEF Boosted

List of active debuffs
1010 ATK Lowered
1020 DEF Lowered
1020 DEF Lowered
1027 Gravity
1083 Burned

List of active buffs
1019 DEF Boosted

List of active debuffs
1010 ATK Lowered
1020 DEF Lowered
1020 DEF Lowered
1027 Gravity
1083 Burned

List of active buffs
1019 DEF Boosted

List of active debuffs
1020 DEF Lowered
1027 Gravity
1083 Burned

List of active buffs
1019 DEF Boosted

List of active buffs
1019 DEF Boosted

**Comment by thebp2** [comment]
I think I'm now seeing this error only immediately after using a clarity herb on a character will skill seal. I have this in my script and it seems to trigger the error (and never gets to the refresh):
    if characters["Rosetta"]:HasStatusEffect("1111") then
	  UseClarityHerbOnPartyMember(2)
	  Refresh()
	end
