### ISSUE TITLE
Serious Issue with zoeybot losing focus on screen before loading luascripts

### ISSUE THREAD

**Issue by LordShade** [Masuzu/ZooeyBot#452]
This is on random occurrence. Sometimes after clearing the network request history, zoey will attempt to load the luascript again however she will very often (every 2 to 3 attempts during my xeno ex runs) lose complete focus on the screen and pause. However clicking absolutely anywhere on the screen of the game, will cause the program to resume.

https://puu.sh/yM9Xs/1d84e0cdea.jpg picture on where she seems to be freezing, note she is stuck on loading a luascript despite loading it a few times before and having no issues.

Heres my luascript that I use for XenoDiablos Extreme

```
if battle == 1 then
	DisableChargeAttack()
	SelectTarget(2)
end
if battle == 2 then
	SelectTarget(2)
end
if battle == 3 then
	if enemy_1.hp_percentage > 75 then
		if booleans ["perform opening skills"] == nil then
			booleans ["Opening skills will be performed"] = true
				character_1:UseSkill(2)
				character_1:UseSkill(3)
				character_1:UseSkill(4)
				character_3:UseSkill(1)
				character_3:UseSkill(2)
				character_3:UseSkill(3)
				character_4:UseSkill(2)
				character_4:UseSkill(1)
				character_4:UseSkill(3)
				character_2:UseSkill(2)
				character_1:UseSkill(4)
		end
	end
end	
if battle == 3 then
	if enemy_1.hp_percentage < 49 then
		EnableChargeAttack()
	end
end			
```

my script is in no way efficient, but its what I need because my team is not all that strong, but its strong enough for me to do it myself with some work, also I'm mostly learning this as a complete newbie because I had no idea what a luascript was up until a few months ago. Fairly certain the booleans isn't necessary but Its there because I wanted to experiment. 

I also experimented with the booleans because I was having serious issues having zoey reuse skills. She would often lose focus and just sit there until the auto fail popped up on the command line.

**Comment by Masuzu** [comment]
Hi,
Thank you for reporting this issue. For now I sontrgly advised against not setting the ReloadOnLastBattle parameter to true. This would avoid this kind of issue after clearning the network requests.
