### ISSUE TITLE
Extension keeps disappearing when i relaunch Chrome.

### ISSUE THREAD

**Issue by violafayde** [Masuzu/ZooeyBot#453]
Hi, I'm not sure if this has been raised before, but all the extensions (Zooey, Beatrix, Sarasa) disappear when I relaunch my chrome browser. Is there any way to stop that from happening? As of now I have had to reload my extensions every time I open the browser.

**Comment by po456asd** [comment]
when it ask when you launch chrome read it carefully what it say before close.

**Comment by Masuzu** [comment]
Hi,
I am aware of this minor issue but won't do anything about it. It could be related to Google accounts syncs settings but I can't confirm it.
