### ISSUE TITLE
Change Serial Number

### ISSUE THREAD

**Issue by Reh87** [Masuzu/ZooeyBot#454]
Hello,

I want to know if i can change the serial number in my PC so it do'nt interfere with another account since mine is already used ?
I want to use ZooeyBot but also the new one so can you do something about it ?

**Comment by Reh87** [comment]
Hello ?

**Comment by Masuzu** [comment]
Hi,
Please use the management page to do so.

**Comment by Reh87** [comment]
In the management page, i can change only the serial number in the account not my own serial number.
GBFPokerBotSerialNumberGenerator.exe give this SN : 6fc9e1c38b674d6f24e813f15c989c22dde9c34bbaf1ff4d68930aac67ff18bf8876b088f824f30ce585fb8c07230f1c058a166ff9f6648fc20b54600e28bffe

But it's already used by another account so i need to change this one.
