### ISSUE TITLE
nighthound switch

### ISSUE THREAD

**Issue by maso94** [Masuzu/ZooeyBot#456]
is there a way to code the swap of the nighthound class to switch charas from the front to the backline?
ty in advance

**Comment by Masuzu** [comment]
Hi,
Not yet, I will consider it.

**Comment by calvinhyang** [comment]
I would also appreciate this addition 
I need it for my Zooey+Dianthia meme teams

**Comment by Masuzu** [comment]
Before the start of this month GW, if the time allows it.

**Comment by Masuzu** [comment]
Feature added in v2.6.0. Enjoy! https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-6-0
