### ISSUE TITLE
About slave mode

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/ZooeyBot#462]
Just want to inform you that the problem is because the new UI, so it will be stuck on calibrating, whatever version it is.
I've tried all version starting from 2.4.2 to 2.3.x none worked.

**Comment by thebp2** [comment]
For some reason it works for me in 2.4.3. Only had calibrating fail when my slave browser window was scrolled down.

**Comment by Sundaerae** [comment]
after I seen your reply, I try it again and turn off viramate.
now it works on 2.4.3 -_-a

strange, but thanks

**Comment by thebp2** [comment]
Bizarre. It works for me with viramate.

**Comment by Masuzu** [comment]
Hi,
Make sure not to use Lite settings on the slave window or else you may be stuck at the initialization phase.
