### ISSUE TITLE
Solo COOP mode isn't refresh

### ISSUE THREAD

**Issue by kamohati** [Masuzu/ZooeyBot#463]
![zooeybotnazo](https://user-images.githubusercontent.com/34973275/34458219-15a63066-ee0d-11e7-8d32-540a9d908cdd.png)
solo coop mode isn't refresh, and output log like this picture.
I want to play solo coop speedy. What should I do?

**Comment by cobeng13** [comment]
Check combat settings.
Reloadonlastpage=true

Also make sure that your script has a skipattack line

**Comment by kamohati** [comment]
cobeng13 thank you.
Realodonlastpage is true, already.
and my script has been written 
character_3:UseSkill(3)
SkipAttack()
only. 

Anyways, COOP battle ended 1 turn. but zooey bot console is displayed "battle 1 turn ~"

**Comment by kamohati** [comment]
Hope I didn't make too many English mistakes today. sorry.

**Comment by kamohati** [comment]
Sorry, I solved.
Chrome canary is the cause of problem.
