### ISSUE TITLE
Master failing to return to coop room in slave mode

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#465]
I'm having an issue where sometimes the master window gets stuck on the results URL. Zooey appears to try to navigate back to the coop room but for some reason the (empty) results page shows up. After a couple times of this Zooey exits (perhaps because it thinks the room has ended?).

This is with 2.4.3. Since Zooey exits I can't get a capture of the console window, but I did see something about "returning to lobby" before it quit.

Here's what the master window looks like after Zooey has exited:
![image](https://user-images.githubusercontent.com/32204823/34465604-8b379dd6-ee82-11e7-9c65-707d657ba991.png)

**Comment by greatmany** [comment]
I get this issue too, it happens even when i switch to an older version that never had this issue when i used it in the past

**Comment by greatmany** [comment]
I turned off search autocomplete in chrome and it seems to have completely solved the problem.

Strange because I have never touched the autocomplete settings in chrome and zooeybot never exhibited this problem for me in the past.

**Comment by Masuzu** [comment]
Good thing that you got it solved!
