### ISSUE TITLE
SetPreferredGroup and SetPreferredDeck issue

### ISSUE THREAD

**Issue by merun23** [Masuzu/ZooeyBot#466]
Hi there,
On my zooeybot.ini, i have:
PreferredPartyGroup=5
PreferredPartyDeck=1

On my scheduling.lua, i have:
SetPreferredPartyGroup=7
SetPreferredPartyDeck=5
SetPreferredSummons("Kaguya, White Rabbit")
SetLuaScript("Scripts/VHmode.lua")
RepeatQuest... <list of repeat quest here>

When zooeybot runs scheduling.lua, it still uses 5/1 instead of 7/5.
Does the SetPreferredPartyGroup/Deck not overwrite PreferredPartyGroup/deck? Or am i missing something?

**Comment by thebp2** [comment]
I suspect you need to do:
SetPreferredPartyGroup(7)
SetPreferredPartyDeck(5)

**Comment by merun23** [comment]
Seems to be working fine now (: thanks so much!!
