### ISSUE TITLE
Zooey Stuck at calibrating (used to work before)

### ISSUE THREAD

**Issue by Kluiman** [Masuzu/ZooeyBot#47]
It used to be working before in the past 4 days. Today, it stuck at calibrating process.

![image](https://cloud.githubusercontent.com/assets/28539574/26070689/b19b90bc-39cf-11e7-8b27-ee40b2af2265.png)

**Comment by Masuzu** [comment]
Hi,

I happened to update the FAQ xwith this issue a few days ago:
https://github.com/Masuzu/ZooeyBot/wiki/FAQ#zooey-is-stuck-during-the-calibration-phase
