### ISSUE TITLE
Second computer

### ISSUE THREAD

**Issue by Sumetfu** [Masuzu/ZooeyBot#471]
Is there anyway to run this on my laptop without buying another key? I didn’t realize this took over the mouse. So I can’t do anything while it runs

**Comment by violafayde** [comment]
you can login with your account on your laptop and download the bot. the only thing you need to do is to use the serial code generator to generate a new code, and then update the serial on your manage account page with the new code.

**Comment by Sumetfu** [comment]
thanks, for some reason when i do that the website says expired but i tried running and it works!
