### ISSUE TITLE
(QoL update?) Is it possible to have a feature in scheduling.lua to trigger notification.mp3 upon schedule end/upon request?

### ISSUE THREAD

**Issue by ErogeSeiyuu** [Masuzu/ZooeyBot#472]
Since ROTB is coming, is it possible to have a script setting to trigger notification mp3 when a schedule is done? Since a lot of people, myself included, can't solo ROTB EX+ raids, it'd be helpful to get zooey to notify me of its availability once the scheduled 8 normal raids is done. 

For example, I'd schedule 8 solo Zhuque, zooey bot ends after 8 solo zhuque and notify me with notification mp3 and then I do the Agni raid by myself+call backup.

**Comment by Masuzu** [comment]
Added in v2.7.0
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-7-0
