### ISSUE TITLE
[Informational] Do not play at the same time when you are using Zooey Bot

### ISSUE THREAD

**Issue by hebrew** [Masuzu/ZooeyBot#473]
I am using zooeybot, but I took measures to stop using GBF for about 7 hours today.
This situation occurred in situations where image authentication was not requested while using zooeybot, so it seems that new type of fraud detection began to be applied at GBF operation.
Although it is unknown what kind of detection it is, please check and correspond.

**Comment by Alissa1122** [comment]
During last half AP co-op event, I found there is no captcha shown even once during my 4 days co-op slave mode slime blasting using zooeybot, I guess they do change some captcha mechanism, either they totally remove it from co-op mode or they change the way how captcha show, so during the zooeybot operation, it won’t trigger captcha at all, don’t know it’s a good thing or bad thing, hope Masuzu can look into this issue in high priority, it may has risk to bot now

**Comment by violafayde** [comment]
nah, i got capcha'd, they probably changed the conditions that trigger captcha.

**Comment by Lucas2009** [comment]
Do you get captcha in co-op mode these days when using zooeybot?
I play like this:
1 hr co-op mode bot -> about 10 mins play manually to spend my BPs -> repeat

And I did this about 8~10hrs per day, I got zero captcha pop which is abnormal I guess?

**Comment by Masuzu** [comment]
Hi,
I am sorry but if you triggered the captcha it is your own issue.
Besides, if you do 2 things at the same time (poker and slime blasting for instance or slime blasting and joining raids at the same time, then you will trigger some kind of detection - this fact I can guarantee).

**Comment by hebrew** [comment]
In my case, I have done more than 2 things at the same time, but Captcha was not displayed.
I did not know that it is better to stop doing more than two things at the same time even in one interval ...
It may be caused that I was banned from using GBF because it was not caused by Captcha but was doing more than two things.

From now on I will be careful not to do more than two things.

**Comment by Hedova928** [comment]
What were the two things? Is it safe to for example shop and upgrade weapons at the same time when the bot is battling?

**Comment by Masuzu** [comment]
Upgrading weapons is fine. Joining other raids is risky.
