### ISSUE TITLE
Bot wont click "right behind you" ex quest

### ISSUE THREAD

**Issue by edgellidan** [Masuzu/ZooeyBot#475]
not sure why, itll go to the home page, click extreme but then get stuck at the selection screen (30ap vs 40ap).

# Use this special event mode to automate farming of events stages which require a certain number of items to be hosted, such as Guild War nightmare modes.
# Please refer to https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode for more information
[TreasureEventMode]
Enabled=true
# Url of the event page. The URL of the June 2017 dark GW is given as an example.
TreasureEventUrl=http://game.granbluefantasy.jp/#event/treasureraid063
# Supported value are 'vh' (for "very hard"), 'ex' (for "extreme"), 'xeno-raid' (for the level 100 Xeno raid), 'gw' (for the preliminary round and first day of "Unite and Fight" nightmare mode level 90), 'gw-day-2-nm-90' for the second and 3rd days of "Unite and Fight" nightmare mode level 90, 'gw-day-2-nm-95' for the second and 3rd days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-90' for the 4th and last days of "Unite and Fight" nightmare mode level 90, 'gw-day-4-nm-95' for the 4th and last days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-100' for the 4th and last days of "Unite and Fight" nightmare mode level 100
Difficulty=ex
# Action point cost of the quest you are trying to start
ActionPointCost=30
TreasureEventModeScript=Scripts/meme.lua

**Comment by Masuzu** [comment]
Hi,

This is now fixed: https://github.com/Masuzu/ZooeyBot/issues/470
