### ISSUE TITLE
New difficulty impossible

### ISSUE THREAD

**Issue by onionknight107** [Masuzu/ZooeyBot#476]
Right now zooey bot is only able to auto farm the extreme difficulty which costs 30 ap. For some high rank players auto farm the new impossible difficulty would be more desired. Could you please add that fuction to zooey bot? Thank you

**Comment by Masuzu** [comment]
Hello,
I will do it within the next 8 or 9 hours. Hopefully you will still have enough time after the release to squeeze in some runs.

**Comment by Masuzu** [comment]
Feature added in v2.5.0
