### ISSUE TITLE
Serial Number Stolen/Replicated? 

### ISSUE THREAD

**Issue by Miyoumu** [Masuzu/ZooeyBot#477]
So, as mentioned previouly on your SarasaBot Github, it would seem that my laptops serial number is already in use by another email that I have no relation to. 

I am currently using ZooeyBot and SarasaBot on my desktop but wish to make the transfer to my Laptop in an effort to do other things whilst botting. 

I haven't purchased your bot in a few months though I do use it a lot, but recently came back to repurchase it. When I tried to login it said my password was incorrect, so I try to reset it but I never got an email needed to reset my password. So I assumed maybe making a new account would be the easiest solution but I cannot do that because it specifies that the serial number is already being used when trying to make the new account from my laptop. That made me suspcious, so I attempted the "forgot my email" option and entered in the serial number associated with my laptop to find out my email and I recieved an email telling me that the email connected to my serial number is

![image](https://user-images.githubusercontent.com/28634170/34664829-bf7a3cee-f42b-11e7-9d85-0cc7e9267ab3.png)

Which is not correct, I've never seen this email in my life. 

When attempting to update my serial number from my Desktop to my Laptop, it says that my Laptop's serial number is already taken. Confirming that my serial number has indeed been taken or replicated.

![image](https://user-images.githubusercontent.com/28634170/34664855-e26aba12-f42b-11e7-823e-af11d8243146.png)

I look forward to your help with this problem. I would like to continue to use your bot but I don't see myself doing so unless I can use it on my Laptop. 

P.S: Sorry for posting the same issue I posted on SarasaBot github originally twice. I haven't recieved help in days so I thought it would be better to move the issue from SarasaBot github to here.

**Comment by Masuzu** [comment]
Hello,
I am sorry for the very late reply >_<
I will check later on today if this email is linked to an account with or without an active licence. I will keep you posted.

**Comment by Masuzu** [comment]
Update: the associated serial number is available again.
You should be able to change it again on this page: https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber
