### ISSUE TITLE
My Zooey bot keep reload to main menu

### ISSUE THREAD

**Issue by yuzurihaz** [Masuzu/ZooeyBot#478]
i just buy it moment ago i try to set myscreen like the recommend but i when the program told me to go to quest menu i go to quest menu and it keep reload to main menu but the logs in the program write i select summon  is it because i play on  Notebook with 1366*768 scale ? that's most scale i can set to my note book ps: sry im suck on english ps2: my mouse keep select in the black circle

**Comment by Masuzu** [comment]
Hi,

This will happen if you try to host an even quest using the `EventMode`. You have to set the parameter `EventPageUrl` to the URL of the event page (`http://game.granbluefantasy.jp/#event/treasureraid063` for instance) or else navigating to the quest URL will automatically redirect you to the main page. 
You may want to increase the value for the parameter `WaitTimeInMsAfterEventPageIsLoaded` as well (to 1000 for instance for 1 second) depending on your ping.

Edit: I removed the links for privacy reasons and your safety.

**Comment by yuzurihaz** [comment]
thank now i can auto Halo with ctrl+alt+left arrow  cuz when i go in summon collect it can't click on ok or it's my problem with 1366*768 resolution ?

**Comment by Masuzu** [comment]
Oh that's an issue with low screen resolutions which you have just unearthed again.
I will do something about it later today.

**Comment by Masuzu** [comment]
Update: patch will be delayed. Sorry.

**Comment by Masuzu** [comment]
Mitigation provided in v2.5.1 https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-5-1
Let me know if it is still an issue after.
