### ISSUE TITLE
sry i don't understand about Co op with 2id (main-slave)

### ISSUE THREAD

**Issue by yuzurihaz** [Masuzu/ZooeyBot#481]
like the topic  i read how to co-op i read it and do it but this is it happend
could you teach me by past the guideline link
![y1](https://user-images.githubusercontent.com/35253544/34815607-89947570-f6e4-11e7-825d-98337713e226.jpg)
 step by step 1>2>3>4>x 

ps: sry for make you a problem

**Comment by Masuzu** [comment]
Hi,

First of all, please make sure to have the Home button visible in the top left corner, like this:
![image](https://user-images.githubusercontent.com/5464705/34843945-38918a92-f710-11e7-8b40-bda54221511f.png)
It does not seem to be the case in your screenshot.

If you still have issues after:
Do you manage to perform the calibration with the other modes? If not, it is a scaling issue as mentioned here: https://github.com/Masuzu/ZooeyBot/wiki/FAQ#i-have-scaling-issues-again
If the calibration works for the other mode, make sure you set your settings to Standard (not Lite) for the Chrome window with your slave account.

**Comment by yuzurihaz** [comment]
maybe it is my scaling problem sitll calibration and has nothing
