### ISSUE TITLE
Romeo : Activating his first skill twice.

### ISSUE THREAD

**Issue by tiongcock** [Masuzu/ZooeyBot#483]
hello i want to ask, how to make my romeo ( water ) activate his first skill again after using third skill ?

> 	character_4:UseSkill(1)
> 	character_4:WithWaitTime(1100): UseSkill(3)
> 	character_4:WithWaitTime(3500): UseSkill(1)

seems doesn't work for me, it just go after skill1 -) skill3 -) then proceed to atk.
thanks :)

**Comment by Masuzu** [comment]
Hi,
I will investigate this particular case. Thank you for providing the example.

**Comment by tiongcock** [comment]
oh, and if it's possible to add line for selecting certain target? like xuanwu counts as 3 target, i want to select certain target before doing any action. Thanks in advance :)

**Comment by Shamool** [comment]
Target selection is already present thoug?

**Comment by Masuzu** [comment]
Target selection is already available: https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts#enemy-selection

**Comment by Masuzu** [comment]
Hello,
The feature works. Make sure you configured your delay between skill use properly not to get any "Failed to parse ability results" errors.
```
character["Romeo"]:UseSkill(1)
character["Romeo"]:UseSkill(3)
character["Romeo"]:UseSkill(1)
```

**Comment by tiongcock** [comment]
thanks!
