### ISSUE TITLE
DMM accounts - summon selection issue

### ISSUE THREAD

**Issue by esqapade** [Masuzu/ZooeyBot#484]
So for some reason its not able to use lua scripts when I set `UseVirmate=true` and also the bot has trouble selecting a summon that is too far down the list. Anything at position 9 and below it fails indefinitely to "scroll up" and instead just clicks the top-most pixel on my screen over and over again.

**Comment by esqapade** [comment]
I think I figured something out. DMM account users that want to use viramate have to use a script that allows the sidebar to actually appear and I guess that also conflicts with the bots recognition.

**Comment by Masuzu** [comment]
Hello,
Hmm I had someone else have the same issue. I did not know it could be linked to the different layout of DMM accounts.

**Comment by esqapade** [comment]
Yea people who play with DMM accounts have to use this [script](https://github.com/Yoctillion/Viramate-Fix) to actually have the sidebar show up at all. I'm not sure if there's more deep seeded differences between Viramate working for DMM vs for Mobage but I do know that if you want the bot to utilize Viramate while I play on my DMM account,  the bot breaks entirely.

**Comment by onionknight107** [comment]
Dmm user, having the same issue here. I am using viramate, the fix script for viramate, and zooey bot at the same time. Usually what I do when zooey fails to select a summon is to scroll up manually and click the ok button. A temporary solution is to enable the prefer high-level summons in viramate, and hopefully the summons of your high level friends will appear at the top.

**Comment by Masuzu** [comment]
I will have to create a DMM account to fix the issue. I will do it this week if the time allows it.

**Comment by onionknight107** [comment]
Update: I think the problem is caused by Viramate-fix. The summon selection works fine when I turns it off.

Here is a link to that tampermonkey script: https://github.com/Yoctillion/Viramate-Fix

**Comment by Masuzu** [comment]
Great finding!
