### ISSUE TITLE
Trying to register the account for Zooey bot, but the verification email never come.

### ISSUE THREAD

**Issue by 8GUNDAM8** [Masuzu/ZooeyBot#485]
same as the topic, any way to resend without register with another email?

**Comment by 8GUNDAM8** [comment]
BTW, it've been almost 24H i believe

**Comment by Masuzu** [comment]
Hello,
There is no resend verification email for now. I will add this feature as soon as I can.

**Comment by 8GUNDAM8** [comment]
Hi,
Right now it won't allow me to register again since my serial number already taken. So is there a way i can get a new serial number and try to register with my Gmail? My friends told me that Gmail can receive the verification email.

**Comment by Masuzu** [comment]
Hello,
The most probably scenario for your serial number to be already taken would be that you are using a computed leased by your company or university or school. For now there is supported official way to get a new serial number without using another computer.

**Comment by 8GUNDAM8** [comment]
Hi, 
My serial number to be already taken is because I register this serial number with the account: liliwoli@aol.com which never receive the verification email and i couldn't login. So i decide to use my personal Gmail to register again since my friends told me Gmail works with no problem. so could you link the post to the offcial way for getting a new serial number without using another computer? i couldn't find that post.
thanks.

**Comment by Masuzu** [comment]
Hello,
There is no support for such a request for now.
However, I can delete the account associated with the email `liliwoli@aol.com` is that's fine with you.

**Comment by Masuzu** [comment]
It has just been deleted. You can now create a new account using the same serial number but the correct email this time.

**Comment by AzurNep** [comment]
If its possible, delete mine too, it seems verification doesn't play nice with aol accounts, I was able to use my waifu.club email on another computer and got it instantly, however since my main computer I use is my laptop, i'd need the following email account cleared/deleted so i can remake under a new email and free the serial / transfer it to the waifu.club email account.
namedown@aol.com

**Comment by niconicocolonel** [comment]
Nice to meet you, @Masuzu.  https://github.com/Masuzu/ZooeyBot/issues/485#issuecomment-358960080 

If its possible, delete mine too. imano_tamo@yahoo.com 
Thank you for your help in advance.

**Comment by Mirimu** [comment]
hello @Masuzu 
if its possible can you delete mine too? lastation40@gmail.com
or can you make new features about changing the verify email.

**Comment by monopoly0920** [comment]
@Masuzu 
hello
if its possible can you delete mine too? yp4c6f@gmail.com
