### ISSUE TITLE
my script wont work on Rising the beast

### ISSUE THREAD

**Issue by yuzurihaz** [Masuzu/ZooeyBot#487]
if battle == 1 then
EnableChargeAttack()
Summon(6)
--[[Use Full Arsenal III whenever it is off cooldown (bound to the skills at position 4 and 3 in my case)--]]
 if characters["My main character"] ~= nil then
  characters["My main character"]:UseSkill(1)
  characters["My main character"]:UseSkill(3)
 end
 if characters["Clarisese"] ~= nil then
  characters["Clarisese"]:UseSkill(1)
 end
end

**Comment by Masuzu** [comment]
Hello,
You have mistyped character names. 
Also, please check https://github.com/Masuzu/ZooeyBot/wiki/FAQ if you use Viramate especially and skills are not cast.
