### ISSUE TITLE
GW Mat Farm Issue

### ISSUE THREAD

**Issue by sinanjugbf** [Masuzu/ZooeyBot#490]
I'm trying to farm zephyr feathers, but zoibot just keeps refreshing instead of hitting attack. My lua file is blank so I think it should just be hitting attack?

**Comment by Masuzu** [comment]
Hi,
Did you make sure to disable Viramate auto-close popup feature?
I got that same issue reported a lot because of this.

**Comment by sinanjugbf** [comment]
Ah yeah, I remember that being the issue now. Thanks.
