### ISSUE TITLE
Serial number issue

### ISSUE THREAD

**Issue by einzwarthz** [Masuzu/ZooeyBot#491]
My serial number suddenly changed into a serial number that i can't regcognize. At first i think there's an error so i tried to change the serial number, then i generate the serial number, but the generated serial number is the same with the serial number that has been changed so i tried to download the key and the key is different with the serial number on website.

can you please check this ? thx

**Comment by Masuzu** [comment]
Hello,

The key.txt is a different thing from the serial number and you should never have to touch it, as mentioned here:
https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation#first-run

**Comment by einzwarthz** [comment]
i didn't touch the key.txt. sorry if my english is bad let me try to sum it
1. im still using the bot 2 days ago
2. when i want to use it again today i can't cuz it said 
Zooey boy Unregistered user
3. when i check the website the serial nuimber that the site show is diffrent then my serial number so i tried to generate new key.
4. the generated new key is the same like the site, then i tried to download the key.txt file
5. when i download the key.txt file when i open it, it have different serial number

**Comment by Masuzu** [comment]
As I said, key.txt is not the same as your serial number. You do not even need to compare the key.txt contents with anything. The only file whose contents you want to compare with the one on the website is the one named `serial_number.txt`. Forget about the `key.txt` file.

**Comment by einzwarthz** [comment]
Oh i see so i've been lookin for a wrong 1 then.
I checked the serial number on the web and mine is different should i change it ?
