### ISSUE TITLE
Chrome extension memory leak

### ISSUE THREAD

**Issue by Hedova928** [Masuzu/ZooeyBot#492]
I noticed that during long fights - after around 20 to 30 turns - Chrome's memory usage blows up to 2-3GB, and eventually becomes unresponsive and the tab crashes. 

![memory_1](https://user-images.githubusercontent.com/35021122/34928036-a0b51218-f96f-11e7-8566-10e223dd5d04.PNG)

The Chrome task manager shows that the usage is mostly due to JavaScript heap space, and profiling the memory allocation points to functions in the ZooeyBot extension as the culprit.

![memory_2](https://user-images.githubusercontent.com/35021122/34928037-a0c8655c-f96f-11e7-857f-d839959f96c1.PNG)

Here is the [memory allocation profile](https://github.com/Masuzu/ZooeyBot/files/1630447/Heap-20180114T210533.zip) using un-minimized jquery. Tried to take a heap dump as well but the tab always crashes during the snapshot. 

Is this due to something in my combat scripts? Let me know if there's anything I can do to help debug.

**Comment by Masuzu** [comment]
Hello,
This is somewhat a known issue.
For now please do something like:
```
if turn % 5 == 0 then
  Refresh()
end
```
or else set the parameter `ReloadPageOnLastBattle ` to true.
