### ISSUE TITLE
Add popup or info to show that a captcha occured rather than closing the bot right away

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/ZooeyBot#493]
So sometimes I leave my pc for about 30 mins or so and sometimes the bot stops and I dont know why. It could be that the captcha showed up but just didnt see since sometimes I also see Connection Lost error. 

So for informational purposes put an alert popup that never disappears so that I know its because of captcha or not.

**Comment by Masuzu** [comment]
Hello,

If a captcha popups it will always trigger a sound alert for a couple of hours until you stop it manually, which is unmissable.
As for  Connection Lost error it is just not supposed to happen, at all! The only way for this to happen is to close the Chrome DevTool window. Make sure to set the configuration parameter `ChromeDevToolsWindowDOckerdOnTheRight` to the suitable value for your layout to avoid potential issues with click positions.
