### ISSUE TITLE
"No active window with Grandblue Fantasy was found"

### ISSUE THREAD

**Issue by Shizukanawa** [Masuzu/ZooeyBot#494]
Like I have a tab open and followed everything in the setup, but it still doesn't find anything.

**Comment by iysuua** [comment]
have you changed the language values (en/jp) in ZooeyBot.ini?

**Comment by Shizukanawa** [comment]
The game is in English and the .ini file is on en

**Comment by Masuzu** [comment]
I am sorry but I am not sure how on earth you managed to run into this issue.

**Comment by Shizukanawa** [comment]
I mean if you can’t fix refund me as I can’t get it working

**Comment by Shizukanawa** [comment]
No there’s nothing. If you can’t fix, refund me please.

**Comment by Masuzu** [comment]
There is nothing to fix. Even though there is no refund policy as stated by the [terms and conditions of service](https://poker-bot.azurewebsites.net/en/Home/Legal), refund will be issued for this particular case. Stripe refunds takes between 5 and 10 business days to be effective, hence the delay, if any.

**Comment by Shizukanawa** [comment]
Thank you!
