### ISSUE TITLE
Can not use the SlaveMode

### ISSUE THREAD

**Issue by Nefghy** [Masuzu/ZooeyBot#497]
![zooey](https://user-images.githubusercontent.com/35523073/35034163-3aaf9eee-fba8-11e7-8468-59210ebee751.jpg)

**Comment by Masuzu** [comment]
Hello,
What does your screen setup look like?
Make sure not to click on the ready button.
https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)
