### ISSUE TITLE
Script

### ISSUE THREAD

**Issue by UthurPen** [Masuzu/ZooeyBot#499]
Not really a problem but is there a script for when ST activates

**Comment by UthurPen** [comment]
like "if ougi == 100 then" or something like that

**Comment by Hexadecimalism** [comment]
I suggest reading this https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts

Check the section on "Accessing characters data" and "Charge attack"
Almost all my scripts start with DisableChargeAttack() except for my gunslinger and strike time scripts which instead start with EnableChargeAttack()

It's best to have separate strike time scripts.
If you want to enable charge attack at specific periods, like maybe when orchid in this at 70 percent

If characters["Orchid"].charge_gauge >= 70 then EnableChargeAttack()

You can also add complex ones that verify based on everyone's positions by using AND.

As an aside it's better to use character.1, character.2 etc, not the character's name when making complex charge  scripts.

**Comment by Masuzu** [comment]
Hello,
Thank you for reaching out.
As detailed by @Hexadecimalism (thank you!), please do check the wiki for complete information.
You can use custom user variables to trigger a different behaviour during assault time, as shown here for instance: https://github.com/Masuzu/ZooeyBot/blob/master/Scripts/gw_ex_with_zooey.lua
