### ISSUE TITLE
Zooey is very confuse and press twitter everytime.

### ISSUE THREAD

**Issue by po456asd** [Masuzu/ZooeyBot#5]
i'm trying to blast a slime 
using 1600x900 screen so i don't know is this a problem or not.
zooey very confuse press a twitter and goes to another browser screen 

here my setting
https://pastebin.com/XaHL0q97

and video
*EDIT the fuck. got temp banned because not completely hide name*
use below vvvvvv video instead.

**Comment by po456asd** [comment]
ah i can get it work now by unknown reason still didn't figure out how can i done that

**Comment by po456asd** [comment]
this is another problem 
video
"2017-05-08 00-31-02.flv"
https://drive.google.com/drive/folders/0B4AQ7NyN6b_VNEM0Z0JjWjlHTlk?usp=sharing

1.44 it both go to first page
7.23 Twitter
13.02 Twitter
18.40 Twitter,Stuck then open zooey again and it open twitter again
26.15 Twitter,Stuck
33.40 Twitter

some time screen will open twitter and another one go to my page at very first when zooey ask who is slave

**Comment by po456asd** [comment]
Additional information you can spectate dev tool from chrome using this 

![image](https://cloud.githubusercontent.com/assets/13596788/25783842/146e0a4c-338d-11e7-99b3-6634ed3f5f13.png)

**Comment by Masuzu** [comment]
Hi,
Thank you for reporting this. I will look into it when I have the data. I remember having issues trying to dock the DevTools window outside of the webpage.
There seems to be some weird interaction (a bug on Google's side) when several DevTools window are open such as in slave mode but it is not happening all the time.
Stay safe.

**Comment by po456asd** [comment]
oh hey i think video have leaked too much that i cant even censor all 
a name , a room link (yeah, a number of room so they can check who in this room) or even a result page  an address bar... etc
( and i see that your demo video leaked ***** too :/ )

can i massage you somewhere so i can send a link of no censored footage ?

**Comment by Masuzu** [comment]
Hi,
Yes sure, you can share a private link with gbfpokerbot@gmail.com
