### ISSUE TITLE
Two more feature requests / improvements

### ISSUE THREAD

**Issue by thenastyworm** [Masuzu/ZooeyBot#50]
Hey,

I saw you implemented some of the stuff that was requested recently, thanks for that!

I got three more suggestions of functionality that I would believe would be very useful:

## Time based actions
In addition to letting us stop the bot after a certain time has passed or certain AP has been used - maybe let us start and stop at pre-defined system times in the ini? This way we could setup Zooey to start farming guild war when guild war goes live and similar.

## Setting and reloading ini options from lua script
Maybe you could add something like a background.lua file - that is running in the background and gets executed every minute or so in addition to the combat related lua tasks. In this it would be amazing if we can set certain ini variables and force an ini refresh from a lua script.

What I am thinking here for my personal use case is something like writing a lua script that lets me update the EventRaidUrl based on my current system time, so I could automate the selection for celestial bonuses based on time.

Maybe something like:

setIni("EventRaidUrl", "http://game.granbluefantasy.jp/#quest/supporter/510031/5")
reloadIni()

## Reload (F5) from lua script
Would be great to have a way to manually reload the current stage to use it with skills like luchador's tag team where zooey does not recognize the extra turn-less attack as a turn and wastes time by not refreshing

Keep up the good work!

**Comment by Masuzu** [comment]
Hi,

Thank you for the detailed suggestions and potential use cases. Some of them are very unusual.
For now, I believe that a "refresh on demand" command would be very useful, especially with the ongoing guild war. I will try to release it later today.
As for the other features requested, I will keep them in mind and will maybe add them later on when the time allows it.

**Comment by Masuzu** [comment]
Reload from lua script partially available with version 1.5.2:
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes
