### ISSUE TITLE
I have probleme with my script 

### ISSUE THREAD

**Issue by yuzurihaz** [Masuzu/ZooeyBot#500]
When Beatrix died my script get error like this how to fix it with my script  when Beatrix died just let character 4,5 auto attack instead
![987](https://user-images.githubusercontent.com/35253544/35041620-f0884cd4-fbb7-11e7-8d51-b153aa0f41e0.jpg)

if battle == 1 then
EnableChargeAttack()
--[[Use Stall III whenever it is off cooldown (bound to the skills at position 4 and 3 in my case)--]]
 if characters["Cirno"] ~= nil then
  characters["Cirno"]:UseSkill(4)
  characters["Cirno"]:UseSkill(3)
  characters["Cirno"]:UseSkill(2)
  characters["Cirno"]:UseSkill(1)
 end
   if characters["Percival"] ~= nil then
  characters["Percival"]:UseSkill(3)
   end
--[[As long as Yuel is alive, use his first and third skills whenever they are off cooldown--]]
    if characters["Yuel"] ~= nil then
  characters["Yuel"]:UseSkill(2)
    end
--[[As long as Beatrix is alive, use his first and third skills whenever they are off cooldown--]]
      if turn == 1 then
     if characters["Beatrix"] ~= nil then
  characters["Beatrix"]:UseSkill(1)
     end
	  end
   if turn == 2 then
 DisableChargeAttack()
 characters["Beatrix"]:UseSkill(2)
 characters["Beatrix"]:UseSkill(1)
 characters["Beatrix"]:UseSkill(3)
   end
 Summon(6)
  if characters["Magisa"] ~= nil then
 characters["Magisa"]:UseSkill(4)
  end
 if characters["Anthuria"] ~= nil then
 characters["Anthuria"]:UseSkill(3)
 end
end

**Comment by Hedova928** [comment]
As the error mentions, on line 25 you attempt to reference ```characters["Beatrix"]``` even though she is dead. You need to put the following into the ```if characters["Beatrix"] ~= nil``` block:

```lua
characters["Beatrix"]:UseSkill(2)
characters["Beatrix"]:UseSkill(1)
characters["Beatrix"]:UseSkill(3)
```

Replace lines 17 - 28 with this:

```lua
--[[As long as Beatrix is alive, use his first and third skills whenever they are off cooldown--]]
if characters["Beatrix"] ~= nil then
  if turn == 1 then
    characters["Beatrix"]:UseSkill(1)
  end
  if turn == 2 then
    DisableChargeAttack()
    characters["Beatrix"]:UseSkill(2)
    characters["Beatrix"]:UseSkill(1)
    characters["Beatrix"]:UseSkill(3)
  end
end
```

The problem with your script though is it will only use her skills on turn 1 and 2, and doesn't help when the enemy isn't in overdrive and doesn't keep up her 3 buff. It will also never charge attack after turn 2.

Here is my Beatrix routine that only activates skill 1 and 2 when the enemy is in overdrive, otherwise keep her skill 3 up and use HP pots to keep her alive:

```lua
if characters["Beatrix"] ~= nil then
    -- If skill 2 is on CD and skill 1 has been activated twice, turn it off by activating it once
    if not characters["Beatrix"].skill_2_available and (characters["Beatrix"]:HasStatusEffect("16451")) then
        characters["Beatrix"]:UseSkill(1)
    end 
    -- If skill 2 is on CD and skill 1 has been activated once, turn it off by activating it twice
    if not characters["Beatrix"].skill_2_available and (characters["Beatrix"]:HasStatusEffect("1645")) then
        characters["Beatrix"]:UseSkill(1)
        characters["Beatrix"]:UseSkill(1)
    end 
    -- If enemy is in overdrive and ODA is available, activate skill 1 twice and use ODA
    if enemy_1.overdrive_state == true and characters["Beatrix"].skill_2_available then
            characters["Beatrix"]:UseSkill(1)
            characters["Beatrix"]:UseSkill(1)
            characters["Beatrix"]:UseSkill(2)
    end
    -- Use pots to keep her HP up so she can use her skill 3
    if booleans["greenPotUsed_2"] == true and characters["Beatrix"].hp_percentage < 50 then
        UseBluePotion()
    end
    if characters["Beatrix"].hp_percentage < 50 then
        -- Replace with Bea's position
        UseGreenPotionOnPartyMember(4)
        if booleans["greenPotUsed_1"] == nil then
            booleans["greenPotUsed_1"] = true
        else
            booleans["greenPotUsed_2"] = true
        end
    end
    if characters["Beatrix"].hp_percentage >= 50 and not characters["Beatrix"]:HasStatusEffect("1181") then
        characters["Beatrix"]:UseSkill(3)
    end
end
```

**Comment by yuzurihaz** [comment]
ty very much
