### ISSUE TITLE
HasStatusEffect bugs or problem

### ISSUE THREAD

**Issue by nobody0014** [Masuzu/ZooeyBot#501]
I have been trying to use status effect for awhile now. Mostly it has been working fine. (tested triple attack up and double attack down and def down on the chars) However, I noticed that "1019_1_50" which is fire dmg cut 50% (from carbuncle) always gives out false which is not possible because I just summoned the carbuncle. 

Another thing too which is a suggestion to improve the bot.
Does enemy_1:HasStatusEffect works? 
Last I check it works fine in the lua script but always give out false even though the enemy already have def down.

**Comment by Masuzu** [comment]
Hello,

The feature `enemy_1:HasStatusEffect` is already supported and works the same way.
I might have to check for the ID of 1019_1_50, but you can now do it on your own thanks to the listener mode (https://github.com/Masuzu/ZooeyBot/wiki/Lua-Scripts-(playing-with-status-effects)#obtaining-status-effect-ids)
