### ISSUE TITLE
Improve speed when chain burst kills boss

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#502]
If attacking on a turn with a chain burst kills the boss, right now Zooey waits the AdditionalDelayInMsAfterXChainBurst time before refreshing/checking to see if the boss is dead. Since I'm using Mechanic for full chain burst every time, this is an additional 11.5 seconds on every battle. Could Zooey instead refresh right away and then wait if the boss isn't dead?

**Comment by ErogeSeiyuu** [comment]
then just turn down the additionaldelay to 0 and then put Wait(x) into your script
