### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by Shizukanawa** [Masuzu/ZooeyBot#504]
Can i have a refund since I haven’t been able to use the bot and you said that you couldn’t fix it.

**Comment by Masuzu** [comment]
Please send here the email address you used or transaction ID.

**Comment by Shizukanawa** [comment]
The email adress used for the account is deviousfinest@gmail.com. I used the stripe option.

**Comment by Masuzu** [comment]
Alright, thank you. I will try and do it later in the day.
