### ISSUE TITLE
Bot stucks at calibrating 

### ISSUE THREAD

**Issue by Premines** [Masuzu/ZooeyBot#505]
after i click quest to start nothing happens afterwards the mouse doesn't move

**Comment by Masuzu** [comment]
Hello,

First of all: detailed instructions to get started:
https://github.com/Masuzu/ZooeyBot/wiki/Basic-mode---story-quests,-free-quests-and-special-quests-automated-farming

Then, if the issue still persists:
https://github.com/Masuzu/ZooeyBot/wiki/FAQ#i-have-scaling-issues-again
