### ISSUE TITLE
Preferred Summon stuck and reload 

### ISSUE THREAD

**Issue by ariaanaa** [Masuzu/ZooeyBot#51]
I was set RerollSummonWhenNoPreferredSummonWasFound=true and RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true

but then zooey just reload the Test Machina Alpha page instead of going to battle for reload the summon list. Is this a bug? thank you!

**Comment by Masuzu** [comment]
Hi,
It's a bug indeed and I fixed it on my side (I could reproduce it and check that it was fixed with automated GW extreme+ farming).
I will release a fix later today.

**Comment by Masuzu** [comment]
Addressed in version 1.5.2:
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes

**Comment by ariaanaa** [comment]
nice and thanks for your hardwork!

**Comment by ariaanaa** [comment]
hi! I have test it and it comeback to this issue https://github.com/Masuzu/ZooeyBot/issues/40 
zooey reload the summon from trial battle for just 1 time and then she go to dimensional halo then retreat
