### ISSUE TITLE
Unregistered user with active license

### ISSUE THREAD

**Issue by moourns** [Masuzu/ZooeyBot#510]
I'm unable to use the program since it keeps telling me I'm unregistered even though I have a current and active license in the serial number file.

**Comment by rebokz** [comment]
Double check the serial number to make sure they match, also did you buy the bot on a separate computer then you're trying to run the bot on?

**Comment by moourns** [comment]
Same computer that I've always used, just resubscribed after a couple of months. Serial number matches perfectly.

**Comment by Masuzu** [comment]
Hello,
Thank you for reaching out.
Please check https://github.com/Masuzu/ZooeyBot/wiki/FAQ#i-get-an-unregistered-user-error-message
Then if you still have the issue, please redownload the key.txt file from the management page.
