### ISSUE TITLE
GW EX+ Farming - Event home page loads up almost instantly with result screen

### ISSUE THREAD

**Issue by ReinaryuIlyen** [Masuzu/ZooeyBot#512]
Having an issue, rarely and intermittently (but 3 times over Preliminary period) where the GW Event page will load up almost same time as results page, but the results page was not finished loading, so Zooey seems to get stuck and just sits waiting on the event page doing nothing.

Manually opening the results screen in pending raids allows Zooey to continue.

Screenshot of Zooeybot window as it happens, not sure what else can help narrow this issue down:
https://puu.sh/z4ngC/af3e3dbbbd.png

**Comment by Masuzu** [comment]
Hello,
Thank you for reaching out,
You have a slow Internet connection resulting in this "issue". With a stable 300 ms ping I can guarantee that you will not have such an issue at all, but will add a workaround in a next release to avoid this kind of rare situation.

**Comment by cobeng13** [comment]
Experiencing this too. Thanks
