### ISSUE TITLE
Wait for chain burst not working leading to skill cancellations

### ISSUE THREAD

**Issue by kommtodd** [Masuzu/ZooeyBot#518]
hi I noticed that recently the bot doesn't take into account ougi chain burst timings and when the next turn begins it attempts to use a skill but doesn't register because of the ougi wait time and as a result it skips the skill.

no modification was done to the timing of the script

**Comment by Masuzu** [comment]
Hello,
I can confirm that it does take into account chain burst timing unless it displays "Failed to parse attack result".
