### ISSUE TITLE
Accidental summon selection when starting NM

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#519]
When leaving Zooey running on nightmare 90, sometimes I come back and Zooey is alternating between clicking the Auto and Skip buttons in a fight with a summon not on my list selected (and will continue this for minutes). The text log does not indicate a summon being selected at all.

My theory (I haven't observed this happening) is that the summon select screen loaded while Zooey was in the middle of hitting the OK button again to get to the summon select screen. Then Zooey accidentally selected a summon, and accidentally hit the OK button to start the fight (since these are all more or less in the same place on the screen), all while still thinking it's hitting the button on the nightmare selection page.

**Comment by thebp2** [comment]
Screenshot of Zooey log when this happens:
![image](https://user-images.githubusercontent.com/32204823/35184478-326285e4-fdc4-11e7-9e93-acd77ebe5922.png)

**Comment by thebp2** [comment]
Managed to watch this happen finally, it is missing that the summon selection screen is up and continuing to click where the OK button for nightmare mode selection is.

**Comment by Masuzu** [comment]
This is a slow computer/internet connection issue. Please consider increasing the parameter `MaxWaitTimeBeforeRetry`.

**Comment by thebp2** [comment]
Ok, thanks!
