### ISSUE TITLE
I/O error: Permission denied

### ISSUE THREAD

**Issue by kit2361** [Masuzu/ZooeyBot#521]
Got this error while my license is still active.
![t1](https://user-images.githubusercontent.com/34981935/35184993-ce73cfce-fe37-11e7-9389-d31fc9349cee.jpg)
![t2](https://user-images.githubusercontent.com/34981935/35184994-ce9ddbac-fe37-11e7-9557-0099c8b4c7d5.jpg)

**Comment by Masuzu** [comment]
Did you check your antivirus settings/run it as admin mode?
I sometimes get the same but it is not an issue.

**Comment by VladiMio** [comment]
I've got the same issue.
