### ISSUE TITLE
Ilsa bullets count variable

### ISSUE THREAD

**Issue by wewladdie** [Masuzu/ZooeyBot#523]
Can we get a variable for Ilsa's bullets count like Korwa's fils variable (num_korwa_fils) ?

Maybe something like num_ilsa_bullets

For reference, the status ids are:

```
14311 Bullets [turn]
14312 Bullets [turn]
14313 Bullets [turn]
14314 Bullets [turn]
14315 Bullets [turn]
14316 Bullets [turn]
14317 Bullets [turn]
14318 Bullets [turn]
14319 Bullets [turn]
```

Thanks much

**Comment by wewladdie** [comment]
Not sure if I should open a new issue but this is related to bullet buff.

This is what i have for basic Ilsa usage:

```lua
if characters["Ilsa"] ~= nil then
	if characters["Ilsa"].skill_3_available and (characters["Ilsa"]:HasStatusEffect("14319")) then
		characters["Ilsa"].UseSkill(3)
		characters["Ilsa"].UseSkill(1)
	end
end
```
Essentially, I want Ilsa to use Skill 3 when she has 9 bullets, then use Skill 1 right after.

This crashes for some reason...

![rip](https://0x1a4.moe/i/6nlv5.png)

**Comment by Masuzu** [comment]
Hello,
There should be a different buff ID for each bullet count remaning.

**Comment by Masuzu** [comment]
Also I'd be careful when mixing in Viramate options such as:
```
![image](https://user-images.githubusercontent.com/5464705/35440701-d6b7a530-02a0-11e8-99f4-9fd504b9cf6e.png)
```

**Comment by Masuzu** [comment]
By the way you code is wrong:
It's `characters["Ilsa"]:UseSkill(3)`

Not with a dot

**Comment by wewladdie** [comment]
Ah right, sorry about the code.

Also, I know there are different buff ID for each bullet count, this is the same for Korwa. 

I'm asking if you can add a variable like Korwa's num_korwa_fils.

Thanks much.
