### ISSUE TITLE
GW buff stop Zooeybot

### ISSUE THREAD

**Issue by Ramkm77** [Masuzu/ZooeyBot#524]
Hi , yesterday I saw the bot stop on the event page without any reason, today I discovered when my crew switch on the gw buffs, and Zooey bot start new fight, it’s stuck coz of the buff animation any way to avoid that? Thx

**Comment by Masuzu** [comment]
Hello,
Thank you for reporting this issue.

**Comment by Masuzu** [comment]
Addressed in v2.7.0
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-7-0
