### ISSUE TITLE
Stuck at now loading page

### ISSUE THREAD

**Issue by onionknight107** [Masuzu/ZooeyBot#525]
During long-time runnig, the webpage sometimes stuck at now loading page for no reason, which requires a refresh before further operation. However, currently the bot does not response to this error and will wait forever for the next move. Could you please improve this? Thank you!
![qq 20180120230508](https://user-images.githubusercontent.com/32561965/35190730-65566476-fe36-11e7-8cd1-283e7473cc43.png)

**Comment by Masuzu** [comment]
Hello,
If this happens in the first place then it is already a bad sign!
When does this happen specifically?

**Comment by lyhonlam** [comment]
This often happen to me too and it started since the late december game update. I know this isn't Zooey fault cuz it happen when i play normally too.
Could you make zooey auto refresh when this occur ?.

**Comment by onionknight107** [comment]
I do think it's the internet connection's fault because I am living in a dormitory, and it also happens when I nornally play without using the bot. Sometimes I can use the bot hours long without encountering this, but sometimes it happens every ten minutes, and I think I started to encounter this in December.

**Comment by Masuzu** [comment]
I think it is more related to internet connection stability issues (using a share network and the likes). I do not plan to dwell too much with workarounds for such cases as it is similar to going down the rabbit hole.
I do not run into any of these issues while playing manually or not.
