### ISSUE TITLE
Bot unable to detect skill seal status for Anthuria and s.Beatrix

### ISSUE THREAD

**Issue by merun23** [Masuzu/ZooeyBot#526]
Hiya, been doing nm90 and 95 for the fire gw yesterday and today, and I've noticed that the bot doesnt detect that Anthuria and s.Beatrix is skill sealed.

I could settle nm90 without Anthuria but unfortunately not for nm95 

Helpful(?) info:
-s.Beatrix starts @ slot 2
-Anthuria's placed on backline @ slot 5
-placed at slot 2 and 4 after she comes out from backline
-when they're skill sealed by the boss, she zooeybote still tries to use their skills and get's stuck there
-on the console, it doesn't say that they're skill sealed, although it does so for mc and other units

**Comment by Masuzu** [comment]
Hello,
I will look into it but it should be similar to what happens when the Nighthound switch skill is used for instance (for testing purposes). Thank you for reporting this issue.
