### ISSUE TITLE
Using HasStatusEffect with enemy

### ISSUE THREAD

**Issue by onionknight107** [Masuzu/ZooeyBot#528]
The bot does not respond to the def buff of the wind guild war boss. Is there something wrong with my script or is this function still not supported yet?

if enemy_1:HasStatusEffect("1931_13") then
Summon(2)
end

**Comment by Hedova928** [comment]
That will only match the buff when it has 3 turns left, try the following 

```lua
if enemy_1:HasStatusEffect("1931_13") or enemy_1:HasStatusEffect("1931_12") or enemy_1:HasStatusEffect("1931_11") then
   Summon(2)
end
```

**Comment by Masuzu** [comment]
Great answer!
