### ISSUE TITLE
Calibrating issues at the first try.

### ISSUE THREAD

**Issue by shadowfinted** [Masuzu/ZooeyBot#529]
Hello good day. I've seen all the calibrating issues that were closed before but I just couldn't seem to work mine still. I haven't gotten to make it work for the first time even. 

here is the current status of my problem

![image](https://user-images.githubusercontent.com/35731150/35276933-103c2600-0080-11e8-8a6d-d7f015daf598.png)

I also noticed that whenever i alt-tab during this phase it seems to bug out and starts to move suddenly. I thought it started to work at that point but it seems it was just refreshing my game to the main page and it was saying something like Network Clear History of some sort from the console

attempting to change the banner results to this:
![image](https://user-images.githubusercontent.com/35731150/35277080-7375abb0-0080-11e8-8be2-d3bb7493930c.png)

![image](https://user-images.githubusercontent.com/35731150/35276791-8ffa4a9e-007f-11e8-913e-e558f1b82488.png)

also my CalibrationgDebugImage is empty like this:
![image](https://user-images.githubusercontent.com/35731150/35277563-230ac51e-0082-11e8-8e29-6ba3e8b43fd2.png)

Please and thank you. :)

**Comment by Masuzu** [comment]
Hello,

Just from the screenshot, your in-game layour looks abnormally small compared to what other people have and what I use. This is the issue. Are you sure you set your Chrome Zoom to 100% and you applied all the in-game settings detailed here https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation?
If you would like to debug the banner size, please do so from a coop room, as the JS query provided to do so only applies to quest banners from a coop room.

**Comment by Masuzu** [comment]
Oh and by the way, don't use the Mobile phone emulator when opening the devtools window. It'll shrink your elements.

**Comment by shadowfinted** [comment]
It works perfectly now. Thank you! :D
