### ISSUE TITLE
Zooey skips the step after "dismiss error popup"

### ISSUE THREAD

**Issue by JillVernus** [Masuzu/ZooeyBot#53]
As all we know, after using a Full Combo, server needs you to wait around 15~16s to place the next action, 
if you place any actions during the cooldown time, system will give you an error popup.

There is the bug I discovered : 

if turn == 1 then
	EnableChargeAttack()  --enable Charge Attack and give the boss a FullCombo
end
if turn == 2 then
	character_1:UseSkill(1)  -- Error popup > dismiss ...until cooldown over, then Zooey skip this step and use the next one!!
	character_1:UseSkill(2) 
end

please kindly look into it. thanks.

**Comment by JillVernus** [comment]
One more thing related to MaxNumPotionsToUse, 
if I set it to 5, "MaxNumPotionsToUse=5"
it actually uses the 6th Potions before stop,

**Comment by Masuzu** [comment]
Hi,
There are up to MaxNumActionRetries times where Zooey will try to dismiss the error popup and perform again the last action. After the last attempt, whether it were successful or not, Zooey will move to the next available action in your script.
I will add a new feature to wait for a user defined amount of time after a x-characters-ougi chain is performed later on this week when I have some time.

**Comment by Masuzu** [comment]
Thanks for reporting the bug with the incorrect number of potions used too
