### ISSUE TITLE
Help me build lua script for healing

### ISSUE THREAD

**Issue by salvanost** [Masuzu/ZooeyBot#530]
hello i'm stuck with healing script
for example
action 1: use panacea first
action 2: if panacea not available, use yuel skill 4 and 3
action 3: if both yuel's heal and panacea not available, use support potion
action 4: use green potion after action 1 to 3

here the raw script please help me fix the script 
thank you

-----------------------------------------------------------------------------------------------------------------
> 
function NumCharactersBelowHPPercentage(percentage)
  local sum = 0
  for name,character in pairs(characters) do
    if character.hp_percentage <= percentage then
      sum = sum + 1
    end
  end
  return sum
end

if NumCharactersBelowHPPercentage(75) >= 2 then
  if character_1.skill_1_available then
    character_1:UseSkill(1)
  else if character_2.skill_3_available then
    character_2:UseSkill(4)
    character_2:UseSkill(3)
  else
    UseSupportPotion()
end

if character_1.hp_percentage < 31 then
   UseGreenPotionOnPartyMember(1)
end
if character_2.hp_percentage < 31 then
   UseGreenPotionOnPartyMember(2)
end
if character_3.hp_percentage < 31 then
   UseGreenPotionOnPartyMember(3)
end
if character_4.hp_percentage < 31 then
   UseGreenPotionOnPartyMember(4)
end

if enemy_1.hp_percentage < 25 and NumCharactersBelowHPPercentage(55) >= 2 then
  UseBluePotion()  
end

>

**Comment by salvanost** [comment]
update/revision (no error for nm 95)

function NumCharactersBelowHPPercentage(percentage)
  local sum = 0
  for name,character in pairs(characters) do
    if character.hp_percentage <= percentage then
      sum = sum + 1
    end
  end
  return sum
end

if NumCharactersBelowHPPercentage(67) >= 2 then
  if character_1.skill_1_available then
    character_1:UseSkill(1)
  else if character_2.skill_3_available then
    character_2:UseSkill(4)
    character_2:UseSkill(3)
  else
    UseSupportPotion()
  end
  end
end

if character_1.hp_percentage < 31 then
   UseGreenPotionOnPartyMember(1)
end
if character_2.hp_percentage < 31 then
   UseGreenPotionOnPartyMember(2)
end
if character_3.hp_percentage < 31 then
   UseGreenPotionOnPartyMember(3)
end
if character_4.hp_percentage < 31 then
   UseGreenPotionOnPartyMember(4)
end

**Comment by Masuzu** [comment]
Hello,
Please check the documentation. There are character_X.skill_Y_available variables for this use case.
