### ISSUE TITLE
can't use slave mode

### ISSUE THREAD

**Issue by yuzurihaz** [Masuzu/ZooeyBot#532]
Slave mode - Initialization
Initializing slime-blasting modeCalibrating
Successfully hooked to the Home button
Clear network request history
Vertical offset: 85
Calibrating

ps2: when i try again it become like this 
Slave mode - Initialization
Initializing slime-blasting modeCalibrating

pls make 1366*768 use slavemode  : (

1366*768 screen scale
![cant cop](https://user-images.githubusercontent.com/35253544/35370410-3079f7e4-01c0-11e8-918b-dafaa1947087.jpg)

**Comment by Masuzu** [comment]
Hello,
Failures to calibrate on the slave window are usually due to not following the instructions on the Wiki documentation about closing/opening/starting the extensions in the correct order.
