### ISSUE TITLE
Making ZooeyBot stop recasting Orchid's 1st skill while Puppet Strings is under effect

### ISSUE THREAD

**Issue by GumiFlatline** [Masuzu/ZooeyBot#533]
Hi,
I wanted to write a more elaborated script for Orchid, so ZooeyBot don't recast her 1st skill while Puppet Strings is in effect, or when she's afflicted by Tangled Strings debuff. So I did the follow:
```
if characters["Orchid"] ~= nil then
      characters["Orchid"]:UseSkill(1)
      characters["Orchid"]:UseSkill(3)
 -- If Orchid is already under Puppet Strings (60401) or Tangled Strings (60402) stats effect 
booleans["Puppet Strings"] = true
for index, buff in pairs(characters["Orchid"].buffs) do
  if buff.id == 60402 then
      booleans["Puppet Strings"] = false
  end
  if buff.id == 60401 then
      booleans["Puppet Strings"] = false
  end
end
if booleans["Puppet Strings"] then
      characters["Orchid"]:UseSkill(1)
end
end
```
But ZooeyBot doesn't stop casting Orchid's 1st skill on CD. What should I do?

And yes, RetrieveStatusEffects=true on ZooeyBot.ini.

**Comment by Shamool** [comment]
Pardon me if I'm wrong, but the use of skill 1 is tagged under the if condition that Orchid is there? You should tag the casting of skill 1 to the condition when the buff is absent for example, to cast when no puppet strings..

**Comment by GumiFlatline** [comment]
But that's exactly what I tried to do (disregard the second line because that was my last attempt).

Buff ID 60401 is her Puppet Strings status, while 60402 means Tangled Strings debuff.

Having that in mind, I tried to make Zooey only cast Orchid's 1st skill when she didn't have either Puppet Strings or Tangled Strings status effect.

If Zooey was able to cast her 1st in the first turn of battle (again, disresgard the second line), something is preventing Zooey to retrieve her status effect, or I fucked something along the way.

Correct me if I'm wrong, but shouldn't Zooey list each character status effect each turn? Because it's only listing my opponent's status effect.

**Comment by Shamool** [comment]
No, that wasn't what I was referring to. The part using the booleans look to be correct in my opinion. It is this part:

if characters["Orchid"] ~= nil then
      characters["Orchid"]:UseSkill(1)
      characters["Orchid"]:UseSkill(3)

Since UseSkill(1) is tagged under
"if characters["Orchid"] ~= nil then"

As long as Orchid is on the frontline, zooey will try to do two things, cast skill 3 and 1. So every turn, as long as orchid is alive and either of skills are off cd, won't zooey cast them immediately?

**Comment by GumiFlatline** [comment]
Yeah, that's why I told you to disresgard the second line of my script (it seems I can't edit posts through mobile), because only UseSkill(3) is under "if characters["Orchid"] ~= nil then". It look like this now (just to illustrate better):
```
if characters["Orchid"] ~= nil then
      characters["Orchid"]:UseSkill(3)
 -- If Orchid is already under Puppet Strings (60401) or Tangled Strings (60402) stats effect 
booleans["Puppet Strings"] = true
for index, buff in pairs(characters["Orchid"].buffs) do
  if buff.id == 60402 then
      booleans["Puppet Strings"] = false
  end
  if buff.id == 60401 then
      booleans["Puppet Strings"] = false
  end
end
if booleans["Puppet Strings"] then
      characters["Orchid"]:UseSkill(1)
end
end
```
But even under such conditions, Zooey still tries to cast Puppet Strings. Or is "if characters["Orchid"] ~= nil then" causing any conflict?

**Comment by Shamool** [comment]
Hmm... Then I'm stumped. I don't have Orchid to test either. Have you tried going back to using HasStatusEffect? Otherwise, I'd just wait for Masuzu. Sorry for not being able to help.

**Comment by Masuzu** [comment]
Hello,
First of all, did you check this new mode? https://github.com/Masuzu/ZooeyBot/wiki/Lua-Scripts-(playing-with-status-effects)#obtaining-status-effect-ids
```
if characters["Orchid"] ~= nil and not characters["Orchid"]:HasStatusEffect("60401") then
  characters["Orchid"]:UseSkill(1)
end

**Comment by GumiFlatline** [comment]
@Shamool no worries and thanks for trying to help me.

@Masuzu thanks for answering me.
Yes, I used the new mode to retrieve Orchid's Puppet Strings and Tangled Strings ID.

And if I understood correctly, inserting "and not" would nullify a action, correct? If so, could I add something like this:

```
if characters["Orchid"] ~= nil and not characters["Orchid"]:HasStatusEffect("60401") and not characters["Orchid"]:HasStatusEffect("60402") then
...

```
Or should I add a extra line?

Anyway, thanks again for answering me. I only wanted to write something like this to prevent Zooey to keep clicking Orchid's 1st unnecessary, what would cause a error message (telling that Puppet Strings was already under effect).

**Comment by Masuzu** [comment]
Oh, sorry I forgot about the Tangled string debugg as well. That's right, your `if` condition should do what you want it to do. Extra lines are just for clarity (http://dev.minetest.net/Lua_code_style_guidelines)

**Comment by GumiFlatline** [comment]
Oh, those guidelines will be very usefull. Now I understand it clearly. Thanks for sharing it!

Also, thanks again for the help @Shamool @Masuzu !
