### ISSUE TITLE
How to make bot attack until turn 3

### ISSUE THREAD

**Issue by readmynameplease** [Masuzu/ZooeyBot#534]
how to make the bot attack until turn 3? then use skill at turn 3

**Comment by Shamool** [comment]
If you don't write anything in the luascript for combat, it'll automatically attack every turn. E.G. if you want to skill on T3

if turn==3 then
character_(fill in character position):UseSkill(fill in skill number)
end

If you want specific characters, there is the syntax under lua scripts in documentation
