### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by wilfredmaple** [Masuzu/ZooeyBot#535]
![issue](https://user-images.githubusercontent.com/21032033/35430697-5ed3ca9e-02b4-11e8-91da-20437e4bd9ea.png)
![issue2](https://user-images.githubusercontent.com/21032033/35430854-ffceb0b2-02b4-11e8-8c57-724b4d0cb719.png)

I encountered this right after i registered, how do i fix this? do i have to buy?

**Comment by Masuzu** [comment]
Hello,
Indeed, helpful services do not come for free.

**Comment by wilfredmaple** [comment]
Okay thanks
