### ISSUE TITLE
I'm sorry but i still cannot figure out whats wrong and i cant seem to find my problem from the FAQ regarding licensing issues

### ISSUE THREAD

**Issue by Chino-chan** [Masuzu/ZooeyBot#536]
it keeps asking me to renew my license
![image](https://user-images.githubusercontent.com/11248377/35433737-75ad6ecc-02bf-11e8-9fec-bd59ab8bf374.png)

**Comment by Chino-chan** [comment]
is it due to my windows version or smth?

**Comment by Masuzu** [comment]
Did you check your licence info on https://poker-bot.azurewebsites.net/ZooeyBot/en/Manage?
If it's green, then:
- download again the key.txt file from this same management page and overwrite the one you are using
- when you start ZooeyBot, a file named `serial_number.txt` is created. Make sure that its contents matches the one on https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber

**Comment by Chino-chan** [comment]
my license status is red tho

**Comment by Masuzu** [comment]
A licence purchase is required to extend the licence duration.
