### ISSUE TITLE
Serial number suddenly changed, and then changed yet again the next day.

### ISSUE THREAD

**Issue by violafayde** [Masuzu/ZooeyBot#537]
I tried to enter zooey bot yesterday and it told me the serial number did not match. Looking at the serial.txt, i was surprised to find that the serial number suddenly changed. I then changed the new serial on the website and it worked. However, today the serial number changed again, but back into the original serial, and I am unable to use the bot for 4 days now because of the cooldown. Please help ASAP.

**Comment by Masuzu** [comment]
Hello,
Is that really the case? Did you change your PC or something?

**Comment by violafayde** [comment]
no. I have been using my one and only laptop to use the bot.

**Comment by Masuzu** [comment]
It could be updates. I'll lift temporally the limitation this week end.

**Comment by violafayde** [comment]
I am still unable to change my serial number back :(
