### ISSUE TITLE
GBF's own memory leaks might be causing problems.

### ISSUE THREAD

**Issue by MGX94296** [Masuzu/ZooeyBot#541]
For the last few days, I've been having a consistent error where Chrome would freeze my GBF tab due to it taking up too much memory. Since this only happened when Zooey Bot was on, I looked through here to see if I could find a solution. Adding Refresh() and WithWaitTime() to my scripts didn't help, so I decided to do some investigation.

As a disclaimer, Sarasa Bot works fine, so I don't think I have any major system compatibility errors. I can give my PC specs if that helps.

![gbf_memory_leak_00](https://user-images.githubusercontent.com/35868013/35472083-82f97900-031d-11e8-99cc-46ac390314ff.PNG)

Anyways, when I open a new instance of GBF, Chrome's Task Manager reports it uses ~75 MB.

![gbf_memory_leak_01](https://user-images.githubusercontent.com/35868013/35472108-d7d10ac4-031d-11e8-8bef-1038d8a62827.PNG)

Upon getting into a battle it jumps up to ~200 MB,

![gbf_memory_leak_02](https://user-images.githubusercontent.com/35868013/35472111-e841eeaa-031d-11e8-8ced-04dcbba3e6f5.PNG)

and as more battles are done that memory footprint

![gbf_memory_leak_03](https://user-images.githubusercontent.com/35868013/35472117-f9cb3dfc-031d-11e8-8040-491fb2cf718d.PNG)

climbs ever higher. I didn't have the time to keep going to see if Chrome would cut it off, but if anyone wants to try you can speed up the process by repeatedly refreshing mid-battle. I think loading in the sprites is what's clogging things up.

![gbf_memory_leak_04](https://user-images.githubusercontent.com/35868013/35472135-3dbe53dc-031e-11e8-9295-cf3ff0b89bb6.PNG)

The huge footprint persists even after exiting Angel Halo, so there doesn't seem to be any in-game fixes. I tried messing with my game settings to see if I could prevent or slowdown the ramp up, but it didn't matter what I used. Japanese or English language, Standard or Beta version, Lite or Standard animations, Hardware Acceleration on or off, the memory footprint would grow and presumably eventually freeze. The only way I could make the footprint go down was by closing the tab and opening a new instance.

I've had no problems with Chrome forcing GBF to close when playing it long term normally. and I haven't seen any complaints in the sites I browse either. So my current theory is that while Zooey Bot cleans up after itself every few battles, eventually GBF's memory footprint grows so large that Zooey Bot's extra load causes Chrome to freak out.

I don't know if anyone else is having this issue or if it's just me. Beyond hoping that Cygames fixes their code, the only fix I can think of off the top of my head is a new option where Zooey Bot moves to a new tab every *insert user variable* battle(s).

Thank you for reading all of that. Zooey Bot has made my GBF experience so much better, so I hope you're able to fix this.

**Comment by Miyoumu** [comment]
I can 100% vouch for this, though I've been having the issue with Sarasa Bot, particularly (especially) in Grand Order raids but I can confirm that I've experienced this exact issue on several different occassions.

**Comment by onionknight107** [comment]
I have this same issue

**Comment by MGX94296** [comment]
I did some more runs to try and find the cutoff point where Chrome freezes GBF on my browser.

![breakpoint_00](https://user-images.githubusercontent.com/35868013/35479071-70419dda-03a2-11e8-8dc6-015d309a5af0.PNG)

~2.64 GB,

![breakpoint_01](https://user-images.githubusercontent.com/35868013/35479076-8287bb50-03a2-11e8-8ee9-9201c0df87ca.PNG)

~2.61 GB,

![breakpoint_03](https://user-images.githubusercontent.com/35868013/35479078-9263c55a-03a2-11e8-97a7-705b66f82d29.PNG)

and ~2.66 GB.

2.60 GB seems to be a consistent failure point, though that could change depending on PC specs.

I hope this helps.

**Comment by Masuzu** [comment]
Hello,
If the issue reported here is one related to the game itself following one of the recent game updates, you can just hope for Cygames to do something about it.

**Comment by onionknight107** [comment]
Does anyone have a temporary solution to this problem? I have to manually press end process in the task manager to prevent the game from freezing. I wonder if there are tools that automatically purge memory.

**Comment by onionknight107** [comment]
Well on my side the memory keeps accumulating regardless of reloading.

**Comment by Masuzu** [comment]
Even without Zooey Bot?

**Comment by onionknight107** [comment]
Right. Although it accumulates at a much slower rate (it takes me 50 minutes to reach 3 gigabytes), the memory accumulates even withouth Zooey regardless of reloading, unless I close the tab and reopen it. Besides, without the bot, the game does not freeze even at high memory usage, so memory leak does not cause any problem when I play without bot.

**Comment by Iysoni** [comment]
I have the same problem too, died after only 8 Angel Halos. Each stage only takes one turn for me.
I have 16GB ram too, never had any problems until few days ago.
Without bot I can play for hours with multiple windows of the game, watching vids, many chrome tabs etc. Whereas with bot and no other chorme windows open it couldn't even last more than 10mins.
Mine hit the breakpoint at around 4GB...

**Comment by Masuzu** [comment]
> Even without Zooey Bot?

> Right.

It is not my issue then.
