### ISSUE TITLE
Treasure mode stuck at initialization for impossible.

### ISSUE THREAD

**Issue by nobody0014** [Masuzu/ZooeyBot#546]
^self-explainatory. i tried to use zoi to automate the impossible raid (which is added during last treasure event) but was unable to do so. It stuck at after zooey bot initialized (at the event page)

**Comment by Masuzu** [comment]
Hello,

Impossible mode is already supported
https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode-(Guild-Wars-and-others)#general-configuration

The wiki page was updated accordingly.
