### ISSUE TITLE
Zooey won't click on vary hard mode 

### ISSUE THREAD

**Issue by meteoshower** [Masuzu/ZooeyBot#547]
Hello i have problem on treasure event mode  when zooey head to http://game.granbluefantasy.jp/#event/treasureraid064 (Auld Lanxiety Homepage) then she stuck and wont click vary hard banner but if i manual click  just once zooey will work  and head to click banner vh mode. so   after zooey work many time She have some chance to stuck on event home page again (and yeah i have to manual click again). in this case if zooey stuck at eventpage for a long time  my  chrome window will freeze  so that i have to End task my chrome ._. 
. And last when zooey head to summon selection she have to refresh summon window 1 time  and then she can pick summon to fight so i think this case is not too a problem .
I hope you can fix soon i need to farm dama powder .

**Comment by nobody0014** [comment]
i think for vh mode, since it doesnt require items, you should be using event mode.

**Comment by Masuzu** [comment]
Hello,
As said above.
