### ISSUE TITLE
Treasure raid event 'impossible' is not working

### ISSUE THREAD

**Issue by greatmany** [Masuzu/ZooeyBot#548]
When set to EX the bot functions correctly but when set to impossible it stops moving once it gets to the event page

**Comment by Masuzu** [comment]
Do you mean that setting the difficulty to `impossible` does not work as intended?

**Comment by greatmany** [comment]
Yes setting it to impossible does not work

**Comment by nobody0014** [comment]
This is what i mean when I said zoi stuck for impossible, jesus. It's a pain in the arse waiting for a few days for a reply and then have an auto reroute answer.

**Comment by greatmany** [comment]
will this be fixed soon?

**Comment by nobody0014** [comment]
Hell if i know, he has been fixing other bugs but not this one though.
