### ISSUE TITLE
lua script error sometimes

### ISSUE THREAD

**Issue by utenshien** [Masuzu/ZooeyBot#55]
http://i.imgur.com/YAOmmPl.png
it's fine most of the time, but sometimes this error just pops up and zooey will crash
i don't think it's my script's issue and can't figure it out

my script below

EnableChargeAttack()
if character_1.name == "<player's name>" then
  character_1:UseSkill(4)
  character_1:UseSkill(3)
  character_1:UseSkill(2)
  character_1:UseSkill(1)
end
if character_2.name == "ヴィーラ" then
  character_2:UseSkill(1)
  character_2:UseSkill(2)
  character_2:UseSkill(3)
end
if turn == 1 then
  characters["ヴィーラ"]:UseSkill(4)
end
if character_3.name == "ナルメア" then
  character_3:UseSkill(2)
  character_3:UseSkill(1)
end
if character_4.name == "ジャンヌダルク" then
  character_4:UseSkill(2)
  character_4:UseSkill(1)
end
if characters["カリオストロ"] ~= nil then
  characters["カリオストロ"]:UseSkill(3)
  characters["カリオストロ"]:UseSkill(2)
  characters["カリオストロ"]:UseSkill(1)
end

**Comment by Masuzu** [comment]
Hi,

The only case I see for now where it could happen would be failure to retrieve the "combat state" (list of characters alive, list of abilities available and so on). This can happen after a long session if Zooey does not regularly clear the DevTools network history (please check the parameter `ChromeDevToolsWindowDockedOnTheRight`).
I never found myself in this situation.

**Comment by utenshien** [comment]
my devtools window docks on the right, and i already set the parameter to true
should i clear browser history?

**Comment by utenshien** [comment]
anyway, not a big deal
zooey is a good tool, thank you for your effort sir, i really appreciate it
