### ISSUE TITLE
Solution for Memory Leak

### ISSUE THREAD

**Issue by onionknight107** [Masuzu/ZooeyBot#550]
Turning off sound inside the game setting seems to solve the previous memory leak issue. Since many people are having the same issue, I felt that I should post the solution I found.

**Comment by Iysoni** [comment]
Thankyou so much! This is the only fix that works! 
@Masuzu Maybe an option to turn off sound? :)

**Comment by Masuzu** [comment]
@onionknight107 Thank you, very informative indeed!
@Iysoni #DoItYourself

**Comment by Masuzu** [comment]
Addressed as of v3.x
