### ISSUE TITLE
Trouble with installation

### ISSUE THREAD

**Issue by CorrinKrow** [Masuzu/ZooeyBot#551]
Currently trying to install ZooeyBot however, am having a problem loading unpacked extension.

It displays the message "could not load manifest"

![image](https://user-images.githubusercontent.com/36133340/35779406-5421dcaa-09c4-11e8-821c-2c9bca843490.png)

Any help would be appreciated

**Comment by Masuzu** [comment]
Hello,
You must select and load the zooey-bot-extension folder.
You got the wrong folder.

**Comment by CorrinKrow** [comment]
The zip file I downloaded doesnt seem to have that folder when I extract it

**Comment by CorrinKrow** [comment]
Nevermind, realised i downloaded the wrong file.
