### ISSUE TITLE
Unregistered User

### ISSUE THREAD

**Issue by cobeng13** [Masuzu/ZooeyBot#554]
Sorry if I missed something, but I haven't touched my account in a week or so but it is still active (has some days left).
I opened the bot now, and it said I'm an unregistered user so I tried to update my key.txt and serial_number.txt to match what's on my account, but still pops up with this error. I updated my serial number so I cannot do so for another 4 days.

**Comment by cobeng13** [comment]
the serial number on the page and on the generator does not match

**Comment by Masuzu** [comment]
Hello,
You do not have to modify the key.txt (or rather, it should not be modified at all!)
As for the 4 day limitation, I will lift it temporarily in 10 hours from now.

**Comment by cobeng13** [comment]
I successfully updated my serial, thanks @Masuzu
