### ISSUE TITLE
Paused in debugger

### ISSUE THREAD

**Issue by shadowfinted** [Masuzu/ZooeyBot#555]
Good day!

For a while now this has been happening repeatedly while doing extreme trials. It doesnt take long during the botting phase and this happens.  I noticed that the whole thing kinda lags down then the "Paused in debugger" appears. 

![image](https://user-images.githubusercontent.com/35731150/36007427-58d28df0-0d7d-11e8-891a-4ecb4d156b45.png)

**Comment by Masuzu** [comment]
Good day!
Please make sure to always have the Network tab active instead and to configure properly the parameter `ChromeDevToolsWindowDockedOnTheRight` or it'll happen, as stated in the installation guide.
