### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by tidusZX** [Masuzu/ZooeyBot#557]
I keep getting this error after I start the bot and cant proceed.

![capture](https://user-images.githubusercontent.com/33868380/36034095-e8507634-0ded-11e8-91ae-ad3d6bc222f9.PNG)
![capture](https://user-images.githubusercontent.com/33868380/36034113-f2975cca-0ded-11e8-8198-8d39e46dfcab.PNG)

**Comment by Masuzu** [comment]
This can be ignored.
