### ISSUE TITLE
Cannot retreat from trial mode

### ISSUE THREAD

**Issue by aysien** [Masuzu/ZooeyBot#558]
![bug bot](https://user-images.githubusercontent.com/31809167/36035317-da16bf90-0df9-11e8-8b80-234124a91800.jpg)

Always happen on nightmare difficulties
`NightmareModePreferredSummons=titan_1`
`RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true`

Bug Replication Flow:
1. Go to choose summon on NM mode
2. Cannot get preferred summon
3. Go to trial mode
4. Go to choose summon on NM mode
5. Success to get the preferred summon
6. Back again to trial mode
7. Bot get confuse think already inside NM battle but actually it still in trial mode

Never happen to me on Version 2.6.1 on January Guild War
But happen quite often on 2.7.2

Any solution?

**Comment by Masuzu** [comment]
Wow, it looks like you are lagging a lot after moving back to the quest menu. The menu to retreat from the trial battle should pop out right after.
