### ISSUE TITLE
Time duration of licensing

### ISSUE THREAD

**Issue by Shamool** [Masuzu/ZooeyBot#559]
Recently, I just noticed as I was about to extend that the time duration of the extension has been changed from a month to 3 weeks. I would like to confirm if it was deliberate and the extension only last for 3 weeks now? Is the extension for 1 month still available?

**Comment by devvah** [comment]
It's a bug, extension still lasts whole month.

**Comment by Shamool** [comment]
Sorry for the late reply, thank you very uch for helping me confirm this

**Comment by Masuzu** [comment]
The display issue was fixed.
