### ISSUE TITLE
Error message when botting 

### ISSUE THREAD

**Issue by tidusZX** [Masuzu/ZooeyBot#560]
![4559cafb-4775-41a9-91d8-c324c3c108de](https://user-images.githubusercontent.com/33868380/36058717-055ad1c8-0e63-11e8-80f8-35b640803335.jpeg)

The bot will run fine for awhile but after a few minutes of botting, this will pop up and unless I close the pop up the bot will stop running. Anyway to surpass this?

**Comment by Masuzu** [comment]
Game version update, you can't do anything about this.
