### ISSUE TITLE
Fenrir NM being ignored after Zooey tries to refresh summon

### ISSUE THREAD

**Issue by GumiFlatline** [Masuzu/ZooeyBot#561]
Hi,
Like the title says, if Fenrir NM spawns but my preferable summon isn't available, Zooey, as usual, would try to refresh summon through Trial Battle, but after retreating from it, Zooey proceed to repeat EX again, without trying to enter NM again during the 1-hour availability.

There's nothing wrong on command prompt screen, but it seems Zooey is mistaken Trial Battle for NM, thinking that it finished NM after retreating from Trial.

**Comment by Masuzu** [comment]
Hello,
Closing as it was double checked and could not be reproduced.
