### ISSUE TITLE
Battle 2/-1 ?

### ISSUE THREAD

**Issue by CyrusLS** [Masuzu/ZooeyBot#562]
After the first battle zooey bot shows battle 2/-1 and then stops, expecting the results page to appear I assume. I appear to get no response errors even if I increase the delay in the .ini file. I have chrome devtools up, but I'm uncertain if that has anything to do with zooey's success on server responses.
![battles](https://user-images.githubusercontent.com/36385832/36079241-fef8354a-0f35-11e8-92ca-a77f2cfc8c1c.PNG)

lua script:

if battle == 1 then
character_1:UseSkill(4)
character_3:UseSkill(2)
end

if battle == 3 then
character_1:UseSkill(1)
character_2:UseSkill(1)
character_4:UseSkill(3)
end

**Comment by Masuzu** [comment]
Make sure to have your Network tab look like this:
![image](https://user-images.githubusercontent.com/5464705/36146537-4b6d732e-10b5-11e8-9d22-c3e873164030.png)

**Comment by nesiaya** [comment]
Hi, I'm having an identical problem on my desktop, the network tab is as it should be etc, tried messing around with wait times but it just doesn't register the attack button has been pressed. Problem hasn't come up in previous versions, used to work fine on it.
