### ISSUE TITLE
Error on parameter ChromeDevToolsWindowDockedOnTheRight

### ISSUE THREAD

**Issue by athenatan** [Masuzu/ZooeyBot#563]
My chrome has dev tool with network tab docked on the right and the parameter is set to true
but I still got this error.
![image](https://user-images.githubusercontent.com/13170289/36087982-cbd004d6-1007-11e8-9153-812406fc5722.png)

**Comment by Masuzu** [comment]
Your time is better spent doing something else or on https://poker-bot.azurewebsites.net/Marketplace/Home, trust me on this.
