### ISSUE TITLE
DevTool "paused in debugger"

### ISSUE THREAD

**Issue by SchismEternel** [Masuzu/ZooeyBot#565]
Hey there ! I've been having this annoying problem, for about a week now, which prevents me from farming the fenrir showdown among other things. Whenever I launch zooeybot it'll work just fine for about 10-15 min, then the window I run GBF on will freeze and show the message "paused in debugger". 

https://puu.sh/zm5f4/ff51453801.png

When I press the "play" button, the game resumes but ZooeyBot invariably crashes.
I did try to search for possible solutions on the internet but, since I know nothing about DevTool, I couldn't find anything. I have no idea where this problem could come from since I've never encountered it before. I thought it might be due to the fact that I am using the latest version of Zooeybot but using the older ones changed nothing.

What should I do ?

**Comment by agesa** [comment]
Turn sound off.  This is a problem outside of the bot as well, though it seems the bot makes it worse.

**Comment by SchismEternel** [comment]
You mean the sound in the game right ?

**Comment by thebp2** [comment]
Yes. Or play on lite mode.

**Comment by Masuzu** [comment]
Adding fuel to the fire: https://www.reddit.com/r/Granblue_en/comments/7wc4w5/chromes_latest_version_breaks_granblue_memory/

**Comment by ryokage** [comment]
any help wit this because I started getting it with Guild war but didn't have problem in fernir. Need help fixing it asap for gw

**Comment by JeremySDev** [comment]
I'm having the same issue tried the fixes mentioned above as well
