### ISSUE TITLE
Handling on monitors lower than 800 pixels height

### ISSUE THREAD

**Issue by ravenknit** [Masuzu/ZooeyBot#566]
I play on my laptop while overseas on assignment. However the laptop is only up to 1368X768. Is there no way to configure Zoeybot on this? I note that when I try the settings in the guide, even the "OK" button isn't covered when selecting a quest.

**Comment by Masuzu** [comment]
You could rotate your screen 90 degrees: https://www.laptopmag.com/g00/articles/fix-sideways-screen-computer?i10c.encReferrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmZyLw%3D%3D&i10c.ua=1
