### ISSUE TITLE
party_selection script sample

### ISSUE THREAD

**Issue by meisterv** [Masuzu/ZooeyBot#569]
Ever since updating the bot to 2.8 it forces me to use party_selection.lua ,
can someone be kind enough to enlighten me because I don't understand
how this thing works and I'm not good at making scripts myself.

If possible, how can I turn of the programmatic party selection?
I do fine before when running showdown, raids, slimming
but now I'm stuck and need help badly.
![image](https://user-images.githubusercontent.com/36479586/36210885-942e3fbe-11da-11e8-92b9-1f9fd225e316.png)

Thank you in advance.

**Comment by ladysour** [comment]
I personally leave it blank. But your error is cause you didn't put the 'then' after "if selected_summon == Bahamut_1" and probably in the if loop above that as well

**Comment by Masuzu** [comment]
It looks like someone gave a valid example https://poker-bot.azurewebsites.net/Marketplace/Listings/Details/be7ad3a1-233f-4974-9a06-e76e5f99dc18
