### ISSUE TITLE
Key refusing to update

### ISSUE THREAD

**Issue by Akaharu4U** [Masuzu/ZooeyBot#571]
I've followed instructions to the letter and hadn't changed anything in the files since previously using the bot 2 days ago. It mentioned an update, so I followed the steps for that. The key is now refusing to update whenever I edit the file and nothing I'm doing is fixing the issue. 

I open the serial_number.txt and edit it, saving. When I go to start ZooeyBot it still says I'm an unregistered user. The serial number generator file is even properly giving me my new number but this txt is just refusing to update and be useful. I tried to delete it and make a new .txt file but that just changed the new one to the old content too.

**Comment by Masuzu** [comment]
Hello,
You do not edit the file `serial_number.txt`. You update the serial number displayed on [this page](https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber) if the one in the `serial_number.txt` file does not match.
