### ISSUE TITLE
Zooey bot refresh Result page before start next quest

### ISSUE THREAD

**Issue by Poko302** [Masuzu/ZooeyBot#573]
I use zooey bot to farming GW EX+
I notice weird behavior after the battle ended. Zooey bot always wait a few second then refresh result page 1 time and wait a few second before starting new quest.

Anyone have the same problem?

I used the lastest version (2.8.0) 
I did not notice the problem when I use 2.7.2 farming Fenrir. The reason why I switch because Zooey bot got a bug to summon FLB Bahamut at Turn 1 in first position. I write Summon(1) and it returned an error. It seems to be fixed in 2.8.0

**Comment by Masuzu** [comment]
This is the expected behaviour if you do not have a good ping.
You can increase the value of the parameter `WaitTimeInMsAfterEventPageIsLoaded` to 5 seconds for instance if want to wait for the event page tofully  load before proceeding to the summon selection screen.
