### ISSUE TITLE
New verification process

### ISSUE THREAD

**Issue by rockysilver** [Masuzu/ZooeyBot#575]
I just ran into a new type of bot check, didn't had a chance to take a screenshot, but instead of a pop up, there is a button that you have to press when you pick a summon. The check doesn't stop you from picking a summon, so I assume it won't stop the bot from processing.

**Comment by Masuzu** [comment]
I managed to get a screenshot of the issue.
I will follow up in https://github.com/Masuzu/ZooeyBot/issues/579
Please stay safe for today and wait for a workaround to be provided.
