### ISSUE TITLE
New Bot Detection

### ISSUE THREAD

**Issue by onionknight107** [Masuzu/ZooeyBot#578]
CY seems to introduce a new bot detection mechanism. I don't know how to trigger this, but hopefully you can update the bot so that everyone can be safe during GW @Masuzu .

![qq 20180215020553](https://user-images.githubusercontent.com/32561965/36244724-5eaeed6e-11f5-11e8-9359-9b74bc022616.png)

**Comment by onionknight107** [comment]
Important: You cannont trigger this if you are using Viramate's favorite summon function. You will skip the verification. So disable that function right now before getting banned.

**Comment by Masuzu** [comment]
A workaround will be released in 12h from now.
I will follow up in #579
Forgive me if posts are deleted, all of them are very helpful but your safety goes first!
