### ISSUE TITLE
Zooey bot cannot restart quests

### ISSUE THREAD

**Issue by Caropt** [Masuzu/ZooeyBot#580]
After update2.7.2 , lots of "No response received after pressing (attack button/using the abillity) for an abnormally long time" error.

It works on Battle 1, but it cannot repeat the quests.

If a quests has Battle 3(e.g. Fenrir ex), Zooey bot proceed to next stage but cannot runs at next stage.

And if only battle 1(e.g. GW), Zooey bot move to result page but cannot restart the quest.

How can I solve this problem?

Please see a part of log below.
![1e893439a730a399b3ade2b13b777d99](https://user-images.githubusercontent.com/7865951/36244515-d3bd285e-1269-11e8-84be-c5f9a7a4172d.png)

MinWaitTime option is long enough(more than 2000) to work on 2.6.0.

**Comment by Masuzu** [comment]
Hello,
"No response received after pressing the attack button".
Make sure your Network tab looks like this:
![image](https://user-images.githubusercontent.com/5464705/36249166-1cedcea0-123a-11e8-94b8-f1627836ebed.png)

And that you closed all the Devtools window on other tabs (sometimes I forget to close all of them in some hidden tab and the same thing as you happens).
