### ISSUE TITLE
Sharing about bot verification here

### ISSUE THREAD

**Issue by salvanost** [Masuzu/ZooeyBot#581]
There so much post about bot verification
Let’s wait for Mazusu and share information here about the bot verification

1. Did the verification only come out 1 time? Or frequent?
2. Did the bot still continue if the only summon showed is the prefered one?
3.any other information? Pls share here
Thank you

**Comment by onionknight107** [comment]
Using viramate's favorite summon function will skip the verification. So disable it, please.

**Comment by Alissa1122** [comment]
So far this verification seems only appear on guild war battle, other battle won't trigger it

**Comment by ryokage** [comment]
@Masuzu

**Comment by bobby5d** [comment]
someone post the html code of the button

**Comment by Masuzu** [comment]
More information in https://github.com/Masuzu/ZooeyBot/issues/579

**Comment by Masuzu** [comment]
A workaround will be released in 12h from now.
I will follow up in #579
Forgive me if posts are deleted, all of them are very helpful but your safety goes first!
