### ISSUE TITLE
Help scribble sorry email to cygames for those of us that dun goofed?

### ISSUE THREAD

**Issue by devvah** [Masuzu/ZooeyBot#582]
I don't know Japanese or where is their contact email, they really aren't making it easy to find it.

It would be a real shame to miss OP chara like Lyria becaue of this goof.

**Comment by ryokage** [comment]
did you get banned and if so can we get a screenshot of what it exactly says

**Comment by Masuzu** [comment]
I am sorry but this is definitely not the right place to ask for this.

**Comment by rockysilver** [comment]
If you don't mind me asking, how long is the ban?

See this Reddit thread on email template: https://www.reddit.com/r/Granblue_en/comments/69wbza/does_cygames_ever_give_reasons_for_a_ban?sort=top

Do you mind keep us updated if they ever reply to you? The email is probably the generic support email.

**Comment by devvah** [comment]
Ban is month long but in that case it means missing anniversary and what makes sky blue 1&2 which is very strong hit.

Thanks for the link, I will try and see if they unban me early and post results here.

**Comment by devvah** [comment]
Sorry for long delay, I was told to go fuck myself by support
...twice.

That's it me.

**Comment by rockysilver** [comment]
Sorry to hear that, but at least it is not permanent ban.

**Comment by Hedova928** [comment]
I was permanently banned :/

I heard usually they allow one appeal, has anyone had success in this case? I tried apologizing and promising to follow the rules from now but was stonewalled.

**Comment by rockysilver** [comment]
Permanent, is this your first ban? I wonder what the one month ban and permanent ban people did differently.

**Comment by Hedova928** [comment]
No, I've had suspensions before but lost track and didn't realize I was on my last one.
