### ISSUE TITLE
2.90 Error

### ISSUE THREAD

**Issue by sad1234564** [Masuzu/ZooeyBot#584]
No active window with gbf is found, but it is working when using older versions.

**Comment by sad1234564** [comment]
issues has been solved.
I need to input the correct language.

**Comment by Miyoumu** [comment]
Can you elaborate, I'm having the same issue and can't figure it out.

**Comment by Miyoumu** [comment]
Oh you meant the literal language. I see now.
SSSSSSSSSSSSSSSSSS
