### ISSUE TITLE
Issue with Zooeybot doing extreme mode on GW?

### ISSUE THREAD

**Issue by Miyoumu** [Masuzu/ZooeyBot#586]
Last Guild Wars I had zooey set to do Extreme mode boss on GW with these setting and it worked just fine. 

![image](https://user-images.githubusercontent.com/28634170/36289613-d96d7644-128e-11e8-9ca3-d8c9bf56ff95.png)

This guild wars I'm using the same exact settings:  (except with the appropriate link of course)

![image](https://user-images.githubusercontent.com/28634170/36289627-e7edb10c-128e-11e8-8e53-bb0eff044f3c.png)

and I keep getting this error: 

![image](https://user-images.githubusercontent.com/28634170/36289641-03c420e6-128f-11e8-9176-b5909b996d58.png)

Is this an issue on my part or with the bot? it seems weird that the settings would have to be different. On another note NM works fine but ex is the difficulty I'm having trouble with.

I understand Masuzu is busy but help ASAP would be very appreciated.

**Comment by Ohwhat00** [comment]
Just use the normal [EventMode] instead of [TreasureEventMode] for farm EX+/EX/VH  See latest: https://github.com/Masuzu/ZooeyBot/issues/567

For NM farming, use [TreasureEventMode]. See: https://github.com/Masuzu/ZooeyBot/issues/127

**Comment by agesa** [comment]
Have you tried just setting the difficulty to 'ex' like the commented out line above the difficulty value states?  You can also just use event mode instead.

**Comment by Masuzu** [comment]
Don't use the Treasure Event mode for GW to farm the EX mode, as described here https://github.com/Masuzu/ZooeyBot/issues/567
