### ISSUE TITLE
2.9.1 - Alert for verification prompt not working properly?

### ISSUE THREAD

**Issue by Ohwhat00** [Masuzu/ZooeyBot#587]
There seems to be an issue with the alert for the new verification prompt.

The past hour I have had the sound alert triggered twice when on the summon list page. However, no verification prompt message was shown and I could see the full list of summons as normal on the chosen element tab. 

Unless the verification prompt disappears within 3-4 seconds(since I was switching my eyes between monitors), I doubt I would have missed it and I don't use viramate either.

**Comment by thebp2** [comment]
If you look at the logs was it just after rerolling summons with trial battles? Might be the same as #588

**Comment by ryokage** [comment]
Yeah I've gotten the bug wheres theres no verification but it stops the bot

**Comment by Masuzu** [comment]
It is a false positive related to summon rerolling. This will be addressed before the start of the next round.
