### ISSUE TITLE
No Granblue Fantasy Window open [Solved, Nothing to do with Bot]

### ISSUE THREAD

**Issue by Shamool** [Masuzu/ZooeyBot#589]
Since updating to 2.9.1, I can't seem to run ZooeyBot. It can't detect that the granblue window is open

**Comment by Shamool** [comment]
Oh never mind, it's solved. Wasn't the bots problem.

**Comment by ryokage** [comment]
I just got the same problem how did you fix it

**Comment by Masuzu** [comment]
It was an issue with the language settings set to en instead of jp.
