### ISSUE TITLE
No summons detected error

### ISSUE THREAD

**Issue by sonderbyyonder** [Masuzu/ZooeyBot#591]
Using Zooeybot, I get the no summons detected error when it goes to the summons screen, but there seem to be summons listed?

**Comment by Garnetus** [comment]
Yeah I was running tests for about an hour, the alarm happened  4 times and there is no gacha verify at all.... I think the new feature is not working properly, and with this kind of false alarm rates it's hard to get farm going.

**Comment by Masuzu** [comment]
This thing?
https://github.com/Masuzu/ZooeyBot/issues/588

**Comment by Garnetus** [comment]
Yes...it only happened after swithcing summons, sorry I did not mention it.
