### ISSUE TITLE
New "autobot" detection

### ISSUE THREAD

**Issue by filipi159951** [Masuzu/ZooeyBot#592]
![image](https://user-images.githubusercontent.com/31833213/36312891-ab9a8a10-130e-11e8-93b6-e5f1f53e91c0.png)
there's a new verifying tool,
Some people found that, and if you use viramate with Fav Summon On, it could didn't apear to you and you get ban.

**Comment by Hexadecimalism** [comment]
From what I understand even with the favorite tab, it still works. Still, no such thing as being too safe.

**Comment by Masuzu** [comment]
Hello,
I am aware of this and this has been addressed already in the the v2.9.x and tested successfully.
