### ISSUE TITLE
hello skills not working

### ISSUE THREAD

**Issue by dabudauu** [Masuzu/ZooeyBot#595]
i am using an extremely simple script for gw but it isn't working, i'm getting no response after abnormally long time at position 1,2,3, w/e.
viramate set to true too``

**Comment by Shamool** [comment]
Did you enable keyboard controls for Viramate?

**Comment by Masuzu** [comment]
Please refer the wiki FAQ. https://github.com/Masuzu/ZooeyBot/wiki/FAQ
