### ISSUE TITLE
Updated to latest and still getting new captcha sound alerts 

### ISSUE THREAD

**Issue by MonaSaySleep** [Masuzu/ZooeyBot#596]
Updated to latest 2.9.2 and still getting untimely false positives and triggering sound alerts. I have to go back to 2.8.0 to make it work.

**Comment by Miyoumu** [comment]
Does your bot get stuck at the summons screen?

**Comment by Shamool** [comment]
Are you using favourite summons option in Viramate?

**Comment by Miyoumu** [comment]
^ can confirm, turning off favorite summon option in viramate fixed the issue I was having.

**Comment by MonaSaySleep** [comment]
Turned off fav summons and it works now! thanks!
