### ISSUE TITLE
[Viramate Favourite summon tab] "No summon could be found" when there clearly is one it should be able to find

### ISSUE THREAD

**Issue by Mitsukai** [Masuzu/ZooeyBot#598]
I'm currently having an issue where Zoeybot is seemingly unable to recognize any summons and then just hangs when getting to the summon selection. The error saying that a summon can't be found is incorrect because when the summon page loads, I can instantly see the summon I have set for it to pick in the .ini file. It was also working earlier during GW Preliminaries without problem, and I haven't changed any settings since then. My .ini folder is very clearly marked, there's no typo mistakes or anything of the sort.

Was having the error on 2.9.1, so I figured if I updated maybe that would fix it, but it still happens on 2.9.3.

![error](https://i.imgur.com/PAi2WSb.png)

**Comment by Shamool** [comment]
Do you have the favourite summons option in Viramate disabled?

**Comment by Mitsukai** [comment]
No. I have changed literally nothing in the .ini or Viramate between when it used to work and when it stopped.

**Comment by zcdragon** [comment]
As addressed before, you need to go into your Viramate settings and double-check that this is turned off. The new version of Zooeybot is not compatible with the Favorites feature while the previous versions were.

![summonsetting](https://user-images.githubusercontent.com/31464723/36344616-0a35b446-13d2-11e8-92ba-ea714b5001b0.PNG)
