### ISSUE TITLE
"No active window with Granblue Fantasy was found."

### ISSUE THREAD

**Issue by Akaharu4U** [Masuzu/ZooeyBot#599]
As seen in the attached image, that is clearly not the case. I don't know what's causing it but it's only been popping up since the 9.2 update

![image](https://user-images.githubusercontent.com/36486581/36347266-286263c0-1421-11e8-858a-2db6fe3dbcf3.png)

**Comment by Shamool** [comment]
Could you check to make sure that in your ini file, the language is not set to jp first?

**Comment by Akaharu4U** [comment]
Ah, that managed to get past that. Although now it's stuck after telling me to go to the Quest menu

**Comment by Akaharu4U** [comment]
That worked
