### ISSUE TITLE
windows 10 download issue

### ISSUE THREAD

**Issue by nobody0014** [Masuzu/ZooeyBot#6]
I'm currently using windows 10, when i tried downloading zooey, my windows delete it automatically due to trojan detection. Would you mind clarifying what is causing the trojan detection? (i could just disable and download normally but it would be nice for an explanation on the trojan trigger, i kinda trust you guys since your poker bot was well done)

**Comment by Masuzu** [comment]
https://github.com/Masuzu/GBFPokerBot/issues/79
