### ISSUE TITLE
 2.9.3 - GW - Not claiming treasure?

### ISSUE THREAD

**Issue by Ohwhat00** [Masuzu/ZooeyBot#600]
Keep encountering this issue today, not sure if it's related to GW day 3 or not.

Farming NM90, when the boss dies, URL navigates to the result page, however, it then really quickly navigates to the GW main page and just stays stuck there or it navigates to the unclaim/pending page and shows that the previous battle I finished is still pending/unclaimed.

Screenshot example:
![okkx4g445w](https://user-images.githubusercontent.com/36525320/36361823-19dc5c82-1527-11e8-9e15-b20f01c09ca6.png)

**Comment by salvanost** [comment]
Same issue here
Switch back to old version
No prob with 2.70

**Comment by Masuzu** [comment]
Do you still have issues after increasing the parameter `WaitTimeInMsAfterEventPageIsLoaded` to 3 seconds (3000) or more?

**Comment by Ohwhat00** [comment]
Yeah, I tried increasing it to 5 seconds, but issue was still occurring. However, placing the parameter under [TreasureEventMode] seemed to fix it I think? Doesn't happen anymore. Anyways thanks, working again now!

**Comment by salvanost** [comment]
So the original parameter only works for event mode?

**Comment by Ohwhat00** [comment]
Nope. I thought the issue was fixed, but it's still happening. :S It just doesn't stay in the result/claim page long enough. The parameter only applies when you're on the event page.

**Comment by salvanost** [comment]
I don’t think it’s the bot issue
After end of battle when i reload the url
It’s still jump to event url not the battle result url

Looks like the game got issue after end of battle if reload the url

**Comment by Masuzu** [comment]
After some tests, it looks like it depends on your ping.
