### ISSUE TITLE
"No active window with Granblue Fantasy was found" Error

### ISSUE THREAD

**Issue by ugaru** [Masuzu/ZooeyBot#601]
![default](https://user-images.githubusercontent.com/36652276/36405075-cf877ccc-15ab-11e8-9a00-f890dacbaafa.PNG)
![2](https://user-images.githubusercontent.com/36652276/36405077-d2da7316-15ab-11e8-8a5a-55f9bdea66a1.PNG)
![3](https://user-images.githubusercontent.com/36652276/36405079-d40906f8-15ab-11e8-867b-6cf846ce80c1.PNG)

I have been using zooeybot for a long time and I haven't used it since 2.4.3 version. I started playing GBF again so I got the most recent zooeybot 2.9.3 version and it keeps showing that message. I didn't have this problem before and it's the first time I am seeing this. All my settings seems to be fine and this exact setting used to work on previous versions of zooey. Can anyone help me out please???

**Comment by Ohwhat00** [comment]
Yea, latest released version has the language set to JP. 
Looks you're playing in English, so edit ZooeyBot.ini and set Language=en
