### ISSUE TITLE
Issue with What Makes the Sky Blue EX.

### ISSUE THREAD

**Issue by MatatabiJyarashi** [Masuzu/ZooeyBot#603]
When using event mode on event "What Makes the Sky Blue" for Difficulty "Dominion Core" and lower, it works fine but when I use the link for difficulty "Sandalphon", booting Zooeybot>Clicking on Quest does not direct me to event page.
The link for "Sandalphon" is longer than usual Summoners select link.
http://game.granbluefantasy.jp/#quest/supporter/xxxxxx/1/0/xxxxx

Thank you

**Comment by Masuzu** [comment]
I will try again the "ex" difficulty then and see how it goes. Thank you for reporting this.

**Comment by MatatabiJyarashi** [comment]
Thank you for your time

**Comment by xiang-guo** [comment]
yep, same thing, I can use the treasure mode to do the EX, but it won't be able to clear the HL mode by itself.

**Comment by Masuzu** [comment]
Please use the https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode
It works fine setting the difficulty to EX.
