### ISSUE TITLE
Bot does not work with impossible difficulty

### ISSUE THREAD

**Issue by greatmany** [Masuzu/ZooeyBot#605]
Are there any plans to bring back support for impossible difficulty?

**Comment by Masuzu** [comment]
Doesn't https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode work?

**Comment by violafayde** [comment]
nope, i tried setting the difficulty on treasure raid mode to impossible and the bot couldn't start impossible raids. only ex works.

**Comment by Masuzu** [comment]
Noted, thank you. I will fix it at least for the What makes the Sky blue Part II.

**Comment by Masuzu** [comment]
This is now addressed in v2.9.4
https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-9-4
