### ISSUE TITLE
Not responding when rerolling summon

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/ZooeyBot#607]
Everything is fine until I need to reroll summon, then it just went crashing thus not responding when picking summon for trial.
Currently I'm setting to farm ex then nm, I don't know which one causing the problem.
EDIT: I set the summon to Kaguya only and reroll. The chronological sequence of the crashing is:
-finishing previous ex
-going to event page
-selecting ex
-no Kaguya available
-going to trial battle
-crash!

EDIT2: it crash if I start zooey again right after that, because it tried to find Kaguya, then going to reroll, crash on the trial battle summon selection again.
![notresponding](https://user-images.githubusercontent.com/31296536/36624435-cf31dca6-1941-11e8-8c86-be824a2a4c6f.png)

**Comment by Masuzu** [comment]
I can't reproduce the issue for now. I made tests setting `PreferredSummons=i_do_not_exist`, `RerollSummonWhenNoPreferredSummonWasFound=true` and using the normal mode to farm Angel Halo.

**Comment by Sundaerae** [comment]
I found the problem, I have a typo on DefaultSummonAttributeTab.
