### ISSUE TITLE
still can't host nm90

### ISSUE THREAD

**Issue by meteoshower** [Masuzu/ZooeyBot#61]
hello i still can't host nm90

![story_1](https://cloud.githubusercontent.com/assets/28686592/26232950/f9fce2d2-3c83-11e7-82a1-3a8be6a314b0.jpg)

. Seems like i must pressbutton   to spend meat  (after press banner 
nightmare ) before  choose summon. so i set parameter WaitTimeInMsAfterEventPageIsLoaded to 1000 already.

**Comment by Masuzu** [comment]
Hello,

Sorry, my bad. I will investigate it when the final round starts.

**Comment by Masuzu** [comment]
Put on hold until the next guild war.
