### ISSUE TITLE
Normal Farming Pauses in Debugger, [Sound Turned Off tried]

### ISSUE THREAD

**Issue by Shamool** [Masuzu/ZooeyBot#610]
Recently, I've been using Zooey Bot for normal farming and it has been stopping midway through a battle with debugger. As shown below, does anyone have any idea how to solve this?

**Comment by Masuzu** [comment]
Hello,
It looks like you killed your RAM, which will trigger that message from Chrome DevTools.

**Comment by yradwan** [comment]
I've been receiving the same issue while farming the new event. I have 32GB of RAM so memory should not be the issue. 
![1capture](https://user-images.githubusercontent.com/31907260/36807317-86801104-1cba-11e8-9293-18fc6f500b4b.PNG)

**Comment by Shamool** [comment]
Tried it after the doing with the issue on stackoverflow, it works somehow? I don't really understand any of it though. Resetting your settings on chrome devtools also seems to sidestep the issue

**Comment by Masuzu** [comment]
It looks like the latest Chrome (v65.0.3325 is not compatible anymore though) and Chromium addressed these memory issues.
