### ISSUE TITLE
Problem at doing special quest.

### ISSUE THREAD

**Issue by tiongcock** [Masuzu/ZooeyBot#611]
Hello i have problem when farming corrow stage which consist of 3 stages.
this is my script 

```
--[[Front Line : 
Sword Master ( Bounty Hunter ) 
Sarasa
Seruel
Lucio
Support summon: Kaguya, White Rabbit--]]
if battle == 1 then
	character_4:UseSkill(1)
	character_3:UseSkill(3)
	character_3:UseSkill(1)
end
if battle == 2 then
	character_4:UseSkill(2)
end
if battle == 3 then
	character_1:UseSkill(4)
	character_2:UseSkill(3)
	character_1:UseSkill(1)
end
```

then when it cast attack skill suddenly when enemy drop item, the log on console shows up a lot of turn has been done yet its only one turn per battle. the pointer looks stuttering and it request clearing sth. i will attach the image below.

![prob](https://user-images.githubusercontent.com/23329071/36844486-8620244e-1d85-11e8-80bc-05d774394854.png)

Thanks in advance.

**Comment by Masuzu** [comment]
Hello,
While this behaviour is abnormal, the "ghost" turns end immediately and Zooey falls back on its feet as it eventually "Proceeds to the next stage".
