### ISSUE TITLE
problem of looping

### ISSUE THREAD

**Issue by whitevm** [Masuzu/ZooeyBot#612]
hi,I have been tried changed to chromecarney ,disable Chrome search bar autocompletion ,closed viramate
and still can't slave this problem
![11111](https://user-images.githubusercontent.com/36965701/36859572-22e1ed6c-1dc2-11e8-8d9c-4a59f6932ce2.jpg)

**Comment by Masuzu** [comment]
Hello,
Which quest are you hosting?
If it is a quest requiring materials to host (the event Extreme mode for instance) then you _have_ to use the treasure event mode https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode, or else you'll run into this kind of issue.

**Comment by whitevm** [comment]
HI,
Ｉ want to run the angel halo quest,thanks

**Comment by Masuzu** [comment]
Then your quest ID is not correct. This is the quest ID of the  GW EX mode. Make sure to update the quest ID URL.
