### ISSUE TITLE
Says that I'm an unregistered user all of a sudden???

### ISSUE THREAD

**Issue by iSDestiny** [Masuzu/ZooeyBot#613]
![92894378eb97227b5491f1eb94f7a6fc](https://user-images.githubusercontent.com/32033119/36882235-6c1cdbda-1d87-11e8-8037-94d53481da5c.png)

My serial number does match the one on that page so I'm not sure why I am getting this error.

**Comment by iSDestiny** [comment]
![87d2c37a3e192a9f633e0c772d0afe99](https://user-images.githubusercontent.com/32033119/36882320-f4b81022-1d87-11e8-9f22-cd117484ed85.png)

**Comment by Masuzu** [comment]
Sometimes the serial number generated does not match the actual one that you should use. Make sure to use the one in the file `serial_number.txt`.
Also, try and redownload your `key.txt` file from the management page (note that you never have to ever modify that file).

**Comment by iSDestiny** [comment]
It works now after like 7 hrs. Not sure what I did. I didn't even change any of the files or restart my pc. hmmm...
