### ISSUE TITLE
Quest refresh loop

### ISSUE THREAD

**Issue by optiblast** [Masuzu/ZooeyBot#614]
Farming Satin Feather and Zephyr Feather on Chapter 1 R Chara Quest 「Scattered Cargo」. The bot just suddenly starts refreshing when it gets into battle.
![vmware_2018-03-02_07-56-56](https://user-images.githubusercontent.com/35657824/36900056-b8db8a58-1def-11e8-8357-20bd3c9d082d.png)

**Comment by Masuzu** [comment]
Hello,
If you looked a bit beforehand, here it is: https://github.com/Masuzu/ZooeyBot/issues/509

**Comment by optiblast** [comment]
This is the auto hide popup right? I never have that on. I didn't even know that's a thing.
![vmware_2018-03-02_09-05-59](https://user-images.githubusercontent.com/35657824/36902594-069adfec-1df9-11e8-9e3c-7433d0ff16a9.png)

**Comment by Neno42** [comment]
I also have the same problem and Viramate is not enabled nor do I have google's personalized search algorithm enabled.
