### ISSUE TITLE
Skill won't work with "enemy_1.charge_diamonds"

### ISSUE THREAD

**Issue by YumeHaru** [Masuzu/ZooeyBot#616]
Hi,

Everything in my script work fine except for the part "enemy_1.charge_diamonds". The bot just skip it that step.

```
-- [Use buffs/debuffs whenever they are available] --
character_2:UseSkill(1)

-- [Begin boss fight] --
if battle == 2 then
	Summon(6)
	character_1:UseSkill(1)
	character_1:UseSkill(4)
	character_2:UseSkill(3)
	character_2:UseSkill(2)
	
-- [Protect party against boss special] --
	if enemy_1.charge_diamonds == 4 then
	character_3:UseSkill(3)
	end

-- [Boss fury mode] --	
	if enemy_1.overdrive_state == true then
	Summon(1)
	character_1:UseSkill(3)
	character_3:UseSkill(1)
	character_3:UseSkill(2)
	character_4:UseSkill(2)
	character_4:UseSkill(3)
	end
end
```

**Comment by Masuzu** [comment]
Hello,
I will test in a trial battle (using the `DebugMode=true` feature) later on. There might be a wrong charge diamonds count reported when the boss is affected by gravity.

**Comment by YumeHaru** [comment]
I think that's probably the problem because when I use archer class instead of dark fencer with same command, it doesn't bug at all.

**Comment by Masuzu** [comment]
I will release the change around the maintenance time this Saturday.

**Comment by Masuzu** [comment]
Addressed in https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-10-0
