### ISSUE TITLE
Is there a way to stop zooey IF Nightmare Halo appears? not an ISSUE just a question

### ISSUE THREAD

**Issue by arthurneo** [Masuzu/ZooeyBot#617]
Not an Issue or a problem, but is there a way top configure Zooey bot to stop if she starts Nightmare Halo

Dont know if  or how to implement lua script to press f1 to abort zooey in turn one.

**Comment by Masuzu** [comment]
Hello,
I will add this feature in a next release.

**Comment by YumeHaru** [comment]
I would like that feature too, please. I'm not strong enough to Nightmare Halo, lol

**Comment by Thalatha** [comment]
This is kind of a workaround, but before I was strong enough, I made a very simple script where the bot will wait and do nothing until I turn it off:

Wait(60000)
SkipAttack()

**Comment by arthurneo** [comment]
@Thalatha   Excellent, I didnt know the wait command worked.

Gonna try it later,  if I dare to make another eternal uncap

**Comment by Masuzu** [comment]
Wait, doesn't everyone have 10 fully uncapped Eternals yet?

The feature will be added this week-end to stop and play a sound alert when a nightmare mode appears.
![image](https://user-images.githubusercontent.com/5464705/37200637-a2cb65da-2385-11e8-9e46-8596414123ba.png)

**Comment by Masuzu** [comment]
Done in v2.10
