### ISSUE TITLE
Bot makes Chrome crash

### ISSUE THREAD

**Issue by YumeHaru** [Masuzu/ZooeyBot#619]
Here's the bugs reported by the console log and I don't have any addon that block pop up. I also have only your extension activated nothing else. I've 16GB of ram.
[bugs.txt](https://github.com/Masuzu/ZooeyBot/files/1778790/bugs.txt)

**Comment by YumeHaru** [comment]
Someone already asked same question, sorry that I didn't search beforehand.

**Comment by Masuzu** [comment]
This enclosed script comes from GBF.
This could be related:
https://github.com/Masuzu/ZooeyBot/issues/565 and https://github.com/Masuzu/ZooeyBot/issues/610

My RAM usage tops 1.5-2GB for Google Chrome using Lite settings

**Comment by YumeHaru** [comment]
Downgraded my Chrome to version 1.63 and no more issue. Thanks for your help.
