### ISSUE TITLE
Similar issue as ycalvin got

### ISSUE THREAD

**Issue by lsysz53508** [Masuzu/ZooeyBot#62]
Hello, Masuzu

After the 1.5.3 is released, I still got the same problem as ycalvin got before.

Even I set the parameter to 10000ms, the problem still appears.
It is curious, if I use my hands to do the job. No matter how fast I go, there won't be any problems.
Could you check on this issue?

Maybe the problem is due to the waiting at summon select page instead of the event page?

**Comment by ycalvin** [comment]
Still happening to me too. Very Weird interaction. Using the URLS as bookmarks will allow you to enter the dungeon but something is going on with the Bot that causes the error to happen.

**Comment by Masuzu** [comment]
Hello,

I will follow up with this issue in https://github.com/Masuzu/ZooeyBot/issues/61

**Comment by water000qazzaqzxccxz** [comment]
That error looks like you did not have enough AP to enter the dungeon
