### ISSUE TITLE
Can't farm side story

### ISSUE THREAD

**Issue by YumeHaru** [Masuzu/ZooeyBot#623]
Hi,

I tried to setup event mode for side story (1) farming phoenix but the bot cannot access the page.
EventPageUrl=http://game.granbluefantasy.jp/#sidestory/story/1001
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/720461/3

I tried to not put the pageUrl but it didn't change anything. The bot try to access the page but then is brough back automaticly on the home page. I tried to farm with default mode but the bot didn't work (it was doing nothing on summon page).

Here's a picture of Zooey log https://i.imgur.com/IaiKiRd.png
This behavior never happened in default mode.

Edit: I disabladed the auto fill in in chrome option.
I don't use Viramte
After some tries I hear the mp3

Here's my setup in config file: https://i.imgur.com/zZlORlz.png

**Comment by YumeHaru** [comment]
Here's a picture of Zooey log https://i.imgur.com/IaiKiRd.png
This behavior never happened in default mode.

**Comment by Masuzu** [comment]
Hi,
Do you mean that just by navigating to http://game.granbluefantasy.jp/#quest/supporter/720461/3 you are automatically redirected to your Home page?
This might be linked to https://github.com/Masuzu/ZooeyBot/issues/625

**Comment by Masuzu** [comment]
Hello,
This is related to this issue: https://github.com/Masuzu/ZooeyBot/issues/625
Using Chromium v67 works as well so you can keep your current Chrome version.
