### ISSUE TITLE
New Google Chrome update V65.0.3325

### ISSUE THREAD

**Issue by Ohwhat00** [Masuzu/ZooeyBot#625]
Since updating google chrome to the newest version(65.0.3325), zooeybot has broken for me,

I would get the following error message, when trying to do free quests:

![chromezoi](https://user-images.githubusercontent.com/36525320/37073234-87b3f808-21bd-11e8-8a1a-3eaedd544e03.png)

It just won't proceed to battle 2+. I have tried increasing the wait delay for combat and page loading up to 20 seconds in the .ini file. But the issue still occurs.

New chrome update also causing the following issue with selecting summons: https://github.com/Masuzu/ZooeyBot/issues/626

As a workaround for the time being, I have downgraded my version of chrome to the previous release (64.0.3282.140) and it seems to be working fine again.

**Comment by rockysilver** [comment]
same problem here, it is just stuck at battle 2.

**Comment by Masuzu** [comment]
I will try and see what the issue is with the new Chrome version (65)

**Comment by Masuzu** [comment]
After making some tests, there is definitely a regression introduced in the build 65.x.
I filed an issue to Google DevTools team.

**Comment by Masuzu** [comment]
I can make some changes on my side to be compatible with the new build but that will take some time. I will see what I can do.

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ZooeyBot?src=hash&amp;ref_src=twsrc%5Etfw">#ZooeyBot</a> <a href="https://twitter.com/hashtag/SarasaBot?src=hash&amp;ref_src=twsrc%5Etfw">#SarasaBot</a> If you do not wish to downgrade Chrome from v65.0.3325.146 to v64, you can also use Chromium (tested with v67.0.3366.0) from <a href="https://t.co/kFf1SLr2fb">https://t.co/kFf1SLr2fb</a></p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/971827898817613827?ref_src=twsrc%5Etfw">March 8, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by YumeHaru** [comment]
I've downgraded to V63 since days ago but I had that bug when I tried side stories. I will try Chronium later.

**Comment by YumeHaru** [comment]
Bot doesn't reconize GBF window with chronium :( @Masuzu (no prob with Chrome)

**Comment by Masuzu** [comment]
Chromium version 67.0.3364.0 also has the same issue as Chrome 65.0.3325. Chromium 67.0.3366.0 and 67.0.3367.0 run fine, at the cost of having no H264 codecs installed and being unable to browse several streaming websites, compared to Chrome. But you can have both Chrome and Chromium running side by side.

**Comment by YumeHaru** [comment]
@Masuzu 
I downloaded the last version 67.0.3367.0 (ver64) on Chronium website and bot still can't recognize GBF window: "no active window".

**Comment by Masuzu** [comment]
Did you make sure to set the language setting to either `en` or `jp` accordingly?
Chromium works fine otherwise.

**Comment by YumeHaru** [comment]
@Masuzu 
Yes, I'm using same file that I use for Chrome (so setup in english and game in english ofc). That's why I don't understand why same config file doesn't work on Chronium: https://i.imgur.com/AKZwDEP.png

**Comment by Masuzu** [comment]
Alright, this is starting to become a bit annoying so I'll make a change regarding this issue as well. Browser/Locale dependent issue.

**Comment by dkotama** [comment]
Hi i tried multiple times with chrome 64 even with chromium V67 no windows detected,
I want refund @Masuzu

**Comment by gary173** [comment]
I can't use zooey bot eather.
help me

**Comment by aysien** [comment]
@here
For several hours I check several version of Chronium, 
Logicaly, Its happen because the Chrome updated, so as long its a version before it get update it will be okay. 
I found that as long it quite old version around June - September 2017 build of Chronium it running fine. 
Im currently running Version 63.0.3225.0 (Developer Build) (64-bit)
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/504347/

**Comment by Masuzu** [comment]
@dkotama There is no refund policy as per the terms and conditions of the service, otherwise resulting in a permanent termination of the service.
However your issue seems just related to a misconfiguration: https://github.com/Masuzu/ZooeyBot/issues/631

**Comment by YumeHaru** [comment]
New version of bot works on Chrome and Chronium, tested it yesterday. Will test on Vivaldi too.

**Comment by fdxcfdxc** [comment]
@Masuzu I am a SarasaBot user. I tried Chromium 67.0.3362, 67.0.3367 and the latest version to prevent the problem of not claiming pending battle. The thing is Sarasa can work on Chrome, but on Chromium the "start" button of extensions cannot be clicked at all. Please help, thank you.

**Comment by damnsquidpeople** [comment]
I can attest to it not working on Vivaldi as well regardless of configuration, despite Vivaldi being a Chromium-based browser as well.

**Comment by djeeta111** [comment]
interestingly enough I tested it on one of my vivaldi setups last night and it worked for me (for ZooeyBot, have not tested on SarasaBot) + tested on the same one and it worked.

I have not tested on my standalone versions for multiple profiles though

@Masuzu I would also like to make a request to enable vivaldi/etc if able on the GBFPokerBot as well please

**Comment by Masuzu** [comment]
I do not plan to support many browsers with different versions. It will become a rabbit hole otherwise. I would rather stick with a single Chromium version which works fine.

**Comment by Masuzu** [comment]
@fdxcfdxc Starting the extension works on both Chromium 67.0.3366 and 67.0.3367.

**Comment by Masuzu** [comment]
For future reference, Chromium 67.0.3366 and 67.0.3367 are compatible with Zooey and Sarasa bot.
You can pick your poison here: https://chromium.woolyss.com/download/
