### ISSUE TITLE
No longer able to do AH.

### ISSUE THREAD

**Issue by sephallian** [Masuzu/ZooeyBot#627]
![image](https://user-images.githubusercontent.com/37134859/37077236-4975fc4c-2197-11e8-82af-e5edf74c8d39.png)

I was able to bot AH fine yesterday... however when I set it up today it stalled after defeating wave 1 and moving on to wave 2. Everything works fine until it moves on to wave 2, as you can see it thinks AH has -1 battles total and seems to expect the result screen.

**Comment by YumeHaru** [comment]
Someone already reported that bug and it's related to Chrome new update. You need to downgrade to previous version.

**Comment by sephallian** [comment]
Ah, my bad. Should've looked around a bit more before creating the issue. Thanks for the response!

**Comment by Masuzu** [comment]
Hello,
This is related to this issue: https://github.com/Masuzu/ZooeyBot/issues/625
Using Chromium v67 works as well so you can keep your current Chrome version.
