### ISSUE TITLE
change serial error

### ISSUE THREAD

**Issue by Onmae** [Masuzu/ZooeyBot#628]
while chaning serial code in VMWARE , error happend

what can i do?

**Comment by Onmae** [comment]
or do number have problem? 6d933407c37d973c4979c6d4f09b3e48121a6b1f58f966be152bd3994fc03f27256b4a839d845a4e71358f7065ecf2e0758ab49772f386341e0b71dc61586c16

**Comment by Masuzu** [comment]
Hello,
This is troublesome indeed. I'll fix this.
