### ISSUE TITLE
Reloading trouble

### ISSUE THREAD

**Issue by lolipirate** [Masuzu/ZooeyBot#629]
Hello there. 

For some reason, I cannot get ZooeyBot to work. When I start it and pair it with the chrome extension, I go to the quest tab. Then it takes over and continue to click a specific place on the screen. 
This is the commandline text: 
[image](https://i.imgur.com/kk3UUYm.png)
It keeps clicking this place: 
[Image](https://i.imgur.com/PJWClUW.png)

**Comment by lolipirate** [comment]
Okay, figured out that you can't run it in fullscreen, however it tries to enter this url: http://game.granbluefantasy.jp/#quest/supporter/72****/1, which just returns to the quest side. Anyone know how to fix it?

**Comment by lolipirate** [comment]
Found an earlier thread about this issue and the proposed solution was disabling autosearch completion, which didn't help me. Tried with two accounts.

**Comment by Masuzu** [comment]
Hello,
You can't host side scenario quests for now.
Otherwise, please check https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode if it applies to your case, which is very likely.
