### ISSUE TITLE
Hi, have trouble with slame blast in chromium

### ISSUE THREAD

**Issue by Onmae** [Masuzu/ZooeyBot#630]
Slave does not clear the address properly when going to the closing window after the attack.
master side is fine, but only the slave side has problems.
The picture above is a snapshot of problems with the extended app, and the picture below is a problem with sill usage

![image](https://user-images.githubusercontent.com/37141155/37237503-55d68fc0-2457-11e8-90da-e6ace30e4b77.png)

![1520649539714](https://user-images.githubusercontent.com/37141155/37237551-e85973da-2457-11e8-80fd-fcb67e861732.jpg)

**Comment by Masuzu** [comment]
Hello,

I faced that exact same issue on my side and addressed it in v2.11.0
