### ISSUE TITLE
2.10.1 no active window was found

### ISSUE THREAD

**Issue by fumika779** [Masuzu/ZooeyBot#631]
![2018-03-10_192046](https://user-images.githubusercontent.com/31799116/37242219-2a36cd80-2498-11e8-92c6-c8ff3f27e50c.jpg)

Yes i choose tab correctly

but it's error

**Comment by YumeHaru** [comment]
Did you changedthe language in the config file .ini?
Because by default it's writtent "jp" and you need to write instead "en"
I know that because I just tested new version on Chrome and I didn't got that error.

**Comment by fumika779** [comment]
thx i can fix it
