### ISSUE TITLE
Refresh in select summon

### ISSUE THREAD

**Issue by NzString** [Masuzu/ZooeyBot#633]
![zooeybot_2018-03-11_03-12-47](https://user-images.githubusercontent.com/26919276/37245417-033a1b54-24db-11e8-83ad-63264e07feaf.png)

I always refresh in the select summon.
Bot start -> Quest -> select summon -> refresh -> pick summon -> in raid.
What do I do for avoid refresh?

use vira / no fav summon

**Comment by Masuzu** [comment]
Hello,
While it does not break things, this can happen depending on how slowly the summon selection page is loaded. There are some settings to limit this such as `MaxResponseDelayInMs` to adjust depending on your computers specs and ping.

**Comment by NzString** [comment]
I think it's not loading problem. My computer is 63ms ping with granblue server and fast loading, but every time refresh.
If I change MaxResponseDelayInMs=(500, 3000, 5000), All the same refresh errors.
