### ISSUE TITLE
Unneeded refresh with slave mode coop

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#634]
Zooey almost always refreshes my master window in slave mode coop right before it finishes loading. Is there a timer in the settings I need to extend to make it wait longer?

This is with version 2.11.0

**Comment by Masuzu** [comment]
It can happen the first rounds when the page assets are not yet all fully cached. `MaxResponseDelayInMs`, `MaxPageLoadDelayInMsBeforeRetry` are related to this observation, among other things.
