### ISSUE TITLE
2.11.0 slave mode slime issue

### ISSUE THREAD

**Issue by Garnetus** [Masuzu/ZooeyBot#635]
It simply begins to refreshing slave account instead of keep doing slime after one success attempt. 
The mouse would skip the ready button for main account and cause the whole process stops.
Pretty sure it has nothing to do with my setting/PC since I had this worked with exact setting/pc last patch...

**Comment by nut11443366** [comment]
I have this problem too .

**Comment by Masuzu** [comment]
Hello,
Do you mean that after the first host and returning to the lobby, the ready button is not clicked?
Can you share the console messages right after this happens? I can't reproduce the issue on my side for now.

**Comment by Masuzu** [comment]
Awesome!
