### ISSUE TITLE
Slave mode issue on 2.11.0

### ISSUE THREAD

**Issue by Nassy1121** [Masuzu/ZooeyBot#636]
I saw slave mode stack at following message and currently I can't do slime blasting.
> Slave proceeding to result page

Here attached window log.
[log.txt](https://github.com/Masuzu/ZooeyBot/files/1800359/log.txt)

**Comment by Premines** [comment]
i have this problem too

**Comment by Masuzu** [comment]
Hello,
I saw this nasty line in your logs: `No response received after using the ability at position 1 an abnormally long time!`
This is a typical issue of Chrome v65 which introduced breaking changes:
https://github.com/Masuzu/ZooeyBot/issues/625
Either downgrade to Chrome v64 or switch to Chromium with one of the versions mentioned in the issue above or a more recent version.
