### ISSUE TITLE
zooeybot suddenly not refreshing(was fine before I slept)

### ISSUE THREAD

**Issue by edgellidan** [Masuzu/ZooeyBot#637]
it just wont refresh and just breaks out and I have to automatically wait for the loot window, the script was 100% fine

character_2:UseSkill(3)
SkipAttack()
![zooeybug](https://user-images.githubusercontent.com/35202501/37254514-d9796872-2536-11e8-93cf-3f4b428191a9.jpg)

**Comment by Masuzu** [comment]
Did you set the `RefreshPageOnLastBattle` parameter to `true`?
Also, please note that Chrome v65 introduced breaking changes: https://github.com/Masuzu/ZooeyBot/issues/625
