### ISSUE TITLE
PreferredSummons name in katakana

### ISSUE THREAD

**Issue by GranblueOjisan** [Masuzu/ZooeyBot#64]
Hello, I often use jp language setting and I was trying to use ini file has prefferredsummon that was written in Katakana.for example, バハムート as Bahamut.
>make sure to write the summon names in katakana

But something is wrong with this. bot keeps retreating from battles(it's not trial battle, just cost AP =/).so I decided to use en setting and it works perfectly.

probably there is an issue with Katakana.
I'm sorry for bad English. I hope you can understand what's going on.

**Comment by Masuzu** [comment]
Hello,

I took note of the problem and will look into it.

**Comment by Masuzu** [comment]
I identified the issue and released a fix for this in the version 1.6.3.
