### ISSUE TITLE
Slave mode not working and Failed to initialize security.

### ISSUE THREAD

**Issue by i-Grey** [Masuzu/ZooeyBot#643]
I have 2 issues.

For the first one, Slave mode is not working anymore.
After display the result page, ZooeyBot stop moving suddenly.
I've been cooping for nearly 3 hours and then it stop without reason. I've tried to restart my PC and then the second problem occurs.

The latter issue is 'Failed to initial security (error code 0x80010119)'. I've search in this github and found method you mentioned in #628 and I can run bot again. But the result is still same. ZooeyBot stop moving after Result Page appear.

I'm not quite sure what's wrong between bot or something in GBF side.
Hope you can fix this soon.

Best Regards.

**Comment by i-Grey** [comment]
For additional, I've been testing by used to older version and other mode than Slave account and result  still same. I can't not use ZooeyBot anymore. 

FYI. I use Google Chrome version 65.0.3325.146

**Comment by i-Grey** [comment]
After some test and trail. It seems that Chrome V65 is the main problem.
I revert back to the older one and it works fine right now.

**Comment by Masuzu** [comment]
Hello,
Indeed please do not use Chrome v65 as mentioned here https://github.com/Masuzu/ZooeyBot/issues/625
