### ISSUE TITLE
Zooey bot does not stop and does not work alarm (ROTB bosses)

### ISSUE THREAD

**Issue by Chololoco13** [Masuzu/ZooeyBot#644]
I am sorry for my bad english.
zooey bot does not stop when a boss appears and the alarm does not work.
Zooey  works with angel halo but not in rotb
what am I doing wrong?
zooey does not stop when Agni,Titan, Neptune and Zephyros appears

![notepad _2018-03-12_20-37-53](https://user-images.githubusercontent.com/25869534/37319907-b76def4a-2636-11e8-8a2c-877a212ee9e2.png)
![notepad _2018-03-12_20-38-14](https://user-images.githubusercontent.com/25869534/37319908-b7876204-2636-11e8-94f0-8e38e3828544.png)

**Comment by Masuzu** [comment]
Hello,
Sadly the RoB bosses are not considered as Nightmare modes, for now.
It's better to use the CustomizedScheduling mode for this use case, since the bosses will spawn after 8 hosts.

**Comment by Masuzu** [comment]
This is now partially addressed with the new checks available in the [Customized raid scheduling](https://github.com/Masuzu/ZooeyBot/wiki/Customized-raid-scheduling#rise-of-the-beasts-specific-commands) mode.
