### ISSUE TITLE
Extending License Error

### ISSUE THREAD

**Issue by Shamool** [Masuzu/ZooeyBot#645]
My current subscription is running out soon and I was planning to extend it today. However, I encountered an error saying that the site did not allow me to make live charges and to contact the owner. Would you mind looking into it?
I don't like to use paypal as it's rates are higher and I've had a bad run in with them before over some transactions and severly distrusts them now.

**Comment by Shamool** [comment]
![error](https://user-images.githubusercontent.com/30111700/37329095-5b1fb97a-26d7-11e8-9941-301270374c9d.PNG)

**Comment by Masuzu** [comment]
Hello,
This is more troublesome than I expected it to be and will take some time to resolve while an alternative can be found.

**Comment by Shamool** [comment]
Thank you for acknowledgement, I guess I'll just extend using Paypal for now.

**Comment by Masuzu** [comment]
https://github.com/Masuzu/ZooeyBot/issues/646
