### ISSUE TITLE
Coding Luscripts: Regarding usage of enemy_x

### ISSUE THREAD

**Issue by Shamool** [Masuzu/ZooeyBot#647]
I was trying to write an all-in-one luascript to be used for any ROTB raids because manually switching the configurations was just not efficient and I hit a snag. Below is my script where it checks for assault time and whether or not the raid was Xuan Wu.
I keep getting snagged on [[Checking for Xuanwu raid]] part where it tells me unexpected symbol as encountered. Any one here can help me?

DisableChargeAttack()

[[Checking for Assault Time]]
if turn==1 and character_1.charge_gauge==100 and character_2.charge_gauge==100 then
booleans["AssaultTime"] = true
end

[[Checking for Xuanwu raid]]
if enemy_3==nil then
booleans["NotXuanWu"] = true
end

if booleans["AssaultTime"]==nil then
	[[For Non-Xuanwu Raids]]
	if booleans["NotXuanWu"]==true then
		if turn==1 then
		EnableChargeAttack()
		character_1:UseSkill(1)
		character_1:UseSkill(2)
		character_1:UseSkill(3)
		character_4:UseSkill(2)
		character_4:UseSkill(1)
		character_4:UseSkill(3)
		end
	else
		[[For XuanWu Raids]]
		if turn==1 then
		SelectTarget(3)
		EnableChargeAttack()
		character_1:UseSkill(1)
		character_1:UseSkill(2)
		character_1:UseSkill(3)
		character_4:UseSkill(2)
		character_4:UseSkill(1)
		end
	end
else
	if booleans["NotXuanWu"]==true then
		if turn==1 then
		EnableChargeAttack()
		character_1:UseSkill(3)
		character_4:UseSkill(2)
		character_4:UseSkill(1)
		character_4:UseSkill(3)
		end
	else
		[[For XuanWu raids during ST]]
		if turn==1 then
		EnableChargeAttack()
		SelectTarget(3)
		character_1:UseSkill(3)
		character_4:UseSkill(2)
		character_4:UseSkill(1)
		end
	end
end

**Comment by Beedrills** [comment]
Which line, specifically, does it say the error's on?
If it's on the line with `if booleans["NotXuanWu"]==true then` then the problem may be an attempt to check a value that hasn't been set. Try adding in a
`if turn == 1 then
booleans["NotXuanWu"] = true
end`
before the xuan wu check.

That will have it set the boolean to true on the first turn always, but then set it to false immediately after if it is xuan wu.

**Comment by Shamool** [comment]
Thanks for the suggestion, I'll go try it out in Trials to see if it works
