### ISSUE TITLE
Zoey not starting

### ISSUE THREAD

**Issue by GromSC** [Masuzu/ZooeyBot#648]
Zoey gets stuck in an infinite loop like this doesn't fix even if I'm on fullscreen
![capture453452345](https://user-images.githubusercontent.com/37358988/37384395-a696e2d6-27a2-11e8-825c-46eae01bc1b0.PNG)
How do I solve this issue as I bought the monthly subscription and I can't figure out how to get it to work

**Comment by Shamool** [comment]
1) The console should be on network.
2) Did you set up your settings? Its inside the folder in a file called ZooeyBot.ini or something.

**Comment by Masuzu** [comment]
Thank you @Shamool
