### ISSUE TITLE
Refresh in select summon #2

### ISSUE THREAD

**Issue by NzString** [Masuzu/ZooeyBot#649]
#633 
I think it's not loading problem. My computer is 63ms ping with granblue server and fast loading, but every time refresh in select summon.
If I change MaxResponseDelayInMs=(100, 500, 3000, 5000), All the same refresh errors.

There is no problem with slave coop.

_I use Chromium 67.0.3367.0, use Vira, no fav summon, zooeybot(2.11.1)_

**Comment by NzString** [comment]
@Masuzu 
https://cdn.discordapp.com/attachments/201784369940004866/424951218683510785/mv.mp4

**Comment by Masuzu** [comment]
Thank you for the recording.
Ah, in this case you could increase the default value of the parameter `MaxNumActionRetries`

**Comment by NzString** [comment]
I change `MaxNumActionRetries` = 0~5, Same issue.
But new version refresh in 1 second, so no problem now.
