### ISSUE TITLE
Slave and Main just constantly refreshing

### ISSUE THREAD

**Issue by feeeeels** [Masuzu/ZooeyBot#65]
I just bought the zooey bot and read the wiki. I prepared the coop room with summons ready and readied on both accounts. But when zooey bot went onto autopilot it just kept refreshing both pages. What should i do

**Comment by feeeeels** [comment]
jesus this is a fuking mess

**Comment by BakaPhoenix** [comment]
did you perhaps click on ready your main acc before starting the bot?

**Comment by feeeeels** [comment]
MainAccountLuaScript=Scripts/slime_blasting_clarisse.lua
character_4:UseSkill(3)
SkipAttack()
this is what i have for clarisse with her being in the fourth position but the bot isnt using her ability 
also when have to manually select the slime raid because the bot doesnt seem to do so. Do you happen to have an already setup version that i could use. That would be of great help

**Comment by Masuzu** [comment]
Hello,

The instructions clearly state **not** to press the ready button. (i.e. it should not be red on the main account window)
