### ISSUE TITLE
RerollSummonWhenNoPreferredSummonWasFound not working with Scheduling

### ISSUE THREAD

**Issue by AL-XF** [Masuzu/ZooeyBot#651]
Hi~ I tried to use the scheduling function to do Rise of the Beasts.
It works nicely :) good work. However, zooey crashed when it was unable to find the summons which set in SetPreferredSummons. 
If I turned RerollSummonWhenNoPreferredSummonWasFound to true, it went to an incorrect url. 
for example:
http://game.granhttp//gahhthttp://game.granbluefantasy.jp/#quest/supporter/990041/17tp://game.granbluefa........................
I think it pasted the url between the original url. 
Would you mind take a look this problem? Thank you

**Comment by Masuzu** [comment]
Hello,
Thank you for reporting this issue. I will address it within the next 24 hours.

**Comment by Masuzu** [comment]
This is fixed in v2.11.2
