### ISSUE TITLE
PlaySoundNotificationAfterScheduling 

### ISSUE THREAD

**Issue by jentertaiment** [Masuzu/ZooeyBot#652]
hi, its not like its major bug, but, PlaySoundNotificationAfterScheduling isnt working as intended in scheduling mode, if i set this to true, after the schedule is finished, there is a popup like this :

![image](https://user-images.githubusercontent.com/37410509/37471689-f31d214c-289c-11e8-83cc-e8ca3d235d8a.png)

but no sound was played when the popup is still on, after i click "ok" the sound play by itself, so it might be not working as intended since i need to press ok before it proceed to play the sound

**Comment by Masuzu** [comment]
This was fixed as well.
