### ISSUE TITLE
Not useable after I updated

### ISSUE THREAD

**Issue by akira9311** [Masuzu/ZooeyBot#654]
I am trying to do the angle halo very hard. It keeps telling me that "No response after pressing the attack button for an abnormally long time".

In the version 1.2.2. yes, i didn;t play for almost a year.
MinWaitTimeInMsAfterAttack=500.

Now even I set the value to be 3600. It keeps crash. 
The message is 
No response after pressing the attack button for an abnormally long time
Proceed to next stage
New page loaded....
Battle 2/ -1
Move to result page (And it won't move again)

Why is this? please help me!
The slime blasting mode won't run after the first turn as well. It won't return to the lobby after "going to slave mode result"!!

Thanks!

**Comment by Masuzu** [comment]
Hello,
This is typical of this issue: https://github.com/Masuzu/ZooeyBot/issues/625
