### ISSUE TITLE
Zooey does not select summon on special quest.

### ISSUE THREAD

**Issue by eichisama** [Masuzu/ZooeyBot#655]
Hi Zooey does not select summon for special quest, it just stuck there doing nothing. Using basic mode.

![summon2](https://user-images.githubusercontent.com/33214703/37552142-078132d8-29ea-11e8-873c-44ff7203850d.JPG)

Config :
```

[Summons]
# Comma-delimited list of summons which will be selected in priority if they are available
PreferredSummons=Bahamur,Kaguya,White Rabbit
# In case none of the preferred summons was found, select a random summon in the given summon attribute tab, unless the parameter RerollSummonWhenNoPreferredSummonWasFound is set to true.
# Possible values are 'misc' (Kaguya, White Rabbit fall into this category), 'fire', 'water', 'earth', 'wind', 'light' or 'dark'.
# Not case-sensitive.
DefaultSummonAttributeTab=Dark
# Zooey will reroll summons until one of the preferred summons is available, using trial battles to refresh the summon list. This does not apply to the summon selection for the nightmare stage (see the EventMode section).
RerollSummonWhenNoPreferredSummonWasFound=false

```
What should I do?

**Comment by optiblast** [comment]
Gonna add mine. Trying to do AH.

![vmware_2018-03-17_21-03-28](https://user-images.githubusercontent.com/35657824/37561561-c036c580-2a27-11e8-97c2-90a734ec1dc0.png)

[ZooeyBot.ini.zip](https://github.com/Masuzu/ZooeyBot/files/1822257/ZooeyBot.ini.zip)

**Comment by Masuzu** [comment]
Hi,
The quest selection (favourite or special mode) will fail if you do not use a "correct" Chrome version or another Chrome-like browser: https://github.com/Masuzu/ZooeyBot/issues/625
