### ISSUE TITLE
Bot gets stuck on initial trigger for Xeno Corow

### ISSUE THREAD

**Issue by soufflenote** [Masuzu/ZooeyBot#659]
Hi! Just wanted to report a bug I've been running into while trying to farm the Xeno Corow event. The boss does a trigger at the start of the fight with a very long animation, and Zooey seems to get stuck on trying to select a character to use a skill because of this long period of no response at the start of the fight. 

To be specific, my lua script's lines in question look like this:

`
if battle == 3 then

  if character_1.name == "Protagonist" then
    character_1:UseSkill(1)
    character_1:UseSkill(2)
    character_1:UseSkill(3)
    character_1:UseSkill(4)
 end

`

Where the main character is on Elysian and skills 1 through 4 are concludere, miserable mist, call of the abyss, and clarity. Once Xeno Corow appears, the script tries to run the first line, and use concludere. However, Corow is still doing the animation for her trigger here. I get an error message saying an abnormally long time has passed since trying to press skill 1, and Zooey skips this line and goes to attempt to use skill 2, mist. This is where she gets stuck, and nothing further happens.

Hope the information helps!

**Comment by Shamool** [comment]
Just work around it by placing a
"Wait(5000)" command on turn 1

**Comment by Masuzu** [comment]
Hello,
Please do as @Shamool suggested. I can't do anything reliable about this matter but the aforementioned workaround works like a charm.

**Comment by soufflenote** [comment]
Got it, works perfect, thank you for the help! :)
