### ISSUE TITLE
Only runs once when farming EX+ through event mode

### ISSUE THREAD

**Issue by granblue5eva** [Masuzu/ZooeyBot#66]
Initial run works properly - selects summon, refreshes if no baha, and runs proper lua script to beat EX+ boss. However, after arriving at the results screen with EXP GAINED pop up, Zoey does not do anything else and just sits there. The last message shown in the .exe popup is "New page loaded: http://..."

**Comment by kiunch** [comment]
Did you turn on auto end quest/raid in viramaid. I found out that zooeybot wouldn't restart next quest. Same thing when my team wipe and backup finish the boss, zooey wouldn't start the next raid until I restart.

**Comment by Masuzu** [comment]
If your team is enable to complete the quest on its own then Zooey is not made for you.
Some support to use potions will be added later on.
