### ISSUE TITLE
sometimes stuck on trial battle

### ISSUE THREAD

**Issue by Sundaerae** [Masuzu/ZooeyBot#660]
using chromium and latest bot build.
when the bot goes to trial battle to refresh the summon list, sometimes it tried to press the attack button instead of going to quest screen and press retreat. It will just keep reloading the trial battle.

**Comment by meteoshower** [comment]
i can confirm this problem when in case  zooey will  attack with dummy  for a long time . it bug when reroll summon .

**Comment by thebp2** [comment]
I've seen this issue too.

**Comment by Beedrills** [comment]
Same here, I keep having to manually exit test machine and restart zooey.

**Comment by Masuzu** [comment]
This happens when the retreat failed. I will see what I can do.

**Comment by UminekoScarlet** [comment]
Got the same problem. It looks like the bot fails to properly press the Retreat button, when I observed it it seems to have clicked a bit below it.

**Comment by Shamool** [comment]
Just encountered this issue as well. In my case, it went directly to the Nightmare mode without going to quest page, missing the retreat popup.

**Comment by IZEROII** [comment]
I've seen this issue for a while (long time user).  

It happens in one of two forms either it reloads before it physically clicks reset or it gets stuck on the initiation of trial battle, hanging on the window popup detailing trail battles, and/or fails move forward to the retreat command.  As of the most reset release (unfortunately being forced into using chromium) this happens fairly frequently.

**Comment by Shamool** [comment]
A bit of an update and more info.I went back to using Chrome and I haven't encountered the issue for an hour or two now.

**Comment by IZEROII** [comment]
I can confirm what @Shamool has stated.  First time it will do it correctly.  If it has to reroll again the bot cripples itself. 

As we roll in 24 hours now...

**Comment by Sundaerae** [comment]
I tested using chrome 63, and the problem still there, so it's not really chromium problem.
and yeah, I cam confirm that the bot broke if it had to reroll twice because lack of summon.

**Comment by Masuzu** [comment]
I will add a user defined delay to mitigate the failures to retreat. It seems too much ping dependent.

**Comment by Jankos5571** [comment]
Has the possible fix ( the added delay ) been implemented? A few friends and I (and a few others it seems ) are running into this issue with the current Dark GW.
