### ISSUE TITLE
After selecting a summon it won't press okay to start the raid

### ISSUE THREAD

**Issue by Rimewind** [Masuzu/ZooeyBot#662]
When I start up the bot, it selects the summon then it just waits, and refreshes.  It won't press okay to select the raid.  I switched to the working chromium version as well.

**Comment by Rimewind** [comment]
to be more specific it keeps saying "something went wrong when trying to select the summon" and then it just keeps looping.

**Comment by Rimewind** [comment]
After playing around, it only seems to not work when doing event mode.  I am able to do custom raid scheduling for dailies.  I have no idea what's wrong

**Comment by BrokenWing67** [comment]
I'm having exactly the same problem. I've tried Chromium and downgrade my chrome to v63 and it still doesn't work. It was working fine just a couple of days ago tho.

**Comment by Rimewind** [comment]
I tried event mode with angel halo and it was able to work.  I think going to the Xeno showdown page first then going to the select summon page messes it up.  Not sure what the problem is though

**Comment by BrokenWing67** [comment]
i tried event mode with AH and it work just fine as well.

**Comment by Masuzu** [comment]
Hello, does the issue still persist if you increase all the delays in the General section of the configuration file and the MaxNumRetries parameter as well?

**Comment by BrokenWing67** [comment]
yes, the problem is still there

**Comment by Masuzu** [comment]
What does it do setting the MaxNumRetries to like 1000000? Does it get stuck without refreshing at least?

**Comment by BrokenWing67** [comment]
it just loops pressing summon and doesn't press ok with "something went wrong when trying to select the summon"

**Comment by IrbeinTepes** [comment]
I'm having the same issue

**Comment by Rimewind** [comment]
it selects the party just fine, but when it goes to select what summon you want to use it doesn't press "Okay" to confirm it, it just refreshes over and over

**Comment by IrbeinTepes** [comment]
in my side it doesn't even select the team, it just stop and reload to summon supporter after x seconds

**Comment by Masuzu** [comment]
Ah, so actually the loop happens before the message "Selecting party" is displayed on the console?
The only case where I had this was when I forgot to close some of the other DevTools windows which were hidden in some other tabs.

**Comment by IrbeinTepes** [comment]
I will do further testing after I get home

**Comment by BrokenWing67** [comment]
the loop only happens for xeno corrow, other quests seems to be fine.

**Comment by Masuzu** [comment]
Closed as could not be properly reproduced.
