### ISSUE TITLE
Summon not selected

### ISSUE THREAD

**Issue by tidusZX** [Masuzu/ZooeyBot#664]
After i start the bot and it goes to the summon page, it will not select any summon and just stop there. Any idea how to fix this?

**Comment by DarkenShade** [comment]
i also have this problem and have to scroll a bit with the mouse wheel and hit picks the summon but then when the battle started the bot crashed

**Comment by i-Grey** [comment]
Same as here. It happens sometimes. 
for me, I use ZooeyBot for Xeno farming nearly 3 hours, bot had stopped at the summon page for 2 times.

**Comment by IZEROII** [comment]
I can also confirm that at random the bot command box identifies the summon to select but the mouse cursor is off the game window.  When you manually move the mouse back over the game window, the bot re-activates and scrolls to the summon identified.  When this occurs and the summon is selected by the bot, there is a red text warning basically stating the battle is out of sync once the battle begins.  This is using latest bot with chomium.

**Comment by thebp2** [comment]
I'm seeing this too with 2.11.3

**Comment by meteoshower** [comment]
I can confirm this case my zooey can click summon on Impossible mode (What make sky blue 2) but Vary hard she wont click summon

**Comment by Jankos5571** [comment]
Can confirm, problem only started with this new update. I thought it was a browser problem and have tried swapping from Chrome to Chrome Canary to Vivaldi, yet the problem still persists.

**Comment by Sundaerae** [comment]
I also stumbled upon this problem once in a while.
I have to scroll a bit before the bot take over again and do its thing.

**Comment by Sundaerae** [comment]
(sorry I don't know how to edit via mobile page)
it is confirmed that the cursor sometimes going out of bound, to the right sidebar, so it can't scroll down. We have to move the cursor back to 'in game' so the bot can carry on with selecting summon it needed.

**Comment by Masuzu** [comment]
I will address this scrolling issue in the next release. And easy workaround is to use Chrome windowed mode and to reduce the width of your window to hide the option menu on the right side (black bar with the settings and chat icons).

**Comment by Sundaerae** [comment]
well, what I said about cursor on the right side is only 1 example.
once, the cursor moved to nearly the bottom of the screen (where the back, home button are) and also get this scrolling error.

**Comment by Masuzu** [comment]
Ok, got it, thank you for the information.

**Comment by Masuzu** [comment]
A fix was released for this issue: https://github.com/Masuzu/ZooeyBot/releases/tag/2.11.4
