### ISSUE TITLE
serial already taken

### ISSUE THREAD

**Issue by Onmae** [Masuzu/ZooeyBot#666]
![image](https://user-images.githubusercontent.com/37141155/37594593-03b61968-2bb9-11e8-9759-2545b79e084c.png)

i setuped new computer so i must change serial number
but cant..

can u help me?

**Comment by Onmae** [comment]
my email is cenfie@naver.com

**Comment by Masuzu** [comment]
Hello,
You could check whether it was not a previous account by retrieving the corresponding username? https://gbtools.azurewebsites.net/en/Account/ForgotEmail
If the associated user already has an active licence I won't be able to do much/

**Comment by Onmae** [comment]
i tried that 
i received mail that be written dan_naflaga@yahoo.com

can u reset that email with serial?

**Comment by Masuzu** [comment]
I can't do that if it is not your account in the first place. That would amount to stealing someone's else account.
