### ISSUE TITLE
Bot abort

### ISSUE THREAD

**Issue by CrimSugar** [Masuzu/ZooeyBot#667]
I can't use Zooeybot v2.11.3.
I will try to start bot,but bot is aborted.
I could use v2.9.x,but I can't start v2.11.3.

I found ucrtbase.dll is causing bot to crash, but I don't know how to fix it.

**Comment by Masuzu** [comment]
Hello,
Did you make sure to install VC++ Redistributable packages?

**Comment by Masuzu** [comment]
I can provide this missing file otherwise. I guess that you are probably using a Windows version below 10.

**Comment by CrimSugar** [comment]
I installed VC++ Redistributable packages,and My OS is Windows10 Pro 64 bit.

**Comment by CrimSugar** [comment]
Resetting bot,It worked fine.
Thanks.
