### ISSUE TITLE
Quests with side pop-ups

### ISSUE THREAD

**Issue by UthurPen** [Masuzu/ZooeyBot#668]
I recently have trouble with the automated farming when it comes to farming zephyr feather on chapter 1 Scattered Cargo
After the pop up shows the bot refreshes the page and just keeps on refreshing

**Comment by Masuzu** [comment]
Hello, please refer to the FAQ https://github.com/Masuzu/ZooeyBot/wiki/FAQ, "quests with a side scrolling stage".
