### ISSUE TITLE
Auto event mode...ish

### ISSUE THREAD

**Issue by Rkdheishins** [Masuzu/ZooeyBot#67]
im sorry the lua scrips are just to complicated for me, is there a way to just to have zoey auto the battle like with special or favorited quest's but now with unite and fight?

or! is there no general scrips for any team just to use all skills and auto?

**Comment by Masuzu** [comment]
Nothing is too difficult for people willing to put some effort into it to make their life easier.

**Comment by Rkdheishins** [comment]
Awesome!

Can you show me how to create lua scrips???

Youve literally given us a program and said figure it out.

It would be helpful to give a general "not in depth" guide in how to make some basic actions

Absolutely i can serch the web and get answers from someone else but from the sole creater i would hope to think you would walk with your customer a short while befor letting then go.

**Comment by Masuzu** [comment]
Please refer to the wikipedia https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts
All you need is a text editor such as https://notepad-plus-plus.org/ or https://www.sublimetext.com/

**Comment by Masuzu** [comment]
As for the event mode, it is a similar question as this one: https://github.com/Masuzu/ZooeyBot/issues/30
You can find below a working configuration to automate EX+ farming such as showcased in https://www.youtube.com/watch?v=p8ZauRRBdoM:
```
[EventMode]
# Set this parameter to true to use the event mode. Zooey will enter autopilot mode when you navigate to the quest menu.
Enabled=false
# Url of the summon selection page for Angel Halo (Extreme)
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/510031/5
EventRaidScript=
# Url of the summon selection page for Dimensional Halo
NightmareModeUrl=http://game.granbluefantasy.jp/#quest/supporter/510051/5
NightmareModeScript=
# Some events such as Rise of the Beasts require to navigate to the home page of the event before navigating to the event raid url defined above. If EventPageUrl is provided, Zooey will first navigate to this url before hosting the raid. Leave EventPageUrl blank for events which do not require you to do so.
EventPageUrl=
# Comma-delimited list of summons which will be selected in priority if they are available for the nightmare mode.
# In case none of the preferred summons was found, select a random summon in the summon attribute tab defined by the parameter DefaultSummonAttributeTab, unless the parameter RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode is set to true.
NightmareModePreferredSummons=Bahamut
# Zooey will reroll summons until one of the preferred summons for the nightmare mode is available, using trial battles to refresh the summon list.
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
# Set this parameter to true if the nightmare mode is available when you start Zooey so she can proceed to the nightmare stage right ahead.
NightmareModeAvailableAtStart=false
# Wait time in milliseconds after Zooey finishes loading the EventPageUrl
WaitTimeInMsAfterEventPageIsLoaded=1000
```
Simply replace your `EventMode` section in the configuration file `ZooeyBot.ini` with the parameters given above.

**Comment by Rkdheishins** [comment]
I've spend the last 2 hours trying to figure this out.

so i ended up copying your event mode section and what I got was zoey bot doing angel hollow automatically, so what i did was search this website of yours and ended up finding out to copy the url for the event "which is Guildwars" and posting it where it should be under  - EventRaidUrl, after doing so zoey was able to enter into the game" only by me actually clicking U&F and selecting the difficulty "which is weird because i know i selected the difficulty and then was on the screen to select a summon" once zoey oddly found a bunny/kaguya instead of bahamut i entered into the game only to see zoey trying to click on the attack button and refreshing not dismissing the window for backup when starting any raid.

conclusion, unable to utilize zoey for any guild war stage/ even when in stage unable to get zoey to dismiss backup window, i've spent the last 2 hours reading and doing the same thing over and over to the scrips with no avail...

im able to do slime more no problem
angel hollow
special stages like diablo and sagitarius
favorite quests/ story quest

but i cant for the life of me get this Unite and Fight zoey bot to work :(

**Comment by Masuzu** [comment]
Unite and Fight nightmare modes are known not to work yet.
The fix for this is "ready" but will need to wait for the next Unite and Fight event to be properly tested.

**Comment by Rkdheishins** [comment]
well thats explains alot, ill have to buy your product again and hope it'll be ready for the next event, thank you for your time and effort toward this.
