### ISSUE TITLE
Need help finding the problem with my script please

### ISSUE THREAD

**Issue by DarkenShade** [Masuzu/ZooeyBot#671]
need help finding the prob with the script.
im not using viramate with the bot.
the bot shows the script its reading but it only knows how to mash attack.
when i slime with the same version it works normally
![image](https://user-images.githubusercontent.com/36144222/37630480-cd1f8f52-2bb2-11e8-907f-d814849a41e5.png)

![image](https://user-images.githubusercontent.com/36144222/37630512-052b1506-2bb3-11e8-84cb-e0d49ddb7a5a.png)

**Comment by Sundaerae** [comment]
the correct syntax is characters[namehere]

**Comment by Hexadecimalism** [comment]
```
 if characters["Ferry"] ~= nil then
 	characters["Ferry"]:UseSkill(1)
 end
```
characters["character name"]UseSkill(x) is the correct syntax. Also works with whatever you name you mc.

**Comment by DarkenShade** [comment]
ah thank you it works now
