### ISSUE TITLE
Zooey not clicking on OK when using skills

### ISSUE THREAD

**Issue by takeshisen** [Masuzu/ZooeyBot#672]
Kind of need some help. The bot was working fine a few hours ago but for some reason it's not working now. It does not click the 'ok' button after selecting a skill to use. Any help would be great.
![image](https://user-images.githubusercontent.com/37564009/37631903-9b77757c-2c26-11e8-9629-d13458d41fcf.png)

**Comment by Shamool** [comment]
Idk anything about clicking okay, but just work around it for now by using description skip in granblue

**Comment by takeshisen** [comment]
omg. my brain farted for a moment. thanks alot. lol

**Comment by Masuzu** [comment]
Hello,
Indeed skipping skill description should be toggled on.
