### ISSUE TITLE
Very Important.

### ISSUE THREAD

**Issue by Miyoumu** [Masuzu/ZooeyBot#673]
Please check 
https://github.com/Masuzu/SarasaBot

Theres been a multitude of bot breaking issues that have not been looked at with a multitude of people facing the same issues.

Its your responsibility to monitor and appropriatly assess problems like this as soon as possible when money is involved, if a fix cannot be pushed out, please at least let people know you are looking into it. 

Thank you.

**Comment by Masuzu** [comment]
Hello, I will address this issue as soon as I can (today).
I apologize for the inconvenience.
Compensation in the form of a licence extension will be provided.

**Comment by Masuzu** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/SarasaBot?src=hash&amp;ref_src=twsrc%5Etfw">#SarasaBot</a> A critical bug made its way in the last release. Version 1.7.8 addressed it. A one week extension was provided to all the users with a subscription, whether their licence expired or not. I apologize for the inconvenience.</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/976006558587990016?ref_src=twsrc%5Etfw">March 20, 2018</a></blockquote>
