### ISSUE TITLE
GBF freezing on nm70 xeno corow

### ISSUE THREAD

**Issue by cfilorvyls** [Masuzu/ZooeyBot#674]
![image](https://user-images.githubusercontent.com/33967087/37636899-550fb50c-2c37-11e8-949e-a33421a7ed2b.png)
![image](https://user-images.githubusercontent.com/33967087/37636990-f8720de4-2c37-11e8-9a6e-2e7fe0bc9535.png)

```
Combat mode active
New page loaded: http://game.granbluefantasy.jp/#raid/228869891
Loading Lua script C:\Users\CFL\Google Drive\zooey-bot-v2.11.3\Scripts/xenocorownm.lua
Select character at position 1 (CFL.禁止)
Use skill at position 2
Use skill at position 1
Use skill at position 3
List of active buffs
6312_12 Dance of the Empress

Use skill at position 4
Select character at position 3 (Vira)
Use skill at position 2
No response received after using the ability at position 2 an abnormally long time!
Select character at position 4 (Jeanne d'Arc)
Use skill at position 1
No response received after using the ability at position 1 an abnormally long time!
Use skill at position 2
No response received after using the ability at position 2 an abnormally long time!
Use summon at position 6
No response received after using the summon at position 6 for an abnormally long time!
Script loaded
Enemy ID 6047315
Battle 1 turn 1
Attack
No response received after pressing the attack button for an abnormally long time!

```

Using chromium Version 67.0.3367.0. Had the same problem with Chrome Version 67.0.3367.0
Memory usage seems normal, so doesn't seem to be a memory leak problem?
Also, only have this problem on NM xeno while botting, never freeze while playing manually for a long time or on other battles.

**Comment by cfilorvyls** [comment]
Hmm i also use lite animation so there isn't really any intro animation, but i'll try that out

**Comment by Masuzu** [comment]
There is one even with lite settings.

**Comment by cfilorvyls** [comment]
I tried doing that and it doesn't freeze now, thanks
