### ISSUE TITLE
How to use skill when party HP is low than X% ?

### ISSUE THREAD

**Issue by YumeHaru** [Masuzu/ZooeyBot#675]
Hi,

I'm a total newby when it comes to scripting. I know that boleans exist but I didn't understood how can I code a condition like: if party HP is lower than 50% then Katalina cast heal.

**Comment by Shamool** [comment]
if character_1.hp_percentage<=50 or [fill in conditionals] then
booleans["PartyHPbelow50"]=true
end

//To use booleans in case booleans is true
if booleans["PartyHPbelow50"]~=nil then
etc
end

**Comment by YumeHaru** [comment]
Thank you very much!

**Comment by YumeHaru** [comment]
Thank you very much!
