### ISSUE TITLE
Need help:Nothing happens in Quest page

### ISSUE THREAD

**Issue by wyyin2010** [Masuzu/ZooeyBot#676]
Zooeybot didn't ask me to navigate to any quest. (same as event mode and default mode)

Thanks!

**Comment by Masuzu** [comment]
Hello,
Try and refresh your page to trigger the initialization phase. Make sure that the scaling is correct as well but I guess that you already did it.

**Comment by wyyin2010** [comment]
Yes, I have checked the scaling and try to refresh, but it still not work.
Is that any mistake with Zooeybot setting? What should I do now?

**Comment by Masuzu** [comment]
For your safety, I removed the picture since your player ID was visible.
This is what I get:
![image](https://user-images.githubusercontent.com/5464705/37661462-2ecbe5b4-2c55-11e8-93e2-9bff7e7d0476.png)
Did you make sure not to have your firewall or antivirus block the program?

**Comment by wyyin2010** [comment]
Yes, I close all the firewall and antivirus. I also reset the window system.
However, I still didn't and didn't ask me to navigate to the Quest menu!

**Comment by Masuzu** [comment]
Hello,
That is very unfortunate we could not find what the issue was, but I am sorry and won't fix issues affecting 0.1% of the user base. You can ask for a refund.
