### ISSUE TITLE
slave bot stuck at reloading after initialization

### ISSUE THREAD

**Issue by rotted** [Masuzu/ZooeyBot#677]
![image](https://user-images.githubusercontent.com/37586806/37661262-c2cc3f2e-2c97-11e8-9991-44332698f970.png)

**Comment by Masuzu** [comment]
Did you make sure not to press the ready button?
The instructions may look daunting at first but every detail counts https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)

**Comment by rotted** [comment]
yes, i didnt press the ready button

**Comment by Masuzu** [comment]
Closed and can't be reproduce if following all the guidelines *and* pitfalls described in https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)
