### ISSUE TITLE
Zooey bot crashes

### ISSUE THREAD

**Issue by ejcabell87** [Masuzu/ZooeyBot#678]
![image](https://user-images.githubusercontent.com/37592843/37672613-5bf6b4a6-2c3c-11e8-8b5e-17f216b40e51.png)

I am getting this error, I have followed the setup guide and have all the required microsoft stuff.  Please assist.

**Comment by Masuzu** [comment]
Hello,
This error at calibration means that it is a scaling issue. Did you make sure to set your browser zoom to 100%?
