### ISSUE TITLE
i have a problem ucrtbase.dll

### ISSUE THREAD

**Issue by rkrkrr0101** [Masuzu/ZooeyBot#679]
I use Google Translator
Run zooeybot.exe (5 out of 10 times) or intermittently (about every 10 minutes) while zooeybot is running
When I look at the Event Viewer, it says something about ucrtbase.dll
My situation was that I installed the Windows 10 64-bit VC 15 package, and this situation happened with v2.11.3 and v2.11.5
There was no such problem when using v2.11.1 and earlier versions

**Comment by rkrkrr0101** [comment]
i use slave mode
1. zooeybot start= zooeybot click>appcrash      !>popup
                                        

Normal situation= zooeybot click>popup>slavemode Detect


2. zooeybot running slave attack->Main window top->appcrash   !>main lua start

**Comment by rkrkrr0101** [comment]
event log 

 ZooeyBot.exe 
   0.0.0.0 
   5ab128b3 
   ucrtbase.dll 
   10.0.16299.248 
   dcc3eab0 
   c0000409 
   0009348b 
   14d8 
   01d3c093c84b49de 
   C:\Users\fds\Downloads\zooey-bot-v2.11.5\zooey-bot-v2.11.5\ZooeyBot.exe 
   C:\Windows\System32\ucrtbase.dll 
   13f4f5f6-8e1b-4eb5-9957-0275e5cd0eb5

**Comment by rkrkrr0101** [comment]
I ran it in administrator mode 
without using a firewall

**Comment by Masuzu** [comment]
Hello,
The VC++ 2017 redistributable package is required. Not the 2015 one.
