### ISSUE TITLE
Sent an E-Mail to you about the NM hosting issue specifying what I think the issue is.

### ISSUE THREAD

**Issue by Koraxor** [Masuzu/ZooeyBot#68]
Just to make sure you're aware, I sent it to your gbfpokerbot e-mail address.

Also must say I'm a little disappointed with the response time, I understand you have a life, but making sure your product works with GW should be a pretty large priority, but it's been days with no response, and I can only assume you didn't actually test if the wait time function you added for NM90+ actually fixed the issue.

**Comment by Masuzu** [comment]
Sorry about this, will follow up in https://github.com/Masuzu/ZooeyBot/issues/61
