### ISSUE TITLE
Customized Scheduled Raids not going to next quest

### ISSUE THREAD

**Issue by djeeta111** [Masuzu/ZooeyBot#680]
I have been using this for my daily hards (and normals during magfest).

Prior it worked perfectly (2.10.1 definitely) 

However as of late (2.11.2 at least that I've tested  &&  the current version 2.11.5), I've had some weird bugs where the customized scheduled raids does the 1st quest perfectly, but when it needs to do the quest again/go to the next quest, it just holds for an indefinite amount of time

I have reconfirmed as much as possible my settings compared to the zooeybot recommended ones, but it still does not go to the next quest

says the Battle 1 turn X then says result page

EDIT: if I use viramate it goes to saying battle 1 turn 47
then says "Proceed to next stage"
"Battle 2/-1"
"Move to result page"
then gets stuck there too

in 2.11.2, it had this same behavior, but after exited and reran the program it worked properly for the rest of them.   Did not test inbetween versions, and have not gotten 2.11.5 to work

**Comment by djeeta111** [comment]
log with id stuff stripped:

`Customized raid scheduling mode activated
Please check the configuration parameter ChromeDevToolsWindowDockedOnTheRight depending on which side your Chrome DevTools window is docked. The former has to be docked either on the right or at the bottom. Thank you.
Please start the Zooey bot Chrome extension to get started.
Initialization: 1/3
Please make sure to open the Chrome DevTools by pressing F12
Initialization: 2/3
Please make sure to open the Chrome DevTools by pressing F12
Initialization: 3/3
Player ID <>
Please navigate to the Quest menu.
New page loaded: http://game.granbluefantasy.jp/#quest
Entered quest menu
Zooey bot is calibrating
Calibrating
Successfully hooked to the Home button
Clear network request history
Zooey bot initialized
Loading scheduling script scheduling.lua
New page loaded: http://game.granbluefantasy.jp/#quest/supporter/<>/1
Listing available summons
Quest cost 0
Select summon white rabbit (rank 1) in misc attribute tab at position 6
Selecting party
Loading party selection script party_selection.lua
New page loaded: http://game.granbluefantasy.jp/#raid_multi/<>
Combat mode active
New page loaded: http://game.granbluefantasy.jp/#raid_multi/<>
Loading Lua script C:\Personal\Programs\GBFZooeyBot\zooey-bot-v2.11.5\Scripts/DailyHards.lua
Select character at position 2 (<>)
<>
<>
<>
Select character at position 1 (<>)
Use skill at position 3
No response received after using the ability at position 3 an abnormally long time!
Script loaded
Enemy ID <>
Battle 1 turn 1
Loading Lua script C:\Personal\Programs\GBFZooeyBot\zooey-bot-v2.11.5\Scripts/DailyHards.lua
Script loaded
Enemy ID <>
Battle 1 turn 2
Loading Lua script C:\Personal\Programs\GBFZooeyBot\zooey-bot-v2.11.5\Scripts/DailyHards.lua
Script loaded
Enemy ID <>
Battle 1 turn 3
Loading Lua script C:\Personal\Programs\GBFZooeyBot\zooey-bot-v2.11.5\Scripts/DailyHards.lua
Script loaded
Enemy ID <>
Battle 1 turn 4
New page loaded: http://game.granbluefantasy.jp/#result_multi/<>
Loading Lua script C:\Personal\Programs\GBFZooeyBot\zooey-bot-v2.11.5\Scripts/DailyHards.lua
Script loaded
Enemy ID <>
Battle 1 turn 5
Enemy ID <>
Battle 1 turn 6
Move to result page
New page loaded: http://game.granbluefantasy.jp/#quest/index
`

**Comment by djeeta111** [comment]
I have tested as well with the default .ini file and edited it to use the scheduling.lua, and the default scheduling.lua to test it.

Still the exact same issue

And I have also compared with the wiki's Setup-and-installation page to make sure my settings are right (though it does start and do the first battle/raid correctly.)

@Masuzu Is there a way to fix this or something?   This is the main feature I purchased this software for, so if this isn't fixed to how it was working, I don't have a use for Zooeybot ... which sucks after I renewed the license about a week ago (give or take)

**Comment by Thalatha** [comment]
Same issue but trying to do solo coop.

**Comment by Thalatha** [comment]
Turns out Chrome updated itself automatically and didn't tell me. Switching to Chromium 63.0.3225.0 fixed it.

**Comment by djeeta111** [comment]
Oops, I thought I was on the right browser for Chrome (main one, not on Chromium) 63.0.3239.132   My bad. sorry (I really need to remove the regular chrome because I don't really use it atm since I swapped to vivaldi as my main browser)

So yeah, the downgrading fixed the issue for me as well.  oops.

also as an aside, #690 might be a related issue to this one (and related to the Chrome regression in v65 outlined in #625)?

**Comment by Masuzu** [comment]
Hello,
Battle count inconsistencies are due to the last Chrome version:
https://github.com/Masuzu/ZooeyBot/wiki/FAQ
