### ISSUE TITLE
Zooey abnormal retreat.

### ISSUE THREAD

**Issue by meteoshower** [Masuzu/ZooeyBot#682]
Hello masuzu i have new issue about retreat from Machina alpha .after zooey choose summon for reroll and face with machina alpha she head to homepage and run notify.mp3  when i check aftersound alert i found she don't retreat the Machina alpha . I found this issue by event mode and reroll summon case

**Comment by meteoshower** [comment]
And i still have problem about zooey dont pick summon . she stuck at choose summon window so i have to move or click on game window manually then zooey can pick summon . Anyone still have this problem?

**Comment by Shamool** [comment]
Can't say I have. But I already didn't have summon selection problem before aside from trial reload thing that plagued everyone

**Comment by YumeHaru** [comment]
Are you using Viramate? Bot doesn't like to work with Viramate "farorite summon" option.
Though, I've to say that I encounter the same bug about the trial, from time to time my bot will get stuck there too.

**Comment by meteoshower** [comment]
@YumeHaru  I disable all of checkbox of summon tab in viramate

**Comment by Masuzu** [comment]
Hello,
Ah again that retreat issue.
After starting the machina alpha, did you mean that you were redirected to the Home page instead of the quest page? That could happen in some cases and lead to this issue.

**Comment by meteoshower** [comment]
@Masuzu  Yes Zooey redirected to homepage and make sound alert.After i test `PreferredSummons=i_do_not_exist` Zooey keep re-roll summon normally but after around 20 mins Zooey Redirect to homepage and make sound alert again

**Comment by meteoshower** [comment]
It's surprising today i dont have abnormal retreat and zooey dont pick summon problem .. but now i have problem like #686  zooey stuck in trail battle she keep  to summon window and back to training room again and again i'll try with  `i_do_not_exist`

**Comment by Masuzu** [comment]
I will follow up in https://github.com/Masuzu/ZooeyBot/issues/698
