### ISSUE TITLE
ZooeyBot.exe disappears from folder first time calibrating

### ISSUE THREAD

**Issue by lillieZai** [Masuzu/ZooeyBot#684]
I open ZooeyBot.exe it says No active window with GranblueFantasy was found
So I tried editing ZooeyBot.ini and changing Language=jp to Language=en
i also set ChromeDevToolsWindowDockedOnTheRight=false to true

When i ran it, it says to open the console by pressing F12 even when it was already open.
It started calibrating, went to home screen and refreshed a few times, then it played an audio repeatedly. I assume its the captcha notification
after closing it the Zooeybot.exe disappeared right after

I'm using zooey-bot-v2.11.5. and I use Viramate
![bot](https://user-images.githubusercontent.com/37609158/37696495-e145b4d8-2d11-11e8-917c-bacc14daf198.jpg)

Do I have a scaling problem? If so how do I change the scaling?

**Comment by Masuzu** [comment]
Hello,
If the exe file is deleted, this is definitely antivirus issue wrong flagging the program.
