### ISSUE TITLE
Bot skip "battle 2" command

### ISSUE THREAD

**Issue by YumeHaru** [Masuzu/ZooeyBot#687]
Hi,

I tried today to farm extreme of dark and to my surprise the bot **is skipping battle 2 command and just auto attack.** Beside that it works fine during the trial. I didn't encountered that bug before using new version of Zooey bot.

Bot version: 2.11.5
Chronium version: 67.0.3366.0

--------------
Combat Script
----------------
```
-- Use buffs/debuffs whenever they are available --
Summon(1)

if battlle == 2 then
Summon(6)
character_1:UseSkill(1)
character_1:UseSkill(4)
end

if battle == 3 then
character_1:UseSkill(3)
character_2:UseSkill(1)
character_2:UseSkill(2)

	if enemy_1.overdrive_state == true then
	Summon(3)
	character_1:UseSkill(2)	
	character_3:UseSkill(1)
	character_3:UseSkill(2)
	character_3:UseSkill(3)
	character_4:UseSkill(1)
	character_4:UseSkill(2)
	end
	
	if enemy_1.break_state == true then
	character_2:UseSkill(3)
	end
	
end
```

**Comment by Shamool** [comment]
Didn't you just mispell battle.... It's battlle 2 there...
