### ISSUE TITLE
Link to #679

### ISSUE THREAD

**Issue by rkrkrr0101** [Masuzu/ZooeyBot#688]
Link to https://github.com/Masuzu/ZooeyBot/issues/679
I've erased all vc ++ and reinstalled version 2017 of the vc ++ redistribution package, but the same problem repeats itself
Is there a solution?

**Comment by Masuzu** [comment]
Ah, I am sorry about this.
Did you make sure to install the 32 bit version of the VC++ 2017 redistributable package?
Here is a direct download link:
https://aka.ms/vs/15/release/vc_redist.x86.exe

(even if you use Windows 64-bit the 32-bit version is required)
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by rkrkrr0101** [comment]
Yes I have installed 86 bit

**Comment by Masuzu** [comment]
I would tend to think that it's missing Windows updates, as ucrtbase is provided directly with Windows without having to install anything else. This looks strangely similar to https://steamcommunity.com/app/356190/discussions/0/1484358860944996931/

**Comment by rkrkrr0101** [comment]
Can you tell what you are doing until the first popup after the program runs?

**Comment by rkrkrr0101** [comment]
i will find bug  and i will kill bug
