### ISSUE TITLE
Unregisterd User?

### ISSUE THREAD

**Issue by jn1127** [Masuzu/ZooeyBot#689]
![image](https://user-images.githubusercontent.com/31079598/37747095-69c88518-2d4b-11e8-9151-c80654f837f9.png)

What exactly is happening here? I was just able to use it and then the next minute, I get this error. My license is still good so not sure.

**Comment by Masuzu** [comment]
Hello,
Please check that the contents of your serial_number.txt file matches the one on https://gbtools.azurewebsites.net/en/Manage/ChangeSerialNumber
Thank you in any case for reporting the display issue.
