### ISSUE TITLE
Zooey bot stuck on result page

### ISSUE THREAD

**Issue by Firzin** [Masuzu/ZooeyBot#690]
Zooey bot gets stuck after completing one slime round. No error - just says waiting for result page.
![ss 2018-03-22 at 08 44 43](https://user-images.githubusercontent.com/36872239/37774412-814cc828-2db6-11e8-8a63-304cf749cafe.jpg)

**Comment by Masuzu** [comment]
Hello,
Please check your Chrome version:
https://github.com/Masuzu/ZooeyBot/wiki/FAQ
The "No response received" message leads into a bunch of other issues such as this one.

**Comment by Firzin** [comment]
The website you linked to download that Chromium version is not available. Oldest version you can find is the following : 2018-03-12: 67.0.3369.0 - 542473

**Comment by Shamool** [comment]
@Firzin
https://github.com/RobRich999/Chromium_Clang/tags

Under Windows tab when you click more information. I only found 3366, didn't bother looking for 3367
