### ISSUE TITLE
ZooeyBot not selecting a summon

### ISSUE THREAD

**Issue by crimn** [Masuzu/ZooeyBot#691]
I checked closed issues with similar problems but their solutions don't seem to apply to me.

![ss 2018-03-22 at 10 42 02](https://user-images.githubusercontent.com/37674971/37800397-f15619aa-2e22-11e8-8a8f-c7c4b040f52c.png)

I can get as far as the summon selection and Zooey doesn't select a summon. 
My .ini file should have any errors as it was still working 2 weeks ago. I unpacked the latest version, added the new key file after the domain change thing and copied my old .ini file into it.
Sarasa is still working so it shouldn't be an AV/firewall related issue.

Zooey crashes if I leave the summon selection by going back or clearing the selected quest.

**Comment by Masuzu** [comment]
Hello,
Couldn't it just be a Chrome version issue?
https://github.com/Masuzu/ZooeyBot/wiki/FAQ

**Comment by crimn** [comment]
Hi,
thanks for the feedback, it really was the Chrome version issue.
I tested it on the latest Chromium version and it works.
