### ISSUE TITLE
"No response after pressing the attack" after long hour of farming

### ISSUE THREAD

**Issue by Poko302** [Masuzu/ZooeyBot#692]
The problem just happenned a few hours ago after I let the bot farming Angel Halo for many hours. 

After I tried restart the bot, it returned the same error. I did not change any setting in ZooeyBot.ini at all.

I tried restart the bot many time. I tried changing many quests. It is still an error. 

I tried increase "MinWaitTimeInMsAfterAttack" from 600 upto 20000. It did not help.

The error always occurs in Battle 2.

[This is the error](https://imgur.com/a/kCPGn
)
I tried restart the pc, the problem is still there.

Anyone having this issue?

**Comment by Miyoumu** [comment]
Having this issue at the moment too.

**Comment by Masuzu** [comment]
Hello,
Please check the first lines here about the Chrome version:
https://github.com/Masuzu/ZooeyBot/wiki/FAQ, which is a common cause for this kind of issue.
