### ISSUE TITLE
No respond After Use Skills or Press Attack Button

### ISSUE THREAD

**Issue by MillionRice** [Masuzu/ZooeyBot#693]
After yesterday update of GBF, the zooey bot seems unable to retrieve use skill respond and attack respond. And also after finish a battle, the zooey bot will stuck at result page and will not repeat the selected quest. I have already update the version to the latest one but can not solve it. Please help to fix this asap. Thanks! 
![problem](https://user-images.githubusercontent.com/36122626/37828323-c0cfae28-2ed5-11e8-937e-95ce4d68384f.png)

**Comment by Mitsukai** [comment]
Having this same issue as well. The bot is correctly activating skills or attacking, but it doesn't seem to recognize that the attack/skill has successfully gone through.

**Comment by CreepersAU** [comment]
Can say the same, farming Xeno Corow for the last hours and after using a summon in position 6, it will correctly go through then crash after pausing due to thinking it never successfully summoned position 6. On current update as well.

**Comment by Masuzu** [comment]
Hello,
Please check the first lines here about the Chrome version:
https://github.com/Masuzu/ZooeyBot/wiki/FAQ, which is a common cause for this kind of issue.
Also, the past Xeno Corrow had some intrinsic issues (on the game side itself) when you were using Viramate. A workaround was simply to add a `Wait(xxx)` on the first turn to wait for the initial Corrow animation to complete.
