### ISSUE TITLE
It is possible to automatize the process to create a coop room?

### ISSUE THREAD

**Issue by JohnCog** [Masuzu/ZooeyBot#695]
It's not really a issue but is possible to create a coop room automatically? With the current state I need to go to my pc every hour to reset the bot. Taking the oportunity to ask the bot can use the xp boost and drop rate potion as well?

**Comment by Shamool** [comment]
As nice as it would be to not have to fully automate it, I believe it isn't a good idea. And Masuzu probably said something a while back about not planning on doing this when someone asked a similar question before.

**Comment by Masuzu** [comment]
Hello,
That would be convenient indeed but I am afraid I won't go in this direction; as automating the use of consumables to buff the room can sometimes fail, resulting in a partially buffed room and a wasted hour.
