### ISSUE TITLE
Is it possible to specify a party set?

### ISSUE THREAD

**Issue by SunNEET** [Masuzu/ZooeyBot#696]
Hi,
I wonder if there's a way to specify set A or set B when selecting parties.
It seems that GranBlue has turned the memorizing party function on by default, and that couldn't be canceled. As a result, my scheduling is often messed up because the party selecting page jumps unexpectedly between A and B, and then chooses a wrong team.

**Comment by Masuzu** [comment]
Hello,
Not yet for now.

**Comment by breinjhel** [comment]
Yea this is actually quite annoying I have to go over all enter all raids and set the party Set of each manually
