### ISSUE TITLE
Zooeybot going to the home page

### ISSUE THREAD

**Issue by OPZooey** [Masuzu/ZooeyBot#697]
When I go to the quest menu, after calibrating, zooey will attempt to go to http://game.granbluefantasy.jp/#quest/supporter/723991/1 before I even select a quest. This seems to go to the quest page for a moment judging by the music which makes sense as it looks like an address for a support summon page, but it will then go back to the home page.
![image](https://user-images.githubusercontent.com/37730150/37861677-10f90004-2efc-11e8-93e9-67e0ab0809d6.png)

**Comment by Masuzu** [comment]
Hello,
First of all, please check the URL of the quest.
Then, if it is a quest which needs material to host, then use this mode: https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode
