### ISSUE TITLE
Bot is stuck at clicking charge attack mode(hold/auto) at 1366 x 768 resolution

### ISSUE THREAD

**Issue by prokopets** [Masuzu/ZooeyBot#70]
Hi Masuzu!

Really appreciate that you've made bot to scroll down if ok button is not visible on Summon selection page. Is there a possibility to add such functionality in battle? Cauze my lua scripts make bot to switch off charge attack, but as button for disabling/enabling CA so is not visible, bot gets stuck on clicking on the bottom of the screen. Thank you!

**Comment by Masuzu** [comment]
Hi,

For now, please enlarge your window: it should be large enough with a 768 height?
https://i.imgur.com/c36awgY.png

**Comment by prokopets** [comment]
Unfortunately, this is the largest how i can set my screen(
![screenshot_24](https://cloud.githubusercontent.com/assets/22854160/26375719/af648c74-4012-11e7-9f87-4deb9ea2f01b.png)

**Comment by Masuzu** [comment]
Alright, thank you, I see. For now, an alternative is to use Viramate with its skill hotkeys which lets you enable/disable charge attack by pressing the 'C' key.

**Comment by prokopets** [comment]
Ok, thank you! I'do it that way

**Comment by Masuzu** [comment]
Yes that's it. This is what is showcased in https://www.youtube.com/watch?v=UJmuqbfEaM0
