### ISSUE TITLE
No response received... Abnormally Long time

### ISSUE THREAD

**Issue by mdanishu** [Masuzu/ZooeyBot#701]
I keep getting "No Response Received after ______ in abnormally long time!" 

it makes the fight longer, which i don't mind but when it moves to result page, the next fight in schedule bot does not occur. Any idea what is happening or how i can fix it? my zooeybot.ini is after the zooeybot log

[https://i.imgur.com/YuKNPKl.jpg](url)
![image](https://user-images.githubusercontent.com/18097717/37867695-1f9061f2-2f6a-11e8-9426-0e63a86c3866.png)

[General]
# Possible values: jp, en. Default to en when the string is malformed
Language=en
# ChromeDevToolsWindowDockedOnTheRight should be set to false if your Chrome DevTools console is docked on the bottom (as seen here https://i.imgur.com/bvTOq0g.png), and to true if it is docked on the right
ChromeDevToolsWindowDockedOnTheRight=true
MaxPageLoadDelayInMsBeforeRetry=3500
# Maximum amount of time Zooey will wait for an expected event to occur (for instance, the attack button appearance) before triggering the fallback policy.
MaxTriggerDelayInMsBeforeFallback=5000
# Maximum delay before an action is deemed to have failed due to a lack of response from the GBF servers
MaxResponseDelayInMs=5000
# Maximum number of retry attempts when an action fails (due to a lack of response for instance) before the fallback policy kicks in
MaxNumActionRetries=2
MinWaitTimeInMsAfterRefresh=2000
# The bot will stop after the given parameter no matter what.
TimeLimitInSeconds=999999
UseViramate=true
MaxNumPotionsToUse=40
# Zooey-bot will stop after using the given number of 1/2 AP potions (resets each time you restart Zooey-bot)
# Zooey-bot will start using full elixirs when this parameter is set to true if there is no 1/2 AP potions left. In any case, no more than MaxNumPotionsToUse potions will be used
UseFullElixirsWhenNoRemainingHalfAPPotions=false

**Comment by Koraxor** [comment]
Check your version of Chrome. Had a similar issue.
