### ISSUE TITLE
Licence generated as expired

### ISSUE THREAD

**Issue by williamvun** [Masuzu/ZooeyBot#703]
Licence generated is expired when entering it.
Tried on other computer also the same.

**Comment by Masuzu** [comment]
Please refer to the wiki FAQ page regarding this issue and update your serial number accordingly on your management page.
For any kind of common issue the FAQ should be the first thing you can check. https://github.com/Masuzu/ZooeyBot/wiki/FAQ

**Comment by williamvun** [comment]
But I did update it my serial number based on what it generated. when I update it, it still shows as expired. There's nothing in the FAQ regarding the problem.
