### ISSUE TITLE
Is is possible to check if daily raids are available?

### ISSUE THREAD

**Issue by junyong300** [Masuzu/ZooeyBot#704]
I want to farm Normal/Hard using ZooeyBot, but sometimes the scheduling script messes up and Zooeybot ends before the script is over.

Is there a way to check if other raids are available? for example 

if AvailableNumbers(" URL to LEVI HARD") >= 1 then
  RepeatQuest("LEVI HARD", 10,1)
end

This way, Zooeybot can skip finished raids and continue with the farming. 

Thank you.,

**Comment by Masuzu** [comment]
I will see what I can do about it.

**Comment by Masuzu** [comment]
Update: the feature is somewhat functional _but_ it could potentially get you banned if you try to schedule other types of raids with no daily limit.
