### ISSUE TITLE
Infinite Loop after running a while in quest farming

### ISSUE THREAD

**Issue by MillionRice** [Masuzu/ZooeyBot#705]
![325](https://user-images.githubusercontent.com/36122626/37872155-563b5a98-3034-11e8-81f7-762aa6767fc3.png)

Thanks for your update and message on Chrome version issue. Yesterday, I have updated to 2.11.6 version and download the recommended chrome version. But after running it for about 20-30 mins, it went to infinite refresh loop during battle. I have no idea what cause this.

Just reporting this issue. Will update if this happened in other mode later

:)

**Comment by Masuzu** [comment]
Did you make sure to disable Viramate auto hide popup?
