### ISSUE TITLE
trouble with sarasa bot installation

### ISSUE THREAD

**Issue by UthurPen** [Masuzu/ZooeyBot#706]
So im kinda confused on what to do on this part since i havent done anything like this before
on the create app for twitter what things should i input

**Comment by Shamool** [comment]
Basically, you need to create a twitter application, just google it. You don't really need anything but the name and some random description, fill in something for website if needed, doesn't really need to exist. After you create it, go to management and you'll find your access tokens there. Plug them into Sarasabot and you're done.

**Comment by IZEROII** [comment]
Why are you even posting in this forum.  There is a separate forum for that program....

**Comment by Masuzu** [comment]
Hello,
I do not want to be rude, but #ReadTheFuckingManual
Why is there even a [wiki](https://github.com/Masuzu/SarasaBot/wiki) with a FAQ
