### ISSUE TITLE
serial number mysteriously changed again

### ISSUE THREAD

**Issue by violafayde** [Masuzu/ZooeyBot#707]
Hi, I downloaded the latest patch and my serial number apparently changed again. I've raised this issue before and now I'm stuck with unregistered user... again.
![image](https://user-images.githubusercontent.com/33265321/37877894-b2dff010-3093-11e8-8da7-9a9d97750118.png)
![image](https://user-images.githubusercontent.com/33265321/37877892-a983ded2-3093-11e8-8687-a375a442f3db.png)
attached are the images of the serial generator and my current serial. The exact same thing happened last time, with my serial suddenly changing to the one shown in the 2nd screenshot. All along I have not changed computers and have used the same laptop for zooey.

**Comment by i-Grey** [comment]
It happens with me sometimes too.

I just rebooted my PC and serial revert back to the normal one.
I'm not sure it would help you or not but it's worth to try out.
