### ISSUE TITLE
Cannot download version 1.6.2 from Dropbox

### ISSUE THREAD

**Issue by Zoichan** [Masuzu/ZooeyBot#71]
Hi,
today when i tried to download the new version from Dropbox, the error 403 appear and I couldnt download the new version.
Please recheck the download link.
Best regard.

**Comment by Koraxor** [comment]
Masuzu tweeted that dropbox is down, so not much he can do unless he wants to host it elsewhere.

**Comment by Masuzu** [comment]
I can download the new version fine now. The direct download link is https://www.dropbox.com/s/h5jw02rfiptr787/zooey-bot-v1.6.2.zip?dl=1
