### ISSUE TITLE
Zooey detecting slave id in event mode

### ISSUE THREAD

**Issue by Firzin** [Masuzu/ZooeyBot#710]
Zooey is detecting my player id as a slave id causing it to never go past the quest screen. Using Chromium 67.0.3366.
![ss 2018-03-26 at 01 11 04](https://user-images.githubusercontent.com/36872239/37888026-18d36ccc-3093-11e8-9fc6-331e4880e098.jpg)

**Comment by Masuzu** [comment]
Hello,
That is just because you started the wrong extension.
Make sure to select the start the correct one (the one with the Zooey picture), not the one with the Beatrix picture.
