### ISSUE TITLE
Stuck after retreat from trial battle

### ISSUE THREAD

**Issue by aysien** [Masuzu/ZooeyBot#712]
![error](https://user-images.githubusercontent.com/31809167/37921322-75d3771a-3164-11e8-87bd-ea66b7d7e8de.jpg)

Hi Masuzu,

My bot always stuck in this location.
Its happen since 2.11.6 and still happen in 2.11.7
But its totally fine in 2.11.5.
It might related to Improved summon retreat feature on 2.11.6.
Im using Chromium Version 63.0.3225.0 (Developer Build) (64-bit).
Please take a look about this case. 

And can you give me reference regarding Chromium version that totally fine running 2.11.7?

Thank you.

**Comment by Shamool** [comment]
This seems to be the same issue in #698 that I hit as well.

**Comment by aysien** [comment]
Ill close and comment on your side instead.
Thx for heads up.
