### ISSUE TITLE
Trial Battle/Summon Re-Rolling Remains an Issue

### ISSUE THREAD

**Issue by IZEROII** [Masuzu/ZooeyBot#713]
![fail](https://user-images.githubusercontent.com/24773141/37938919-2e8b913e-312e-11e8-8da0-e6e1d16d63e7.png)

On Chromium v67.0.3370.0 (Developer Build) (64-bit) using ZooeyBot 2.11.7

Watched it happen.  Went to trial battle to reroll, on the dialogue box where retreat is to be selected the bot clicked on 'Resume'.  This brought it back to the trial battle where it then attempted to do the retreat sequence again and crashed.

#698 appears to follow the same line of issues

**Comment by Masuzu** [comment]
Hello,
I do not see why the Resume button would be clicked in your case while it is not the case for other users.
However, after retreating, there is indeed an issue with that last screen where Zooey can be stuck in some cases: https://user-images.githubusercontent.com/31809167/37922214-f251a918-3166-11e8-8c45-77ba1fa2816f.jpg

**Comment by Masuzu** [comment]
I will follow up in https://github.com/Masuzu/ZooeyBot/issues/698
