### ISSUE TITLE
Licence generated as expired

### ISSUE THREAD

**Issue by williamvun** [Masuzu/ZooeyBot#714]
But I did update it my serial number based on what it generated. when I update it, it still shows as expired. There's nothing in the FAQ regarding the problem.

**Comment by williamvun** [comment]
[http://oi64.tinypic.com/kf62ow.jpg](url)

**Comment by Masuzu** [comment]
Hello,
There is no more free licences.

**Comment by williamvun** [comment]
OK. Thanks. By the way, you should update the site too incase someone else asking the same thing.
