### ISSUE TITLE
Manifest file missing?

### ISSUE THREAD

**Issue by IgarashiDai** [Masuzu/ZooeyBot#715]
I renewed (or got for the first time, rather) my license and downloaded the program, but when I tried to get the extension to work, it told me the manifest file was missing. Is there a different extension that I'm supposed to download?

If so, where? 
EDIT: I saw a link where I suspect the extension should be, but all I get when I click on it is that it has been moved, lol.

**Comment by IgarashiDai** [comment]
![image](https://user-images.githubusercontent.com/37836106/37966645-72b40526-31c9-11e8-9a40-83ccd41e8446.png)

**Comment by Masuzu** [comment]
Hello,
The site moved to http://gbtools.azurewebsites.net

**Comment by IgarashiDai** [comment]
I know it moved there, but I can't find the extension on the new site. When
I click on any of the bots from that site, they send me to the page I sent
a screenshot of, which still has the faulty links. :/
Or if those links are not where the extension should be downloadable, where
can I find it?

2018-03-28 13:03 GMT+02:00 Masuzu <notifications@github.com>:
