### ISSUE TITLE
No active window with Grandblue Fantasy was found

### ISSUE THREAD

**Issue by kujaras** [Masuzu/ZooeyBot#717]
Updated to the newest version of ZooeyBot and started receiving this error.

![fdgh](https://user-images.githubusercontent.com/36498630/37993329-433287d8-31dc-11e8-820f-04ae89ce1a32.PNG)

**Comment by Shamool** [comment]
Did you remember to switch to en, it came default in jp this time.

**Comment by kujaras** [comment]
Alright, that fixed it. Thanks!
