### ISSUE TITLE
Parsing error: "argument expected"?

### ISSUE THREAD

**Issue by IgarashiDai** [Masuzu/ZooeyBot#720]
So I tried using the Treasure Event mode, but Zooey bot keeps telling me there's a problem with my code. I think it said the problem was in line 36 (something about an argument being expected near '[' ), but I really can't tell what it is...

This is the code:
![image](https://user-images.githubusercontent.com/37836106/38168020-929753f4-3541-11e8-9e14-8a99f16245b3.png)
![image](https://user-images.githubusercontent.com/37836106/38168023-adc8101e-3541-11e8-90de-91866fdeb5a2.png)

**Comment by Shamool** [comment]
Your last three lines of code from 36 - 38 is in wrong syntax. It's supposed to be UseSkill(~) not with box [ ]

**Comment by IgarashiDai** [comment]
Ohhh dang, how did I miss that :x
Thanks!
