### ISSUE TITLE
Bot loses focus after clearing network history during a raid.

### ISSUE THREAD

**Issue by violafayde** [Masuzu/ZooeyBot#721]
I noticed that the bot regularly clears the network history during long battles, every 5 turns. However, after clearing the network history, the bot is unable to process the lua commands for that particular turn because the browser focus is on the dev tools window and not on the game. I think a simple fix would be just to use the mouse cursor to click back into the game window, but you could try to replicate this bug before confirming. Thank you.
This has been happening while i was soloing the past two events' impossible 100 mode, which requires more than 5 turns per battle. Viramate is enabled. (hotkeys)

**Comment by Masuzu** [comment]
Hello,
Thank you a lot for reporting this issue. I will address it it in the coming days.

**Comment by Masuzu** [comment]
This is now addressed in v2.11.9
https://gbtools.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-11-9
