### ISSUE TITLE
Need guildelines to automate Robomi Z / EMPEROR TYRIAS [EX]

### ISSUE THREAD

**Issue by Gukak444** [Masuzu/ZooeyBot#722]
![capture](https://user-images.githubusercontent.com/37141179/38176740-c49ed132-361e-11e8-9fcb-7a80a10d3d6c.PNG)

**Comment by AL-XF** [comment]
Use TreasureEventMode
It did tell you how to select difficulty
# Supported value are 'vh' (for "very hard"), 'ex' (for "extreme"), 'impossible' (introduced since the "Right Behind You" event)

lua is the battle AI, you may need to think and write one or use the sample.

**Comment by Gukak444** [comment]
I try before but it doesnt work.What could i do?
![capture](https://user-images.githubusercontent.com/37141179/38179180-441cd708-364a-11e8-8925-e869a6447146.PNG)

**Comment by Shamool** [comment]
First, change the "ture" to "true".
Summons should be "lucifer".

If it doesn't work still, post a screenshot of the console log and your screen at point of failure.

**Comment by Gukak444** [comment]
Oh! i see.thank a lot fam and sorry about my stupidity.(>/\<)

**Comment by Shamool** [comment]
Sorry, I tested a few ideas that I had and they didn't work out. Need to wait for a person more proficient in Lua to help

**Comment by AL-XF** [comment]
I don't understand why you want to use at the lowest one....
but this will work for that even hp is full

local function getlowesthp()
    local t = {character_1.hp, character_2.hp, character_3.hp, character_4.hp}
    local key, min = 1, t[1]
    for k, v in ipairs(t) do
        if t[k] < min then
            key, min = k, v
        end
    end
    return key
end
UseGreenPotionOnPartyMember(getlowesthp())

**Comment by Masuzu** [comment]
@Gukak444 @AL-XF function does what you want to do perfectly.
