### ISSUE TITLE
slime-blasting not active main account browser.

### ISSUE THREAD

**Issue by AL-XF** [Masuzu/ZooeyBot#723]
Hi Masuzu, 
I got an issue when I tried slime-blasting today. I didn't have this issue two weeks ago.
After slave account use its ability, the bot try to use main account's ability, but failed.
Seems the main account browser was not been selected, until four timeout, it would be selected and continue. Stuck around 40 seconds for each slime, very inconvenient. 
Please take a look. thank you:)
![error](https://user-images.githubusercontent.com/30537599/38178857-4538ed68-35e9-11e8-9546-02d8fa6cf491.png)

**Comment by Masuzu** [comment]
Hello,
The picture shown shows that it is the slave account failing to obtain a feedback after an ability was used. This is typically an initialization issue where the slave extension was not started correctly, resulting in failures to detect any action performed by the slave account. Please make sure that you went through all the tiny details of the slave mode initialization and requirements as described in the wiki page.
I will check later on my side to see if it is a bug or not. I usually have my slave not performing any action.

**Comment by AL-XF** [comment]
Strange...I did try a few times, still same problem.
I didn't have this problem before OTZ.
Using Chromium - no version change at all
also, I didn't touch all delay setting in INI file since months ago.
-- After "Processing turn 1 of slave account", my slave account was using ability immediately. However, somehow the bot start "select character at position 1 (this is my main)". it failed, because the windows focus on my slave not my main. -> it tries 4 times -> all failed, and re-select my main window, then works.
I will try slave not performing any action to see. Thanks for the advice.

**Comment by Hustlin** [comment]
Hi
have you been able to find a solution for this? I am expierincing the same issue. Haven't changed the *.ini file since last Half AP for COOP and then it was working without delay.
