### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Mamaddzz** [Masuzu/ZooeyBot#725]
First time here but i don't know what i have to do...
I have fuliflled the Prerequisites like in game settings too
I am stuck at this step.
![12](https://user-images.githubusercontent.com/37998257/38188740-7338f084-3687-11e8-959a-00fb0c5cdc97.png)
i am on my quest to Robomi z event with this code setup
![123](https://user-images.githubusercontent.com/37998257/38188864-ee266182-3687-11e8-890d-467a5b2d9038.png)
Am i missing something?

**Comment by williamvun** [comment]
Try setting Animation settings to Standard and Resolution settings to Standard. Its should fix it.

**Comment by Mamaddzz** [comment]
But, my settings already like that.

**Comment by vegta12** [comment]
i am also having the same problem

**Comment by williamvun** [comment]
This is my settings. my screen resolution 1366x768. Browser set to maximize.
![solution 1](https://user-images.githubusercontent.com/22395744/38231968-a4ecaae2-3747-11e8-8cf8-d949badc8f9a.jpg)
![solution 2](https://user-images.githubusercontent.com/22395744/38231978-ada79ea8-3747-11e8-80e7-1f137970ca2c.jpg)
Some new chrome browser have problem with zooeybot. Currently I'm using chromium 49.0.2623.112.
[Link here](https://github.com/henrypp/chromium/releases/tag/v49.0.2623.112-r403382-win32).
Works fine for me.

**Comment by Mamaddzz** [comment]
It's working now, thank you so much!! 
I don't know if i have to fullscreen it.

**Comment by Mamaddzz** [comment]
I mean maximize it
