### ISSUE TITLE
Coop wont reload immediately after boss is dead [Multi character charge attack]

### ISSUE THREAD

**Issue by Gutenhl** [Masuzu/ZooeyBot#727]
It'll happen if i use yoda ougi instead of swordmaster to kill slime.
the setup is using 100% ca bar coop-item.
bot press attack then it'll wait for all the ougi animation to be over before going to result page.
i have tried both true and false for reloadpageonlastbattle
and changing extra time for 1 2 3 4 burst chain to 1ms
it just wont refresh asap

why not swordmaster? because i wanna use oliver for more placebo :D

(edit)
but it does go to the result page asap when in solo coop mode, not waiting for the ougi animation. It's only broken when using slave mode

**Comment by Masuzu** [comment]
Just to be sure, is it your main account or slave account performing the chain burst? Did you have any "Failed to obtain attack result" displayed in the console?

**Comment by Einhalkzt** [comment]
My main account. 
Main account attack first = true.
Nope I don't have any failed to obtain attack result.

**Comment by Masuzu** [comment]
I can't reproduce the issue for now. The battle end is detected properly and as a result there is no wait time after the chain burst is performed.

**Comment by Einhalkzt** [comment]
may i know your coop and combat settings?
this is mine

[SlaveMode]
Active=true
# Relative path to the script to use to customize the behaviour of the main account.
# If left blank, the slave account will attack at each turn.
MainAccountLuaScript=
# Relative path to the script to use to customize the behaviour of the slave account.
# If left blank, the slave account will attack at each turn.
SlaveLuaScript=Scripts/slime_blasting_sword_slave.lua
# By default, Zooey will make the slave account attack first. Set this parameter to true if you would like your main account to attack first.
ProcessMainAccountTurnFirst=true

[Combat]
# Zooey-bot will wait at least the given number of milliseconds after pressing the attack button
MinWaitTimeInMsAfterAttack=350
# Zooey-bot will wait at least the given number of milliseconds after using a summon
MinWaitTimeInMsAfterSummon=500
# Zooey-bot will wait at least the given number of milliseconds after using a skill
MinWaitTimeInMsAfterAbility=350
# Relative path to the script to use to customize the pace of combats. Embrace a world of infinite possibilities!
# Leave this parameter blank if you do not want to use any script. In this case Zooey will just attack at each turn. You can test your scripts using the TrialBattleMode (see the Debug section).
# Please refer to https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts for a comprehensive overview of the scripting features.
LuaScript=
# If set to true, Zooey will refresh the page after each attack on the last stage of a quest.
# This saves up some precious seconds and that is what every MVP racer does.
ReloadPageOnLastBattle=true
# Maximum wait time in milliseconds to load the character selection menu when an ability targetting a party member is used.
MaxWaitTimeToLoadCharacterSelectionMenuInMs=1100

# After performing a chain burst with 2 or more characters, you can't take any actions for a short period of time.
# Use the parameters below to configure how long you would like to wait when it happens.
AdditionalDelayInMsAfter2ChainBurst=1
AdditionalDelayInMsAfter3ChainBurst=1
AdditionalDelayInMsAfter4ChainBurst=1
AdditionalDelayInMsAfterOverchainBurst=1

**Comment by Masuzu** [comment]
Sorry for the late reply, sure, I used:
```
[SlaveMode]
Active=true
# Relative path to the script to use to customize the behaviour of the main account.
# If left blank, the slave account will attack at each turn.
MainAccountLuaScript=Scripts/test.lua
# Relative path to the script to use to customize the behaviour of the slave account.
# If left blank, the slave account will attack at each turn.
SlaveLuaScript=Scripts/test_slave.lua
# By default, Zooey will make the slave account attack first. Set this parameter to true if you would like your main account to attack first.
ProcessMainAccountTurnFirst=true
```
(the other parameters are the default ones from the ZIP).
test.lua is as follows (the main character job is set to Mechanic):
```
character_1:UseSkill(1)
character_1:UseSkill(2)
```
test_slave.lua is as follows:
```
character_1:UseSkill(1)
SkipAttack()
```
The latter is never called since the full chain from the main account clears the stage (H2-2 - torch), with Yodarha.
