### ISSUE TITLE
Zooeybot stopping at quest menu

### ISSUE THREAD

**Issue by kujaras** [Masuzu/ZooeyBot#729]
![untitled](https://user-images.githubusercontent.com/36498630/38271845-89e825f6-3755-11e8-94b4-e0f2655d2e7f.png)

Zooeybot started to stop at the "Please navigate to the Quest menu." step after the Robomi Z event started. The mouse curser stops right below XHR where the red marker in the screenshot indicates.

Using Chromium 67.0.3366.0.

The .ini file is set to en.

Event mode is enabled to attempt to farm Robomi Z quests + nightmare. This setting worked during Robomi Generations. Nothing was changed except for the links to the event page, the raid pages, the summons and the lua script.

**Comment by williamvun** [comment]
Did you try maximise browser?

**Comment by kujaras** [comment]
Yeah, just tried that. The curser goes right below the AP bar in the GBF window. Zooeybot is updated to the latest version. Still unsure of why this is happening. The developer's sidebar in Chromium is a little bit different than Chrome, I was thinking it could have something to do with that, but Zooeybot was working in Chromium in Robomi Generations just fine.

**Comment by kujaras** [comment]
![2](https://user-images.githubusercontent.com/36498630/38394080-1a6df974-38fb-11e8-90ca-9d7f9371f488.png)

I disabled mobile mode, and the mouse curser goes to where I indicated in the screenshot, but still nothing more happens. I recall this working with mobile mode during the last event, also.

**Comment by kujaras** [comment]
I re-installed everything and it works now. Don't know what was wrong, but I no longer need assistance, so feel free to close the thread.

**Comment by crimn** [comment]
I have the same problem using Chromium 67.0.3366.0
It occurs for Extreme/Nightmare event battle but it works for special quests and the other event quests.
![ss 2018-04-07 at 02 06 22](https://user-images.githubusercontent.com/37674971/38448912-d1da8038-3a08-11e8-98ad-9e68096dbf3a.png)

It's seems it's repeatedly trying to GET a resource but server is returning an error. When selecting a different quest it's requesting a different resource and works. Could this be related to the different URL pattern of the extreme and nightmare battle?

**Comment by Masuzu** [comment]
Hello,
About that last error, it seems likely to be the case.
But as far as I am concerned both URLs (for the EX and NM modes) are similar this time
http://game.granbluefantasy.jp/#quest/supporter/728141/5 (Extreme mode)
http://game.granbluefantasy.jp/#quest/supporter/728191/5 (NM 100 mode)
