### ISSUE TITLE
Version 1.6.3 crashes if japanese names are used for the summons in the config

### ISSUE THREAD

**Issue by greatmany** [Masuzu/ZooeyBot#73]
Program crashes instantly at launch if japanese names are used for the summons in the ini file

**Comment by Masuzu** [comment]
Could you please post here the summon list you tried to use?

**Comment by utenshien** [comment]
i have the same problem
this is my setting

PreferredSummons=マキュラ・マリウス,リヴァイアサン・マグナ

**Comment by greatmany** [comment]
what i used was 
PreferredSummons=バハムート

i have tried running it in english mode instead, however it crashes once it goes into battle, might be because my main character's name is in japanese

**Comment by utenshien** [comment]
sorry to post on your thread but
i saved it as UTF8 but this time it said no active window was found
everything worked fine in previous version
my system language is jpn

**Comment by greatmany** [comment]
It no longer crashes at launch once I used Notepad++ to save the config in UTF-8 instead of Notepad, thank you

the previous versions were ok when Japanese saved in Notepad, so you might want to put this info in the patch notes

**Comment by utenshien** [comment]
ok Notepad++ sloved my problem too
thank you greatmany

**Comment by Masuzu** [comment]
Thank you both of you :)

@utenshien P¨lease make sure that you have on Chrome widget active with GBF active as follows when you use the japanese langage settings to avoid this error message: ![](https://i.imgur.com/YWiBQHS.png)
