### ISSUE TITLE
Zooey stops working on extremes for the event

### ISSUE THREAD

**Issue by vegta12** [Masuzu/ZooeyBot#731]
Hey, When i run zooey to do the extremes for the event it will be fine and finish the first battle, after that it gets to the summon select screen and just stop.

**Comment by vegta12** [comment]
All the arrow is doing is slightly moving around on that summon screen. Anyone have any ideas.

**Comment by vegta12** [comment]
Also when zoey tries to clear browser history, it hits the top button since in chromium it’s the clear button and then the lightbulb button

**Comment by Masuzu** [comment]
Hello,
Make sure you configured `ChromeDevToolsWindowDockedOnTheRight` properly.
Then as long as your Devtools tab looks like this
![image](https://user-images.githubusercontent.com/5464705/38470531-66bcf88c-3b64-11e8-9af1-dc461efa4ae1.png)

You will be fine (the widget order does not matter)
