### ISSUE TITLE
Eternal calibration??

### ISSUE THREAD

**Issue by ImpulsiveCarrot** [Masuzu/ZooeyBot#732]
I've gone through the prerequisite shit several times to make sure I had ALL the settings right, and everything is setup right. Using Chromium since Chrome 65 is incompatible with Zooey. She'll stay at Initialization 2/3 if I don't leave the Devkit (F12 menu) open before starting her. If I don't follow the instructions and leave the devkit (F12 menu) open and just start her, she'll complete the initialization stage, ask me to navigate to the Quest Menu, and then she calibrates for all eternity. 

https://imgur.com/XSippie

I don't know if I'm just retarded and can't follow directions somewhere or what, but any help would be great since I have no idea what I'm doing.

**Comment by williamvun** [comment]
Try refer this [#725](https://github.com/Masuzu/ZooeyBot/issues/725)

**Comment by ImpulsiveCarrot** [comment]
Alright so I've gotten past the eternal calibration problem but now Zooey just attempts to select a summon a few times and sits at the home screen. I'm trying to get her to farm the Very Hard Angel Halo quest.

**Comment by ImpulsiveCarrot** [comment]
Screenshots wont load for some reason, but this is what she's doing

https://prnt.sc/j31zps

**Comment by ImpulsiveCarrot** [comment]
Also, I solved the Calibration issue by reinstalling Zooey and changing to chromium version 49.0.2623.112.
