### ISSUE TITLE
i Cant use my serial number

### ISSUE THREAD

**Issue by Onmae** [Masuzu/ZooeyBot#734]
![image](https://user-images.githubusercontent.com/37141155/38459713-5b11a50e-3ae8-11e8-9c56-e193a63b30c5.png)

My serial it is already in use.
As a result, I am making it impossible to use the program now.
My serial number says that my account is currently being used in 'dan_naflaga@yahoo.com'
This is an account that I do not know at all
Computer Formatt continued to cause this problems and ask for help.

**Comment by Onmae** [comment]
my serial number is fa2fda77ffb71ebef35b238fb0d2d5e4bd82ec8c52b09e2d74e2646ffa052759010c9ddc2377cf209f9907e3f4ca5522aafb728fbf9b6135a52be026d5565fa8

**Comment by Masuzu** [comment]
Hello,
I can't do anything for you in this case unfortunately since this serial number is bound to another user who has an active licence.
Using a different computer (avoid "shared university" computers) could fix that serial number issue.
