### ISSUE TITLE
Having trouble treating from trial battle

### ISSUE THREAD

**Issue by onionknight107** [Masuzu/ZooeyBot#735]
Sometimes when the bot tries to retreat, it does not do it correctly but instead jumping to the summon selection page.

**Comment by Masuzu** [comment]
Hello,
Do you have a full console log of what exactly happens?
Do you have bad ping usually (or unstable)?

**Comment by Masuzu** [comment]
That would only happen if after going back to the quest page, there is no popup with a
"Level XXX <raid nam> is in progress" with buttons <Retreat> and <Resume>displayed.
Or maybe it is specific to the japanese language settings. I will check with JP language settings.

**Comment by thebp2** [comment]
I'm seeing something similar. Zooey never goes to the quests page to retreat and instead goes right to trying to pick a summon.

**Comment by yuusui3** [comment]
This bug also occurred to me

**Comment by ngocin** [comment]
I have the same problem

**Comment by calvinhyang** [comment]
This is happening to me to when farming GW Ex+. I'm playing on english, so I don't think it's related to JP language settings. 
I also get the message that it says couldn't find the retreat button, and then it just keeps switching from the EX+ summon select page and going back into the same trial battle (that have failed to retreat). So you keep going to the EX+ summon select page with the same summons as before and as a result just get stuck in infinite loop.

**Comment by Masuzu** [comment]
Do you mean that after navigating to the quest menu you do not have any popup asking whether you want to retreat from the trial battle?

**Comment by Masuzu** [comment]
I have just made some amendments in v2.12.1.
You can use this configuration to test summon rerolling:
```
[Summons]
# Comma-delimited list of summons which will be selected in priority if they are available
PreferredSummons=FooBar
# In case none of the preferred summons was found, select a random summon in the given summon attribute tab, unless the parameter RerollSummonWhenNoPreferredSummonWasFound is set to true.
# Possible values are 'misc' (Kaguya, White Rabbit fall into this category), 'fire', 'water', 'earth', 'wind', 'light' or 'dark'.
# Not case-sensitive.
DefaultSummonAttributeTab=Light
# Zooey will reroll summons until one of the preferred summons is available, using trial battles to refresh the summon list. This does not apply to the summon selection for the nightmare stage (see the EventMode section).
RerollSummonWhenNoPreferredSummonWasFound=true
```
The summon to reroll being non-existent, it'll keep rerolling it.
Will follow up in https://github.com/Masuzu/ZooeyBot/issues/755
