### ISSUE TITLE
[Question]Terminate script when all member is gone.

### ISSUE THREAD

**Issue by Nassy1121** [Masuzu/ZooeyBot#738]
Does anyone know the way to terminate script when all characters is died?
Please share script sentence if you know.

Thanks,

**Comment by Shamool** [comment]
As far as I know, while you can condition for a situation where all your party is dead, you can't terminate the script

**Comment by Masuzu** [comment]
Hello,
You can't and will cause issues. Your party should be strong enough for the quest/raid you want to automate.
