### ISSUE TITLE
during slimeblast - bot doesn't always use the lua attack rotation

### ISSUE THREAD

**Issue by xeratzy** [Masuzu/ZooeyBot#740]
![image](https://user-images.githubusercontent.com/16266200/38643346-2276fb7a-3ddd-11e8-95e7-c9feb40cb65b.png)
![image](https://puu.sh/A19j0/10334f2719.png)

Noticed the bot sometimes ignores the skill rotation and goes right to refresh, also the bot sometimes get stuck and tries to go to reward screen before the run is finished, which causes the bot to get stuck doing nothing. Didn't catch a screenshot of this(can i see the log somehow?)

edit: seems to work fine again after i downgraded chromium to v65

**Comment by Masuzu** [comment]
Hello,
Did you mean that some skills were not cast while they should? Sometimes the "synchronize between windows" option of Viramate can cause such issues.

**Comment by xeratzy** [comment]
well, based on what I could see, the bot didn't try to  use the lua scrip and just pressed attack after a few seconds delay.

I did not use the above mentioned setting, and it works flawless now after i downgraded chromium so I cannot reproduce the problem.

**Comment by Masuzu** [comment]
All good then, some Chromium version may have the same issue as Chrome Version 65.0.3325.181
I am using Chromium Version 67.0.3376.0 just fine for now.
