### ISSUE TITLE
.lua - How do I create a proper counter variable? [edit: kinda solved]

### ISSUE THREAD

**Issue by xeratzy** [Masuzu/ZooeyBot#741]
EDIT: TLDR: I'm boosted, self-found my main issue.

Still would like to know why this line
```
  characters["Narmaya"]:UseSkill(2)
  characters["Narmaya"]:UseSkill(1):WithWaitTime(3000) <---- line where it breaks
  numbers["cd"]=0      
```
return this error: https://puu.sh/A2xYk/e3d533fc38.png

while this one:
```
  characters["Narmaya"]:UseSkill(2)
  characters["Narmaya"]:UseSkill(1)
  numbers["cd"]=0   
```
works perfect

______________________

For future reference:

counters are written as:
`numbers["counter_name_variable"] = numbers["counter_name_variable"]+1`

**Comment by Masuzu** [comment]
Hello,
All good then!
About that, please check again the wiki. You are using the old deprecated syntax. Now it should be:
`characters["Narmaya"]:WithWaitTime(3000):UseSkill(1)`
