### ISSUE TITLE
Bot repeatable tries to initiate next turn/.lua in multistage fights

### ISSUE THREAD

**Issue by xerance** [Masuzu/ZooeyBot#742]
Seems like the bot has some issues with detecting turns on multistage quests and tries to initiate a new turn:

https://puu.sh/A2QKP/fd007d4e72.png

Current used .lua is the same as coop slime one but with a second character skill after skill one and current stage is special quest shiny slime search running default mode in zooey.ini

**Comment by Masuzu** [comment]
I just can't reproduce the issue for now.
Each "empty" turn should end immediately normally. Make sure you did turn on Viramate auto complete features or the likes.

**Comment by xeratzy** [comment]
manage to get another screenshot
[](https://puu.sh/A7TKN/a582b48f73.png)
tested with both the auto complete feature on and off, no difference

bot settings are on event mode, stage is shiny slime search(special quest, 2 stages).

**Comment by Masuzu** [comment]
Hmm make sure not to use Viramate auto raid end features:
![image](https://user-images.githubusercontent.com/5464705/39265458-9b59750a-48c7-11e8-81e6-a29070b8ae07.png)

**Comment by xeratzy** [comment]
![image](https://user-images.githubusercontent.com/16266200/39394863-6466568c-4ad7-11e8-8585-79aecc9076b5.png)
what i'm using, tested with both auto on and off, same issue, haven't tested the new version yet, as it seem it doesn't detect the gbf window?

**Comment by xeratzy** [comment]
After some testing, this issue only appears on the search for shiny slime special quest, no other multistage quest i tested so far is causing this issue.

**Comment by sudonim7** [comment]
I've been notice Zooeybot running significantly slower for multi-stage battles, it would sometimes take 10 seconds before Zooeybot registers that a turn has ended and move on to the next stage. Attack Animations are also more clunkier and laggier during the fight on battles 1 and 2.

Not sure if anything has changed, I've only noticed this behavior about a few weeks ago.
