### ISSUE TITLE
no response after using the ability at position x an abnormally long time

### ISSUE THREAD

**Issue by abc123129** [Masuzu/ZooeyBot#743]
"no response after using the ability at position x an abnormally long time"

Since the latest update today, I've been getting this message immediately after using every skill when sliming (haven't check if this happens in other modes), meaning there's really no delay between the skill being clicked on by the bot versus this message appearing. So the parameter MaxResponseDelayInMs=2500 does not seem to be working.

The bot will just retry the skill several times (the numbers of times you allowed it to retry) and sometimes refresh the page randomly after this before proceeding to the next skill.  

If you then set the numbers of times you are allowed to retry to less than 2, this seems to mess up the skill order in the script if you have a long skill animation like conjunction.

Changing the MaxResponseDelayInMs seems to do nothing so I end up just leaving it at 2500.

So while the bot still works, it just wastes a lot of time trying to re-click every skill that has already went off.

**Comment by Masuzu** [comment]
Hello,
I guess that you also use Viramate. This happens if you have bad ping and your raid window stays black for a long time before loading the sprites. However, increasing `MaxResponseDelayInMs` should help. I will make the new feature introduced in v2.11.12 optional then.
