### ISSUE TITLE
Chromium messes up during slave mode

### ISSUE THREAD

**Issue by Firzin** [Masuzu/ZooeyBot#745]
Not really sure how to describe this... this always happens after a while when sliming in slave mode for Chromium Version 67.0.3366.0.

![ss 2018-04-16 at 10 54 26](https://user-images.githubusercontent.com/36872239/38850691-7ea40648-41e0-11e8-898d-998594b95023.png)

**Comment by devvah** [comment]
Happens here as well since few previous versions and after closing bot you have to close chrome using task manager so it seems like some memory leak?

**Comment by Masuzu** [comment]
Hello,
You should always have the Network tab selected. This is not the case with your Devtools windows.
