### ISSUE TITLE
Stuck on starting quest in slave mode

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#746]
Maybe some weird timing issue with finishing faster? With the new 2.11.12, zooey fails to press Ready on the main window and gets stuck pressing Start repeatedly on the slave window fairly often. My script is a single hit kill on the main window with Sarasa.

I think this was preceded by the main window sitting at the results screen for longer than normal.

**Comment by Masuzu** [comment]
This is definitely weird, pressing the start button if the ready button is not supposed to happen.

**Comment by thebp2** [comment]
This happened right away once with 2.12.4 so I managed to get the log. Looks like end of battle is not registering properly:
Initializing slime-blasting mode
Calibrating
Successfully hooked to the Home button
Clear network request history
Calibrating
Successfully hooked to the Home button
Clear network request history
Initialization complete, Zooey is now proceeding to autopilot mode.
46 remaining AP
Quest cost 10
Slave window - New page loaded: http://game.granbluefantasy.jp/#raid_multi/xxxxxxxxxxxx
Slave window - New page loaded: http://game.granbluefantasy.jp/#raid_multi/xxxxxxxxxxxx
New page loaded: http://gameC.goramnbbluaeftan tamsyo.jdp/e#c ooaprcaitd/irovome/8
8412P66rocessing turn 1 of main account

Waiting for Attack button to be active
New page loaded: http://game.granbluefantasy.jp/#raid_multi/xxxxxxxxxxxx
Loading Lua script P:\zooey-bot-v2.12.4\sarasa.lua
Select character at position 2 (Threo)
Use skill at position 3
List of active buffs
1036_9 Bounty

Script loaded
The battle ended.
Slave window - New page loaded: http://game.granbluefantasy.jp/#coopraid
New page loaded: http://game.granbluefantasy.jp/#coopraid
Processing turn 2 of main account
New page loaded: http://game.granbluefantasy.jp/#result_multi/xxxxxxxxxxxx
Slave window - New page loaded: http://game.granbluefantasy.jp/#result_multi/xxxxxxxxxxxx
Waiting for Attack button to be active
Slave window - New page loaded: http://game.granbluefantasy.jp/#coopraid
New page loaded: http://game.granbluefantasy.jp/#coopraid
New page loaded: http://game.granbluefantasy.jp/#coopraid/room/yyyyyyyy
Slave window - New page loaded: http://game.granbluefantasy.jp/#coopraid/room/yyyyyyyy
Refresh
Slave window - New page loaded: http://game.granbluefantasy.jp/#coopraid/room/yyyyyyyy
Refresh
Combat ended
Slave window - New page loaded: http://game.granbluefantasy.jp/#coopraid
New page loaded: http://game.granbluefantasy.jp/#coopraid
Slave window - New page loaded: http://game.granbluefantasy.jp/#coopraid/room/yyyyyyyy
New page loaded: http://game.granbluefantasy.jp/#coopraid/room/yyyyyyyy
New page loaded: http://game.granbluefantasy.jp/#coopraid
New page loaded: http://game.granbluefantasy.jp/#coopraid/room/yyyyyyyy
New page loaded: http://game.granbluefantasy.jp/#coopraid
New page loaded: http://game.granbluefantasy.jp/#coopraid/room/yyyyyyyy

**Comment by Masuzu** [comment]
Thank you for the logs, it looks related to https://github.com/Masuzu/ZooeyBot/issues/787
