### ISSUE TITLE
Bug　in　CustomScheduleMode

### ISSUE THREAD

**Issue by himappe** [Masuzu/ZooeyBot#747]
**first,**
use summon (EventMode - NightmareModePreferredSummons) and party(PreferredNightmareModePartyGroup and Deck) in "ZooeyBot.ini" when Play Nightmare Mode in Schedule after Maniac.
for example

SetPreferredPartyGroup("4")
SetPreferredPartyDeck("5")

SetLuaScript("Scripts/ConanManiac.lua")
SetPreferredSummons("Tiamat Omega_2,Grimnir_1,Tiamat Omega_1,Grimnir")
SetEventPageUrl("http://game.granbluefantasy.jp/#quest/extra/event")
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/728161/5", 50, 1) --Connan ManiacMode

SetPreferredPartyGroup("4") -- Not Active
SetPreferredPartyDeck("5") -- Not Active
SetLuaScript("Scripts/ConanHELL.lua")
SetPreferredSummons("Tiamat Omega_2,Grimnir_1,Tiamat Omega_1,Grimnir") --Not Active
SetEventPageUrl("http://game.granbluefantasy.jp/#quest/extra/event")
RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/728201/5", 1, 1)--Connan NightMareMode

**second,**
stuck in selecting summon when Play Nightmare Mode in Schedule after Maniac.
Active Window is NightmareMode Timer and GranblueFantasy Window is Not Active when Summon selecting.
Zooey bot Scrolling on NightmareMode Timer eternal...

**Comment by Masuzu** [comment]
Hello,
The parameter `NightmareModePreferredSummons` is ignored using the scheduling mode.
Use `SetPreferredSummons` instead.

About the second point, I heard that for some user the timer window could cause some issues. Thanksfully this can be addressed easily, which will be done in the next release.
