### ISSUE TITLE
Disable refresh?

### ISSUE THREAD

**Issue by IgarashiDai** [Masuzu/ZooeyBot#749]
Is there a way to disable the refresh at the end of a quest to skip to the results? 

I noticed that sometimes, Zooey tries to refresh and skip to the results, even though there is one more battle or one more turn before the quest ends. The result is that Zooey gets stuck and the loop ends. :/ I'm not sure if this bug is reproducible, but I do think it could be fixed easily by disabling the refresh not only between turns (I already found that option), but also at the end of a quest...

**Comment by Masuzu** [comment]
Hello,
Do you mean that Zooey tried to move to the result page on a multi-stage quest before the final battle?
I didn't have such issue in the last days, whether it was the collaboration event or Angel Halo.
For now the only possibility I see for this case would be that you are using one of the "blacklisted" Chrome distributions which had some compatibility issues.

**Comment by IgarashiDai** [comment]
Hmmm, I'll look into that. Thanks! (I'll report back.)

**Comment by IgarashiDai** [comment]
Update: Never mind! I have no idea what I did, but it seems to have worked XD

**Comment by Masuzu** [comment]
Surprising but I am glad that it ended up well then and that you got it sorted out on your own!
