### ISSUE TITLE
serpent toxin

### ISSUE THREAD

**Issue by zannettsama** [Masuzu/ZooeyBot#753]
anyone know how to clarity herb serpent toxin?

**Comment by Masuzu** [comment]
Hello,
You need to use the HasStatusEffect command in order to do so, after obtaining the status ID of the ailment in question. A detailed way to do so is described in the Lua script, status effect wiki page, using the Listener mode.

**Comment by Garnetus** [comment]
Can't find the debuff ID for this one...pretty sure this is a new defuff, would you mind to have a script for us on how to use herb when this debuff is applied?

**Comment by moourns** [comment]
the status effect id is 3012 for Serpent Toxin.
