### ISSUE TITLE
Albert's Electrified Status

### ISSUE THREAD

**Issue by Firzin** [Masuzu/ZooeyBot#754]
Hello, I'm attempting to run a Lua script with Albert - but using his 3rd skill the script into a loop where it can't exit due to it thinking Skill 1 or 2 is useable despite him just Electrifying himself. Is there a way around this?

**Comment by Masuzu** [comment]
Hello,
You can obtain the buff ID for this effect and use it in your script to avoid casting a skill with `if character_X:HasStatusEffect("<id>")` using the Listener mode as described here: https://github.com/Masuzu/ZooeyBot/wiki/Lua-Scripts-(playing-with-status-effects)
