### ISSUE TITLE
Verify message during gw

### ISSUE THREAD

**Issue by chuongcyper** [Masuzu/ZooeyBot#756]
[Hi,] i'm suing zoi bot now and there's an issue with verify message from the summon tab and it seems zoi bot cannot detect it and i have to click it myself. anyway to have zoi detect it? 
![11](https://user-images.githubusercontent.com/27999904/39167454-68142e60-47b9-11e8-9fdb-a82084b11763.jpg)

**Comment by Masuzu** [comment]
Hello, detection for this is implemented in both Zooey and Sarasa bot. Zooey will play in a loop a sound alert and stop moving when it appears. The detection was tested successfully during both the past Guild War and just a few hours ago as well.
