### ISSUE TITLE
Unable to select Luminiera summon and network error 

### ISSUE THREAD

**Issue by kwho292** [Masuzu/ZooeyBot#758]
Hello, I'm having issues with Zooey Bot never selecting Luminiera. I can't get it to work when I specify MLB/FLB or when I list it generally. Could anyone copy paste their working Luminiera summon section?

Second issue I'm having is that I get network errors selecting Nightmare 90 using event mode for Zooeybot. Should I be using treasure mode for this?

**Comment by devvah** [comment]
1) It's Luminiera Omega_2,Luminiera Omega_1 or シュヴァリエ・マグナ_2,シュヴァリエ・マグナ_1

2) Yes, NM requires meats to host and requires treasure mode.

**Comment by kwho292** [comment]
Thanks, it worked.
