### ISSUE TITLE
Help with running NM90 past the first time

### ISSUE THREAD

**Issue by vegta12** [Masuzu/ZooeyBot#759]
So everytime the bot beats the first NM, it no long picks the right summon for the 2nd battle and it keeps clicking charge attack or charge attack animation. how do i fix it so it doesnt go out of wack

**Comment by Masuzu** [comment]
Hello,
I can't provide any help without the logs displayed in the console starting from the point when it goes wrong.
Make sure you use the Treasure Event mode as well.
I ran fine for several hours in a row during the first round.

**Comment by AL-XF** [comment]
Don't leave DefaultSummonAttributeTab empty, give any attribute. I did get a lot of problems when I left it empty. If the first battle works ok, no idea why the 2nd battle failed. Did you move your browser window?
I hunt 3000 pieces of meat without any problem this this time.

**Comment by vegta12** [comment]
![img_1287](https://user-images.githubusercontent.com/34905307/39346617-ad0c0b80-49b4-11e8-837b-7a8840f76ef7.jpg)

**Comment by vegta12** [comment]
here is what it looks like @Masuzu   my mouse just hovers between that  spot. between the arrow and then it looks like that.
