### ISSUE TITLE
Slave bot still stuck at waiting for attack button

### ISSUE THREAD

**Issue by greatmany** [Masuzu/ZooeyBot#76]
Before the latest version 1.6.3 the bot was already successfully getting the focus of the main window so it appears that was not the issue causing the problem in my case

I've tried both english and japanese mode and in both cases it gets stuck unable to detect the attack button is active when it switches to main window

I've tried disabling Viramate but it crashes after it opens the skill window in battle (different bug)

Let me know if you need me to test anything for you

**Comment by Masuzu** [comment]
Hi,

I can't reproduce the situation on my side. Could you please test this version and tell me whether when the bot sets the focus on the main account window, you have this series of messages displayed in the console:
```
Waiting for Attack button to be active
Processing turn 1 of main account
Retrieve combat state -> This should appear
```
[ZooeyBot_for_debug.zip](https://github.com/Masuzu/ZooeyBot/files/1029590/ZooeyBot_for_debug.zip)

If it is stuck, could you please check the Chrome Devtools console of the main account window:
![image](https://cloud.githubusercontent.com/assets/5464705/26459715/b4592ae4-4177-11e7-9438-e476eaad1c72.png)
and check whether some error messages are there?

**Comment by greatmany** [comment]
![zbot1](https://cloud.githubusercontent.com/assets/28790334/26463034/9b7ad160-41b5-11e7-9b19-2a86a630e75e.jpg)
![zbot2](https://cloud.githubusercontent.com/assets/28790334/26463035/9bb90c32-41b5-11e7-81fd-387c1066604e.jpg)
This is what I've got

**Comment by Masuzu** [comment]
Ah, I guess that it is only the slave window which keeps refreshing the page, is that right? In this case, this means that you take more than the pre-defined number of seconds to load the page - not enough time to let the slave page load the attack button after it refresher.

Regardless of this matter, it looks like you have your main account script (configuration parameter `MainAccountLuaScript) do something like this:
```
SkipAttack()
```
as I see that your main account ends its turn not performing any action.

This new version waits for an increasing amount of time after each refresh:
[ZooeyBot_v1.6.4b.zip](https://github.com/Masuzu/ZooeyBot/files/1029821/ZooeyBot_v1.6.4b.zip)

**Comment by greatmany** [comment]
I've tried the new version and also tried removing SkipAttack from the script but the same problem still happens that does not attack in the main window

I removed the battle script completely and the console now shows that it detected it as battle ended (still does not attack in main window, and battle has not actually ended)

![screenshot 2017-05-27 00 11 54](https://cloud.githubusercontent.com/assets/28790334/26503045/ca64ae58-4271-11e7-9088-428e4984b30e.jpg)

I've tried switching slave and master roles, but what happens is that it still attacks only in the first window and is unable to attack when it goes to the 2nd window.

**Comment by Masuzu** [comment]
I am amazed since I have not received any such bug reports. There must be something wrong with your initialization. Please make sure that you pass this check and everything should be OK:
![](https://i.imgur.com/GmEYxui.png)
I also something really abnormal which should **not** happen:
When the slave page is refreshed, you should **not** see any message saying "New page loaded" (this should only happen only when a new page is loaded on the main account window).
After I load a new page the slave window, I only see messages along the lines of "Slave window - New page loaded" as follows:
![](https://i.imgur.com/VrcugYp.png)
[ZooeyBot_with_additional_debug_messages.zip](https://github.com/Masuzu/ZooeyBot/files/1033078/ZooeyBot_with_additional_debug_messages.zip)
If you see messages saying `Timeout, this should not happen!!!` with the enclosed version you know that it is "game over" and that you mis-initialized the slave mode.

**Comment by greatmany** [comment]
After you pointed out the problem with the "New page loaded" message I started checking the extensions.

I removed both extensions from the chrome and loaded them up again, still get "New network request" when i test the slave window.

I clicked **reload on both extensions** and tested and "New network request" was gone and the bot works fine now. I guess the problem was with the extensions being loaded wrongly somehow, which was not fixed somehow from removing and loading again, but I had to click on "reload"

![zbot3](https://cloud.githubusercontent.com/assets/28790334/26521039/797cccb4-4311-11e7-8300-4a7dc271feee.jpg)
![zbot4](https://cloud.githubusercontent.com/assets/28790334/26521038/797a475a-4311-11e7-9563-a46d183760e8.jpg)
For your debug purposes: these two images are from my final test before I tried checking the extensions and finally got the slave slime blasting to work, did not get the "Timeout" message.

**Comment by mynameisjovi** [comment]
@Masuzu I got the same problem. However I tried reinstall the extension or reload it, it still same.

**Comment by Masuzu** [comment]
Thank you for the report, there seems to be an issue indeed when multiple Chrome DevTools window are opened, where one of them captures the messages from the other window - something against which I can't do anything sadly. To avoid this, opening the DevTools console on one of the 2 windows, starting the extension on this very window, then repeating the process on the second window is a workaround.

@mynameisjovi Make sure to close all your Chrome DevTools console window before clicking on the ![](https://i.imgur.com/2t34wdV.png) button and to open one Chrome DevTools console at a time. If it still fails, close the Chrome Windows and repeat the process.
