### ISSUE TITLE
Create zooeybot lua scripts

### ISSUE THREAD

**Issue by williamvun** [Masuzu/ZooeyBot#760]
Is there any guide for writing the zooeybot lua scripts? The link provided "https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts" isin't very helpful and the internet have so many kinds of scripts but none for this. Does anyone have any scripts to share and we just edit it to our liked. Thank you.

This is my scripts written based on what I understand on how to write the lua script from masuzu link.

battle :1
Summon 6
character_1:UseSkill(3),UseSkill(2)
character_2:UseSkill(1)
character_4:UseSkill(1).useskill(3)
character_3:UseSkill(1)
character_1:UseSkill(4)

battle 5
Summon 1
character_1:UseSkill(1)

Its already have error on syntax 1 and I don't know what.

**Comment by xeratzy** [comment]
should be 
```
if battle == 1 then
  character_1:UseSkill(3),UseSkill(2)
  ...
end
```

**Comment by Masuzu** [comment]
Hello,
It should be
```
character_1:UseSkill(3)
character_1:UseSkill(2)
```
and so on
