### ISSUE TITLE
 I do not want to use the new features of Viramate

### ISSUE THREAD

**Issue by rkrkrr0101** [Masuzu/ZooeyBot#764]
I am slow in networking, and if I use new features, I will ignore the first summon or first blue potion and proceed to the next
This does not happen if the previous version or use of the Viramate is false

**Comment by rkrkrr0101** [comment]
Can not you make true false as an option?

**Comment by rkrkrr0101** [comment]
I think you can reproduce this by using vpn.

**Comment by Masuzu** [comment]
Hello,
Simply increase the value of `MinWaitTimeBeforeActionAfterEarlyTurnStartInMs` and it'll be fine.
