### ISSUE TITLE
I do not want to use the new features of Viramate #764  continue

### ISSUE THREAD

**Issue by rkrkrr0101** [Masuzu/ZooeyBot#767]
Failed to send chat messageSelect character at position 3 (Albert)
Use skill at position 1
Enemy at position 1 is in overdrive state.

This is the message that pops up when you use the blue potion
i give MinWaitTimeBeforeActionAfterEarlyTurnStartInMs=10000
It usually starts and stops for 4 seconds, then that message pops up and runs the next Lua.
start(popup attack button)->4sec->fail message->use skill1
Is there any security issue with my version 1.11.12?
And can I add the ability to turn it off and on?

**Comment by onionknight107** [comment]
increasing waiting time before using blue potion does not seem to solve the problem for me.

Using Summon multiple times maybe helps. For example using Summon(6) Summon(6) Summon(6) instead of just once.

**Comment by Masuzu** [comment]
Hello,
I took note of the request. I'll add an option to disable the feature then.

**Comment by Masuzu** [comment]
The feature is now disabled by default.
