### ISSUE TITLE
Enhancement: Commit default .ini to GitHub when there is an update

### ISSUE THREAD

**Issue by thenastyworm** [Masuzu/ZooeyBot#77]
It would be awesome if you could commit the new default ini to GitHub whenever you push a new build. This way someone so inclined would be able to quickly spot ini changes or additions with GitHub's diff view and make the relevant changes on their install and just replace the exe.

Of course I am aware that you already mention changes in the changelog and I could just diff my files locally versus the new release, but as a quality of life improvement for power users I think it would help.

**Comment by Masuzu** [comment]
Hi,

Very good point indeed!
I committed the latest ini file https://github.com/Masuzu/ZooeyBot/blob/master/ZooeyBot_v1.6.3.ini and will commit it again whenever some new changes are introduced.
