### ISSUE TITLE
OpenCV Error: Assertion failed

### ISSUE THREAD

**Issue by granbluebeepboop** [Masuzu/ZooeyBot#770]
![image](https://user-images.githubusercontent.com/38770561/39360922-2b23a45e-49ee-11e8-8b9d-1e1933919468.png)

Whenever I try to go to quest page to calibrate, it just instantly crashes with this error.

**Comment by Masuzu** [comment]
Indeed, or make sure that the Home button is visible in the top left corner.

**Comment by granbluebeepboop** [comment]
Windows scaling is 100% and chromium zoom is 100%. It does not even get past the black loading screen before it crashes, as seen here.
https://gfycat.com/RingedSkeletalHalibut

**Comment by granbluebeepboop** [comment]
![image](https://user-images.githubusercontent.com/38770561/39395904-ca87aeae-4ab2-11e8-8435-0d2195fe9a3f.png)
