### ISSUE TITLE
Failure to use summons at start of turn

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#771]
The new cast early with Viramate feature seems to not cast summons if they're first on a turn. I have this block at the top of my script:
Summon(6)
Summon(1)
Summon(3)
Summon(2)
Summon(5)
And it never uses them. After I moved them later down under skills, they do get used.

**Comment by Masuzu** [comment]
Hello,
In that case it means that your ping and page loading speed is not fast enough for the default value of `MinWaitTimeBeforeActionAfterEarlyTurnStartInMs`. Simply increase it.
