### ISSUE TITLE
Can anyone upload version 2.11.12 ?

### ISSUE THREAD

**Issue by Hustlin** [Masuzu/ZooeyBot#772]
not available on the page. I have replaced mistakenly the version with the new non-working version. I am not able to keep up with GW like that.

would appreciate if someone could provide v. 2.11.12

cheers

**Comment by mawile0816** [comment]
@Masuzu 
[zooey-bot-v2.11.12.zip](https://github.com/Masuzu/ZooeyBot/files/1957554/zooey-bot-v2.11.12.zip)
@Masuzu if its not good for you. please delete this comment

**Comment by Hustlin** [comment]
appreciated!
