### ISSUE TITLE
Issue with zoi copy the wrong link

### ISSUE THREAD

**Issue by masteraxel2602** [Masuzu/ZooeyBot#773]
Hi i have issue with sliming with slave mode for slave account. After the battle zoi copy the link to the ready screen but everytime i try it just copy the wrong link for examble:
http://game.granbluefantasy.jp/#coopraid 
Zoi keeps on copying this in the address bar:
http://game.grhttp//game.granbluefantasy.jp/#coopraidanbluefantasy.jp.

**Comment by Masuzu** [comment]
Hello,
I am not sure which version you are using but probably an old one.
This does not apply anymore in more recent versions.
