### ISSUE TITLE
Zooey should avoid bottom left screen corner

### ISSUE THREAD

**Issue by thebp2** [Masuzu/ZooeyBot#776]
Mostly seen this while doing coop. I'm using Windows 10 and sometimes Zooey moves the mouse to the bottom left corner, which causes the start menu to appear and covers my browser window.

**Comment by xeratzy** [comment]
cant you just resize the window and move it away from the bottom left corner?

**Comment by thebp2** [comment]
It's going outside the window all the way to the bottom left. I guess I could move the window away from the bottom a little, not sure if that would help or not.

**Comment by Ohwhat00** [comment]
Yea mine does that as well. Workaround was to move the browser to the opposite side, hasn't been an issue since.

**Comment by Masuzu** [comment]
All good then if you managed to sort it out like that!
