### ISSUE TITLE
Is it possible to request backup and tweet raid ID?

### ISSUE THREAD

**Issue by fdxcfdxc** [Masuzu/ZooeyBot#777]
if it is possible, then it would be much easier and fast to farm omega.

**Comment by Ohwhat00** [comment]
Someone suggested this before. Masuzu said this was a low priority enhancement and no plans to add the feature to zooey bot for now: https://github.com/Masuzu/ZooeyBot/issues/482

**Comment by Masuzu** [comment]
Hello,
The original choices catered to high end players but adding such an option would make sense now.

**Comment by cobeng13** [comment]
Excited for this one

**Comment by Masuzu** [comment]
Update:
The feature will be added as an experimental feature by the end of the week, which means that any possible related crash after requesting backup won't necessarily be addressed, or very slowly.

**Comment by Masuzu** [comment]
The feature is available as of v3.1.0, however note that continuous support for this feature may or may not  be provided.
