### ISSUE TITLE
Feature Suggestion - Trigger alarm alert when your party wipes

### ISSUE THREAD

**Issue by Ohwhat00** [Masuzu/ZooeyBot#780]
Basically have ZooeyBot trigger the alarm when your party completely wipes in a battle. 
Just wondering if it's possible for this feature to be implemented.

Would be nice for when you run the bot unattended for long period of time (ie 4-5 hours), with journey drop buffs enabled, but you end up dying to a bosses' trigger in one of the runs for whatever reason.

**Comment by Masuzu** [comment]
Hello,
I took note of the request.
