### ISSUE TITLE
Chrome v66 fixes whatever was wrong with v65?

### ISSUE THREAD

**Issue by Mitsukai** [Masuzu/ZooeyBot#781]
I noticed my Chrome auto-updated to v66 recently, and I decided to see if the bot would work, and unlike in v65 where the bot wouldn't be able to properly read and tell if scripted commands had been issued correctly, it was able to read them again now and properly received information from the game.

I haven't updated my version of the bot in while (I'm still on 2.11.12) and it still worked, so I'm guessing whatever the problem was before has been solved on Google's side?

Just figured I'd drop a thread and see if this is the case, or if it'd be recommended to still keep using v64 for now.

**Comment by Masuzu** [comment]
Hello,
As you said, those are good news. The official Chrome build  66.0.3359.139 works fine indeed and that's what I've been using. There is no need to use other Chrome builds.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ZooeyBot?src=hash&amp;ref_src=twsrc%5Etfw">#ZooeyBot</a> <a href="https://twitter.com/hashtag/SarasaBot?src=hash&amp;ref_src=twsrc%5Etfw">#SarasaBot</a> <a href="https://twitter.com/hashtag/GranblueFantasy?src=hash&amp;ref_src=twsrc%5Etfw">#GranblueFantasy</a> The last Chrome version (66.0.3359.117) is confirmed to be compatible \o/ No need anymore to use another Chrome distribution, but for how long?</p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/986727729650372609?ref_src=twsrc%5Etfw">April 18, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
