### ISSUE TITLE
ZooeyBot stuck at "Move to result page"

### ISSUE THREAD

**Issue by Toanl31** [Masuzu/ZooeyBot#788]
[https://i.imgur.com/i8BCsps.png](url)
The bot can resume itself after scrolling down but it seems to just be stuck here.

**Comment by Masuzu** [comment]
Update: actually it is similar to an issue which prevented scrolling down on the summon selection page.
I will address it in the next release.

**Comment by Toanl31** [comment]
I have actually fixed this completely by going full screen!
