### ISSUE TITLE
No active window with Grandblue Fantasy was found!

### ISSUE THREAD

**Issue by granbluebeepboop** [Masuzu/ZooeyBot#789]
https://github.com/Masuzu/ZooeyBot/issues/770
You closed my last issue without solving my problem.

As I mentioned in the thread, both my Chromium and Windows zoom are set to 100% and I posted pictures. 

You said "make sure the home button is visible in the top left corner" but I can't even get past the loading screen before it crashes, as seen here. https://gfycat.com/RingedSkeletalHalibut

e: Actually think I figured out what that issue is, but now I have another. I think the reason it was doing that is because it was ignoring my Chromium and hooking onto Chrome. But now I'm getting "No active window with Grandblue Fantasy was found!" 
And yes, my language is set to en in the config file. 
![image](https://user-images.githubusercontent.com/38770561/39732359-d9b9d8fe-523a-11e8-9736-22dd462da071.png)
Checked the wiki and I don't see any other indication as to what it could be. It's also encoded using UTF8. 
![image](https://user-images.githubusercontent.com/38770561/39732392-014d5026-523b-11e8-944b-217570f00e28.png)

**Comment by Ohwhat00** [comment]
From my experience using chromium(not sure if this also applies to chrome), changing the encoding to UTF-8 for ZooeyBot.ini doesn't work, but it does work for lua scripts.

Try change the encoding for ZooeyBot.ini to ANSI and see if you still get the same issue.

**Comment by granbluebeepboop** [comment]
Neither works.

**Comment by Masuzu** [comment]
Ah the crash may happen if the page you move to from the Home page takes relatively long to load but it is a relatively isolated issue and not reproducible, and therefore is qualified as very minor.
You should star navigating to http://game.granbluefantasy.jp/#quest before starting the executable file, then refresh the page (with F5) when prompted to navigate to the Quest menu.
