### ISSUE TITLE
Still having issues with refreshes

### ISSUE THREAD

**Issue by feeeeels** [Masuzu/ZooeyBot#79]
This is my setting under slave mode:
Active=true
You can get the quest ID of a coop quest using Chrome DevTools https://i.imgur.com/FDlL9Gw.png 601011 is the quest ID of the slime stage (H2-1)
QuestId=601011
Relative path to the script to use to customize the behaviour of the main account.
If left blank, the slave account will attack at each turn.
MainAccountLuaScript=Scripts/slime_blasting_clarisse.lua
Relative path to the script to use to customize the behaviour of the slave account.
If left blank, the slave account will attack at each turn.
SlaveLuaScript=Scripts/slime_blasting_sword_master.lua
By default, Zooey will make the slave account attack first. Set this parameter to true if you would like your main account to attack first.
ProcessMainAccountTurnFirst=true

slime_blasing_clarisse.lua being
character_4:UseSkill(3)
SkipAttack()

when i load the program up and got the slime room ready the bot for some reason clicks on the far bottom left corner causing another tab to open but once i manually close that it readies up and goes into the slime battle. But it just freezes there doing nothing and starts refreshing and replacing the url.
http://prntscr.com/fco5i0 this is what i see in the battle.
Its been 9 days since i bought the bot and still have not been able to use it once properly and instead wasted alot of time. Kinda frustrating

**Comment by Masuzu** [comment]
Hi,

The point you mention with Zooey clicking on the far bottom left corner is related to
the parameter `ChromeDevToolsWindowDockedOnTheRight=false`
Please make sure to set it to true if your Chrome DevTools window is docked to the left.
The bot will at the initialization and periodically clear the network history or else your browser will be significantly slower after some time.
