### ISSUE TITLE
'Failed to Select Character Bug' Persists v2.12.6

### ISSUE THREAD

**Issue by IZEROII** [Masuzu/ZooeyBot#791]
This is using new version v2.12.6 non viramate user as addressed in #790 

Confirmed that unable to use skills for character in position 4.  Funny enough, I have Zooey in position 4 and the bot fails to use her skills when scripted.  I changed her to position 3 and adjusted the script to reflect that and success was achieved.

**Position 4 character fails to cast skills**.  This bug has not been rectified @Masuzu

**Comment by utenshien** [comment]
same problem here

**Comment by soufflenote** [comment]
Chiming in, same issue here.

**Comment by Masuzu** [comment]
Hello,
Thank you for providing details about that particular issue. I will address this issue during this week-end.

**Comment by Masuzu** [comment]
The week was eventful but I did not forget about this issue!
This is now addressed in v2.12.7
