### ISSUE TITLE
No active window with Grandblue Fantasy was found

### ISSUE THREAD

**Issue by granbluebeepboop** [Masuzu/ZooeyBot#793]
"No active window with Grandblue Fantasy was found!"
And yes, my language is set to en in the config file.
![image](https://user-images.githubusercontent.com/38770561/39967212-5f6dbabc-5685-11e8-916c-953df78f7884.png)
I've even tried removing the line so it defaults to English. Still does nothing.

![image](https://user-images.githubusercontent.com/38770561/39967217-77476f02-5685-11e8-942d-e277d2fbb934.png)

**Comment by granbluebeepboop** [comment]
I do not use an antivirus, and I have UAC disabled ("never notify"), as well as tried running as admin.

**Comment by Masuzu** [comment]
Consider yourself to be lucky to be the first one to have that particular issue persisting then!
Hopefully we will find a solution.

**Comment by Masuzu** [comment]
Additional messages are now displayed in the console when this happen (for Zooey Bot only).

**Comment by granbluebeepboop** [comment]
Well, I updated to the new version and keep getting this. 
![image](https://user-images.githubusercontent.com/38770561/40087995-065957de-5873-11e8-948f-b2e43c029f59.png)

Then I changed changed my serial number and I don't think I should have done that.
To be clear, it already was throwing that error before I changed anything. But still pretty sure I messed up by changing my serial number.

Is it possible for you to reset it or something?

**Comment by Masuzu** [comment]
The 4 day restriction to update your serial number was temporarily lifted.

**Comment by granbluebeepboop** [comment]
![image](https://user-images.githubusercontent.com/38770561/40246385-9aeb03b4-5a96-11e8-8de6-ed4269fa5547.png)

Not sure how much this helps but here you go

**Comment by granbluebeepboop** [comment]
![image](https://user-images.githubusercontent.com/38770561/40246567-3e539282-5a97-11e8-8254-60e0f0c626db.png)

Here you go

**Comment by Masuzu** [comment]
Whoa, so it is that your Chromium version does not display properly the window names.
You should use the official Chrome build, which does not have this issue.
My GBF window is listed as `Granblue Fantasy - Google Chrome`

**Comment by Masuzu** [comment]
If you are fine with it, you are free to send the email that you used to register an account on the website to support@azuriteworlds.com. I would be more than happy to provide an extension of your licence for the troubles you encountered.
@granbluebeepboop

**Comment by granbluebeepboop** [comment]
> However, this is definitely weird that in the picture you sent, Notepad++ does not even appear.
I opened it afterwards. 

Anyway, got it now. Appreciate it. 
![image](https://user-images.githubusercontent.com/38770561/40285147-e11703f2-5c66-11e8-89d1-040dacc7a008.png)

**Comment by Masuzu** [comment]
Granted!
