### ISSUE TITLE
Guidelines for automated Xeno Vohu Manah farming

### ISSUE THREAD

**Issue by Masuzu** [Masuzu/ZooeyBot#794]
You can use the [Event mode](https://github.com/Masuzu/ZooeyBot/wiki/Event-mode) to automate farming the Nightmare and Extreme modes of the ongoing Xeno Vohu Manah showdown, by setting the parameter `EventRaidUrl` to http://game.granbluefantasy.jp/#quest/supporter/501031/5 (Xeno Extreme raid URL) under the `EventMode` section.

You will find below the URLs of the Nightmare modes. Choose the one you would like to clear by overriding the `NightmareModeUrl` value under the `EventMode` section.
- Nightmare mode Level 70: http://game.granbluefantasy.jp/#quest/supporter/501051/5
- Nightmare mode Level 100: http://game.granbluefantasy.jp/#quest/supporter/501061/5
- Nightmare mode Level 120: http://game.granbluefantasy.jp/#quest/supporter/501071/5

Last but not least, you can also automate the Xeno Level 100 raid version by using the [Treasure Event mode](https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode).

Good luck with your drops!

**Comment by YumeHaru** [comment]
Hi,

I don't want my party to use skill during the first turn of the battle, what do I need to write? I didn't found it in your scripts files on Github.

**Comment by Masuzu** [comment]
Hello,
This question has no place here. For your answer, please refer to https://github.com/Masuzu/ZooeyBot/wiki/Lua-scripts#global-state-of-the-raid
There are several examples provided in https://github.com/Masuzu/ZooeyBot/tree/master/Scripts matching this case.
