### ISSUE TITLE
Zooey not starting battle after summon gets selected

### ISSUE THREAD

**Issue by Allurez** [Masuzu/ZooeyBot#796]
Only happening for Xeno Vohu
https://gyazo.com/6cf48e0123347d2511dfa9d3fd5d42e3
infinite loop of: selects summon > fails to start battle > refresh
Chrome Version 66.0.3359.170

**Comment by Masuzu** [comment]
Hello,
I doubled check and things work fine. There was a Chrome update today as well today.
Make sure to disabble this Viramate feature:
![image](https://user-images.githubusercontent.com/5464705/40080002-f9e02dea-5889-11e8-9f90-9b7018b6d242.png)
If your ping is high, also make sure to increase `MaxResponseDelayInMs`.
