### ISSUE TITLE
Unregistered error

### ISSUE THREAD

**Issue by Ramkm77** [Masuzu/ZooeyBot#797]
Hi . Starting from today I'm getting unregistered error on zooey bot and sarsara bot. I tried to update my pc serial number it's the same no change. Not sure what made the bots giving this error. Any suggestions how to solve this issue ? Thx

**Comment by Masuzu** [comment]
Hello,
This is a frequent question. Hopefully instructions to solve this can be found [here](https://github.com/Masuzu/ZooeyBot/wiki/FAQ#i-get-an-unregistered-user-error-message)!

**Comment by Ramkm77** [comment]
Thx for the answer but. Seem I have an issue here . When I change the serial number on the txt file. And run the bot. Its auto change my serial to another 1. Anyway i took this and updated my serial on the page its work . But still giving me annoying error 
![20180516_023612](https://user-images.githubusercontent.com/30638021/40087046-f8c6f63c-58b1-11e8-9ba4-15d3fbcf4b18.jpg)
