### ISSUE TITLE
Running multiple battle number if statements?

### ISSUE THREAD

**Issue by kujaras** [Masuzu/ZooeyBot#798]
I am using the following lua script to farm Xeno Vohu EX and the code in the "if battle == 1 then" statement will activate in the first battle, but the code in the "if battle == 3 then" statement will not activate during the third.

I've had this code work for many other three turn battles, but it suddenly stopped working and I can't for the life of me figure out why. Perhaps I am overlooking something obvious? Let me know if anyone can help me out here. ZooeyBot is up to date.

EDIT: I tried commenting out the "if turn == 1 then" statement as well as the "if battle == 1 then" statement, and the "if battle == 3 then" statement did indeed execute. Now I'm just curious as to why this was the case... and how I can have multiple statements execute depending on what battle it is.

```
if turn == 1 and character_1.charge_gauge == 100 then
  booleans["assault_time"] = true
end
if booleans["assault_time"] == nil then
  --[[Command list for non-assault time (ATなし-)-]]
  if turn == 1 then
  
		if battle == 1 then
		
			DisableChargeAttack()
			
			characters["Siegfried"]:UseSkill(3)
			
		end
   
		if battle == 3 then
	
			EnableChargeAttack()
	
			character_1:UseSkill(2)
	
			characters["Siegfried"]:UseSkill(1)
		
			character_1:UseSkill(3)
			character_1:UseSkill(4)
	
			characters["Seofon"]:UseSkill(1)
			characters["Seofon"]:UseSkill(2)
	
			characters["Levi"]:UseSkill(2)
			characters["Levi"]:UseSkill(3)
		
			characters["Siegfried"]:UseSkill(2)
			
			Summon(1)
	
		end
		
  end
 
else
  --[[Command list for assault time (AT)--]]
  if turn == 1 then

  end
end
```

**Comment by Ohwhat00** [comment]
In battle events, you need to specifiy what "battle" turn you're on. You can't just have "turn" by itself like in raids. So for example:
```
if battle == 3 then
characters["Siegfried"]:UseSkill(1)
characters["Seofon"]:UseSkill(1)
characters["Seofon"]:UseSkill(2)
Summon(1)
end
```
The above characters  will keep using reusing those skills/resummon on cooldown in battle 3 until that battle turn ends or they die. 

If you want to be more specific on what a character will do per turn in that battle:
```
if battle == 3 and turn == 2 then
characters["Siegfried"]:UseSkill(3)
Summon(4)
end
```
So turn 2 in battle 3, siegfrield will use skill 3 and summon 4 will be used.

And so on:

```
if battle == 4 and turn == 3 and character_1.charge_gauge == 100 then
EnableChargeAttack()
characters["Levi"]:UseSkill(2)
end
```

**Comment by kujaras** [comment]
Thanks a lot, I changed my lua script to the following and it worked:

```
if battle == 1 and turn == 1 then
		
	DisableChargeAttack()
			
	characters["Siegfried"]:UseSkill(3)
			
end
   
if battle == 3 and turn == 1 then
	
	EnableChargeAttack()
	
	character_1:UseSkill(2)
	
	characters["Siegfried"]:UseSkill(1)
		
	character_1:UseSkill(3)
	character_1:UseSkill(4)
	
	characters["Seofon"]:UseSkill(1)
	characters["Seofon"]:UseSkill(2)
		
	characters["Levi"]:UseSkill(3)
		
	characters["Siegfried"]:UseSkill(2)
			
	Summon(1)
	
end
```
