### ISSUE TITLE
The bot stopped at the Main account quest page everytime

### ISSUE THREAD

**Issue by akira9311** [Masuzu/ZooeyBot#8]
Hello,
Please see the attached files.
Thanks

**Comment by Masuzu** [comment]
Hello,

Thanks for reporting this. As I can't reproduce the issue on my side for now, I will release today another version with more info.
By the way, you should remove your names, room ID and raid ID from your screenshot.

**Comment by Masuzu** [comment]
Slight update in version 1.1 https://poker-bot.azurewebsites.net/ZooeyBot/en/Home/PatchNotes adding some debug messages.
