### ISSUE TITLE
Suggestions for AH mode

### ISSUE THREAD

**Issue by whyiseveryusernamealreadytaken** [Masuzu/ZooeyBot#80]
Would it be possible to make the bot search in console for the dimensional halo boss ID - in order to find out whether or not it transforms, without having to bring it down to 50%? If the boss doesnt transform, the bot could simply retreat from the battle. 
Reference: https://www.reddit.com/r/Granblue_en/comments/6aiw9e/how_to_tell_if_angel_halo_nightmare_is_going_to/

IDS figured out so far:
No transform (retreat): 6005070
Uno:
Song: 2966050
Sarasa:
Quatre: 2968050
Funf:
Seox: 2970050 
Siete:
Okto:
Nio:
Esser: 2974050 

And another suggestion:
Have the bot switch parties when you are fighting regular AH and dimensional halo.
When farming manually, i use wiseman team with 2x bunny, for quicker clears because of wiseman's AoE attacks, as well as better drops from using bunny. For DH I usually use my dark team. So when DH appears, the bot would switch to my dark team, position specified in config, and when it's done, it switches back to the wiseman farm team.

**Comment by Masuzu** [comment]
Hi there,

Good points indeed. I will see what I can do: https://github.com/Masuzu/ZooeyBot/issues/83

**Comment by Masuzu** [comment]
The retreat feature when the Dimensional Halo boss won't transform is available in v1.7.1.
Experimental support for party selection has been added in v1.8.0.
Please let me know if you run into issues.

**Comment by whyiseveryusernamealreadytaken** [comment]
Ive tried it out for 2 3 hour sessions, no problems so far. The only thing is that when captcha appears and the sound notification is going on, the bot keeps refreshing the page, which i think is unrelated to these two particular functions though.

**Comment by Masuzu** [comment]
Thank you for the feedback.
It is unrelated to these two functions indeed. As long as you do not manually stop the bot (by pressing F1 by default) and that the sound notification is going on, the bot will keep refreshing the page indeed.
