### ISSUE TITLE
xeno summon screen "not ok"

### ISSUE THREAD

**Issue by daisuke031** [Masuzu/ZooeyBot#800]
![image](https://user-images.githubusercontent.com/39315856/40098412-b31b09f2-58b1-11e8-98a1-b4704a634c8f.png)

the bot works 100% on any other quest, and was working just fine on the last event, I did no changes outside inputing the new xeno ex link, to which the bot will proceed to the summon page, pick the summon, and start looping not scrolling down to click on the "OK" buttom. you guys got any ideas on how to fix this?
ps: already changed the response time, fresh .INI files with just the link and different versions of chrome.

**Comment by Masuzu** [comment]
Hello,
It loosk like you have a small screen resolution such as 1024*768.
You can use the Chrome full screen mode to avoid having to have the OK button on the party selection page hidden, even that screen resolution.
