### ISSUE TITLE
Zoeey initialize problem?

### ISSUE THREAD

**Issue by xiang-guo** [Masuzu/ZooeyBot#807]
After open Zooey, it stuck at this point, It was working properly last night. 

![image](https://user-images.githubusercontent.com/9344555/40232677-c25e7274-5a6d-11e8-8dcd-4394fabdb88e.png)

Any idea ? Thanks.

**Comment by Ramkm77** [comment]
had same issue before . try to connect to vpn and check if its works. mostly blocked from internet provider

**Comment by Masuzu** [comment]
Hello,
This is a good advice indeed. I can't do anything about country wide firewall issues such as enforced in China.
