### ISSUE TITLE
Delay in pressing "Next" button during Angel Halo farming.

### ISSUE THREAD

**Issue by GBF99** [Masuzu/ZooeyBot#810]
There is a huge delay (more than 3 seconds) on the bot pressing the next button after all enemy are dead. is there a way to change the setting?

**Comment by GBF99** [comment]
P.S. i am using the default script and the team only need one turn to kill all three Angel Core

**Comment by tomatoman514** [comment]
Set EnableEarlyTurnStartWithViramate to false.
I also had same problem.
