### ISSUE TITLE
Summon select stuck

### ISSUE THREAD

**Issue by yuzurihaz** [Masuzu/ZooeyBot#812]
![sssssssssssssssssssssss](https://user-images.githubusercontent.com/35253544/40282202-ee16fc54-5c95-11e8-8aef-63d0e49f3170.jpg)

how to fix

**Comment by Masuzu** [comment]
You are probably using a non compatible Chrome version (the last version as of now of the official Chrome build works) or the mouse cursor is not located inside the summon window.

**Comment by yuzurihaz** [comment]
how to fix it it  im using  chrome v. 66.0.3359.181 (Official Build) (64-bit)

**Comment by Masuzu** [comment]
This is simply not supposed to happen and the fix should already have provided in a past version of Zooey Bot.
Where is located your mouse cursor when this happens? If you did not move it, the mouse cursor should be located somewhere on the summon list. Your specific issue is that scrolling down to have the summon appear in the main window fails as the mouse cursor is probably somewhere else.

**Comment by yuzurihaz** [comment]
i have install new windows after that i got this problem
