### ISSUE TITLE
Is it possible to check in combat .lua script if you are on the last battle stage?

### ISSUE THREAD

**Issue by xeratzy** [Masuzu/ZooeyBot#814]
Assuming I have a very polished .lua combat script that i generic want to use for everything.

Would it be possible to check for last battle in .lua? would be useful for applying TH or turn on charge attack on last stages only.

Something like:

```
If "last stage" == true then
  stuff
end
```

is it possible?

**Comment by Masuzu** [comment]
Simply use if battle ==

**Comment by xeratzy** [comment]
I know that the battle turn exist, it's not what I'm after unless it can be used differently.

For example if I raid schedule a battle with 3 battle stages and another one with 1 stage ; can I by using "battle"  detect the last stage using the same script?
