### ISSUE TITLE
*Warning* Do not leave ZooeyBot unattended.

### ISSUE THREAD

**Issue by Hexadecimalism** [Masuzu/ZooeyBot#818]
Despite audio warnings for both kinds of automation checks and my responding to them within seconds, I still got hit with a 4 hour suspension for automation. If there's a new detection method, I missed it. Basically don't leave the room or go to sleep. Use it as a support tool while doing other things by your computer.

**Comment by thenastyworm** [comment]
That should honestly be common sense. 

That said - I got hit with both validation methods on the summon select page and the classic capcha and Zooey caught them both just fine.

Is it possible that you took to long to respond or something similar?

**Comment by Hexadecimalism** [comment]
Doubtful as I have my speakers on max volume and the entire house pretty much blasts the alert. I was in the next room over. I have no clue what happened exactly, but yeah common sense is necessary. Even the most competent among us make stupid mistakes.

**Comment by acgfreshman** [comment]
Same 4 hour suspension here. I found the suspension was during the battle without any captcha.
I am using viramate shortcuts for farming, maybe that is the reason

**Comment by GBFThrowaway** [comment]
Same thing over here, except mine doesn't have a suspension timer.

**Comment by Hexadecimalism** [comment]
@acgfreshman Now that you mention it, I was in the middle battle, and I do use viramate shortcuts.

**Comment by Ohwhat00** [comment]
What do viramate shortcuts do? Are you able to  bypass the summon selection page with them?
Since GW started, I have had the classic captcha prompt 6 times (3 of those woke me up when I was sleeping) and the new validation method 2 times. Haven't received any suspensions.

**Comment by utenshien** [comment]
i'm using viramate shortcuts too but haven't received any suspension
i want to know if you guys enabled viramate's favorite summon tab?

**Comment by Hexadecimalism** [comment]
@Ohwhat00 
shortcuts allow you to use your keyboard for battle by assigning 1-4 for character selection and QWER for skill selection.
@utenshien 
I don't have favorite summons enabled. From what I understand though, that should not matter since the bot check shows up on the favorite tab too.

**Comment by MegaBlues** [comment]
IIRC, it's somewhat common knowledge that using Viramate shortcuts is dangerous. It might be alright normally, but during Guild Wars when extra measures to stop cheating seem to be put in place, I wouldn't use them.

I've left a captcha up for Pokerbot for a few hours before and nothing came of it, if that means anything.

**Comment by salvanost** [comment]
I got no problem with the bot
Got captcha 4 times
And each time i’m failed 3 times to enter the ride captcha

**Comment by salvanost** [comment]
Update today i leaving my bot for 3-4 hours
And yes i got suspend for too
They use capcha after 2 hours bot

**Comment by salvanost** [comment]
It’s a new detection i think through captcha

**Comment by Masuzu** [comment]
It goes without saying that you have to complete the captcha as soon as possible, and avoid failing it too many times in a row... 
The sound alarm is there for this. You can change the sound file to use as well if you find it not conspicuous enough.
