### ISSUE TITLE
"Retreat from Battle" Error

### ISSUE THREAD

**Issue by ErogeSeiyuu** [Masuzu/ZooeyBot#819]
Occasionally, zoibot would be unable to retreat from trial battle. Normally, the process goes like this for rerolling summons:

1. Zoi goes to trial summon select when it can't find the right summon
2. It selects a summon, enter battle, then go to game.gbf.jp/quest to retreat.
3. A first window pops up asking to "Retreat or Resume". Zoi clicks on Retreat (it never fails this step)
4. A second window appears, showing the "progress of the battle" asking "if you retreat xyz will be lost" and below it is "Cancel or Retreat". 

On step 4, zoibot would occasionally unable to "find" the retreat button and move the cursor on a straight line to the right side, clicking on nothing. Instead, it should have move the cursor diagonally to the lower right side to click on retreat. This issue never happened to me before v2.12.9.

**Comment by Masuzu** [comment]
Hello,
I see, thank you for reporting this. It is sadly caused by how slowly you load pages and menus. I will see what can be done about this.
