### ISSUE TITLE
Request: Option to allow party switching

### ISSUE THREAD

**Issue by XenoeJin** [Masuzu/ZooeyBot#82]
Right now, the bot simply uses whatever party is currently selected.
Would be nice if there's an option to allow party switching, very often, NMs might use a different party than non NMs

**Comment by Masuzu** [comment]
Hi there,

Good point indeed. I will see what I can do: https://github.com/Masuzu/ZooeyBot/issues/83

**Comment by Masuzu** [comment]
Experimental support for such a feature has been added in v1.8.0.
Please let me know if you run into issues.
