### ISSUE TITLE
Do we have a function can refresh the page manually?

### ISSUE THREAD

**Issue by xiang-guo** [Masuzu/ZooeyBot#820]
when character get slept, I used Clarity to remove the debuff, but I still can not use the skills until I refresh the game, So do we have a function can refresh the page manually?

**Comment by ngocin** [comment]
Im in the same situation as you 
To prevent this, i set if MC get asleep effect then use gw herd to clar then call a sum then use MC's clar

**Comment by xeratzy** [comment]
doesn't the 
`Refresh()`
work?

**Comment by xiang-guo** [comment]
Thanks for the reply, The problem is when I trying to use skill from the character who just get clarity, it will pop out "this character is debuffed and can not use skill",  So I have to refresh the game to use the skill.

**Comment by xiang-guo** [comment]
Thanks for helping. Using summon after that does solve the problem.
