### ISSUE TITLE
re: Is it possible to check in combat .lua script if you are on the last battle stage

### ISSUE THREAD

**Issue by xerance** [Masuzu/ZooeyBot#821]
re: https://github.com/Masuzu/ZooeyBot/issues/814

still not solved. 

What I'm asking for is a way to detect the last battle stage without presetting it to a specific number in the combat.lua

an an example:

```
if battle == 3 then
 stuff
```
this works well and good except assuming I queue(raid scheduling) up 2 or more different quests with different numbers of "waves".
for example "Playing Cat and Mouse" with 2 "waves of battle" paired with "Antiquarian Troubles" with 5 "waves".

What I'm asking is if there is a condition to ask if you are on the last stage? as zooeybot already seems to be able to do this as it can read battle (1/3) and so on when it runs.

as an example
```
if battle == last_stage then
 stuff
```

This would be quite handy if you create a fairly well polished battle.lua instead of making multiple copies for specific quests and use the customized raid scheduling function "SetLuaScript("Scripts/XXXX.lua")" or for just generic usage to clean up the combat.lua folder.

Hope I was more clear in explaining what I'm asking. Made a new post as I'm not sure how github treats closed issues? Sorry for any inconvenience.

**Comment by ErogeSeiyuu** [comment]
just SetLuaScript() for each individual raids and make a different scripts for each. There's no "last_stage" check right now.

**Comment by xerance** [comment]
Yah, as I wrote thats what I'm using atm, was simply asking if there was such a function as it would make the script folder more organized and you could potentially use the same script for multiple different quests/raids with various number of "waves".

**Comment by Masuzu** [comment]
Oh that, I get the use case.
