### ISSUE TITLE
Slave doesn't detect "combat end" causing refresh loop

### ISSUE THREAD

**Issue by falassiry** [Masuzu/ZooeyBot#824]
I've been having an issue where slave mode works, but wastes a huge amount of time refreshing the slave window using the fallback procedure right after both windows return to the coop room.

I'm using the default swordmaster script along with do_nothing for the slave window, and have tried all the different variations of setups as follows:

- Confirmed working version of Chrome and Incognito window
- ‎Confirmed working version of Chromium and Incognito window
- ‎Combination of Chrome and Chromium windows without incognito mode
- ‎ Using viramate with shortcuts enabled, disabled, and without viramate, all while setting the viramate setting correctly in ini
- ‎ Starting with main or slave account
- ‎ Default delays or increased delays up to ten seconds each for testing. All exhibit the same behavior.

I can confirm that I am following the initialization process to the T, and the slave window shows the correct response as per the prompt. However too much time is wasted while going through these unnecessary refresh loops.

I have been able to identify that Zooeybot can identify that the battle has ended right after using swordmaster, however the "combat ended" notification only appears after the refresh loop is over, which seems to indicate it is somehow failing to detect the end of the fight in slave window, causing the unnecessary refresh loop.

Appreciate if you can help me figure out how to sort this issue as I am running out of threads to pull.

Thanks.

**Comment by Masuzu** [comment]
Hello,
I sometimes had this issue due to a fluctuating ping.
What I did to reduce the occurrences of this situation was to increase the delay `MinWaitTimeInMsAfterAbility`.

**Comment by falassiry** [comment]
Thanks for the suggestion, will try it out and report back if it helps. For me it is consistent and I can't avoid this happening at all - basically makes sliming for half elixirs not worth the resources with such a slow turnaround.

**Comment by Masuzu** [comment]
You might want to consider using VPNs if it can help (like mudfish or the likes for instance).
