### ISSUE TITLE
Has anyone else seen a suspension like this?

### ISSUE THREAD

**Issue by GBFThrowaway** [Masuzu/ZooeyBot#825]
It originally started in prelims but is still going.

![image](https://user-images.githubusercontent.com/30182019/40792550-38efd20c-64c8-11e8-994d-083c88370eb0.png)

**Comment by IZEROII** [comment]
Just remember that it is an inherent risk when using a bot.

I had a 24 hour temp ban that was lifted as I was one of the (I'm sure) large group of people who were hit with suspected activity notifications this past GW.  

I don't know if you use Viramate or do anything else that bends the rules or adds QoL to the game.  You'll have to figure out the means of contacting the powers that be oversees to figure out the status of your account. I'm sure Reddit has threads on this.

**Comment by Masuzu** [comment]
All I can say is that none of the bot checks were responsible for that during the past GW unless you were sleeping when the alert was triggered.
I hope that you get your situation sorted out.
