### ISSUE TITLE
Slime bot with slower wifi

### ISSUE THREAD

**Issue by moonlee7777** [Masuzu/ZooeyBot#826]
My wifi isnt slow, but it's slow enough that there's a second or so stutter between the slave client starting the coop room and the main client joining. This creates a disparity in load time, which causes the slave account to refresh a few times until the main acc loads, and even when it loads. Is there anything I can do to stop it from refreshing?

**Comment by moonlee7777** [comment]
Also, if it doesnt bother you, may I see the settings you used for slime blasting?

**Comment by Masuzu** [comment]
Hello,
Ah about that, you can increase the value of the configuration parameter `MaxTriggerDelayInMsBeforeFallback`.
I used these settings in the past, with a stable 175-190 ms ping:
```
[Combat]
# Zooey-bot will wait at least the given number of milliseconds after using a skill
MinWaitTimeInMsAfterAbility=450
# Maximum wait time in milliseconds to load the character selection menu when an ability targetting a party member is used.
MaxWaitTimeToLoadCharacterSelectionMenuInMs=1100
EnableEarlyTurnStartWithViramate=true
# This parameter is only taken into account when UseViramate and EnableEarlyTurnStartWithViramate are set to true, which makes it possible to cast skills or use summons before the raid stage is fully loaded. It configures how long to wait before taking any action, from the moment Zooey deemed it possible to start casting skills or using summons.
MinWaitTimeBeforeActionAfterEarlyTurnStartInMs=1300
```
(I use Threo so the only parameters which matter are the one listed above).
