### ISSUE TITLE
Slavemode problem

### ISSUE THREAD

**Issue by Kizuchi** [Masuzu/ZooeyBot#827]
Zooeybot is only able to initialize one account, doesnt matter which order i press it, it is only able to initialise the 1st account that i click start on the chrome extension

**Comment by Masuzu** [comment]
Hello,
Every step and _every_ details count, as described step by step on the [guidelines](https://github.com/Masuzu/ZooeyBot/wiki/Slave-mode-(slime-basting)) page.
