### ISSUE TITLE
zooeybot stuck at "Press OK" after side scrolling pops up

### ISSUE THREAD

**Issue by magicfindsheep** [Masuzu/ZooeyBot#829]
Hello, I'm having issue after my side scrolling pop up the "OK" pop up. Zooeybot is stuck.

Will like to know why is it so. Please help. Thanks!

**Comment by snowedrunner** [comment]
I think we're having the same problem. Once a free quest is started, zooey will make it to the "OK" pop up and stop there. Nothing shows in the console as an error, nor do I believe it to be my ping. If I manually click the "OK", zooey proceeds as normal until it gets back to the "OK" on the nxt run. I've tried looking up any previous similar issues and nothing seems to work as I've also made sure Viramate's auto close of pop-ups is disabled, I've messed w/ my delay for the fallback policy w/ no luck, and all my other required game settings for zooey are correct. I only am having issues w/ free/story quests, so it maybe just something there. Any help would be appreciated.

**Comment by IZEROII** [comment]
It's definitely a newly introduced bug that needs addressing. Same problem here.

**Comment by Masuzu** [comment]
Hello,
It is not a bug. Please refer to https://github.com/Masuzu/ZooeyBot/wiki/FAQ#zooey-is-stuck-on-the-side-scrolling-scene

**Comment by Masuzu** [comment]
Hello,
Ah it must have been caused by a change in the game with one of the recent updates. I will check it.

**Comment by Masuzu** [comment]
Addressed in v2.12.11.

**Comment by magicfindsheep** [comment]
thanks!
