### ISSUE TITLE
free quest stuck

### ISSUE THREAD

**Issue by yuzurihaz** [Masuzu/ZooeyBot#831]
i dont use viramate but i stuck on this screen how to fix halo quest or other it's work but not with free quest with item screen 
![45453](https://user-images.githubusercontent.com/35253544/40898562-6bf04bec-67ec-11e8-91a3-756897949b77.jpg)

**Comment by rockysilver** [comment]
Same problem here, the bot no longer dismissing the pop up.

**Comment by IZEROII** [comment]
Ya can confirm this issue as well.  Major issue

**Comment by Masuzu** [comment]
Hello,
It is not a bug. Please refer to https://github.com/Masuzu/ZooeyBot/wiki/FAQ#zooey-is-stuck-on-the-side-scrolling-scene
