### ISSUE TITLE
party_selection.lua help 

### ISSUE THREAD

**Issue by ModelGTX** [Masuzu/ZooeyBot#832]
Hello, I stopped playing the game for a while and I am back to use Zooey.

I am trying to write a party_selection.lua script where if a certain summon is selected it will direct me to a certain party.

Here is what I've got:

if selected_summon == Colossus_Omega,Shiva then
SetPreferredPartyGroup(1)
SetPreferredPartyDeck(2)
end
if selected_summon == Leviathan_Omega,Europa then
SetPreferredPartyGroup(3)
SetPreferredPartyDeck(2)
end
if selected_summon == Yggdrasil_Omega then
SetPreferredPartyGroup(6)
SetPreferredPartyDeck(2)
end
if selected_summon == Tiamat_Omega,Grimnir then
SetPreferredPartyGroup(5)
SetPreferredPartyDeck(2)
end
if selected_summon == Celeste_Omega,Bahamut then
SetPreferredPartyGroup(4)
SetPreferredPartyDeck(2)
end
if selected_summon == Luminiera_Omega,Lucifer then
SetPreferredPartyGroup(2)
SetPreferredPartyDeck(2)
end

The script seems to be running into error messages if it detects multiple summons written up there with a comma in between (for example, colossus omega and shiva). 

So if i remove it and make it into a single summon (for example, if selected_summon == Colossus Omega_1) then I no longer runs into any issues with Zooey. However this script does not select the actual preferred party. Any one able to point out what I've did wrong? and how I can improve this?

Thanks

**Comment by Masuzu** [comment]
Hello,
You have to use the names as displayed in the summon list menu:
selected_summon == "Colossus Omega" or selected_summon == ... and so on.
Converting the strings to lower case in the script (Lua offers such helper functions already) could avoid facing potential issues as well for english language settings.
