### ISSUE TITLE
No active granblue fantasy was found 

### ISSUE THREAD

**Issue by ShadowRyze** [Masuzu/ZooeyBot#833]
so I have this issues knowing that I tried everything possible 
![image](https://user-images.githubusercontent.com/39913136/40921508-aae782a0-6820-11e8-9ab9-ce5135c18a0b.png)

**Comment by Masuzu** [comment]
Hello,
Your Chrome browser is not detected as seen in the list of programs in the console.
You are advised to use the last version of the official Chrome distribution, which has no issue, instead of other distributions such as Chromium.
