### ISSUE TITLE
Sword master s1 bug ?

### ISSUE THREAD

**Issue by einzwarthz** [Masuzu/ZooeyBot#836]
when ever i do s1 for sword master / glory using disparia or any other sword it will just keep using the s1 non stop until for 5 - 7 sec and count the turn then proceed to the next line do you know how to fix this ?

**Comment by Masuzu** [comment]
Hello,
The turn count keeps increasing even though no attack is performed.
I plan to address this week-end.

**Comment by einzwarthz** [comment]
When will you release the patch for the bugs ? it's 2 month already w/o updates

**Comment by Masuzu** [comment]
This is now addressed in v2.14
https://gbtools.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-14-0
