### ISSUE TITLE
Zooey stops recognizing current AP

### ISSUE THREAD

**Issue by Felessan2** [Masuzu/ZooeyBot#837]
After update bot stop refreshing ap when it's too low for current quest

**Comment by Masuzu** [comment]
Hello,
Which quest are you trying to do?
Thank you for reporting this, I will look into it.

**Comment by Masuzu** [comment]
I tested it and:
- for the Shiny Slime (http://game.granbluefantasy.jp/#quest/supporter/400151/4), with the default mode, the quest AP is picked up properly
- for the elemental trial (http://game.granbluefantasy.jp/#quest/supporter/599861/5 today), same thing with the default mode
