### ISSUE TITLE
i am trying to make it so that the script does not fail if a character dies :)

### ISSUE THREAD

**Issue by dabudauu** [Masuzu/ZooeyBot#841]
i copied and pasted one of your scripts and edited in my characters - (THANK YOU SO MUCH!)
but if one of the characters dies the script turns off completely. what do i do? i'm using this for xeno ifrit by the way :)

--[[Constants]]
DoubleAttackBuff = "1004"

--[[Helper functions]]
function NumCharactersBelowHPPercentage(percentage)
  local sum = 0
  for name,character in pairs(characters) do
    if character.hp_percentage <= percentage then
      sum = sum + 1
    end
  end
  return sum
end

--[[Assumes no charge bar slowed]]
function MaxChainBurst()
  local sum = 0
  if character_1.charge_gauge == 100 and
     character_2.charge_gauge >= 90 and
	 character_3.charge_gauge >= 80 and
	 character_4.charge_gauge >= 70 then
    return 4
  end
  if (character_1.charge_gauge == 100 and
     character_2.charge_gauge >= 90 and
	 (character_3.charge_gauge >= 80 or character_4.charge_gauge >= 80)) or
	 (character_1.charge_gauge == 100 and
     character_3.charge_gauge >= 90 and
	 character_4.charge_gauge >= 80) or
	 (character_2.charge_gauge == 100 and
     character_3.charge_gauge >= 90 and
	 character_4.charge_gauge >= 80) then
    return 3
  end
  if (character_1.charge_gauge == 100 and
     (character_2.charge_gauge >= 90 or character_3.charge_gauge >= 90 or character_4.charge_gauge >= 90)) or
	 (character_2.charge_gauge == 100 and
     (character_3.charge_gauge >= 90 or character_4.charge_gauge >= 90)) or
	 (character_3.charge_gauge == 100 and character_4.charge_gauge >= 90) then
    return 2
  end 
  if character_1.charge_gauge == 100 or
     character_2.charge_gauge == 90 or
	 character_3.charge_gauge == 80 or
	 character_4.charge_gauge == 70 then
    return 1
  end 
  return 0
end

if not booleans["Once"] and enemy_1.hp_percentage > 30 and NumCharactersBelowHPPercentage(70) >= 2 then
  UseSupportPotion()
  booleans["Once"] = true
end
characters["Altair"]:UseSkill(1)
if MaxChainBurst() <= 2 then
  characters["Altair"]:UseSkill(3)
end

--[[Cast water SR buncle every 4 turns]]
if turn >= 6 and (turn - 6) % 4 == 0 then
  Summon(4)
  Summon(5)
end

if turn >= 14 then
  --[[Refresh debuffs]]
  characters["Altair"]:UseSkill(2)
  character_1:UseSkill(4)
  character_1:UseSkill(2)
end

if turn == 1 then
  EnableChargeAttack()
  --[[Cast defence down debuffs]]
  characters["Altair"]:UseSkill(2)
  if turn == 1 then
  character_1:UseSkill(4)
  --[[Cast Rain of Arrows]]
  character_1:UseSkill(2)
  characters["Diantha"]:UseSkill(1)
  
   if turn == 1 then
  characters["Silva"]:UseSkill(2)
  characters["Silva"]:UseSkill(1)
end
if turn == 2 then
  characters["Diantha"]:UseSkill(2)
end
characters["Diantha"]:UseSkill(1)
if not(character_1.charge_gauge == 100 and characters["Silva"].charge_gauge >= 90 or
       characters["Silva"].charge_gauge == 100) then
  characters["Silva"]:UseSkill(2)
  characters["Silva"]:UseSkill(1)
end

if enemy_1.hp_percentage < 79 and enemy_1.hp_percentage > 75 then
  --[[Cast phalanx]]
  character_1:UseSkill(1)
end

if enemy_1.hp_percentage < 44.5 and enemy_1.hp_percentage > 50 then
  if characters["Silva"].skill_3_available then
    characters["Silva"]:UseSkill(3)
  else
    --[[In case we did not deal enough damage, cast phalanx]]
    character_1:UseSkill(1)
  end
end
if enemy_1.hp_percentage < 30 and enemy_1.hp_percentage > 25 then
  if characters["Silva"].skill_3_available then
    characters["Silva"]:UseSkill(3)
  else
    --[[In case we did not deal enough damage, cast phalanx]]
    character_1:UseSkill(1)
  end
end

if enemy_1.hp_percentage < 25 then
  if not booleans["Used support potion"] then
    UseSupportPotion()
	booleans["Used support potion"] = true
  end
  --[[Activate Uno's god mode]]
  characters["Diantha"]:UseSkill(3)
  if character_2:HasStatusEffect(DoubleAttackBuff) and not booleans["Leviathan Omega1"] then
	Summon(2)
	DisableChargeAttack()
	booleans["Leviathan Omega1"] = true
  end
  if character_2:HasStatusEffect(DoubleAttackBuff) and not booleans["Leviathan Omega2"] then
	Summon(3)
	DisableChargeAttack()
	booleans["Leviathan Omega2"] = true
  end
end

**Comment by salvanost** [comment]
Change silva altair into character position?

**Comment by Masuzu** [comment]
Hello,
Before using a skill, you must make sure that the character is present, which can be done as follows:
```
if characters["<character_name>"] ~= nil then
 --[[<character_name> is still alive so let's use one of his or her skills]]
 characters["<character_name>"]:UseSkill(1)
end
```
Otherwise you will run into the kind of errors you mentioned.

**Comment by dabudauu** [comment]
thank you so much :) <3

**Comment by dabudauu** [comment]
can you edit the script i pasted to make it that way though because i dont
know how to because im not smart like you
