### ISSUE TITLE
Licence Error

### ISSUE THREAD

**Issue by MeGamacumai** [Masuzu/ZooeyBot#842]
Error can not be resolved. Please teach me in Japanese
![error](https://user-images.githubusercontent.com/40167369/41226546-bff7ca24-6dac-11e8-8a17-e4df5f52bd2e.jpg)

**Comment by Masuzu** [comment]
Hello,
This is covered extensively by the FAQ https://github.com/Masuzu/ZooeyBot/wiki/FAQ#i-get-an-unregistered-user-error-message
