### ISSUE TITLE
Bot Stuck on choosing summon

### ISSUE THREAD

**Issue by filipi159951** [Masuzu/ZooeyBot#843]
Hello, i'm here 'cause some times when it's working the bot, it try to choose the summon, but then it clicks on the Summon Host and goes to it profile, them it try again, and finally it stops... what should i do to prevent it?

-i'm not on home right now, when i came i'll post my bot setup.

**Comment by Masuzu** [comment]
Hello,
Please disable this Viramate option which hides some of the summon information:
![image](https://user-images.githubusercontent.com/5464705/41243833-947c00c6-6da3-11e8-9a49-931a336936f8.png)
