### ISSUE TITLE
Slave window problem

### ISSUE THREAD

**Issue by xiang-guo** [Masuzu/ZooeyBot#846]
When I using Salve mode to do co-op battle, Here's couple wired things happening. 
First, when I using same command in both main account script and salve account script, main account works fine, but slave account give me error. 
The command is "  SelectTarget(3)"
![image](https://user-images.githubusercontent.com/9344555/41383591-13fb06ec-6fa4-11e8-9fc7-ca74e26f67bf.png)
So I have to delete the command in salve's script (main's script still have that)

Second thing is that, when leave the script blank and doing salve mode, main account works fine and salve mode and salve account can not click the attack button.
It works fine until I let salve account use a skill first then attack. 

Would you please take a look? Thanks for the help.

**Comment by Masuzu** [comment]
Hello,
There was an issue when the main account performed an action first which was addressed in today's patch, but I am not sure if it solved your specific case.
Target selection works fine in coop the last time I tried.
