### ISSUE TITLE
New Zooey Bot user

### ISSUE THREAD

**Issue by magicfindsheep** [Masuzu/ZooeyBot#849]
Hello, I have been using the basic farming mode.

I would want to use it for the new persona 5 collab or future collaboration works.

I tried using zooey to do some lua scripts but she doesn't even register the lua script and proceed to normal behavior only (pressing the attack button etc).

How do i go about programming her to use skills at specific battles?

Please help. I've read the tutorials but i do not understand them

**Comment by einzwarthz** [comment]
did you make sure the extension is .lua ? and the encoding is in UTF-8 ?

**Comment by magicfindsheep** [comment]
yep. i definitely did. may I ask which part of the script for zooey.ini do i put the commands under?

**Comment by einzwarthz** [comment]
on event mode there's EventRaidScript right you need to place it there
ex: EventRaidScript=Scripts/EXRaid.lua

something like that and also if you want to do the nightmare scrip there's also NightmareModeScript

**Comment by Masuzu** [comment]
What @einzwarthz said.
All the tutorials and other resources can also be found here
https://github.com/Masuzu/ZooeyBot/wiki
