### ISSUE TITLE
Is there a retreat function for Nightmare mode?

### ISSUE THREAD

**Issue by GBFUSER1993** [Masuzu/ZooeyBot#850]
As the title said
Sometimes the battle against Nightmare will be disappointed
So it may take a few tries for a player to win against a specific nightmare mode
however, Zooey bot doesn't seems to have this kind of function
IF you lose a nightmare battle, the screen will just stuck on the specific page, rather than retreat and do it again

So did anybody knows if there was a retreat and do it again function for Zooey bot event mode?

**Comment by salvanost** [comment]
Use mechanic 
U got 1 chance to spam charge attack
Should be no problem when using it with nm lvl 60

**Comment by Masuzu** [comment]
Hello,
There is not and I do not plan to have such a feature. Your party is supposed to be strong enough to clear it. You can skip going into the Nightmare mode by letting the URL of the Nightmare mode blank.
