### ISSUE TITLE
Zooeybot running significantly slower for multi-stage battles　 help wanted 

### ISSUE THREAD

**Issue by gary173** [Masuzu/ZooeyBot#851]
I've been notice Zooeybot running significantly slower for multi-stage battles, it would sometimes take 10 seconds before Zooeybot registers that a turn has ended and move on to the next stage. Attack Animations are also more clunkier and laggier during the fight on battles 1 and 2.

Not sure if anything has changed, I've only noticed this behavior about a few weeks ago.

can anybody help me ?

**Comment by sudonim7** [comment]
I believe this is only happening on events found in the Special Quests tab (trials, rotating showdowns, angel halo, shiny slime search, etc.). The multi-stage battles from the Persona Events are also experience some serious slowdown.

I did not notice this slowdown at all during Xeno Ifrit, which has its multi-stage battles on its own page.

**Comment by Miyoumu** [comment]
Same issue. Bot is practically unusable right now.

**Comment by Masuzu** [comment]
Hello,
This has already been reported in the past and was caused by the activation of the parameter EnableEarlyCombatStart. This should be set to false.
