### ISSUE TITLE
Zooeybot unregistered user even though I'm subscribed

### ISSUE THREAD

**Issue by Santheron** [Masuzu/ZooeyBot#853]
![image](https://user-images.githubusercontent.com/40581698/41877890-2fbeedf4-7890-11e8-997c-4d37d5924165.png)

even though...

![image](https://user-images.githubusercontent.com/40581698/41878094-f1dd138e-7890-11e8-9752-56882c11081e.png)

Every time I change the serial number to the number in my manage account
![image](https://user-images.githubusercontent.com/40581698/41878160-343738e0-7891-11e8-9090-510d2b8f3a64.png)

Then I launch Zooey bot and it still says
![image](https://user-images.githubusercontent.com/40581698/41878184-4c32d4a4-7891-11e8-8ede-2ffd3e6562e3.png)

and when I go back to serial_number.txt the number has completely changed.

**Comment by ErogeSeiyuu** [comment]
I got this issue recently after updating win 10 home to the newest version, but I found a fix (not sure if temporarily or not, will update if something new happens).

There was a weird mismatch between:
1. The serial code generator's serial code (starts with fd9) which was and still is the same serial code on the gbtools website's Manage Account page.
2. The automatically generated serial_number.txt's serial code (starts with aa3) that zooeybot.exe produces.

So to fix it, I copied the automatically generated serial_number.txt to update the serial code on gbtools, and it's now fixed. I still get the "Fail to initialize security Error code 0x80010119" when starting, but at least the bot still runs.
