### ISSUE TITLE
Laptop issue

### ISSUE THREAD

**Issue by corncookie** [Masuzu/ZooeyBot#858]
it seems my laptops resolution which is 1366x768 - only works with fullscreen with 75% scalling - but if it selecting a summon it will went haywire . help?

**Comment by Masuzu** [comment]
Hello,
You should in this case use Chrome in fullscreen mode, which should be just enough to have the party selection button visible.

**Comment by corncookie** [comment]
ok that fullscreen thing works thank god - now new problem occurs - it will scroll 1 time only andl it will click the buttom in my screen. after scrolling onetime and didnt manage to find the corresponding summon that the bot wants it will click to the button immediately then goes haywire again refreshing non stop.

**Comment by corncookie** [comment]
for now - gonna try to fix this on my own - well let u know if i manage to fix this thanks 0/

**Comment by corncookie** [comment]
finally - i solved it by removing the bottom buttons - thanks

**Comment by corncookie** [comment]
everything turn back to normal now

**Comment by Masuzu** [comment]
All good then!
