### ISSUE TITLE
error on waitwithtime lua script

### ISSUE THREAD

**Issue by salvanost** [Masuzu/ZooeyBot#859]
![untitled](https://user-images.githubusercontent.com/32562379/42763770-31159e50-893e-11e8-8ab3-cfa688011053.jpg)

already change the waitwithtime location but still error
usefor skill 2 wind jeanne

**Comment by salvanost** [comment]
Dunno why the OnPartyMember(4):UseSkill2 got no default min wait time

So if the skill lagged or stop responding, the bot won’t redo the skills like other skill
So i tried to use withwaittime command to force the bit redo the skill if lagged / no response from the game

**Comment by Masuzu** [comment]
Hello,
The valid syntax for now is character_2:OnPartyMember(4):WithWaitTime(XXX):UseSkill(XX)

**Comment by Masuzu** [comment]
It will be addressed before the start of the first round for NM 90 2 turn kills gimmicks with Shiva, Lecia and Arriet.

**Comment by Masuzu** [comment]
This is now addressed in v2.14.1
https://gbtools.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#2-14-1
