### ISSUE TITLE
stop at calibrating

### ISSUE THREAD

**Issue by Akifuma** [Masuzu/ZooeyBot#860]
same issues in any ver. of  zooey bot (2.14.0,2.13.0)

test in Chromium 
Version 66.0.3343.0 (Developer Build) (64-bit)
Version 67.0.3379.0 (Developer Build) (64-bit) <<< away use this 
Version 69.0.3494.0 (Developer Build) (64-bit)

![2018-07-17_084648](https://user-images.githubusercontent.com/31799116/42792141-30674be2-899e-11e8-92c4-41b82f8967b5.jpg)

It used fine in
Version 67.0.3379.0 with V2.14.0 ,V2.13.0 bot 
last used around 1am(jst)

i suggest maybe 4am(jst) game patch make it stuck

**Comment by salvanost** [comment]
Use old version of the bot to confirm is it the bot issue or connection issue
Don’t replace old cersion with new one

**Comment by fumika779** [comment]
I use 2.13.0 to test that early (same issue) 
also this night I will test with the older ver.
(2.14.0 run perfectly before 1 am jst )


I suggest my resolution may the issue. I will test that too

**Comment by Masuzu** [comment]
The last version works just like the previous ones for the calibration. Most likely it's a resolution/zoom issue on your side.

**Comment by happydanial** [comment]
hi. I am having this issue as well. Caliberating either takes too long or it doesnt run at all. And even if it runs, my mouse is moving in a weird direction (either top or bottom only) and all i get is just im using standard settings. can i know what might have caused these?
