### ISSUE TITLE
Siete buff counts

### ISSUE THREAD

**Issue by Nassy1121** [Masuzu/ZooeyBot#862]
Can anyone share status effect ID of siete ability 1?
Because I tried listen mode and confirmed "status_effects" but I couldn't find like that.

**Comment by Masuzu** [comment]
Hello,
The feature works fine, you can just active the Listener mode and head to a trial battle with Siete while casting his sword shine buff each turn. It'll display in the console the buff ID.

**Comment by Nassy1121** [comment]
@Masuzu 
Thanks for your information.
As a result, I needed to show status list of siete.
So buff ID was shown on console window.

Thanks
