### ISSUE TITLE
ZooeyBot on 1360x1080 monitor

### ISSUE THREAD

**Issue by SilvaFang** [Masuzu/ZooeyBot#866]
if i were to scale the game to the requirement, zooey cannot reach the start quest button as the screen is too big, is there any way to use zooey without a 1980x1080 monitor. i bought this and i feel really sad that ii cant use it

**Comment by Masuzu** [comment]
Hello,
I suggest that you use Chrome full screen mode (F11). It's been reported to work fine with smaller screen resolutions like yours.
Also you can always use a vertical screen if you can instead of a horizontal one (with a 90 degree rotation).
