### ISSUE TITLE
Zooey bot crashes consistently (Event battle)

### ISSUE THREAD

**Issue by csyeul** [Masuzu/ZooeyBot#871]
Basically I'm running the Poacher event extreme + nightmare when it appears without viramate.
However, the program crashes randomly (it could be 7min or 13min etc into starting the bot) but it always crashes during battle 2 of extreme stage of the Poacher event.

No logs are created in crash, so I am not sure how to even diagnose the problem. The program closes completely without warning. 

I've read the entire FAQ from top to bottom but I couldn't find a working solution. 
Does anyone know how to resolve this problem?

**Comment by Masuzu** [comment]
Hello,
I am afraid this is too isolated to reproduce consistently, since no other user seem to have this issue.
Make sure above all to have a stable internet connection.

**Comment by Miyoumu** [comment]
I am now experiencing this issue consistently with Deluge Trial and the new Aquors event.
