### ISSUE TITLE
Summer Event Expedition pop-up stalls the bot

### ISSUE THREAD

**Issue by moourns** [Masuzu/ZooeyBot#875]
The summer event introduced an arcarum-like expedition quest that can only be undertaken once you fill up the expedition bar. Each 20 AP raid fills up the bar by 10 and once you fill it up completely, you get a pop up that shows you can undertake the expedition. This pop up stalls the bot and everytime it tries to refresh, it just ends up going to the home/sign out page.

**Comment by Masuzu** [comment]
Hello,
I am not sure I follow: I have not been hindered in the least by that popup screen whenever it appeared as the bot would move directly to the URL of the 20 AP raid again after reaching the result page.
Make sure to leave your `EventPageUrl` parameter blank.

**Comment by moourns** [comment]
I was using TreasureEvent mode to farm the 20 AP quest but using Event mode fixed the issue. However, I started using TreasureEvent mode to run the 30 AP Ex quest (I can't leave the EventPageUrl blank in this mode) and the bot would hang for a moment when the pop up appears trying to pick the quest before refreshing the page. After waiting a couple more seconds it would finally go to the URL to start the quest. It works just with a slight delay due to the pop up. Not sure if anything can be done to speed that part up but since it's not stalling, I can deal with it.

**Comment by i-Grey** [comment]
Same with moourns. It would be better if there's something to speed up about that part.

**Comment by Masuzu** [comment]
Indeed the page will be refreshed when it happens but it is just a minor annoyance, isn't it?
A quick alternative to work around it would be to use Viramate's popup auto close feature.
