### ISSUE TITLE
Is it possible to make the bot do NM procs using the raid scheduling?

### ISSUE THREAD

**Issue by xerance** [Masuzu/ZooeyBot#876]
Hey, is it possible to que up the bot to do x raids but still to possible nm procs that might happen?

While we haven't seen much use for it until now, it would be quite useful if you make the bot farm x raids until expedition bar fills up for one manual arcarum(summer edition) run.

**Comment by Masuzu** [comment]
Hello,
What you describe can be done as shown here: https://github.com/Masuzu/ZooeyBot/wiki/Customized-raid-scheduling#rise-of-the-beasts-specific-commands
