### ISSUE TITLE
Enhancement Request: Pushbullet integration 

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/ZooeyBot#878]
It would be nice to have integration with Pushbullet API to send alerts to our phones with screenshot when captcha is found. So in case we are AFK we can also send remote commands using pushbullet to stop the bot or if possible send the appropriate captcha letters and let the bot input those.

**Comment by Masuzu** [comment]
Hello,
That sound terrific! If I had more time I would consider doing it. However, right now I have my sights on other completely different things.

**Comment by xerance** [comment]
maybe merge this one with https://github.com/Masuzu/ZooeyBot/issues/737 as a future perhaps planned feature?

**Comment by Masuzu** [comment]
Merged as requested. However, just keep in mind that the ROI is too low to justify the feature right now.
