### ISSUE TITLE
Zooey Bot calibration takes a long time

### ISSUE THREAD

**Issue by ghosimage1** [Masuzu/ZooeyBot#879]
Hi all,
On a sudden day, my calibration takes a long time to work. I am not facing eternal calibration. But the calibrating takes more than 5mins before I refreshes the page and it starts to move own its own again. May I know where went wrong? All the per-requisite settings has been set correctly, therefore it should not be having settings issue, if not it wont work at all. Can some tell help me with understanding why the calibration will take so long to work? It was fine the day before and the next morning it becomes like that. 
Thanks

**Comment by ImmaGOOD** [comment]
same here i got freeze at calibating like 5 min and bot still do nothing 

https://i.imgur.com/rCC9wJi.png

**Comment by Ohwhat00** [comment]
Make sure your game animation and resolution settings are set to standard and if possible, make sure your browser window shows majority of the game.

**Comment by Masuzu** [comment]
Hello,
You can also check this:
https://github.com/Masuzu/ZooeyBot/issues/886
