### ISSUE TITLE
ZooeyBot stops working most of time after initialization

### ISSUE THREAD

**Issue by MagCat** [Masuzu/ZooeyBot#88]
This is not a crash. Zooeybot does nothing at summon selection screen. Here is the list of steps I tried:

1) At first the bot just crashes straight up when a special quest starts, 

2) I thought it was due to viramate support being buggy again, so I went back .ini to set it to false to see if combat works. However, after setting it to false, the bot client just does nothing after 3/3 initialization (after it tries to clear network history). 

3) I tried to restart the client and chrome several times, after an hour, the bot finally moves again and select summon, but crashed again due to lua script(?). I thought the preferred summon selection is bugged, so I set the parameter to false. However, the client does nothing after clearing network history, and got stuck at summon list. 

Note that the client doesn't crash when it hangs at summon selection screen. I also made sure the network tab is visible and not in capture screenshot mode.

Update: After many struggles to get bot working by disabling and enabling ChromeDev and clearing network history, I found a problem that keeps the client crashing. I need you guys to look at the script to see what is causing the crash.

DisableChargeAttack()

if battle == 1 and turn >= 1 then
character_3.UseSkill(2)
character_1:UseSkill(3)
end

if battle == 2 and turn >= 1 then
character_3.UseSkill(2)
end

if battle == 3 and turn >= 1 then
character_1.UseSkill(2)
character_1.UseSkill(4)
character_2.UseSkill(2)
character_3.UseSkill(1)
end

if battle == 3 and turn >= 3 and character_1.charge_gauge >= 100 then
EnableChargeAttack()
Summon(6)
character_1:UseSkill(1)
end

Update 2: Increasing ms delay for skills, summons or whatever does not help.

**Comment by Dreamfinal** [comment]
So am I. stops working most of time after initialization

[EventMode]
Enabled=true
EventRaidUrl=http://game.granbluefantasy.jp/#quest/supporter/500361/5
EventRaidScript=Scripts/test.lua
NightmareModeUrl=http://game.granbluefantasy.jp/#quest/supporter/510051/5
NightmareModeScript=
EventPageUrl=
NightmareModePreferredSummons=Lucifer
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=true
WaitTimeInMsAfterEventPageIsLoaded=5000




if battle < 3 then
  DisableChargeAttack()
else
  EnableChargeAttack()
end
if battle == 1 and turn == 1 then
  Summon(6)
end
if battle == 1 and turn == 1 then
  characters["Heles"]:UseSkill(3)
  characters["Jeanne d'Arc"]:UseSkill(3)
end
if battle == 3 then
  characters["Gran"]:UseSkill(2)
  characters["Gran"]:UseSkill(4)
  characters["Jeanne d'Arc"]:UseSkill(1)
  characters["Jeanne d'Arc"]:UseSkill(2)
  characters["Heles"]:UseSkill(1)
  characters["Heles"]:UseSkill(2)
  characters["Lucio"]:UseSkill(1)
  characters["Lucio"]:UseSkill(3)
end
