### ISSUE TITLE
Problems with lua script.

### ISSUE THREAD

**Issue by JohnCog** [Masuzu/ZooeyBot#880]
I can't understand why the script crashs, I mean diantha is in the backline but i put those (is_alive) in case someone in the team dies and she comes forward.
![image](https://user-images.githubusercontent.com/37500265/43671905-18d0469e-9779-11e8-9e7c-0ed39f833ae6.png)
![image](https://user-images.githubusercontent.com/37500265/43671906-22d2237e-9779-11e8-97f0-6b9f675f8b42.png)

**Comment by JohnCog** [comment]
Actually is for every character i mention without having it in the frontline. 
![image](https://user-images.githubusercontent.com/37500265/43673182-740119b0-9794-11e8-8b84-cc5735c3f331.png)

**Comment by JohnCog** [comment]
![image](https://user-images.githubusercontent.com/37500265/43673184-7f25789a-9794-11e8-9bd6-145c955d9a0c.png)

**Comment by Ohwhat00** [comment]
The `is_alive` field is only intended to be used with the variables character_1, character_2 and so on.

Just use the following instead for sub characters:

```
if characters["Feower"] ~= nil then
characters["Feower"]:UseSkill(1)
characters["Feower"]:UseSkill(2)
end
```

**Comment by Masuzu** [comment]
Thank you @Ohwhat00
