### ISSUE TITLE
Cant Change Serial key 

### ISSUE THREAD

**Issue by ImmaGOOD** [Masuzu/ZooeyBot#882]
please Fix Serial key page is broken

https://i.imgur.com/zHZAkxM.png

**Comment by Masuzu** [comment]
I am not sure this is valid anymore. Tested that the serial number update was functional and indeed it is.

**Comment by ImmaGOOD** [comment]
i still cant still got same error

**Comment by ImmaGOOD** [comment]
so i do is get serial number from my new PC and paste in to new one but still error

**Comment by ImmaGOOD** [comment]
9e726a9fe9deb028eac7a7605df2b3ce87e9a3eaa4fb66b33193a6344b12ac1d4e660bbb11bf9821abdfc7adfeaa1962bbf11ea5972c53a3e556fd813df5e048

here's my new pc serial code please check
