### ISSUE TITLE
Timer is not working.

### ISSUE THREAD

**Issue by csyeul** [Masuzu/ZooeyBot#884]
TimeLimitInSeconds=7000

This variable is set to 7000 seconds, roughly 116minutes. However, the bot keeps going no matter what unless it's stopped or runs into captcha. Why doesn't the timer work?

**Comment by Ohwhat00** [comment]
Have you tried something smaller like 15mins (900 seconds) to see if that's the case?  Mine always automatically closes when the time limit has been reached.

**Comment by csyeul** [comment]
Seems like the only value that does not work is the default value (7000), I change it to any other value and it works. Pretty weird but I guess I can work around it.
