### ISSUE TITLE
Slave Mode Stuck on Calibration

### ISSUE THREAD

**Issue by Copiousity** [Masuzu/ZooeyBot#888]
I checked my scaling and checked for 3/6 + 6/6 and also the new network request.
But when i press enter, the bot clears the main account's console log and stops moving.
The bot is still open but it just doesn't do anything after clearing the console log.
In the cmd, it just says "calibrating".

**Comment by Masuzu** [comment]
Hello,
You may want to use standard resolution settings on your slave window as well, I have been told that for some people using Lite settings on both the slave and main account window did not work sometimes, while Lite settings worked fine on the main account for the other modes.
