### ISSUE TITLE
Slave mode calibrating issue

### ISSUE THREAD

**Issue by Avalachance** [Masuzu/ZooeyBot#889]
Dear Masuzu,

With all due respect, I understand that I may be just reposting the same issue as everyone else, but I feel like this is strange. I was able to bit finely just a few days ago until it stopped at Calibrating while using Slave mode. 

What I have noticed is that when I tried to refresh both the windows, both say Slave window (I will attach a screenshot for this). Could that makes Zooey does not calibrate? Because it thinks both are the Slave, and no Master window is found?
Other than that, though, I am unable to find anything wrong.

I do get that you are trying to say that it is running just fine on your side, but however, it is not, on my side. I am a quite long time user, so I supposedly know what I am doing, and no, I am using all the set up you give. I am using standard on both windows, no zoom, medium size. Yes.

I thank you in advance,

Regards,
Lucy.

P.s. I don't know why, there was one time, ALL my scripts in the Script folder is gone and replaced by the 2 default scripts. I don't really mind rewriting the LUAs, but... eh. if it keeps happening I suppose I'll get angry too one day.

![caliisue](https://user-images.githubusercontent.com/42192375/43809996-b400fc08-9adf-11e8-853d-6cab64c4c2f3.png)

**Comment by Masuzu** [comment]
Hello Avalachance,

Thank you for all the details about the issue you are facing. I can confirm the fact that refreshing the main account window results in the "Slave window - New page loaded" message being also displayed, but this should not prevent the calibration from succeeding on the slave window, nor the continuation of the execution. From the screenshot above, the calibration phase for your main account completed, then I guess that you probably refreshed both pages after seeing that the calibration was stuck for the slave account window? What bothers me is the absence of "Successfully hooked to the home button" message during the slave calibration, which makes the issue you are facing not linked to the extension initialization. Did you make sure to press Enter or Backspace properly depending on which window was initially identified as the slave one?

By the way, when you reload the slave account window, you should only see "New slave network request received" messages in the console, not "New network request received messages". If not, then make sure that this is configured properly for the Zooey Bot (non slave) extension: 
![image](https://user-images.githubusercontent.com/5464705/43841994-a6c28788-9b24-11e8-9b95-bdaf2377a25f.png)


About the scripts disappearing, I can guarantee that the program itself does not delete any files. The only file modification which happens is the creation of the `serial_number.txt` file at start up. It could be an antivirus marking the script files as quarantined and deleting them in the process, even though this usually happens with executable files or archives. Or it could simply be a wrong user manipulation.

**Comment by Avalachance** [comment]
Dear Masuzu,

Ah, yes, it probably is because of the key that the script is missing. 

And also, yes, your assumptions is correct, I refreshed my slave window, then the main window. And I am a 100% sure I pick the right window, of course. As I have mentioned, this is not my first time botting. I've done it longer than you think. 

I made sure that ONLY the Slave extention (Beatrix) is available on incognito mode, Zooey is not enabled. 

The message I am receiving after reloading the slave page is correct too, I only am refreshing the main page to make sure it doesn't give slave network. 

So yes. I am pretty clueless about this myself. I wouldn't mind if you want to check this out by yourself using Team Viewer or other sort of method. 

Thank you for your reply, looking forward for another. 

Regards, 
Lucy.

**Comment by Masuzu** [comment]
The new version 14.5 introduces additional debug information regarding this specific issue:
https://github.com/Masuzu/ZooeyBot/releases/tag/2.14.5
```
[Debug]
...
Clicks=false
# When this parameter is set to true, Zooey bot won't start until you press ENTER. This is especially useful to test your Lua scripts using trial battles.
TrialBattleMode=false
DebugCalibration=true
...
```

**Comment by Avalachance** [comment]
Dear Masuzu,

Here's what the console looks like:
![caliisue2](https://user-images.githubusercontent.com/42192375/43870752-53a75a0e-9ba3-11e8-9327-915740bdda83.png)

and here's the CalibrationDebugImage.png:
![calibrationdebugimage](https://user-images.githubusercontent.com/42192375/43870766-63ab4f78-9ba3-11e8-9f2d-4c78ed45010e.png)
Looks pretty normal eh?

Yeah, I don't know what's wrong. Addition information for me to add, the cursor stops at the "Clear" button on the Main window DevTool after clicking it and doesn't move at all.

Thank you.

Kind regards,
Lucy

**Comment by Masuzu** [comment]
Oh I see now, it may seem very silly but I suggest you hide your bookmark bar.

**Comment by Avalachance** [comment]
Dear Masuzu,

Thank you for your reply, yet, here I am, bringing more bad news :(

![caliisue3](https://user-images.githubusercontent.com/42192375/43889658-02495a1c-9bef-11e8-889d-802b2c560403.png)
![caliisue4](https://user-images.githubusercontent.com/42192375/43889664-0555f33c-9bef-11e8-85af-5a5cbf075cef.png)
![caliisue5](https://user-images.githubusercontent.com/42192375/43889666-0703cf92-9bef-11e8-858b-bd938a14a75e.png)
![calibrationdebugimage](https://user-images.githubusercontent.com/42192375/43889674-09c2bae0-9bef-11e8-80bc-c6743c290b93.png)

the value changes after a while, but it's decreasing. And.. nope. Doesn't work.

Oh anyway, if you didn't notice, maybe because I censored the name, but the Debug Image is taken on my slave window, not the main window (it's kinda obvious, but just in case you missed it).

Kind regards,
Lucy.

**Comment by violafayde** [comment]
Hi, I'd like to add to this issue as well. I have had a similar problem while trying to bot. The bot can detect both windows and clears network history, but then just stops after that and begins to refresh the page.
![screenshot_5](https://user-images.githubusercontent.com/33265321/44275041-5a528c00-a276-11e8-93d4-632bac1001d5.png)

**Comment by lamewood** [comment]
I had the same issues like you guys stated, the bot calibrates the main window successfully, but stops at calibrating the slave window.
I tried a little around and the bot started working after I clicked on the Home from the Slave Window, without releasing the click (not actually clicking, but still clicking per se)
Then the bot started working like it should
I hope this helps for the debugging

**Comment by Masuzu** [comment]
It looks like a window getting out of focus issue if you had to move the cursor inside the window of the slave account and clicking somewhere inside to make it active.

**Comment by violafayde** [comment]
it was on network, i moved it to console to look at some stuff. but it doesn't resolve the matter of the bot constantly refreshing the main account and doing nothing after the text saying 'Initialization complete, Zooey is now proceeding to autopilot mode.'
