### ISSUE TITLE
Is it possible to make Zooey Bot work with Ancheera ?

### ISSUE THREAD

**Issue by ngocin** [Masuzu/ZooeyBot#890]
Hi Masuzu
When i don't use zoi bot to auto, i usually use combine both viramate and ancheera (not from chrome store, its outdated) to play
The function "Skip next quest" or "Skip Coop Result" is really useful, or i should say powerful, i can even do 6-8 slime per minute with it . It's the best if zoi bot can work with it! 
![1](https://user-images.githubusercontent.com/30687323/44138442-2a1dcf56-a09e-11e8-94d9-c7c5baafbc0c.PNG)

**Comment by Chololoco13** [comment]
where did you get the new version?

**Comment by ImmaGOOD** [comment]
ngocin not found yet LOL

**Comment by Masuzu** [comment]
Hello,
That is a good QoL feature indeed but have other projects I am working on which have the priority right now.

**Comment by ImmaGOOD** [comment]
@Masuzu  can we have feature that we can do 4 man coop ?

**Comment by Masuzu** [comment]
@ImmaGOOD I will follow up in https://github.com/Masuzu/ZooeyBot/issues/918.
It depends on my other ongoing projects.
