### ISSUE TITLE
ZooeyBot sometimes not completely refilling AP

### ISSUE THREAD

**Issue by djeeta111** [Masuzu/ZooeyBot#891]
It usually gets stuck refilling AP somehow, I actually intervene before it gets completely stuck.

Granted I'm not exactly using the raid scheduler completely as intended probably (though it doesn't really fit regular mode scheduling or anything because Quests like Antiquarian Troubles are only two times per day.

but somehow it gets stuck refilling AP once a day in my scheduler (outside of magfest)

![image](https://user-images.githubusercontent.com/37136455/44179809-e6fe1e00-a0ad-11e8-9c35-6232f504da82.png)
(sorry for the blanks, I did it to preserve my privacy)

it selects the summon, but since I didn't have enough AP to start, it tries to refill...which it does, but not enough and tries to start with it

![image](https://user-images.githubusercontent.com/37136455/44179841-11e87200-a0ae-11e8-8a41-37c1387a1de7.png)

![image](https://user-images.githubusercontent.com/37136455/44179862-32183100-a0ae-11e8-87ff-86453d5aad20.png)

so I end up very quickly using another halfpot and refreshing the page, then it continues as normal, but otherwise it gets stuck

(interestingly the 2nd run loads perfectly fine, possibly because it only needed to refill 1 halfpot)

I'm pretty sure it's because ZooeyBot only refills 1 halfpot when not enough AP (without doing any calculation after, and gets stuck as a result if the cost of the AP is too high).. which is why I didn't see this during magfest as 40 AP is much more managable?

Thanks in advance

**Comment by breinjhel** [comment]
Im also getting this error sometimes

**Comment by Masuzu** [comment]
Hello,
Thank you for reporting this bug. I am sorry that there is no refill of more than 2 potions at a time for now, while this should be needed indeed!
