### ISSUE TITLE
Using bot after account suspension got lifted

### ISSUE THREAD

**Issue by i-Grey** [Masuzu/ZooeyBot#894]
I'm ZooeyBot user for more than 1 year.
2 weeks ago I've got permanent account suspension because grinding too much and can't reproduce Captcha immediately after it appeared.

After I got BANned, I sent an apologising mail immediately to GBF team and they lifted my BAN around last week.

My question is "Is it still considering as SAFE for using ZooeyBot again"?
They describe in mail that GBF Team will take more severe action if I violate rule again.

Is there anyone who got permanent account suspension like me and still using ZooeyBot?
Please share your experience. Thank you.

P.S. I've got temporary BAN around 1-2 years ago. Which is 3-6-9 hours temporary suspension.

**Comment by Chololoco13** [comment]
I think you're safe unless you take a long time to solve the captcha.
I grinded slimes 5-8 hours a day.
You should always be aware of the captcha with the speakers at a high volume.
During the magnafest I was wrong 4 times in a row with the captcha and I was not banned.
Google translator

**Comment by i-Grey** [comment]
Thank you Chololoco13.

The reason of my latest banning is taking too much time on solve the captcha.
I will make sure that I will use ZooeyBot when I'm sticky with the PC.

Thanks for your advice.

**Comment by Masuzu** [comment]
You'd better have your PC close by in any case to be on the safe side.
Waiting too long before solving a captcha is very unfortunate. Make sure not to mute your speakers so that you can hear the sound notification if you are not keeping an active eye on your window.
