### ISSUE TITLE
Main Window needs delay during Slave Mode

### ISSUE THREAD

**Issue by lamewood** [Masuzu/ZooeyBot#896]
During Slave mode, my main windows is lacking behind in speed and the bot always refreshes the window right after the game shows up. This leads to huge delays in terms of efficient farming.
Is there a setting for the bot to wait a little longer before trying to refresh? 
I added several ms to the settings but all it did in the end was delaying using the skill after the refresh.

I hope you can help me out, greetings!

**Comment by Masuzu** [comment]
Hello,
You can increase the values of the parameter `MaxResponseDelayInMs` under the `General` section of your configuration file to mitigate this issue.
Normally it's only during the first battle that loading times may be significantly higher. Assets are then cached and the other runs go very smoothly after, at least on my end.
