### ISSUE TITLE
Slave mode no longer working after update

### ISSUE THREAD

**Issue by Rkdheishins** [Masuzu/ZooeyBot#899]
The moment the game updated the co op slave mode is no longer working.

with or with out the lua scrips with 2 accounts the main account will not select attack or abilities 

made sure to select other lua scrips
no luck
tried without lua scrip
no luck

the slave account continues to work, weather its using abilities or attacking but the moment its the main accounts turn, the mouse stops moving and refreshes.

restarted computer, no luck. and same result
re downloaded zooey, no luck and same result

zooey works with event mode on main account, but refuses to work in slave mode with 2 accounts the very second gbf updated tonight.

**Comment by xiang-guo** [comment]
I have same kind of issue using salve mode after updated. 
My sub account keeps refresh for "abnormal wait time". But I didn't change any setting.

**Comment by Rkdheishins** [comment]
Another update, downloaded on second computer, same problem persists, is their a fix for this or a workaround Masuzu?

**Comment by Rkdheishins** [comment]
Wonderful news!
so even after deleting zoey bot folder and re download and using settings at default it was still not working but, after deleting all zoey bot folders, completely removing zoey bot extensions  and slave extensions that seemed to do the trick.

something happened when the new update hit, it somehow disabled extensions from working properly, so i think by removing them and added back the extensions that should fix our problem :D

**Comment by Zuser120000000** [comment]
A similar problem also occurs in my environment.
How did you solve it?

**Comment by Zuser120000000** [comment]
If you use older version it will not happen, but it will not work with the latest version.
I recognize that it is a problem on the bot side.
It seems that we have not received a response from Slave Account side (SeacretWindow).
