### ISSUE TITLE
The use of green potions

### ISSUE THREAD

**Issue by Rkdheishins** [Masuzu/ZooeyBot#901]
Is their a way to tell zoey "if" theirs any green potions left then use them.

im running into a situation where u use all my green potions and shes stuck on trying to use them still

how can i scrip if theres no potions left dont "keep trying" to use them?

my script is as follows for the use of green potions

	if character_1.hp_percentage < 23 then
	  UseGreenPotionOnPartyMember(1)
	end
	if character_2.hp_percentage < 23 then
	  UseGreenPotionOnPartyMember(2)
	end
	if character_3.hp_percentage < 23 then
	  UseGreenPotionOnPartyMember(3)
	end
	if character_4.hp_percentage < 23 then
	  UseGreenPotionOnPartyMember(4)
	end
	if character_3.name == "Mahira" then
	end

**Comment by salvanost** [comment]
If i’m not wrobg if no green pot bot won’t attempt to use green pot again
Maybe bug? Oh well let’s try make some script then
It’s just an idea u need to confirm this urself
Use 2 boolean

If turn == 1 then 
   Booleans[“2pot”] == true
   Booleans[“1pot”] == nil
End

If booleans[“2pot”] == true then
if character_1.hp_percentage < 23 then
  UseGreenPotionOnPartyMember(1)
  Booleans[“2pot”] == nil
  Booleans[“1pot”] == true
end
if character_2.hp_percentage < 23 then
  UseGreenPotionOnPartyMember(2)
  Booleans[“2pot”] == nil
  Booleans[“1pot”] == true
end
if character_3.hp_percentage < 23 then
  UseGreenPotionOnPartyMember(3)
  Booleans[“2pot”] == nil
  Booleans[“1pot”] == true
end
if character_4.hp_percentage < 23 then
  UseGreenPotionOnPartyMember(4)
  Booleans[“2pot”] == nil
  Booleans[“1pot”] == true
end
End

If booleans[“1pot”] == true and booleans[“2pot”] == nil then
if character_1.hp_percentage < 23 then
  UseGreenPotionOnPartyMember(1)
  Booleans[“1pot”] == nil
end
if character_2.hp_percentage < 23 then
  UseGreenPotionOnPartyMember(2)
  Booleans[“1pot”] == nil
end
if character_3.hp_percentage < 23 then
  UseGreenPotionOnPartyMember(3)
  Booleans[“1pot”] == nil
end
if character_4.hp_percentage < 23 then
  UseGreenPotionOnPartyMember(4)
  Booleans[“1pot”] == nil
end
End

**Comment by salvanost** [comment]
Hmm... looks like the booleans method not working, i’m testing it to my bot

**Comment by Masuzu** [comment]
Hello,
Trying to use green potions when none is left is not supposed to happen and nothing should have changed with the last versions?

**Comment by Rkdheishins** [comment]
Yea sorry my bot keeps trying to use potions when 0 is available

Its clicking on potions”when none is available” and trying to select character
This process goes on until i stop zoey, ive watched it for 5 mins and came to a conclution that its stuck at this point.

Any solutions on how to fix this?

**Comment by salvanost** [comment]
Tell mazusu ur bot version
The one come up small pop up when u start the bot

**Comment by Rkdheishins** [comment]
yea, you cant use zoey unless its the newest version. and its doing it everyday, and yes here even on guildwar, please help me find a fix for this Masuzu
