### ISSUE TITLE
serial number automatically changing whenever staring the program

### ISSUE THREAD

**Issue by imwithme** [Masuzu/ZooeyBot#903]
Whenever I try to start the program the serial_number.txt file changes and I come up as an unregistered user. I've tried manually changing the serial number to match the one shown on my account settings but the txt file still gets changed when starting up the program. The serial_number.txt file changes to the same serial number every time.

I've tried redownloading the program and key file to no avail.

**Comment by imwithme** [comment]
I don't know why but it seems that the issue has resolved itself

**Comment by imwithme** [comment]
The program has started changing the serial number again. It appears to be changing to the same serial number as before. This time I tried to change to this serial number through account management but it tells me that it is already taken.

**Comment by Masuzu** [comment]
Hello,
This is definitely not supposed to happen. This can happen with some windows updates but your serial number should stop changing after you install the last update.
