### ISSUE TITLE
An error occurs when a sub member appears on the front line

### ISSUE THREAD

**Issue by Zuser120000000** [Masuzu/ZooeyBot#904]
I am using Google Translate.
Currently I am using Zooey bot in Japanese.

![image](https://user-images.githubusercontent.com/35060006/44620520-d41af300-a8d0-11e8-9322-c41fa7c06ad5.png)

Despite this way of writing, an error occurs when it comes out on the front line.
Please tell me the solution.

**Comment by Masuzu** [comment]
Hello,
What is the error message (if any)? Is there any popup window indicating a script parsing error?
I do not see anything wrong with your script for now, or else it could be caused by encoding issues (it should be encoded using UTF8 or UT8-without BOM depending on your Windows locale settings).
