### ISSUE TITLE
Zooeybot triggers alert captcha on summon even without captcha

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/ZooeyBot#905]
Zooeybot goes to summon selection and selects Misc tab for some reason then finds a long list of summon there and treats it as captcha. I dont see any verify button and Im not using favorite summons in viramate. Its kinda annoying i have to re roll the summon and start the bot again.

**Comment by Masuzu** [comment]
Hello,
I am aware of this: it is an occasional issue which can happen when you have some people not setting some summons in their support slots.

**Comment by Masuzu** [comment]
I apologize for the very late reply, I will publish a new release today or tomorrow to address this case.

**Comment by Masuzu** [comment]
The detection is less likely to report false positives as of v2.14.7

**Comment by breinjhel** [comment]
Thank you very much :)

**Comment by breinjhel** [comment]
Thanks :)

**Comment by breinjhel** [comment]
I just verified it still does happen. :( For reference when it couldnt find the summon it clicks the new tab button in chrome for some reason.
