### ISSUE TITLE
Summon confirmation issue

### ISSUE THREAD

**Issue by BB951** [Masuzu/ZooeyBot#906]
I am not sure if this is just an issue on my side, but since today, if ZooeyBot has to scroll down to select a support summon, the confirmation popup box will appear out of screen at the top of the page, and  the bot will get stuck on summon selection page trying to click the "OK" button.

![capture2](https://user-images.githubusercontent.com/40469795/44626918-d5dbc980-a957-11e8-9a3c-749e12a3549d.PNG)

![capture](https://user-images.githubusercontent.com/40469795/44626907-96ad7880-a957-11e8-96cc-b872d038bb0a.PNG)

**Comment by salvanost** [comment]
try to use vpn like browsec

**Comment by BB951** [comment]
Using a VPN didn't work, but turns out the cause was an anti-tracking extension I had installed in Chrome. Added an exception for the GBF site and it's working fine now.
