### ISSUE TITLE
Chrome extension issues

### ISSUE THREAD

**Issue by WVVWVWVVW** [Masuzu/ZooeyBot#91]
Pressing start on the extension doesn't do anything. I've tried reinstalling it, reloading it, redownloading Zooey-Bot, and restarting my computer.

**Comment by Nanaya8** [comment]
I have the same problem on my virtual machine. I press start on both the main extension and the slave and nothing happens, the bot still waits for them to start. Fine on my main computer otherwise.

**Comment by Masuzu** [comment]
Some antivirus may cause the issue.
Should this still happen, I apologize but I won't fix the issues encountered by a minority of the users.
