### ISSUE TITLE
ZooeyBot closes itself

### ISSUE THREAD

**Issue by Taktakshi** [Masuzu/ZooeyBot#911]
Was running it on my first raid, then it closes itself.
Subsequently it just runs as per normal till you close for the subscription date, where it closes itself again.
Then i never had a chance to actually open the bot to make it work proper.
Realize that on Summon(6) in the .lua, it just quit itself. Works again once i took that Line out.
To add on, after it closes down by itself while having the Summon(6) is present, the moment the program quits i cannot drag-drop anything at all until i refresh the PC.
No AV software used/active on my platform.

**Comment by Taktakshi** [comment]
To add on, after it closes down by itself, i cannot drag-drop anything at all until i refresh the PC

**Comment by Masuzu** [comment]
Hello,
The symptoms look like an unstable internet connection. I am sorry I will have to close the ticket as it is not reproducible at all under normal usage conditions.
