### ISSUE TITLE
Potential out-of-memory crash workaround?

### ISSUE THREAD

**Issue by NxKai** [Masuzu/ZooeyBot#912]
Hi, New here, big fan of your work.

Been running into some performance issues for a while now, like 7-8 days worth of using the bot. After a while, the browser window will begin to slow down(without desyncing, which is what I expected). I made some changes to the settings of the dev tools because I thought the clear button was not being pressed earlier; I manged to fix that but now dev tools stops the bot from continuing due to a "Potential out-of-memory crash" which clearing the network activity tab seems to not fix. Did I miss something in my configuration?

I run Google Chrome Version 68.0.3440.106(64-bit) on a Windows 10 Home system(build10240) with 8 GB of RAM.

**Comment by Masuzu** [comment]
Hello,
That is really unfortunate indeed. I know of some issues when you have in-game sound settings enabled, which would cause a steady increase in memory consumption until this browser would stop responding altogether. Disabling sound settings, unless you are stuck on a same page for several minutes, your memory consumption should not go beyond 2 GB.

**Comment by Masuzu** [comment]
Note that https://github.com/Masuzu/ZooeyBot/issues/914 is a point of action for future releases.

**Comment by Masuzu** [comment]
I advise you to try the newly released version 3.0.0 introducing brand new changes specific to this issue.
https://gbtools.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#3-0-0
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/ZooeyBot?src=hash&amp;ref_src=twsrc%5Etfw">#ZooeyBot</a> <a href="https://twitter.com/hashtag/SarasaBot?src=hash&amp;ref_src=twsrc%5Etfw">#SarasaBot</a> You will definitely enjoy the upcoming releases 🙂 101 turns, retained memory still below 250 MB, while your browser window would have become slow to the point of being unresponsive with the previous versions. <a href="https://t.co/0ZPN255VCo">pic.twitter.com/0ZPN255VCo</a></p>&mdash; GBTools (@GBFPokerBot) <a href="https://twitter.com/GBFPokerBot/status/1037427847919546375?ref_src=twsrc%5Etfw">September 5, 2018</a></blockquote>

**Comment by NxKai** [comment]
Thanks a lot for this! I have no time testing this out ASAP, but I will make some tests once the weekend hits.
