### ISSUE TITLE
Failure to load new Slave Extention

### ISSUE THREAD

**Issue by Shamool** [Masuzu/ZooeyBot#915]
![failure](https://user-images.githubusercontent.com/30111700/45133672-24dff500-b1c9-11e8-9123-a2a082be1a7d.PNG)

Posting what I saw. Just a heads up

**Comment by Masuzu** [comment]
Hello,
Thank you for reporting this, I will fix it later in the day.
In the meantime you can delete everything past the line 36.

**Comment by Masuzu** [comment]
This is now fixed in v3.0.2.
