### ISSUE TITLE
chain in the previous quest

### ISSUE THREAD

**Issue by sharpnelOwO** [Masuzu/ZooeyBot#916]
if 4 chained before quest, when zooey trying to use ability or summon,GBF says "waiting for last turn to be processed".
after this message. zooey skips the ability that couldn't use

ex:
if turn == 1 then
character_4:UseSkill(2)
Summon(1)
end

In this case,zooey ignores the second skill of character 4 and executes Summon (1)

**Comment by Masuzu** [comment]
Hello, that is the expected behaviour.
Please consider increasing the parameter `AdditionalDelayInMsAfter4ChainBurst` under the `Combat` section accordingly.

**Comment by sharpnelOwO** [comment]
I made a video
https://www.youtube.com/watch?v=BfsS5nujLu4&feature=youtu.be
