### ISSUE TITLE
I have an idea to create 3th and 4th coop ID 

### ISSUE THREAD

**Issue by Dreamfinal** [Masuzu/ZooeyBot#918]
First of all, I understand that there's restriction that 1 PC can operate 2 screens at a time (2nd ID in incognito mode). 
However, I have a solution to this. Why not use a second PC to run 3rd or 4th ID?

For an example;
1st PC works normally. Which is 1st ID clicks ready while 2nd ID waits to click start.
On 2nd PC, 3rd ID clicks ready just like 1st ID (in case, there is 4th ID running on the second PC, it should wait to click ready button as well).
In the continuing process, the other IDs will get more potions and could switch roles to decrease stamina consumption.

I think this example/algorithm is possible to make. And it will be beneficial to you and players who have multiple IDs and resources. 
You will have more customers that want to buy your product. 
Because right now all players ran out of red potion. And this solution will help you regenerate infinite red potion for people who use 2 PCs with 4 IDs coop at the same time.
 Please consider this offer, it will be win-win for all. If you succeed, you will be the first person who could solve this national Grand Blue problem. You are the only hope of humanity.

**Comment by RaiModels** [comment]
Totally agree with this, a third client would mean unlimited pots. Instead of requiring a second PC though could also try and run it via different users(chrome profiles) or using two different chrome versions.

**Comment by Masuzu** [comment]
Hello,
Ideas on how to add this feature is now what is missing indeed. I can see myself working on it in the future.
