### ISSUE TITLE
Is the server down?

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/ZooeyBot#919]
I cant seem to load zooeybot it takes too long to open the console and when it does it crashes when trying to access the server to check the key or something

**Comment by ngocin** [comment]
Im having the same problem

**Comment by Zuser120000000** [comment]
It is the same situation.
As you say, if the server is down, there is no choice but to wait for recovery.

**Comment by Masuzu** [comment]
The issue should have been resolved now.

**Comment by Chololoco13** [comment]
same problem
