### ISSUE TITLE
Chrome extension installation error

### ISSUE THREAD

**Issue by cakerecipe** [Masuzu/ZooeyBot#92]
Just downloaded the trial but can't get it to work. After I select "Load unpacked extension..." it always gives an error message "Failed to load extension from: D:\zooey-bot-v1.9.2\zooey-bot-extension
Could not load background script 'js/zooey-util.js'."

I already have both C++ redistributable and .NET framework installed.

Once this is fixed, is there a way to reset the trial (since it doesn't work right now)? Thanks!

**Comment by thenastyworm** [comment]
Sometimes one of the files in the extension gets quarantined by Antivirus as a false positive. Try extracting the files again and if you are using any, pay close attention to the anti virus.

If this file ends up missing, it would explain why loading the extension fiails.

**Comment by Masuzu** [comment]
What @thenastyworm said. Thank you
