### ISSUE TITLE
Selecting people rather than summons

### ISSUE THREAD

**Issue by RaiModels** [Masuzu/ZooeyBot#921]
I recently updated to the latest build and have noticed that the bot keeps accidentally clicking on people's profiles rather than their summons. The bot usually manages to get back on track, but I just watched the bot click on a user's profile, refresh twice, navigate back to the summons list and then proceed to click on the same player's profile again... To my knowledge this didn't use to happen on old builds?

**Comment by Masuzu** [comment]
Hello,
Are you using viramate compact summon list display by any chance?

**Comment by RaiModels** [comment]
Oh, you know what, that was the problem. Thanks!
