### ISSUE TITLE
something about party selection script

### ISSUE THREAD

**Issue by niayyy** [Masuzu/ZooeyBot#923]
firstly appreciate for making the bot

my first question is that is it possible that (say in Rise of the Beast), I schedule to play the "Zhuque" for 2 hrs with using TEAM A selecting Shiva as summon, and then after the 2-hr, auto start to play "Xuanwu" for another 2 hrs with using Godsworn as summon and TEAM B

Also how do I target a particular part of the boss, say the boss has 3 parts

finally, how to set "request backup" when the boss's hp is below certain %?

How should I set such scripts?

Thank you very much

**Comment by Masuzu** [comment]
Hello,
Using the current time of the day to schedule a different raid is not possible for now.
Requesting backup is not possible for now. Even though that feature was not intended at all, I may add it in the feature as an _experimental feature_, which means that any possible related crash after requesting backup won't necessarily be addressed.
