### ISSUE TITLE
Assert4SymbolsPendantsBelow (30000) does not work

### ISSUE THREAD

**Issue by Zuser120000000** [Masuzu/ZooeyBot#924]
Write Assert4SymbolsPendantsBelow (30000) in the script and ZooeyBot will crash when reaching 30000.
There is no error.

![image](https://user-images.githubusercontent.com/35060006/45595759-753a2c80-b9eb-11e8-933b-f70ebf17165d.png)
![image](https://user-images.githubusercontent.com/35060006/45595762-8125ee80-b9eb-11e8-94eb-7777e5aa1240.png)

Both are similar

**Comment by worthworth** [comment]
I think
Assert4SymbolsPendantsBelow(30000)
is correct.

Your script is 
Assert4SymbolsPendantsBelow (30000)

**Comment by worthworth** [comment]
Did you try Assert4SymbolsPendantsBelow(30000) ?

**Comment by Zuser120000000** [comment]
Assert4SymbolsPendantsBelow (30000)
To
Assert4SymbolsPendantsBelow(30000)

I tried changing the above example to the example below, but the symptoms did not improve.

**Comment by Masuzu** [comment]
Thank you for reporting this, I will take a look.

**Comment by Zuser120000000** [comment]
It happens when we load the event page after reaching 30000.
ZooeyBot will exit while leaving the event page.

**Comment by Masuzu** [comment]
I see, thank you.
It is close to the expected behaviour: when your amount of pendants exceeds the value you give to `Assert4SymbolsPendantsBelow`, a sound alert should play. At least the main point is that Zooey does not keep going when you hit the pendants cap.
