### ISSUE TITLE
[Raid specific] Bot crashes when retrieving the combat state in certain situations

### ISSUE THREAD

**Issue by violafayde** [Masuzu/ZooeyBot#929]
Hi, I'm trying to use a script for Agni, but when it reaches turn 2 the bot loads the lua script and then freezes + crashes. I'm thinking it has something to do with the command PartySelect(x), as the bot crashes without any lua error dialog boxes. I've written scripts that work on long fights so I really cannot tell what the issue is.
Here's my script.

EnableChargeAttack()

if turn == 1 then
  SelectTarget(3)
  Summon(6)
  character_1:UseSkill(1)
  character_1:UseSkill(4)
  character_1:UseSkill(3)
  characters["Vajra"]:UseSkill(1)
  if characters["Altair"] ~= nil then
    characters["Altair"]:UseSkill(3)
    characters["Altair"]:UseSkill(2)
    characters["Altair"]:UseSkill(1)
  end
  character_1:UseSkill(2)
  if characters["Grea"] ~= nil then
    characters["Grea"]:UseSkill(1)
    characters["Grea"]:UseSkill(3)
    characters["Grea"]:OnPartyMember(4):UseSkill(2)
  end
  if characters["Vajra"] ~= nil then
    characters["Vajra"]:UseSkill(3)
    characters["Vajra"]:UseSkill(2)
  end
end

if turn > 7 then
  Summon(2)
end

if turn > 1 then
  Summon(5)
  Summon(4)
  Summon(3)
  character_1:UseSkill(1)
  character_1:UseSkill(3)
  character_1:UseSkill(4)
  if characters["Vajra"] ~= nil then
    characters["Vajra"]:UseSkill(1)
    characters["Vajra"]:UseSkill(2)
    characters["Vajra"]:UseSkill(3)
  end

  if characters["Altair"] ~= nil then
    characters["Altair"].UseSkill(1)
    characters["Altair"].UseSkill(2)
    characters["Altair"].UseSkill(3)
  end

  if character_1.charge_gauge >= 40 then
  character_1:UseSkill(2)
  end

  if characters["Grea"] ~= nil then
    if characters["Grea"].charge_gauge >= 30 then
      characters["Grea"]:UseSkill(3)
    end
    characters["Grea"]:OnPartyMember(4):UseSkill(2)
    characters["Grea"]:UseSkill(1)
  end

end

**Comment by Masuzu** [comment]
Hello,
Do you mean that you encounter the issue at this point:
`characters["Grea"]:OnPartyMember(4):UseSkill(2)`?
Are all the commands preceding this one executed, such as `characters["Grea"]:UseSkill(3)`?

**Comment by violafayde** [comment]
Nah, it's crashing just as turn 2 begins. As you know, at the start of each turn zooey will load the lua script, then display a list of debuffs that are currently on the enemies present. It is during this display of debuffs that it freezes for a microsecond (0.1ms?) and then closes itself.

**Comment by Masuzu** [comment]
Make sure you don't use some of the Viramte buff and debuff check features maybe?
![image](https://user-images.githubusercontent.com/5464705/45741232-61fbac80-bbf7-11e8-8f68-a4d64dbf4d61.png)

**Comment by violafayde** [comment]
i will test that. another problem is that SetPreferredPartyDeck and SetPreferredPartyGroup do not seem to work for when Agni and co. appear anymore. It keeps selecting the wrong party. For example, I have used SetPreferredPartyGroup(7) and SetPreferredPartyDeck(2) to select my water team for Agni, but the bot uses Group 1 Deck 1 instead. It also picked Bahamut summon, which was the default summon that was selected in combat mode. Also, the nightmare mode timer box appeared as well.

**Comment by violafayde** [comment]
nope, same problem happening. It just shows the debuffs on the enemies, does nothing and then closes itself.

**Comment by Masuzu** [comment]
Ah I see, thank you. It is raid specific then. I will have to test with Agni specifically.
Acknowledged the bug regarding the summon and party selection based on the Nightmare settings defined in the Party and Summon selection sections of the configuration file.

**Comment by violafayde** [comment]
thank you. zooey has been a great help to me because of my insane schedule and i hope you can further improve zooey's functionalities. :)
