### ISSUE TITLE
Co-op slave mode bug?

### ISSUE THREAD

**Issue by RaiModels** [Masuzu/ZooeyBot#932]
When using slave mode it works completely fine when I try to use it on the torch in 2-2. However, I tried to use it to farm the co-op mats in 1-3 (for feathers) and it gets stuck in calibrating. It works completely normally in stage 2-2 though, even though I'm doing the exact same things as before.

**Comment by Masuzu** [comment]
Hello,
Did you try with standard settings on the window where the calibration failed?
Otherwise a configuration parameter DebugCalibration was added to get more insights about the issue.

**Comment by RaiModels** [comment]
That fixed it, thanks!

**Comment by Masuzu** [comment]
Great!
