### ISSUE TITLE
Feature Request: Have a Train Mode

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/ZooeyBot#933]
It would be nice to have some sort of coop train mode where the bot just clicks on Start and then follows a script for like 30 times or until the train ends. This will help us in Ubaha normal train that takes 2 hours mindless train

**Comment by Masuzu** [comment]
Hello,
Maybe in the future this will be added. Meanwhile I advise to join only 185+ rooms which usually end in less than 45 minutes.

**Comment by breinjhel** [comment]
Can i reopen this i badly need this feature
