### ISSUE TITLE
[Scheduling mode] Zooey did not reroll summon

### ISSUE THREAD

**Issue by giauten** [Masuzu/ZooeyBot#934]
Hi, I'm currently using scheduling mode with this script for Agni
```
for i=1,3 do
  for i=1,8 do
	  SetLuaScript("Scripts/rotb.lua")
	  SetPreferredSummons("Hades, Celeste Omega_1, Bahamut")
	  RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/711191/1", 20, 1)
	  Assert4SymbolsPendantsBelow(30000)
	  SetPreferredSummons("Bonito_2")
  end
  SetPreferredSummons("Bonito_2")
  SetLuaScript("Scripts/rotb-agni.lua")
  RepeatQuest("http://game.granbluefantasy.jp/#quest/supporter/711201/1/0/5020", 30, 1)
  Assert4SymbolsPendantsBelow(30000)
end
```
with RerollSummonWhenNoPreferredSummonWasFound=true in [Summon]
When Agni was appearing and Bonito flb was not available, zooey will pickup Bahamut and enter the battle
Could you help me fix this please?
(I tried put the SetPreferredSummons("Bonito_2") while farming normal beast, but its still same)

**Comment by Masuzu** [comment]
This is addressed in v3.1.0
https://github.com/Masuzu/ZooeyBot/wiki/Customized-raid-scheduling#syntax
