### ISSUE TITLE
RequestBackup

### ISSUE THREAD

**Issue by gold-nugget** [Masuzu/ZooeyBot#935]
I have been trying to get this to work for xeno saggatarius. 
could someone give me the correct method of getting it to work?

**Comment by Zuser120000000** [comment]
RequestBackup()

By entering like this, the bot will do a relief, but after that the bot will stop closing the message of relief completion.
Is it the same symptom?

**Comment by gold-nugget** [comment]
Ah i was missing the () part.
yeah seems to be working now.

seems to not be able to close the pop-up after it requests backup. but, that is fine.

**Comment by gold-nugget** [comment]
If you have viramate.
enable this option.
https://puu.sh/BzHOb/de37972e3c.png

**Comment by Zuser120000000** [comment]
Yeah, I think that the solution is good.
As an improvement plan, it may be better to use Refresh () after sending help using Zooey bot 's Auto hide popup function.
