### ISSUE TITLE
Bot crashes when party is wiped

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/ZooeyBot#936]
For starters thank you very much for the requestBackup function being added.

So after doing that and my party gets wiped out the bot should wait until the raid is done then continue on next raids instead of crashing after the raid is done.

Thanks

**Comment by Masuzu** [comment]
Hello,
Your party is supposed to be strong enough not to wipe, that's the basic assumption and support for anything other than this was never intended from the beginning.
However, I took note of the crash.
