### ISSUE TITLE
Failing to select a summon sometimes

### ISSUE THREAD

**Issue by breinjhel** [Masuzu/ZooeyBot#944]
Sometimes the bot goes to Misc tab to select a summon and couldnt find it and then throws a captcha alert sounds.

It seems like the counting was off
The bot logged that it found a Griminir summon on position 15 in misc tab but when i counted it manually it was on position 16 that could be the reason why its failing

**Comment by breinjhel** [comment]
Whats more is it only happens on my laptop. I have the same setup on my PC at home with same settings (copied the whole folder from pc), browser and extension versions. They are both similar but the laptop is the only one with that kind of problem... What could be the issue here?

**Comment by Masuzu** [comment]
Acknowledged but dropped due to being an isolated case.

**Comment by breinjhel** [comment]
Hi Masuzu,

Im not quite sure how this is happening on my laptop consistently while on
my PC i dont see this issue and both are running same version of bot and
the browser. Can you enlighten me as to why this is happening
