### ISSUE TITLE
Bot not able to go to results page

### ISSUE THREAD

**Issue by Zerphane** [Masuzu/ZooeyBot#95]
Wanting to buy a license but I need to get this figured out first. I've checked my scaling and everything is set 100% as recommended. I've had the bot do a quest but when it tries to do the "results page" part the pointer is a fraction lower than where my address bar is so the bot just moves my mouse around but can never find what it's looking for. Unsure why it would do that with correct scaling. Sadly my test period will end before I will know if this issue can be resolved.

Thanks

**Comment by cobeng13** [comment]
Are you using viramate? If yes, try to disable auto end raids/quests

**Comment by Zerphane** [comment]
I have been using Viramate. But I do not have auto end raids & quest on.

**Comment by ErogeSeiyuu** [comment]
is your viramate bar horizontal or vertical? because last time I set it on horizontal, the same problem happened.

**Comment by Masuzu** [comment]
As @ErogeSeiyuu said

**Comment by Zerphane** [comment]
It was set to vertical, I did change something in Viramate that did fix the issue, I turned off the TEXT options, and it the bot started to work.
