### ISSUE TITLE
Chrome and chromium won't load some pages

### ISSUE THREAD

**Issue by SchismEternel** [Masuzu/ZooeyBot#950]
Well I'm not really sure where I'm supposed to present my problem so I'll do it here. Since 1-2 days ago both chromium and chrome have been unable to load certain websites or web pages including those I need to play gbf on the chrome/chromium browsers. I tried clearing my browser history, my cache, cookies, everything to no avail. I tried uninstalling chrome and chromium then downloading older builds, still didn't work. 

The game only works in those browsers if I start a new game. When I try to select "continue", I do get redirected to the authentification page but the game immediately freezes afterward no matter what I do, I can't select "mobage" and refreshing the page changes nothing. The app on my phone works just fine though and it's what I'am currently playing the game with. I asked a friend to send me a link to the authentification pages, thinking it might help me skirt the problem, but that didn't work either. Here's what I got: https://puu.sh/BLndB/57e348af61.png

Actually gbf isn't the only website I have a problem with on chrome. Since 2 days ago some website just won't load properly on chrome/chromium. I only get pages with texts and broken links and pictures Here's another example, the mobage website on chrome:

https://puu.sh/BLnh2/d563a58cbb.png

I have NONE of this problems using other web browsers (firefox). I haven't really changed anything on my computer in the last 2 days. Only thing which comes to mind is chrome updating itself, in which case I assume downloading an older build should've resolved the problem. Do you guys have any idea what may be the cause of this ?

**Comment by Masuzu** [comment]
Acknowledged but dropped due to being an isolated case.
