### ISSUE TITLE
Zooey not recognising AP, can't refill properly

### ISSUE THREAD

**Issue by lamewood** [Masuzu/ZooeyBot#951]
Hello Masuzu,
today i tried out Zooey again and i encountered the issue that the bot can't refill the AP accordingly, it happens sometimes at the beginning, but sometimes during the process.
The screenshot shows that the last quest was finished successfully, but then it couldn't refill it and got stuck
![image](https://user-images.githubusercontent.com/37760162/46967076-c5221700-d0af-11e8-9baa-9fda0e4295d1.png)

**Comment by Masuzu** [comment]
Hello,
This is most likely due to a misconfiguration of the quest AP cost depending on the mode you are using. (The Treasure Event mode especially requires explicitly the AP cost to be specified).
