### ISSUE TITLE
party_selection

### ISSUE THREAD

**Issue by lamewood** [Masuzu/ZooeyBot#956]
is there a possibility to set the party selection for the A and B side, because currently i'm using alot of teams from A and B side, but if the bot switches from one element to another, it wont register the A and B site and will choose the wrong team afterwards.
I can fix this problem for myself, so it's a low priority, but is there a setting for this?

**Comment by Masuzu** [comment]
Acknowledged but dropped due to not being really needed. There is also an old ticket mentioning this feature request.
