### ISSUE TITLE
Request: Add Raids that require treasure to Customized Scheduling

### ISSUE THREAD

**Issue by NxKai** [Masuzu/ZooeyBot#961]
I would have assumed there's an issue with this before, but it seems like not the case. With the request for backup function raids are now easier(???) to automate even more. Therefore I would like to request that raids that require treasure be added to customized scheduling. For now, It is for the best to assume the person has enough treasure to start the raid and to stop the bot when there's not enough required treasure. As for events that have two options of required treasure(summon raids), maybe assume only the left option is always used?(since no one realistically hosts using dragon scales) Keep up the good work man.

**Comment by Masuzu** [comment]
Acknowledged but dropped due to being redundant with the actual TreasureEvent mode.
