### ISSUE TITLE
the mouse won't select summon

### ISSUE THREAD

**Issue by niayyy** [Masuzu/ZooeyBot#963]
the mouse won't move to the KAGUYA summon and won't  click it, everything works fine before the gbf updates.

**Comment by niayyy** [comment]
i believe this is the same issue of #664

**Comment by niayyy** [comment]
btw dunno if my chrome version is related to the issue, my current chrome version is 70.0.3538.77 (Official Build) (64-bit)

**Comment by xerance** [comment]
https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation

https://puu.sh/BXTCc/ee7e0bab6d.png

![image](https://user-images.githubusercontent.com/16266200/48146362-168b8380-e2b5-11e8-8232-0ac743a06b6f.png)

**Comment by Masuzu** [comment]
All good,
I am using the last Chrome version fine (Version 68.0.3440.106)
