### ISSUE TITLE
ex not starting stuck 

### ISSUE THREAD

**Issue by pakulu** [Masuzu/ZooeyBot#964]
i see people have same issue in past? but no fix
mouse stop on ex menu
farmed vh well 
now i have many host mats and no time
please help
![image](https://user-images.githubusercontent.com/44754208/47972244-a43f5700-e09a-11e8-8a34-3f6b40f089a9.png)
here is where stop
sorry for everything orz

**Comment by MegaBlues** [comment]
Are you using the treasure mode? If so, are you using the proper syntax for EX and Impossible, noted in the .ini?

**Comment by MegaBlues** [comment]
Assuming that your event URL is correct, that should be fine. Also make sure that you disabled the other mode after enabling that one.

**Comment by GBFUSER1993** [comment]
Why don't you try the normal event mode? just insert the exact URL。 Try it

**Comment by pakulu** [comment]
yes url is correct, it goes to ex / imp screen but then dont choose anything.
normal event mode doesnt do anything with EX url, but works fine with vh and nm
treasureeventmode also work fine with vh but no ex orz

**Comment by GBFUSER1993** [comment]
I'm not sure, maybe the decode was not correct? In my memory doesn't goes wrong, using a notepad application to edit the ini file will make thing much easier

**Comment by niayyy** [comment]
i cant even farm vh ... are u guys using event mode to farm vh?

**Comment by pakulu** [comment]
Yes it farmed vh very good but no ex 
Now have many host material and little time to use

**Comment by zappky** [comment]
Maybe put your config file here,so we can see if your parameters have any thing wrong.

**Comment by pakulu** [comment]
# Use this special event mode to automate farming of events stages which require a certain number of items to be hosted, such as Guild War nightmare modes.
# Please refer to https://github.com/Masuzu/ZooeyBot/wiki/Treasure-Raid-Event-mode for more information
[TreasureEventMode]
Enabled=true
# Url of the event page. The URL of the June 2017 dark GW is given as an example.
TreasureEventUrl=http://game.granbluefantasy.jp/#event/treasureraid074
# Supported value are 'vh' (for "very hard") and 'ex' (for "extreme"), 'gw' (for the preliminary round and first day of "Unite and Fight" nightmare mode level 90), 'gw-day-2-nm-90' for the second and 3rd days of "Unite and Fight" nightmare mode level 90, 'gw-day-2-nm-95' for the second and 3rd days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-90' for the 4th and last days of "Unite and Fight" nightmare mode level 90, 'gw-day-4-nm-95' for the 4th and last days of "Unite and Fight" nightmare mode level 95, 'gw-day-4-nm-100' for the 4th and last days of "Unite and Fight" nightmare mode level 100
Difficulty=ex
# Action point cost of the quest you are trying to start
ActionPointCost=30
TreasureEventModeScript=water.lua

**Comment by pakulu** [comment]
I know event is now over but im still curious as to why it didnt work.
Missed my chance of getting a free spark and wasted pots farming VH.
Next time i will try to create something on the schedules see if i can manage. For the meantime im a bit disappointed, since i do not think such a good event will happen again

**Comment by pakulu** [comment]
Sorry for the font i just copy pasted hastily.
It might be something relates to encoding, i am using notepad++ and also have some issues with slime mode. It keeps refreshing way too hastily right before it loads completely.
Im assuming this might be the issue

**Comment by pakulu** [comment]
Since i dont want to open another thread ill show my slime issue here OTL
MaxPageLoadDelaiInMsBeforeRetry=25000
MaxTriggerDelayInMsBeforeFallback=55000
MaxResponseDelayInMs=20500
Even if i put crazy big numbers it still refreshes toó quuckly

**Comment by Masuzu** [comment]
Hello,
You should use the Event mode for this. Please refer to https://github.com/Masuzu/ZooeyBot/issues/971
