### ISSUE TITLE
Is there anyway to let zooey bot click the skill as usual?

### ISSUE THREAD

**Issue by GBFUSER1993** [Masuzu/ZooeyBot#965]
As default, zooey bot activate the skill after the previous skill was fully activated. However, this is different from our usual usage, which was clicking all skills at the first moment without waiting for the skill to activate. So I think the difference between the two may cause CY to detect BOT. So did anyone knows how to set the bot to click the skills without waiting for it?

**Comment by GBFUSER1993** [comment]
@nzstring
I think this might work
# If set to true, Zooey won't wait for a response from GBF servers after using a skill or summon or after attacking. Use this parameter if you know what you are doing, or else this may result in Zooey going out of control in case you use several skills each turn. The main use of this parameter is to make skill usage slightly more responsive during slime blasting.
DoNotWaitForServerResponse=false

However there's no such option in the current version of ini

**Comment by Masuzu** [comment]
Hello,
Both methods (stacking up skills) and waiting for animations to complete are both human-like behaviour so this feature would not really needed right now. In case you might be worried, you can add your own random additional wait time in your scripts (http://lua-users.org/wiki/MathLibraryTutorial, math.random)
