### ISSUE TITLE
Bot Crash before collecting rewards in Proving Grounds

### ISSUE THREAD

**Issue by i-Grey** [Masuzu/ZooeyBot#967]
There are 2 problems which I've seen by testing the Proving Grounds Event.

1. Bot won't collect the treasure rewards after finish last battle which will lead in to infinite loop in Summon Selection Page. (Critical problem)
2. Bot crash before 2nd Battle start. It seems to be a problem about detecting "START" button. It might solved by adding some delay to detect in that page of something else.

Hope you fix this soon

**Comment by Rkdheishins** [comment]
i cant even get it to the stage to fight, would u mind sharing me your configuration settings?

**Comment by Masuzu** [comment]
Unfortunately this will have to wait until the next rerun of such an event >.<
