### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by samuelljacksonn** [Masuzu/ZooeyBot#969]
When starting zooeybot, the serial number file gets overwritten with something thats different from the one the generator provides. I've re-installed, re-ran the serial generator and compared with account management page to make sure its the same, re-downloaded key file, but its still showing me as not having a license. The serial number file keeps getting overwritten on starting zooeybot.

**Comment by ngocin** [comment]
I got this problem long time ago. All solved after i restart my computer

**Comment by Masuzu** [comment]
All good then!
