### ISSUE TITLE
Summon

### ISSUE THREAD

**Issue by niayyy** [Masuzu/ZooeyBot#970]
actually that happened days ago #963 but no one helped me. Someone said it is related to Chrome version but my friend works fine with the latest Chrome ver so I planned to stop paying the bot .. 
but I decide to give it a try again and have just paid .. but summon is not selected and it stops at the summon selection page just like #664 but my resolutions are all set to Standard and the side bar are hidden.

![1](https://user-images.githubusercontent.com/43200136/48635136-4861c000-ea02-11e8-948f-63763d8b5f0b.png)

**Comment by niayyy** [comment]
here's my setting

**Comment by niayyy** [comment]
https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation

and the setting listed in the above page has been set already, the bot worked fine like 2 weeks ago, it just went wrong suddenly, i haven't made any changes to the settings

**Comment by xerance** [comment]
event mode works just fine for ex mode

**Comment by niayyy** [comment]
thanks @xerance changed to event mode but still stuck at summon page the mouse just wont move

![untitled](https://user-images.githubusercontent.com/43200136/48653955-da3ded00-ea43-11e8-925c-8ade534e38bb.png)

**Comment by Masuzu** [comment]
Hello,
Please do not use Viramate compact summon view and you should be fine!
