### ISSUE TITLE
New bot detection?

### ISSUE THREAD

**Issue by rockysilver** [Masuzu/ZooeyBot#972]
Can zooeybot detect this one? I never see this before.

https://imgur.com/a/MtAV4h4

**Comment by MegaBlues** [comment]
Doesn't it already play a warning sound for the Verify button itself? I don't see why this would stop it at all.

**Comment by ariaanaa** [comment]
so it still safe right? the bot still stop when this new verify appear?

**Comment by Sacrivisor** [comment]
U need to FOCUS ON the RED WORDS

Please do start a battle after this verification

It’s mean U NEED TO FINISH THE BATTLE WITHOUT BOT ONCE!!!

Cannot restart ur bot without manually finish the battle first

**Comment by ariaanaa** [comment]
that why i'm asking is the bot can detect it and play a sound with this new verification thing, so we can click it manually.

the old verification that u need to clicking 1 button it don't need to battle manually for once, after u click the verify button, it back to normal summon page and I still safe to run the bot again. i hope it still the same

**Comment by jinoga** [comment]
![image](https://user-images.githubusercontent.com/45120465/48660133-39751f00-ea8f-11e8-9fb7-4f3ca43d64d7.png)

bot detection on skill select

**Comment by zooeyjapan** [comment]
> Can zooeybot detect this one? I never see this before.
> 
> https://imgur.com/a/MtAV4h4

This one got detected no problem.
obviously check the button and do a battle manually after it.

The one posted by jinoga -> not sure, not seen it, can you confirm if that was detected?

**Comment by MegaBlues** [comment]
> bot detection on skill select?

I'm positive this was a joke.

**Comment by Masuzu** [comment]
Hello,
Nothing changed so far and the sound alert will trigger in every existing scenario where you'd have to perform a manual verification check.

[Deleted some post to avoid spreading false informatio as there is no reason to be worried for now].
