### ISSUE TITLE
Bot doesn't work on Chrome but still work on Chromium

### ISSUE THREAD

**Issue by ngocin** [Masuzu/ZooeyBot#973]
My Chrome version is  64.0.3282.186
My Chromium version is 66.0.3359.181
When i use Chromium, bot run smoothly , but when i move to Chrome , it stuck here 
![image](https://user-images.githubusercontent.com/30687323/48655818-d499d480-ea4e-11e8-9eba-128db349ac18.png)
It happen with both ZooeyBot and Sarasa Bot 
Also , both Chrome and Chromium run the same file, same script

**Comment by Masuzu** [comment]
Hello,
You may want to set the DebugCalibration parameter under the Debug section to true.
I am using Chrome Version 68.0.3440.106 with no issue.
