### ISSUE TITLE
Host NM 95 on GW day 1

### ISSUE THREAD

**Issue by ariaanaa** [Masuzu/ZooeyBot#975]
Since there NM 95 on day 1, how can you host NM 95? 
I always got wrong parameter on treasure mode difficulty. Even using 'gw' parsmeter the bot didn't host NM 90. Did anyone have same problem?

Thank you

**Comment by niayyy** [comment]
same here, using 'gw" in treasure mode for NM90 doesnt working

**Comment by Masuzu** [comment]
Hello,
The description is indeed deprecated since the GW changes where there are only 4 rounds. Thank you for pointing this out.
In any case everything still hold and you should use:
Difficulty=gw-day-2-nm-90
or 
Difficulty=gw-day-2-nm-95
for the first 2 rounds.
