### ISSUE TITLE
Does zooeybot detect this particular verification?

### ISSUE THREAD

**Issue by csyeul** [Masuzu/ZooeyBot#976]
![image](https://user-images.githubusercontent.com/41708504/48730494-89c3bc80-ec08-11e8-8293-90e4566f1777.png)

I ran into this and my summon is set to select shiva, I was doing it manually and not running bot at a time so I clicked verify. But if I was running the bot, would it have notified me? since the bot mechanism works that if there's shiva summon, it clicks and runs it through battle. I think this verification is relatively new. Anyone know?

**Comment by Chololoco13** [comment]
Yes, zooey can detect it without problems.
Google translate-

**Comment by csyeul** [comment]
Awesome, gonna close this then.
