### ISSUE TITLE
please How to use Ninja's Mark skill

### ISSUE THREAD

**Issue by matp07289** [Masuzu/ZooeyBot#977]
please How to use Ninja's Mark skill,,,

![696d67_3231303330315f6b745f315f30312e706e67](https://user-images.githubusercontent.com/40632392/48780025-3b9fdd80-ed1c-11e8-8713-54f196eb4d90.png)

https://www.google.co.jp/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjssaelkOPeAhXRM94KHVK0AyEQjRx6BAgBEAU&url=https%3A%2F%2Fkamigame.jp%2F%25E3%2582%25B0%25E3%2583%25A9%25E3%2583%2596%25E3%2583%25AB%2F%25E3%2582%25B2%25E3%2583%25BC%25E3%2583%25A0%25E7%259F%25A5%25E8%25AD%2598%2F%25E5%25BF%258D%25E8%25A1%2593.html&psig=AOvVaw3BWklCB8WeBp-vciVDtGjQ&ust=1542808663446579

**Comment by hebrew** [comment]
Runeslayer's skill "Runeweaving" is also the same specification.
I also want to know.

**Comment by Masuzu** [comment]
Hello,
I will implement this feature as soon as I can. Thank you for reporting this.
