### ISSUE TITLE
Zooeybot ban wave?

### ISSUE THREAD

**Issue by ericli51** [Masuzu/ZooeyBot#978]
It seems like a number of zooey-bot users all had their account suspended at around the same time.

I haven't missed any verifications, but my account was suspended about an hour ago with no prior warning.

It seems like Cygames has a new method for determining zooey botters? Either way, I would say using Zooeybot during GW might be risky. Even if you pass all the Verifications and captchas there still seems to be a way for you to be banned.

**Comment by Nassy1121** [comment]
Does anyone are banned?
I've not seen any problem today.

**Comment by breinjhel** [comment]
Thats scary af. Dont have any problem today but im keeping a close eye on my stuff

**Comment by breinjhel** [comment]
How many do you know got banned? Any specific behavior they are doing that might cause it?

**Comment by Masuzu** [comment]
Hello,
These is fake news and spreading misinformation is something I would not condone.
However, always stay alert and you will stay safe.
