### ISSUE TITLE
multi-line comment

### ISSUE THREAD

**Issue by gold-nugget** [Masuzu/ZooeyBot#979]
Hello, 
how can i use multi-line comments in a script.
preferably custom scheduling.

this is what i have in mind. it works if i manually comment them out. but it would be faster if i can do it with lesser characters. anyone has any idea how i can do that?
![2018-11-24_15-58-37](https://user-images.githubusercontent.com/43519535/48968539-f4f30180-f001-11e8-9d7e-cf6d12281e8c.png)

**Comment by gold-nugget** [comment]
ok i found a mini work around
use
 --[[
script
]]
 to comment lines out


and to return to readable form just delete the --[[ and change ]] to --]]

that seems to work with it so far

**Comment by Masuzu** [comment]
Hello,
That is the correct way in Lua indeed, as seen here https://www.lua.org/pil/1.3.html
