### ISSUE TITLE
New type of verify

### ISSUE THREAD

**Issue by ngocin** [Masuzu/ZooeyBot#980]
There is a new kind of verify
There's still have red verify button 
But instead of only one summon, they listed all summons.
I wonder if bot can detect this, or anyone met that while using bot can confirm please?

**Comment by ngocin** [comment]
Just got one after post this lol. confirm it can detect the new verify

**Comment by Masuzu** [comment]
Thanks for following up this quickly!
I will leave this issue open for now.

**Comment by shigu55** [comment]
Hi Masuzu
Although it can be detected by English setting, it seems that it can not be detected by Japanese setting.

**Comment by Masuzu** [comment]
Hello @shigu55 ,
Thank you a lot for pointing this out. I will work on that today and/or tomorrow.

**Comment by ngocin** [comment]
@Masuzu  sorry for talking about another issue in this thread but even i set UseViramate = true and turn on Viramate's hotkeys. bot still acting like no Viramate ( click on character then click on skills instead of using hotkey) , i try to redownload bot again, delete and download viramate again but it's still like that

**Comment by omieqqe** [comment]
So, it's still safe if we using the English configuration right?
Thank you.

**Comment by Masuzu** [comment]
@ngocin I am not sure what went wrong with your setup but nothing was changed regarding Viramate support and thus the feature still works as intended.

Both the Japanese and English versions are now safe with regards to the new mode thanks to patches introduced in v3.3.1 for Zooey Bot and v2.1.1 in Sarasa Bot.

Happy farming!
