### ISSUE TITLE
Event Halo Regarded as 0 AP

### ISSUE THREAD

**Issue by MegaBlues** [Masuzu/ZooeyBot#986]
Now that the event halo can be automated, I noticed that it's always regarded as 0 AP by Zooeybot, which prevents AP pots from automatically being used.

**Comment by Masuzu** [comment]
Isn't that always the case?
Doesn't the raid ID change after 30/300 clears?

**Comment by minotopo2000** [comment]
It stays at the same ID (at least regarding URL)

**Comment by MegaBlues** [comment]
The ID doesn't change, but the quest is still thought of as 0 AP by Zooeybot. It's also regarded as 0 AP by Viramate, if that helps.

**Comment by Masuzu** [comment]
Ah I see, thank you. Something will have to be done about it then.

**Comment by hebrew** [comment]
"Campaign exclusive quest" will end in the remaining 8 hours, but will you be able to fix "Zooey bot" in time?

**Comment by MegaBlues** [comment]
I can't believe it took so long to think of this, but using custom raid scheduling to manually set the AP cost will let you avoid the error.
