### ISSUE TITLE
License Activation Failure

### ISSUE THREAD

**Issue by Lurline** [Masuzu/ZooeyBot#988]
I keep getting a failure to activate license error when trying to renew my license. I already sent an email about that almost 10 days ago and no reply. I'd like to be able to use Zooey before Fenrir ends...

**Comment by Masuzu** [comment]
Hello Lurline,
I apologize for the delay in the reply. I provided you a brief report of the case with the information I had and gave you a few extra days so that you can farm Cerberus and Fenrir in the meantime while hopefully you sort out the situation.
Good luck!

**Comment by Lurline** [comment]
Thank you very much! I will look into the solution you provided and try to have that sorted out asap! Many thanks for the extra days as well! :D

**Comment by Lurline** [comment]
@Masuzu It worked! I was able to renew my license again! Many thanks!
