### ISSUE TITLE
fail to find script

### ISSUE THREAD

**Issue by yuzurihaz** [Masuzu/ZooeyBot#989]
how to fix it. i place my script at d/zooeybot/script but it wont work

**Comment by JeremyMerkur** [comment]
And how do you reference it in your Zooey.init file? It should be something like:
LuaScript=script/<SCRIPT NAME>.lua

**Comment by yuzurihaz** [comment]
> And how do you reference it in your Zooey.init file? It should be something like:
> LuaScript=script/<SCRIPT NAME>.lua
i forgot to set it to En now i already fix it
