### ISSUE TITLE
Can't download Zooeybot on Dropbox

### ISSUE THREAD

**Issue by MagCat** [Masuzu/ZooeyBot#99]
When I open the dropbox link, it keeps telling me that the zooeybot folder does not exist for some reasons. I don't use dropbox a lot so I don't know what is the go around for this. I also don't know how to contact Masuzu personally either, so my apology if I'm not supposed to start a new thread. The description of Masuzu's post doesn't say anything about he pulled the link off either.

**Comment by spongebear** [comment]
yea same.

**Comment by forte87** [comment]
I don't either

**Comment by i-Grey** [comment]
You can download it directly from main site. https://poker-bot.azurewebsites.net/ZooeyBot/en/Manage

**Comment by MagCat** [comment]
@i-Grey I can't download from the website either. For some reasons there the Download button just gives me nothing on clicking.

**Comment by whyiseveryusernamealreadytaken** [comment]
It's because the url is wrong. I inspected the download button with dev tools, and the url starts with hhttp:// instead of http://

Use this link to download it.
https://www.dropbox.com/s/8q05h8008vh7ni3/zooey-bot-v1.9.7.zip?dl=1

**Comment by Masuzu** [comment]
It's fixed now.
