### ISSUE TITLE
Fail to Retreat During Summon Refresh

### ISSUE THREAD

**Issue by JeremyMerkur** [Masuzu/ZooeyBot#990]
![screenshot 2018-12-22 03 47 02](https://user-images.githubusercontent.com/1916550/50372527-c84cee00-059d-11e9-8c5b-798351ecb1e7.png)
Sometimes, when retreating from the Trial during a summon refresh, the second retreat window takes a little longer to pop up, so Zooeybot misses the button because it clicks too early. Would it be possible to add a config parameter to the init file that specifies a wait time here? Then I could set a longer time to avoid this problem (without interfering with other users).

**Comment by JeremyMerkur** [comment]
See, I am 99.9% sure that's not the case. I have my MaxResponseDelayInMs set to 8500, and this bug happens in under two seconds. It clicks the first retreat button, and then moves the mouse to where the resume button is while the screen transitions to the second popup:

![screenshot 2018-12-22 03 47 26](https://user-images.githubusercontent.com/1916550/50383171-50a1c080-067c-11e9-9133-574f520b2278.png)

If it's waiting for the second popup, why does it move the mouse so quickly? If it's searching for the retreat button, why can't it find the clearly visible one right there? 

As near as I can guess, it immediately starts looking for something as soon as it presses the first retreat button, and if there's enough delay before the first popup disappears, it mistakenly identifies the resume button as something it should press, tries to press it, and gets stuck either because it can't press the button as the second popup replaces the first, and so ends up in an inconsistent state, or because it shouldn't be pressing that button at all so the mere act of trying means it's gone into an inconsistent state.

**Comment by Masuzu** [comment]
Thank you for those details.
This will be addressed during the week-end of January 5, 2019 as unfortunately I don't have access to a workstation right now.

**Comment by Masuzu** [comment]
Version 3.3.3 introduces an additional delay before confirming the retreat action: https://gbtools.azurewebsites.net/ZooeyBot/en/Home/PatchNotes#3-3-3

**Comment by JeremyMerkur** [comment]
Thanks, seems to work.
