### ISSUE TITLE
Stuck in Home Page

### ISSUE THREAD

**Issue by Evilplaynice** [Masuzu/ZooeyBot#991]
I put the bot to farm the Slime Trial, but in some moments happens some bug and the bot ends up getting stuck in the home page and stop repeating the mission, I wonder if there is something I can do to when he gets stuck on the home page

**Comment by ravenknit** [comment]
I have the exact same problem - but it's for the event halo. Zoeybot loads the script, then goes back to Home. This is the exact same script I was using just last week to do the event halo, so I don't think it's a script problem
